### ISSUE TITLE
Request resend error "IO error in sending request" 

### ISSUE THREAD

**Issue by vskram21** [zaproxy/zaproxy#1710]
I am getting an error message "IO error in sending request" when I try to use Resend request.

I have changed the POST to GET and moved few parameters in POST to GET.

I am using ZAP version _D-2015-07-14.

**Comment by thc202** [comment]
Would you mind checking the log file to see what is the error? (file zap.log located in ZAP's default directory or the directory manually specified [1]).

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by vskram21** [comment]
Please find the error messages below,

WARN  ManualRequestEditorDialog - IO error in sending request.
java.io.IOException: IO error in sending request.
	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:112)
	at org.parosproxy.paros.extension.manualrequest.ManualRequestEditorDialog$3.run(ManualRequestEditorDialog.java:207)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.commons.httpclient.CircularRedirectException: Circular redirect to 'http://example.com'
	at org.apache.commons.httpclient.HttpMethodDirector.processRedirectResponse(HttpMethodDirector.java:690)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:83)
	... 2 more


I setup fiddler between ZAP and the application to find out if the application is receiving any response.
It turns out a response was received with a 302 and ZAP is not displaying the same.

Also, I have few error messages in my log file not sure if those are actual timeouts (did this without the fiddler setup).

WARN  ManualRequestEditorDialog - IO error in sending request.
java.io.IOException: IO error in sending request.
	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:112)
	at org.parosproxy.paros.extension.manualrequest.ManualRequestEditorDialog$3.run(ManualRequestEditorDialog.java:207)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:2032)
	at org.zaproxy.zap.ZapGetMethod.readResponse(ZapGetMethod.java:88)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1147)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:450)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:83)
	... 2 more

**Comment by kingthorin** [comment]
When that happens are you able to proxy through ZAP at roughly the same time?

**Comment by thc202** [comment]
The circular redirect exception happens when the server is redirecting to same URL in a redirection chain (e.g. <http://example.com> > <http://example.com> or <http://example.com/A> > <http://example.com/B> > <http://example.com/A>).
It should be possible to configure that.

Regarding the read time out, which value do you have set in [Connection options](https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsConnection#timeout-in-seconds)?

**Comment by vskram21** [comment]
@kingthorin 
I was able to proxy during that time and the connectivity was working fine.
The average RTT was about 5.55 s (based on the active scan that was running).
As I was getting timeout error. I paused the scan for a while and even then I was getting timeout error messages. Normal request going through the browsers has no issues they had a RTT of not more than 2.5s 
 
Later, I set fiddler between zap and the application and I noticed that there is a response with 302 that is been received but ZAP was displaying a IO error.

@thc202 
timeout value is set to 30 sec.

The fiddler response didn't take take more than 5 sec. It seems like ZAP is displaying IO error when 302 response is received.

**Comment by vskram21** [comment]
@thc202 
I see that circular redirect is happening. Is there an option to specify the number of redirects to follow and to display the final page after all the redirects (even if it is a 302).

**Comment by thc202** [comment]
No, not yet.

**Comment by vskram21** [comment]
Is there an option to specify not to follow redirects (in resend) rather display the response itself.

**Comment by thc202** [comment]
Yes, you need to deselect the "Follow redirect" option. [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsResend#-follow-redirect

**Comment by vskram21** [comment]
Thanks for highlighting.

**Comment by kingthorin** [comment]
Can this issue be closed?

**Comment by vskram21** [comment]
Sure.
