### ISSUE TITLE
ZAP hanging on Windows

### ISSUE THREAD

**Issue by inf1320** [zaproxy/zaproxy#1759]
I am having this constant issue wit ZAP on Windows whenever there's a lot of processing going on. For instance when loading a Dirbuster list into fuzzing or while actively scanning a relatively big application.
I tried to reduce the number of concurrent threads and increase the JVM memory but I'm still having the same issue even though i'm running it on a powerful machine.

Does that happen on a Linux environment as well?

**Comment by psiinon** [comment]
Are there any errors in the zap.log file?
https://github.com/zaproxy/zaproxy/wiki/FAQhelp

Cheers,
Simon

**Comment by inf1320** [comment]
I am getting terrors such as the following in the logs:

[ZAP-ProxyThread-552] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-ProxyThread-552"
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by kingthorin** [comment]
How much RAM does the system have?
Do you have orphaned/crashed Java processes?

**Comment by thc202** [comment]
Also, what ZAP version are you using?

**Comment by gregorycaswell** [comment]
Haven't narrowed down to exactly what, but appears reproducible doing a fuzz with any number of threads using fuzzdb-1.09.  Weirdly enough, doesn't reproduce using jbrofuzz lists.  Normal memory usage of the Java process hovers around 2.5 GB, but immediately ramps up to 3.5 GB once the fuzz begins and starts to choke, eventually crashing.  If you stop and clear the fuzz results prior to the crash, it recovers fine.  Machine has 16 GB of memory available, nothing else other than a couple browsers running.  Running newest 2.4.1 of ZAP.  

Snippet from logs:

2015-08-18 10:04:52,774 INFO  HttpFuzzer - Fuzzer started...
2015-08-18 10:05:09,766 INFO  ENGINE - Checkpoint start
2015-08-18 10:05:09,766 INFO  ENGINE - checkpointClose start
2015-08-18 10:05:11,682 INFO  ENGINE - dataFileCache commit start
2015-08-18 10:05:24,393 INFO  ENGINE - checkpointClose end
2015-08-18 10:05:27,895 INFO  ENGINE - Checkpoint end
2015-08-18 10:05:52,969 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerTaskSubmitter-2"
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:112)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.messagelocations.TextHttpMessageLocationReplacer$Replacer.<init>(TextHttpMessageLocationReplacer.java:139)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.messagelocations.TextHttpMessageLocationReplacer$Replacer.<init>(TextHttpMessageLocationReplacer.java:133)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.messagelocations.TextHttpMessageLocationReplacer.replace(TextHttpMessageLocationReplacer.java:79)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.messagelocations.TextHttpMessageLocationReplacer.replace(TextHttpMessageLocationReplacer.java:32)
	at org.zaproxy.zap.extension.fuzz.messagelocations.MultipleMessageLocationsDepthFirstReplacer.next(MultipleMessageLocationsDepthFirstReplacer.java:125)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzer$FuzzerTaskSubmitter.submitTasks(AbstractFuzzer.java:557)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzer$FuzzerTaskSubmitter.run(AbstractFuzzer.java:522)
2015-08-18 10:05:58,853 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-3"
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutput	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
Stream.grow(ByteArrayOutputStream.java:113)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
	at org.apache.commons.httpclient.HttpMethodBase.getResponseBody(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.sendMessage(HttpFuzzerTask.java:84)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:52)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:32)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzerTask.run(AbstractFuzzerTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-08-18 10:06:04,394 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-11"
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.parosproxy.paros.network.HttpBody.setBody(Unknown Source)
	at org.parosproxy.paros.network.HttpMessage.setRequestBody(Unknown Source)
	at org.parosproxy.paros.network.HttpMessage.<init>(Unknown Source)
	at org.parosproxy.paros.db.RecordHistory.<init>(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.build(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.read(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)
	at org.parosproxy.paros.model.HistoryReference.<init>(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.ui.HttpFuzzerResultsTableModel.addResult(HttpFuzzerResultsTableModel.java:88)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzer.fuzzResultAvailable(HttpFuzzer.java:136)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:64)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:32)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzerTask.run(AbstractFuzzerTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2015-08-18 10:06:09,661 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-1"
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
	at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:496)
	at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1023)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:960)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
	at javax.crypto.Cipher.doFinal(Cipher.java:2333)
	at sun.security.ssl.CipherBox.decrypt(CipherBox.java:461)
	at sun.security.ssl.InputRecord.decrypt(InputRecord.java:172)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:996)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:911)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:182)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:108)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.httpclient.AutoCloseInputStream.read(AutoCloseInputStream.java:127)
	at org.apache.commons.httpclient.HttpMethodBase.getResponseBody(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.sendMessage(HttpFuzzerTask.java:84)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:52)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzerTask.runImpl(HttpFuzzerTask.java:32)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzerTask.run(AbstractFuzzerTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2015-08-18 10:06:14,772 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-PassiveScanner"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:20,476 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-9"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:24,131 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-6"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:28,765 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-4"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:33,405 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-7"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:38,057 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-2"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:42,688 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-12"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:48,083 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-14"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:06:54,788 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-17"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:00,903 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-19"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:04,362 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-10"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:08,034 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-25"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:14,174 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-22"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:17,780 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-13"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:26,529 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-21"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:23,988 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-8"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:38,695 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-20"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:37,641 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-29"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:44,522 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-31"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:42,493 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-18"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:53,384 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-15"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:49,117 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-33"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:49,115 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-26"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:07:48,094 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-27"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:08:00,165 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-5"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:08:09,003 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-23"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:08:01,197 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-37"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:08:09,003 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-16"
java.lang.OutOfMemoryError: GC overhead limit exceeded
2015-08-18 10:08:14,351 ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-FuzzerThreadPool-2-thread-34"
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by thc202** [comment]
Thanks! The problem is that the fuzz tasks are being created immediately after starting the fuzz process instead of just when required. Will take care of that very soon.

**Comment by thc202** [comment]
The active scanner should no longer have (evident) memory problems (as per #1890 and #1974).
An issue has been raised to fix the issue of the fuzzer (#2051).

Closing as insufficient evidence, though, as it might not be the same issues that you were seeing. If the issue happens again with latest release(s) either comment here (or in the users mailing list [1]) or raise a new issue.
Thank you.

[1] https://groups.google.com/group/zaproxy-users
