### ISSUE TITLE
Unable to initialize home directory! xml/config.xml (No such file or directory)

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#1760]
Issue reported in OWASP ZAP Developer Group: https://groups.google.com/d/topic/zaproxy-develop/6ZVJ0rytr9w/discussion

Steps to reproduce the issue:
1. Run ZAP using the jar from a working directory other than installation directory, for example:
java -jar path/to/ZAP_2.4.1/zap-2.4.1.jar -installdir path/to/ZAP_2.4.1
2. Note the output:
Unable to initialize home directory! xml/config.xml (No such file or directory)
java.io.FileNotFoundException: xml/config.xml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.parosproxy.paros.model.FileCopier.copyLegacy(Unknown Source)
        at org.parosproxy.paros.model.FileCopier.copy(Unknown Source)
        at org.parosproxy.paros.Constant.initializeFilesAndDirectories(Unknown Source)
        at org.parosproxy.paros.Constant.<init>(Unknown Source)
        at org.parosproxy.paros.Constant.createInstance(Unknown Source)
        at org.parosproxy.paros.Constant.getInstance(Unknown Source)
        at org.zaproxy.zap.ZAP.main(Unknown Source)

Remarks:
The default directory [1] should not exist.

ZAP Version:
Versions >= 2.3.1 (older versions might be affected).

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by thc202** [comment]
Fixed in @abc8adae3a3b58117b88489e3fbc3ce0f4b736f4
