### ISSUE TITLE
Trying to run a ruby script with owasp_zap gem in linux os. Its throws "Can't connect to X11 window server using 'localhost:0.0'"

### ISSUE THREAD

**Issue by ambikashri** [zaproxy/zaproxy#1779]
I am using the below code in ruby

#using owasp gem
require 'owasp_zap'

include OwaspZap

z = Zap.new :base=>'http://127.0.0.1:8082'
z = Zap.new :target=>'http://www.xyz.com' # create new Zap instance with default params 

z = Zap.new :target=>'http://www.xeran.com'
z = Zap.new :output=>'logfile.txt' # it will log the stdout log from Zap Proxy to a file

z.start # start interactive
z.start #:daemon=>true # start in daemon mode
z.scanner
z.shutdown # stop the proxy

On running the ruby script, I get the below error
Found Java version 1.7.0_65
Available memory:  994 MB
Setting jvm heap size: -Xmx256m
else
0 [main] INFO org.zaproxy.zap.ZAP  - OWASP ZAP 2.4.1 started.
23 [main] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "main"
java.lang.InternalError: Can't connect to X11 window server using 'localhost:0.0' as the value of the DISPLAY variable.

I am ./zap.sh in daemon mode.
./zap.sh -port 8082 -daemon -config api.disablekey=true -last_scan_report /root/report.xml

**Comment by psiinon** [comment]
Is there a stack trace in the zap.log file?
This can be found in the default user directory, unless you've used the '-dir' command line parameter: https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by ambikashri** [comment]
Below is the last few lines of log

2015-08-11 16:35:50,281 [ZAP-daemon] INFO  ExtensionLoader - Initializing The Online menu links
2015-08-11 16:40:21,108 [Thread-4] INFO  ENGINE - dataFileCache commit start
2015-08-11 16:40:21,119 [Thread-4] INFO  ENGINE - Database closed
2015-08-11 16:40:21,246 [Thread-4] INFO  CoreAPI - OWASP ZAP 2.4.1 terminated.
2015-08-11 16:40:23,284 [main ] INFO  ZAP - OWASP ZAP 2.4.1 started.
2015-08-11 16:40:23,283 [main ] INFO  ZAP - OWASP ZAP 2.4.1 started.
2015-08-11 16:40:23,305 [main ] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "main"
java.lang.InternalError: Can't connect to X11 window server using 'localhost:0.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at java.awt.Toolkit$2.run(Toolkit.java:869)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
        at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:608)
        at org.zaproxy.zap.ZAP.run(Unknown Source)
        at org.zaproxy.zap.ZAP.main(Unknown Source)
2015-08-11 16:40:23,306 [main ] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "main"
java.lang.InternalError: Can't connect to X11 window server using 'localhost:0.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at java.awt.Toolkit$2.run(Toolkit.java:869)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
        at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:608)
        at org.zaproxy.zap.ZAP.run(Unknown Source)
        at org.zaproxy.zap.ZAP.main(Unknown Source)

**Comment by kingthorin** [comment]
You seem to have commented out daemon mode:
```
z.start # start interactive
z.start #:daemon=>true # start in daemon mode
```

If you started interactive then I believe you do need DISPLAY set, also trying to start twice might be causing you issues. 

I assume you're copying from here (https://github.com/vpereira/owasp_zap/blob/master/README.md) or somewhere similar, not all pieces are simultaneously applicable, usage provides examples. [Also you're use of z.scanner seems incorrect. z.scan would run a scan while z.scanner is used to configure the scanner....from the quick reading I did anyway]

**Comment by ambikashri** [comment]
So if i change it to z.scan it throws the below error
Hello World
"1"
"http://127.0.0.1:8082"
"http://127.0.0.1:8082"
"2"
"http://127.0.0.1:8082"
"3"
:zap
"http://127.0.0.1:8082"
"4"
owasp_run.rb:21:in `<main>': undefined method `scan' for #<OwaspZap::Zap:0x000000020e0838> (NoMethodError)

Also I changed because in lib/owasp_zap , there is no scan.rb but scanner.rb

module OwaspZap
    # TODO 
    # maybe create a policy class as well
    class Scanner

**Comment by ambikashri** [comment]
And after uncommenting

#z.start # start interactive
#
# TODO
# document it further :) 
z.start :daemon=>true # start in daemon mode
z.scanner
z.shutdown # stop the proxy
~

I still get the display error

root@vdeck:~# cat logfile.txt 
Found Java version 1.7.0_65
Available memory:  994 MB
Setting jvm heap size: -Xmx256m
else
0 [main] INFO org.zaproxy.zap.ZAP  - OWASP ZAP 2.4.1 started.
740 [main] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open start
748 [main] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open end
1334 [main] INFO org.parosproxy.paros.network.SSLConnector  - Reading supported SSL/TLS protocols...
1334 [main] INFO org.parosproxy.paros.network.SSLConnector  - Using a SSLEngine...
6802 [main] INFO org.parosproxy.paros.network.SSLConnector  - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
6884 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate  - Unsafe SSL renegotiation disabled.
7090 [main] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "main"
java.lang.InternalError: Can't connect to X11 window server using 'localhost:0.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:190)
        at java.awt.Toolkit$2.run(Toolkit.java:869)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
        at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:1934)
        at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:752)
        at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:434)
        at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
        at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1589)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:536)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:576)
        at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1345)
        at javax.swing.UIManager.initialize(UIManager.java:1455)
        at javax.swing.UIManager.maybeInitialize(UIManager.java:1422)
        at javax.swing.UIManager.getUI(UIManager.java:1003)
        at javax.swing.JLabel.updateUI(JLabel.java:274)
        at javax.swing.JLabel.<init>(JLabel.java:163)
        at javax.swing.JLabel.<init>(JLabel.java:193)
        at org.zaproxy.zap.utils.FontUtils.getDefaultFont(Unknown Source)
        at org.zaproxy.zap.utils.FontUtils.setDefaultFont(Unknown Source)
        at org.zaproxy.zap.ZAP.run(Unknown Source)
        at org.zaproxy.zap.ZAP.main(Unknown Source)

**Comment by ambikashri** [comment]
So now I have edited the code as follows

require 'owasp_zap'
include OwaspZap

puts "Hello World"
p 'Base initialization'
z = Zap.new :base=>'http://127.0.0.1:8082'
p 'Target initiliazation'
z = Zap.new :target=>'http://www.xeran.com' # create new Zap instance with default params 
p'zap bin initialization'
z = Zap.new :zap=>"/root/ZAP/ZAP_2.4.1/zap.sh"
p 'Output initialization'
z = Zap.new :output=>'logfile.txt' # it will log the stdout log from Zap Proxy to a file
p z
p 'Starting zap in daemon mode'
z.start :daemon=>true # start in daemon mode
p 'Starting attack'
a = Attack.new
a = Attack.new :target =>'http://www.xyz.com'
a.start
z.shutdown # stop the proxy

And I get the below output

Hello World
"Base initialization"
"Target initiliazation"
"zap bin initialization"
"Output initialization"
#<OwaspZap::Zap:0x0000000160b160 @base="http://127.0.0.1:8082", @target="http://www.xyz.com", @zap_bin="/root/ZAP/ZAP_2.4.1/zap.sh", @output="logfile.txt">
"Starting zap in daemon mode"
"Starting attack"
"======================="
#<Addressable::URI:0xb05590 URI:/JSON/ascan/action/scan/>
"Attack started"
{:zapapiformat=>"JSON", :url=>"http://www.xyz.com"}
nil
/usr/local/lib/ruby/1.9.1/net/http.rb:1405:in `addr_port': undefined method `+' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1339:in `begin_transport'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1315:in `transport_request'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:1293:in `request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:328:in `net_http_do_request'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:500:in `block in transmit'
        from /usr/local/lib/ruby/1.9.1/net/http.rb:745:in `start'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:494:in `transmit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:202:in `execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:52:in `execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/rest-client-2.0.0.rc1/lib/restclient.rb:66:in `get'
        from /usr/local/lib/ruby/gems/1.9.1/gems/owasp_zap-0.0.95/lib/owasp_zap/attack.rb:16:in `start'
        from owasp_run.rb:24:in `<main>'

Is the way I am passing the target wrong? Or am I missing something else as it isnt getting the addr(). As when I do print addr(), it prints nil

**Comment by thc202** [comment]
If you create the ```Attack``` yourself you also need to specify the ```base``` URL (note that you are creating several instances of ```Zap```/```Attack``` class, not just one with the various variables initialised).
You can use the ```Zap``` instance to obtain the ```Attack``` instead of instantiating it yourself though.
Following an example script:
```Ruby
require 'owasp_zap'
include OwaspZap

zap = Zap.new :base=>'http://127.0.0.1:8082', :target=>'http://www.xyz.com', :zap=>'/root/ZAP/ZAP_2.4.1/zap.sh', :output=>'logfile.txt'
zap.start :daemon=>true

# Wait for ZAP to start
until zap.running?
    sleep(2)
end

# Generate some requests for Active Scan
spider = zap.spider
spider.start
sleep(2)

# Wait for the spider to finish
while spider.running?
    sleep(2)
end

p 'Starting Active Scan...'
scan = zap.ascan # Obtaining the Attack from zap instance
scan.start
sleep(2)

# Wait for the active scan to finish
while scan.running?
    sleep(2)
end

# do something with results

zap.shutdown
```

**Comment by ambikashri** [comment]
Thank you. This worked. It didnt work previously for me probably because I wasn't doing the spider and directly going for active scan.

**Comment by kingthorin** [comment]
Safe to close this ticket then?
