### ISSUE TITLE
Stop Attack Feature Locks up ZAP?

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#1798]
I've tried this twice in a row. Start an attack, and then stop it after just a few requests and it stops, but all of ZAP just locks up...

**Comment by psiinon** [comment]
Strange, just tried it and I've not hit this problem.
Are there any errors in the zap.log file?
How are you launching the scan?
If its a app like OWASP Benchmark can you walk us through the steps you take?

**Comment by davewichers** [comment]
It's against the Benchmark. Pretty simple. Launch ZAP, paste in benchmark
home page URL, hit attack, immediately hit Stop.  It did this to me 2-3
times in a row. I'll try again tonight to see if I  can repeat the result.
I am running on Mac and giving ZAP lots of memory, neither of which should
matter.

Dave

**Comment by thc202** [comment]
I was able to reproduce the issue (used "develop" branch), following the stack traces of offending threads:
```
2015-08-25 19:22:07

"AWT-EventQueue-0" - Thread t@14
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- waiting to lock <6abf5502> (a java.util.concurrent.locks.ReentrantLock$NonfairSync) owned by "ZAP-QuickStart-AttackThread" t@38
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at org.zaproxy.zap.extension.spider.SpiderScanController.getActiveScans(SpiderScanController.java:175)
	at org.zaproxy.zap.extension.spider.ExtensionSpider.getActiveScans(ExtensionSpider.java:442)
	at org.zaproxy.zap.view.ScanPanel2.setActiveScanLabelsEventHandler(ScanPanel2.java:268)
	at org.zaproxy.zap.view.ScanPanel2.scanProgressEventHandler(ScanPanel2.java:506)
	at org.zaproxy.zap.view.ScanPanel2.access$4(ScanPanel2.java:501)
	at org.zaproxy.zap.view.ScanPanel2$7.run(ScanPanel2.java:489)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
	- None

"ZAP-QuickStart-AttackThread" - Thread t@38
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <175ef269> (a java.awt.EventQueue$1AWTInvocationLock)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1313)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
	at org.zaproxy.zap.view.ScanPanel2.scanFinshed(ScanPanel2.java:461)
	at org.zaproxy.zap.extension.spider.SpiderScan.spiderComplete(SpiderScan.java:280)
	at org.zaproxy.zap.extension.spider.SpiderScan.scanFinshed(SpiderScan.java:344)
	at org.zaproxy.zap.extension.spider.SpiderThread.spiderComplete(SpiderThread.java:311)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderComplete(Spider.java:710)
	- locked <689bc2e1> (a org.zaproxy.zap.spider.Spider)
	at org.zaproxy.zap.spider.Spider.stop(Spider.java:497)
	at org.zaproxy.zap.extension.spider.SpiderThread.stopScan(SpiderThread.java:146)
	at org.zaproxy.zap.extension.spider.SpiderScan.stopScan(SpiderScan.java:209)
	at org.zaproxy.zap.extension.spider.SpiderScanController.stopScan(SpiderScanController.java:290)
	at org.zaproxy.zap.extension.spider.ExtensionSpider.stopScan(ExtensionSpider.java:452)
	at org.zaproxy.zap.extension.quickstart.AttackThread.run(AttackThread.java:103)

   Locked ownable synchronizers:
	- locked <32d4f865> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

	- locked <6abf5502> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```
(obtained with Java VisualVM with "Threads Inspector" plugin)

**Comment by psiinon** [comment]
Ah - I was starting my scan using the Active Scan dialog ;)
