### ISSUE TITLE
Scan URl via API --> ERROR Model - Failed to delete 

### ISSUE THREAD

**Issue by jengra** [zaproxy/zaproxy#1803]
Hey 
i don't know what the problem is
I'd like to scan my application via API 
i have donwload one example 
https://github.com/gmaran23/zaproxy/blob/master/dotnet/api/src/OWASPZAPDotNetAPI/OWASPZAPDotNetAPI.Samples/AuthenticatedScanWithFormsAuthentication.cs

this are my configs
        private static string _target = "http://localhost:8020/home/index" --> if i start this url in my browser i see the website 
        private static ClientApi _api = new ClientApi("localhost", 8090);--> if i start this url i see the zap api

open zap works 
SimplePointAndClickScan works

but if i start 
AuthenticatedScanWithFormsAuthentication

i have following error 

2015-08-18 18:50:30,234 [main ] INFO  ZAP - OWASP ZAP 2.4.1 started.
2015-08-18 18:50:30,282 [main ] ERROR Model - Failed to delete file C:\Users\jennifer\OWASP ZAP\session\untitled1.data
2015-08-18 18:50:30,283 [main ] ERROR Model - Failed to delete file C:\Users\jennifer\OWASP ZAP\session\untitled1.lck
2015-08-18 18:50:30,283 [main ] ERROR Model - Failed to delete file C:\Users\jennifer\OWASP ZAP\session\untitled1.log
2015-08-18 18:50:40,793 [main ] FATAL ZAP - invalid database address: jdbc:hsqldb:file:C:/Users/jennifer/OWASP ZAP/session/untitled1
java.sql.SQLException: invalid database address: jdbc:hsqldb:file:C:/Users/jennifer/OWASP ZAP/session/untitled1
	at org.sqlite.JDBC.createConnection(JDBC.java:110)
	at org.sqlite.JDBC.connect(JDBC.java:87)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosDatabaseServer.start(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosDatabaseServer.<init>(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosDatabase.open(Unknown Source)
	at org.parosproxy.paros.model.Model.createAndOpenUntitledDb(Unknown Source)
	at org.parosproxy.paros.model.Model.init(Unknown Source)
	at org.zaproxy.zap.ZAP.run(Unknown Source)
	at org.zaproxy.zap.ZAP.main(Unknown Source)

i check the folder session i can't uncheckt the readonly flag 

any idea i'm unhappy i can 't work start with my work if i dont't understand the basics please help me someone. maby it's a small problem

**Comment by kingthorin** [comment]
Either ```C:\Users\jennifer\OWASP ZAP\``` doesn't exist or you can't write there.

**Comment by jengra** [comment]
it does exist 
but if i start my console app --> and start owasp --> then jave has handle on the files 
my stacktrace in visuel studio 

 bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei System.Net.WebClient.DownloadString(String address)
   bei OWASPZAPDotNetAPI.SystemWebClient.DownloadString(String address) in c:\Users\jennifer.simson\API-Owasp\api\src\OWASPZAPDotNetAPI\OWASPZAPDotNetAPI\SystemWebClient.cs:Zeile 45.
   bei OWASPZAPDotNetAPI.ClientApi.AccessUrl(String url) in c:\Users\jennifer.simson\API-Owasp\api\src\OWASPZAPDotNetAPI\OWASPZAPDotNetAPI\ClientApi.cs:Zeile 101.
   bei OWASPZAPDotNetAPI.Samples.AuthenticatedScanWithFormsAuthentication.LoadTargetUrlToSitesTree() in c:\Users\jennifer.simson\API-Owasp\api\src\OWASPZAPDotNetAPI\OWASPZAPDotNetAPI.Samples\AuthenticatedScanWithFormsAuthentication.cs:Zeile 305.
   bei OWASPZAPDotNetAPI.Samples.AuthenticatedScanWithFormsAuthentication.Go() in c:\Users\jennifer.simson\API-Owasp\api\src\OWASPZAPDotNetAPI\OWASPZAPDotNetAPI.Samples\AuthenticatedScanWithFormsAuthentication.cs:Zeile 42.

**Comment by kingthorin** [comment]
So now you have a different error?

```C:\Users\jennifer\OWASP ZAP\session\untitled1.data``` != ```c:\Users\jennifer.simson\API-Owasp\api\src\OWASPZAPDotNetAPI\OWASPZAPDotNetAPI\SystemWebClient.cs:Zeile```

It might exist but is it writable? Are the files in use when you launch ZAP and it tries to remove them?

**Comment by kingthorin** [comment]
User reporting same issue as previously addressed: https://github.com/zaproxy/zaproxy/issues/1775
