### ISSUE TITLE
Error when calling Komponent:pnh --> Aktion: Monitor 

### ISSUE THREAD

**Issue by jengra** [zaproxy/zaproxy#1845]
Steps to reproduce the issue:
1. Run ZAP;
2. Access the following URL while proxying through ZAP:

http://zap/JSON/pnh/action/monitor/?zapapiformat=JSON&id=1&message=testing

Logfile: 
2015-08-20 15:33:34,490 [ZAP-ProxyThread-404] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-ProxyThread-404"
net.sf.json.JSONException: A JSONObject text must begin with '{' at character 1 of 1
	at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499)
	at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:972)
	at net.sf.json.JSONObject._fromString(JSONObject.java:1201)
	at net.sf.json.JSONObject.fromObject(JSONObject.java:165)
	at net.sf.json.JSONObject.fromObject(JSONObject.java:134)
	at org.zaproxy.zap.extension.plugnhack.PlugNHackAPI.handleApiAction(PlugNHackAPI.java:106)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by kingthorin** [comment]
This is easy to recreate. It's unclear what the "message" param is supposed to be?

**Comment by thc202** [comment]
I don't think it needs to be clear this is an "internal" endpoint (but one can check it in `pnh_probe.js`), we just need to fix the exception handling.
