### ISSUE TITLE
An error occurred checking a url for SQL Injection vulnerabilities java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by qaDream77** [zaproxy/zaproxy#1860]
Trying to run zaproxy from jenkins and getting the following socket errors, any ideas/thoughts would be appreciated. Cheers.

33510 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrules.TestSQLInjection  - An error occurred checking a url for SQL Injection vulnerabilities
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(Unknown Source)
	at org.zaproxy.zap.ZapGetMethod.readResponse(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodBase.execute(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(Unknown Source)
	at org.zaproxy.zap.extension.ascanrules.TestSQLInjection.scan(TestSQLInjection.java:751)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by thc202** [comment]
Shouldn't be closed now? (since it's duplicate)

**Comment by kingthorin** [comment]
Closing duplicate :smile:
