### ISSUE TITLE
Null Pointer Exception when trying to import a context

### ISSUE THREAD

**Issue by logancarmody** [zaproxy/zaproxy#1863]
when trying to import a context, which is in the proper `.ZAP/contexts/` dir... I get a null pointer exception... not really sure what the issue is, because I created the context file with the same version of zap and hasn't been edited since then...

```
17935 [ZAP-ProxyThread-2] ERROR org.zaproxy.zap.extension.api.ContextAPI  - 
java.lang.NullPointerException
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at org.zaproxy.zap.control.AddOnLoader.loadClass(Unknown Source)
	at org.parosproxy.paros.model.Session.importContext(Unknown Source)
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
18077 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - handleApiRequest error: Internal Error
Internal Error (internal_error)
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
rake aborted!
```

**Comment by kingthorin** [comment]
Ok you opened and closed your own issue, which is great. But what did you find out? It might be relevant to others in the future :smile:
