### ISSUE TITLE
Failed to attack URL, please check that the URL you specify is valid

### ISSUE THREAD

**Issue by lloydracine** [zaproxy/zaproxy#1892]
I'm using OWASP ZAP 2.4.2 on Windows 7

I can access the URL without issue using either Chrome or IE browsers..

The URL that an attack is being attempted on only supports TLS 1.0 protocol.

When setup as a proxy for the browser I receive the following message in the browser:

ZAP Error [javax.net.ssl.SSLHandshakeException]: Received fatal alert: handshake_failure

Stack Trace:
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by thc202** [comment]
There's a FAQ entry that has suggestions on how to fix handshake failures. [1]
If the previous doesn't work you could try just enable "TLS 1" in "Connection" options panel.

[1] https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake

**Comment by lloydracine** [comment]
Thanks for the response.

Same results after disabling all security protocols except TLS 1.0 on Connection Options panel.
Same results after checking Enable unsafe SSL/TLS renegotiation as suggested in the FAQ.
Same results after installing the 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files' as suggested in the FAQ.

Any other suggestions would be appreciated.

**Comment by kingthorin** [comment]
What OS?
What Java Version?
What browser are you using?
Have you installed ZAPs CA Certificate?
Where is the site/app you're testing located in relation to your ZAP/browser machine? (Localhost, local network, etc)

**Comment by lloydracine** [comment]
Machine running OWASP ZAP is Windows 7 with Java 1.8.  I've tried both Chrome and IE 11 browsers with ZAP proxy enabled.  ZAPs CA Certificate is installed.  The site being tested is a remote internet site running Linux 2.6 with Java RTE 1.6 and the only security protocol it supports is TLS 1.0,

**Comment by lloydracine** [comment]
I should mention that ZAP works fine attacking a number of other websites (http and https) from this machine using quick start or browser proxy.  The website that is throwing the error is a https which only supports TLS 1.0.

**Comment by kingthorin** [comment]
When you connect via chrome or IE directly are you able to verify TLS1.0? Could you tell us the cyphersuite that gets picked?
Are you able to share the URL?

**Comment by lloydracine** [comment]
If I connect directly using Chrome and not via the ZAP proxy, Chrome indicates the "connection to www.website.com is encrypted using an obsolete cipher suite.  The connections uses TLS 1.0."  

I am unable to share the URL especially via a public forum.  It is production website that while publicly accessible is not publicly available.

**Comment by kingthorin** [comment]
Are you using ZAP 2.4.2?

**Comment by lloydracine** [comment]
Yes

**Comment by kingthorin** [comment]
Perhaps: http://stackoverflow.com/a/32019108
Entire thread is here: http://stackoverflow.com/questions/32009083/javax-net-ssl-sslhandshakeexception-handshake-failure-when-using-jmeter-with-ss

**Comment by lloydracine** [comment]
Configuring Java to use older JRE 7 and installing 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files' for JRE 7 seems to have gotten me past the issue.

**Comment by kingthorin** [comment]
So the issue might be java 8 clients and your server offering RC4 ciphers. Are you able to disable RC4? As they ended up doing in that stackoverflow answer post?

I'll update our SSL FAQ with this info.

**Comment by lloydracine** [comment]
No I am not able to disable RC4.  I am not in control of the server and the owner is reluctant to make any changes at this time.

**Comment by kingthorin** [comment]
No problem. Glad to hear you got things running. Are you OK with us closing this ticket?

**Comment by kingthorin** [comment]
FAQ updated: https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake/_compare/2b1d9d468c2f3a1dcf4c44c659381d68abdca3cd...712b96da1bfd6ee91a3f2861d88dc62045926f62
