### ISSUE TITLE
Unable to add empty string payloads for fuzzer

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#1948]
Steps to reproduce the issue:
1. Run ZAP;
2. Fuzz a message and add two empty "String" payloads (i.e. hit return key and click "Add");
3. Start the fuzzer and note that nothing happens;
4. Check the log file, there should be an exception:
```
46612 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: Parameter values must not be null nor empty.
	at org.zaproxy.zap.extension.fuzz.payloads.generator.DefaultStringPayloadGenerator.<init>(DefaultStringPayloadGenerator.java:50)
	at org.zaproxy.zap.extension.fuzz.payloads.ui.impl.DefaultStringPayloadGeneratorUIHandler$DefaultStringPayloadGeneratorUI.getPayloadGenerator(DefaultStringPayloadGeneratorUIHandler.java:145)
	at org.zaproxy.zap.extension.fuzz.payloads.ui.impl.DefaultStringPayloadGeneratorUIHandler$DefaultStringPayloadGeneratorUI.getPayloadGenerator(DefaultStringPayloadGeneratorUIHandler.java:71)
	at org.zaproxy.zap.extension.fuzz.impl.FuzzMessageLocationsPanel.getFuzzMessageLocations(FuzzMessageLocationsPanel.java:191)
	at org.zaproxy.zap.extension.fuzz.impl.FuzzerDialog.save(FuzzerDialog.java:215)
```

Remarks:
It should also be possible to add just one empty string payload, instead it's shown a dialogue saying that it must be entered a string.

Add-on version:
"AdvFuzzer" versions >= 1.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions@0a0b67e7a5d2ea0bd2a959bfab5192b931767a03.
