### ISSUE TITLE
NullPointerException when passive scanning with "Base64 Disclosure"

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2037]
Steps to reproduce the issue:
1. Run ZAP with "Passive scanner rules (alpha)" installed;
2. Access a page that contains a Base64 string, for example:
`MDEyMzQ1Njc4OTEwQWJDZEVmRysvLQ==`
3. Check the log file, there should be an exception:
```
146062 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscan.PassiveScanThread  - Scanner Base64 Disclosure failed on record 4 from History table: POST https://example.com/
java.lang.NullPointerException
	at org.zaproxy.zap.extension.pscanrulesAlpha.Base64Disclosure.scanHttpResponseReceive(Base64Disclosure.java:277)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(Unknown Source)
```

Add-on:
"Passive scanner rules (alpha)" versions >= 5

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions@8c3b30494880d5e42c20f0c9e70b90883a360e5a.
