### ISSUE TITLE
Improve Fuzzer memory usage

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2051]
From #1759.
Steps to reproduce the issue:
1. Run ZAP with "AdvFuzzer" add-on installed;
2. Fuzz a message and select a big "File Fuzzer", for example, "directory-list-2.3-big.txt";
3. Start the fuzzer and note that the memory usage increases (a lot);
4. Potentially leading to exhaustion of the memory, for example:
```
331029 [ZAP-FuzzerTaskSubmitter-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-FuzzerTaskSubmitter-0"
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:101)
	at org.parosproxy.paros.network.HttpHeader.parse(Unknown Source)
	at org.parosproxy.paros.network.HttpHeader.setMessage(Unknown Source)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(Unknown Source)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(Unknown Source)
	at org.parosproxy.paros.network.HttpRequestHeader.<init>(Unknown Source)
	at org.parosproxy.paros.network.HttpMessage.setRequestHeader(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.messagelocations.TextHttpMessageLocationReplacer.replace(TextHttpMessageLocationReplacer.java:108)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.messagelocations.TextHttpMessageLocationReplacer.replace(TextHttpMessageLocationReplacer.java:32)
	at org.zaproxy.zap.extension.fuzz.messagelocations.MultipleMessageLocationsDepthFirstReplacer.next(MultipleMessageLocationsDepthFirstReplacer.java:125)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzer$FuzzerTaskSubmitter.submitTasks(AbstractFuzzer.java:555)
	at org.zaproxy.zap.extension.fuzz.AbstractFuzzer$FuzzerTaskSubmitter.run(AbstractFuzzer.java:520)
```

Remarks:
The fuzzer tasks are immediately created, instead of progressively as they are consumed, leading to a high memory usage.

Add-on version:
"AdvFuzzer" versions >= 1.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#96.
