### ISSUE TITLE
Issue with Token generator

### ISSUE THREAD

**Issue by vskram21** [zaproxy/zaproxy#2116]
Hi All, 

Token generator is not working below is how I initiated the extension. There were two JSESSION IDs displayed I tried with both.

![image](https://cloud.githubusercontent.com/assets/468730/11714715/316e0982-9f62-11e5-9003-415c1f5e7991.png)

Here is the flow of authentication.

1. Username and password is sent in POST request to the server.
2. Servers sends a redirects to the index page ("302" request),  sets the cookie using "Set-Cookie:"  

I notice that ZAP doesn't find the session token,
![image](https://cloud.githubusercontent.com/assets/468730/11714848/22fe5b94-9f63-11e5-89d6-635d2028e745.png)

I get the below error message from the logs

```2015-12-10 14:17:06,301 [Thread-328] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "Thread-328"
java.lang.ArithmeticException: / by zero
	at org.zaproxy.zap.extension.tokengen.CharacterFrequencyMap.checkCharacterUniformity(CharacterFrequencyMap.java:134)
	at org.zaproxy.zap.extension.tokengen.TokenAnalyserThread.run(TokenAnalyserThread.java:97)```



Regards,
Satheesh

**Comment by kingthorin** [comment]
@thc202 fixed?

**Comment by thc202** [comment]
No, the problem of ZAP not finding the cookies is still not fixed.
