### ISSUE TITLE
Zest "Active scan sequence" not working

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2120]
Steps to reproduce the issue:
1. Run ZAP (v2.4.3) with Zest (v19), Sequence (v2) and Script Console (v15) add-ons installed;
2. Create a Zest Sequence script;
3. Select the script, open the context menu and choose "Active scan sequence";
4. Note that the "Active Scan" tab is shown but nothing happens, the progress bar is stuck at 0%;
5. Check the log file, there should be an exception:
```
165978 [Thread-12] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "Thread-12"
java.lang.NullPointerException
	at org.zaproxy.zap.model.StructuralSiteNode.getName(Unknown Source)
	at org.parosproxy.paros.core.scanner.Scanner.getHostAndPort(Unknown Source)
	at org.parosproxy.paros.core.scanner.Scanner.scan(Unknown Source)
	at org.parosproxy.paros.core.scanner.Scanner.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

Remarks:
Stopping the scan does not work immediately, only after pausing.

ZAP Version:
Versions >= 2.4.1

Add-on:
"Zest - Graphical Security Scripting Language"

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions@297c34094805f3a9b4d1b90d2f35f5b40cd58eb5.
