### ISSUE TITLE
Continuous Integration support for parallel test execution

### ISSUE THREAD

**Issue by arcuri82** [zaproxy/zaproxy#2157]
Hi,
 trying to integrate ZAP into a CI environment, where I have thousands of Selenium tests, running them in parallel around 16-32 at a time. Using ZAP (latest 2.4.3) as a proxy, and then using REST api to call "htmlreport" once all tests are finished. 
ZAP (cross-platform version) is started from its directory installation with:

java -jar <jar>  -daemon -host < host >  -port < port > -config api.disablekey=true

However, the logs are full of crashes like:

build	30-Dec-2015 13:13:27	1528354 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
build	30-Dec-2015 13:13:27	1528354 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
build	30-Dec-2015 13:13:27	1528354 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.params.ExtensionParams  - java.sql.SQLTransactionRollbackException: transaction rollback: serialization failure
build	30-Dec-2015 13:13:27	org.parosproxy.paros.db.DatabaseException: java.sql.SQLTransactionRollbackException: transaction rollback: serialization failure
build	30-Dec-2015 13:13:27		at org.parosproxy.paros.db.paros.ParosTableParam.update(Unknown Source)
build	30-Dec-2015 13:13:27		at org.zaproxy.zap.extension.params.ExtensionParams.persist(Unknown Source)
build	30-Dec-2015 13:13:27		at org.zaproxy.zap.extension.params.ExtensionParams.onHttpResponseReceive(Unknown Source)
build	30-Dec-2015 13:13:27		at org.zaproxy.zap.extension.params.ParamScanner.scanHttpResponseReceive(Unknown Source)
build	30-Dec-2015 13:13:27		at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(Unknown Source)
build	30-Dec-2015 13:13:27	Caused by: java.sql.SQLTransactionRollbackException: transaction rollback: serialization failure
build	30-Dec-2015 13:13:27		at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
build	30-Dec-2015 13:13:27		at org.hsqldb.jdbc.Util.sqlException(Unknown Source)
build	30-Dec-2015 13:13:27		at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
build	30-Dec-2015 13:13:27		at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
build	30-Dec-2015 13:13:27		... 5 more
build	30-Dec-2015 13:13:27	Caused by: org.hsqldb.HsqlException: transaction rollback: serialization failure
build	30-Dec-2015 13:13:27		at org.hsqldb.error.Error.error(Unknown Source)
build	30-Dec-2015 13:13:27		at org.hsqldb.error.Error.error(Unknown Source)
build	30-Dec-2015 13:13:27		at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
build	30-Dec-2015 13:13:27		at org.hsqldb.Session.execute(Unknown Source)
build	30-Dec-2015 13:13:27		... 7 more
build	30-Dec-2015 13:13:27	1528360 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
build	30-Dec-2015 13:13:27	1528421 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
build	30-Dec-2015 13:13:27	1528422 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end
build	30-Dec-2015 13:14:30	1591216 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint start
build	30-Dec-2015 13:14:30	1591216 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose start
build	30-Dec-2015 13:14:30	1591219 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
build	30-Dec-2015 13:14:30	1591366 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - checkpointClose end
build	30-Dec-2015 13:14:30	1591367 [HSQLDB Timer @8e24743] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Checkpoint end

and

build	30-Dec-2015 13:09:06	1267072 [ZAP-ProxyThread-13089] ERROR org.parosproxy.paros.network.HttpSender  - 
build	30-Dec-2015 13:09:06	java.util.ConcurrentModificationException
build	30-Dec-2015 13:09:06		at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
build	30-Dec-2015 13:09:06		at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
build	30-Dec-2015 13:09:06		at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
build	30-Dec-2015 13:09:06		at java.util.LinkedList.addAll(LinkedList.java:408)
build	30-Dec-2015 13:09:06		at java.util.LinkedList.addAll(LinkedList.java:387)
build	30-Dec-2015 13:09:06		at java.util.LinkedList.<init>(LinkedList.java:119)
build	30-Dec-2015 13:09:06		at org.zaproxy.zap.session.CookieBasedSessionManagementHelper.getMatchingHttpSession(Unknown Source)
build	30-Dec-2015 13:09:06		at org.zaproxy.zap.extension.httpsessions.HttpSessionsSite.getMatchingHttpSession(Unknown Source)
build	30-Dec-2015 13:09:06		at org.zaproxy.zap.extension.httpsessions.HttpSessionsSite.processHttpRequestMessage(Unknown Source)
build	30-Dec-2015 13:09:06		at org.zaproxy.zap.extension.httpsessions.ExtensionHttpSessions.onHttpRequestSend(Unknown Source)
build	30-Dec-2015 13:09:06		at org.parosproxy.paros.network.HttpSender.notifyRequestListeners(Unknown Source)
build	30-Dec-2015 13:09:06		at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
build	30-Dec-2015 13:09:06		at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
build	30-Dec-2015 13:09:06		at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
build	30-Dec-2015 13:09:06		at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
build	30-Dec-2015 13:09:06		at java.lang.Thread.run(Thread.java:745)

beside these ERROR messages, the build logs are flooded by thousands of INFO messages stating for example:

build	30-Dec-2015 13:09:25	1285725 [ZAP-ProxyThread-13403] INFO org.zaproxy.zap.extension.httpsessions.HttpSessionsSite  - Created a new session as no match was found: HttpSession [name=Session 1,071, active=false, tokenValues='']

At the end of test executions, I do get an html report from the ZAP daemon. However, it is very small, having less entries then when running a couple of tests manually from my local machine. 

Wondering: considering the above entries in the logs, does ZAP daemon support parallel Selenium tests using it as a proxy?  If not: is it something that can be fixed? Is there any viable workaround? Could run each single test with its own ZAP proxy, but, beside complicating the setting and introducing non-negligeable execution overheads, how to (easily) merge the test results?

cheers

Andrea

**Comment by kingthorin** [comment]
I guess you might be hitting some kind of concurrency issue with hsqldb.
