### ISSUE TITLE
HPP - Causes Protocol and Host Exceptions

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#2175]
Based on https://groups.google.com/forum/#!topic/zaproxy-develop/kpxnenhuoJA & http://zapbot.github.io/zap-mgmt-scripts/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

May require a logging change. The first exception seems related to a redirect response, the second is less clear but may also be a redirect. Better logging could clarify.

`9502700 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - start host http://172.17.0.2:8080 | HPP strength HIGH threshold MEDIUM`

`9560954 [ZAP-ActiveScanner-1] ERROR org.zaproxy.zap.extension.ascanrulesBeta.HPP  - unsupported protocol: '172.17.0.2'
java.lang.IllegalStateException: unsupported protocol: '172.17.0.2'
	at org.apache.commons.httpclient.protocol.Protocol.lazyRegisterProtocol(Protocol.java:149)
	at org.apache.commons.httpclient.protocol.Protocol.getProtocol(Protocol.java:117)
	at org.apache.commons.httpclient.HttpHost.<init>(HttpHost.java:107)
	at org.apache.commons.httpclient.HttpMethodBase.setURI(HttpMethodBase.java:294)
	at org.apache.commons.httpclient.HttpMethodDirector.processRedirectResponse(HttpMethodDirector.java:668)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:189)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:185)
	at org.zaproxy.zap.extension.ascanrulesBeta.HPP.scan(HPP.java:157)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
	at java.lang.Thread.run(Thread.java:745)`

`9561780 [ZAP-ActiveScanner-0] ERROR org.zaproxy.zap.extension.ascanrulesBeta.HPP  - &zap=zaproxy
java.net.UnknownHostException: &zap=zaproxy
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:280)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:439)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:191)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:307)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:519)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:478)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:456)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:364)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:189)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:185)
	at org.zaproxy.zap.extension.ascanrulesBeta.HPP.scan(HPP.java:157)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:282)
	at java.lang.Thread.run(Thread.java:745)
9564386 [Thread-21] INFO org.parosproxy.paros.core.scanner.HostProcess  - completed host/plugin http://172.17.0.2:8080 | HPP in 61.686s`

**Comment by kingthorin** [comment]
Specifically this was from this iteration of the log: https://raw.githubusercontent.com/zapbot/zap-mgmt-scripts/2d6cc66d9b2e70f28008df95e7c9f3400c19a067/reports/wavsep-1.5-weekly-RBAJ-M-M.logs.txt

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#221.
