### ISSUE TITLE
Websocket java.net.SocketException

### ISSUE THREAD

**Issue by famedoro** [zaproxy/zaproxy#2242]
Under Scientific Linux 6.7 (like CentOs), using ZAP 2.4.3 I have tried to intercept my own websocket traffic coming from port 7072, but I have this error:

ZAP Error [java.net.SocketException]: Pipe broken

Stack Trace:
java.net.SocketException: Pipe rotta
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
    at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
    at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:857)
    at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:828)
    at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
    at org.parosproxy.paros.network.HttpOutputStream.flush(Unknown Source)
    at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
    at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
    at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
    at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
    at org.parosproxy.paros.core.proxy.ProxyThread.writeHttpResponse(Unknown Source)
    at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
    at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:744)

**Comment by kingthorin** [comment]
Could you let us know what version of Java? Also did this happen immediately or after a bit of testing/proxying?

**Comment by famedoro** [comment]
[root@galahad ZAP_2.4.3]# java -version
java version "1.8.0_20-ea"
Java(TM) SE Runtime Environment (build 1.8.0_20-ea-b05)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b05, mixed mode)

Initially the http and https pages are loaded , as soon as it reaches the page that contains the connection which have wss websocket there is the java exception

**Comment by thc202** [comment]
Are you able to see the WebSocket handshake in ZAP?
Which browser (and version) are you using?

**Comment by famedoro** [comment]
Hi see only http and https traffic. The browser is Opera 35 and it works correctly if I don't use Zap proxy

**Comment by psiinon** [comment]
Can you try Firefox, just to see if that works. 
I dont suppose the website is publicly accessible is it?

**Comment by thc202** [comment]
@famedoro with WebSocket handshake I'm referring to the HTTP Upgrade request.

**Comment by famedoro** [comment]
How can I identify the HTTP Upgrade request ?

**Comment by famedoro** [comment]
To access to website you need private credential

**Comment by thc202** [comment]
It has "Upgrade: websocket" header and response status code should be 101.

**Comment by famedoro** [comment]
@thc202 
The header is:
HTTP/1.1 502 Bad Gateway
Content-Length: 1417
Content-Type: text/plain; charset=UTF-8

The Body:
ZAP Error [java.net.SocketException]: Broken pipe

Stack Trace:
java.net.SocketException: Pipe rotta
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:857)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:828)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.parosproxy.paros.network.HttpOutputStream.flush(Unknown Source)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.writeHttpResponse(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:744)

First of this I have only GET method with code 200

**Comment by thc202** [comment]
OK, and the request header of that response? Is it trying to initiate the WebSocket upgrade?
Something like:
> GET / HTTP/1.1
> Upgrade: websocket
> Connection: Upgrade
> Host: example.com

**Comment by famedoro** [comment]
@thc202 

The request is:
GET https://www.example-url.com/ita/scripts/jquery/jquery.validate.js HTTP/1.1
User-Agent: Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: it-IT,it;q=0.9,en;q=0.8
Referer: https://www.example-url.com/ita/example-urlxt-back.jsp
Cookie: sauth=%7B%22version%22%3A%221.1%22%2C%22authenticated%22%3Atrue%2C%22state%22%3A%22user_new_a%22%2C%22lastDay%22%3A%2220160221%22%7D; JSESSIONID=K8SRWKyLcL36zgFnvVxs6Pcl2tkzFdpgxQ458SyfCQtqv14K1PBr!-1350204758!-1407959962!20101!-1; _pk_id.1.c524=54b13f865236862b.1450721989.8.1456089341.1456089341.; _pk_ses.1.c524=*; ACTemp=1; psessionid=K8SRWKyLcL36zgFnvVxs6Pcl2tkzFdpgxQ458SyfCQtqv14K1PBr!-1350204758!-1407959962!20101!-1!1456089320445; _pk_id.22.c524=b304aaa31a2c511b.1450722039.6.1456089360.1456089360.; _pk_ses.22.c524=*; _pk_id.23.c524=f3b23fed925d38e0.1450721989.7.1456089360.1456089341.; _pk_ses.23.c524=*; _nvis_cl5=1456089360518%2C1111111; visitz=OYtYbaDGUgPonUEpZ3ggvEqVnPSKhGELpi61vgf5UHpaMFXJrvgXwJujOETuZU3gjXtzomoYBwTCaNytx8JneucvgZQ44jh2fPO0xfM1dMGBvrtdFxSxxryQEaIgCUWOuogEFX7nLeJoQ8258f5gYo; _example-urlCheckFlag=1456089358749; _gat=1; _ga=GA1.2.1138497230.1450721989; _gali=Avanti
Connection: Keep-Alive
Host: www.example-url.com

**Comment by thc202** [comment]
OK, it's failing always in the "jquery.validate.js" request? Or, it happens with several requests?

Yeah, that's the request (and response) I was expecting to see in ZAP.

**Comment by famedoro** [comment]
@thc202 
with reference to the tests done, it only happens jquery.validate.js

**Comment by famedoro** [comment]
@thc202 
I think that this exception causes the block of the  websocket data traffic between the provider and the browser, in fact  the data in the browser are no longer updated

**Comment by famedoro** [comment]
@psiinon 
my problem is similar to that posted on http://stackoverflow.com/questions/12344529/websockets-and-application-proxy-connection-issues.
The site is not publicly available, but if you want I can give you all the necessary information

**Comment by famedoro** [comment]
I think that the problem of blocking traffic coming from websocket is due to the fact that, in this case, it comes from port 7072 which is not a standard port.

**Comment by kingthorin** [comment]
Are you able to host it differently or reverse proxy to prove or disprove?

I'd lean towards no if it's manifesting browser specific behavior, but worth checking.

**Comment by famedoro** [comment]
No, I am sorry I am unable to intervene on the server. I can only receive the data after authentication. 
There is some information or test that can I be done in order to help you to solve this problem ?

**Comment by thc202** [comment]
I was able to reproduce the "502 Bad Gateway" issue with Opera 35 (not with 12.16 though). But, it does request again the JS file and keeps working as expected.
It's strange that the browser closes the connection so abruptly, it could wait for the response...

Does in your case re-request the JS file?

The combination Opera/ZAP/Websocket works fine with other ports (tested with 7072, 8080).

**Comment by famedoro** [comment]
@thc202 
Note with firefox 44.0.2 I don't have the exception, although still I do not receive data from websocket.

With Opera I have 3  "502 Bad Gateway",  one after the other,  note: from the second to the third the server it is different see below:

The first:

Request:
GET https://www.privateSite.com/ita/scripts/jquery/qtip/jquery.qtip-1.0.0-rc3.min.js HTTP/1.1
User-Agent: Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: it-IT,it;q=0.9,en;q=0.8
Referer: https://www.privateSite.com/privateSitex-back.jsp
Cookie: sauth=%7B%22version%22%3A%221.1%22%2C%22authenticated%22%3Atrue%2C%22state%22%3A%22user_new_a%22%2C%22lastDay%22%3A%2220160224%22%7D; JSESSIONID=L1tNWN6QGx2K5BwX711Jw31Q94Tf2kJHKvfhC4Lc2G46g7PVfVWx!653275306!-1407959958!10101!-1; _pk_id.1.c524=54b13f865236862b.1450721989.10.1456339595.1456339595.; _pk_ses.1.c524=*; ACTemp=1; psessionid=L1tNWN6QGx2K5BwX711Jw31Q94Tf2kJHKvfhC4Lc2G46g7PVfVWx!653275306!-1407959958!10101!-1!1456339584296; _pk_id.22.c524=b304aaa31a2c511b.1450722039.8.1456339623.1456339623.; _pk_ses.22.c524=*; _pk_id.23.c524=f3b23fed925d38e0.1450721989.9.1456339623.1456339595.; _pk_ses.23.c524=*; _nvis_cl5=1456339628528%2C111111111; visitz=OYtYbaDGUgPonUEpZ3ggvEqVnPSKhGELpi61vgf5UHpaMFXJrvgXwJujOETuZU3gjXtzomoYBwTCaNytx8JneucvgZQ44jh2fPO0xfM1dMGBvrtdFxSxxryQEaIgCUWOuogEFX7nLeJoQ8258f5gYo; _privateSiteCheckFlag=1456339622242; _gat=1; _ga=GA1.2.1138497230.1450721989; _gali=Avanti
Connection: Keep-Alive
Host: www.privateSite.com

Response:
HTTP/1.1 200 OK
Date: Wed, 24 Feb 2016 18:47:30 GMT
Server: Apache
Last-Modified: Mon, 10 Oct 2011 10:55:48 GMT
ETag: "1ee2e-9604-4aeefa22b3500"
Accept-Ranges: bytes
Content-Length: 38404
Vary: Accept-Encoding,User-Agent
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: application/javascript

/*
 * jquery.qtip. The jQuery tooltip plugin
 *
 * Copyright (c) 2009 Craig Thompson
 * http://craigsworks.com
 *
 * Licensed under MIT
 * http://www.opensource.org/licenses/mit-license.php
 *
 * Launch  : February 2009
 * Version : 1.0.0-rc3
 * Released: Tuesday 12th May, 2009 - 00:00
 * Debug: jquery.qtip.debug.js
 */
(function(f){f.fn.qtip=function(B,u){var y,t,A,s,x,w,v,z;if(typeof B=="string"){......


The second:

Request:
GET https://www.privateSite.com/ita/scripts/jquery/qtip/jquery.qtip-1.0.0-rc3.min.js HTTP/1.1
User-Agent: Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: it-IT,it;q=0.9,en;q=0.8
Referer: https://www.privateSite.com/privateSitex-back.jsp
Cookie: sauth=%7B%22version%22%3A%221.1%22%2C%22authenticated%22%3Atrue%2C%22state%22%3A%22user_new_a%22%2C%22lastDay%22%3A%2220160224%22%7D; JSESSIONID=L1tNWN6QGx2K5BwX711Jw31Q94Tf2kJHKvfhC4Lc2G46g7PVfVWx!653275306!-1407959958!10101!-1; _pk_id.1.c524=54b13f865236862b.1450721989.10.1456339595.1456339595.; _pk_ses.1.c524=*; ACTemp=1; psessionid=L1tNWN6QGx2K5BwX711Jw31Q94Tf2kJHKvfhC4Lc2G46g7PVfVWx!653275306!-1407959958!10101!-1!1456339584296; _pk_id.22.c524=b304aaa31a2c511b.1450722039.8.1456339623.1456339623.; _pk_ses.22.c524=*; _pk_id.23.c524=f3b23fed925d38e0.1450721989.9.1456339623.1456339595.; _pk_ses.23.c524=*; _nvis_cl5=1456339628528%2C111111111; visitz=OYtYbaDGUgPonUEpZ3ggvEqVnPSKhGELpi61vgf5UHpaMFXJrvgXwJujOETuZU3gjXtzomoYBwTCaNytx8JneucvgZQ44jh2fPO0xfM1dMGBvrtdFxSxxryQEaIgCUWOuogEFX7nLeJoQ8258f5gYo; _SellaCheckFlag=1456339622242; _gat=1; _ga=GA1.2.1138497230.1450721989; _gali=Avanti
Connection: Keep-Alive
Host: www.privateSite.com

Response
HTTP/1.1 502 Bad Gateway
Content-Length: 1417
Content-Type: text/plain; charset=UTF-8

ZAP Error [java.net.SocketException]: Pipe rotta

Stack Trace:
java.net.SocketException: Broken Pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:857)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:828)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.parosproxy.paros.network.HttpOutputStream.flush(Unknown Source)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.writeHttpResponse(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:744)

The third:
Request:
GET https://server.privateSite.com/FrontEnd/Scripts/deployJava.js?201602171748895 HTTP/1.1
User-Agent: Opera/9.80 (X11; Linux x86_64) Presto/2.12.388 Version/12.16
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: it-IT,it;q=0.9,en;q=0.8
Referer: https://server.privateSite.com/FrontEnd/Internet/Gbs.aspx
Cookie: ASP.NET_SessionId=cpq0hqsibuh3nf5mxw2jdipc; ids=f239979e45c476617e2ff159ac4457778511b5d3e16a4b9bc9f9a0d1849387; _gat=1; _gali=Avanti; _ga=GA1.2.1138497230.1450721989
Connection: Keep-Alive
Host: server.privateSite.com

Response:
ZAP Error [java.net.SocketException]: Pipe rotta

Stack Trace:
java.net.SocketException: Broken Pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:857)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:828)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.parosproxy.paros.network.HttpOutputStream.flush(Unknown Source)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at org.parosproxy.paros.network.HttpOutputStream.write(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.writeHttpResponse(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:744)

------------------------------------------------------

**Comment by famedoro** [comment]
@thc202 
Despite the exception everything seems to work, except for the problem that I do not receive traffic from websocket.

Thanks for your help.

**Comment by kingthorin** [comment]
Is this still an issue?
