### ISSUE TITLE
Error in sessions view with tokens

### ISSUE THREAD

**Issue by Lux0r87** [zaproxy/zaproxy#2246]
The sessions view throws an exception, when trying to show a session which contains a token that starts with a number. This only happens for the XML output format, JSON and HTML work properly.

### Exception:
ERROR API - INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified.
org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createElement(CoreDocumentImpl.java:622)
	at org.zaproxy.zap.extension.api.ApiResponseSet.toXML(Unknown Source)
	at org.zaproxy.zap.extension.api.ApiResponseList.toXML(Unknown Source)
	at org.zaproxy.zap.extension.api.ApiResponseList.toXML(Unknown Source)
	at org.zaproxy.zap.extension.api.API.responseToXml(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce:
1. Start ZAP and a browser with ZAP's proxy settings (e.g. localhost, port: 8090)
2. Open a page in the browser, which contains a session token starting with a number
	* Open a web page of your choice (e.g. http://example.com)
	* [Add a session token](http://zap/UI/httpSessions/action/addSessionToken) that starts with a number (e.g. 1234567890)
	* [Set the session token value](http://zap/UI/httpSessions/action/setSessionTokenValue)
3. Open the [sessions view](http://zap/UI/httpSessions/view/sessions) and select XML as output format

==> The error occurs, see log file [zap.zip](https://github.com/zaproxy/zaproxy/files/135853/zap.zip).

### Possible solutions:
1. Don't use the token names as element names.
2. Add a prefix to the element names, to prevent that they start with a number, e.g. token_{tokenName}.

**Comment by Lux0r87** [comment]
According the possible solution No. 2:
It seems that it's actually enough to add an underscore as a prefix.
> Element names must start with a letter or underscore
[XML Naming Rules](http://www.w3schools.com/xml/xml_elements.asp)
