### ISSUE TITLE
Zest - Should not be able to delete THEN statement

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2295]
Steps to reproduce the issue:
1. Run ZAP with Zest add-on installed;
2. Create a Zest Proxy script with "Proxy default template.zst";
3. Select the statements "THEN" and "Comment: Called for the request.Set re..." and delete them, context menu "Delete";
4. Note that both statements are deleted, attempting to move the "IF" statement (context menu, "Move Up") results in an exception:
```
530649 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.IndexOutOfBoundsException: Index: -2, Size: 1
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at org.mozilla.zest.core.v1.ZestScript.add(ZestScript.java:199)
	at org.mozilla.zest.core.v1.ZestScript.move(ZestScript.java:214)
	at org.zaproxy.zap.extension.zest.ExtensionZest.moveNodeUp(ExtensionZest.java:990)
	at org.zaproxy.zap.extension.zest.menu.ZestPopupZestMove$1.actionPerformed(ZestPopupZestMove.java:82)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

Reproduced with:
 - ZAP 2.4.3;
 - "Zest - Graphical Security Scripting Language" version 19, older versions might also be affected.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#261.
