### ISSUE TITLE
Zest - Exception while adding Zest Condition

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2296]
Steps to reproduce the issue:
1. Run ZAP with Zest add-on installed;
2. Create a Zest Proxy script, with "Proxy default template.zst";
3. Select the statement "Comment: Proxy  scripts are called for ..." and attempt to add a Zest Condition, context menu "Add Zest Condition" > "Empty AND";
4. Check the log file, there should be an exception:
```
183136 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: Unexpected parent node: org.mozilla.zest.core.v1.ZestComment@3dd6fec8 Comment: Proxy  scripts are called for ...
	at org.zaproxy.zap.extension.zest.ExtensionZest.addToParent(ExtensionZest.java:854)
	at org.zaproxy.zap.extension.zest.ExtensionZest.addToParent(ExtensionZest.java:825)
	at org.zaproxy.zap.extension.zest.menu.ZestAddConditionPopupMenu$1.actionPerformed(ZestAddConditionPopupMenu.java:262)

```

Reproduced with:
 - ZAP 2.4.3;
 - "Zest - Graphical Security Scripting Language" version 19, older versions might also be affected.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#261.
