### ISSUE TITLE
Zest - Statement lost after drag and drop

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2299]
Steps to reproduce the issue:
1. Run ZAP with Zest add-on installed;
2. Create a Zest Proxy script, with "Proxy default template.zst";
3. Drag  the IF statement and drop it between itself and the above comment and note that it disappears (instead of staying in the same place);
4. Check the log file, there should be an exception, most likely a side effect of being lost:
```
46411 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException: 1 >= 1
	at java.util.Vector.elementAt(Vector.java:474)
	at javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:245)
	at javax.swing.tree.DefaultTreeModel.getChild(DefaultTreeModel.java:174)
	at javax.swing.plaf.basic.BasicTreeUI.getDropLineRect(BasicTreeUI.java:1324)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.repaintDropLocation(BasicTreeUI.java:3472)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3458)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8430)
	at javax.swing.JTree.setDropLocation(JTree.java:1456)
	at javax.swing.TransferHandler$DropHandler.setComponentDropLocation(TransferHandler.java:1452)
	at javax.swing.TransferHandler$DropHandler.cleanup(TransferHandler.java:1570)
	at javax.swing.TransferHandler$DropHandler.drop(TransferHandler.java:1550)
	at java.awt.dnd.DropTarget.drop(DropTarget.java:455)
```

Reproduced with:
 - ZAP 2.4.3;
 - "Zest - Graphical Security Scripting Language" version 19, older versions might also be affected.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#263.
