### ISSUE TITLE
Zest - Exception while pasting IF statement (after deleting it)

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2301]
Steps to reproduce the issue:
1. Run ZAP with Zest add-on installed;
2. Create a Zest Proxy script, with "Proxy default template.zst";
3. Copy the IF statement and after that delete it;
4. Paste it into the script again and note that nothing happens;
5. Check the log file, there should be an exception:
```
168746 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException
	at org.zaproxy.zap.extension.zest.ZestTreeModel.addToNode(ZestTreeModel.java:75)
	at org.zaproxy.zap.extension.zest.ZestTreeModel.addToNode(ZestTreeModel.java:94)
	at org.zaproxy.zap.extension.zest.ExtensionZest.addToParent(ExtensionZest.java:836)
	at org.zaproxy.zap.extension.zest.ExtensionZest.addToParent(ExtensionZest.java:825)
	at org.zaproxy.zap.extension.zest.ExtensionZest.pasteToNode(ExtensionZest.java:1306)
	at org.zaproxy.zap.extension.zest.ExtensionZest.pasteToNode(ExtensionZest.java:1273)
	at org.zaproxy.zap.extension.zest.ExtensionZest.pasteToNode(ExtensionZest.java:1269)
	at org.zaproxy.zap.extension.zest.menu.ZestPopupNodePaste$1.actionPerformed(ZestPopupNodePaste.java:78)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
```

Remarks:
Expected the IF statement to be in the clipboard so, deleting the original would have no side effects.

Reproduced with:
 - ZAP 2.4.3;
 - "Zest - Graphical Security Scripting Language" version 19, older versions might also be affected.

**Comment by kingthorin** [comment]
ZAP DEV Build
[id=zest, version=48.6.0]

Still happening (this comment isn't meant to rush anything, the current exception just provides slightly more detail):

```

78602598 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "AWT-EventQueue-0"
java.lang.NullPointerException: Cannot invoke "org.zaproxy.zest.core.v1.ZestElement.getElementType()" because "za" is null
	at org.zaproxy.zap.extension.zest.ZestTreeModel.addToNode(ZestTreeModel.java:74) ~[?:?]
	at org.zaproxy.zap.extension.zest.ZestTreeModel.addToNodeAt(ZestTreeModel.java:164) ~[?:?]
	at org.zaproxy.zap.extension.zest.ZestTreeModel.addAfterNode(ZestTreeModel.java:204) ~[?:?]
	at org.zaproxy.zap.extension.zest.ExtensionZest.addAfterRequest(ExtensionZest.java:864) ~[?:?]
	at org.zaproxy.zap.extension.zest.ExtensionZest.addAfterRequest(ExtensionZest.java:973) ~[?:?]
	at org.zaproxy.zap.extension.zest.ExtensionZest.pasteToNode(ExtensionZest.java:1382) ~[?:?]
	at org.zaproxy.zap.extension.zest.ExtensionZest.pasteToNode(ExtensionZest.java:1347) ~[?:?]
	at org.zaproxy.zap.extension.zest.menu.ZestPopupNodePaste.lambda$initialize$0(ZestPopupNodePaste.java:70) ~[?:?]
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at ...

```
