### ISSUE TITLE
Spider Failing with "Does Not Exist" Upon API Call Java api 2.4 v10.

### ISSUE THREAD

**Issue by ndoell** [zaproxy/zaproxy#2303]
Hi,

I am using the stable docker container of owasp/zap2docker-stable to conduct spidering and attacking. Below I used bodgeit for the example.

Step 1: docker run --name "ZAP" -d -p 8090:8090 -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config api.disablekey=true

Step 2: I use a java app using zap-api-2.4-v10.jar to automated this but I think it's easier to show on the ZAP docker container API UI.

By default the API sets the contextName parameter which can be left empty.  
The default request is not working containing contextName: 
http://<0.0.0.0>:8090/JSON/spider/action/scan/?zapapiformat=JSON&url=http%3A%2F%2F192.168.1.154%3A8080%2Fbodgeit%2F&maxChildren=&recurse=&contextName=

Returns: {"code":"does_not_exist","message":"Does Not Exist"}

What works (Removed contextName param): 
http://<0.0.0.0>:8090/JSON/spider/action/scan/?zapapiformat=JSON&url=http%3A%2F%2Flocalhost%3A8080%2Fbodgeit%2F&maxChildren=&recurse=

Returns: {"scan":"0"}

**Comment by ndoell** [comment]
Just saw this issue which is the same: https://github.com/zaproxy/zaproxy/issues/2108

But says it was resolved in version 9?  I am using version 10 for the java api client.

**Comment by thc202** [comment]
How are you calling the scan method? The parameter "contextname" must be null to not be sent.

**Comment by ndoell** [comment]
I am calling it as the following:

ApiResponse resp = api.spider.scan(apikey, target, "", "", "");

**Comment by thc202** [comment]
OK, the last parameter must be null otherwise it will be sent and trigger the issue (#2122).

**Comment by ndoell** [comment]
Thanks for the quick responses.  I am leaving the last quotations empty in api.spider.scan request as seen above but still receiving the "Does not exist" error.  Possibly this is related to the docker instance of ZAP, I'll give it a shot with a locally installed OS X version of ZAP.

**Comment by thc202** [comment]
Note that you really need to set it to null:
```Java
ApiResponse resp = api.spider.scan(apikey, target, "", "", null);
```
so the ZAP API client knows that it must not sent it.

**Comment by ndoell** [comment]
Thank you! :)

**Comment by thc202** [comment]
You're welcome!

**Comment by ferdasonmez** [comment]
Hi,
I am using the ZAP JAVA API for the first time. I am getting this error.

Spider : http://www.xxxxxx.com/
Open URL: http://zap/xml/spider/action/scan/?contextName=Default+Context&apikey=apikey&url=http%3A%2F%2Fwww.milliyet.com%2F&maxChildren=10000&
Exception : java.net.SocketException: Unexpected end of file from server
org.zaproxy.clientapi.core.ClientApiException: java.net.SocketException: Unexpected end of file from server
	at org.zaproxy.clientapi.core.ClientApi.callApiDom(ClientApi.java:307)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:289)
	at org.zaproxy.clientapi.gen.Spider.scan(Spider.java:213)
	at tr.com.ferda.owasp.zap.ZapReader.main(ZapReader.java:24)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.zaproxy.clientapi.core.ClientApi.getConnectionInputStream(ClientApi.java:314)
	at org.zaproxy.clientapi.core.ClientApi.callApiDom(ClientApi.java:305)
	... 3 more

Process finished with exit code 0

**Comment by thc202** [comment]
Most likely the API is not correct or the source address is not allowed. [1] [2]

[1] https://github.com/zaproxy/zaproxy/wiki/FAQapikey
[2] https://github.com/zaproxy/zaproxy/wiki/FAQremote

**Comment by psiinon** [comment]
Please dont ask questions in issues, and especially not closed ones.
The ZAP User Group is a more suitable place for questions: https://groups.google.com/group/zaproxy-users
