### ISSUE TITLE
Ability to manage Sites in ZAP via API

### ISSUE THREAD

**Issue by alienatix** [zaproxy/zaproxy#2342]
It would be great to be able to manage Sites in ZAP via API. Right now once site is added (while proxying requests through ZAP), it's only possible to remove it via GUI.

**Comment by psiinon** [comment]
Yeah, the API should be able to do pretty much everything the UI can do, so +1 for this

**Comment by okwrite** [comment]
+1

**Comment by DarkPrince304** [comment]
I'm currently looking into this so I would like to get assigned to this :)
By the way it would be good if we could discuss the method and the parameter names for this API action.

**Comment by alienatix** [comment]
I would start from ability to remove sites:

`/sites/action/removeSite/`

params:
`url - delete a site's url (exact match)`
`recurse - delete all sites that contain the url`

**Comment by DarkPrince304** [comment]
@alienatix I was wondering if we set `recurse` to false and if only the parent is meant to be deleted and not the children, what will take the place of the parent?

Or should we keep it similar to GUI where you right click a node and if you delete all its subnodes are deleted without having the choice of just deleting the parent.

**Comment by kingthorin** [comment]
IMHO the first implementation should be as close to guide functionality as possible.

You dont want to orphan any content. Think of it like a tree, if you cut a branch you don't expect the leaves to stay in place defying gravity. (They go with the branch.)

**Comment by alienatix** [comment]
@DarkPrince304 @kingthorin your suggestions make a lot of sense!

**Comment by thc202** [comment]
@kingthorin the nodes could be left in place (with temporary requests), like when the nodes are created for a request with a path with many segments. But it might not be a required/useful functionality.

**Comment by alienatix** [comment]
I downloaded the most recent docker image with weekly build and experience the following issue (running it on Ubuntu in headless mode: zap.sh -daemon). Seems it happens when I delete site via API:

> 414035 [ZAP-ProxyThread-236] ERROR org.zaproxy.zap.extension.history.PopupMenuPurgeSites  - 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:234)
	at org.parosproxy.paros.extension.history.LogPanel.initialize(LogPanel.java:131)
	at org.parosproxy.paros.extension.history.LogPanel.<init>(LogPanel.java:116)
	at org.parosproxy.paros.extension.history.ExtensionHistory.getLogPanel(ExtensionHistory.java:179)
	at org.parosproxy.paros.extension.history.ExtensionHistory.clearLogPanelDisplayQueue(ExtensionHistory.java:193)
	at org.zaproxy.zap.extension.history.PopupMenuPurgeSites.purge(PopupMenuPurgeSites.java:97)
	at org.zaproxy.zap.extension.history.PopupMenuPurgeSites.purge(PopupMenuPurgeSites.java:82)
	at org.zaproxy.zap.extension.history.PopupMenuPurgeSites.purge(PopupMenuPurgeSites.java:82)
	at org.zaproxy.zap.extension.api.CoreAPI.handleApiAction(CoreAPI.java:457)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:321)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:338)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:244)
	at java.lang.Thread.run(Thread.java:745)

@DarkPrince304 may be you can look into it

**Comment by psiinon** [comment]
Fixed in https://github.com/zaproxy/zaproxy/pull/2497

**Comment by alienatix** [comment]
Thanks!
