### ISSUE TITLE
Show a more informative message on read timeouts through the proxy

### ISSUE THREAD

**Issue by tuxayo** [zaproxy/zaproxy#2400]
When connecting to https://webchat.freenode.net/ through ZAP (whatever random nickname will do)
And being idle for few minute (being in a channel is not even needed)
Then some requests (that look like heartbeats) will timeout with 504 error
![capture d ecran_2016-04-13_18-26-21](https://cloud.githubusercontent.com/assets/2678215/14501186/703c4138-01a5-11e6-89a4-9e0507a606e4.png)
And the response of the request will be
```
ZAP Error [java.net.SocketTimeoutException]: Read timed out

Stack Trace:
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
	at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
	at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
	at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodBase.readResponse(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodBase.execute(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

```
Which will lead to an alert box saying "Error: connection closed after several requests failed."
Whereas sending a message will always succeed. Although I couldn't find the difference between the heartbeat requests and the message requests (except the message of course)

Related to #2399

**Comment by kingthorin** [comment]
An alert from ZAP or form your web browser?

**Comment by tuxayo** [comment]
In the browser 
![capture d ecran_2016-04-13_19-09-43](https://cloud.githubusercontent.com/assets/2678215/14502381/51029af0-01ab-11e6-9f2a-fca451046f84.png)

**Comment by kingthorin** [comment]
Hmmm interesting looking at your screenshot what's the difference between a P request and an S request? 

Because there's a P request that returns 200/html, then a S that returns 200/html, then a S that returns 200/plain, then the S requests start returning 504/plain.
[Do you see the same sequence when ZAP isn't in place?]

How are things set for ZAP's Local Proxy settings with regard to "Modify/Remove "Accept-Encoding" request-header" and "Always unzip gzipped content"

**Comment by kingthorin** [comment]
Looking at the "heartbeat" (or whatever) during a normal session each request is just over 30,000ms.

In ZAP try going Tools > Options > Connection and set your timeout as 35sec.

**Comment by tuxayo** [comment]
> what's the difference between a P request and an S request? 

A P request is when I send a message, it's followed by one of to S requests(HTML). So there are two kind of S requests (because the "heartbeat" is an S request(plain) too). The type is plain when it contains the ZAP error.

> Do you see the same sequence when ZAP isn't in place?

I see only the requests related to a message that I send.


> How are things set for ZAP's Local Proxy settings with regard to "Modify/Remove "Accept-Encoding" request-header" and "Always unzip gzipped content"

They are booth checked.

> Looking at the "heartbeat" (or whatever) during a normal session each request is just over 30,000ms.
> In ZAP try going Tools > Options > Connection and set your timeout as 35 sec.

Default timeout is 20 seconds. **Setting it to 31 seconds allow the requests to not fail and to show up in ZAP**

**Comment by thc202** [comment]
Thanks for letting us know.

**Comment by tuxayo** [comment]
No problem :)

Is the default timeout that breaks freenode's webchat(and other webapps I guess) not a problem?

**Comment by thc202** [comment]
I would say, no, IMHO a default of 20 seconds is enough for the majority of the cases (which can be easily changed if a higher value is required for a specific case).
Thoughts?

**Comment by kingthorin** [comment]
Agreed

**Comment by psiinon** [comment]
Agreed

**Comment by tuxayo** [comment]
> a default of 20 seconds is enough for the majority of the cases (which can be easily changed if a higher value is required for a specific case).

As #2399 is fixed, it should be easier to spot such a case and think of increasing the timeout right?

**Comment by thc202** [comment]
Yeah, we could also change the error message to suggest that?

**Comment by tuxayo** [comment]
What is the current error message?

**Comment by kingthorin** [comment]
As you quoted in the original report:

> ZAP Error [java.net.SocketTimeoutException]: Read timed out
> 
> Stack Trace:
> java.net.SocketTimeoutException: Read timed out
>     at java.net.SocketInputStream.socketRead0(Native Method)
>     at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
>     .....

If we could separately catch SocketTimeoutException for proxied traffic (vs. Active scan or spider), we could supress the stack trace and add something like:
`A SocketTimeoutException occurred, consider adjusting ZAP's default time out in the Connection options panel.`
(Or something like that?)

**Comment by psiinon** [comment]
Or something like: "Failed to connect to site: https:///www.example.com within 20 secs, check to see if the site is available and if so consider adjusting ZAP's default time out in the Connection options panel."

**Comment by thc202** [comment]
OK, I'll take this.
