### ISSUE TITLE
Unable to dynamically uninstall WebSockets add-on

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2436]
Steps to reproduce the issue:
1. Run ZAP with add-ons WebSockets (version 10) and AdvFuzzer (version 14) installed.
2. Try uninstall WebSockets add-on;
3. Note that it shows an alert dialogue saying that it was not possible to successfully uninstall it;
4. Check the log file, there should be an exception:
```
28349 [SwingWorker-pool-1-thread-1] ERROR org.zaproxy.zap.control.AddOnInstaller  - An error occurred while uninstalling the extension "ExtensionWebSocketFuzzer" bundled in the add-on "websocket":
java.lang.NullPointerException
	at org.zaproxy.zap.extension.websocket.fuzz.ExtensionWebSocketFuzzer.unload(ExtensionWebSocketFuzzer.java:145)
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtension(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtensions(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.uninstall(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.removeAddOnImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.removeAddOn(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstall(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$1100(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$10.doInBackground(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$10.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
28369 [SwingWorker-pool-1-thread-1] WARN org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - Not all add-ons were successfully uninstalled: [[id=websocket, fileVersion=10]]
```

Remarks:
The issue only happens if the add-on AdvFuzzer is installed (the ExtensionWebSocketFuzzer is loaded in that case), otherwise the add-on is dynamically unloaded successfully.

ZAP:
Versions >= 2.4.0

**Comment by kingthorin** [comment]
Looks good
