### ISSUE TITLE
GUI freezes while opening Scan Progress dialogue

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2550]
Issue reported in OWASP ZAP Developer Group: https://groups.google.com/d/topic/zaproxy-develop/vMPfHeiRlMM/discussion

Steps to reproduce the issue:
1. Run ZAP;
2. Make sure the option "Options" > "Active Scan" > "Max progress chart in mins" is enabled (it has a value higher than zero);
3. Start an active scan;
4. Open the Scan Progress dialogue and note that the GUI freezes;
5. Check the log file, there should be a lot of exceptions like:
```
ERROR ScanProgressDialog - You are attempting to add an observation for the time period Wed Jun 08 12:34:56 WEST 2016 but the series already contains an observation for that time period. Duplicates are not permitted.  Try using the addOrUpdate() method.
org.jfree.data.general.SeriesException: You are attempting to add an observation for the time period Wed Jun 08 12:34:56 WEST 2016 but the series already contains an observation for that time period. Duplicates are not permitted.  Try using the addOrUpdate() method.
	at org.jfree.data.time.TimeSeries.add(TimeSeries.java:519)
	at org.jfree.data.time.TimeSeries.add(TimeSeries.java:562)
	at org.jfree.data.time.TimeSeries.add(TimeSeries.java:548)
	at org.zaproxy.zap.extension.ascan.ScanProgressDialog.showProgress(ScanProgressDialog.java:386)
	at org.zaproxy.zap.extension.ascan.ScanProgressDialog.access$6(ScanProgressDialog.java:368)
	at org.zaproxy.zap.extension.ascan.ScanProgressDialog$4$1.run(ScanProgressDialog.java:472)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Remarks:
The problem might not happen always (it depends on how fast/slow ZAP (i.e. its threads) is processed).

ZAP Versions:
Versions >= 2.4.3

**Comment by kingthorin** [comment]
Looks good
