### ISSUE TITLE
Fuzzer consuming all memory on error

### ISSUE THREAD

**Issue by NVolcz** [zaproxy/zaproxy#2568]
If the fuzzer is accidentally set up in an incorrect manner its fuzzer error messages will quickly consume all available memory.

This also freezes the GUI because:
```
"AWT-EventQueue-0" - Thread t@18
   java.lang.Thread.State: RUNNABLE
	at java.util.Arrays.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at javax.swing.DefaultRowSorter.rowsInserted0(Unknown Source)
	at javax.swing.DefaultRowSorter.rowsInserted(Unknown Source)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsInserted(DefaultSortController.java:404)
	at javax.swing.JTable.notifySorter(Unknown Source)
	at javax.swing.JTable.sortedTableChanged(Unknown Source)
	at javax.swing.JTable.tableChanged(Unknown Source)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(Unknown Source)
	at org.zaproxy.zap.extension.fuzz.httpfuzzer.ui.HttpFuzzerErrorsTableModel$1.run(HttpFuzzerErrorsTableModel.java:52)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
```

In my case this resulted in over 820 000 errors, most containing the error:
```org.parosproxy.paros.network.HttpMalformedHeaderException: Failed to find pattern: (\w+) +([^\r\n]+) +(HTTP/\d+\.\d+)```

A solution could be to group errors with the same message or stop the fuzzer if most requests results in errors.

**Comment by thc202** [comment]
The fuzzer already allows to stop after some number of errors, it's not enabled by default, though, maybe it should?

**Comment by NVolcz** [comment]
I would like it to be. It is not pleasant to lose parts of your session. Part of the problem is that the GUI is to dependent on the rest of the application and easily hangs. I guess this is solved when ZAP-as-a-service is complete(?).

**Comment by thc202** [comment]
OK, will change that option to be enabled by default.

Hopefully, yes.
