### ISSUE TITLE
Customize HTML Report throwing OOME 

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#2591]
Issue reported in IRC channel (#websectools).

Steps to reproduce the issue:
1. Run ZAP with CustomReport add-on installed;
2. Spider or scan a site, that raises alerts;
3. Create a custom HTML report (Report > Customize HTML Report);
4. Note that nothing happens (for a while);
5. Check the log file, there should be an exception:

```
[AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
    at java.lang.StringBuffer.append(StringBuffer.java:272)
    at java.io.StringWriter.write(StringWriter.java:101)
    at org.dom4j.io.XMLWriter.writeNodeText(XMLWriter.java:1291)
    at org.dom4j.io.XMLWriter.writeNode(XMLWriter.java:1311)
    at org.dom4j.io.XMLWriter.writeElementContent(XMLWriter.java:1122)
    at org.dom4j.io.XMLWriter.writeElement(XMLWriter.java:949)
    at org.dom4j.io.XMLWriter.writeNode(XMLWriter.java:1301)
    at org.dom4j.io.XMLWriter.writeElementContent(XMLWriter.java:1136)
    at org.dom4j.io.XMLWriter.writeElement(XMLWriter.java:954)
    at org.dom4j.io.XMLWriter.writeNode(XMLWriter.java:1301)
    at org.dom4j.io.XMLWriter.writeElementContent(XMLWriter.java:1136)
    at org.dom4j.io.XMLWriter.writeElement(XMLWriter.java:954)
    at org.dom4j.io.XMLWriter.writeNode(XMLWriter.java:1301)
    at org.dom4j.io.XMLWriter.writeElementContent(XMLWriter.java:1136)
    at org.dom4j.io.XMLWriter.writeElement(XMLWriter.java:954)
    at org.dom4j.io.XMLWriter.writeNode(XMLWriter.java:1301)
    at org.dom4j.io.XMLWriter.writeElementContent(XMLWriter.java:1136)
    at org.dom4j.io.XMLWriter.writeElement(XMLWriter.java:954)
    at org.dom4j.io.XMLWriter.writeNode(XMLWriter.java:1301)
    at org.dom4j.io.XMLWriter.write(XMLWriter.java:344)
    at org.dom4j.tree.AbstractDocument.asXML(AbstractDocument.java:81)
    at org.zaproxy.zap.extension.customreport.ReportParser.selectExpectedAlerts(ReportParser.java:95)
    at org.zaproxy.zap.extension.customreport.ReportLastScan.generate(ReportLastScan.java:91)
    at org.zaproxy.zap.extension.customreport.ReportLastScan.generateReport(ReportLastScan.java:243)
    at org.zaproxy.zap.extension.customreport.ExtensionCustomReport.generateReport(ExtensionCustomReport.java:145)
    at org.zaproxy.zap.extension.customreport.OptionDialog$2.actionPerformed(OptionDialog.java:79)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
```

Remarks:
Reproduced with default memory settings (i.e. heap memory automatically set to 512M).
The issue depends on the number of alerts and which report options are enabled (for example, if the contents of the messages are included).

Add-On:
CustomReport version >= 1.

ZAP:
v2.5.0

**Comment by thc202** [comment]
Closing, the Custom Report add-on is being superseded by the Report Generation add-on:
https://www.zaproxy.org/docs/desktop/addons/report-generation/
