### ISSUE TITLE
Java 9 (9-ea)

### ISSUE THREAD

**Issue by alfsb** [zaproxy/zaproxy#2602]
Zap fails with new Java 9:

    ~/ZedAttackProxy/zap250$ ./zap.sh
    ./zap.sh: linha 49: [: 9-ea: esperado expressão de número inteiro
    Exiting: ZAP requires a minimum of Java 7 to run, found 9-ea

**Comment by alfsb** [comment]
May be related. Removing the `if` on `zap.sh` line 49 results in:

    ~/ZedAttackProxy/zap250$ ./zap.sh 
    Available memory: 16004 MB
    Setting jvm heap size: -Xmx512m
    Can't find bundle for base name Messages, locale en_GB

**Comment by mozfreddyb** [comment]
I have a similar problem, but the version reported is "9-ubuntu".
> zap.sh: line 48: [: 9-Ubuntu: integer expression expected
> Exiting: ZAP requires a minimum of Java 7 to run, found 9-Ubuntu

**Comment by thc202** [comment]
All Java 9 related issues reported so far should be fixed. Leaving this open for now.

**Comment by thc202** [comment]
Per #3919, ZAP does not compile with Java 9.

**Comment by thc202** [comment]
As reported in #3934, the add-on Access Control Testing does not work correctly with Java 9:
```
120727 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.ExceptionInInitializerError
        at org.zaproxy.zap.extension.accessControl.view.ContextAccessControlPanel$AccessRuleNodeCellRenderer.getTreeCellRendererComponent(ContextAccessControlPanel.java:300)
        at org.jdesktop.swingx.JXTree$DelegatingRenderer.getTreeCellRendererComponent(JXTree.java:1269)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(Unknown Source)
        at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setModel(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setModel(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
        at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
        at java.desktop/javax.swing.JTree.setModel(Unknown Source)
        at org.jdesktop.swingx.JXTree.setModel(JXTree.java:1532)
        at org.jdesktop.swingx.JXTreeTable.setTreeTableModel(JXTreeTable.java:1238)
        at org.zaproxy.zap.extension.accessControl.view.ContextAccessControlPanel.initContextData(ContextAccessControlPanel.java:233)
        at org.parosproxy.paros.view.SessionDialog.initContextPanel(SessionDialog.java:125)
        at org.parosproxy.paros.view.SessionDialog.initParam(SessionDialog.java:111)
        at org.parosproxy.paros.view.View.showSessionDialog(View.java:689)
        at org.parosproxy.paros.view.View.showSessionDialog(View.java:657)
        at org.parosproxy.paros.control.MenuFileControl.properties(MenuFileControl.java:506)
        at org.zaproxy.zap.view.MainToolbarPanel$7.actionPerformed(MainToolbarPanel.java:357)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.desktop/javax.swing.ImageIcon.<init>(Unknown Source)
        at org.zaproxy.zap.extension.accessControl.widgets.SiteNodeIcons.<clinit>(SiteNodeIcons.java:27)
        ... 60 more
```

The add-on SOAP Scanner is also failing:
```
15374 [ZAP-BootstrapGUI] ERROR org.parosproxy.paros.extension.ExtensionLoader  - javax/xml/soap/SOAPException
java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
	at java.base/java.lang.Class.getConstructor0(Class.java:3315)
	at java.base/java.lang.Class.getConstructor(Class.java:2108)
	at org.zaproxy.zap.control.AddOnLoaderUtils.loadAndInstantiateClassImpl(AddOnLoaderUtils.java:111)
	at org.zaproxy.zap.control.AddOnLoaderUtils.loadDeclaredClasses(AddOnLoaderUtils.java:151)
	at org.zaproxy.zap.control.AddOnLoaderUtils.getActiveScanRules(AddOnLoaderUtils.java:177)
	at org.zaproxy.zap.control.AddOnLoader.getActiveScanRules(AddOnLoader.java:791)
	at org.parosproxy.paros.core.scanner.PluginFactory.initPlugins(PluginFactory.java:99)
	at org.parosproxy.paros.core.scanner.PluginFactory.getLoadedPlugins(PluginFactory.java:131)
	at org.parosproxy.paros.core.scanner.PluginFactory.loadAllPlugin(PluginFactory.java:397)
	at org.zaproxy.zap.extension.ascan.ScanPolicy.<init>(ScanPolicy.java:22)
	at org.zaproxy.zap.extension.ascan.PolicyManager.getAllPolicyNames(PolicyManager.java:68)
	at org.zaproxy.zap.extension.ascan.PolicyManager.init(PolicyManager.java:51)
	at org.zaproxy.zap.extension.ascan.ExtensionActiveScan.postInit(ExtensionActiveScan.java:130)
	at org.parosproxy.paros.extension.ExtensionLoader.hookAllExtension(ExtensionLoader.java:793)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:664)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:57)
	at org.parosproxy.paros.control.Control.init(Control.java:123)
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:299)
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:258)
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:70)
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:200)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:256)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 24 more
```

**Comment by thc202** [comment]
There's an issue when using scripts (can be reproduced by using one of the default pop up menu Extender scripts):
```
ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.BootstrapMethodError: call site initialization exception
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:385)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:250)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:240)
	at jdk.nashorn.javaadapters.org_zaproxy_zap_view_popup_PopupMenuItemHistoryReferenceContainer.isManagingFocus(Unknown Source)
	at java.desktop/javax.swing.JComponent.<init>(JComponent.java:603)
	at java.desktop/javax.swing.AbstractButton.<init>(AbstractButton.java:74)
	at java.desktop/javax.swing.JMenuItem.<init>(JMenuItem.java:145)
	at java.desktop/javax.swing.JMenuItem.<init>(JMenuItem.java:124)
	at org.parosproxy.paros.extension.ExtensionPopupMenuItem.<init>(ExtensionPopupMenuItem.java:73)
	at org.zaproxy.zap.view.popup.ExtensionPopupMenuItemMessageContainer.<init>(ExtensionPopupMenuItemMessageContainer.java:53)
	at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer.<init>(PopupMenuItemHttpMessageContainer.java:111)
	at org.zaproxy.zap.view.popup.PopupMenuItemHistoryReferenceContainer.<init>(PopupMenuItemHistoryReferenceContainer.java:68)
	at org.zaproxy.zap.view.popup.PopupMenuItemHistoryReferenceContainer.<init>(PopupMenuItemHistoryReferenceContainer.java:55)
	at jdk.nashorn.javaadapters.org_zaproxy_zap_view_popup_PopupMenuItemHistoryReferenceContainer.<init>(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2$\^eval\_$cu1$restOf.:program(<eval>:13)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:652)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:517)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:448)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:405)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:154)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.zaproxy.zap.extension.script.ExtensionScript.invokeScriptImpl(ExtensionScript.java:1173)
	at org.zaproxy.zap.extension.script.ExtensionScript.invokeScript(ExtensionScript.java:1112)
	at org.zaproxy.zap.extension.script.ExtensionScript.getInterface(ExtensionScript.java:1519)
	at org.zaproxy.zap.extension.scripts.ExtensionScriptsUI.installExtenderScript(ExtensionScriptsUI.java:833)
	at org.zaproxy.zap.extension.scripts.ExtensionScriptsUI.scriptAdded(ExtensionScriptsUI.java:575)
	at org.zaproxy.zap.extension.script.ExtensionScript.addScript(ExtensionScript.java:563)
	at org.zaproxy.zap.extension.script.ExtensionScript.addScript(ExtensionScript.java:552)
	at org.zaproxy.zap.extension.scripts.dialogs.NewScriptDialog.save(NewScriptDialog.java:238)
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:398)
	at org.zaproxy.zap.view.StandardFieldsDialog.access$1(StandardFieldsDialog.java:388)
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:381)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:269)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6578)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3343)
	at java.desktop/java.awt.Component.processEvent(Component.java:6343)
	at java.desktop/java.awt.Container.processEvent(Container.java:2259)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4961)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4480)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2303)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2758)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.getContext(Context.java:1393)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.getContextTrusted(Context.java:1303)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.fromClass(Context.java:1419)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Context.getDynamicLinker(Context.java:1315)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.Bootstrap.bootstrap(Bootstrap.java:223)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.JavaAdapterServices.bootstrap(JavaAdapterServices.java:206)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:324)
	... 69 more
```
This looks like a JRE issue, similar to:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8164748
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8134304

**Comment by thc202** [comment]
A bug report was submitted for the above issue (https://github.com/zaproxy/zaproxy/issues/2602#issuecomment-343246334), it's in review process.

**Comment by thc202** [comment]
The bug was created:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8191196

**Comment by kingthorin** [comment]
Note the groovy and jython addons are now reporting Illegal reflective access as well:

```console
> Task :addOns:jython:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/home/travis/.gradle/caches/modules-2/files-2.1/org.python/jython-standalone/2.7.1/942c3294840dc9dfb3528d775f4d02a6d57c421f/jython-standalone-2.7.1.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

```console
> Task :addOns:groovy:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/travis/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.14/cd1a8ce914f5fe86c00a917b0577da6f367edcf9/groovy-all-2.4.14.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by kingthorin** [comment]
The groovy and jython issues seem to have been addressed in previous Dependency Update PRs.

**Comment by thc202** [comment]
The warnings with the reports are no longer happening.
