### ISSUE TITLE
Error on Debian with Java 8: "Could not generate DH keypair"

### ISSUE THREAD

**Issue by fd0** [zaproxy/zaproxy#2626]
Hi,

I'm trying to use ZAP on Debian with OpenJDK8 (package is `openjdk-8-jre`, Version `8u91-b14-1~bpo8+1`). Accessing a website via HTTPS through ZAP with a browser configured properly (CA is installed and configured) leads to the following error (most of the time, see notes below):

```
ZAP Error [javax.net.ssl.SSLException]: java.lang.RuntimeException: Could not generate DH keypair

Stack Trace:
java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 2048 (inclusive)
at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120)
at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:674)
at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:128)
 [wrapped] java.lang.RuntimeException: Could not generate DH keypair
at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:142)
at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:114)
at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:708)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:268)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
 [wrapped] javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown Source)
at org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
at java.lang.Thread.run(Thread.java:745)
```

These are my notes so far:
- It looks like ZAP is trying to create DH parameters larger than 2048 bit, this will be supported in Java 9, [thread on stackoverflow](http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception), [OpenJDK bugtracker](https://bugs.openjdk.java.net/browse/JDK-8072452)
- Using burpsuite works, with the same version of Java
- It seems Fedora patched OpenJDK to allow larger primes: https://bugzilla.redhat.com/show_bug.cgi?id=1163501
- It looks like the size of the DH parameters is provided by the server: [thread on stackoverflow](http://stackoverflow.com/a/21617747)
- Whether this error occurs depends on the Server: It works well with TLS servers with small DH groups, but due to the mitigation for the Logjam attack, everybody generated large, custom DH parameters.
- I've tried the latest released version (2.5.0) and the latest nightly version of ZAP, no difference.

Is there anything I can do to help you debug this problem further? 

I'd really like to use ZAP, is it maybe possible to configure the SSLContext to only accept ciphers which do not use DH with a Java version that is unable to handle large DH parameters? How do other program work around this limitation?

**Comment by kingthorin** [comment]
You could try 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files' https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake

**Comment by fd0** [comment]
Thanks for the suggestion, but unfortunately installing the unlimited JCE does not help at all. Tried it, same error, which is consistent with what others report, e.g. here: http://stackoverflow.com/questions/14253039/is-there-a-workaround-for-java-lang-runtimeexception-could-not-generate-dh-key/21617747

**Comment by kingthorin** [comment]
Ok, that's fair.

I'm not sure what PortSwigger has done with BurpSuite to work around the issue. 
I did see one suggestion (in the links you provided) of not allowing the client to offer DH as an option. So there are probably two things we could do:

1. Have an option to disable or exclude DH suites from the client set (in the standard option(s) screens, which would be a somewhat static & user controlled solution).
2. Try to catch this condition and (assuming we could specifically identify it @ SSLConnector) and after an initial failure log a relevant message and create a new SSL context with DH disabled (which would be more of a dynamic solution). Not sure how easy/hard that might be...

Would you be able to tell us, either: What the site is that you're connecting to? or What the DH prime size is that it's trying to use?

Have you been able to try with the Oracle JRE?

**Comment by fd0** [comment]
I've also tested this with Oracle Java 8: Same error. I've ran into this issue at work and I'm not able to disclose the server. It can however be easily reproduce on the [TLS DHE Test Page](https://dh.tlsfun.de/) by Hanno Böck, try accessing the following images through ZAP:
 * Works: `https://dh2048.tlsfun.de/good.png`
 * Does not work: `https://dh4096.tlsfun.de/good.png`

**Comment by kingthorin** [comment]
Thanks!

**Comment by fd0** [comment]
Hey, any progress on this issue? Is there anything I can do to help? This bugged me again today...

**Comment by thc202** [comment]
I'm not aware of anyone working on this issue. Are you able to dive into the code? We also need to discuss what's the best fix.

It's possible to access the previous examples using Java 9 (EA) and latest ZAP weekly release.

**Comment by fd0** [comment]
Thanks for responding. Unfortunately, I don't have the time to fix this myself. I'll try with Java 9 and ZAP weekly.

**Comment by kingthorin** [comment]
@fd0 did Java 9 work for you?

**Comment by fd0** [comment]
Sorry, I did not yet have the time to try this.

**Comment by kingthorin** [comment]
@fd0 did you ever get a chance to try Java 9?

**Comment by fd0** [comment]
Nop, but I'll try to do that next week. :)

**Comment by fd0** [comment]
I've just tried with the Debian `openjdk-9-jre` package with ZAP 2.6.0 and I can confirm that it works. It's just a hassle to install this package (don't get me started).

```
$ java -version
openjdk version "9-Debian"
OpenJDK Runtime Environment (build 9-Debian+0-9b170-2)
OpenJDK 64-Bit Server VM (build 9-Debian+0-9b170-2, mixed mode)
```

**Comment by kingthorin** [comment]
@fd0 thanks for checking and letting us know!

**Comment by fd0** [comment]
FYI, openjdk-9-jre can just be installed on the latest Debian stable release ("stretch"). Maybe we can close this issue, what's your take on this?

**Comment by kingthorin** [comment]
I'm good with closing it. 

https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake
Can be updated with the info.

**Comment by fd0** [comment]
I've added the info there. Thanks!

**Comment by kingthorin** [comment]
Awesome. I totally didn’t mean that as a task for you (or anyone else really). Just wanted to make sure I wrote it somewhere so that I didn’t forget. Thanks!

**Comment by fd0** [comment]
No big deal, I'm glad it's resolved ;)
