### ISSUE TITLE
I got below error when I try to run zap tool on mac and firefox 

### ISSUE THREAD

**Issue by laki88** [zaproxy/zaproxy#2776]
StorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 69f87405-052a-c64e-8029-8f8bf605249f
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.wrapWebDriverExceptionIfConnectionException(WebDriverBackedEmbeddedBrowser.java:878)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.throwIfConnectionException(WebDriverBackedEmbeddedBrowser.java:885)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.goToUrl(WebDriverBackedEmbeddedBrowser.java:265)
	at com.crawljax.core.Crawler.crawlIndex(Crawler.java:446)
	at com.crawljax.core.CrawlTaskConsumer.crawlIndex(CrawlTaskConsumer.java:85)
	at com.crawljax.core.CrawlController.call(CrawlController.java:66)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37)
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread.run(SpiderThread.java:196)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Lakshmans-MacBook-Pro.local', ip: '10.100.5.161', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, handlesAlerts=true, databaseEnabled=true, version=47.0, platform=MAC, nativeEvents=false, acceptSslCerts=true, webStorageEnabled=true, locationContextEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 69f87405-052a-c64e-8029-8f8bf605249f
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.to(RemoteWebDriver.java:969)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.goToUrl(WebDriverBackedEmbeddedBrowser.java:261)
	... 6 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:7055 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:162)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:160)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:380)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 9 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 24 more

crawling not happen. firefox exits without crawaling.

**Comment by thc202** [comment]
Are you using Firefox 47 or 47.0.1? If the former it might be #2739.

**Comment by laki88** [comment]
Hi thc202,

I am using firefox 47. issue may be the reason you pointed. I will check with 47.0.1 version. Thanks a lot.

**Comment by laki88** [comment]
Hi thc202,

After upgrading selenium addon version in zap to 7 and firefox version to 47.0.1, I could run zap without any issue. 

Thanks

**Comment by thc202** [comment]
Great, thanks for letting us know!
