### ISSUE TITLE
Zap Report Generation Bug

### ISSUE THREAD

**Issue by Ncoder1** [zaproxy/zaproxy#2998]
I have ZAP 2.5.0 integrated in a QA setup, where ZAP records all QA Automation test cases and then i perform an Active Scan using ZAP. I have used the JAVA API to interact with ZAP. I do get through successfully generating reports via the zapapi.core.htmlreport(). But sometimes, i get the below error.
I also save my sessions, when i opened it manually and tried to generate a html report through the report tab the same error occurs.

Error (POPUP):

File creation may have failed or is not complete.

Exception:

ERROR ReportGenerator - Character reference "&#
org.xml.sax.SAXParseException; lineNumber: 2361; columnNumber: 1222; Character reference "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.parosproxy.paros.extension.report.ReportGenerator.stringToHtml(Unknown Source)
	at org.parosproxy.paros.extension.report.ReportLastScan.generate(Unknown Source)
	at org.parosproxy.paros.extension.report.ReportLastScan.generateReport(Unknown Source)
	at org.parosproxy.paros.extension.report.ExtensionReport$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by thc202** [comment]
@Ncoder1 do you still have a session that reproduces the issue? Tried some alert fuzzing but no luck reproducing it.

**Comment by Ncoder1** [comment]
@thc202 , sorry i didnt get an update regarding the question ! 

Yes i do have a session (but unfortunately, i might not be able to share it :( But i can help you with any info you want.
But when i opened and tried to run the report through the tabs, i get this error. 

java.io.IOException: Failed to mail or browse file:/Users/user/Docs/ZAPPER/Reports/App/App.html. Error code: -43
	at sun.lwawt.macosx.CDesktopPeer.lsOpen(CDesktopPeer.java:72)
	at sun.lwawt.macosx.CDesktopPeer.browse(CDesktopPeer.java:65)
	at java.awt.Desktop.browse(Desktop.java:386)
	at org.zaproxy.zap.utils.DesktopUtils.openUrlInBrowser(Unknown Source)
	at org.parosproxy.paros.extension.report.ReportLastScan.generateReport(Unknown Source)
	at org.parosproxy.paros.extension.report.ExtensionReport$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Ncoder1** [comment]
@thc202 The full log from the time i opened the session:

016-11-17 10:57:49,043 [AWT-EventQueue-0] INFO  MenuFileControl - opening session file /Users/user/Docs/ZAPPER/Sessions/App/SESSION_2016/11/08 15:15:43.session
2016-11-17 10:57:49,083 [AWT-EventQueue-0] INFO  Control - Open Session
2016-11-17 10:57:49,138 [Thread-7] INFO  ENGINE - dataFileCache commit start
2016-11-17 10:57:49,140 [Thread-7] INFO  ENGINE - dataFileCache commit end
2016-11-17 10:57:49,142 [Thread-7] INFO  ENGINE - Database closed
2016-11-17 10:57:49,290 [Thread-7] INFO  ENGINE - open start - state not modified
2016-11-17 10:57:49,312 [Thread-7] INFO  ENGINE - dataFileCache open start
2016-11-17 10:57:49,330 [Thread-7] INFO  ENGINE - dataFileCache open end
2016-11-17 10:58:46,648 [AWT-EventQueue-0] ERROR ReportGenerator - Character reference "&#
org.xml.sax.SAXParseException; lineNumber: 538; columnNumber: 256; Character reference "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.parosproxy.paros.extension.report.ReportGenerator.stringToHtml(Unknown Source)
	at org.parosproxy.paros.extension.report.ReportLastScan.generate(Unknown Source)
	at org.parosproxy.paros.extension.report.ReportLastScan.generateReport(Unknown Source)
	at org.parosproxy.paros.extension.report.ExtensionReport$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-11-17 10:58:49,809 [AWT-EventQueue-0] ERROR DesktopUtils - Failed to mail or browse file:/Users/etssec/Documents/ZAPPER/Reports/Romulus/Romulus.html. Error code: -43
java.io.IOException: Failed to mail or browse file:/Users/user/Docs/ZAPPER/Reports/App/App.html. Error code: -43
	at sun.lwawt.macosx.CDesktopPeer.lsOpen(CDesktopPeer.java:72)
	at sun.lwawt.macosx.CDesktopPeer.browse(CDesktopPeer.java:65)
	at java.awt.Desktop.browse(Desktop.java:386)
	at org.zaproxy.zap.utils.DesktopUtils.openUrlInBrowser(Unknown Source)
	at org.parosproxy.paros.extension.report.ReportLastScan.generateReport(Unknown Source)
	at org.parosproxy.paros.extension.report.ExtensionReport$1.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Ncoder1** [comment]
@thc202 any update on this issue ?

**Comment by thc202** [comment]
(Sorry for not commenting sooner, this is on my TODO list of things to be done for 2.6.0)

No updates yet, not enough info to address the issue. Do you still have access to the session that exhibits the issue? If so, are you able to run a Stand Alone script? I might provide a script to pinpoint the issue more easily.

**Comment by Ncoder1** [comment]
@thc202, Yes i do have access now. I have got the issue for a different application. i can run a standalone script, please send me the script.

**Comment by Ncoder1** [comment]
@thc202 , I have found the root cause of the issue, Base 64 Disclosure does not stop detecting its instances and the count keeps increasing. So when i try to generate the report its failing. This could be possible for all passive scan vulnerabilities that could keep findings issues and does not stop. I disabled Base 64 Disclosure in Options --> Passive Scan Rules and then i was able to generate the report.

**Comment by thc202** [comment]
@devQA123 are you seeing the same error in the zap.log?

@Ncoder1 thanks for the info, will try reproduce that with the steps provided.

**Comment by devQA123** [comment]
@thc202 , Yes.

2017-08-29 15:45:26,503 [AWT-EventQueue-0] ERROR ReportGenerator - Character reference "&#
org.xml.sax.SAXParseException; lineNumber: 1696; columnNumber: 112382; Character reference "&#
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)

**Comment by thc202** [comment]
OK, thanks.

**Comment by omerlh** [comment]
Just encountered the same error. If that helps, I have a saved session that can be used to reproduce it.

**Comment by thc202** [comment]
Can you share the session (or the alert/fields that causes the issue)? I'm not able to reproduce it so far.

**Comment by omerlh** [comment]
Sure, I'll send you over slack

**Comment by troex** [comment]
@thc202 also having the same issue with 2.7.0 and two latest weekly builds, can provide sessions if needed

**Comment by thc202** [comment]
Sure, let me know what's the best way for you to share it.

@omerlh were you able to send that through slack? (to @psiinon?)

**Comment by troex** [comment]
@thc202 email would work, I can send report to psiinon or maybe you have some shared inbox?

**Comment by psiinon** [comment]
You can email it to me - my username at gmail.com.

**Comment by omerlh** [comment]
@thc202 somehow missed your comment, I'll send it over to @psiinon now also over slack

**Comment by psiinon** [comment]
Noooo! Dont do that - I've been locked out of slack once again :/

**Comment by omerlh** [comment]
Oh no! Sending it to you over mail :)

**Comment by thc202** [comment]
Thank you (all), we now know what the problem is.

**Comment by troex** [comment]
just in time! @psiinon thanks a lot, I need to generate HTML report for SF security review, is this fix included in 08-14 weekly or it will be in next one?
