### ISSUE TITLE
NullPointerException with Zest without Script Console

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3032]
Steps to reproduce the issue:
1. Run ZAP, with Zest and without Script Console;
2. Check the output or log file, there should be an exception:
```
76292 [Thread-10] ERROR org.parosproxy.paros.extension.ExtensionLoader  - 
java.lang.NullPointerException
	at org.zaproxy.zap.extension.zest.dialogs.ZestDialogManager.initialize(Unknown Source)
	at org.zaproxy.zap.extension.zest.dialogs.ZestDialogManager.<init>(Unknown Source)
	at org.zaproxy.zap.extension.zest.ExtensionZest.hook(Unknown Source)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensionImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensions(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.install(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.checkAndInstallAddOnsNotInstalled(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.addAddon(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(Unknown Source)
```

ZAP version:
Version 2.5.0

Add-on:
"Zest - Graphical Security Scripting Language" version 22.

**Comment by thc202** [comment]
Closing, duplicate of #2656 :/
