### ISSUE TITLE
cast exception with Java stacktrace

### ISSUE THREAD

**Issue by EnDe** [zaproxy/zaproxy#3084]
While running ZAP, following (see below) exception occoured. The GUI is corrupted then, means that most part are no longer shown. Some parts will come back if the mouse is hovered over them, but not all. ZAP needs to be killed.
No action/command was done inside ZAP, ZAP was idle for about 6 hours. ZAP process itself was wunning since 5 days.

#----
SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

java -Xmx512m -jar /opt/tools//ZAP_2.5.0/zap-2.5.0.jar -dir /home/
#----

----------------------------- Stacktrace from zap.log (a lot of line snipped)
299549538 [AWT-EventQueue-0] INFO org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzer  - Fuzzer started...
299549577 [ZAP-FuzzerTerminationNotifier-0] INFO org.zaproxy.zap.extension.fuzz.httpfuzzer.HttpFuzzer  - Fuzzer completed.
331988696 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData
	at sun.java2d.xr.XRPMBlitLoops.cacheToTmpSurface(XRPMBlitLoops.java:148)
	at sun.java2d.xr.XrSwToPMBlit.Blit(XRPMBlitLoops.java:356)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:86)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1030)
	at sun.java2d.SunGraphics2D.copyImage(SunGraphics2D.java:3229)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3393)
	at sun.awt.image.ImageRepresentation.drawToBufImage(ImageRepresentation.java:877)
	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1037)
	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:196)
	at sun.java2d.SunGraphics2D.copyImage(SunGraphics2D.java:3229)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3270)
	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3214)
	at javax.swing.text.html.ImageView.paint(ImageView.java:375)
	at javax.swing.text.BoxView.paintChild(BoxView.java:161)
	at javax.swing.text.BoxView.paint(BoxView.java:433)
	at javax.swing.text.BoxView.paintChild(BoxView.java:161)
[snip]
at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by thc202** [comment]
Seems to be https://bugs.openjdk.java.net/browse/JDK-7172749. The fix should be included in 8u112/8u121.

**Comment by EnDe** [comment]
How to proceed with this issue?
I can't change my java currently, hence not tests with newer java. Sorry.

**Comment by thc202** [comment]
It seems there's a workaround:
https://netbeans.org/bugzilla/show_bug.cgi?id=219756#c9

**Comment by EnDe** [comment]
Thanks for the workaround, but I've to admit that it's hard to test.
I'll add  -Dsun.java2d.xrender=false to the JVM. Is tha in  ~/.ZAP/.ZAP_JVM.properties  (file does yet not exist for me)?

You can close this issue as there is no proper way to reproduce it and test it.

**Comment by EnDe** [comment]
-Dsun.java2d.xrender=false  in ~/.ZAP/.ZAP_JVM.properties 
is a workaround

**Comment by thc202** [comment]
Thanks for letting us know!

Closing per previous comments. Hopefully new versions of Java 8 have the issue fixed.
