### ISSUE TITLE
SSLException: Invalid padding length

### ISSUE THREAD

**Issue by almanda70** [zaproxy/zaproxy#3190]
I receive this error.....why????

ZAP Error [javax.net.ssl.SSLException]: Invalid Padding length: 135

Stack Trace:
javax.crypto.BadPaddingException: Invalid Padding length: 135
	at sun.security.ssl.CipherBox.removePadding(Unknown Source)
	at sun.security.ssl.CipherBox.decrypt(Unknown Source)
	at sun.security.ssl.InputRecord.decrypt(Unknown Source)
 [wrapped] javax.net.ssl.SSLException: Invalid Padding length: 135
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.tunnelCreated(Unknown Source)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.tunnelCreated(MultiThreadedHttpConnectionManager.java:1521)
	at org.apache.commons.httpclient.HttpMethodDirector.executeConnect(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by kingthorin** [comment]
Looks like an SSL error.

**Comment by kingthorin** [comment]
To be clear, if you need a more specific answer we kind of need more specifics. (Go figure,eh?)

What version of java?
What java dust (oracle, open, etc)?
What version of zap?
What were you doing when u encountered the error?
Do you know anything about the confit of the server in question?
Do regular browsers connect as expected?

**Comment by almanda70** [comment]
What version of java? Version 8 Update 121
What java dist (oracle, open, etc)? Open
What version of zap? 2.5.0
Do you know anything about the confit of the server in question? No

In OSWAP windows, when try a GET response with a Bad Gateway:
HTTP/1.1 502 Bad Gateway
Content-Length: 2027
Content-Type: text/plain; charset=UTF-8

ZAP Error [javax.net.ssl.SSLException]: Invalid Padding length: 51

**Comment by kingthorin** [comment]
Do regular browsers (IE, Firefox, Chrome) connect as expected?
Have you tried connecting with openssl s_client?

**Comment by almanda70** [comment]
Without OWASP ZAP Explorer can connect....

**Comment by kingthorin** [comment]
@almanda70 are you still experiencing this problem?

Do you have the JCE files installed?
https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake
