### ISSUE TITLE
WAFP Extension not working

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3240]
Steps to reproduce the issue:
1. Run ZAP with WAFP Extension add-on;
2. Select Tools > Fingerprinting tools;
3. Add the target URL and press Fingerprint;
4. Note that nothing happens, in the console output there's;
```
java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException
	at org.zaproxy.zap.extension.cmss.FastFingerprinter.filterResults(FastFingerprinter.java:310)
	at org.zaproxy.zap.extension.cmss.FingerPrintingThread.run(FingerPrintingThread.java:21)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:214)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

**Comment by thc202** [comment]
The add-on is no longer available in the marketplace, since it does not work (because of the missing dependencies and other functional issues). [1]

[1] https://github.com/zaproxy/zap-admin/commit/57cc5bf65f7447a740bff33a6d2f4e53c64a5cba

**Comment by kingthorin** [comment]
Code ref: https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/cmss

**Comment by kingthorin** [comment]
I propose that we simply remove/retire this add-on. It's code will live on in the repo history. Wappalyzer has been implemented and kept up-to-date as it's own add-on. At least some of the finger printing employed by CMSS/WAFP is hard coded and unmaintained (and maintenance unfriendly).
