### ISSUE TITLE
Can't decrypt SSL traffic (app refuse to connect)

### ISSUE THREAD

**Issue by PASAf** [zaproxy/zaproxy#3248]
Debugging app with bundled custom JVM where I can not modify any system properties (but can define proxy via command line).
Followed instructions in [FAQjavaappssl](https://github.com/zaproxy/zaproxy/wiki/FAQjavaappssl)
(in bundled JVM there is cacerts)

App raised exception:
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1446)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at tzax.m.run(SourceFile:840)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1428)
	... 11 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
	... 17 more
```

**Comment by kingthorin** [comment]
You're using a client certificate?

**Comment by kingthorin** [comment]
Are you able to connect (with a standard browser, etc.) without proxying through ZAP?

Is ZAP on windows or linux? Have you added the CA certs to the local trust store?

This is at least partially related to: https://github.com/zaproxy/zaproxy/issues/3225

**Comment by thc202** [comment]
The provided exception stack trace is not from ZAP, most likely from the application under test.

**Comment by PASAf** [comment]
> The provided exception stack trace is not from ZAP, most likely from the application under test.
Exactly what I meant by writing "App raised exception"
>You're using a client certificate?
I followed exactly instructions in [FAQjavaappssl](https://github.com/zaproxy/zaproxy/wiki/FAQjavaappssl)
I've used dynamic root CA certificate generated by zaproxy.
>Are you able to connect (with a standard browser, etc.) without proxying through ZAP?
All traffic (including HTTPS) from other applications captured normally.
>Is ZAP on windows or linux? Have you added the CA certs to the local trust store?
ZAP on Windows. Yes I've added CA certs both to local and user store.

**Comment by thc202** [comment]
Are you able to pass args to the JVM? If so, enable network debug (e.g. ` -Djavax.net.debug=all`) and verify that ZAP's Root CA cert is being trusted (the output should also indicate the trust store being used).

**Comment by PASAf** [comment]
@thc202, no I'm not, but I will try, thank you.

**Comment by kingthorin** [comment]
https://groups.google.com/forum/m/#!topic/zaproxy-users/Yty5mdf8QA4

**Comment by kingthorin** [comment]
Is this related to Spine from Esoteric Software?

**Comment by PASAf** [comment]
@kingthorin, yes it is.

**Comment by kingthorin** [comment]
Might want to read through this thread: http://esotericsoftware.com/forum/Downloading-new-version-on-each-startup-5781?start=25

**Comment by kingthorin** [comment]
@pasaf is there something more we can do here? Have you updated your software or anything else suggested in that vendor thread?

**Comment by PASAf** [comment]
@kingthorin I've already used latest available version of software. I'm not sure if this is software problem.

**Comment by kingthorin** [comment]
@pasaf any luck doing the jvm stuff @thc202 suggested a month ago? Is there something more we can do here? Can this issue be closed?
