### ISSUE TITLE
Error related to zap.spider.scan

### ISSUE THREAD

**Issue by AdamBuji** [zaproxy/zaproxy#3259]
Error when running "zap.spider.scan(target, apikey=apikey)" , any idea how to solve this problem ?
This is the code I run
https://github.com/zaproxy/zaproxy/wiki/ApiPython
```
Spidering target http://10.0.0.5
Traceback (most recent call last):
  File "/home/zapcode.py", line 24, in <module>
    scanid = zap.spider.scan(target, apikey=apikey)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/spider.py", line 156, in scan
    return next(self.zap._request(self.zap.base + 'spider/action/scan/', params).itervalues())
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 145, in _request
    return json.loads(self.urlopen(url + '?' + urllib.urlencode(get)))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Spidering target http://10.0.0.5
```

**Comment by thc202** [comment]
For questions like this is better to use the [User Group](https://groups.google.com/group/zaproxy-users).

Most likely the API client is not talking with ZAP, in which port is ZAP listening? 8080?

**Comment by AdamBuji** [comment]
Thc202 ,  so I changed it to 80 
`zap = ZAPv2(proxies={'http': 'http://127.0.0.1:80', 'https': 'http://127.0.0.1:80'})
`

**Comment by thc202** [comment]
Continuing this in the User Group:
https://groups.google.com/d/topic/zaproxy-users/VoLXzCxyd4o/discussion

Thanks!
