### ISSUE TITLE
A specific url give SSL handshake error

### ISSUE THREAD

**Issue by khalidse** [zaproxy/zaproxy#3362]
We have an automation project using selenium and we are using proxy to list browser network calls. We tried to use ZAProxy which is working good for both http and https requests, but we have an issue with a specific url "https://content.jwplatform.com/libraries/d8kYgPIS.js". We connect browser to  ZAProxy but the above url always crash with (SSL handshake error) meanwhile all other https links works normally.

Certificates for ZAProxy installed in trusted store certificates. also i have update java security jar files.

Is there anyway i could work around this error ?

Also to note this error happen in OSX, linux and windows, and tried to use JDK 7 and JDK 8.

**Comment by thc202** [comment]
I'm able to access that URL while proxying through ZAP(2.5.0 and 2.6.0). Could you provide the error message?

**Comment by kingthorin** [comment]
Per https://github.com/zaproxy/zaproxy/wiki/FAQsslHandshake have you installed the 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files'?

**Comment by khalidse** [comment]
@thc202 This is the error raised and the ZAP version i am using is 2.5.0
The below error is retrieved in call response
"ZAP Error [javax.net.ssl.SSLHandshakeException]: Received fatal alert: handshake_failure

Stack Trace:
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.parosproxy.paros.network.SSLConnector.createSocket(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)"

**Comment by khalidse** [comment]
@kingthorin i tried with java 7 which supposed it does not need this update
But when i tried with java 8, yes i have installed java Cryptography Extension jar files

**Comment by kingthorin** [comment]
What OS?
What browser?
Do you have an outbound proxy specified (i.e.: upstream of ZAP)?

**Comment by kingthorin** [comment]
http://stackoverflow.com/questions/43206239/ssl-handshake-error-for-a-specific-url-only-when-using-a-proxy

**Comment by thc202** [comment]
I'm able to reproduce the issue only when "SSLv2Hello" is selected. Do you have that selected?

**Comment by kingthorin** [comment]
@khalidse have you resolved your issue?

**Comment by kingthorin** [comment]
@khalidse have you resolved your issue?

**Comment by thc202** [comment]
Going to change ZAP to retry the connection with SSLv2Hello disabled. That will prevent this issue.

**Comment by AjCaroline** [comment]
I am having the same issue. I've been all over the net, installed the JCEs for Java 8 did not work. Installed the latest ZAP - got the latest JDK 9 version and I still can't access a specific https site. This is urgent as it's for work I dont know what else to try PLEASE HELP.

thank you.

**Comment by thc202** [comment]
Could you provide more details about the exception that you are getting? Is it also a `handshake_failure`? Did you try enable just the newer versions of TLS? [1]

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsConnection#security-protocols

**Comment by AjCaroline** [comment]
Yes this is the SSLHandshakeException: Fatal Alert/Access Denied, I disabled SSLv2Hello and restarted ZAP leaving SSL 3 TLS 1 TLS 1.1 TLS 1.2 all checked as it was - did not work.  Then I unchecked 1 and 1.1 leaving only 1.2 and SSL 3 checked and still the same problem. Under Certificate "Enable unsafe SSL/TLS renegotiation is checked...I have JDK 9.0.1.0 installed and ZAP 2.7.0 installed...I spent ALL DAY troubleshooting this... as I said I do not know what else to try.

**Comment by thc202** [comment]
Are you able to access the server with a browser? Does it require a client certificate?

**Comment by kingthorin** [comment]
@AjCaroline do you have further details on this? Can you answer the previous questions?

**Comment by kingthorin** [comment]
@thc202 can this be closed or were you still planning to change some SSLv2 behavior?

**Comment by thc202** [comment]
Yes, will tweak that.

**Comment by kidbomb** [comment]
I just came across this error and noticed that, even though you configured everything right (Java 1.8, JCE, disable SSL Hello) you still can get this erro if you are behind a corporate proxy, so if you tried everything and you are still not able to reach HTTPS web sites, try to configure you outgoing web proxy (Tools, Options, Connection, Use Proxy Chain)

**Comment by kingthorin** [comment]
Thanks @kidbomb that's a good point, I've added it to the FAQ.
