### ISSUE TITLE
AJAX Spider via Firefox closes immediately after upgrade to ZAP 2.6.0

### ISSUE THREAD

**Issue by Captain-Kludge** [zaproxy/zaproxy#3369]
Everything was running properly with Firefox 45.8 ESR (Selenium 2.9.1) and ZAP 2.5.0 when I would use the AJAX Spider. 

I upgraded to ZAP 2.6.0 yesterday and now the Firefox window closes almost immediately, though I can tell that it says  "your connection is not secure", fails to load/browse and then closes automatically. Based on that error, I am guessing that the Firefox instance started by the Spider somehow does not like the ZAP cert. 

Interestingly, the two installations of Firefox that I use both have the root cert installed and can browse through the proxy with no errors whatsoever, so the issue seems to be unique to the new window opened by the spider, though it doesn't stay open long enough to investigate. 

I have made sure that Selenium is updated through the ZAP add-on manager, and the only google results I could find that seemed close to the issue were from last year regarding firefox extension signing (which also did not fix the issue). 

Am I missing something??

Below is the error log generated during my attempt:

2017-04-05 14:00:22,523 [ZAP-AjaxSpider] INFO  SpiderThread - Running Crawljax (with firefox): https://www.website.com/
2017-04-05 14:00:22,524 [ZAP-AjaxSpider] INFO  SpiderThread - Starting proxy...
2017-04-05 14:00:22,556 [ZAP-AjaxSpider] INFO  SpiderThread - Proxy started, listening at port [56629].
2017-04-05 14:00:22,581 [ZAP-AjaxSpider] INFO  Plugins - Loaded org.zaproxy.zap.extension.spiderAjax.SpiderThread$DummyPlugin@4d1a1c92 as a OnBrowserCreatedPlugin
2017-04-05 14:00:25,452 [ZAP-AjaxSpider] INFO  UnfiredCandidateActions - There are 1 states with unfired actions
2017-04-05 14:00:25,453 [pool-4-thread-2] INFO  UnfiredCandidateActions - There are 1 states with unfired actions
2017-04-05 14:00:25,599 [pool-4-thread-2] WARN  WebDriverBackedEmbeddedBrowser - Could not get the dom
org.openqa.selenium.WebDriverException: Error: Permission denied to access property "document" (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 7 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
Driver info: org.openqa.selenium.firefox.MarionetteDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20170301181722, version=45.8.0, platform=XP, proxy={}, specificationLevel=1, acceptSslCerts=false, acceptInsecureCerts=true, browserVersion=45.8.0, platformVersion=6.1, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: 1e0ed2ea-2df3-40d4-8952-5ebf3e16957b
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:575)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:516)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getDomTreeWithFrames(WebDriverBackedEmbeddedBrowser.java:570)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getStrippedDom(WebDriverBackedEmbeddedBrowser.java:350)
	at com.crawljax.forms.FormHandler.getFormInputs(FormHandler.java:184)
	at com.crawljax.core.Crawler.handleInputElements(Crawler.java:206)
	at com.crawljax.core.Crawler.crawlThroughActions(Crawler.java:312)
	at com.crawljax.core.Crawler.execute(Crawler.java:126)
	at com.crawljax.core.CrawlTaskConsumer.handleTask(CrawlTaskConsumer.java:75)
	at com.crawljax.core.CrawlTaskConsumer.pollAndHandleCrawlTasks(CrawlTaskConsumer.java:67)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:47)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thc202** [comment]
That Firefox version is not supported with geckodriver (bundled in ZAP 2.6.0), if you want to keep using that version you need to remove the "WebDrivers" add-on corresponding to your OS ("Linux WebDrivers", "MacOS WebDrivers" or "Windows WebDrivers").

For known supported versions of Firefox and which ones require geckodriver:
https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsSeleniumIntro

**Comment by Captain-Kludge** [comment]
Removing the WebDrivers add-on (and restarting ZAP) had the same result as before. Dang!

However, I am not married to that version of Firefox, so I will now attempt to switch to one of the known supported versions that doesn't have problems with self-signed certs (version 52, if I read mozilla Bug 1103196 correctly). 

Addition: ZAP 2.6.0 works fine with Firefox 52, sorry for being a bother!

**Comment by thc202** [comment]
Thanks for letting us know. The help pages will be updated to recommend using newer browser versions with the bundled WebDrivers.
