### ISSUE TITLE
ZAP can no longer load non UTF8 scripts

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3377]
An example is https://github.com/mozilla/zest/blob/develop/examples/BodgeIt_Register_XSS.zst

Likely to be an unintended side effect of #2773

We should be able to cope with scripts that have been created with previous versions of ZAP :/

**Comment by thc202** [comment]
Exception:
```
134694 [AWT-EventQueue-0] ERROR org.zaproxy.zap.extension.scripts.ScriptsListPanel  - Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.read1(BufferedReader.java:212)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at org.zaproxy.zap.extension.script.ExtensionScript.loadScript(Unknown Source)
	at org.zaproxy.zap.extension.scripts.ScriptsListPanel.loadScript(ScriptsListPanel.java:353)
	at org.zaproxy.zap.extension.scripts.ScriptsListPanel.access$000(ScriptsListPanel.java:75)
	at org.zaproxy.zap.extension.scripts.ScriptsListPanel$1.actionPerformed(ScriptsListPanel.java:170)
```

Worth noting that the example script does not load correctly in 2.5.0:
```
132325 [AWT-EventQueue-0] ERROR org.zaproxy.zap.extension.script.ExtensionScript  - java.lang.ClassNotFoundException
com.google.gson.JsonParseException: java.lang.ClassNotFoundException
	at org.mozilla.zest.core.v1.ZestJSON.deserialize(ZestJSON.java:93)
	at org.mozilla.zest.core.v1.ZestJSON.deserialize(ZestJSON.java:23)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:859)
	at com.google.gson.Gson.fromJson(Gson.java:832)
	at org.mozilla.zest.core.v1.ZestJSON.deserialize(ZestJSON.java:90)
	at org.mozilla.zest.core.v1.ZestJSON.deserialize(ZestJSON.java:23)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at com.google.gson.Gson.fromJson(Gson.java:710)
	at com.google.gson.Gson.fromJson(Gson.java:682)
	at org.mozilla.zest.core.v1.ZestJSON.fromString(ZestJSON.java:45)
	at org.zaproxy.zap.extension.zest.ZestScriptWrapper.<init>(Unknown Source)
	at org.zaproxy.zap.extension.zest.ExtensionZest.scriptAdded(Unknown Source)
[...]
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.mozilla.zest.core.v1.ZestJSON.deserialize(ZestJSON.java:89)
	... 60 more
```
but that's another (unrelated) issue.

**Comment by thc202** [comment]
The example was fixed in the meantime, it can be opened in ZAP without problems.

To reproduce the (charset) issue it needs to be used the older version:
https://raw.githubusercontent.com/mozilla/zest/6b16c95efb7784b99b89d033a3fce0a3c1006a5f/examples/BodgeIt_Register_XSS.zst
