### ISSUE TITLE
JxBrowser - Browser prematurely closed while AJAX Spidering

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3393]
Steps to reproduce the issue:
1. Run ZAP with JxBrowser (core and OS specific) and AJAX Spider add-ons installed;
2. Run the AJAX Spider against WIVET; [1] 
3. Note that the browser is closed prematurely and some exceptions are logged when spidering the page 4.php.
```
784891 [pool-15-thread-2] ERROR com.crawljax.core.CrawlTaskConsumer  - Could not complete state crawl: no such window
[...]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.window(RemoteWebDriver.java:1015)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.closeOtherWindows(WebDriverBackedEmbeddedBrowser.java:552)
	at com.crawljax.core.Crawler.fireEvent(Unknown Source)
	at com.crawljax.core.Crawler.crawlThroughActions(Unknown Source)
	at com.crawljax.core.Crawler.execute(Unknown Source)
	at com.crawljax.core.CrawlTaskConsumer.handleTask(CrawlTaskConsumer.java:75)
	at com.crawljax.core.CrawlTaskConsumer.pollAndHandleCrawlTasks(CrawlTaskConsumer.java:67)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:47)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Add-on:
JxBrowser (Linux/macOS/Windows) version 1.

[1] https://github.com/bedirhan/wivet

**Comment by thc202** [comment]
Closing, the JxBrowser add-ons are being phased out.
