### ISSUE TITLE
Ajax Spider closes the browser when an alert box is triggered

### ISSUE THREAD

**Issue by clydevassallo** [zaproxy/zaproxy#3412]
**Client java API version** -  1.0.0
**OWASP ZAP version** - weekly ZAP_D-2017-02-27
**Browser Driver** - Chrome
**Web Application Under Test** - Schoolmate

Given that OWASP ZAP's Ajax Spider is used to crawl a web application,
When an alert box is displayed ( alert() function in JavaScript ), the browser window is closed and the crawling process is terminated. 

33206023 [pool-16-thread-2] WARN com.crawljax.browser.WebDriverBackedEmbeddedBrowser  - Could not get the dom
org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : You must select a grade to edit.}

  at sun.reflect.GeneratedConstructorAccessor71.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  at java.lang.reflect.Constructor.newInstance(Unknown Source)
  at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
  at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
  at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
  at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:511)
  at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getDomTreeWithFrames(WebDriverBackedEmbeddedBrowser.java:570)
  at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getStrippedDom(WebDriverBackedEmbeddedBrowser.java:350)
  at com.crawljax.util.ElementResolver.resolve(ElementResolver.java:55)
  at com.crawljax.util.ElementResolver.resolve(ElementResolver.java:43)
  at com.crawljax.core.Crawler.resolveByXpath(Crawler.java:270)
  at com.crawljax.core.Crawler.fireEvent(Crawler.java:225)
  at com.crawljax.core.Crawler.tryToFireEvent(Crawler.java:181)
  at com.crawljax.core.Crawler.follow(Crawler.java:152)
  at com.crawljax.core.Crawler.execute(Crawler.java:125)
  at com.crawljax.core.CrawlTaskConsumer.handleTask(CrawlTaskConsumer.java:75)
  at com.crawljax.core.CrawlTaskConsumer.pollAndHandleCrawlTasks(CrawlTaskConsumer.java:67)
  at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:47)
  at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)

**Comment by thc202** [comment]
Is that the first exception logged?

**Comment by thc202** [comment]
Which versions of ChromeDriver and Chrome are you using?

**Comment by clydevassallo** [comment]
ChromeDriver version: 2.27.440174
Chrome version: 57.0.2987.133

And yes, it is the first exception logged.

Below is some more information extracted from the console:

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=57.0.2987.133, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]

**Comment by thc202** [comment]
Thanks!

**Comment by jagipas** [comment]
Same here, more concretely in wivet framework link http://wivet.herokuapp.com/pages/10.php.

Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'MacBook-Pro-de-Javi.local', ip: '192.168.79.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9), userDataDir=/var/folders/_b/s2w5t7711nqf5_45_615qvhm0000gn/T/.org.chromium.Chromium.S6pNZz}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=58.0.3029.110, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
Session ID: ca592dc33f952a820d6b9e7cc3924af6
	at sun.reflect.GeneratedConstructorAccessor80.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:511)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getDomTreeWithFrames(WebDriverBackedEmbeddedBrowser.java:570)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getStrippedDom(WebDriverBackedEmbeddedBrowser.java:350)
	at com.crawljax.forms.FormHandler.getFormInputs(FormHandler.java:184)
	at com.crawljax.core.Crawler.handleInputElements(Crawler.java:205)
	at com.crawljax.core.Crawler.crawlThroughActions(Crawler.java:311)
	at com.crawljax.core.Crawler.execute(Crawler.java:126)
	at com.crawljax.core.CrawlTaskConsumer.handleTask(CrawlTaskConsumer.java:75)
	at com.crawljax.core.CrawlTaskConsumer.pollAndHandleCrawlTasks(CrawlTaskConsumer.java:67)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:47)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thc202** [comment]
This will requires changes in Crawljax (being done in https://github.com/zaproxy/crawljax/).

**Comment by thc202** [comment]
Pending a new (fork) Crawljax release.

**Comment by idawson-gl** [comment]
As a workaround could you inject a proxy script to rewrite alert() print()?
window.alert = function() {}
window.print = function() {}

**Comment by thc202** [comment]
That's already being done (for non-native dialogues) but does not help with the cases mentioned earlier (although Crawljax was already changed to just dismiss and continue when that happens).
