### ISSUE TITLE
Memory errors when running active scan

### ISSUE THREAD

**Issue by RomHartmann** [zaproxy/zaproxy#3447]
Seems to be partially identical to https://github.com/zaproxy/zaproxy/issues/1283

Steps to create error:

1)  Use docker image [`owasp/zap2docker-stable`](https://github.com/zaproxy/zaproxy/blob/develop/build/docker/Dockerfile-stable)
2)  `zap.sh -daemon -port 8090 -host 127.0.0.1 -config api.disablekey=true`
3)  `zap-cli -p 8090 open-url http://www.plumblink.co.za/`
4)  `zap-cli -p 8090 spider http://www.plumblink.co.za/`
5)  `zap-cli -p 8090 active-scan -r http://www.plumblink.co.za/`

And then after scanning for some time I get the below trace.

Can I either increase the size of the DB or plug in my own?

Just a note, the scan succeeds on other urls that I have tested

```
2017-04-28T07:57:12.748768013Z INFO:__main__:starting daemon...
2017-04-28T07:57:12.795957006Z INFO:__main__:daemon not running yet, waiting...
2017-04-28T07:57:14.211171930Z Found Java version 1.8.0_121
2017-04-28T07:57:14.322029997Z Available memory: 3699 MB
2017-04-28T07:57:14.322464530Z Setting jvm heap size: -Xmx924m
2017-04-28T07:57:17.431836231Z 1005 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP 2.6.0 started 28/04/17 07:57:17

...
2017-04-28T09:51:08.057026890Z 6831630 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.params.ExtensionParams  - java.sql.SQLDataException: data exception: string data, right truncation
2017-04-28T09:51:08.057049509Z org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: data exception: string data, right truncation
2017-04-28T09:51:08.057053796Z 	at org.parosproxy.paros.db.paros.ParosTableParam.update(Unknown Source)
2017-04-28T09:51:08.057057429Z 	at org.zaproxy.zap.extension.params.ExtensionParams.persist(Unknown Source)
2017-04-28T09:51:08.057069917Z 	at org.zaproxy.zap.extension.params.ExtensionParams.onHttpRequestSend(Unknown Source)
2017-04-28T09:51:08.057072942Z 	at org.zaproxy.zap.extension.params.ParamScanner.scanHttpRequestSend(Unknown Source)
2017-04-28T09:51:08.057085926Z 	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(Unknown Source)
2017-04-28T09:51:08.057089015Z Caused by: java.sql.SQLDataException: data exception: string data, right truncation
2017-04-28T09:51:08.057092541Z 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
2017-04-28T09:51:08.057095205Z 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
2017-04-28T09:51:08.057098128Z 	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
2017-04-28T09:51:08.057100902Z 	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
2017-04-28T09:51:08.057104123Z 	... 5 more
2017-04-28T09:51:08.057106608Z Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation
2017-04-28T09:51:08.057109282Z 	at org.hsqldb.error.Error.error(Unknown Source)
2017-04-28T09:51:08.057111843Z 	at org.hsqldb.error.Error.error(Unknown Source)
2017-04-28T09:51:08.057114472Z 	at org.hsqldb.types.CharacterType.castOrConvertToType(Unknown Source)
2017-04-28T09:51:08.057116959Z 	at org.hsqldb.types.CharacterType.convertToType(Unknown Source)
2017-04-28T09:51:08.057119616Z 	at org.hsqldb.StatementDML.getUpdatedData(Unknown Source)
2017-04-28T09:51:08.057122075Z 	at org.hsqldb.StatementDML.executeUpdateStatement(Unknown Source)
2017-04-28T09:51:08.057126079Z 	at org.hsqldb.StatementDML.getResult(Unknown Source)
2017-04-28T09:51:08.057128723Z 	at org.hsqldb.StatementDMQL.execute(Unknown Source)
2017-04-28T09:51:08.057131383Z 	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
2017-04-28T09:51:08.057134472Z 	at org.hsqldb.Session.execute(Unknown Source)
2017-04-28T09:51:08.057137129Z 	... 7 more
...
...
2017-04-28T10:37:34.622678579Z 9618197 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscan.PassiveScanThread  - Scanner Parameter Scanner failed on record 42395 from History table: POST http://www.plumblink.co.za/p001677/ProductInfo.aspx?productID=001677
2017-04-28T10:37:34.622699478Z java.lang.OutOfMemoryError: Java heap space
2017-04-28T10:37:36.365471486Z 9619940 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscan.PassiveScanThread  - Scanner Parameter Scanner failed on record 42400 from History table: POST http://www.plumblink.co.za/p001677/ProductInfo.aspx?productID=001677
2017-04-28T10:37:36.365497867Z java.lang.OutOfMemoryError: Java heap space
...
```

**Comment by kingthorin** [comment]
I don't think there's much we can do about the memory error. It seems likely that doing some good modelling of the site (it seems to be an online store) might have helped issues.

However the truncation can probably be handled better. (Actually catching `SQLDataException` and maybe log a warning or info message that includes details of the param for which the update is failing):
https://github.com/zaproxy/zaproxy/blob/787b57ac4e18f11c6ad523ebb4fb3ab0f892b860/src/org/zaproxy/zap/extension/params/ExtensionParams.java#L339-L355

It seems likely that the truncation occurred on the values field:
https://github.com/zaproxy/zaproxy/blob/787b57ac4e18f11c6ad523ebb4fb3ab0f892b860/src/org/parosproxy/paros/db/paros/ParosTableParam.java#L63-L66

However, if 8,388,608 characters is exceeded that doesn't seem like a show stopper (that seems like an extreme case).
