### ISSUE TITLE
Passing in -config params without quotes throws "ValueError: need more than 1 value to unpack" exception

### ISSUE THREAD

**Issue by stephendonner** [zaproxy/zaproxy#3462]
Steps to Reproduce:

Invoke the zap-baseline script without quotes for the -config param, and you'll get an error:

WRONG:
```sdonner-17447:zaproxy sdonner$ docker run -v $(pwd):/zap/wrk/:rw -t stephendonner/zaproxy:1.0 zap-baseline.py --active_scan -t http://petstore.swagger.io -d -z -config api.disablekey=true```

CORRECT:
```sdonner-17447:zaproxy sdonner$ docker run -v $(pwd):/zap/wrk/:rw -t stephendonner/zaproxy:1.0 zap-baseline.py --active_scan -t http://petstore.swagger.io -d -z -config "api.disablekey=true"```

Output from the "WRONG invocation:

```sdonner-17447:zaproxy sdonner$ docker run -v $(pwd):/zap/wrk/:rw -t stephendonner/zaproxy:1.0 zap-baseline.py --active_scan -t http://petstore.swagger.io -d -z -config api.disablekey=true
2017-05-01 21:50:51,110 Using port: 55381
2017-05-01 21:50:51,110 Starting ZAP
2017-05-01 21:50:51,116 Starting new HTTP connection (1): localhost
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2017-05-01 21:50:52,122 Starting new HTTP connection (1): localhost
2017-05-01 21:50:53,131 Starting new HTTP connection (1): localhost
2017-05-01 21:50:54,139 Starting new HTTP connection (1): localhost
2017-05-01 21:50:55,144 Starting new HTTP connection (1): localhost
2017-05-01 21:50:56,150 Starting new HTTP connection (1): localhost
2017-05-01 21:50:57,156 Starting new HTTP connection (1): localhost
2017-05-01 21:50:58,162 Starting new HTTP connection (1): localhost
2017-05-01 21:50:59,169 Starting new HTTP connection (1): localhost
2017-05-01 21:51:00,174 Starting new HTTP connection (1): localhost
2017-05-01 21:51:01,181 Starting new HTTP connection (1): localhost
2017-05-01 21:51:02,185 Starting new HTTP connection (1): localhost
2017-05-01 21:51:03,193 Starting new HTTP connection (1): localhost
2017-05-01 21:51:04,202 Starting new HTTP connection (1): localhost
2017-05-01 21:51:05,210 Starting new HTTP connection (1): localhost
2017-05-01 21:51:06,216 Starting new HTTP connection (1): localhost
2017-05-01 21:51:07,221 Starting new HTTP connection (1): localhost
2017-05-01 21:51:08,227 Starting new HTTP connection (1): localhost
2017-05-01 21:51:09,236 Starting new HTTP connection (1): localhost
2017-05-01 21:51:10,245 Starting new HTTP connection (1): localhost
2017-05-01 21:51:11,253 Starting new HTTP connection (1): localhost
2017-05-01 21:51:12,262 Starting new HTTP connection (1): localhost
2017-05-01 21:51:13,268 Starting new HTTP connection (1): localhost
2017-05-01 21:51:14,272 Starting new HTTP connection (1): localhost
2017-05-01 21:51:15,281 Starting new HTTP connection (1): localhost
2017-05-01 21:51:16,291 Starting new HTTP connection (1): localhost
2017-05-01 21:51:17,298 Starting new HTTP connection (1): localhost
2017-05-01 21:51:18,308 Starting new HTTP connection (1): localhost
2017-05-01 21:51:19,313 Starting new HTTP connection (1): localhost
2017-05-01 21:51:20,320 Starting new HTTP connection (1): localhost
2017-05-01 21:51:21,326 Starting new HTTP connection (1): localhost
2017-05-01 21:51:22,331 Starting new HTTP connection (1): localhost
2017-05-01 21:51:23,338 Starting new HTTP connection (1): localhost
2017-05-01 21:51:24,346 Starting new HTTP connection (1): localhost
2017-05-01 21:51:25,355 Starting new HTTP connection (1): localhost
2017-05-01 21:51:26,360 Starting new HTTP connection (1): localhost
2017-05-01 21:51:27,365 Starting new HTTP connection (1): localhost
2017-05-01 21:51:28,371 Starting new HTTP connection (1): localhost
2017-05-01 21:51:29,381 Starting new HTTP connection (1): localhost
2017-05-01 21:51:30,385 Starting new HTTP connection (1): localhost
2017-05-01 21:51:31,389 Starting new HTTP connection (1): localhost
2017-05-01 21:51:32,394 Starting new HTTP connection (1): localhost
2017-05-01 21:51:33,398 Starting new HTTP connection (1): localhost
2017-05-01 21:51:34,404 Starting new HTTP connection (1): localhost
2017-05-01 21:51:35,410 Starting new HTTP connection (1): localhost
2017-05-01 21:51:36,419 Starting new HTTP connection (1): localhost
2017-05-01 21:51:37,426 Starting new HTTP connection (1): localhost
2017-05-01 21:51:38,432 Starting new HTTP connection (1): localhost
2017-05-01 21:51:39,439 Starting new HTTP connection (1): localhost
2017-05-01 21:51:40,448 Starting new HTTP connection (1): localhost
2017-05-01 21:51:41,457 Starting new HTTP connection (1): localhost
2017-05-01 21:51:42,464 Starting new HTTP connection (1): localhost
2017-05-01 21:51:43,474 Starting new HTTP connection (1): localhost
2017-05-01 21:51:44,482 Starting new HTTP connection (1): localhost
2017-05-01 21:51:45,492 Starting new HTTP connection (1): localhost
2017-05-01 21:51:46,498 Starting new HTTP connection (1): localhost
2017-05-01 21:51:47,505 Starting new HTTP connection (1): localhost
2017-05-01 21:51:48,511 Starting new HTTP connection (1): localhost
2017-05-01 21:51:49,516 Starting new HTTP connection (1): localhost
2017-05-01 21:51:50,521 Starting new HTTP connection (1): localhost
2017-05-01 21:51:51,526 Starting new HTTP connection (1): localhost
2017-05-01 21:51:52,532 Starting new HTTP connection (1): localhost
2017-05-01 21:51:53,537 Starting new HTTP connection (1): localhost
2017-05-01 21:51:54,542 Starting new HTTP connection (1): localhost
2017-05-01 21:51:55,547 Starting new HTTP connection (1): localhost
2017-05-01 21:51:56,552 Starting new HTTP connection (1): localhost
2017-05-01 21:51:57,561 Starting new HTTP connection (1): localhost
2017-05-01 21:51:58,568 Starting new HTTP connection (1): localhost
2017-05-01 21:51:59,573 Starting new HTTP connection (1): localhost
2017-05-01 21:52:00,578 Starting new HTTP connection (1): localhost
2017-05-01 21:52:01,583 Starting new HTTP connection (1): localhost
2017-05-01 21:52:02,589 Starting new HTTP connection (1): localhost
2017-05-01 21:52:03,594 Starting new HTTP connection (1): localhost
2017-05-01 21:52:04,602 Starting new HTTP connection (1): localhost
2017-05-01 21:52:05,611 Starting new HTTP connection (1): localhost
2017-05-01 21:52:06,620 Starting new HTTP connection (1): localhost
2017-05-01 21:52:07,628 Starting new HTTP connection (1): localhost
2017-05-01 21:52:08,634 Starting new HTTP connection (1): localhost
2017-05-01 21:52:09,640 Starting new HTTP connection (1): localhost
2017-05-01 21:52:10,645 Starting new HTTP connection (1): localhost
2017-05-01 21:52:11,652 Starting new HTTP connection (1): localhost
2017-05-01 21:52:12,661 Starting new HTTP connection (1): localhost
2017-05-01 21:52:13,669 Starting new HTTP connection (1): localhost
2017-05-01 21:52:14,675 Starting new HTTP connection (1): localhost
2017-05-01 21:52:15,680 Starting new HTTP connection (1): localhost
2017-05-01 21:52:16,686 Starting new HTTP connection (1): localhost
2017-05-01 21:52:17,690 Starting new HTTP connection (1): localhost
2017-05-01 21:52:18,696 Starting new HTTP connection (1): localhost
2017-05-01 21:52:19,704 Starting new HTTP connection (1): localhost
2017-05-01 21:52:20,712 Starting new HTTP connection (1): localhost
2017-05-01 21:52:21,720 Starting new HTTP connection (1): localhost
2017-05-01 21:52:22,728 Starting new HTTP connection (1): localhost
2017-05-01 21:52:23,733 Starting new HTTP connection (1): localhost
2017-05-01 21:52:24,738 Starting new HTTP connection (1): localhost
2017-05-01 21:52:25,744 Starting new HTTP connection (1): localhost
2017-05-01 21:52:26,750 Starting new HTTP connection (1): localhost
2017-05-01 21:52:27,758 Starting new HTTP connection (1): localhost
2017-05-01 21:52:28,763 Starting new HTTP connection (1): localhost
2017-05-01 21:52:29,772 Starting new HTTP connection (1): localhost
2017-05-01 21:52:30,777 Starting new HTTP connection (1): localhost
2017-05-01 21:52:31,784 Starting new HTTP connection (1): localhost
2017-05-01 21:52:32,791 Starting new HTTP connection (1): localhost
2017-05-01 21:52:33,797 Starting new HTTP connection (1): localhost
2017-05-01 21:52:34,806 Starting new HTTP connection (1): localhost
2017-05-01 21:52:35,814 Starting new HTTP connection (1): localhost
2017-05-01 21:52:36,818 Starting new HTTP connection (1): localhost
2017-05-01 21:52:37,823 Starting new HTTP connection (1): localhost
2017-05-01 21:52:38,827 Starting new HTTP connection (1): localhost
2017-05-01 21:52:39,835 Starting new HTTP connection (1): localhost
2017-05-01 21:52:40,839 Starting new HTTP connection (1): localhost
2017-05-01 21:52:41,846 Starting new HTTP connection (1): localhost
2017-05-01 21:52:42,850 Starting new HTTP connection (1): localhost
2017-05-01 21:52:43,855 Starting new HTTP connection (1): localhost
2017-05-01 21:52:44,858 Starting new HTTP connection (1): localhost
2017-05-01 21:52:45,863 Starting new HTTP connection (1): localhost
2017-05-01 21:52:46,867 Starting new HTTP connection (1): localhost
2017-05-01 21:52:47,874 Starting new HTTP connection (1): localhost
2017-05-01 21:52:48,880 Starting new HTTP connection (1): localhost
2017-05-01 21:52:49,890 Starting new HTTP connection (1): localhost
2017-05-01 21:52:50,895 Starting new HTTP connection (1): localhost
2017-05-01 21:52:51,899 Try to import an OpenAPI definition
2017-05-01 21:52:51,902 Starting new HTTP connection (1): localhost
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 650, in <module>
    main(sys.argv[1:])
  File "/zap/zap-baseline.py", line 613, in main
    except IOError as (errno, strerror):
ValueError: need more than 1 value to unpack```

**Comment by thc202** [comment]
@g-k would you be available to address this one? It seems to be the same problem as #3347 (although different cause).

**Comment by g-k** [comment]
Yep, I can pick this up.

**Comment by thc202** [comment]
Thanks!

**Comment by g-k** [comment]
@stephendonner what version of the python zap api client library do you have installed?

you can check with:

```python -c "import pkg_resources; print(pkg_resources.get_distribution('python_owasp_zap_v2.4').version)"```

**Comment by stephendonner** [comment]
@g-k:

```
sdonner-17447:zaproxy sdonner$ python -c "import pkg_resources; print(pkg_resources.get_distribution('python_owasp_zap_v2.4').version)"
0.0.9
sdonner-17447:zaproxy sdonner$ pip freeze
python-owasp-zap-v2.4==0.0.9
requests==2.13.0
```

**Comment by g-k** [comment]
Thanks!

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/pull/3474
