### ISSUE TITLE
Minor Enhancement: ZAP GUI Warn User When its out of Memory

### ISSUE THREAD

**Issue by davewichers** [zaproxy/zaproxy#3486]
I ran out of memory using ZAP. It kept running but the history wouldn't update, and I was trying to figure out why. I went into the zap log and found lots of entries like the one below.  Seems like it would be helpful to the user if ZAP presented something in the UI that it was low on memory and you might want to do something about it. Like restart, restart with more memory, etc. Right now it silently fails (except for these entries in the log).

2017-05-04 12:09:59,083 [ZAP-PassiveScanner] FATAL ENGINE - /Users/dwichers/Documents/projectname/ZAP-App-Admin.session.data getFromFile failed 19689641
org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
        at org.hsqldb.persist.DataFileCache.get(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
        at org.hsqldb.index.IndexAVL.findNode(Unknown Source)
        at org.hsqldb.index.IndexAVL.findFirstRow(Unknown Source)
        at org.hsqldb.RangeVariable$RangeIteratorMain.getFirstRow(Unknown Source)
        at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source)
        at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
        at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
        at org.hsqldb.QuerySpecification.getSingleResult(Unknown Source)
        at org.hsqldb.QuerySpecification.getResult(Unknown Source)
        at org.hsqldb.StatementQuery.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
        at org.parosproxy.paros.db.paros.ParosTableHistory.read(Unknown Source)
        at org.parosproxy.paros.model.HistoryReference.<init>(Unknown Source)
        at org.parosproxy.paros.extension.history.ExtensionHistory.getHistoryReference(Unknown Source)
        at org.zaproxy.zap.extension.pscan.PassiveScanThread.getHistoryReference(Unknown Source)
        at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(Unknown Source)

**Comment by kingthorin** [comment]
@psiinon @thc202 Do you think warning at certain percentage thresholds (perhaps pausing active actions) is sufficient or does whatever monitor need to also track memory reclamation? (Ex, if if falls back below the thresholds.)

**Comment by kingthorin** [comment]
Anyone have feedback?

**Comment by thc202** [comment]
I think the latter otherwise ZAP will be warning/pausing without reason (if after GC memory is still available).

**Comment by psiinon** [comment]
How were you thinking of alerting the user? A dialog that keeps on popping up would be very annoying,

**Comment by davewichers** [comment]
I think a warning dialog would be fine and then when it is dismissed, if
there is still a problem like 5 minutes later, it should pop up again (or
something). That would be a reasonable tempo of warnings I would think.

-Dave

**Comment by psiinon** [comment]
I'm ok with that as long as theres a 'Dont show me this again' checkbox :)

**Comment by psiinon** [comment]
This will be addressed in the next weekly 😁 
The new Insights add-on monitors for high memory use, and will switch to the new tab if it goes over 95%
We'll also be adding the option to automatically stop automated scans.
