### ISSUE TITLE
Trying to produce an xml/html report using Zap CLI gives Python TypeError

### ISSUE THREAD

**Issue by rickyshelton** [zaproxy/zaproxy#3496]
When trying to produce an xml/html report using the ZAP CLI gives an the following error :

`TypeError: coercing to Unicode: need string or buffer, NoneType found`

Observed using :
```
OS : macOS 10.12.3
Docker : Docker version 17.05.0-ce-rc1, build 2878a85
```

I've tried with both the weekly and stable builds
```

REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
owasp/zap2docker-weekly                      latest              54e1d19e9072        7 hours ago         1.25GB
owasp/zap2docker-stable                      latest              12c3b9347b07        5 weeks ago         1.33GB
```

Steps to reproduce :

```
docker run -u zap -p 8080:8080 --name zap -d owasp/zap2docker-stable  zap.sh -daemon -port 8080 -host 127.0.0.1 -config api.disablekey=true -config scanner.attackOnStart=true -config view.mode=attack -config connection.dnsTtlSuccessfulQueries=-1 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

docker exec zap zap-cli -p 8080 open-url http://demo.testfire.net

docker exec zap zap-cli -p 8080 spider http://demo.testfire.net

docker exec zap zap-cli -p 8080 active-scan -r http://demo.testfire.net
```

The alerts will produce the following output :

`docker exec zap zap-cli -p 8080 alerts`

```
[INFO]            Issues found: 5
+----------------------------------+--------+----------+------------------------------------------------------------------------------------------------------------------+
| Alert                            | Risk   |   CWE ID | URL                                                                                                              |
+==================================+========+==========+==================================================================================================================+
| Cross Site Scripting (Reflected) | High   |       79 | http://demo.testfire.net/bank/login.aspx                                                                         |
+----------------------------------+--------+----------+------------------------------------------------------------------------------------------------------------------+
| Cross Site Scripting (Reflected) | High   |       79 | http://demo.testfire.net/search.aspx?txtSearch=%3C%2Fspan%3E%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E%3Cspan%3E |
+----------------------------------+--------+----------+------------------------------------------------------------------------------------------------------------------+
| Cross Site Scripting (Reflected) | High   |       79 | http://demo.testfire.net/comment.aspx                                                                            |
+----------------------------------+--------+----------+------------------------------------------------------------------------------------------------------------------+
| SQL Injection                    | High   |       89 | http://demo.testfire.net/bank/login.aspx                                                                         |
+----------------------------------+--------+----------+------------------------------------------------------------------------------------------------------------------+
| SQL Injection                    | High   |       89 | http://demo.testfire.net/bank/login.aspx                                                                         |
+----------------------------------+--------+----------+------------------------------------------------------------------------------------------------------------------+
```

Producing a text report will work :

```
docker exec zap zap-cli -p 8080 report -o text
[INFO]            Report saved to "text"
```

Trying to produce a formatted report will fail :

```
docker exec zap zap-cli -p 8080 report -f html

Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 507, in report
    zap_helper.html_report(output)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 391, in html_report
    self._write_report(report, file_path)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 396, in _write_report
    with open(file_path, 'w') as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by Grunny** [comment]
Hi @rickyshelton! This is because you're missing the output file name as well, so this should work (to save it to the file `report.html`):
```
docker exec zap zap-cli -p 8080 report -f html -o report.html
```

It should definitely fail more gracefully when it's missing a valid file path, so I'll be sure to do that. Feel free to file `zap-cli` related issues in the [dedicated repo](https://github.com/Grunny/zap-cli). Hope that helps! :)

**Comment by thc202** [comment]
Closing, 3rd party project, the issue should be reported in https://github.com/Grunny/zap-cli/

Please link back (for the record).

**Comment by thc202** [comment]
(Missed @Grunny's comment...)

**Comment by rickyshelton** [comment]
Ahhhhhhh - of course.

Thanks guys !
