### ISSUE TITLE
NPE while spider scan with HTTP State enabled

### ISSUE THREAD

**Issue by rain0r** [zaproxy/zaproxy#3534]
This exception occurs when doing a spider scan with the option HTTP State enabled (branch develop):

```
org.zaproxy.zap.extension.spider.SpiderThread  - Starting spidering scan on http://localhost:33006/ at Sat May 13 10:50:24 CEST 2017
48750 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.spider.Spider  - Spider initializing...
48782 [ZAP-SpiderInitThread-0] INFO org.zaproxy.zap.spider.Spider  - Starting spider...
48861 [ZAP-SpiderThreadPool-0-thread-2] ERROR org.zaproxy.zap.spider.SpiderTask  - An error occurred while fetching the resource [http://localhost:33006/robots.txt]: null
java.lang.NullPointerException
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
48861 [ZAP-SpiderThreadPool-0-thread-1] ERROR org.zaproxy.zap.spider.SpiderTask  - An error occurred while fetching the resource [http://localhost:33006/]: null
java.lang.NullPointerException
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
48884 [ZAP-SpiderThreadPool-0-thread-1] ERROR org.zaproxy.zap.spider.SpiderTask  - An error occurred while fetching the resource [http://localhost:33006/sitemap.xml]: null
java.lang.NullPointerException
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
48896 [ZAP-SpiderThreadPool-0-thread-1] INFO org.zaproxy.zap.spider.Spider  - Spidering process is complete. Shutting down...
48911 [ZAP-SpiderShutdownThread-0] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Spider scanning complete: true
```

**Comment by thc202** [comment]
Thanks for raising the issue.
