### ISSUE TITLE
openapi fails with java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3625]
Only happens with some older examples (and not all).
Exception in thread "ZAP-Import-OpenAPI-1"
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at com.github.fge.jackson.jsonpointer.JsonPointer.<clinit>(JsonPointer.java:46)
	at io.swagger.transform.util.MutableJsonTree.<init>(MutableJsonTree.java:36)
	at io.swagger.transform.migrate.V11ResourceListingMigrator.migrate(V11ResourceListingMigrator.java:81)
	at io.swagger.transform.migrate.SwaggerJsonMigrator.migrate(SwaggerJsonMigrator.java:19)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:153)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:65)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:93)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:68)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:212)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:256)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

I have an example defn that demonstrates this but unfortunately I cant make it public.
Hopefully just need to include the Google Guava lib in the add-on, but will have to work out which version and if there are any other missing dependencies.

**Comment by psiinon** [comment]
Also trying to import https://raw.githubusercontent.com/zaproxy/zap-extensions/alpha/test/resources/org/zaproxy/zap/extension/openapi/PetStore_1_2_defn.json just imports the url - but this _could_ be due to the fact that the content type is wrong?
http://petstore.swagger.io/v2/swagger.json (which has the right content type) imports fine.

**Comment by thc202** [comment]
It should be version 18.0, there are other dependencies missing (not sure if they are required or not).

**Comment by thc202** [comment]
@psiinon are you able to try with latest version of the add-on?

(I checked the dependencies again and this might be because of a version conflict, one of the dependencies is pulling Guava 27 while that library wants Guava 16.)
