### ISSUE TITLE
"Generate Anti-CSRF Test Form" not working

### ISSUE THREAD

**Issue by ArunObappa** [zaproxy/zaproxy#3633]
Hi ,

I upgraded to ZAP 2.6.0 from ZAP 2.5.0
When I try to "Generate Anti-CSRF Test Form" . I get below error.
Please let me know how to revert back to ZAP 2.5.0
It was working fine in ZAP 2.5.0

http://www.localhost.com:8080/OTHER/acsrf/other/genForm//?apinonce=83ee9cbf3294dd53&hrefId=4

ZAP Error [java.net.UnknownHostException]: www.localhost.com

Stack Trace:
java.net.UnknownHostException: www.localhost.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kingthorin** [comment]
You should be able to get it manually via: http://localhost:8080/UI/acsrf/other/genForm/

hrefId will be the messageId of the history item for which you want the form made.

Are you using Windows?

**Comment by kingthorin** [comment]
I just did a quick bit of testing with this. It seems like a few bugs might be in play here.
1. The nonce is rejected because the PATHs don't match due to a missing leading slash:

>30981 [ZAP-ProxyThread-1] WARN org.zaproxy.zap.extension.api.API  - API nonce path was OTHER/acsrf/other/genForm/ but call was for /OTHER/acsrf/other/genForm/ in request from 127.0.0.1

When Firefox (that's what I was using) gets this reset/rejection from ZAP it tries hard to resolve localhost and ends up with www.localhost.com (I think).

2. The URL contains a double slash due to this code: https://github.com/zaproxy/zaproxy/blob/develop/src/org/zaproxy/zap/extension/api/API.java#L545-L547 at 545 the path ends in a slash but at 547 a second one is added.
3. I also noticed that all 10 proxy threads warn in the logs:

> 30981 [ZAP-ProxyThread-1] WARN org.zaproxy.zap.extension.api.API  - API nonce path was OTHER/acsrf/other/genForm/ but call was for /OTHER/acsrf/other/genForm/ in request from 127.0.0.1
> 31018 [ZAP-ProxyThread-2] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31058 [ZAP-ProxyThread-3] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31095 [ZAP-ProxyThread-4] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31132 [ZAP-ProxyThread-5] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31171 [ZAP-ProxyThread-6] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31206 [ZAP-ProxyThread-7] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31241 [ZAP-ProxyThread-8] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31275 [ZAP-ProxyThread-9] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1
> 31290 [ZAP-ProxyThread-10] WARN org.zaproxy.zap.extension.api.API  - API nonce bda18a667c68fe3b not found in request from 127.0.0.1

4. If I replace the nonce with my current key the request seems to work as expected (which is just further proof of no. 1....from my PoV):
http://localhost:8080/OTHER/acsrf/other/genForm/?apikey=mycurrentkey&hrefId=12

**Comment by ArunObappa** [comment]
http://www.localhost.com:8080/OTHER/acsrf/other/genForm/?apikey=myapikey&hrefId=4

Changing URL as per point 4 above did not help

**Comment by thc202** [comment]
Did you also change the hostname (to localhost)?

**Comment by ArunObappa** [comment]
my post request have the URL http://servername/mitcsrf/Default.aspx

"Generate Anti-CSRF Test Form" I changed as below. I still have same problem.
http://www.localhost.com:8080/OTHER/acsrf/other/genForm/?apikey=myapikey&hrefId=16

Please let me know, if I need to do further changes to URL

Is there a way I can install 2.5.0

**Comment by thc202** [comment]
You need to change the URL to match ZAP's address:
http://localhost:8080/OTHER/acsrf/other/genForm/?apikey=myapikey&hrefId=16
(Assuming that ZAP is listening on localhost:8080)

If that still fails you need to ensure that you are allowed to access the API (in case you are accessing ZAP remotely from other machine than the one that ZAP is running). [1]

> Is there a way I can install 2.5.0

Yes, you can still use an older version:
https://github.com/zaproxy/zaproxy/releases/download/2.5.0/ZAP_2.5.0_Cross_Platform.zip
(This one doesn't require installation, just unzip and run.)

[1] https://github.com/zaproxy/zaproxy/wiki/FAQapikey

**Comment by thc202** [comment]
@kingthorin regarding 3., that's the browser retrying the requests.

**Comment by kingthorin** [comment]
>@kingthorin regarding 3., that's the browser retrying the requests.

Ok thanks, that makes sense.

**Comment by ArunObappa** [comment]
Thanks thc202 for older version !

Thanks kingthorin, works after dropping  "www." and ".com"
