### ISSUE TITLE
OpenAPI - unrecognized token

### ISSUE THREAD

**Issue by jammasterj89** [zaproxy/zaproxy#3644]
When pulling Docker latest for the ZAP baseline script, the following error has been occurring since 06/06/17 and is still happening today:

```Jun 06, 2017 3:36:12 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'var': was expecting ('true', 'false' or 'null')
 at [Source: /tmp/openapi2489431460889094311.defn; line: 2, column: 5]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:65)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:93)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:68)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:54)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:397)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:259)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Total of 24 URLs
PASS: Cookie No HttpOnly Flag [10010]
PASS: Cookie Without Secure Flag [10011]
...

**Comment by psiinon** [comment]
The error implies there is an issue with your OpenAPI definition on line 2 column 5: the token 'var' appears where the parser expects 'true', 'false' or 'null.
Can you check your definition and see if its valid?
Would it be possible to share it, or the relevant portion of it?

**Comment by jammasterj89** [comment]
Hello, thanks @psiinon. Ah right that's interesting because this is a live system it doesn't have any OpenAPI info on there - I've just asked one of the developers and he said it was part of the source code so won't get compiled into the release. 

Is that what ZAP is doing at that point, scanning the OpenAPI documentation? Because the rest of the baseline scan runs fine after that error.

**Comment by psiinon** [comment]
Yeah, if ZAP detects Open API or SOAP defns it will try to parse and import them when spidering.
The error should impact anything else ZAP is doing, so you can just ignore it :)

**Comment by psiinon** [comment]
Ugh, updated comment to read 'shouldnt' ;)

**Comment by jammasterj89** [comment]
Okay thank you! Just looking through the zap-baseline.py, is it specified in that script where it looks for the defns? Just thinking if I could look at the same file that ZAP is scanning I might be able to debug the error.

**Comment by psiinon** [comment]
No, its provided by this add-on: https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsOpenapiOpenapi
Debug logging might help, but the easiest option is probably to open the site in ZAP and spider it, which should cause the defn to be found and imported (or not as the case may be).
Then you can use the Search tab to look for "swagger"

**Comment by jammasterj89** [comment]
Thanks for the help @psiinon. I've scanned a different site and got the same error (that site doesn't have any OpenAPI definitions either) and doing a manual spider with ZAP searching for "swagger" didn't return anything. Like you say the scanner still runs fine so its not a big deal, but I'll have a poke around and see if I can find out anything further and report back. Thanks again.

**Comment by thc202** [comment]
Might be a response with "application" Content-Type (most likely "application/javascript"?). Worth searching for "var" (for you initial report).

**Comment by kingthorin** [comment]
@jammasterj89 did you ever find anything further one this?

**Comment by jammasterj89** [comment]
Hi @kingthorin, apologies for my late reply. There is no swagger / openAPI endpoint exposed on this system. However, I have found some usage of swagger inside of a javascript file with the following:

// Api service object built from Swagger.io Codegen

require('./services/api/index.js');
require('./services/api-error-handler.js');
require('./services/api-helpers.js');

I need to speak to a developer once I'm back in the office to clarify how this all works, but it looks like it has the code to create a swagger file. Once I know I'll post back. The only thing I can think of is ZAP is maybe seeing this and trying to test an endpoint that doesn't exist.

I've also spidered the site using ZAP 2.7.0 with the openAPI plugin installed, and it doesn't pick anything up, I also can't find any reference to "var"other than a lot of variable assignments in minified javascript files.

**Comment by thc202** [comment]
The error is expected then, ZAP is trying to parse a JavaScript file as a Swagger/OpenAPI definition (which leads to that error). I guess we could change the add-on to be stricter (but we might miss valid definitions?).

**Comment by thc202** [comment]
I believe that's a side effect of the changes done for #3479, now instead of printed the exception is logged.

**Comment by jammasterj89** [comment]
Okay thanks @thc202, I'm happy to close this unless you disagree.

**Comment by thc202** [comment]
Fine to leave it closed, lets see what others think though. @kingthorin, @psiinon should we keep the current behaviour? Or, better stricter to avoid logging the error?
