### ISSUE TITLE
Error when opening session file

### ISSUE THREAD

**Issue by dbilling-mdsol** [zaproxy/zaproxy#3655]
I get this error in zap.log when opening a saved session file:

2017-06-14 09:12:14,446 [AWT-EventQueue-0] INFO  MenuFileControl - opening session file C:\Users\dbilling\Scans\zap_sm_im_q2_13062017-20170614-021906.session
2017-06-14 09:12:14,453 [AWT-EventQueue-0] INFO  Control - Open Session
2017-06-14 09:12:14,555 [Thread-24] INFO  ENGINE - dataFileCache commit start
2017-06-14 09:12:14,567 [Thread-24] INFO  ENGINE - dataFileCache commit end
2017-06-14 09:12:15,538 [Thread-24] INFO  ENGINE - Database closed
2017-06-14 09:12:15,672 [Thread-24] INFO  ENGINE - open start - state not modified
2017-06-14 09:12:15,679 [Thread-24] INFO  ENGINE - dataFileCache open start
2017-06-14 09:12:15,680 [Thread-24] INFO  ENGINE - dataFileCache open end
2017-06-14 09:12:15,738 [Thread-24] ERROR ExtensionWebSocket - java.sql.SQLNonTransientConnectionException: connection exception: closed
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.parosproxy.paros.db.paros.ParosTableSessionUrl.getUrlsForType(Unknown Source)
	at org.zaproxy.zap.extension.websocket.ExtensionWebSocket.sessionChanged(ExtensionWebSocket.java:866)
	at org.parosproxy.paros.extension.ExtensionLoader.sessionChangedAllPlugin(Unknown Source)
	at org.parosproxy.paros.control.Control.sessionOpened(Unknown Source)
	at org.parosproxy.paros.model.Session$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source)
	... 6 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 8 more

The zap UI just returns a generic "an error has occurred when opening session" error message.

Any thoughts?

**Comment by kingthorin** [comment]
@dbilling-mdsol ZAP 2.6.0? Websockets extension v12?

As a test: 

- Could you make a copy of the session files (to keep as your 'gold' standard). 
- Open ZAP, un-install the WebSockets extension. (Restart ZAP if necessary.)
- Open the session.

**Comment by dbilling-mdsol** [comment]
I'll have to run the scan again, but yes, I can do that.

**Comment by kingthorin** [comment]
@dbilling-mdsol any news?

**Comment by kingthorin** [comment]
@dbilling-mdsol any news?
