### ISSUE TITLE
plug-n-hack installation error 

### ISSUE THREAD

**Issue by Sravan-Apps** [zaproxy/zaproxy#3682]
@psiinon 
I am using Firefox  on Firefox 45.6.0.
I tried to install plug-n-hack but it failed with below error. 
I did tried by disabling nounce in API, but that too did not work.

```
582541 [ZAP-ProxyThread-5] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-ProxyThread-5"
java.lang.NoSuchMethodError: org.zaproxy.zap.extension.api.API.getApiKey()Ljava/lang/String;
	at org.zaproxy.zap.extension.plugnhack.PlugNHackAPI.handleShortcut(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
586900 [ZAP-ProxyThread-6] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-ProxyThread-6"
java.lang.NoSuchMethodError: org.zaproxy.zap.extension.api.API.getApiKey()Ljava/lang/String;
	at org.zaproxy.zap.extension.plugnhack.PlugNHackAPI.handleShortcut(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)


```
 I am using ZAP 2.6.0 on Debain 64 bit.

```
$ java -version
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb8u1)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
```

**Comment by thc202** [comment]
Merging into #2069, the add-on is currently non-functional (e.g. the Firefox plugin is not signed yet). I'll remove the current version from the marketplace.

**Comment by thc202** [comment]
The add-on is no longer available in the marketplace. Please, subscribe to #2069 for updates about its state.

**Comment by psiinon** [comment]
However the client side aspects of PnH should still work (ie intercepting and changing PostMessages, which I think is why we kept it available.

**Comment by thc202** [comment]
Sorry, will restore it. Might worth releasing a new version? (To fix the binary incompatible changes.)

**Comment by psiinon** [comment]
yeah, we should do that

**Comment by thc202** [comment]
New version released.
