### ISSUE TITLE
NPE in ExtensionAlertFilters

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#3683]
Reported via https://groups.google.com/d/msg/zaproxy-users/WLxf8IwSC-0/CsDMUxGbAQAJ
Looks like we should be checking for a null context at https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/alertFilters/ExtensionAlertFilters.java#L387

```
396503 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters  - Error handling alert
java.lang.NullPointerException
        at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.handleAlert(ExtensionAlertFilters.java:387)
        at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.handleAlert(ExtensionAlertFilters.java:357)
        at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.eventReceived(ExtensionAlertFilters.java:326)
        at org.zaproxy.zap.eventBus.SimpleEventBus.publishSyncEvent(Unknown Source)
        at org.zaproxy.zap.extension.alert.ExtensionAlert.publishAlertEvent(Unknown Source)
        at org.zaproxy.zap.extension.alert.ExtensionAlert.alertFound(Unknown Source)
        at org.zaproxy.zap.extension.pscan.PassiveScanThread.raiseAlert(Unknown Source)
        at org.zaproxy.zap.extension.pscanrules.CacheControlScanner.raiseAlert(CacheControlScanner.java:118)
        at org.zaproxy.zap.extension.pscanrules.CacheControlScanner.scanHttpResponseReceive(CacheControlScanner.java:84)
        at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(Unknown Source)
```

**Comment by smichka** [comment]
Steps to reproduce:
1) Start owasp zap in daemon mode (zap.sh -daemon -config api.disablekey=true -host localhost -port 8080)
2) Import context X over HTTP-API (http://localhost:8080/UI/context/action/importContext/)
3) Load a session, which references the exact same context X over HTTP-API (http://localhost:8080/UI/core/action/loadSession/) as imported before.

=> Exception:
217303 [ZAP-ProxyThread-71] INFO org.parosproxy.paros.control.Control  - Session file opened
228514 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters  - Error handling alert
java.lang.NullPointerException
        at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.handleAlert(ExtensionAlertFilters.java:387)
        at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.handleAlert(ExtensionAlertFilters.java:357)
        at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.eventReceived(ExtensionAlertFilters.java:326)
        at org.zaproxy.zap.eventBus.SimpleEventBus.publishSyncEvent(Unknown Source)
        at org.zaproxy.zap.extension.alert.ExtensionAlert.publishAlertEvent(Unknown Source)
        at org.zaproxy.zap.extension.alert.ExtensionAlert.alertFound(Unknown Source)
        at org.zaproxy.zap.extension.pscan.PassiveScanThread.raiseAlert(Unknown Source)
        at org.zaproxy.zap.extension.pscanrules.XContentTypeOptionsScanner.raiseAlert(XContentTypeOptionsScanner.java:97)
        at org.zaproxy.zap.extension.pscanrules.XContentTypeOptionsScanner.scanHttpResponseReceive(XContentTypeOptionsScanner.java:69)
        at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(Unknown Source)

-----------
If I skip step 2, there are no any NPE's thrown.

**Comment by thc202** [comment]
Thanks for the steps!

Note that the session contains the contexts, loading/creating a session will remove the contexts previously imported/added (if it's a new context you should load the session first then import the context).

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#937.

**Comment by setzamora** [comment]
I'm getting this error on zap2docker-stable. Is there a way to clear the alert filters explicitly after creating a new session?

**Comment by thc202** [comment]
Which image (ID)?

**Comment by setzamora** [comment]
owasp/zap2docker-stable 2.7.0

![image](https://user-images.githubusercontent.com/18208623/37832525-3ced53a4-2e7f-11e8-8ead-ac3504b8ae66.png)

**Comment by thc202** [comment]
OK, that's #4405. You would have to start ZAP with `-addoninstall alertFilters` to pick the latest version of the add-on.

**Comment by setzamora** [comment]
Perfect. Thank you @thc202 .

**Comment by thc202** [comment]
No problem.
