### ISSUE TITLE
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() for SELECTs

### ISSUE THREAD

**Issue by SyCode7** [zaproxy/zaproxy#3703]
I have just tried to replace the default HSQL with MYSQL on my windows 10 machine. However, I have the following error in the terminal after making the necessary changes in the file "mysql.schema".
`12549 [AWT-EventQueue-0] ERROR org.parosproxy.paros.model.Session  - java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
        at org.zaproxy.zap.db.sql.SqlTableContext.deleteAllDataForContextAndType(Unknown Source)
        at org.zaproxy.zap.db.sql.SqlTableContext.setData(Unknown Source)
        at org.parosproxy.paros.model.Session.setContextData(Unknown Source)
        at org.parosproxy.paros.model.Session.setContextData(Unknown Source)
        at org.parosproxy.paros.model.Session.saveContext(Unknown Source)
        at org.parosproxy.paros.model.Model.newSession(Unknown Source)
        at org.parosproxy.paros.control.Control.createNewSession(Unknown Source)
        at org.parosproxy.paros.control.Control.newSession(Unknown Source)
        at org.parosproxy.paros.control.MenuFileControl.newSession(Unknown Source)
        at org.parosproxy.paros.control.MenuFileControl.newSession(Unknown Source)
        at org.zaproxy.zap.GuiBootstrap$3.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.sql.SQLException: Can not issue executeUpdate() or executeLargeUpdate() for SELECTs
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2045)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
`

**Comment by kingthorin** [comment]
Version of ZAP?
Version of MySQL?

**Comment by thc202** [comment]
Can be reproduced with latest ZAP version (MySQL version does not matter, I think, ZAP is using wrong queries).

**Comment by kingthorin** [comment]
K
