### ISSUE TITLE
Session snapshots might "break" running scans

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3711]
Steps to reproduce the issue:
1. Start ZAP and persist the session;
2. Run the spider;
3. Take a snapshot (while the spider is running);
4. Note a lot of exceptions in the log file, e.g.:
```
62917 [ZAP-SpiderThreadPool-0-thread-2] ERROR org.zaproxy.zap.extension.spider.SpiderThread  - java.sql.SQLNonTransientConnectionException: connection exception: closed
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)
	at org.parosproxy.paros.model.HistoryReference.<init>(Unknown Source)
	at org.zaproxy.zap.extension.spider.SpiderThread.readURI(Unknown Source)
	at org.zaproxy.zap.spider.Spider.notifyListenersReadURI(Unknown Source)
	at org.zaproxy.zap.spider.SpiderTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(Unknown Source)
	... 8 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 11 more
```

Remarks:
The issue might not happen always, it depends on the scanners accessing the session (while it's being copied).

ZAP version:
Version 2.6.0 (older versions are also affected).

**Comment by thc202** [comment]
From discussion in IRC, we should warn/inform of the active actions before proceeding with the session snapshot.
