### ISSUE TITLE
CookieLooselyScopedScanner: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rain0r** [zaproxy/zaproxy#3713]
This part of the [code ](https://github.com/zaproxy/zap-extensions/blob/beta/src/org/zaproxy/zap/extension/pscanrulesBeta/CookieLooselyScopedScanner.java#L142)raises an ArrayIndexOutOfBoundsException:

`		if (!cookieDomains[cookieDomains.length - 2].equalsIgnoreCase(hostDomains[hostDomains.length - 2])) {`

```
2017-06-28 09:30:16,267 [ZAP-PassiveScanner] ERROR PassiveScanThread - Scanner Loosely Scoped Cookie failed on record 1 from History table: GET http://localhost:8080/tan/
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.zaproxy.zap.extension.pscanrulesBeta.CookieLooselyScopedScanner.isCookieAndHostHaveTheSameDomain(CookieLooselyScopedScanner.java:142)
	at org.zaproxy.zap.extension.pscanrulesBeta.CookieLooselyScopedScanner.isLooselyScopedCookie(CookieLooselyScopedScanner.java:100)
	at org.zaproxy.zap.extension.pscanrulesBeta.CookieLooselyScopedScanner.scanHttpResponseReceive(CookieLooselyScopedScanner.java:67)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:148)
```

ZAP-Version: ZAP_WEEKLY_D-2017-06-27

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#942.
