### ISSUE TITLE
Can't open the Resend window because of missing font

### ISSUE THREAD

**Issue by junmoxiao** [zaproxy/zaproxy#3779]
when I in request windows,click the resend button,the resend window did't appear.
this function is work when I use windows 7.
<img width="799" alt="zap" src="https://user-images.githubusercontent.com/9711902/28560574-d7bb720c-714d-11e7-814d-2cee824b7ea4.png">

xiao@cat ~/t/ZAP_D-2017-07-17> java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

the manual request editor is on work.
<img width="1276" alt="zap2" src="https://user-images.githubusercontent.com/9711902/28560793-89ff0b72-714e-11e7-869a-3ea73a1c9a8c.png">

**Comment by kingthorin** [comment]
What version of ZAP are you using?
Are you able to try this with a weekly? https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by thc202** [comment]
Seems that happened using a weekly `ZAP_D-2017-07-17`. Worth taking a look at the log when that happens.

**Comment by junmoxiao** [comment]
@kingthorin 
yes, i use the latest weekly version.just i used the 

Weekly - cross platform | 2017-10-02 | 279 MB .
and when i right click and choose "Open/Resend With Request Editor",it still can't work

**Comment by junmoxiao** [comment]
@thc202 
47753 [AWT-EventQueue-0] ERROR org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer  -
java.lang.NullPointerException
    at org.zaproxy.zap.utils.FontUtils.getFont(FontUtils.java:93)
    at org.zaproxy.zap.extension.viewstate.HttpPanelViewStateView.getContainerPanel(HttpPanelViewStateView.java:117)
    at org.zaproxy.zap.extension.viewstate.HttpPanelViewStateView.getPane(HttpPanelViewStateView.java:98)
    at org.zaproxy.zap.extension.viewstate.HttpPanelViewStateView.getPane(HttpPanelViewStateView.java:51)
    at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.addView(HttpPanelComponentViewsManager.java:317)
    at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.addView(HttpPanelComponentViewsManager.java:366)
    at org.zaproxy.zap.extension.httppanel.component.split.request.RequestSplitComponent.addView(RequestSplitComponent.java:190)
    at org.zaproxy.zap.extension.httppanel.HttpPanel.addView(HttpPanel.java:525)
    at org.zaproxy.zap.view.HttpPanelManager$HttpPanelManagement.addPanel(HttpPanelManager.java:175)
    at org.zaproxy.zap.view.HttpPanelManager.addRequestPanel(HttpPanelManager.java:61)
    at org.zaproxy.zap.extension.httppanel.HttpPanelRequest.<init>(HttpPanelRequest.java:42)
    at org.parosproxy.paros.extension.manualrequest.http.impl.ManualHttpRequestEditorDialog.getRequestPanel(ManualHttpRequestEditorDialog.java:155)
    at org.parosproxy.paros.extension.manualrequest.http.impl.ManualHttpRequestEditorDialog.<init>(ManualHttpRequestEditorDialog.java:98)
    at org.parosproxy.paros.extension.history.ExtensionHistory.getResendDialog(ExtensionHistory.java:540)
    at org.zaproxy.zap.extension.stdmenus.PopupMenuResendMessage.performAction(PopupMenuResendMessage.java:43)
    at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer.performActions(PopupMenuItemHttpMessageContainer.java:563)
    at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer.performActions(PopupMenuItemHttpMessageContainer.java:544)
    at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer$PerformActionsActionListener.actionPerformed(PopupMenuItemHttpMessageContainer.java:587)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by junmoxiao** [comment]
this happen on all HTTP messages

**Comment by thc202** [comment]
Thanks!

**Comment by kingthorin** [comment]
The offending code seems to be:
`vsInfoTxt.setFont(FontUtils.getFont("Courier", Font.BOLD));`

I read some posts that suggest "Courier New" is generally widely available and default. Other things suggest that the following would generally work `vsInfoTxt.setFont(Font.MONOSPACED, Font.BOLD));`

**Comment by junmoxiao** [comment]
@kingthorin You mean there is no font like Courier in the system?

**Comment by kingthorin** [comment]
That seems to be Jack's issue if you read the exception/code.

Yup could remove the Viewstate add-on, restart ZAP and see if Resend works.

**Comment by thc202** [comment]
That can also be achieved by just disabling the extension `ExtensionHttpPanelViewStateView`. [1] (It still requires the restart of ZAP though.)

[1] https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsExt

**Comment by thc202** [comment]
@kingthorin yeah, use of `Font.MONOSPACED` is probably better, we still need to change core to fail gracefully when the font is not available though.

**Comment by junmoxiao** [comment]
@kingthorin Yes, when I uninstall the Viewstate extension, I can open the resend window

**Comment by kingthorin** [comment]
Ok, thanks for confirming.

**Comment by thc202** [comment]
Took a look at the code again, it seems it's failing because it's missing the default font of the L&F (`FontUtils` already handles that case in other methods, just not the one being called). Still we should probably change the font requested in the add-on.

**Comment by thc202** [comment]
@junmoxiao could you confirm that you are able to open the Resend dialogue with the latest weekly release? (You might need to install the Viewstate add-on.)

**Comment by junmoxiao** [comment]
@thc202 
`72990 [AWT-EventQueue-0] ERROR org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer  -
java.lang.NullPointerException
	at org.zaproxy.zap.utils.FontUtils.getFont(FontUtils.java:93)
	at org.zaproxy.zap.extension.viewstate.HttpPanelViewStateView.getContainerPanel(HttpPanelViewStateView.java:117)
	at org.zaproxy.zap.extension.viewstate.HttpPanelViewStateView.getPane(HttpPanelViewStateView.java:98)
	at org.zaproxy.zap.extension.viewstate.HttpPanelViewStateView.getPane(HttpPanelViewStateView.java:51)
	at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.addView(HttpPanelComponentViewsManager.java:317)
	at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.addView(HttpPanelComponentViewsManager.java:366)
	at org.zaproxy.zap.extension.httppanel.component.split.request.RequestSplitComponent.addView(RequestSplitComponent.java:190)
	at org.zaproxy.zap.extension.httppanel.HttpPanel.addView(HttpPanel.java:525)
	at org.zaproxy.zap.view.HttpPanelManager$HttpPanelManagement.addPanel(HttpPanelManager.java:175)
	at org.zaproxy.zap.view.HttpPanelManager.addRequestPanel(HttpPanelManager.java:61)
	at org.zaproxy.zap.extension.httppanel.HttpPanelRequest.<init>(HttpPanelRequest.java:42)
	at org.parosproxy.paros.extension.manualrequest.http.impl.ManualHttpRequestEditorDialog.getRequestPanel(ManualHttpRequestEditorDialog.java:155)
	at org.parosproxy.paros.extension.manualrequest.http.impl.ManualHttpRequestEditorDialog.<init>(ManualHttpRequestEditorDialog.java:98)
	at org.parosproxy.paros.extension.history.ExtensionHistory.getResendDialog(ExtensionHistory.java:540)
	at org.zaproxy.zap.extension.stdmenus.PopupMenuResendMessage.performAction(PopupMenuResendMessage.java:43)
	at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer.performActions(PopupMenuItemHttpMessageContainer.java:563)
	at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer.performActions(PopupMenuItemHttpMessageContainer.java:544)
	at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer$PerformActionsActionListener.actionPerformed(PopupMenuItemHttpMessageContainer.java:587)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

I Just download the latest weekly release(ZAP_D-2017-10-09). After install the viewstate  add-on and then still can't open the Resend dialogue.

**Comment by thc202** [comment]
Sorry, I thought the change ended up in the weekly but it didn't. Following a zap.jar that contains the change:
https://github.com/thc202/zaproxy/releases/download/w2016-10-25/zap-D-2017-10-09.jar

(You just need to replace it.)

**Comment by junmoxiao** [comment]
@thc202 Yes, it can work properly

**Comment by junmoxiao** [comment]
Thank you for your help

**Comment by thc202** [comment]
Thank you!
