### ISSUE TITLE
Mapping to different host port not working with Docker container

### ISSUE THREAD

**Issue by kiview** [zaproxy/zaproxy#3796]
If I want to map ZAP to a different host port, like this, 

```
docker run -p 9090:8090 -i owasp/zap2docker-stable zap.sh -daemon -port 8090 -host 0.0.0.0 -config 'api.disablekey=true' -config 'api.addrs.addr.name=.*' -config 'api.addrs.addr.regex=true'
```
 ZAP won't accept the connection and will return the following stacktrace inside the HTTP body:

```
ZAP Error [java.net.ConnectException]: Connection refused (Connection refused)

Stack Trace:
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(Unknown Source)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(Unknown Source)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(Unknown Source)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.runMethod(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.send(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thc202** [comment]
What's the request sent to ZAP? An API request?

It seems ZAP is accepting the connection and it's attempting to connect to the target (and failing since there's nothing listening on 9090?).

**Comment by kiview** [comment]
This even happens when accessing the UI with a browser on `http://localhost:9090`.

**Comment by psiinon** [comment]
Are there any errors logged in the zap.log file?

**Comment by thc202** [comment]
@kiview the request is not "translated", it's passed as is, e.g.:
```
GET / HTTP/1.1
Host: localhost:9090
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
```
so ZAP will receive a request to 9090 not to 8090/itself. To access the ZAP API you can use `http://zap` (if proxying through `localhost:9090`).

**Comment by kiview** [comment]
Is this a problem specific to ZAP's HTTP implementation? I've never had a similar error regarding host port mapping and Java applications, i.e. Spring-Boot apps.

**Comment by thc202** [comment]
ZAP is a special case since it also acts as proxy, so the contents of the host header are relevant and Docker is just forwarding the request to ZAP, not changing the request (i.e. Host header). For ZAP that's just a request to proxy/forward to another server (form ZAP side there's not enough information to know that 9090 is intended to be 8090).

I guess we could allow to specify which ports the ZAP API should served?

What's the use case for the mapping, can't ZAP listen on 9090?

**Comment by psiinon** [comment]
Good point, starting ZAP on 9090 should solve this problem, no?

**Comment by kiview** [comment]
The use case is a highly dynamic containerized CI environment (currently Gitlab-CI), which will map the container ports to random free host ports. To be really concrete, it's the integration with https://github.com/testcontainers/testcontainers-java, which is a great library for instrumenting dockerized integration tests.

**Comment by mkonwerski** [comment]
I Have this same problem. Is someone who fix this issue

**Comment by scentro** [comment]
I have the same problem. I would like to map a dynamic port to internal zap 8080 port. that way I can just keep the zap internal port config the same.

**Comment by brian-villanueva** [comment]
I ran into the same problem but found that it's important to have the ports matching. I also noticed that if you're using zap-cli, there is a ZAP_PORT environment variable that you must set if you change from the default port 8080. (Or alternatively you can pass a --port argument on every CLI command, but that's a little awkward IMO.) So set ZAP_PORT in your container and start zap with that port as well and you should be ok.
