### ISSUE TITLE
java.awt.Toolkit initialised when running without view

### ISSUE THREAD

**Issue by nkpathrut** [zaproxy/zaproxy#3798]
I have tried to implement the following youtube demo but not performed well. 

https://youtu.be/swDRxxqFmjo

I have tried to perform security test on the sample App as show in video.

The following logs I got in Jenkins : 

Started by user admin
Building in workspace /var/lib/jenkins/workspace/zap_demo1
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/Eficode/security_testing_demo_app # timeout=10
Fetching upstream changes from https://github.com/Eficode/security_testing_demo_app
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/Eficode/security_testing_demo_app +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 7086f9056675491013a2eb80ba5980cf8636ed4f (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7086f9056675491013a2eb80ba5980cf8636ed4f
 > git rev-list 7086f9056675491013a2eb80ba5980cf8636ed4f # timeout=10

<details>
<summary>Log output (click to expand)</summary>

```console
[ZAP Jenkins Plugin] START PRE-BUILD ENVIRONMENT VARIABLE REPLACEMENT
	HOST = [ localhost ]
	PORT = [ 9999 ]

	SESSION FILENAME = [  ]
	INTERNAL SITES = [  ]

	CONTEXT NAME = [ testsession ]

	INCLUDE IN CONTEXT = [ http://127.0.0.1:7272 ]

	EXCLUDE FROM CONTEXT = [  ]

	STARTING POINT (URL) = [ http://127.0.0.1:7272 ]
	REPORT FILENAME = [ JENKINS_ZAP_VULNERABILITY_REPORT_new_reports ]
	REPORT TITLE = [  ]

	COMMAND LINE = 

[ZAP Jenkins Plugin] END PRE-BUILD ENVIRONMENT VARIABLE REPLACEMENT

[ZAP Jenkins Plugin] CLEAR LOGS IN SETTINGS...
	ZAP HOME DIRECTORY [ ~/.ZAP ]
	JENKINS WORKSPACE [ /var/lib/jenkins/workspace/zap_demo1 ]
	CLEARING ZAP HOME DIRECTORY/LOGS

[zap_demo1] $ /bin/sh -xe /tmp/hudson8989210358448731038.sh
+ ./start.sh
[zap_demo1] $ /bin/sh -xe /tmp/hudson1645626650176217381.sh
+ cat server.pid
+ kill 16530
[zap_demo1] $ /bin/sh -xe /tmp/hudson1414936493837958112.sh
+ rm server.pid

[ZAP Jenkins Plugin] START BUILD STEP

[ZAP Jenkins Plugin] PLUGIN VALIDATION (PLG), VARIABLE VALIDATION AND ENVIRONMENT INJECTOR EXPANSION (EXP)
	ZAP INSTALLATION DIRECTORY = [ /var/lib/jenkins/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/zap/ZAP_2.6.0 ]
	(EXP) HOST = [ localhost ]
	(EXP) PORT = [ 9999 ]
	(EXP) LOAD SESSION = [ /var/lib/jenkins/workspace/zap_demo1/test/za_proxy/zap_session.session ]
	(EXP) CONTEXT NAME = [ testsession ]
	(EXP) INCLUDE IN CONTEXT = [ http://127.0.0.1:7272 ]
	(EXP) EXCLUDE FROM CONTEXT = [  ]
	(EXP) STARTING POINT (URL) = [ http://127.0.0.1:7272 ]
	(EXP) REPORT FILENAME = [ JENKINS_ZAP_VULNERABILITY_REPORT_new_reports ]

[ZAP Jenkins Plugin] CONFIGURE RUN COMMANDS for [ /var/lib/jenkins/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/zap/ZAP_2.6.0/zap.sh ]
[ZAP Jenkins Plugin] EXECUTE LAUNCH COMMAND
[ZAP_2.6.0] $ /var/lib/jenkins/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/zap/ZAP_2.6.0/zap.sh -daemon -host localhost -port 9999 -config api.key=ZAPROXY-PLUGIN

[ZAP Jenkins Plugin] INITIALIZATION [ START ]
Found Java version 1.8.0_131
Available memory: 3951 MB
Setting jvm heap size: -Xmx987m
0 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP 2.6.0 started 03/08/17 15:03:41
41 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.key = ZAPROXY-PLUGIN was null
48 [main] INFO org.parosproxy.paros.network.SSLConnector  - Reading supported SSL/TLS protocols...
48 [main] INFO org.parosproxy.paros.network.SSLConnector  - Using a SSLEngine...
186 [main] INFO org.parosproxy.paros.network.SSLConnector  - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
193 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate  - Unsafe SSL renegotiation disabled.
729 [main] INFO hsqldb.db..ENGINE  - open start - state not modified
932 [main] INFO hsqldb.db..ENGINE  - dataFileCache open start
943 [main] INFO hsqldb.db..ENGINE  - dataFileCache open end
1055 [ZAP-daemon] INFO org.zaproxy.zap.control.ExtensionFactory  - Loading extensions
1161 [ZAP-daemon] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-daemon"
java.awt.AWTError: Can't connect to X11 window server using ':99' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at javax.swing.ImageIcon.<init>(ImageIcon.java:198)
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at org.zaproxy.zap.extension.ascan.ExtensionActiveScan.<clinit>(Unknown Source)
	at org.zaproxy.zap.control.CoreFunctionality.createExtensions(Unknown Source)
	at org.zaproxy.zap.control.CoreFunctionality.getBuiltInExtensions(Unknown Source)
	at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(Unknown Source)
	at org.parosproxy.paros.control.Control.addExtension(Unknown Source)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(Unknown Source)
	at org.parosproxy.paros.control.Control.init(Unknown Source)
	at org.parosproxy.paros.control.Control.initSingletonWithoutViewAndProxy(Unknown Source)
	at org.zaproxy.zap.HeadlessBootstrap.initControl(Unknown Source)
	at org.zaproxy.zap.DaemonBootstrap$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

ERROR: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jenkinsci.plugins.zap.ZAPDriver.waitForSuccessfulConnectionToZap(ZAPDriver.java:746)
	at org.jenkinsci.plugins.zap.ZAPDriver.access$100(ZAPDriver.java:112)
	at org.jenkinsci.plugins.zap.ZAPDriver$WaitZAPDriverInitCallable.invoke(ZAPDriver.java:2710)
	at org.jenkinsci.plugins.zap.ZAPDriver$WaitZAPDriverInitCallable.invoke(ZAPDriver.java:2696)
	at hudson.FilePath.act(FilePath.java:996)
	at hudson.FilePath.act(FilePath.java:974)
	at org.jenkinsci.plugins.zap.ZAPDriver.startZAP(ZAPDriver.java:659)
	at org.jenkinsci.plugins.zap.ZAPBuilder.perform(ZAPBuilder.java:277)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)

ERROR: Unable to connect to ZAP's proxy after 60 seconds.
	at org.jenkinsci.plugins.zap.ZAPDriver.waitForSuccessfulConnectionToZap(ZAPDriver.java:767)
	at org.jenkinsci.plugins.zap.ZAPDriver.access$100(ZAPDriver.java:112)
	at org.jenkinsci.plugins.zap.ZAPDriver$WaitZAPDriverInitCallable.invoke(ZAPDriver.java:2710)
	at org.jenkinsci.plugins.zap.ZAPDriver$WaitZAPDriverInitCallable.invoke(ZAPDriver.java:2696)
	at hudson.FilePath.act(FilePath.java:996)
	at hudson.FilePath.act(FilePath.java:974)
	at org.jenkinsci.plugins.zap.ZAPDriver.startZAP(ZAPDriver.java:659)
	at org.jenkinsci.plugins.zap.ZAPBuilder.perform(ZAPBuilder.java:277)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)

Build step 'Execute ZAP' marked build as failure
Archiving artifacts
Finished: FAILURE
```

</details>

Anyone please help on same?

**Comment by thc202** [comment]
Are you using/starting Xvfb?

**Comment by nkpathrut** [comment]
No. I'm not using any Xvfb. I just followed step provided in the video
that has no any connectivity to Xvfb setting.

**Comment by nkpathrut** [comment]
I have added the OWASP ZAP using the custom global tool option. In manage jenkin options.

**Comment by thc202** [comment]
OK, this is a bug, the only workaround is to start the X11 window server before starting ZAP (e.g. `Xvfb :99`).

**Comment by nkpathrut** [comment]
Will you please elaborate more in term of activity steps in Jenkins and ZAP? I'm new to ZAP

**Comment by nkpathrut** [comment]
I have enabled 

Build Environment ->Start Xvfb before the build, and shut it down after.

in Jenkin's Build's Configuration. then the issue resolved.

Thank you so much.

**Comment by thc202** [comment]
Going to reopen this, pre previous comment this is a bug in ZAP (which should not be requiring the initialisation of the Toolkit in daemon mode, that's only expected if used JxBrowser, which is not the case).

**Comment by thc202** [comment]
Closing, core and default add-ons no longer have this issue.

**Comment by thc202** [comment]
Reopening per #7790.
