### ISSUE TITLE
latest weekly docker image not staying running

### ISSUE THREAD

**Issue by mikedouglasdev** [zaproxy/zaproxy#3811]
Hi,

I'm trying to start a container for OWASP ZAP in a Docker Swarm and it appears to start and then stop almost immediately after. If I change the container to use a previous image already downloaded it works fine.  Has anything changed in the latest release?

docker -H 172.16.0.5:2375 run -u zap -p 8098:8098 -d owasp/zap2docker-weekly zap.sh -daemon -port 8098 -host 0.0.0.0 -addonupdate -config database.recoverylog=false -config api.key=myapikey -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

Thanks,
Mike

**Comment by thc202** [comment]
No, nothing that would cause that (crash?).

Anything useful in the logs/output?

**Comment by mikedouglasdev** [comment]
How do I look at the logs?  Hopefully tonight I can research this.

If I change my run statement to use the previous weekly image, it will run fine.

docker -H 172.16.0.5:2375 run -u zap -p 8098:8098 -d **ea1f2d38fa51** zap.sh -daemon -port 8098 -host 0.0.0.0 -addonupdate -config database.recoverylog=false -config api.key=myapikey -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

Thanks,
Mike

**Comment by omerlh** [comment]
Could you try running `docker logs <container id>`?

**Comment by mikedouglasdev** [comment]
Here is the error if I run it from the SSH session.  Log file is below.  I ran the same exact command for the previous image and it works fine.
Let me know if you need anything else.

~$ docker -H 172.16.0.5:2375 run -u zap -p 8098:8098 -d owasp/zap2docker-weekly zap.sh -daemon -port 8098 -host 0.0.0.0 -addonupdate -config database.recoverylog=false -config api.key=myapikey -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
2551f166b7a7aa6e5d64d160876d66187950363a4b9c006861ccdcc850564213
ERRO[0000] error getting events from daemon: EOF

**Here are the logs**

Found Java version 1.8.0_131
Available memory: 1676 MB
Setting jvm heap size: -Xmx419m
750 [main] INFO org.zaproxy.zap.DaemonBootstrap  - OWASP ZAP D-2017-07-31 started 10/08/17 12:13:18 with home /home/zap/.ZAP_D/
882 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config database.recoverylog = false was null
883 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.key = myapikey was null
889 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.addrs.addr.name = .* was null
890 [main] INFO org.parosproxy.paros.common.AbstractParam  - Setting config api.addrs.addr.regex = true was null
946 [main] INFO org.parosproxy.paros.network.SSLConnector  - Reading supported SSL/TLS protocols...
947 [main] INFO org.parosproxy.paros.network.SSLConnector  - Using a SSLEngine...
1459 [main] INFO org.parosproxy.paros.network.SSLConnector  - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
1480 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate  - Unsafe SSL renegotiation disabled.
2757 [main] INFO hsqldb.db..ENGINE  - open start - state not modified
3295 [main] INFO hsqldb.db..ENGINE  - dataFileCache open start
3344 [main] INFO hsqldb.db..ENGINE  - dataFileCache open end
3630 [ZAP-daemon] INFO org.zaproxy.zap.control.ExtensionFactory  - Loading extensions
4094 [ZAP-daemon] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-daemon"
java.lang.ExceptionInInitializerError
        at org.zaproxy.zap.control.CoreFunctionality.createExtensions(CoreFunctionality.java:68)
        at org.zaproxy.zap.control.CoreFunctionality.getBuiltInExtensions(CoreFunctionality.java:60)
        at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:107)
        at org.parosproxy.paros.control.Control.addExtension(Control.java:160)
        at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:53)
        at org.parosproxy.paros.control.Control.init(Control.java:123)
        at org.parosproxy.paros.control.Control.initSingletonWithoutViewAndProxy(Control.java:313)
        at org.zaproxy.zap.HeadlessBootstrap.initControl(HeadlessBootstrap.java:58)
        at org.zaproxy.zap.DaemonBootstrap$1.run(DaemonBootstrap.java:77)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:236)
        at org.parosproxy.paros.extension.edit.ExtensionEdit.<clinit>(ExtensionEdit.java:49)
        ... 10 more
