### ISSUE TITLE
No operations allowed after statement closed

### ISSUE THREAD

**Issue by YangYongZhi** [zaproxy/zaproxy#3828]
I start a zaproxy instance on a server machine.
and use it in low memory mode and db experimental mode, but there are some database connection errors will be appear after a while.

The exception message is like this:

2017-08-04 18:41:08,639 [ZAP-ProxyThread-1414] DEBUG HttpSender - sendAndReceive GET http://captive.apple.com/hotspot-detect.html took 11650
2017-08-04 18:41:08,639 [Thread-1070] WARN  ProxyListenerLog - java.sql.SQLException: No operations allowed after statement closed.
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: No operations allowed after statement closed.
        at org.zaproxy.zap.db.sql.SqlTableHistory.write(Unknown Source)
        at org.zaproxy.zap.db.sql.SqlTableHistory.write(Unknown Source)
        at org.parosproxy.paros.model.HistoryReference.<init>(Unknown Source)
        at org.parosproxy.paros.extension.history.ProxyListenerLog.createHistoryReference(Unknown Source)
        at org.parosproxy.paros.extension.history.ProxyListenerLog.createAndAddMessage(Unknown Source)
        at org.parosproxy.paros.extension.history.ProxyListenerLog.access$000(Unknown Source)
        at org.parosproxy.paros.extension.history.ProxyListenerLog$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: No operations allowed after statement closed.
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
        at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442)
        at com.mysql.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3340)
        at com.mysql.jdbc.PreparedStatement.setLong(PreparedStatement.java:3368)
        ... 8 more

So I guess this is because  the connection has been closed by someone.

**Comment by thc202** [comment]
Could you provide more details? "after a while" does that mean always after ZAP is running for some time? Or, just after creating new sessions?

**Comment by YangYongZhi** [comment]
Hi , Thank you first.
Yes, this error will definitely appear every other night.

**Comment by kingthorin** [comment]
As was asked in the [dev group](https://groups.google.com/forum/#!topic/zaproxy-develop/cI9dsHFrCXo)
How long has ZAP been running? 
How big is the session?

https://groups.google.com/forum/#!topic/zaproxy-develop/Nq5VpK7-EO0
> You're probably best off just interfacing your App with the ZAP web API.
> 
> Currently ZAP isn't really built for a multi-user environment. There is progress being made towards ZAP as a Service (ZaaS): https://zaproxy.blogspot.ca/2015/05/zap-as-service-zaas.html
However, with a small core team of developers it's still quite a ways off.

**Comment by thc202** [comment]
I'm just able to reproduce the issue when changing the session (and by analysing the code it seems dependent on session changes).

@YangYongZhi are you also changing the session (e.g. create a new session, load)? If you still have the log does it show that the session was being changed prior the warning?

Worth noting that if it's the case of session changes it's expected that some of the requests might not be persisted while the session is being changed.

**Comment by kingthorin** [comment]
@YangYongZhi are you able to answer the previous questions from @kingthorin and @thc202.

**Comment by kingthorin** [comment]
Original reporter hasn't responded after more than 2 weeks, can this be closed?
