### ISSUE TITLE
Error whilst using Api - ERROR ExtensionUserManagement - Unable to persist Users

### ISSUE THREAD

**Issue by FlickerBean** [zaproxy/zaproxy#3854]
Getting this error whilst trying to use Form Based Authentication through the python api.

```
2017-08-30 09:18:11,542 [ZAP-ProxyThread-5] ERROR ExtensionUserManagement - Unable to persist Users.
java.lang.NullPointerException
        at org.zaproxy.zap.authentication.ManualAuthenticationMethodType$ManualAuthenticationCredentials.encode(ManualAuthenticationMethodType.java:203)
        at org.zaproxy.zap.users.User.encode(User.java:290)
        at org.zaproxy.zap.extension.users.ExtensionUserManagement.persistContextData(ExtensionUserManagement.java:271)
        at org.parosproxy.paros.model.Model.saveContext(Model.java:505)
        at org.parosproxy.paros.model.Session.saveContext(Session.java:1166)
        at org.zaproxy.zap.model.Context.save(Context.java:450)
        at org.zaproxy.zap.extension.users.UsersAPI.handleApiAction(UsersAPI.java:174)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:431)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:436)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:297)
        at java.lang.Thread.run(Thread.java:748)
2017-08-30 09:18:11,553 [ZAP-ProxyThread-6] WARN  API - ApiException while handling API request:
Missing Parameter (missing_parameter) : sessionName
        at org.zaproxy.zap.utils.ApiUtils.getNonEmptyStringParam(ApiUtils.java:83)
        at org.zaproxy.zap.authentication.ManualAuthenticationMethodType$2.handleAction(ManualAuthenticationMethodType.java:423)
        at org.zaproxy.zap.extension.users.UsersAPI.handleApiAction(UsersAPI.java:217)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:431)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:436)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:297)
        at java.lang.Thread.run(Thread.java:748)
```

I note a similar bug was fixed some time back: https://github.com/zaproxy/zaproxy/issues/1770

But this issue is occurring in both 2.6.0 stable, and the latest weekly.

Here is the relevant part of my script:

```python
target = 'http://127.0.0.1:8081/'
username='TTGA001312'
password='testtest1'
contextname = "testcontext"
authmethodname = 'formBasedAuthentication'
authmethodconfigparams = ''.join(("loginUrl="+target+"login/", urllib.quote_plus("username={%username%}&password={%password%}&LoginFormSubmit=1")))

# Use the line below if ZAP is not listening on 8090.
zap = ZAPv2(proxies={'http': 'http://127.0.0.1:8090'})

contextid = zap.context.new_context(contextname);
print "context: "+contextid


print "Including base URL..."
print zap.context.include_in_context(contextname, target+'.*')

print "Setting authentication method..."
print zap.authentication.set_authentication_method(
    contextid,
    authmethodname,
    authmethodconfigparams
)

print "Setting up session management method..."
print zap.sessionManagement.set_session_management_method(contextid, "cookieBasedSessionManagement", None)

print "Creating user..."
userid = zap.users.new_user(contextid, username)
print userid

print "Setting user credentials..."
print zap.users.set_authentication_credentials(contextid, userid, ''.join(("username=", username, "&password=", password)))
```

Is this a bug, or user error on my part?

**Comment by thc202** [comment]
This is a bug (more than one actually).

I've a question regarding the login URL, are the parameters (`username`, `password`, and `LoginFormSubmit`) really for the URL or that's for POST data?

**Comment by FlickerBean** [comment]
It's for POST data, however, as you can probably tell by the code, i'm not particularly (read not at all) strong in Python, nor the Zap Api.

What I have so far is what I've cobbled together from here there and everywhere! I was under the belief that authmethodconfigparams would get posted?

Is there a 4th parameter for set_authentication_method that takes POST data then?

**Comment by thc202** [comment]
Yes, but that's another parameter in `authmethodconfigparams`, called `loginRequestData`, e.g.:
```Python
authmethodconfigparams = ''.join(("loginUrl="+target+"login/", '&loginRequestData=', urllib.quote_plus("username={%username%}&password={%password%}&LoginFormSubmit=1")))
```
