### ISSUE TITLE
An error occurred while initialising JavaFX

### ISSUE THREAD

**Issue by pr0letariat** [zaproxy/zaproxy#3882]
I get the following error when starting ZAP:

![screenshot at 2017-09-14 10 20 05](https://user-images.githubusercontent.com/14975253/30421935-4dde44b8-9936-11e7-888a-a69df8a59666.png)

Here is what I suspect is relevant information from the terminal:

```
4659 [ZAP-BootstrapGUI] WARN org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView  - Unable to use JavaFX:
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Can't load library: /home/me/.ZAP/plugin/ZAP_2.6.0/lib/amd64/libglass.so
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:284)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:127)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:182)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:199)
	at org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView.isJavaFxAvailable(ExtensionHttpPanelBrowserView.java:92)
```
When I try and add the library to the path it says, I get the following error instead:

```
4576 [ZAP-BootstrapGUI] WARN org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView  - Unable to use JavaFX:
java.lang.RuntimeException: java.lang.NoSuchMethodError: notifyView
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:284)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:127)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:182)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:199)
	at org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView.isJavaFxAvailable(ExtensionHttpPanelBrowserView.java:92)
```

```
$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
I had to get the `libglass.so` library from another application which had them as when I tried `find` for it, it wasn't contained in any of the default JRE directories.

**Comment by thc202** [comment]
Do you have the openjfx package [1] installed? If not ,could you try installing it?

[1] https://packages.ubuntu.com/xenial/openjfx

**Comment by pr0letariat** [comment]
Ah! Such a simple fix I should've done. Thanks.

**Comment by thc202** [comment]
Thanks for letting us know!
