### ISSUE TITLE
JSON Input Vector fails if string has quoted chars

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#3895]
There seems to be a very fundamental issue with the JSON variant parser. The following HTTP post body causes an exception when an active scan is started with the following request (only POST parameter chosen):

	POST http://example.com/ HTTP/1.1
	Connection: keep-alive
	Content-Type: application/json
	Content-Length: 12
	Proxy-Connection: Keep-Alive
	Host: example.com
	
	{"foo":"\""}

ZAP stacktrace when a scanner is run on the request:

	3109792 [ZAP-ActiveScanner-0] WARN org.parosproxy.paros.core.scanner.VariantJSONQuery  - Failed to parse the request body: Object not ended with '}' or ']' at position 11
	java.lang.IllegalArgumentException: Object not ended with '}' or ']' at position 11
		at org.parosproxy.paros.core.scanner.VariantJSONQuery.parseObject(Unknown Source)
		at org.parosproxy.paros.core.scanner.VariantJSONQuery.parseContent(Unknown Source)
		at org.parosproxy.paros.core.scanner.VariantAbstractRPCQuery.setRequestContent(Unknown Source)
		at org.parosproxy.paros.core.scanner.VariantAbstractRPCQuery.setMessage(Unknown Source)
		at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(Unknown Source)
		at org.parosproxy.paros.core.scanner.AbstractPlugin.run(Unknown Source)
		at java.lang.Thread.run(Thread.java:745)

My versions:

	ZAP 2.6.0
	Active scanner release quality rules version 26
	Java 1.8.0_77

**Comment by juhakivekas** [comment]
The parser seems to be the issue:
https://github.com/zaproxy/zaproxy/blob/cc58c9e73327cb8f8bc51b6afc3965ff6ab6901a/src/org/parosproxy/paros/core/scanner/VariantJSONQuery.java#L126

**Comment by psiinon** [comment]
We actually include libs for proper json parsing - we should probably use those instead.

**Comment by thc202** [comment]
Yeah, we actually have an issue about that #3322. Should be merged into that one?

**Comment by kingthorin** [comment]
+1 for merging.

**Comment by thc202** [comment]
Merging into #3322.

**Comment by thc202** [comment]
Reopening, it's being handled separately from #3322.
