### ISSUE TITLE
Issues with Java 9

### ISSUE THREAD

**Issue by Emi1305** [zaproxy/zaproxy#3934]
I'm using the weekly update under Windows 10 with Java 9 and have found two issues (Probably related so I'm reporting them together, if not related I can report them separately)

1. Unable to open "Session properties":
It just does nothing and the following stack trace is shown:

```
120727 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.ExceptionInInitializerError
        at org.zaproxy.zap.extension.accessControl.view.ContextAccessControlPanel$AccessRuleNodeCellRenderer.getTreeCellRendererComponent(ContextAccessControlPanel.java:300)
        at org.jdesktop.swingx.JXTree$DelegatingRenderer.getTreeCellRendererComponent(JXTree.java:1269)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(Unknown Source)
        at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setModel(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setModel(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
        at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
        at java.desktop/javax.swing.JTree.setModel(Unknown Source)
        at org.jdesktop.swingx.JXTree.setModel(JXTree.java:1532)
        at org.jdesktop.swingx.JXTreeTable.setTreeTableModel(JXTreeTable.java:1238)
        at org.zaproxy.zap.extension.accessControl.view.ContextAccessControlPanel.initContextData(ContextAccessControlPanel.java:233)
        at org.parosproxy.paros.view.SessionDialog.initContextPanel(SessionDialog.java:125)
        at org.parosproxy.paros.view.SessionDialog.initParam(SessionDialog.java:111)
        at org.parosproxy.paros.view.View.showSessionDialog(View.java:689)
        at org.parosproxy.paros.view.View.showSessionDialog(View.java:657)
        at org.parosproxy.paros.control.MenuFileControl.properties(MenuFileControl.java:506)
        at org.zaproxy.zap.view.MainToolbarPanel$7.actionPerformed(MainToolbarPanel.java:357)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.desktop/javax.swing.ImageIcon.<init>(Unknown Source)
        at org.zaproxy.zap.extension.accessControl.widgets.SiteNodeIcons.<clinit>(SiteNodeIcons.java:27)
        ... 60 more
```

2. Unable to add sites to context 

Again it does nothing. Stacktrace:

```
662658 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.NoClassDefFoundError: Could not initialize class org.zaproxy.zap.extension.accessControl.widgets.SiteNodeIcons
        at org.zaproxy.zap.extension.accessControl.view.ContextAccessControlPanel$AccessRuleNodeCellRenderer.getTreeCellRendererComponent(ContextAccessControlPanel.java:300)
        at org.jdesktop.swingx.JXTree$DelegatingRenderer.getTreeCellRendererComponent(JXTree.java:1269)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(Unknown Source)
        at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(Unknown Source)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setModel(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setModel(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.fire(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
        at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
        at java.desktop/java.awt.Component.firePropertyChange(Unknown Source)
        at java.desktop/javax.swing.JTree.setModel(Unknown Source)
        at org.jdesktop.swingx.JXTree.setModel(JXTree.java:1532)
        at org.jdesktop.swingx.JXTreeTable.setTreeTableModel(JXTreeTable.java:1238)
        at org.zaproxy.zap.extension.accessControl.view.ContextAccessControlPanel$1.actionPerformed(ContextAccessControlPanel.java:180)
        at java.desktop/javax.swing.JComboBox.fireActionEvent(Unknown Source)
        at java.desktop/javax.swing.JComboBox.contentsChanged(Unknown Source)
        at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
        at org.zaproxy.zap.view.widgets.UsersListModel.setSelectedItemImpl(UsersListModel.java:100)
        at org.zaproxy.zap.view.widgets.UsersListModel.access$300(UsersListModel.java:31)
        at org.zaproxy.zap.view.widgets.UsersListModel$TableModelListenerImpl.selectFirstUser(UsersListModel.java:195)
        at org.zaproxy.zap.view.widgets.UsersListModel$TableModelListenerImpl.selectionFallback(UsersListModel.java:200)
        at org.zaproxy.zap.view.widgets.UsersListModel$TableModelListenerImpl.tableChanged(UsersListModel.java:178)
        at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
        at java.desktop/javax.swing.table.AbstractTableModel.fireTableDataChanged(Unknown Source)
        at org.zaproxy.zap.extension.users.UsersTableModel.setUsers(UsersTableModel.java:114)
        at org.zaproxy.zap.extension.users.ContextUsersPanel.initContextData(ContextUsersPanel.java:175)
        at org.parosproxy.paros.view.SessionDialog.initContextPanel(SessionDialog.java:125)
        at org.parosproxy.paros.view.SessionDialog.initParam(SessionDialog.java:111)
        at org.parosproxy.paros.view.View.showSessionDialog(View.java:689)
        at org.parosproxy.paros.view.View.showSessionDialog(View.java:661)
        at org.zaproxy.zap.view.popup.PopupMenuItemIncludeInContext.performHistoryReferenceActions(PopupMenuItemIncludeInContext.java:101)
        at org.zaproxy.zap.view.popup.PopupMenuItemHistoryReferenceContainer.performActions(PopupMenuItemHistoryReferenceContainer.java:230)
        at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer$PerformActionsActionListener.actionPerformed(PopupMenuItemHttpMessageContainer.java:587)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

Java version:

```
C:\>java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

Same issues are not found when using Java 8:

```
C:\>"C:\Program Files\Java\jre1.8.0_144\bin\java.exe" -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

If more information is needed to replicate the issue I can provide it

Thank you in advance

**Comment by thc202** [comment]
Thanks for reporting, this is caused by add-on Access Control Testing. Merging into #2602.

**Comment by thc202** [comment]
(And yes, both issues/exceptions have the same cause.)
