### ISSUE TITLE
Update JRuby library

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3944]
From zaproxy/zap-extensions#1021, update JRuby to latest version (this requires more changes than just update the library, per comments in https://github.com/zaproxy/zap-extensions/pull/1021#pullrequestreview-60103122).

Related to #2602, current version is failing with Java 9:
```
[ZAP-BootstrapGUI] ERROR org.parosproxy.paros.extension.ExtensionLoader  - 
java.lang.ExceptionInInitializerError
	at org.jruby.embed.internal.AbstractLocalContextProvider.<init>(AbstractLocalContextProvider.java:42)
	at org.jruby.embed.internal.SingletonLocalContextProvider.<init>(SingletonLocalContextProvider.java:88)
	at org.jruby.embed.ScriptingContainer.getProviderInstance(ScriptingContainer.java:246)
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:226)
	at org.jruby.embed.jsr223.JRubyEngineFactory.getScriptEngine(JRubyEngineFactory.java:170)
	at org.zaproxy.zap.extension.jruby.ExtensionJruby.hook(ExtensionJruby.java:79)
	at org.parosproxy.paros.extension.ExtensionLoader.hookAllExtension(Unknown Source)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(Unknown Source)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(Unknown Source)
	at org.parosproxy.paros.control.Control.init(Unknown Source)
	at org.parosproxy.paros.control.Control.initSingletonWithView(Unknown Source)
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(Unknown Source)
	at org.zaproxy.zap.GuiBootstrap.access$100(Unknown Source)
	at org.zaproxy.zap.GuiBootstrap$2.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.RuntimeException: unsupported Java version: 9
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1693)
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1398)
	... 15 more
```
Newer JRuby version appears to work fine with Java 9 (no errors at start up and script Traverse sites tree.rb runs with no errors).

**Comment by thc202** [comment]
This is a problem now that ZAP requires Java 11, which means the Ruby script engine can no longer be used.

**Comment by thc202** [comment]
The dependency was updated in zaproxy/zap-extensions#6797, the templates/scripts still need to be reviewed.

**Comment by kingthorin** [comment]
- **active**: Default template fails ❌:
```
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `getMetadata' for main:Objectjava.lang.ClassCastException: class org.jruby.gen.JRubyActiveScript_1318642287 cannot be cast to class org.zaproxy.zap.extension.scripts.scanrules.ActiveScript2 (org.jruby.gen.JRubyActiveScript_1318642287 is in unnamed module of loader org.jruby.util.ClassDefiningJRubyClassLoader @4538bb3b; org.zaproxy.zap.extension.scripts.scanrules.ActiveScript2 is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @78e09f10)
```
- **authentication**: Default template won't load ❌:

<img width="1148" height="268" alt="Image" src="https://github.com/user-attachments/assets/d2234a40-5988-4fc3-950d-05467f76b8c9" />

`2908264 [AWT-EventQueue-0] WARN  org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType - The script jrtauth does not properly implement the Authentication Script interface.`

- **httpsender**: Default template fails ❌:
```
java.lang.ClassCastException: class org.jruby.RubySymbol cannot be cast to class org.zaproxy.zap.extension.script.HttpSenderScript (org.jruby.RubySymbol is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @74614332; org.zaproxy.zap.extension.script.HttpSenderScript is in unnamed module of loader 'app')java.lang.ClassCastException: class org.jruby.RubySymbol cannot be cast to class org.zaproxy.zap.extension.script.HttpSenderScript (org.jruby.RubySymbol is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @74614332; org.zaproxy.zap.extension.script.HttpSenderScript is in unnamed module of loader 'app')
```
- **passive**: Default template works ✅
- **proxy**: Default template works ✅
- **standalone**: All 3 work (default is blank, but a simple print `puts` works) ✅
- **targeted**: Is invoked (if a print `puts` is used outside the method), however `invokeWith` doesn't seem to be invoked) ⚠️ [The template has a semi-colon on its `puts` statement, is that correct/necessary?] This came up before I exited ZAP but I don't know if it was trying the whole time or cause by trying to exit ZAP, or _____ 🤷‍♂️
```
java.lang.ClassCastException: class org.jruby.RubySymbol cannot be cast to class org.zaproxy.zap.extension.script.TargetedScript (org.jruby.RubySymbol is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @74614332; org.zaproxy.zap.extension.script.TargetedScript is in unnamed module of loader 'app')java.lang.ClassCastException: class org.jruby.RubySymbol cannot be cast to class org.zaproxy.zap.extension.script.TargetedScript (org.jruby.RubySymbol is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @74614332; org.zaproxy.zap.extension.script.TargetedScript is in unnamed module of loader 'app')java.lang.ClassCastException: class org.jruby.RubySymbol cannot be cast to class org.zaproxy.zap.extension.script.TargetedScript (org.jruby.RubySymbol is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @74614332; org.zaproxy.zap.extension.script.TargetedScript is in unnamed module of loader 'app')java.lang.ClassCastException: class org.jruby.RubySymbol cannot be cast to class org.zaproxy.zap.extension.script.TargetedScript (org.jruby.RubySymbol is in unnamed module of loader org.zaproxy.zap.control.AddOnClassLoader @74614332; org.zaproxy.zap.extension.script.TargetedScript is in unnamed module of loader 'app')org.jruby.exceptions.NameError: (NameError) undefined local variable or method `msg' for main:Objectorg.jruby.exceptions.NameError: (NameError) undefined local variable or method `msg' for main:Objectorg.jruby.exceptions.NameError: (NameError) undefined local variable or method `msg' for main:Object
```

- **encode/decode**: The template suggested here: https://github.com/zaproxy/zaproxy/issues/5996#issuecomment-1685113614 doesn't work ❌:

<img width="1133" height="439" alt="Image" src="https://github.com/user-attachments/assets/7f93caaf-cd8a-4681-a284-c5900124a920" />

`(TypeError) cannot convert instance of class org.jruby.RubyObject to interface org.zaproxy.addon.encoder.processors.script.EncodeDecodeScript`
