### ISSUE TITLE
GUI hang when installing/uninstalling scripting add-ons

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3945]
Steps to reproduce the issue:
1. Run ZAP (2.6.0) with Script Console and JRuby add-ons installed;
2. Create a Ruby Stand Alone script and ensure it's selected in the Scripts tree;
3. Uninstall the JRuby add-on, note that the GUI hanged (i.e. no repaints).

Remarks:
The issue might not happen always but happens often, it also happens when uninstalling/updating the scripting add-on.

Following thread dumps (just offending threads).
Install:
```
"Thread-12" #46 prio=6 os_prio=0 tid=0x00007fef8031b000 nid=0x3a0e waiting for monitor entry [0x00007fef98194000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.awt.Component.enable(Component.java:1489)
	- waiting to lock <0x000000008385da60> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.enable(JComponent.java:3623)
	at java.awt.Component.enable(Component.java:1513)
	at java.awt.Component.setEnabled(Component.java:1478)
	at javax.swing.JComponent.setEnabled(JComponent.java:2680)
	at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2091)
	at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
	at javax.swing.AbstractAction.setEnabledFromAction(AbstractAction.java:102)
	at javax.swing.AbstractButton.actionPropertyChanged(AbstractButton.java:1218)
	at javax.swing.JMenuItem.actionPropertyChanged(JMenuItem.java:411)
	at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1364)
	at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1352)
	at javax.swing.ActionPropertyChangeListener.propertyChange(ActionPropertyChangeListener.java:88)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at javax.swing.AbstractAction.firePropertyChange(AbstractAction.java:276)
	at javax.swing.AbstractAction.setEnabled(AbstractAction.java:236)
	at org.fife.ui.rtextarea.RUndoManager.updateActions(RUndoManager.java:195)
	at org.fife.ui.rtextarea.RUndoManager.undoableEditHappened(RUndoManager.java:150)
	at javax.swing.text.AbstractDocument.fireUndoableEditUpdate(AbstractDocument.java:286)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:752)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.JTextArea.append(JTextArea.java:477)
	at org.zaproxy.zap.extension.scripts.CommandPanel.appendToCommandScript(CommandPanel.java:128)
	at org.zaproxy.zap.extension.scripts.ConsolePanel.updateCommandPanelState(ConsolePanel.java:337)
	at org.zaproxy.zap.extension.scripts.ConsolePanel.setScript(ConsolePanel.java:296)
	at org.zaproxy.zap.extension.scripts.ExtensionScriptsUI.displayScript(ExtensionScriptsUI.java:313)
	at org.zaproxy.zap.extension.scripts.ExtensionScriptsUI.engineAdded(ExtensionScriptsUI.java:671)
	at org.zaproxy.zap.extension.script.ExtensionScript.registerScriptEngineWrapper(Unknown Source)
	at org.zaproxy.zap.extension.jruby.ExtensionJruby.hook(ExtensionJruby.java:81)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensionImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensions(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.install(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.addAddon(Unknown Source)
	- locked <0x00000000855671d8> (a org.zaproxy.zap.control.AddOnLoader)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(Unknown Source)

"AWT-EventQueue-0" #11 prio=6 os_prio=0 tid=0x00007fefd871e000 nid=0x39ed in Object.wait() [0x00007fef9b26a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at javax.swing.text.AbstractDocument.readLock(AbstractDocument.java:1387)
	- locked <0x0000000085b20e90> (a org.fife.ui.rsyntaxtextarea.RSyntaxDocument)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:908)
	at javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:120)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JTextArea.getPreferredSize(JTextArea.java:618)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	- locked <0x000000008385da60> (a java.awt.Component$AWTTreeLock)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Uninstall:
```
"SwingWorker-pool-1-thread-1" #35 daemon prio=5 os_prio=0 tid=0x00007f6af425d800 nid=0x3aac waiting for monitor entry [0x00007f6b0e970000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.awt.Component.enable(Component.java:1489)
	- waiting to lock <0x00000000839a1090> (a java.awt.Component$AWTTreeLock)
	at javax.swing.JComponent.enable(JComponent.java:3623)
	at java.awt.Component.enable(Component.java:1513)
	at java.awt.Component.setEnabled(Component.java:1478)
	at javax.swing.JComponent.setEnabled(JComponent.java:2680)
	at javax.swing.AbstractButton.setEnabled(AbstractButton.java:2091)
	at javax.swing.JMenuItem.setEnabled(JMenuItem.java:312)
	at javax.swing.AbstractAction.setEnabledFromAction(AbstractAction.java:102)
	at javax.swing.AbstractButton.actionPropertyChanged(AbstractButton.java:1218)
	at javax.swing.JMenuItem.actionPropertyChanged(JMenuItem.java:411)
	at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1364)
	at javax.swing.AbstractButton$ButtonActionPropertyChangeListener.actionPropertyChanged(AbstractButton.java:1352)
	at javax.swing.ActionPropertyChangeListener.propertyChange(ActionPropertyChangeListener.java:88)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at javax.swing.AbstractAction.firePropertyChange(AbstractAction.java:276)
	at javax.swing.AbstractAction.setEnabled(AbstractAction.java:236)
	at org.fife.ui.rtextarea.RUndoManager.updateActions(RUndoManager.java:195)
	at org.fife.ui.rtextarea.RUndoManager.undoableEditHappened(RUndoManager.java:150)
	at javax.swing.text.AbstractDocument.fireUndoableEditUpdate(AbstractDocument.java:286)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:752)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at javax.swing.JTextArea.append(JTextArea.java:477)
	at org.zaproxy.zap.extension.scripts.CommandPanel.appendToCommandScript(CommandPanel.java:128)
	at org.zaproxy.zap.extension.scripts.ConsolePanel.clearScript(ConsolePanel.java:285)
	at org.zaproxy.zap.extension.scripts.ExtensionScriptsUI.displayType(ExtensionScriptsUI.java:393)
	at org.zaproxy.zap.extension.scripts.ExtensionScriptsUI.engineRemoved(ExtensionScriptsUI.java:686)
	at org.zaproxy.zap.extension.script.ExtensionScript.removeScriptEngineWrapper(Unknown Source)
	at org.zaproxy.zap.extension.jruby.ExtensionJruby.unload(ExtensionJruby.java:134)
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtension(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtensions(Unknown Source)
	at org.zaproxy.zap.control.AddOnInstaller.uninstall(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.removeAddOnImpl(Unknown Source)
	at org.zaproxy.zap.control.AddOnLoader.removeAddOn(Unknown Source)
	- locked <0x0000000084d876d0> (a org.zaproxy.zap.control.AddOnLoader)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstall(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$1100(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$10.doInBackground(Unknown Source)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$10.doInBackground(Unknown Source)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


"AWT-EventQueue-0" #11 prio=6 os_prio=0 tid=0x00007f6b4c78e800 nid=0x3a97 in Object.wait() [0x00007f6b0f571000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at javax.swing.text.AbstractDocument.readLock(AbstractDocument.java:1387)
	- locked <0x0000000085617d00> (a org.fife.ui.rsyntaxtextarea.RSyntaxDocument)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:908)
	at javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:120)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JTextArea.getPreferredSize(JTextArea.java:618)
	at javax.swing.text.JTextComponent.getScrollableTracksViewportWidth(JTextComponent.java:2022)
	at javax.swing.JTextArea.getScrollableTracksViewportWidth(JTextArea.java:682)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:898)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	- locked <0x00000000839a1090> (a java.awt.Component$AWTTreeLock)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Add-on:
Script Console version 18 (older versions should cause the issue too).

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1076.
