### ISSUE TITLE
OpenAPI Extension: Action Returns Unexpected Response?

### ISSUE THREAD

**Issue by kvn-s** [zaproxy/zaproxy#3951]
Steps to reproduce:
1. Configure ZAP UI to be accessible as a local proxy.
2. Browse to `http://localhost/UI/openapi/action/importUrl/` and provide a valid URL.
3. Open the network debugger of your browser's development tools.
4. Press "importUrl".
5. Now `{"importUrl":[]}` is the response. Instead something with "OK" is expected as all the other options do it.
Also in case of an import error I would expect something different than a 200 status (but actually there is no distinction).

Thank you for looking into it. :)

**Comment by mr4p** [comment]
I tried to reproduce it:

- Started ZAP with org.zaproxy.zap.ZAP#main
- Went to http://127.0.0.1:8090/UI/openapi/action/importUrl/
- Got response:
"No implementor"

```
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:356)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:745)
```

Can you help

**Comment by kingthorin** [comment]
Do u have the openapi addon installed?

**Comment by thc202** [comment]
@kvn-s it returns an array because while the file/URL might have been imported (OK) it might be with errors/warnings when parsing the definition. I guess it could return OK if there are no errors/warnings... :)

> Also in case of an import error I would expect something different than a 200 status (but actually there is no distinction).

You mean the parsing errors/warnings? Or, wrong URL/file?

**Comment by kvn-s** [comment]
@thc202 Yes, I think "OK" on success and 400 plus error message on import failure (parsing, file not found etc.) would be perfect.

**Comment by kingthorin** [comment]
I think I’m going to break this into two tasks/PRs. One to simply respond okay when there are zero import issues. Another to allow setting response code of API responses in core.

**Comment by secf00tprint** [comment]
I installed the Addon:

![image](https://user-images.githubusercontent.com/1818452/195999021-5823e3bb-1478-4c8b-998d-c6a422ac2b11.png)

Tried to open the url but got a connection error:

![image](https://user-images.githubusercontent.com/1818452/195999049-26b5a96f-c7a6-426f-b807-ccfa626ea45d.png)

**Comment by kingthorin** [comment]
The Import/Export add-on is different than the OpenAPI add-on.

**Comment by thc202** [comment]
You are also not accessing the ZAP API but a local server. More information in: https://www.zaproxy.org/docs/api/

**Comment by secf00tprint** [comment]
Ah thx this helped:

Perhaps for others to get started with this topic:

I had the correct addon installed but was the wrong picture (I mixed it up). This is installed:

![image](https://user-images.githubusercontent.com/1818452/196221636-a5a19fd0-dd7f-45cd-93be-5c65601cf40b.png)

ZAP API is also accessible locally:

![image](https://user-images.githubusercontent.com/1818452/196222420-00add9ce-d196-4b7a-8574-056dc83a26e8.png)

Then I can reach it via:

http://localhost:8080/UI/openapi/action/importUrl/

(It's by default configured for this in `Options->API`

![image](https://user-images.githubusercontent.com/1818452/196222762-cbb097b2-0d3d-4635-a04a-e2372326278f.png)


I found an openapi specification at the petstore demo from swagger

[https://petstore.swagger.io/v2/swagger.json](https://petstore.swagger.io/v2/swagger.json
)

Before clicking `importUrl` and looking into `Network` in the Developer-Tools I copied my 
apiKey from `Options->API` after `*apikey` and put in [https://petstore.swagger.io/v2/swagger.json](https://petstore.swagger.io/v2/swagger.json
) after `*url`.

Result after clicking at `importUrl` like explained:

![image](https://user-images.githubusercontent.com/1818452/196225200-110ffca0-d0c9-4602-9c11-25a800d83074.png)
