### ISSUE TITLE
Database too small to handle large login request bodies

### ISSUE THREAD

**Issue by CookieAndPizza** [zaproxy/zaproxy#3955]
I was working on a project when I noticed my POST request could not be set as "Form based Auth login request". Every time I pressed the button the following exception would be thrown:

`org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: data exception: string data, right truncation;  table: CONTEXT_DATA column: DATA
	at org.parosproxy.paros.db.paros.ParosTableContext.insert(ParosTableContext.java:119)
	at org.parosproxy.paros.db.paros.ParosTableContext.setData(ParosTableContext.java:245)
	at org.parosproxy.paros.model.Session.setContextData(Session.java:1120)
	at org.parosproxy.paros.model.Session.setContextData(Session.java:1116)
	at org.zaproxy.zap.authentication.FormBasedAuthenticationMethodType.persistMethodToSession(FormBasedAuthenticationMethodType.java:902)
	at org.zaproxy.zap.extension.authentication.ExtensionAuthentication.persistContextData(ExtensionAuthentication.java:296)
	at org.parosproxy.paros.model.Model.saveContext(Model.java:505)
	at org.parosproxy.paros.model.Session.saveContext(Session.java:1166)
	at org.parosproxy.paros.model.Session.saveAllContexts(Session.java:1179)
	at org.parosproxy.paros.view.SessionDialog.saveParam(SessionDialog.java:132)
	at org.parosproxy.paros.view.AbstractParamDialog$1.actionPerformed(AbstractParamDialog.java:186)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:139)
	at org.parosproxy.paros.view.SessionDialog.setVisible(SessionDialog.java:137)
	at org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:361)
	at org.parosproxy.paros.view.View.showSessionDialog(View.java:695)
	at org.parosproxy.paros.view.View.showSessionDialog(View.java:661)
	at org.zaproxy.zap.authentication.FormBasedAuthenticationMethodType$1$1.performAction(FormBasedAuthenticationMethodType.java:815)
	at org.zaproxy.zap.view.popup.PopupMenuItemSiteNodeContainer.performAction(PopupMenuItemSiteNodeContainer.java:120)
	at org.zaproxy.zap.view.popup.PopupMenuItemHistoryReferenceContainer.performHistoryReferenceActions(PopupMenuItemHistoryReferenceContainer.java:268)
	at org.zaproxy.zap.view.popup.PopupMenuItemHistoryReferenceContainer.performActions(PopupMenuItemHistoryReferenceContainer.java:230)
	at org.zaproxy.zap.view.popup.PopupMenuItemHttpMessageContainer$PerformActionsActionListener.actionPerformed(PopupMenuItemHttpMessageContainer.java:587)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.sql.SQLDataException: data exception: string data, right truncation;  table: CONTEXT_DATA column: DATA
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableContext.insert(ParosTableContext.java:110)
	... 101 more
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation;  table: CONTEXT_DATA column: DATA
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source)
	at org.hsqldb.Table.generateAndCheckData(Unknown Source)
	at org.hsqldb.Table.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 104 more
Caused by: org.hsqldb.HsqlException: data exception: string data, right truncation
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.types.CharacterType.convertToTypeLimits(Unknown Source)
	... 112 more`

This means the databaserow 'data' is too small to handle the, in my case, request body. Looking into the code I saw the following:

`			if (!DbUtils.hasTable(conn, TABLE_NAME)) {
			    // Need to create the table
			    DbUtils.executeAndClose(
			            conn.prepareStatement("CREATE cached TABLE CONTEXT_DATA (dataid bigint generated by default as identity (start with 1), contextId int not null, type int not null, data varchar(8192) default '')"));
			}`
(Found in 'ParosTableContext.java')

My request body was at least 22000 characters long, hence this problem. I took a look into the database of the current context and noticed that in the "hisotry" tabel the values request body and response body have no limit. 

Therefore I raise this issue (or ask this question), is there a reason the request body in the "CONTEXT_DATA" table is so small? 

Notes: 

- Changing the value in the query shown above has no impact on the actual database (do not know why). If you'd like to change the actual database value the 'zapdb.script' file should be changed. 
- I run the OWASP Zap dev build

**Comment by thc202** [comment]
There was no specific reason to have that limit. The referenced `ParosTableContext` code is only executed for older sessions (that predate the context functionality).
