### ISSUE TITLE
Invoked application fails to start with ZAP 2.6 in macOS

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#3960]
Issue reported in OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/8xw8VDLbO5U/discussion

The command is shown in the Output tab but no output from the application, a previous version of the add-on works fine.

Add-on:
Invoke Applications version 6.

**Comment by thc202** [comment]
The application might not be starting at all (per zaproxy/zap-extensions#1101).

**Comment by thc202** [comment]
Updated the title to reflect latest information received in the mailing list. The issue only happens with 2.6.0, following stack trace:
```
2017-10-19 16:58:07,611 WARN  InvokeAppWorker - Failed to start the process: Cannot run program "/path/to/app" (in directory "/path/to"): error=0, spawn failed
java.io.IOException: Cannot run program  "/path/to/app" (in directory  "/path/to"): error=0, spawn failed
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at org.zaproxy.zap.extension.invoke.InvokeAppWorker.doInBackground(InvokeAppWorker.java:118)
at org.zaproxy.zap.extension.invoke.InvokeAppWorker.doInBackground(InvokeAppWorker.java:39)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=0, spawn failed
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
at java.lang.ProcessImpl.start(ProcessImpl.java:134)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 8 more
```
most likely related to JRE bundled in ZAP 2.6.0.

**Comment by thc202** [comment]
From latest info, this is related to macOS installer, the Cross Platform Package works fine.

**Comment by thc202** [comment]
Merging into #3976.
