### ISSUE TITLE
Sending to the Callback Endpoint while proxying through ZAP logs an error

### ISSUE THREAD

**Issue by denniskniep** [zaproxy/zaproxy#4013]
If you are proxying through ZAP and send something to the Callback Endpoint on HTTP there is the follwing Exception:

```
ZAP Error [org.parosproxy.paros.network.HttpMalformedHeaderException]: Failed to find pattern: (HTTP/\d+\.\d+) +(\d{3}) *([^\x00-\x1f\r\n]*)

Stack Trace:
org.parosproxy.paros.network.HttpMalformedHeaderException: Failed to find pattern: (HTTP/\d+\.\d+) +(\d{3}) *([^\x00-\x1f\r\n]*)
	at org.parosproxy.paros.network.HttpResponseHeader.parse(HttpResponseHeader.java:119)
	at org.parosproxy.paros.network.HttpResponseHeader.setMessage(HttpResponseHeader.java:94)
	at org.parosproxy.paros.network.HttpHeader.<init>(HttpHeader.java:146)
	at org.parosproxy.paros.network.HttpResponseHeader.<init>(HttpResponseHeader.java:78)
	at org.parosproxy.paros.network.HttpMethodHelper.getHttpResponseHeader(HttpMethodHelper.java:282)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:514)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:479)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:394)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:351)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:509)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:748)
```

If you use HTTPS with an IpAddress there is additionally a "ERR_CERT_COMMON_NAME_INVALID" problem before the HttpMalformedHeaderException.

**Comment by thc202** [comment]
The exception is normal/expected (the callback does not return any response on purpose), does that happen in a normal use case? (Is the target application proxying through ZAP? or was a "manual" request?)

**Comment by denniskniep** [comment]
From IRC: 

@denniskniep says
> I think the Problem in #4013 is that the callback endpoint returns nothing. And the Proxy has tries to parse this response header with StatusCode 0 . But the regex assumes 3 digits.
Browser <--> Proxy through ZAP <--> ZAP Callback Endpoint

> On the one hand we could set the response to 200 in the Callback Endpoint or on the other hand we could accept "no response" in the proxy.

@thc202 says

> initial reason was to not allow leak any data (and that's why it's cloned to the callback handlers)
> I guess we could return the minimum HTTP/1.1 200 OK or something

**Comment by denniskniep** [comment]
The SSL-Error is not only while invoking the callbacks endpoint. Created a separate issue #4016.
