### ISSUE TITLE
Websocket related exception leads to UI freeze

### ISSUE THREAD

**Issue by juhakivekas** [zaproxy/zaproxy#4044]
When testing an application that opened Websockets, the history tab and all other tabs in the pane would freeze after some exceptions that are caused by the opened Websocket connections. These are the exceptions that happen before the freeze in my app under test. The second stacktrace repeats when i keep zap and the tested application open.
```
10835 [ZAP-ProxyThread-1] ERROR org.parosproxy.paros.core.proxy.ProxyThread  - An error occurred while notifying listener:
java.lang.ArrayIndexOutOfBoundsException
	at java.util.ArrayList.remove(ArrayList.java:499)
	at javax.swing.JTabbedPane.removeTabAt(JTabbedPane.java:964)
	at javax.swing.JTabbedPane.remove(JTabbedPane.java:1026)
	at java.awt.Container.addImpl(Container.java:1098)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:724)
	at org.zaproxy.zap.view.TabbedPanel2.addTab(TabbedPanel2.java:261)
	at org.zaproxy.zap.view.TabbedPanel2.setVisible(TabbedPanel2.java:206)
	at org.parosproxy.paros.extension.AbstractPanel.setTabFocus(AbstractPanel.java:82)
	at org.zaproxy.zap.extension.websocket.ExtensionWebSocket.onHandshakeResponse(ExtensionWebSocket.java:540)
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyPersistentConnectionListener(ProxyThread.java:747)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:562)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:745)
10835 [ZAP-ProxyThread-2] ERROR org.parosproxy.paros.core.proxy.ProxyThread  - An error occurred while notifying listener:
java.lang.ArrayIndexOutOfBoundsException
13388 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.ArrayIndexOutOfBoundsException
15518 [ZAP-ProxyThread-14] ERROR org.parosproxy.paros.core.proxy.ProxyThread  - An error occurred while notifying listener:
java.lang.ArrayIndexOutOfBoundsException
	at java.util.ArrayList.remove(ArrayList.java:499)
	at javax.swing.JTabbedPane.removeTabAt(JTabbedPane.java:964)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:710)
	at org.zaproxy.zap.view.TabbedPanel2.addTab(TabbedPanel2.java:261)
	at org.zaproxy.zap.view.TabbedPanel2.setVisible(TabbedPanel2.java:206)
	at org.parosproxy.paros.extension.AbstractPanel.setTabFocus(AbstractPanel.java:82)
	at org.zaproxy.zap.extension.websocket.ExtensionWebSocket.onHandshakeResponse(ExtensionWebSocket.java:540)
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyPersistentConnectionListener(ProxyThread.java:747)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:562)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:745)
```

Simply opening a website which uses Websockets already causes a warning which might be related to what is happening here. The websocket.org site will cause this exception:

```
62908 [ZAP-WS-Listener (local) 'de14.zopim.com:443 (#1)'] WARN org.zaproxy.zap.extension.websocket.WebSocketProxy  - Invalid range
java.lang.IndexOutOfBoundsException: Invalid range
	at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:864)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsInserted(DefaultSortController.java:404)
	at javax.swing.JTable.notifySorter(JTable.java:4270)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4118)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.fireMessageArrived(WebSocketMessagesViewModel.java:382)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketPanel.onMessageFrame(WebSocketPanel.java:455)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:668)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:561)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by juhakivekas** [comment]
I updated to Java 1.8_152, and Websockets broke down even further. No more exceptions or stacktraces, but websocket.org seems to fall bak on http long-polling, and the ReactNative app I'm testing fails to switch protocols.

This looks like falling back to long polling:
```
531904 [ZAP-ProxyThread-166] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827000472 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
552728 [ZAP-ProxyThread-168] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827021267 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
575162 [ZAP-ProxyThread-169] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827043733 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
605368 [ZAP-ProxyThread-175] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827073864 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
628339 [ZAP-ProxyThread-177] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827096899 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
651489 [ZAP-ProxyThread-178] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827119994 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
680585 [ZAP-ProxyThread-184] WARN org.parosproxy.paros.core.proxy.ProxyThread  - Failed to read https://ie14.zopim.com/s/W/xdds/XIjpxyDh7qbbFQKI/p/1510827149153 within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
```
The history seems to show that the ReactNative (Android) app cannot connect to the npm server with websockets and just retries forever.

Method |URL|Code|Reason|Size Resp.Body 
-- | -- | -- | -- | --
GET | http://localhost:8081/message?device=SM-G920F%20-%207.0%20-%20API%2024&app=com.xxx&clientid=DevSupportManagerImpl | 101 | Switching Protocols | 0
GET | http://localhost:8081/inspector/device?name=SM-G920F%20-%207.0%20-%20API%2024 | 101 | Switching Protocols | 0
GET | http://localhost:8081/message?device=SM-G920F%20-%207.0%20-%20API%2024&app=com.xxx&clientid=DevSupportManagerImpl | 101 | Switching Protocols | 0
GET | http://localhost:8081/inspector/device?name=SM-G920F%20-%207.0%20-%20API%2024 | 101 | Switching Protocols | 0
GET | http://localhost:8081/message?device=SM-G920F%20-%207.0%20-%20API%2024&app=com.xxx&clientid=DevSupportManagerImpl | 101 | Switching Protocols | 0
GET | http://localhost:8081/inspector/device?name=SM-G920F%20-%207.0%20-%20API%2024 | 101 | Switching Protocols | 0
GET | http://localhost:8081/message?device=SM-G920F%20-%207.0%20-%20API%2024&app=com.xxx&clientid=DevSupportManagerImpl | 101 | Switching Protocols | 0

The response sizes show 0bytes, even if the response is not empty:

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: ZiU5JMlBnBe+DTmK8CvPY53PBuU=
```

**Comment by thc202** [comment]
Regarding the response size, that column is showing the size of the body not the header (it's possible to show the column for the header though).

Have you tried increasing the connection timeout? Are you using an outgoing proxy?

**Comment by juhakivekas** [comment]
Yeah I noticed i had the size wrong -.- The sizes of the headers seems alright.
I'm not using an outgoing proxy, and the timeouts were only happening with alt-proxies, maybe websockets don't attach to those yet? Now when using the primary proxy both web and ReactNative fail with the same exception:

```
25793 [ZAP-WS-Listener (local) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - forward message#1
25793 [ZAP-WS-Listener (local) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - forward frame
25795 [ZAP-WS-Listener (remote) 'localhost:8081 (#2)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxy  - Process WebSocket frame: 8 (CLOSE)
25795 [ZAP-WS-Listener (remote) 'localhost:8081 (#2)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - length of current frame payload is: 16; first two bytes: 10001000 00010000
25795 [ZAP-WS-Listener (remote) 'localhost:8081 (#2)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - close code is: 1000
25795 [ZAP-WS-Listener (remote) 'localhost:8081 (#2)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - got control-payload: 1000End of session
25796 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxy  - Process WebSocket frame: 8 (CLOSE)
25796 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - length of current frame payload is: 16; first two bytes: 10001000 00010000
25796 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - close code is: 1000
25796 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - got control-payload: 1000End of session
25797 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.db.TableWebSocket  - insert message: #1.2
25799 [ZAP-WS-Listener (remote) 'localhost:8081 (#2)'] DEBUG org.zaproxy.zap.extension.websocket.db.TableWebSocket  - insert message: #2.2
25801 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - forward message#2
25801 [ZAP-WS-Listener (remote) 'localhost:8081 (#1)'] DEBUG org.zaproxy.zap.extension.websocket.WebSocketProxyV13  - forward frame
25801 [ZAP-WS-Listener (remote) 'localhost:8081 (#2)'] WARN org.zaproxy.zap.extension.websocket.WebSocketProxy  - Invalid range
java.lang.IndexOutOfBoundsException: Invalid range
	at javax.swing.DefaultRowSorter.rowsInserted(DefaultRowSorter.java:864)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsInserted(DefaultSortController.java:404)
	at javax.swing.JTable.notifySorter(JTable.java:4270)
	at javax.swing.JTable.sortedTableChanged(JTable.java:4118)
	at javax.swing.JTable.tableChanged(JTable.java:4395)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(AbstractTableModel.java:231)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.fireMessageArrived(WebSocketMessagesViewModel.java:382)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketPanel.onMessageFrame(WebSocketPanel.java:455)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:668)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:561)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
