### ISSUE TITLE
new version is sometimes unresponsive under certain tasks

### ISSUE THREAD

**Issue by ReK2Fernandez** [zaproxy/zaproxy#4106]
Since when?
- Since I updated to  2.7.0
When?
- Dirbusting or fuzzing

When dirbustin with rockyou.txt or john.txt etc it becomes unresponsive..
sometimes doing heavy taks also becomes unresponsive
rarely had this issues before...now almost all the time if not all the time since I updated less than 24 hours a go but already go hit like 4-6 times.

**Comment by kingthorin** [comment]
What operating system?
What version of Java?

**Comment by ReK2Fernandez** [comment]
- Linux (BlackArch not on a VM, I use it as my main OS)
- Java

> [ blackarch SecLists ]$ java --version
> openjdk 9
> OpenJDK Runtime Environment (build 9+181)
> OpenJDK 64-Bit Server VM (build 9+181, mixed mode)

**Comment by thc202** [comment]
Do you have more details when that happens? Does that happen just after starting the fuzzer or after a while? Any errors in the log?

**Comment by thc202** [comment]
Could you also obtain some thread dumps when that happens? (`kill -3 <zap-pid>`)

**Comment by ReK2Fernandez** [comment]
@thc202 after like 30 secs to a minute..  I killed the app and is 2am here so about to head to bed but tomorrow if it happens again I will get this info for you. but you could prob replicate with rockyou.txt get it from https://github.com/danielmiessler/SecLists/tree/master/Passwords is the tar.gz file one. cheers.

**Comment by thc202** [comment]
Thanks, will try that.

**Comment by thc202** [comment]
I'm not able to reproduce that (probably not doing the same), how many payloads are you using? Is the fuzzer running along with other tools (e.g. spider, scanner, dir buster)?

**Comment by CreativeWolf** [comment]
Same issue here - It's unresponsive

Since When:
After 2.7.0 upgrade - Ran a scan, persisted session and tried to close ZAP
When:
Shutting down ZAP
OS: 
Linux 4.10.0-40-generic #44~16.04.1-Ubuntu
Java Version? openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Thread Dump:

java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f6824029800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:166)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
	at sun.jvm.hotspot.runtime.DeadlockDetector.createThreadTable(DeadlockDetector.java:149)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:56)
	at sun.jvm.hotspot.runtime.DeadlockDetector.print(DeadlockDetector.java:39)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:62)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f6824029800
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)
	... 17 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.tools.jstack.JStack.runJStackTool(JStack.java:140)
	at sun.tools.jstack.JStack.main(JStack.java:106)
Caused by: java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f6824029800 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:166)
	at sun.jvm.hotspot.runtime.Threads.first(Threads.java:150)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:75)
	at sun.jvm.hotspot.tools.StackTrace.run(StackTrace.java:45)
	at sun.jvm.hotspot.tools.JStack.run(JStack.java:66)
	at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
	at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
	at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
	at sun.jvm.hotspot.tools.JStack.main(JStack.java:92)
	... 6 more
Caused by: sun.jvm.hotspot.types.WrongTypeException: No suitable match for type of address 0x00007f6824029800
	at sun.jvm.hotspot.runtime.InstanceConstructor.newWrongTypeException(InstanceConstructor.java:62)
	at sun.jvm.hotspot.runtime.VirtualConstructor.instantiateWrapperFor(VirtualConstructor.java:80)
	at sun.jvm.hotspot.runtime.Threads.createJavaThreadWrapper(Threads.java:162)

**Comment by thc202** [comment]
@CreativeWolf how much time did it take to persist the session? When shutting down was it showing the dialogue "Shutting down server and database..."? Were the dialogues/windows painted?

It was not able to obtain the thread dump :/

**Comment by CreativeWolf** [comment]
@thc202 Took more than 15 minutes (didn't measure but definitely more than 15 minutes) to persist the session. Yes, the dialogue box with "Shutting down server and database" was visible. No the window / dialogue box wasn't painted but extremely sluggish when minimized and tried to open back.

**Comment by thc202** [comment]
OK, that seems to be other issue (and should be present in 2.6.0 and older), I'll check that (I suspect it's related to deletion of temporary messages).

**Comment by RickTorresJr** [comment]
Just had the same behavior when running the Fuzzer with rockyou.txt . The Fuzzer never kicks off.
OWASP ZAP version 2.7.0
Java Version 8 Update 161 (build 1.8.0_161-b12)
OS: Windows 7 Service Pack 1

**Comment by RickTorresJr** [comment]
I used the rockyou included in Kali (139MB). I used the default memory allocation included in the Windows version. How can I look this value up? @kingthorin

**Comment by kingthorin** [comment]
I was kind of wondering if you’d checked task manager or whatever at the time. However, knowing the source of the file and that defaults were used brings me closer to being able to recreate.

**Comment by thc202** [comment]
@RickTorresJr was there any error in the log? That seems to be another issue.

**Comment by kingthorin** [comment]
Closing, it’s been a year or more with no further feedback from those who mentioned the issue)s).
