### ISSUE TITLE
[owasp/zap2docker-weekly] zap-baseline.py script always fail with the following error:

### ISSUE THREAD

**Issue by bravoman** [zaproxy/zaproxy#4144]
I seem to get this error when running it in it's simplest form:  
`docker run -t owasp/zap2docker-weekly zap-baseline.py -t https://some.site.to.test`

Gives me:
```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('(' (code 40)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: /tmp/openapi6066722609839388415.defn; line: 1, column: 2]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:437)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2363)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:65)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:93)
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:68)
        at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:54)
        at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:397)
        at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:259)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ERROR <type 'exceptions.TypeError'>
2017-12-12 10:39:28,829 Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 328, in main
    num_urls = len(zap.core.urls)
TypeError: object of type 'instancemethod' has no len()
```

**Comment by kingthorin** [comment]
Which docker image are you using?

**Comment by thc202** [comment]
The first exception (which does not cause any harm) is related to #3644. The Python error should be fixed in the latest weekly release (Image ID a8dbbe5390bb).

**Comment by bravoman** [comment]
Ok, thanx!

**Comment by bravoman** [comment]
I guess I should update my weekly image more frequently ;) Sorry for bothering you with this.

**Comment by kingthorin** [comment]
No worries, give it a whirl and let us know.

**Comment by bravoman** [comment]
My latest pull of the image works without issues as you said. Thanx!
