### ISSUE TITLE
Stacktraces java.net.UnknownHostException seen over the wire

### ISSUE THREAD

**Issue by fhauser84** [zaproxy/zaproxy#4188]
Hi guys,

first of all awesome project! I try to upgrade my skills for the topic "zap and sdlc" (jenkins integration etc.). I want to recommend your solution to my clients such that they integrate zap into their infrastructure as a baseline security component.

During a fast security investigation with your proxy, I simply did some netcat connections and I've seen several stacktraces "over the wire". So usually we talk about information disclosure issues etc. when it comes to assessments and this happens, right? Therefore, you maybe should fix this also. :-)

If a client would see these stracktraces in their network monitoring systems and these stacktraces originate from zap as a security component, this could cause trouble...

netcat to proxy: nc -nv MYIP 8080

```
GET http://null/ HTTP/1.1



HTTP/1.1 502 Bad Gateway
Content-Type: text/plain; charset=UTF-8
Content-Length: 1909

ZAP Error [java.net.UnknownHostException]: null

Stack Trace:
java.net.UnknownHostException: null
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:333)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:564)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:523)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:501)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:405)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:362)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:509)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:748)
```

Greetings
and thanks for your amazing work

**Comment by kingthorin** [comment]
Could you elaborate on where your "server" was, what the "client" was, where ZAP was in relation to the two, and where you did the network capture?

**Comment by psiinon** [comment]
I agree that we could display a nicer message, but I'm afraid I cant get too excited about the security implications. I'd expect most people to use ZAP locally, in which case they would know they are using ZAP and which version they are using. However if you can suggest how this might be more serious then I might reconsider ;)

**Comment by fhauser84** [comment]
Hi both of you,

well sorry for some missing details. I wanted to be sure that this is not an old issue or discussion first even though I didn't find anything via search.

Here are the missing facts:

- I downloaded the 2.7.0 release as zip file from github.
- I started ZAP via the zap.sh script in my bash.
- ZAP is running on x64 machine with Ubuntu 16.04.3 LTS.
- ZAP config was adjusted to listen on local IP address 192.168.0.13 such that all machines in the same network can connect to it.
- Another linux machine was used to make a direct TCP socket connection via the tool "netcat" as stated in my first post: nc -nv 192.168.0.13 8080
- Inserting the string "GET http://null/ HTTP/1.1" leads to the stacktrace given above.

Since there is a option in ZAP (Local Proxies -> Address) to change the listening address from loopback to something else, I assumed that ZAP could be used in a (at least "internal") network besides loopback. This is what would be awesome when it comes to using ZAP in Jenkins CI environments etc., since then a ZAP has to be accessible over the network because maybe you don't want to have a ZAP on every single machine (divergent configs etc.).

Since ZAP is talking over sockets anyway, this seemed to me like a desirable next step. Or is this just pie in the sky? :-) Maybe I misinterpreted the roadmap of ZAP a little bit...sorry for that.

**Comment by kingthorin** [comment]
You’re right that ZAP can listen on a non-loop back interface and that is definitely by design. However it isn’t made to be long running or support large numbers of clients (yet). 

When you ask it to process an invalid request how would you like/expect it to respond?

I don’t see the issue of a stacktrace on the wire, nothing has leaked that isn’t public knowledge or already been seen on the wire...

**Comment by fhauser84** [comment]
Alright, I wasn't aware of non-supporting (larger number of) clients in a network so far, sorry.

Well, how should a server respond to a invalid request: the HTTP code is just fine. For a network component, which ZAP is not as I understand now, it simply should not show a stacktrace. Just snip your "e.printStackTrace()" (however it is implemented?!) and just put it in your logs but never reflect back to the client.

Even so your code is publicly available, stacktraces on the wire could be bad anyways, e.g. IF ZAP would be a network component:
- IDS/monitoring systems etc. could be triggered.
- Faster evaluation for an attacker by seeing traces from several libraries you use (don't have to look into your sources anymore). This could be triggered by vuln scanners for example.
- Many more arguments :-)

Well, since my primary assumption was wrong ("network based"), we can close this issue, if you like.
Sorry for any inconvenience. I'm looking forward ZAP maybe becoming a network component for enterprise security some time.

**Comment by psiinon** [comment]
That right, ZAP is really a single user system right now.
We do have plans for a scalable multi-user option, but they havnt been progressed for a while. If and when we support that then you are right, we should not return such stack traces :)
