### ISSUE TITLE
Unable to create reports with Export Report add-on and Java 9+

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4214]
Steps to reproduce the issue:
1. Run ZAP with Export Report (and Java 9);
2. Attempt to create a report through the API;
3. Note that no report is created, in the log there's an exception:
```
ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-ProxyThread-12"
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.zaproxy.zap.extension.exportreport.export.ExportReport.generateReport(ExportReport.java:176)
	at org.zaproxy.zap.extension.exportreport.ExtensionExportReport.generateReport(ExtensionExportReport.java:300)
	at org.zaproxy.zap.extension.exportreport.ExportReportAPI.handleApiAction(ExportReportAPI.java:170)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:431)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:256)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 7 more
```

Remarks:
When done through the UI it fails silently.

Add-on:
Export Report, version 4 (and older).

**Comment by thc202** [comment]
This will be addressed during the migration to Gradle (to avoid pushing more binaries to the repo), by depending on (and thus bundling) the required library.

**Comment by thc202** [comment]
Done in zaproxy/zap-extensions#1974.
