### ISSUE TITLE
experimentalDb for MySQL fails in ZAP 2.7.0 

### ISSUE THREAD

**Issue by SyCode7** [zaproxy/zaproxy#4262]
ZAP 2.6.0 worked well with the MySQL switch `zap.sh -experimentalDb` however the current version, 2.7.0 fails. Running on windows 10, with the ZAP native UI, the "creating new session file option. Please wait ..." dialog box prompts and remains forever.

**Comment by thc202** [comment]
Would you mind checking the zap.log file?

**Comment by SyCode7** [comment]
So the error went after I dropped the old MYSQL db. However, there is another error ` Failed to add script "Copy as curl command menu.js", provided script type "extender" not found, available: [proxy, httpsender, variant, standalone, targeted, active, passive] .  ` Also, the addon for exploring OpenAPI documents and other features available via the tools menu as described in this [ZAP blog](https://zaproxy.blogspot.de/2017/04/exploring-apis-with-zap.html) post are not available.

**Comment by thc202** [comment]
It seems the add-ons (Script Console and OpenAPI) are not installed. Which package did you download? (Core does not include any add-on.)
In any case you should be able to install the add-ons any time through the marketplace.

**Comment by SyCode7** [comment]
@thc202 I have tried your recommendations but there is no joy yet. I downloaded the core and manually installed openapi extension. I have the following errors when i attempt importing an openapi json file : 
`
16532 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - Unable to load the configuration
org.apache.commons.configuration.ConfigurationException: Unable to load the configuration
        at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:955)
        at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:908)
        at org.apache.commons.configuration.XMLConfiguration$XMLFileConfigurationDelegate.load(XMLConfiguration.java:1583)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:324)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:261)
        at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238)
        at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.load(AbstractHierarchicalFileConfiguration.java:184)
        at org.zaproxy.zap.utils.ZapXmlConfiguration.<init>(ZapXmlConfiguration.java:88)
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getPreviousVersionInfo(ExtensionAutoUpdate.java:883)
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.alertIfNewVersions(ExtensionAutoUpdate.java:639)
        at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 3-byte UTF-8 sequence.
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:408)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1895)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:942)

` 
I also cloned the entire zap git to play and tried using mysql by changing the adapting db.properties file. I made sure also that Openapi extention was installed via the gui and tried to import an openapi file. I had the following errors in the IDE : 
 `
12358 [Thread-8] INFO hsqldb.db..ENGINE  - dataFileCache open end
61549 [AWT-EventQueue-0] WARN org.zaproxy.zap.extension.openapi.ExtensionOpenApi  - Connection refused: connect
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:337)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:568)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:527)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:505)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:494)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:409)
	at org.zaproxy.zap.extension.openapi.network.Requestor.getResponseBody(Requestor.java:95)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinition(ExtensionOpenApi.java:171)
	at org.zaproxy.zap.extension.openapi.ImportFromUrlDialog.actionPerformed(ImportFromUrlDialog.java:137)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:139)
	at org.zaproxy.zap.extension.openapi.ImportFromUrlDialog.<init>(ImportFromUrlDialog.java:114)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$2$1.run(ExtensionOpenApi.java:152)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

**Comment by SyCode7** [comment]
@kingthorin @thc202  i didnt't get through this, infact I decided to manage it by grabbing every report and persisting it into another mysql database. Not ideal but works !!

**Comment by kingthorin** [comment]
@SyCode7 are you ok with the ticket being closed? There's not much more we can do here since the errors don't seem to be DB related and you've gone a different direction.

There is still work being done towards ZaaS and better/different db support.
