### ISSUE TITLE
OWASP ZAP 'stuck' 'Shutting down server and database' with large sessions

### ISSUE THREAD

**Issue by VorTechS** [zaproxy/zaproxy#4348]
On several occasions now, I've been running OWASP ZAP (on port 8081) against debug projects in Visual Studio 2015 and when I try to close the application after marathon sessions (over a period 2-3 days) that result in session files in excess of 2.x GB in size, the application sits with a (modal) dialog of 'Shutting down server and database'.  

There's usually a flurry of disk activity which can go on for some time, but then nothing appears to happen afterwards.  After half an hour of 'nothingness' I usually assume that nothing is really happening and kill the process.  Before closing the application I always save the current session off in case there's anything I might need reporting-wise later on.

Today, I thought I'd see what happened when I click on the 'X' (close dialog) button on this popup and the application simply closed (apparently cleanly, as there was nothing sinister hiding in Event Viewer)

My process is:

Start Visual Studio 2015 Update 3 Debugging (3 website projects, 2 of which are WCF services)
Work my way through every screen and function in the UI element of the application
Set out a scope relevant only to the 3 projects in use
Set 'Active Scan -> Timeout to 0'
Start an 'Active Scan'

Occasionally I'll have to interact with Visual Studio that may have highlighted an in-handled exception, where I just get it to continue (for some reason it ignores the exception settings telling it not to throw in-handled CLR exceptions).

Present in the latest version (2.7) and has been present in unidentified versions from last year, 2014 and 2015 also, which were entirely separate machines and organisations.

**Comment by thc202** [comment]
Could you check the zap.log [1] file? I guess it's hitting a out of memory error.

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by VorTechS** [comment]
Sure.  Here's a sample of the later entries in the last ZAP log file (that's not the current one as I started a new session just a few minutes ago):

```
2018-02-05 13:34:02,670 [ZAP-WS-Listener (remote) 'localhost:23830 (#251)'] ERROR WebSocketMessagesViewModel - java.sql.SQLNonTransientConnectionException: connection exception: closed
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessageCount(TableWebSocket.java:241)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.getRowCount(WebSocketMessagesViewModel.java:147)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.fireMessageArrived(WebSocketMessagesViewModel.java:376)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketPanel.onMessageFrame(WebSocketPanel.java:455)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:668)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:561)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.buildCriteriaStatementHelper(TableWebSocket.java:740)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.buildMessageCriteriaStatement(TableWebSocket.java:511)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessageCount(TableWebSocket.java:234)
	... 9 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 14 more
2018-02-05 13:34:02,677 [ZAP-WS-Listener (remote) 'localhost:23830 (#251)'] ERROR WebSocketMessagesViewModel - java.sql.SQLNonTransientConnectionException: connection exception: closed
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessageCount(TableWebSocket.java:241)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.getRowCount(WebSocketMessagesViewModel.java:147)
	at java.desktop/javax.swing.JTable$ModelChange.<init>(Unknown Source)
	at java.desktop/javax.swing.JTable.sortedTableChanged(Unknown Source)
	at java.desktop/javax.swing.JTable.tableChanged(Unknown Source)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(Unknown Source)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.fireMessageArrived(WebSocketMessagesViewModel.java:382)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketPanel.onMessageFrame(WebSocketPanel.java:455)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:668)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:561)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.buildCriteriaStatementHelper(TableWebSocket.java:740)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.buildMessageCriteriaStatement(TableWebSocket.java:511)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessageCount(TableWebSocket.java:234)
	... 15 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 20 more
2018-02-05 13:34:02,677 [ZAP-WS-Listener (remote) 'localhost:23830 (#251)'] ERROR WebSocketMessagesViewModel - java.sql.SQLNonTransientConnectionException: connection exception: closed
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessageCount(TableWebSocket.java:241)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.getRowCount(WebSocketMessagesViewModel.java:147)
	at org.jdesktop.swingx.sort.TableSortController$TableRowSorterModelWrapper.getRowCount(TableSortController.java:144)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsInserted(DefaultSortController.java:403)
	at java.desktop/javax.swing.JTable.notifySorter(Unknown Source)
	at java.desktop/javax.swing.JTable.sortedTableChanged(Unknown Source)
	at java.desktop/javax.swing.JTable.tableChanged(Unknown Source)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(Unknown Source)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableRowsInserted(Unknown Source)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketMessagesViewModel.fireMessageArrived(WebSocketMessagesViewModel.java:382)
	at org.zaproxy.zap.extension.websocket.ui.WebSocketPanel.onMessageFrame(WebSocketPanel.java:455)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:668)
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:561)
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:89)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.buildCriteriaStatementHelper(TableWebSocket.java:740)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.buildMessageCriteriaStatement(TableWebSocket.java:511)
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessageCount(TableWebSocket.java:234)
	... 17 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 22 more
```

It may or may not be related, as they look like they may be related to when I was browsing to the API to look at extracting the alerts out (which I subsequently found using the Reporting option)

**Comment by kingthorin** [comment]
@VorTechS at what point are you persisting the session? Do you have "Compact (on exit)" set?

https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsPersistsession
https://github.com/zaproxy/zap-core-help/wiki/HelpUiTlmenuFile#persist-session
https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDatabase#compact-on-exit

**Comment by kingthorin** [comment]
@VorTechS are you able to answer the previous questions or can this be closed?

**Comment by VorTechS** [comment]
Sorry, I missed the previous notification.  The session was being persisted right at the end of the process.  It was started, setup and executed with no intermediate persistence.

Compact on Exit is not set.

**Comment by kingthorin** [comment]
Thanks
