### ISSUE TITLE
zap api Fails at spider scan stage

### ISSUE THREAD

**Issue by tanujain** [zaproxy/zaproxy#4353]
I am trying to use ZAP API for ZAP version 2.7. 
I have installed python-owasp-zap-v2.4 on the machine and using dummy code as given https://github.com/zaproxy/zaproxy/wiki/ApiPython but I am getting an error as shown below. I am not able to figure out the issue. Could anyone suggest if this is a problem with the latest version as is it something else?

STACK TRACE:
Traceback (most recent call last):
  File "./zapapicode.py", line 25, in <module>
    scanid = zap.spider.scan(target)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/spider.py", line 212, in scan
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'spider/action/scan/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

This is resolved. The issue was with the wrong API key.

**Comment by thc202** [comment]
Great, thanks for letting us know.

For the record, there's a FAQ entry with more details: https://github.com/zaproxy/zaproxy/wiki/FAQapikey

**Comment by WeiserAriel** [comment]
Add the same issue....
the problem was using the wrong apikey :)
