### ISSUE TITLE
Error creating new context on zap headless mode via zap python api

### ISSUE THREAD

**Issue by setzamora** [zaproxy/zaproxy#4417]
Two issues:

1. Unable to remove the default context
2. Unable to create a new context

```
default_context_name = 'Default Context'
context_name = 'New Context'
api_key = ''

zap = ZAPv2(apikey = api_key)
zap.context.set_context_in_scope(contextname = default_context_name, booleaninscope = False, apikey = api_key)
zap.context.remove_context(contextname = default_context_name, apikey = api_key)

zap.context.new_context(contextname = context_name, apikey = api_key)
zap.context.include_in_context(contextname = context_name, regex = include_url, apikey = api_key)
zap.context.set_context_in_scope(contextname = context_name, booleaninscope = True, apikey = api_key)
```

I'm getting this error. The zap daemon is confirmed to be running.

```
Traceback (most recent call last):
  File "scan.py", line 78, in run
    zap.context.set_context_in_scope(contextname = default_context_name, booleaninscope = False, apikey = api_key)
  File "/usr/local/lib/python3.5/dist-packages/zapv2/context.py", line 138, in set_context_in_scope
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'context/action/setContextInScope/', {'contextName': contextname, 'booleanInScope': booleaninscope, 'apikey': apikey})))
  File "/usr/local/lib/python3.5/dist-packages/zapv2/__init__.py", line 160, in _request
    return data.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by thc202** [comment]
Could you check the ZAP output/log? The Default Context might not be present.

I'm not able to reproduce the exception provided. Which version of the API client are you using?

**Comment by setzamora** [comment]
Nothing in the zap.log except the usual daemon startup logs.

I think it has something to do with the python api.

Here are the details:

```
Requirement already satisfied: python-owasp-zap-v2.4 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: six in /usr/local/lib/python3.5/dist-packages (from python-owasp-zap-v2.4)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from python-owasp-zap-v2.4)
```

**Comment by setzamora** [comment]
Error log:

```
root@74990976a131:/root# 984699 [ZAP-ProxyThread-206] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/context/action/newContext/] from [127.0.0.1]:
Bad Format (bad_format)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:349)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:456)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
        at java.lang.Thread.run(Thread.java:748)
Bad Format
[2]-  Done                    curl -X GET http://zap/context/action/newContext/?zaapiformat=JSON
[3]+  Done                    formMethod=GET
```

**Comment by thc202** [comment]
The API request is indeed malformed it should be something like:
`http://zap/JSON/context/action/newContext/?contextName=Test`
Missing the format. `JSON`. The parameters `zapapiformat` and `formMethod` could be removed, not used by the ZAP API. (Note that the ampersands should be escaped.)

**Comment by thc202** [comment]
That does not give useful response though, `JSON` or `XML` should.

**Comment by setzamora** [comment]
We can now close this issue.

How the problem was solved:

- Set the system HTTP proxy to ZAP
`ENV http_proxy http://127.0.0.1:80`
- Reuse chromedriver / geckodriver 
`ENV PATH $PATH:/root/.ZAP/webdriver/linux/64/`

- Set webdriver's HTTP proxy to ZAP
```
        profile = webdriver.FirefoxProfile()
        profile.set_preference('network.proxy.type', 1)
        profile.set_preference('network.proxy.http', '127.0.0.1')
        profile.set_preference('network.proxy.http_port', 80)
        profile.update_preferences()

        options = webdriver.FirefoxOptions()
        options.add_argument('--headless')

        browser = webdriver.Firefox(firefox_profile = profile, firefox_options = options)
```
- Set Python ZAPv2 proxy to ZAP
```
        proxies = {
            'http': 'http://127.0.0.1:80',
            'https': 'http://127.0.0.1:80'
        }

        zap = ZAPv2(proxies = proxies)
```

**Comment by kingthorin** [comment]
Thanks for letting us know.

**Comment by thc202** [comment]
Cool, thanks for letting us know!

**Comment by thc202** [comment]
Oops! :)
