### ISSUE TITLE
Chrome not included in Docker images

### ISSUE THREAD

**Issue by jamatute** [zaproxy/zaproxy#4427]
Hi, I'm trying to launch the chrome browser from within zap but it doesn't work. I've tried with several versions of Zap

* owasp/zap2docker-stable
```
Found Java version 1.8.0_151
Available memory: 7746 MB
Setting jvm heap size: -Xmx1936m
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP 2.7.0 started ...
....
```

* owasp/zap2docker-weekly

```
Found Java version 1.8.0_151
Available memory: 7746 MB
Setting jvm heap size: -Xmx1936m
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP D-2018-02-18 started 22/02/18 11:36:20 with home /home/zap/.ZAP_D/
...
````

* owasp/zap2docker-live

```
Found Java version 1.8.0_151
Available memory: 7746 MB
Setting jvm heap size: -Xmx1936m
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP D-2018-02-22 started 22/02/18 11:40:28 with home /home/zap/.ZAP_D/
....
```

And when I clik on `Chrome` `Launch Browser` I get the following trace on all versions:

```
/home/zap/.ZAP/webdriver/linux/64/chromedriver: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
Feb 22, 2018 11:34:56 AM org.openqa.selenium.os.OsProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Process exited with an error: 127 (Exit value: 127)
57063 [Thread-10] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch  - Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'e6dbd70e1652', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-5-amd64', java.version: '1.8.0_151'
Driver info: driver.version: ChromeDriver
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'e6dbd70e1652', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-5-amd64', java.version: '1.8.0_151'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:650)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:628)
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:600)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:491)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:571)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:540)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:528)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:519)
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$2$1.run(ExtensionQuickStartLaunch.java:278)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:15943/status] to be available after 20003 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
	... 19 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 20 more
```
And chrome never opens

**Comment by kingthorin** [comment]
I suspect that’s expected, from within the docket container ZAP likely can’t find Chrome (or any browser?) on your local host system.

**Comment by thc202** [comment]
How is docker/ZAP being started?

**Comment by jamatute** [comment]
@kingthorin it is able to launch firefox and jxbrowser.

@thc202 with this alias:
```bash
alias zap='docker run -u zap \
  -v ~/.local/share/zap:/home/zap \
  -v /tmp/.X11-unix/:/tmp/.X11-unix \
  -e DISPLAY=unix:0 \
  --device /dev/snd \
  -p 8080:8080 \
  -p 8090:8090 \
  -i owasp/zap2docker-stable \
  zap.sh -host 0.0.0.0 -port 8080'

alias zapw='docker run -u zap \
  -v ~/.local/share/zap:/home/zap \
  -v /tmp/.X11-unix/:/tmp/.X11-unix \
  -e DISPLAY=unix:0 \
  --device /dev/snd \
  -p 8080:8080 \
  -p 8090:8090 \
  -i owasp/zap2docker-weekly \
  zap.sh -host 0.0.0.0 -port 8080'

alias zapl='docker run -u zap \
  -v ~/.local/share/zap:/home/zap \
  -v /tmp/.X11-unix/:/tmp/.X11-unix \
  -e DISPLAY=unix:0 \
  --device /dev/snd \
  -p 8080:8080 \
  -p 8090:8090 \
  -i owasp/zap2docker-live \
  zap.sh -host 0.0.0.0 -port 8080'
```

**Comment by kingthorin** [comment]
@jamatute thanks for the update.

**Comment by thc202** [comment]
Chrome is not being installed in the images (just Firefox).

**Comment by setzamora** [comment]
If you really want Google Chrome, do this. I'm assuming you need Selenium as well.

```
FROM owasp/zap2docker-stable

# Add Google Chrome Repo
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# Install Dependencies
RUN apt-get install -y apt-transport-https
RUN apt-get update -y
RUN apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4

# Set Google Chrome, ChromeDriver and Selenium Versions
ENV CHROME_DRIVER_VERSION 2.35
ENV SELENIUM_STANDALONE_VERSION 3.4.0
ENV SELENIUM_SUBDIR 3.4

# Install Google Chrome
RUN apt-get install -y google-chrome-stable

# Install ChromeDriver
RUN wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
RUN unzip ~/chromedriver_linux64.zip -d ~/
RUN rm ~/chromedriver_linux64.zip
RUN mv -f ~/chromedriver /usr/local/bin/chromedriver
RUN chown root:root /usr/local/bin/chromedriver
RUN chmod 0755 /usr/local/bin/chromedriver

# Install Selenium
RUN wget -N http://selenium-release.storage.googleapis.com/$SELENIUM_SUBDIR/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar -P ~/
RUN mv -f ~/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar /usr/local/bin/selenium-server-standalone.jar
RUN chown root:root /usr/local/bin/selenium-server-standalone.jar
RUN chmod 0755 /usr/local/bin/selenium-server-standalone.jar
```

**Comment by psiinon** [comment]
ZAP already bundles selenium and chrome driver.
Do we want to include chrome in any of the docker images? That will no doubt make them bigger.
Alternatively we could provide a script that correctly installs it and configures ZAP to know where it is?

**Comment by setzamora** [comment]
@psiinon that would be great and it makes sense to just reuse ZAP's selenium and chrome driver bundle. 

This is the error we get when we don't _re_install Selenium and Chrome Driver:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'
```

A separate official zap docker image with Google Chrome might make sense as some web apps support Google Chrome only; it doesn't hurt to roll your own Dockerfile either.

**Comment by thc202** [comment]
The `chromedriver` is not added to the `PATH`, it's just copied to `<ZAP-home>/webdriver/linux/64/chromedriver`.

**Comment by setzamora** [comment]
FROM owasp/zap2docker-stable

USER root
WORKDIR /root/

# Set environment variables
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV HOME /root/
ENV OLDPWD /root/.ZAP
ENV PWD /root

RUN apt-get update -y
# Add Google Chrome Repo
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# Install Dependencies
RUN apt-get install -y apt-transport-https
RUN apt-get update -y
RUN apt-get install -y python3-pip && apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4

# Install Google Chrome
RUN apt-get install -y google-chrome-stable

# Add ZAP Python Scripts
RUN pip install --upgrade pip
RUN pip3 install --upgrade pip
RUN pip3 install zapcli

WORKDIR /root/
# Do not forget to set this to ZAP
ENV http_proxy http://127.0.0.1:80
# Reuse webdrivers
ENV PATH $PATH:/root/.ZAP/webdriver/linux/64/

**Comment by jamatute** [comment]
@setzamora Thank you for your answer

Although it still doesn't launch Chrome and the logs don't show any error :S 

Any idea why?

**Comment by psiinon** [comment]
This is now documented in https://www.zaproxy.org/faq/how-do-i-use-chrome-with-zap-in-docker/
