### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by ssnmworld** [zaproxy/zaproxy#4519]
Hi - I have a Spring boot application that uses JUnit test cases. I used the TestRestTemplate with Proxy to define the zap proxy server, to record the urls for test case.

  proxy = new Proxy(Type.HTTP, new InetSocketAddress(proxyServer, Integer.valueOf(proxyPort)));
  requestFactory.setProxy(proxy);
  RestTemplate template = new RestTemplate(requestFactory);				
   template.setRequestFactory(requestFactory);
   testRestTemplate = new TestRestTemplate(template);

This approach is validated fine in Mac OS, where I can record the urls and run scans on them and produce results.

But, the same code is used in Linux, where I get this error in the zap.log, where it attempts to log the urls, but some header-related error. All the HTTP requests returns 502 instead of 200, in the JUnit test cases. 

2018-03-18 22:45:14,841 [ZAP-ProxyThread-1] DEBUG HttpSessionsSite - No session tokens for: 127.0.0.1:55545
2018-03-18 22:45:14,961 [Thread-8] DEBUG SiteMap - addPath http://127.0.0.1:55545/issuing/account/terms/1234
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findAndAddChild Sites / http://127.0.0.1:55545
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findChild Sites / http://127.0.0.1:55545
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findAndAddChild http://127.0.0.1:55545 / issuing
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findChild http://127.0.0.1:55545 / issuing
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findAndAddChild issuing / account
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findChild issuing / account
2018-03-18 22:45:14,962 [Thread-8] DEBUG SiteMap - findAndAddChild account / terms
2018-03-18 22:45:14,963 [Thread-8] DEBUG SiteMap - findChild account / terms
2018-03-18 22:45:14,963 [Thread-8] DEBUG SiteMap - findAndAddLeaf terms / 1234
2018-03-18 22:45:14,963 [Thread-8] DEBUG SiteMap - findChild terms / GET:1234
2018-03-18 22:45:14,963 [Thread-8] DEBUG SimpleEventBus - publishSyncEvent siteNode.added from org.parosproxy.paros.model.SiteMapEventPublisher
2018-03-18 22:45:15,674 [ZAP-ProxyThread-1] DEBUG HttpInputStream - Read 0 bytes from upstream. Could not read header!
2018-03-18 22:45:15,674 [ZAP-ProxyThread-1] DEBUG ProxyThread - IOException: 
java.io.IOException
	at org.parosproxy.paros.network.HttpInputStream.readRequestHeader(HttpInputStream.java:65)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:443)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Unknown Source)

Can you provide some insight on this issue ? 

Thanks

**Comment by thc202** [comment]
What are the actual contents of the response returned to the client? It seems that ZAP is not able to deliver the request to the target (`127.0.0.1:55545`).

**Comment by ssnmworld** [comment]
The actual content is the JSON response, coming back to the test case.

**Comment by thc202** [comment]
Interesting, could you provide the whole response header?

**Comment by ssnmworld** [comment]
Here are the response headers..

Age →0
Cache-Control →no-cache, no-store, max-age=0, must-revalidate
Connection →Keep-Alive
Content-Type →application/json;charset=UTF-8
Date →Mon, 19 Mar 2018 20:00:07 GMT
Expires →0
Pragma →no-cache
Transfer-Encoding →chunked
X-Application-Context →api:test,default,unittest:8080
X-Content-Type-Options →nosniff
X-Frame-Options →DENY
X-XSS-Protection →1; mode=block

**Comment by thc202** [comment]
And the status line? Just to confirm, that's what's returned by ZAP? (Not the application under test directly.)

**Comment by ssnmworld** [comment]
The status code returned was 502. If I remove the zap proxy from the test code resttemplate, it works fine.

**Comment by thc202** [comment]
And the reason phrase? I'm still not sure what the issue is in ZAP, based on the logs provided it seems to be working as expected. The log `Could not read header!` is happening when reading a second request from the client, but fails because the client closes the connection (in this case ZAP does not return anything).
Do you know if ZAP has any replacer rule [1] or script [2] enabled that could be changing the response?

[1] https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsReplacerReplacer
[2] https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsScriptsScripts

**Comment by thc202** [comment]
@ssnmworld any more info on this one? Can be closed?

**Comment by kingthorin** [comment]
@ssnmworld any more info on this one? Can be closed?
