### ISSUE TITLE
Zaproxy in Docker - Badstatus Line

### ISSUE THREAD

**Issue by SeriyVol4ishe** [zaproxy/zaproxy#4606]
I run zaproxy in Docker container with this command:
```docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://testhtml5.vulnweb.com/ ```
But I have that output: 
```
[INFO]            Starting ZAP daemon
[INFO]            Running a quick scan for http://testhtml5.vulnweb.com/ 
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:],**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 230, in quick_scan
    zap_helper.run_active_scan(url, options['recursive'], options['context_name'], options['user_name'])
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 171, in run_active_scan
    scan_id = self.zap.ascan.scan(target_url, recurse=recursive, apikey=self.api_key)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/ascan.py", line 209, in scan
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'ascan/action/scan/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by thc202** [comment]
I'd guess it's because of the address:
https://github.com/zaproxy/zaproxy/wiki/FAQremote

Could you try allow all?

**Comment by SeriyVol4ishe** [comment]
nothing happend=( the same output

**Comment by kingthorin** [comment]
Can you be specific please. What did you change and how did you set it?

**Comment by SeriyVol4ishe** [comment]
so, a pulled your docker image and run container in my program using aiodocker. all parameters are correct (saw it in portainer). today tried running with terminal and all works... but with aiodocker doesn't.

**Comment by thethirdlink** [comment]
i got the same error below it's just that i'm using ZAP-CLI

root@kali:~# zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://123.456.789.123/
[INFO]            Starting ZAP daemon
[WARNING]         ZAP is already running on port 8090
[INFO]            Running a quick scan for http://123.456.789.123/
Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 11, in <module>
    load_entry_point('zapcli==0.9.0', 'console_scripts', 'zap-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zapcli/cli.py", line 230, in quick_scan
    zap_helper.run_active_scan(url, options['recursive'], options['context_name'], options['user_name'])
  File "/usr/local/lib/python2.7/dist-packages/zapcli/zap_helper.py", line 171, in run_active_scan
    scan_id = self.zap.ascan.scan(target_url, recurse=recursive, apikey=self.api_key)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/ascan.py", line 215, in scan
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'ascan/action/scan/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by thc202** [comment]
@SeriyVol4ishe and @thethirdlink could you check the ZAP log/output? [1] ZAP should be logging the reason why the API request was not accepted (if that's the problem).

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by kingthorin** [comment]
Closing. 1month + with no response.
