### ISSUE TITLE
unable to check update add ons - windows 7 - displays error

### ISSUE THREAD

**Issue by Gam-7** [zaproxy/zaproxy#4634]
when I go to manage add ons > Marketplace > check for updates , I get the following

![7](https://user-images.githubusercontent.com/38298059/39439117-6b9f4c60-4c9e-11e8-8626-3964253e6dd1.png)

version 2.7.0 
works fine on kali

**Comment by kingthorin** [comment]
Is that as soon as you open the Marketplace? Of when you click "Check for Updates"?

**Comment by thc202** [comment]
Worth taking a look at zap.log file. [1]

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by Gam-7** [comment]
when i click check for updates

**Comment by Gam-7** [comment]
2018-04-30 17:37:20,050 [ZAP-cfu] WARN  ExtensionAutoUpdate - Failed to check for updates using: https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions-2.7.xml
java.net.ConnectException: Connection refused: connect
	at java.base/java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.base/java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.PlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:333)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:564)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:523)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:501)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:405)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getRemoteConfigurationUrl(ExtensionAutoUpdate.java:806)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$900(ExtensionAutoUpdate.java:94)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$8.run(ExtensionAutoUpdate.java:963)

**Comment by kingthorin** [comment]
Is this the first time you've run ZAP on that system? Is Windows firewall running? Did you allow java access when prompted?

**Comment by Gam-7** [comment]
[Solved] The error was becasue I was using a proxy chain to burp but did not have burp open. Silly me. working fine now thanks

**Comment by kingthorin** [comment]
Thanks for letting us know.
