### ISSUE TITLE
Can't get the alerts, when i use python api -- zapv2.

### ISSUE THREAD

**Issue by purpleroc** [zaproxy/zaproxy#4640]
At first spider the target: zap.spider.scan(target)
and then scan zap.ascan.scan(target)
and after that, when i use zap.core.alerts() to get all results, I got a problem, some times it return 'Internal Error', and some times just can't get the result, looks like stucked.

**Comment by thc202** [comment]
Could you check the zap.log file? [1]

You might need to get the alerts in batches (depending on how many were raised).

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfig

**Comment by purpleroc** [comment]
Seems filled with Exception like this:
looks like can't read content from /root/.ZAP/session/untitled1.data.
and when I check this file, found it full filled with \x00.

My working environment is like this:
I will startup ZAP every minute and listening different ports from 80 to 90, and when i got a job I will chose one of the port, and after get alerts I will shutdown this process.

It seems I will use different users to startup the ZAP?

2018-05-04 10:44:43,959 [Thread-9] WARN  HostProcess - Failed to read message with ID [3288], cause: java.sql.SQLException: IO error: RowInputBinary
2018-05-04 10:44:43,959 [Thread-9] FATAL ENGINE - /root/.ZAP/session/untitled1.data getFromFile failed 1204605
org.hsqldb.HsqlException: IO error: RowInputBinary
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readInt(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.<init>(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
	at org.hsqldb.index.IndexAVL.findNode(Unknown Source)
	at org.hsqldb.index.IndexAVL.findFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.getFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getSingleResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getResult(Unknown Source)
	at org.hsqldb.StatementQuery.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.read(ParosTableHistory.java:255)
	at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:338)
	at org.parosproxy.paros.core.scanner.HostProcess.scanMessage(HostProcess.java:448)
	at org.parosproxy.paros.core.scanner.HostProcess.processPlugin(HostProcess.java:371)
	at org.parosproxy.paros.core.scanner.HostProcess.run(HostProcess.java:302)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at org.hsqldb.lib.HsqlByteArrayInputStream.readInt(Unknown Source)
	... 29 more
2018-05-04 10:44:43,960 [Thread-9] WARN  HostProcess - Failed to read message with ID [3289], cause: java.sql.SQLException: IO error: RowInputBinary
2018-05-04 10:44:43,960 [Thread-9] FATAL ENGINE - /root/.ZAP/session/untitled1.data getFromFile failed 1204605
org.hsqldb.HsqlException: IO error: RowInputBinary
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readInt(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.<init>(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
	at org.hsqldb.index.IndexAVL.findNode(Unknown Source)
	at org.hsqldb.index.IndexAVL.findFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.getFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getSingleResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getResult(Unknown Source)
	at org.hsqldb.StatementQuery.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
	at org.parosproxy.paros.db.paros.ParosTableHistory.read(ParosTableHistory.java:255)
	at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:338)
	at org.parosproxy.paros.core.scanner.HostProcess.scanMessage(HostProcess.java:448)
	at org.parosproxy.paros.core.scanner.HostProcess.processPlugin(HostProcess.java:371)
	at org.parosproxy.paros.core.scanner.HostProcess.run(HostProcess.java:302)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException
	at org.hsqldb.lib.HsqlByteArrayInputStream.readInt(Unknown Source)
	... 29 more
........


And

**Comment by purpleroc** [comment]
found that:
158567 [ZAP-SpiderThreadPool-0-thread-1] ERROR org.zaproxy.zap.extension.spider.SpiderThread  - java.sql.SQLException: Data cache size limit is reached: 10000
158571 [ZAP-SpiderThreadPool-0-thread-1] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "ZAP-SpiderThreadPool-0-thread-1"

**Comment by purpleroc** [comment]
done
