### ISSUE TITLE
ZAProxy installer *and zap.sh script* crashes because I'm in Wayland

### ISSUE THREAD

**Issue by q2dg** [zaproxy/zaproxy#4659]
When I simply execute (as root) Linux's ZAP Proxy installer (that is to say, https://github.com/zaproxy/zaproxy/releases/download/2.7.0/ZAP_2_7_0_unix.sh file ) in my Wayland session (I'm using Fedora 28) I get these error messages:

_java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2020)
	at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
	at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
	at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
	at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
	at javax.swing.UIManager.initialize(UIManager.java:1459)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
	at javax.swing.UIManager.getUI(UIManager.java:1006)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at com.install4j.runtime.installer.frontend.FormPanel.<init>(FormPanel.java:50)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:67)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.<init>(ConsoleScreenExecutor.java:24)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.<init>(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:92)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:58)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)_

The output of _java -version_ command in this system is:

_openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)_

Thanks

 - Java: [e.g. openjdk version "1.8.0_171"]

**Comment by psiinon** [comment]
We use Install4J for our installer.
Have you searched for this error?
I've found the following links that look like they might be relevant:

- https://stackoverflow.com/questions/21131855/could-not-initialize-class-sun-awt-x11graphicsenvironment-on-solaris?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
- https://confluence.atlassian.com/bitbucketserverkb/linux-installer-fails-with-java-lang-noclassdeffounderror-could-not-initialize-class-sun-awt-x11graphicsenvironment-error-938843519.html
- https://docs.oracle.com/middleware/1221/core/BIMIG/GUID-D6038515-9AA2-4F29-8330-D68EADD058A1.htm#BIMIG-GUID-D6038515-9AA2-4F29-8330-D68EADD058A1

**Comment by q2dg** [comment]
The problem is I'm not using X. I'm using Wayland.

**Comment by psiinon** [comment]
I'm afraid I know nothing about Wayland. Have you tried using the Linux Package? - thats just a tar.gz

**Comment by q2dg** [comment]
Yes, yes. I think the problem is explained here: https://stackoverflow.com/questions/45200281/install-xsdk-on-fedora-java-lang-noclassdeffounderror-could-not-initialize-clas . As  ZAP installer must be executed as root, it can't use XWayland wrapper so it can't go through X subsystem. Well...it´s a problem of Install4J...so there's little to solve here, unfortunately. Thanks, anyway.
I let this issue open as a future reference.

**Comment by psiinon** [comment]
So the tar.gz works ok for you? That doesnt need to be run as root.

**Comment by q2dg** [comment]
Yes, it works. Running ./zap.sh script shows ZAP without any issue

**Comment by kingthorin** [comment]
Does this need to stay open? Closed issues are still searchable and always returned.

**Comment by q2dg** [comment]
The issue isn't resolved yet although it is a Install4J issue, not a ZAP's one.
It's already tagged to "third-party" here, so do whatever you consider.

**Comment by kingthorin** [comment]
I just downloaded Fedora live and the installer works fine for me. Yes you have to sudo to run it but it executes and finishes without issue, zap is installed. I get stuck trying to execute zap.sh
```terminal
[liveuser@localhost-live bin]$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)
[liveuser@localhost-live bin]$ pwd
/usr/local/bin
[liveuser@localhost-live bin]$ ./zap.sh 
Found Java version 1.8.0_162
Available memory: 3921 MB
Setting jvm heap size: -Xmx980m
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP 2.7.0 started 10/07/18 08:21:54 with home /home/liveuser/.ZAP/
196 [main] FATAL org.zaproxy.zap.GuiBootstrap  - ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
(Note, some of the ZAP features that require a display, for example, running AJAX Spider with Firefox, might still be run with the help of applications like Xvfb.)
ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
(Note, some of the ZAP features that require a display, for example, running AJAX Spider with Firefox, might still be run with the help of applications like Xvfb.)
```

Will grab the tar ball and see if it is more successful.

**Comment by q2dg** [comment]
Well, it seems even zap.sh script doesn't work now in a Wayland environment. I've downloaded ZAP weekly and I get this error running it as a regular user:

Found Java version 1.8.0_201
Available memory: 15911 MB
Using JVM args: -Xmx3977m
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP D-2019-03-04 started 07/03/19 22:50:34 with home /home/q2dg/.ZAP_D/
42 [main] FATAL org.zaproxy.zap.GuiBootstrap  - ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
(Note, some of the ZAP features that require a display, for example, running AJAX Spider with Firefox, might still be run with the help of applications like Xvfb.)
ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
(Note, some of the ZAP features that require a display, for example, running AJAX Spider with Firefox, might still be run with the help of applications like Xvfb.)

**Comment by thc202** [comment]
When was the last time it worked? 2.7.0? Asking because the headless check is in place since 2.5.0 (#2390).

**Comment by q2dg** [comment]
Well,according to my own comment (https://github.com/zaproxy/zaproxy/issues/4659#issuecomment-389574949) -because I just don't remember- it worked past year...

**Comment by q2dg** [comment]
Well, this issue starts to be urgent... weekly zap.sh still throws the "FATAL org.zaproxy.zap.GuiBootstrap  - ZAP GUI is not supported on a headless environment." and Wayland is progressing as default backend in Gnome environments (and, therefore, in Gnome, Fedora, etc)

**Comment by kingthorin** [comment]
You could try this: `sudo dnf install xorg-x11-apps --assumeyes`

**Comment by kingthorin** [comment]
Other suggestions: * https://www.reddit.com/r/Fedora/comments/5eb633/solution_running_graphical_app_with_sudo_in/
* https://stackoverflow.com/questions/39197208/java-gui-support-on-wayland

**Comment by q2dg** [comment]
Thanks a lot, @kingthorin , for your suggestions.
Sadly, none of them has worked: I get the same error every time

**Comment by q2dg** [comment]
Well...I've got the solution to zap.sh execution error: it wasn't a Wayland's fault...it was about lacking JRE installed: I've only had JRE-headless but not complete JRE. But message error was somewhat misleading... Sorry for the inconvenience. I'll close the issue, if you don't mind.

**Comment by psiinon** [comment]
Thanks for letting us know - that makes much more sense :)

**Comment by RJColeman** [comment]
I had the same problem using ZAP on Fedora 31 with the following java / jre versions:

```
$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

```
I had to:

`$ sudo yum install java-1.8.0-openjdk-devel  to get it to work.   `
