### ISSUE TITLE
Error feedback for failed openAPI definitions 

### ISSUE THREAD

**Issue by jammasterj89** [zaproxy/zaproxy#4667]
**Is your feature request related to a problem? Please describe.**
When importing openAPI / swagger definitions sometimes they don't work. The error is reported in zap.log as to why it has failed. However, the same generic message is always shown to the user (that it failed to parse).

**Describe the solution you'd like**
Use the title of the exception from openAPI in the front end, e.g. the error in zap.log is:

    org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Default host required but not provided.
     at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:114)
     at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:74)
     at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:217)

So the error on the front end could be the title of the error:

      Default host required but not provided.

**Comment by kingthorin** [comment]
Can you provide an example file that manifests this issue?

**Comment by jammasterj89** [comment]
Sure, steps to reproduce

Successful parse:
1. Save [this ](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json)file
2. Tools -> Import openAPI from local file system
3. Success message.

Failed to parse:
1. Delete _"host": "petstore.swagger.io"_, from previously downloaded .json
2. Tools -> Import openAPI from local file system
3. "Failed to parse" error displayed, and zap.log contains the described exception.

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1622.

**Comment by jammasterj89** [comment]
Thank you for such a quick fix @kingthorin @thc202 !

**Comment by kingthorin** [comment]
In the end it looks like this:
![image](https://user-images.githubusercontent.com/7570458/40054805-125a2892-5814-11e8-8fdf-4bfa713bbee7.png)

**Comment by psiinon** [comment]
:+1:

**Comment by thc202** [comment]
The new version is already available in the marketplace.

**Comment by jammasterj89** [comment]
Unfortunately I'm now seeing an error when importing a swagger.json file that was working before. The exception from the zap.log is below. Should I open a separate issue?

      2018-05-17 13:53:37,516 [ZAP-Import-OpenAPI-2] DEBUG SwaggerConverter - Examining defn 
      2018-05-17 13:53:38,461 [ZAP-Import-OpenAPI-2] WARN  ExtensionOpenApi - mapping values are not allowed here
    in 'string', line 2, column 13:
      "swagger" : "2.0",
                ^

      mapping values are not allowed here
      in 'string', line 2, column 13:
       "swagger" : "2.0",
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:252)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:167)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:62)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:121)
	at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:152)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:127)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:121)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:89)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:75)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:218)

**Comment by thc202** [comment]
Yes, that's a different issue. Which version are you using? Does not seem to be the latest.

**Comment by thc202** [comment]
Never mind the last question, the lines match.

**Comment by tejabanka1** [comment]
HI Team,
I am trying to run the zap scan with script based authenication for my swagger but I am not able to 

> Import a API def from local system. I am getting error "Default host needed but not provided". 
I gave all the user details and loaded the script and added the HTTP sender token and gave url in session properties and all goo but at the end I am getting that error when I try to import a API def file. please help me, TIA.

**Comment by tejabanka1** [comment]
![API Def Error](https://user-images.githubusercontent.com/51893377/59571882-3408a300-9077-11e9-8ee2-b360e59eb7dd.PNG)

**Comment by kingthorin** [comment]
https://swagger.io/docs/specification/2-0/basic-structure/
