### ISSUE TITLE
openAPI import error

### ISSUE THREAD

**Issue by jammasterj89** [zaproxy/zaproxy#4676]
I'm now seeing an error when importing a swagger.json file that was working before upgrading my openAPI plugin to the latest version as of 17/05/18 (ZAP 2.7.0). However, I can import [this ](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/json/petstore-expanded.json) example .json without error.

My zap.log contains:

      2018-05-17 13:53:37,516 [ZAP-Import-OpenAPI-2] DEBUG SwaggerConverter - Examining defn 
      2018-05-17 13:53:38,461 [ZAP-Import-OpenAPI-2] WARN  ExtensionOpenApi - mapping values are not allowed here
    in 'string', line 2, column 13:
      "swagger" : "2.0",
                ^

      mapping values are not allowed here
      in 'string', line 2, column 13:
       "swagger" : "2.0",
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:252)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:167)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:62)
	at io.swagger.parser.Swagger20Parser.convertToSwagger(Swagger20Parser.java:121)
	at io.swagger.parser.Swagger20Parser.parse(Swagger20Parser.java:152)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:127)
	at io.swagger.parser.SwaggerParser.parse(SwaggerParser.java:121)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:89)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:75)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:218)

**Comment by thc202** [comment]
It's falling back to YAML parser, does the file start with `{`?

**Comment by jammasterj89** [comment]
Thanks, just checked and no whitespace at the start, the file starts like so:

     {
        "swagger" : "2.0",
        "info" : {
        "version" : "1.0.1",

**Comment by kingthorin** [comment]
Using version 11 of the addon it imports fine for me....

**Comment by thc202** [comment]
@jammasterj89 that should work then, could you share the file or a trimmed/redacted version that reproduces the issue?

**Comment by thc202** [comment]
Fixed in zaproxy/zap-extensions#1628.

**Comment by thc202** [comment]
The new version (12) is available in the marketplace.
