### ISSUE TITLE
Getting started guide for developing a new extension

### ISSUE THREAD

**Issue by spyhunter99** [zaproxy/zaproxy#4765]
**Is your feature request related to a problem? Please describe.**

Apologies if this exists already but I couldn't find anything in the wiki. I want to make a new extension for zap and I'm totally not clear on what needs to be done. I've found what APIs I need to trigger and listen for and I've made a jar and placed it in the plugins folder, however it's never listed in the extensions list.

**Describe the solution you'd like**
A clear and concise description of what steps are required to activate a plugin. If it's a different packaging type, I need to know how to build it. Is it only certain extensions or file name patterns? Does it need to be signed?

**Comment by kingthorin** [comment]
Ant is use to build all the existing (non third party) addons. Have a look at build.xml in the master, beta, or alpha branch of the zaproxy/zap-extensions repo for examples.

Once you've created an appropriate target to build your new addon (generally addons start in the alpha branch) you can just run it and then use ctrl+L (File : Load Addon) to load the addon in ZAP.

**Comment by spyhunter99** [comment]
Gotcha, looks like there an extra xml file added to the jar. For those that don't primarily use ant, it might be worth documented the requirements for building an add on without it

**Comment by spyhunter99** [comment]
Actually, the zap-extension repo (master branch) isn't building. Looks like it's missing some kind of selenium dependency...

**Comment by kingthorin** [comment]
What target were you using?

**Comment by spyhunter99** [comment]
i just checked it out and ran `ant -f build/build.xml`

**Comment by kingthorin** [comment]
You'd need to build based on an actual target that's defined in the file.

I'm not sure if you're using eclipse but I find that makes life much easlier for building things. Just open build.xml, scroll down the outline to the target you want to run, right click it and select "Run As > Ant Build". Watch the details (stdout) in the console tab. Then you'll know where the addon (*.zap) file has been placed on disk, then you can just load it in ZAP (ctrl+L).

**Comment by spyhunter99** [comment]
i tried this `ant -f build/build.xml deploy-saverawmessage` got the same message
what version of selenium do i need?

**Comment by spyhunter99** [comment]
````
C:\projects\zap-extensions-master>ant -f build/build.xml deploy-saverawmessage
Buildfile: C:\projects\zap-extensions-master\build\build.xml

deploy-saverawmessage:

clean:
   [delete] Deleting directory C:\projects\zap-extensions-master\build\zap-exts
   [delete] Deleting directory C:\projects\zap-extensions-master\build\build
   [delete] Deleting directory C:\projects\zap-extensions-master\build\temp
   [delete] Deleting directory C:\projects\zap-extensions-master\build\buildtest
   [delete] Deleting directory C:\projects\zap-extensions-master\build\results

init:
    [mkdir] Created dir: C:\projects\zap-extensions-master\build\zap-exts
    [mkdir] Created dir: C:\projects\zap-extensions-master\build\build
    [mkdir] Created dir: C:\projects\zap-extensions-master\build\temp
    [mkdir] Created dir: C:\projects\zap-extensions-master\build\buildtest
    [mkdir] Created dir: C:\projects\zap-extensions-master\build\results

compile:
     [echo] Compiling the source...
    [javac] Compiling 21 source files to C:\projects\zap-extensions-master\build\build
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:31: error: package org.zaproxy.zap.extension.reveal does not exist
    [javac] import org.zaproxy.zap.extension.reveal.RevealAPI;
    [javac]                                        ^
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:32: error: package org.zaproxy.zap.extension.selenium does not exist
    [javac] import org.zaproxy.zap.extension.selenium.SeleniumAPI;
    [javac]                                          ^
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:33: error: package org.zaproxy.zap.extension.selenium does not exist
    [javac] import org.zaproxy.zap.extension.selenium.SeleniumOptions;
    [javac]                                          ^
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:34: error: package org.zaproxy.zap.extension.spiderAjax does not exist
    [javac] import org.zaproxy.zap.extension.spiderAjax.AjaxSpiderAPI;
    [javac]                                            ^
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:35: error: package org.zaproxy.zap.extension.spiderAjax does not exist
    [javac] import org.zaproxy.zap.extension.spiderAjax.AjaxSpiderParam;
    [javac]                                            ^
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:57: error: cannot find symbol
    [javac]             api = new AjaxSpiderAPI(null);
    [javac]                       ^
    [javac]   symbol:   class AjaxSpiderAPI
    [javac]   location: class ApiGenerator
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:58: error: cannot find symbol
    [javac]             api.addApiOptions(new AjaxSpiderParam());
    [javac]                                   ^
    [javac]   symbol:   class AjaxSpiderParam
    [javac]   location: class ApiGenerator
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:61: error: cannot find symbol
    [javac]             list.add(new RevealAPI(null));
    [javac]                          ^
    [javac]   symbol:   class RevealAPI
    [javac]   location: class ApiGenerator
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:62: error: cannot find symbol
    [javac]             list.add(new SeleniumAPI(new SeleniumOptions()));
    [javac]                          ^
    [javac]   symbol:   class SeleniumAPI
    [javac]   location: class ApiGenerator
    [javac] C:\projects\zap-extensions-master\src\org\zaproxy\zap\extension\ApiGenerator.java:62: error: cannot find symbol
    [javac]             list.add(new SeleniumAPI(new SeleniumOptions()));
    [javac]                                          ^
    [javac]   symbol:   class SeleniumOptions
    [javac]   location: class ApiGenerator
    [javac] 10 errors

BUILD FAILED
C:\projects\zap-extensions-master\build\build.xml:556: The following error occurred while executing this line:
C:\projects\zap-extensions-master\build\build.xml:422: The following error occurred while executing this line:
C:\projects\zap-extensions-master\build\build.xml:61: Compile failed; see the compiler error output for details.

Total time: 1 second

C:\projects\zap-extensions-master>ant -f build/build.xml gettingStarted
````

**Comment by kingthorin** [comment]
You probably need to specify the lib path since you're doing it from the command line.

https://ant.apache.org/manual/running.html

This old thread might help you as well:
https://groups.google.com/forum/#!msg/zaproxy-develop/rLuUxALS2oU/5UfneLhMBwAJ

**Comment by spyhunter99** [comment]
ok looks like the jar needs to have the ZapAddOn.xml file and the jar has to end in .,zap. With the xml file populated, i get the following

```
java.lang.IllegalArgumentException: Parameter version [1] is not valid: null
        at org.zaproxy.zap.Version.<init>(Version.java:52)
        at org.zaproxy.zap.control.BaseZapAddOnXmlData.createVersion(BaseZapAddOnXmlData.java:227)
        at org.zaproxy.zap.control.BaseZapAddOnXmlData.readDataImpl(BaseZapAddOnXmlData.java:196)
        at org.zaproxy.zap.control.BaseZapAddOnXmlData.<init>(BaseZapAddOnXmlData.java:166)
        at org.zaproxy.zap.control.ZapAddOnXmlFile.<init>(ZapAddOnXmlFile.java:47)
        at org.zaproxy.zap.control.AddOn.loadManifestFile(AddOn.java:357)
        at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:339)
        at org.zaproxy.zap.control.AddOnCollection.createAddOn(AddOnCollection.java:219)
        at org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:176)
        at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:150)
        at org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:154)
        at org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:78)
        at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:109)
        at org.parosproxy.paros.control.Control.addExtension(Control.java:162)
        at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:53)
        at org.parosproxy.paros.control.Control.init(Control.java:125)
        at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:306)
        at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:257)
        at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:70)
        at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:200)
        at java.lang.Thread.run(Unknown Source)
````

this was with a semantic version of "1" I also tried "1.1". Docs for the xml file state  `Optional, semantic version of the add-on`. What am i doing wrong?

**Comment by thc202** [comment]
There are wiki pages explaining the add-on structure and development e.g.:
https://github.com/zaproxy/zap-extensions/wiki/AddOnStructure
https://github.com/zaproxy/zap-extensions/wiki/AddOnDevelopment

(For sure they could be better and more detailed.)

Which branch are you using (I can see master but the number of source files don't match), here's the output (excerpt) of building the master branch:
```
➜  zap-extensions git:(master) ✗ ant -f build/build.xml 
Buildfile: /zap/zap-extensions/build/build.xml

clean:
   [delete] Deleting directory /zap/zap-extensions/build/zap-exts
   [delete] Deleting directory /zap/zap-extensions/build/build
   [delete] Deleting directory /zap/zap-extensions/build/temp
   [delete] Deleting directory /zap/zap-extensions/build/buildtest
   [delete] Deleting directory /zap/zap-extensions/build/results

init:
    [mkdir] Created dir: /zap/zap-extensions/build/zap-exts
    [mkdir] Created dir: /zap/zap-extensions/build/build
    [mkdir] Created dir: /zap/zap-extensions/build/temp
    [mkdir] Created dir: /zap/zap-extensions/build/buildtest
    [mkdir] Created dir: /zap/zap-extensions/build/results

compile:
     [echo] Compiling the source...
    [javac] Compiling 192 source files to /zap/zap-extensions/build/build
     [echo] Compiling tests...
    [javac] Compiling 33 source files to /zap/zap-extensions/build/buildtest
[...]
```

In your case you have a lot less source files, did you delete packages or libraries? If so, you also need to change the `ApiGenerator` to not include the deleted classes/libs (or delete it as well).

> is there a specific version i need or plugin set?

No, almost any (recent) version of Eclipse can be used as is (but Ant is all it's needed to build them).

> What am i doing wrong?

The Semantic Version is expected to be `MAJOR.MINOR.PATCH`, `1` is not enough (`1.0.0` should work though): https://semver.org/

These type of questions are better for the dev mailing list: https://groups.google.com/group/zaproxy-develop

**Comment by spyhunter99** [comment]
Ahh i just downloaded the zip and i think the windows screwed up unzipping the file. I just used 7zip and it compiles just fine. Thanks for the help
