### ISSUE TITLE
Reponse Body length problem

### ISSUE THREAD

**Issue by fyr3fyr3** [zaproxy/zaproxy#4783]
**Describe the bug**
I've want to scan a website, first I've got a cache error wich i can fix with the configuration in zapdb.script.
Now there's the next error with the response body length, see error message.
I run the zap script on the command line with the -cmd parameter and no gui.
I've searched several config files, but cant find any value matching the problem.

**Software versions**
 - ZAP: 2.7
 - Add-on: Spider
 - OS: SLES12 SP3
 - Java: openjdk version "1.8.0_171"
 - Browser: 

**Errors from the zap.log file**
> 2018-06-22 08:28:25,088 [ZAP-SpiderThreadPool-0-thread-2] ERROR SpiderThread - java.sql.SQLException: The actual Response Body length 18060436 is greater than the configured response body length 16777216
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: The actual Response Body length 18060436 is greater than the configured response body length 16777216
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:296)
	at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:359)
	at org.zaproxy.zap.extension.spider.SpiderThread.notifySpiderTaskResult(SpiderThread.java:488)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderTaskResult(Spider.java:809)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: The actual Response Body length 18060436 is greater than the configured response body length 16777216
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:311)
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:294)
	... 7 more
2018-06-22 08:28:25,095 [ZAP-SpiderThreadPool-0-thread-2] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "ZAP-SpiderThreadPool-0-thread-2"
java.lang.NullPointerException
	at org.zaproxy.zap.extension.spider.SpiderScan.notifySpiderTaskResult(SpiderScan.java:339)
	at org.zaproxy.zap.spider.Spider.notifyListenersSpiderTaskResult(Spider.java:809)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by thc202** [comment]
The size of the response body can be configured in Options > Database: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDatabase

but unless that file is really important it might worth excluding it (seems binary?).

**Comment by kingthorin** [comment]
@fyr3fyr3 anything further on this one?

**Comment by kingthorin** [comment]
No further input in ~1month. Closing.

**Comment by urbaniak** [comment]
How to configure that on the command line?

Running zap headless in docker and proxying integration tests via it

**Comment by thc202** [comment]
The body sizes can be changed with `-config database.request.bodysize=1000` and `-config database.response.bodysize=1000`. [1]

If the file is not relevant it's better excluding it though.

[1] https://github.com/zaproxy/zaproxy/wiki/FAQconfigValues
