### ISSUE TITLE
Jython script authentification don't load "script null"

### ISSUE THREAD

**Issue by Nazime** [zaproxy/zaproxy#4801]
**Describe the bug**
Error when using jython script "Simple form-based authentication.py"

**To Reproduce**
1. Go to Scripts -> New Script ... 
2. Select script Engine "python : jython"
3. Select template "simple form-based authentication.py"
4. Script name : test
5. Click save
6. Go to session properties -> authentication -> select script-based authentication
7. select script "test" -> click load

**Expected behavior**
Pop up window error :  Script loading error
an error has occurred while loading the selected authentication script : null
message in script console window : java.lang.reflect.UndeclaredThrowableException

**Screenshots**
![capture 2](https://user-images.githubusercontent.com/23621072/42092879-cb42ec40-7baa-11e8-8db8-a1d676995e1c.png)
![capture 3](https://user-images.githubusercontent.com/23621072/42092882-cdc3a6a8-7baa-11e8-9075-f0ef59341f34.png)

**Software versions**
 - ZAP: 2.7.0
 - Add-on:Python Scripting : 10.0.0
 - OS: Windows 7 
 - Java:  1.8.0_171-b11

**Errors from the zap.log file**
```
2018-06-29 14:50:48,599 [AWT-EventQueue-0] DEBUG ContextAuthorizationPanel - Initializing panel with BasicAuthorizationDetectionMethod: BasicAuthorizationDetectionMethod [AND: code=-1, header=null, body=null]
2018-06-29 14:50:48,599 [AWT-EventQueue-0] DEBUG ContextSessionManagementPanel - Initializing configuration panel for session management method: Cookie-based Session Management for context Default Context
2018-06-29 14:50:48,600 [AWT-EventQueue-0] DEBUG ContextAuthenticationPanel - Initializing configuration panel for authentication method: org.zaproxy.zap.authentication.ManualAuthenticationMethodType$ManualAuthenticationMethod@7460 for context Default Context
2018-06-29 14:50:48,601 [AWT-EventQueue-0] DEBUG ContextAuthenticationPanel - Binding authentication method to new panel of proper type for context Default Context
2018-06-29 14:50:48,601 [AWT-EventQueue-0] DEBUG ContextAuthenticationPanel - Selected new Authentication type: Manual Authentication
2018-06-29 14:50:48,602 [AWT-EventQueue-0] INFO  ContextAuthenticationPanel - Creating new panel for configuring: Manual Authentication
2018-06-29 14:50:51,677 [AWT-EventQueue-0] DEBUG ContextAuthenticationPanel - Selected new Authentication type: Script-based Authentication
2018-06-29 14:50:51,678 [AWT-EventQueue-0] INFO  ContextAuthenticationPanel - Creating new panel for configuring: Script-based Authentication
2018-06-29 14:50:56,397 [AWT-EventQueue-0] DEBUG ExtensionScript - invokeScript test
2018-06-29 14:50:59,887 [AWT-EventQueue-0] ERROR ScriptBasedAuthenticationMethodType - Error while calling authentication script
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy32.getLoggedInIndicator(Unknown Source)
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$ScriptBasedAuthenticationMethodOptionsPanel.loadScript(ScriptBasedAuthenticationMethodType.java:409)
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$ScriptBasedAuthenticationMethodOptionsPanel.access$500(ScriptBasedAuthenticationMethodType.java:274)
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$ScriptBasedAuthenticationMethodOptionsPanel$1.actionPerformed(ScriptBasedAuthenticationMethodType.java:316)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:139)
	at org.parosproxy.paros.view.SessionDialog.setVisible(SessionDialog.java:137)
	at org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:361)
	at org.parosproxy.paros.view.View.showSessionDialog(View.java:712)
	at org.parosproxy.paros.view.View.showSessionDialog(View.java:674)
	at org.parosproxy.paros.control.MenuFileControl.properties(MenuFileControl.java:513)
	at org.zaproxy.zap.view.MainToolbarPanel$7.actionPerformed(MainToolbarPanel.java:357)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2238)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2296)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4475)
	at java.awt.Container.dispatchEventImpl(Container.java:2282)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoSuchMethodException: getLoggedInIndicator
	at org.python.jsr223.PyScriptEngine$1.invoke(PyScriptEngine.java:178)
	... 91 more

```
**Additional context**
When i use "ECMAScritpt : Oracale Nashorn" it work perfectly

**Comment by thc202** [comment]
Merging into #4515. The fix is already included in the weekly releases: https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly
