### ISSUE TITLE
NullPointerException while uninstalling WebSockets add-on with ZAP without GUI

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#4815]
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/1N2eS9rRq98/discussion

Steps to reproduce the issue:
1. Start ZAP in daemon (or command line) mode and updating the websocket add-on, e.g.: `-daemon -addoninstall websocket`
2. Note in the output/log:
```
16178 [ZAP-daemon] ERROR org.zaproxy.zap.control.AddOnInstaller  - An error occurred while uninstalling the extension "ExtensionWebSocket" bundled in the add-on "websocket":
java.lang.NullPointerException
	at org.zaproxy.zap.extension.brk.ExtensionBreak.removeBreakpointsUiManager(ExtensionBreak.java:235)
	at org.zaproxy.zap.extension.websocket.ExtensionWebSocket.unload(ExtensionWebSocket.java:399)
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtension(AddOnInstaller.java:244)
	at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtensions(AddOnInstaller.java:219)
	at org.zaproxy.zap.control.AddOnInstaller.uninstall(AddOnInstaller.java:133)
	at org.zaproxy.zap.control.AddOnLoader.removeAddOnImpl(AddOnLoader.java:555)
	at org.zaproxy.zap.control.AddOnLoader.removeAddOn(AddOnLoader.java:511)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstall(ExtensionAutoUpdate.java:1070)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstallAddOns(ExtensionAutoUpdate.java:1438)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstallAddOn(ExtensionAutoUpdate.java:1424)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1041)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(ExtensionAutoUpdate.java:499)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.waitAndInstallDownloads(ExtensionAutoUpdate.java:1809)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installAddOns(ExtensionAutoUpdate.java:1633)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.execute(ExtensionAutoUpdate.java:1768)
	at org.parosproxy.paros.extension.ExtensionLoader.runCommandLine(ExtensionLoader.java:444)
	at org.parosproxy.paros.control.Control.runCommandLine(Control.java:324)
	at org.zaproxy.zap.DaemonBootstrap$1.run(DaemonBootstrap.java:88)
	at java.base/java.lang.Thread.run(Thread.java:844)
16223 [ZAP-daemon] WARN org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate  - It's recommended to restart ZAP. Not all add-ons were successfully uninstalled: [[id=websocket, version=14.0.0]]
```

ZAP:
Version 2.7.0

Add-on:
WebSockets version 16 (and older).

**Comment by idbs-coleman** [comment]
Hi this is George Coleman from the user group (the person who submitted the question).
I'm guessing this is fixed now since all the referenced PR's are approved.
What version of ZAP contains the fix?
Thank you :)

**Comment by thc202** [comment]
It's fixed in the weekly releases: https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by idbs-coleman** [comment]
Thank you :)

**Comment by idbs-coleman** [comment]
Thank you! :)
