### ISSUE TITLE
NTLM authentication - Out of sequence NTLM response message

### ISSUE THREAD

**Issue by avolna** [zaproxy/zaproxy#4847]
**Describe the bug**

When trying to perform NTLM authentication during Active Scan I receive error:
"2018-07-16 18:07:57,969 [ZAP-ActiveScanner-1] ERROR HttpMethodDirector - Out of sequence NTLM response message
org.apache.commons.httpclient.auth.MalformedChallengeException: Out of sequence NTLM response message".

Every few requests I also receive following error:
2018-07-16 18:50:03,583 [ZAP-ActiveScanner-0] WARN  VariantJSONQuery - Failed to parse the request body: Input is invalid JSON; does not start with '{' or '[', c=-1
java.lang.IllegalArgumentException: Input is invalid JSON; does not start with '{' or '[', c=-1

This log is generated after the client sends GET for the webpage and receives the first packet with headers:
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
After that, ZAP just ignores the test and starts next test in line (all tests require auth, so everything fails).

**To Reproduce**
0. Open the web browser with proxy configured for ZAP and click through the whole web application on https://example.com:9443/service (it's an AJAX service).
1. Sessions properties: Create new context with https://example.com:9443/service.*
2. Sessions properties: Authentication: HTTP/NTLM Authentication
	Hostname: https://example.com
	Port: 8443
	Realm: left empty (tried also with {AD Domain} and {AD Domain}.local)
	Regex pattern identified in Logged In response: {string_from_logged_in_response}
3. Sessions properties: Users: Add a valid user from the domain (tried both "{username}" and "{AD Domain}\{username}")
4. Forced User: username set in step 3
5. Session management: HTTP Authentication Session Management
6. Authorization: HTTP Status Code: 401
	Body contains regex: 'access restricted' (string that is placed on 401 page of the webapp)
	At least one of the conditions above must match.

After configuration run the scan:
7. On the Sites tree, right click on https://example.com:9443/service -> Attack -> Active Scan
8. In the Active Scan Scope tab:
	Starting point: https://example.com:9443/service
	Policy: Default
	Context: The one configured above (step 1)
	User: The one configured above (step 3)
9. Start scan.

**Expected behavior**
I have expected the software to log in properly, however it seems ZAP interprets NTLM negotiation call as out of sequence.

**Software versions**
 - ZAP: 2.7.0
 - Add-on: Set of default Add-ons. Pretty sure NTLM support is native for ZAP (?) and does not rely on any add-on
 - OS: Windows 10 17134
 - Java: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
 - Browser: clicking through the application was done with Chrome, version 67.0.3396.99

**Errors from the zap.log file**
2018-07-16 18:07:57,414 [Thread-607] INFO  HostProcess - Scanning 90 node(s) from https://example.com:9443/service as {user}
2018-07-16 18:07:57,418 [Thread-607] INFO  HostProcess - start host https://example.com:9443/service | TestRemoteFileInclude strength MEDIUM threshold MEDIUM
2018-07-16 18:07:57,442 [Thread-607] ERROR HttpMethodDirector - Out of sequence NTLM response message
org.apache.commons.httpclient.auth.MalformedChallengeException: Out of sequence NTLM response message
	at org.zaproxy.zap.network.ZapNTLMScheme.processChallenge(ZapNTLMScheme.java:131)
	at org.apache.commons.httpclient.auth.AuthChallengeProcessor.processChallenge(AuthChallengeProcessor.java:162)
	at org.apache.commons.httpclient.HttpMethodDirector.processWWWAuthChallenge(HttpMethodDirector.java:773)
	at org.apache.commons.httpclient.HttpMethodDirector.processAuthenticationResponse(HttpMethodDirector.java:747)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:221)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:333)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:562)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:523)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:501)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:405)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:362)
	at org.parosproxy.paros.core.scanner.HostProcess.obtainResponse(HostProcess.java:507)
	at org.parosproxy.paros.core.scanner.HostProcess.scanMessage(HostProcess.java:460)
	at org.parosproxy.paros.core.scanner.HostProcess.processPlugin(HostProcess.java:371)
	at org.parosproxy.paros.core.scanner.HostProcess.run(HostProcess.java:302)
	at java.lang.Thread.run(Unknown Source)
2018-07-16 18:50:03,583 [ZAP-ActiveScanner-0] WARN  VariantJSONQuery - Failed to parse the request body: Input is invalid JSON; does not start with '{' or '[', c=-1
java.lang.IllegalArgumentException: Input is invalid JSON; does not start with '{' or '[', c=-1
	at org.parosproxy.paros.core.scanner.VariantJSONQuery.parseObject(VariantJSONQuery.java:117)
	at org.parosproxy.paros.core.scanner.VariantJSONQuery.parseContent(VariantJSONQuery.java:61)
	at org.parosproxy.paros.core.scanner.VariantAbstractRPCQuery.setRequestContent(VariantAbstractRPCQuery.java:167)
	at org.parosproxy.paros.core.scanner.VariantAbstractRPCQuery.setMessage(VariantAbstractRPCQuery.java:51)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:161)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:380)
	at java.lang.Thread.run(Unknown Source)

**Additional context**
It could be I do not understand the NTLM method completely, however I have spent quite a while trying to configure the service and it seems with all configuration variants I keep receiving same response.

**Comment by avolna** [comment]
Additionaly, here is my logging configuration:
log4j.logger.org.parosproxy.paros=DEBUG
log4j.logger.org.zaproxy.zap=DEBUG
log4j.logger.org.apache.commons.httpclient=DEBUG
log4j.logger.httpclient.wire.header=DEBUG
log4j.logger.net.htmlparser.jericho=ERROR
Could I be missing something?

**Comment by kingthorin** [comment]
Do the out of order messages only appear when you're actively proxying browser activity through ZAP?

**Comment by avolna** [comment]
I have checked and it seems the error appears every now and then even when using browser through the proxy. Can you point out the possible problem with NTLM connection (misconfiguration or application error)?

**Comment by kingthorin** [comment]
I believe it has to do with the browser initiating requests for resource type files (css, js, images, etc), I've seen the log message in the past but never had an issue with any of the sites actually working properly.

**Comment by Edza** [comment]
Hi. I have this exact same problem, and after many hours of investigating I found this same out of order problem. @avolna Did you manage to find any solution?

**Comment by kingthorin** [comment]
@edza is there actually a problem? Are you unable to access the site?

**Comment by avolna** [comment]
@Edza unfortunately I did not manage to log in through OWASP Zap. I had same responses (OWASP received "unauthenticated" reply and just went to the next test) no matter which configuration I have tried. I ended up using another software and following it with manual tests. You may try to create NTLM authenticating proxy posted here as a workaround, however I did not try it myself as I was short on time:
https://techblog.mediaservice.net/2017/05/fiddler-ntlm-authentication-when-burp-suite-fails/

@kingthorin I am sorry, maybe the description of the bug was not precise - the 'out of order' messages was just my call on what could be the problem. As described later, my exact issue was not being able to perform the scan due to authentication issue:

>
>
> I see. Thank you. I still have issue with NTLM automatic scan, even though it now seems not to be related with the 'out of sequence' error. While using the browser through proxy everything works just fine, however the web scanner acts like explained in the first post (just sends a single request and after receiving challenge proceeds to the next test without actually authenticating). The site runs on HTTPS with NTLM configured. It's an AngularJS site if it makes any difference (I already have whole site crawled manually through browser proxy).

**Comment by kingthorin** [comment]
It would be nice to know if this is still happening with 2.12/the new networking core.

**Comment by thc202** [comment]
Will check (most likely not).
