### ISSUE TITLE
ConcurrentModificationException thrown in PassiveScanThread

### ISSUE THREAD

**Issue by KajanM** [zaproxy/zaproxy#4911]
**Describe the bug**
The following exception was logged when testing automatic authentication configuration.

`446250 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscan.PassiveScanThread  - Parser failed on record 1 from History table
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
at java.util.ArrayList$Itr.next(ArrayList.java:859)
at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:153)`

**To Reproduce**
I am unable to reproduce the bug using the same approach when it was thrown.

1. started zaproxy(develop branch) dev build in debug mode from eclipse
2. loaded the authenticationhelper-1.1.0 add-on
 - this add-on has a passive scan rule
 - `extensionPassiveScan.addPassiveScanner(getAutoConfigurationPassiveScanner());` not added through `ZapAddOn.xml`
 - the passive scan rule scans the response message to detect login page(in this scenario) and have some authentication auto configuration logic
3. opened firefox using `Launch Browser` option in ZAP and logged in to the proxied web application (bodgeit)
4. made some changes to the add-on
5. loaded the newly built add-on **without unloading the previous one or restarting zap**
 - `PassiveScanThread` may have had pending jobs, don't remember correctly, usually has pending jobs
6. created a new session in ZAP
7. opened firefox using `Launch Browser` option in ZAP and logged in to the proxied web application
8. above exception was logged in the console
9. the add-on completed its job as expected

**Expected behavior**
no such exception is thrown

**Errors from the zap.log file**
2018-08-07 21:33:30,025 [AWT-EventQueue-1] INFO  Control - Discard Session
2018-08-07 21:33:30,045 [AWT-EventQueue-1] INFO  Control - New Session
2018-08-07 21:33:30,047 [AWT-EventQueue-1] INFO  Control - Create and Open Untitled Db
2018-08-07 21:33:30,093 [AWT-EventQueue-1] INFO  ENGINE - dataFileCache commit start
2018-08-07 21:33:30,110 [AWT-EventQueue-1] INFO  ENGINE - dataFileCache commit end
2018-08-07 21:33:30,125 [AWT-EventQueue-1] INFO  ENGINE - Database closed
2018-08-07 21:33:30,245 [AWT-EventQueue-1] INFO  ENGINE - open start - state not modified
2018-08-07 21:33:30,331 [AWT-EventQueue-1] INFO  ENGINE - dataFileCache open start
2018-08-07 21:33:30,341 [AWT-EventQueue-1] INFO  ENGINE - dataFileCache open end
2018-08-07 21:33:38,084 [AWT-EventQueue-1] INFO  ExtensionAutoUpdate - Installing new addon authenticationhelper v1.1.0
2018-08-07 21:33:38,193 [AWT-EventQueue-1] INFO  ExtensionAutoUpdate - Finished installing new addon authenticationhelper v1.1.0
2018-08-07 21:33:48,285 [ZAP-PassiveScanner] WARN  PassiveScanThread - Passive Scan rule Wappalyzer Scanner (Tech Detection) took 12 seconds to scan https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/61.0.1/Firefox/20180704192850/Linux_x86_64-gcc3/en-US/release-cck-ubuntu/Linux%204.15.0-29-generic%20(GTK%203.22.30%2Clibpulse%2011.1.0)/canonical/1.0/1/1/new/ application/xml;charset=UTF-8 157054
**2018-08-07 21:33:48,287 [ZAP-PassiveScanner] ERROR PassiveScanThread - Parser failed on record 1 from History table
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:153)**
2018-08-07 21:33:48,454 [ZAP-PassiveScanner] DEBUG AutomaticAuthenticationConfigurer - Authentication method is not yet configured, scanning to configure one if possible, URI: http://192.168.56.101/bodgeit/login.jsp
2018-08-07 21:33:48,493 [ZAP-PassiveScanner] INFO  AutomaticAuthenticationConfigurer - Created new context, http://192.168.56.101/bodgeit
2018-08-07 21:33:48,613 [ZAP-PassiveScanner] DEBUG AutomaticAuthenticationConfigurer - Context(s) already defined for the URI: http://192.168.56.101/bodgeit/js/util.js
2018-08-07 21:33:48,613 [ZAP-PassiveScanner] DEBUG AutomaticAuthenticationConfigurer - AuthenticationMethod is not correctly configured for context: http://192.168.56.101/bodgeit

**Comment by thc202** [comment]
Thanks for raising the issue!
