### ISSUE TITLE
CacheableScanner: NumberFormatException

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4924]
**Describe the bug**
With a long max-age `Cache-Control: max-age=7776000,private` the CacheableScanner maythrow an NumberFormatException:
```
8079425 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscanrulesAlpha.CacheableScanner  - An error occurred while checking a URI for cacheability
java.lang.NumberFormatException: For input string: "7776000,private"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at org.zaproxy.zap.extension.pscanrulesAlpha.CacheableScanner.scanHttpResponseReceive(CacheableScanner.java:410)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:166)
```

**Software versions**
 - ZAP: DEV
 - Add-on: Passive Scan Rules Alpha 21
 - OS: Win7
 - Java: JDK 1.8.0_171

**Comment by psiinon** [comment]
Been meaning to raise this for a while - have seen it fail in other similar situations.

**Comment by kingthorin** [comment]
Fixed in: https://github.com/zaproxy/zap-extensions/pull/1774

**Comment by thc202** [comment]
Released in version 22 of Passive scanner rules (alpha) add-on.
