### ISSUE TITLE
CacheableScanner: DateParseException

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#4969]
**Describe the bug**
The CacheableScanner may throw a `DateParseException` when encountering a response with `Expires: 0`.
```
372120 [ZAP-PassiveScanner] ERROR org.zaproxy.zap.extension.pscanrulesAlpha.CacheableScanner  - An error occurred while checking a URI for cacheability
org.apache.commons.httpclient.util.DateParseException: Unable to parse the date 0
	at org.apache.commons.httpclient.util.DateUtil.parseDate(DateUtil.java:170)
	at org.apache.commons.httpclient.util.DateUtil.parseDate(DateUtil.java:94)
	at org.zaproxy.zap.extension.pscanrulesAlpha.CacheableScanner.scanHttpResponseReceive(CacheableScanner.java:470)
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:166)
```

**To Reproduce**
Passively scan content with response header such as:
```
HTTP/1.1 200 OK
Cache-Control: must-revalidate,private
Pragma: must-revalidate,no-cache
Content-Type: text/xml;charset=UTF-8
Expires: 0
Last-Modified: 4 Sep 2018 13:04:40 GMT
Server: Microsoft-IIS/10.0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Date: Tue, 04 Sep 2018 13:04:40 GMT
```

**Expected behavior**
Exception should be handled.

**Software versions**
 - ZAP: DEV
 - Add-on: Passive Scan Rules Alpha 23
 - OS: Win7
 - Java: 1.8.0_171

**Additional context**
Similar to: https://github.com/zaproxy/zaproxy/issues/4924

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zap-extensions/pull/1794
