### ISSUE TITLE
SAML add-on leads to errors with Java 9+

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5032]
By simply starting ZAP with Java 9+ the extension fails to initialise with:
```
15763 [ZAP-BootstrapGUI] ERROR org.parosproxy.paros.extension.ExtensionLoader  - Failed to initialise extension org.zaproxy.zap.extension.saml.SAMLExtension (from add-on [id=saml, version=7.0.0]), cause: ClassNotFoundException: 
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.zaproxy.zap.extension.saml.SAMLExtension.hook(SAMLExtension.java:43)
	at org.parosproxy.paros.extension.ExtensionLoader.hookAllExtension(ExtensionLoader.java:773)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:675)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:57)
	at org.parosproxy.paros.control.Control.init(Control.java:123)
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:299)
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:257)
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:70)
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:200)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:256)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
```

Add-on:
SAML Extension, version 7 (and older).

**Comment by thc202** [comment]
Same problem as #4214.

**Comment by thc202** [comment]
This will be addressed during the migration to Gradle (to avoid pushing more binaries to the repo), by depending on (and thus bundling) the required library.

**Comment by thc202** [comment]
Done in zaproxy/zap-extensions#1974.
