### ISSUE TITLE
Custom Vectors don't work properly if plugin ID is injected in the message

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5060]
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/oHT-BMHwyM0/discussion

Steps to reproduce the issue:
1. Start ZAP and proxy a POST request;
2. Enable the option "Active Scan" > "Inject plugin ID in header for all active scan requests";
3. Attack the POST request with a Custom Vector in the request body;
4. Note that the payload is not injected in the selected position.

Also, depending on the position selected it might lead to exceptions, e.g.:
```
[ZAP-ActiveScanner-0] ERROR org.parosproxy.paros.core.scanner.VariantUserDefined  - 
org.parosproxy.paros.network.HttpMalformedHeaderException
	at org.parosproxy.paros.network.HttpHeader.setMessage(HttpHeader.java:183)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:256)
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:282)
	at org.parosproxy.paros.core.scanner.VariantUserDefined.setParameter(VariantUserDefined.java:90)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.setParameter(AbstractAppParamPlugin.java:286)
	at org.zaproxy.zap.extension.ascanrules.TestCrossSiteScriptV2.scan(TestCrossSiteScriptV2.java:168)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:272)
	at org.zaproxy.zap.extension.ascanrules.TestCrossSiteScriptV2.scan(TestCrossSiteScriptV2.java:113)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(AbstractAppParamPlugin.java:200)
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:171)
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:341)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

ZAP
Version 2.7.0 (and older).

**Comment by thc202** [comment]
Fixed in #5092.

**Comment by kingthorin** [comment]
Fixed in https://github.com/zaproxy/zaproxy/pull/5092#issuecomment-434260489

**Comment by kingthorin** [comment]
Hahahahaha .... great minds think alike 😀
