### ISSUE TITLE
OUTOFSCOPE regex parsing example throws errors

### ISSUE THREAD

**Issue by jhoffmann** [zaproxy/zaproxy#5075]
**Describe the bug**

When duplicating the OUTOFSCOPE example `* OUTOFSCOPE *.js` from the documentation at https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan#configuration-file, I get the following error:
```
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 451, in <module>
    main(sys.argv[1:])
  File "/zap/zap-baseline.py", line 237, in main
    load_config(f, config_dict, config_msg, out_of_scope_dict)
  File "/zap/zap_common.py", line 84, in _wrap
    return_data = func(*args_list, **kwargs)
  File "/zap/zap_common.py", line 137, in load_config
    out_of_scope_dict[plugin_id].append(re.compile(optional))
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```
**Software versions**
 - ZAP: owasp/zap2docker-stable | weekly

**Additional context**

Switching to:

```
10038	OUTOFSCOPE	.*\.[js|css]
```

Appears to work.

**Comment by thc202** [comment]
Thanks! Fixed in https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan/_compare/d5a6f84%5E...d5a6f84
