### ISSUE TITLE
cannot reach local server via IPv6

### ISSUE THREAD

**Issue by fabianfrz** [zaproxy/zaproxy#5083]
I cannot reach locally running webserver using ZAP due to an IO errer because the wrong IP version is used.

**To Reproduce**

This popup is what you get when you use the resend interface
![grafik](https://user-images.githubusercontent.com/3713914/47588488-92f19e80-d966-11e8-9a02-f00c0b5832c4.png)

This is how it looks in the history (when pointing the browser to it):
![grafik](https://user-images.githubusercontent.com/3713914/47588595-f8de2600-d966-11e8-8812-bbdb44f295c2.png)

Output of `ss -ltpn`

![grafik](https://user-images.githubusercontent.com/3713914/47588669-3c389480-d967-11e8-85b9-f000fe961400.png)

**Expected behavior**
ZAP should connect to localhost (::1)

**Software versions**
 - ZAP: 2.7.0
 - OS: Arch Linux
 - Java: openjdk version "1.8.0_181"
 - Browser: Firefox 62.0.2

**Errors from the zap.log file**

Manual:
```
2018-10-26 21:29:53,774 WARN  ManualRequestEditorDialog - IO error in sending request: class java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)
java.io.IOException: IO error in sending request: class java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)
	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:133)
	at org.parosproxy.paros.extension.manualrequest.ManualRequestEditorDialog$3.run(ManualRequestEditorDialog.java:211)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:333)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:564)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:523)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:501)
	at org.parosproxy.paros.network.HttpSender.sendAndReceiveImpl(HttpSender.java:901)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:869)
	at org.parosproxy.paros.extension.manualrequest.http.impl.HttpPanelSender.handleSendMessage(HttpPanelSender.java:95)
	... 2 more
```

Normal proxy:
```
ZAP Error [java.net.ConnectException]: Verbindungsaufbau abgelehnt (Connection refused)

Stack Trace:
java.net.ConnectException: Verbindungsaufbau abgelehnt (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:333)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:564)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:523)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:501)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:405)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:362)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:509)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:317)
	at java.lang.Thread.run(Thread.java:748)
```

**Additional context**

* Maybe related to #3705
* Found while coding opnsense/plugins#930 using opnsense/ui_devtools

**Comment by kingthorin** [comment]
Merging into https://github.com/zaproxy/zaproxy/issues/3705
