### ISSUE TITLE
Attack button disabled when try to attack target returns 'timeout'

### ISSUE THREAD

**Issue by jooneyp** [zaproxy/zaproxy#5131]
**Describe the bug**
Attacking to server causing 'timeout' makes Attack button not available, remaining Stop button clickable. It will not fixed unless restarting ZAP. 

**To Reproduce**
1. Type the server causing timeout on 'URL to attack' textbox.
2. Click Attack
3. Failed to attack because of 'Connection timed out', but Stop button remains clickable, Attack button NOT clickable.
4. When I click Stop button, both buttons are blocked.
5. Won't be fixed until restart the whole program

**Expected behavior**
After the failure of Attack, attack button should be clickable.

**Screenshots**
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/4610410/49441131-f9d96180-f808-11e8-85e2-35e09483ed9c.png">

**Software versions**
 - ZAP: 2.7.0
 - Add-on: None
 - OS: macOS
 - Java: java 9.0.4
 - Browser: Not available

**Errors from the zap.log file**
Not available

**Additional context**
Not available

**Comment by kingthorin** [comment]
Did you change the target after the timeout?

**Comment by jooneyp** [comment]
No, nothing touched after timeout.

**Comment by jooneyp** [comment]
FYI, test.yona.naverlabs.com is in private zone in my company. Never mind if you cannot get same result for that domain.

**Comment by kingthorin** [comment]
I'm unable to re-create. If I try to attack something that isn't routable (ex: http://10.255.255.1) I get a timeout: `The host did not accept the connection within timeout of 20000 ms` but the attack button comes back.

Could you copy the text from the Output tab when it fails? It should be something like:
```
The host did not accept the connection within timeout of 20000 ms
org.apache.commons.httpclient.ConnectTimeoutException: The host did not accept the connection within timeout of 20000 ms
	at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory.createSocket(ControllerThreadSocketFactory.java:97)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:128)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:449)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:201)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:360)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:592)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:551)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:529)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:518)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:432)
	at org.zaproxy.zap.extension.quickstart.AttackThread.accessNode(AttackThread.java:183)
	at org.zaproxy.zap.extension.quickstart.AttackThread.run(AttackThread.java:73)
```
(It may or may not have a timestamp depending on your settings)

**Comment by mac25** [comment]
nothing comes to output tab my side !! not sure

**Comment by kingthorin** [comment]
Could one of you try it using the latest weekly?

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/wiki/Downloads#zap-weekly

**Comment by jooneyp** [comment]
cannot launch latest weekly release, on macOS
```
0 [main] INFO org.zaproxy.zap.GuiBootstrap  - OWASP ZAP D-2018-12-06 started 07/12/2018, 11:09:47 with home /Users/Dennis/Library/Application Support/ZAP_D/
441 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP$UncaughtExceptionLogger  - Exception in thread "AWT-EventQueue-0"
java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at org.zaproxy.zap.GuiBootstrap.setupLookAndFeel(GuiBootstrap.java:366)
	at org.zaproxy.zap.GuiBootstrap.startImpl(GuiBootstrap.java:120)
	at org.zaproxy.zap.GuiBootstrap.access$000(GuiBootstrap.java:70)
	at org.zaproxy.zap.GuiBootstrap$1.run(GuiBootstrap.java:109)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
```

**Comment by kingthorin** [comment]
Doh, that's a separate issue https://github.com/zaproxy/zaproxy/issues/4669 :disappointed:

**Comment by thc202** [comment]
You need to run the weekly with Java 8 (the main release includes Java 8 that's why it works by default.)

**Comment by thc202** [comment]
btw, the log file will have the errors in the main release, no need to use the weekly for that.

**Comment by kingthorin** [comment]
@jooneyp are you able to try a weekly w/ java 8?

**Comment by jooneyp** [comment]
Tried weekly(2019-03-11) w/ java 1.8

<img width="2487" alt="image" src="https://user-images.githubusercontent.com/4610410/54328685-301d4d00-4652-11e9-9705-e0f88ecce989.png">

It first seemed same issue is here, but 20secs later

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/4610410/54328758-6c50ad80-4652-11e9-82b6-6ebe43af6461.png">

**Comment by kingthorin** [comment]
Great, thanks for letting us know.
