### ISSUE TITLE
Spieder scanning is killed by something.

### ISSUE THREAD

**Issue by shogosanz** [zaproxy/zaproxy#5193]
**Describe the bug**
Spieder scanning is killed by something.

**To Reproduce**
1. execute zap-baseline.py 
2. Killed while Spider scanning.
**Expected behavior**
Why it kills this proccess?

**Screenshots**
```
sudo docker run -it --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py -d -t https://target -J report.json
```
・
・
・
```
2019-01-18 05:45:28,301 Spider progress %: 41
2019-01-18 05:45:33,321 Spider progress %: 44
2019-01-18 05:45:38,358 Spider progress %: 47
2019-01-18 05:45:43,408 Spider progress %: 48
2019-01-18 05:45:48,474 Spider progress %: 50
2019-01-18 05:45:53,648 Spider progress %: 53
2019-01-18 05:45:58,685 Spider progress %: 55
2019-01-18 05:46:03,716 Spider progress %: 56
2019-01-18 05:46:08,747 Spider progress %: 58
2019-01-18 05:46:13,767 Spider progress %: 59
Killed
ERROR HTTPConnectionPool(host='localhost', port=50004): Max retries exceeded with url: http://zap/JSON/spider/view/status/?scanId=0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f85175cd890>: Failed to establish a new connection: [Errno 111] Connection refused',)))
2019-01-18 05:46:18,778 I/O error: HTTPConnectionPool(host='localhost', port=50004): Max retries exceeded with url: http://zap/JSON/spider/view/status/?scanId=0 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f85175cd890>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 324, in main
    zap_spider(zap, target)
  File "/zap/zap_common.py", line 84, in _wrap
    return_data = func(*args_list, **kwargs)
  File "/zap/zap_common.py", line 372, in zap_spider
    while (int(zap.spider.status(spider_scan_id)) < 100):
  File "/usr/local/lib/python2.7/dist-packages/zapv2/spider.py", line 34, in status
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'spider/view/status/', params)))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
```
**Software versions**
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
```
owasp/zap2docker-weekly     latest              ed277303e885        2 months ago        1.77GB
```

**Errors from the zap.log file**
`$ sudo find / -name "zap.log"`
None

**Comment by shogosanz** [comment]
oh sorry
```
kernel: [11490723.508648] Out of memory: Kill process 15181 (java) score 24 or sacrifice child
kernel: [11490723.515748] Killed process 15181 (java) total-vm:2148276kB, anon-rss:96244kB, file-rss:17624kB
```

**Comment by psiinon** [comment]
Np, thanks for letting us know.
