### ISSUE TITLE
Updating the Version of the Attack Surface Detector

### ISSUE THREAD

**Issue by matthewD-AVI** [zaproxy/zaproxy#5229]
**Add-on repo**
https://github.com/secdec/attack-surface-detector-zap

**Your contact details**
[matthew.deletto@securedecisions.com](mailto:matthew.deletto@securedecisions.com)

**Are you one of the authors**
Yes

**Licence**
https://github.com/secdec/attack-surface-detector-zap/blob/master/LICENSE

**Build instructions**
Build instructions are on the Wiki
https://github.com/secdec/attack-surface-detector-zap/wiki

**Link to more information**
Wiki: https://github.com/secdec/attack-surface-detector-zap/wiki
OWASP project page: https://www.owasp.org/index.php/OWASP_Attack_Surface_Detector_Project

**Twitter handle for tool or author(s)**
@secdec

**Promote to Beta or Release?**
Updating the existing Alpha plugin

**Comment by kingthorin** [comment]
I tested `1.1.3` with `ZAP_D-2019-03-04 this morning.
https://github.com/secdec/attack-surface-detector-zap/releases/tag/1.1.3

It seems to be functional.

I did encounter one weird thing:
- Scrolling the panel with the mouse wheel was REALLY slow, but grabbing the slider at the side and moving it was fine (or using the up/down buttons on the scrollbar). Other panes like the Sites Tree scroll fine with the mouse wheel.

It seems many of the new UI strings are hard coded not leveraging `messages.properties`. But that shouldn't be a blocker.

**Comment by kingthorin** [comment]
I spoke too soon, only did positive test case. There’s an unhandled exception when spider is selected but target is unreachable.

**Comment by kingthorin** [comment]
```trace
62170 [AWT-EventQueue-0] INFO com.denimgroup.threadfix.framework.engine.full.GeneratorBasedEndpointDatabase  - Done buil
ding mappings. Static keys: 19, dynamic keys: 21
66198 [Thread-18] ERROR com.securedecisions.attacksurfacedetector.plugin.zap.action.AttackThread  - Connection refused:
connect
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory
.java:125)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttp
ConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:449)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:201)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:360)
        at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:592)
        at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:551)
        at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:529)
        at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:518)
        at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:432)
        at com.securedecisions.attacksurfacedetector.plugin.zap.action.AttackThread.sendAndProcess(AttackThread.java:247)
        at com.securedecisions.attacksurfacedetector.plugin.zap.action.AttackThread.accessNode(AttackThread.java:235)
        at com.securedecisions.attacksurfacedetector.plugin.zap.action.AttackThread.run(AttackThread.java:85)
66243 [Thread-18] ERROR com.securedecisions.attacksurfacedetector.plugin.zap.action.AttackThread  - Failed to access URL http://localhost:8082/ 66245 [Thread-18] INFO com.securedecisions.attacksurfacedetector.plugin.zap.action.LocalEndpointsButton  - Status is FAILED
```

**Comment by kingthorin** [comment]
Also the addon manifest is out of sync. Current version is 1.1.3 but ZapAddOn.xml still says 1.1.2.

**Comment by matthewD-AVI** [comment]
Published a new release with kingthorin's changes

**Comment by kingthorin** [comment]
Tested:
https://github.com/secdec/attack-surface-detector-zap/releases/tag/1.1.4

Works as expected.

**Comment by thc202** [comment]
Closing, the new version is now available in the marketplace.
