### ISSUE TITLE
OpenAPI add-on is missing a dependency

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#5262]
Steps to reproduce the issue:
1. Run ZAP with OpenAPI Support add-on installed.
2. Import the API definition used in the tests: `PetStore_1_2_defn.json`.
3. Note that nothing happens, in the log there's an exception:
```
Exception in thread "ZAP-Import-OpenAPI-1"
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at com.github.fge.jackson.jsonpointer.JsonPointer.<clinit>(JsonPointer.java:46)
	at io.swagger.transform.util.MutableJsonTree.<init>(MutableJsonTree.java:36)
	at io.swagger.transform.migrate.V11ResourceListingMigrator.migrate(V11ResourceListingMigrator.java:81)
	at io.swagger.transform.migrate.SwaggerJsonMigrator.migrate(SwaggerJsonMigrator.java:19)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:195)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:107)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:101)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:76)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$3.run(ExtensionOpenApi.java:218)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:269)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
```

Remarks:
The test that imports the API definition passes because the build is (wrongly) using dependencies from other add-on (Selenium).

Add-on:
OpenAPI Support version 12 (and older)

**Comment by thc202** [comment]
This will be addressed during the migration to Gradle (to avoid pushing more binaries to the repo), by including the dependencies of the used libraries.

**Comment by thc202** [comment]
Done in zaproxy/zap-extensions#1974.
