### ISSUE TITLE
Improve error message when failed to connect to outgoing proxy

### ISSUE THREAD

**Issue by osandadeshan** [zaproxy/zaproxy#5304]
**Describe the bug**
When trying do do a quick scan, "Failed to attack the URL: host not found" error will be visible

**To Reproduce**
1. Open Zap 2.7.0
2. Input http://newtours.demoaut.com/ as the URL to attack
3. Click on Attack button
4. See error "Failed to attack the URL: host not found"

**Expected behavior**
Should be able to do a quick atack

**Screenshots**
![image](https://user-images.githubusercontent.com/9147189/55539861-4feae280-56df-11e9-99e0-d5b6a9451939.png)

**Software versions**
 - ZAP: 2.7.0
 - OS: Windows 10 64bit
 - Java: openjdk version "1.8.0_171"
 - Browser: Chrome 73

**Comment by kingthorin** [comment]
Can you access the target in a browser?

**Comment by osandadeshan** [comment]
@kingthorin 
You mean Launch browser button on the below. Then it will open a chrome instance and "Explore your application with ZAP" will be visible on the html body

**Comment by kingthorin** [comment]
I mean when you encounter that error are you able to access the target at all? The message seems to indicate a DNS issue.

**Comment by osandadeshan** [comment]
No I have able to access the web page http://newtours.demoaut.com/
Also I used another web sites as well. But not working

**Comment by kingthorin** [comment]
Ok proxy your browser through ZAP and let us know if that works.

**Comment by osandadeshan** [comment]
@kingthorin 
I have added manual proxy to firefox and when I go to the URL this shows in the web page body
`ZAP Error [java.net.UnknownHostException]: Default

Stack Trace:
java.net.UnknownHostException: Default
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:286)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:727)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:447)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:199)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:333)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:564)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:523)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:501)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:405)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:362)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:509)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:303)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by kingthorin** [comment]
You tried to navigate to "Default" after setting the proxy... Unless you have a hosts file entry or some obscure DNS entry that's not going to work.

**Comment by MrARM** [comment]
I'm having no issues finding your site, I'm running ZAP 2.7.0 on MacOS 10.14.4
![image](https://user-images.githubusercontent.com/8205849/55575852-7efc5680-56d5-11e9-9932-5ba1978a36cd.png)

**Comment by osandadeshan** [comment]
@MrARM But in windows I am facing the issue

**Comment by kingthorin** [comment]
https://groups.google.com/forum/m/#!topic/zaproxy-users/2YAd-XUXRWw

**Comment by thc202** [comment]
We could use this to improve the error message though, to mention that the problem happened while connecting to the outgoing proxy not the target.

**Comment by kingthorin** [comment]
Re-open and label as enhancement?

**Comment by thc202** [comment]
Tweaked.

**Comment by kingthorin** [comment]
How's this look?
![image](https://user-images.githubusercontent.com/7570458/55747413-2f39ca00-5a0a-11e9-9170-7367b9844d7c.png)
