### ISSUE TITLE
 Installing new addon browserView v5.0.0 error/ cant find javaFX or jre/jdk

### ISSUE THREAD

**Issue by ReK2Fernandez** [zaproxy/zaproxy#5327]
I am trying to get this to work.. but it does not find my java? even do zap does..
```
 archlinux-java status
Available Java environments:
  java-10-openjdk
  java-11-openjdk (default)
  java-12-jdk
  java-7-openjdk/jre
  java-8-openjdk
```
I switch between different versions and official sun 12-jdk with no luck
![zap-bug-html-render](https://user-images.githubusercontent.com/5316229/56845055-f4d88580-686f-11e9-83d1-7c953dacbc21.png)

thanks! sometimes I wish this was made in GO instead of java.. so many problems always..

**Comment by ReK2Fernandez** [comment]
more info:
```
107669 [ZAP-DownloadInstaller] WARN org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView  - Unable to use JavaFX:
java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView.isJavaFxAvailable(ExtensionHttpPanelBrowserView.java:92)
	at org.zaproxy.zap.extension.browserView.ExtensionHttpPanelBrowserView.hook(ExtensionHttpPanelBrowserView.java:74)
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:769)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensionImpl(AddOnInstaller.java:280)
	at org.zaproxy.zap.control.AddOnInstaller.installAddOnExtensions(AddOnInstaller.java:261)
	at org.zaproxy.zap.control.AddOnInstaller.install(AddOnInstaller.java:92)
	at org.zaproxy.zap.control.AddOnLoader.addAddOnImpl(AddOnLoader.java:435)
	at org.zaproxy.zap.control.AddOnLoader.addAddon(AddOnLoader.java:408)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1148)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.lambda$installNewExtensionsImpl$0(ExtensionAutoUpdate.java:592)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensionsImpl(ExtensionAutoUpdate.java:590)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(ExtensionAutoUpdate.java:537)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(ExtensionAutoUpdate.java:528)
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:269)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more
```
hope this helps...

**Comment by ReK2Fernandez** [comment]
I installed sun java 10 and switched arch to use that one and this works... still I was not working under sun java 10 jdk....  
```
archlinux-java status
Available Java environments:
  java-10-jre/jre
  java-10-openjdk
  java-11-openjdk
  java-12-jdk (default)
  java-7-openjdk/jre
  java-8-openjdk
```
```
sudo archlinux-java set java-10-jre/jre
```
```
archlinux-java status
Available Java environments:
  java-10-jre/jre (default)
  java-10-openjdk
  java-11-openjdk
  java-12-jdk
  java-7-openjdk/jre
  java-8-openjdk
```

**Comment by kingthorin** [comment]
Here's a recent thread thatbmihht help: https://groups.google.com/forum/?nomobile=true#!topic/zaproxy-users/uAuHfK1v2vA

**Comment by thc202** [comment]
> I though that 10-11-12 as long they were the SUN version not openjdk they all include javaFX...

That's no longer the case, JavaFX is not bundled in newer versions, you have to install it separately.

**Comment by kingthorin** [comment]
@ReK2Fernandez did you get OpenFX installed and address the issue?

**Comment by kingthorin** [comment]
No further user feedback, closing.
