### ISSUE TITLE
Bad Addons - Need descriptive message(s)

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5334]
I encountered this on a Kali VM this morning. I'm not sure what kind of weirdness I may have done to break them (start an update and then kill the VM while it was writing etc):

```
17730 [ZAP-cfu] WARN org.zaproxy.zap.control.AddOnCollection  - Failed to create add-on for ascanrulesBeta
java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1527)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1341)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1435)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1266)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.zaproxy.zap.control.AddOn.loadManifestFile(AddOn.java:350)
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:428)
	at org.zaproxy.zap.control.AddOnCollection.load(AddOnCollection.java:125)
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:53)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$8.run(ExtensionAutoUpdate.java:958)
17786 [ZAP-cfu] WARN org.zaproxy.zap.control.AddOnCollection  - Failed to create add-on for jxbrowserlinux64
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1527)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1428)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1435)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1266)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.zaproxy.zap.control.AddOn.loadManifestFile(AddOn.java:350)
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:428)
	at org.zaproxy.zap.control.AddOnCollection.load(AddOnCollection.java:125)
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:53)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$8.run(ExtensionAutoUpdate.java:958)
79985 [Thread-8] INFO org.zaproxy.zap.extension.proxies.ExtensionProxies  - Stopping alt proxy server: localhost:9999
```

I removed ascanrulesBeta via the Marketplace, but now it doesn't show as either installed or available for installation :disappointed:  The exception doesn't display the path to the bad archive either :cry: 

ZAP: `2.7.0`
Java:
```
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-2, mixed mode)
```

**Comment by kingthorin** [comment]
Maybe this was already addressed via https://github.com/zaproxy/zaproxy/pull/5158 ?

**Comment by kingthorin** [comment]
I’ll grab the file I renamed and test it against a weekly on mon or tues.

**Comment by thc202** [comment]
I don't think that will fix it, the exception message would be the same.

Isn't the message descriptive enough? From the message it's clear that the ZIP file is corrupt.

The other points need to be addressed in any case (missing file path and not be able to un/install).

**Comment by kingthorin** [comment]
The Exception is specific enough, some additional details would just help the user without them having to dig for details/solution.

(I'll update the issue subject.)

**Comment by kingthorin** [comment]
I did try the two broken addons with weekly `2019-04-29`. In the weekly the path to the offending addon is actually displayed in the log (:+1:) and both come up as "zip file is empty" being the cause (whereas in 2.7 they had slightly different causes and no path).

I'm not sure that the whole stack trace is necessary, however, the weekly messaging is better than 2.7s.

<details>
<summary>Weekly 2019-04-29 Logs</summary>

```
2583 [ZAP-BootstrapGUI] WARN org.zaproxy.zap.control.AddOnCollection  - Failed to create add-on for ascanrulesBeta
java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1527)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1341)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1435)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1266)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.zaproxy.zap.control.AddOn.loadManifestFile(AddOn.java:530)
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:614)
	at org.zaproxy.zap.control.AddOnCollection.load(AddOnCollection.java:125)
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:53)
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:48)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getPreviousVersionInfo(ExtensionAutoUpdate.java:975)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.initialize(ExtensionAutoUpdate.java:169)
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.<init>(ExtensionAutoUpdate.java:157)
	at org.zaproxy.zap.control.CoreFunctionality.createExtensions(CoreFunctionality.java:80)
	at org.zaproxy.zap.control.CoreFunctionality.getBuiltInExtensions(CoreFunctionality.java:60)
	at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:98)
	at org.parosproxy.paros.control.Control.addExtension(Control.java:163)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:53)
	at org.parosproxy.paros.control.Control.init(Control.java:126)
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:312)
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:264)
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:70)
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:207)
	at java.base/java.lang.Thread.run(Thread.java:844)
3315 [ZAP-BootstrapGUI] WARN org.zaproxy.zap.control.AddOn  - Invalid add-on: /root/.ZAP_D/plugin/jxbrowserlinux64-alpha-7.zap
org.zaproxy.zap.control.AddOn$InvalidAddOnException: zip file is empty
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:515)
	at org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:453)
	at org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:175)
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:150)
	at org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:154)
	at org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:69)
	at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:100)
	at org.parosproxy.paros.control.Control.addExtension(Control.java:163)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:53)
	at org.parosproxy.paros.control.Control.init(Control.java:126)
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:312)
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:264)
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:70)
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:207)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1527)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1341)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1435)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1266)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:422)
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:513)
	... 14 more
3318 [ZAP-BootstrapGUI] WARN org.zaproxy.zap.control.AddOn  - Invalid add-on: /root/.ZAP_D/plugin/ascanrulesBeta-beta-24.zap
org.zaproxy.zap.control.AddOn$InvalidAddOnException: zip file is empty
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:515)
	at org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:453)
	at org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:175)
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:150)
	at org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:154)
	at org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:69)
	at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:100)
	at org.parosproxy.paros.control.Control.addExtension(Control.java:163)
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:53)
	at org.parosproxy.paros.control.Control.init(Control.java:126)
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:312)
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:264)
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:70)
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:207)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1527)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1341)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1435)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1266)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:845)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:245)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:175)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:189)
	at org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:422)
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:513)
	... 14 more
```

</details>

**Comment by thc202** [comment]
Agreed, the stack trace is unnecessary and we should suppress the warning when loading the local `AddOnCollection` (better to just read them once though).
