### ISSUE TITLE
GtkNativeMainLoopThread

### ISSUE THREAD

**Issue by eb0zavrik** [zaproxy/zaproxy#5402]
Kali linux (full update)
ZAP 2.7.0
Load on the start freezes.
Error from log:
2019-06-07 14:47:23,026 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionHttpPanelBrowserView
2019-06-07 14:47:23,355 [GtkNativeMainLoopThread] ERROR ZAP$UncaughtExceptionLogger - Exception in thread "GtkNativeMainLoopThread"
java.lang.UnsatisfiedLinkError: com.sun.glass.ui.gtk.GtkApplication._init(J)V
	at com.sun.glass.ui.gtk.GtkApplication._init(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.init(GtkApplication.java:55)
	at com.sun.glass.ui.gtk.GtkApplication.access$000(GtkApplication.java:17)
	at com.sun.glass.ui.gtk.GtkApplication$3$1.run(GtkApplication.java:88)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-06-07 14:47:23,535 [ZAP-Jython-EngineLoader] INFO  ExtensionJython - Jython engine loaded.

**Comment by thc202** [comment]
Could you provide a thread dump when that happens? e.g `kill -3 <zap-pid>` to output the thread dump.
The GTK exception seems unrelated to the hang.

I'd also suggest using/trying 2.8.0 released recently.

**Comment by kingthorin** [comment]
@eb0zavrik are you able to provide further details or use an up-to-date version?

**Comment by kingthorin** [comment]
Closing due to lack of feedback.
