### ISSUE TITLE
Connecting to ZAP Docker via Java API fails

### ISSUE THREAD

**Issue by SyCode7** [zaproxy/zaproxy#5418]
**Describe the bug**
I want to run send scanning requesting to ZAP using the openapi addon. Therefore, I run the stable image command together with addoninstall openapi. After running successfully, I send a scan request but it fails with errors.
**To Reproduce**
1. `docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true -addoninstall openapi
`
2. run an application that has  openapi implemented i.e. advertises `swagger.json` in the url.
3. Scanning request fails
4. See error:

```
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)
        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:449)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:201)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:398)
        at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:633)
        at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:589)
        at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:565)
        at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:553)
        at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:458)
        at org.zaproxy.zap.extension.openapi.network.Requestor.getResponseBody(Requestor.java:95)
        at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinition(ExtensionOpenApi.java:172)
        at org.zaproxy.zap.extension.openapi.OpenApiAPI.handleApiAction(OpenApiAPI.java:95)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:499)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
        at java.lang.Thread.run(Thread.java:748)
240645 [ZAP-ProxyThread-38] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/xml/openapi/action/importUrl/] from [172.17.0.1]:
Provided parameter has illegal or unrecognized value (illegal_parameter) : url
        at org.zaproxy.zap.extension.openapi.OpenApiAPI.handleApiAction(OpenApiAPI.java:105)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:499)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
        at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
The scan should run successfully, this works well with the normal ZAP installation.
**Screenshots**

**Software versions**
 - ZAP: [2.8]
 - Add-on: Name and version [openapi, v12.0.0]
 - OS: [Windows 10]
 - Java: [e.g. java "1.8.0_144"]

**Comment by kingthorin** [comment]
Your steps are incomplete. 
The important part of the exception is 
`240645 [ZAP-ProxyThread-38] WARN org.zaproxy.zap.extension.api.API  - Bad request to API endpoint [/xml/openapi/action/importUrl/] from [172.17.0.1]:
Provided parameter has illegal or unrecognized value (illegal_parameter) : url`

**Comment by SyCode7** [comment]
I will be grateful if you can provide some guidance on the missing steps.

**Comment by kingthorin** [comment]
With steps 2 and 3 you haven’t provided complete details, so we can’t possibly know what might have gone wrong.

**Comment by SyCode7** [comment]
@kingthorin , you are correct. I skipped a proper description of my scenario. I will expatiate below:
1. use the ZAP docker image to start ZAP and install the openapi addon : `docker run -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true -addoninstall openapi`
2. Since I am using the ZAP Java API, I have implemented REST scanning as described in this [ZAP blog](https://zaproxy.blogspot.com/2017/04/exploring-apis-with-zap.html).
3. The Java API sends a scanning request against the exposed ZAP endpoint (localhost:8080). See snippet of Java implementation:

`Map<String, String> map = new HashMap<>();`
`map.put("url", swaggerUrl);`
`ApiResponse openApiResp = zapClient.callApi("openapi", "action", "importUrl", map)`

4. Normally, the above step runs well with the normal ZAP installation.

**Comment by thc202** [comment]
ZAP is failing to access the target from the Docker container `Connection refused (Connection refused)`, I guess Windows (or whatever) is blocking the connection (assuming is reachable).

**Comment by SyCode7** [comment]
**Update:**  I just tried also with a public external application on this endpoint `https://petstore.swagger.io/v2/swagger.json` and it works fine. Could the issue be that the ZAP docker image cannot reach applications on the same host?

**Comment by thc202** [comment]
It can but you need to use other address: https://github.com/zaproxy/zaproxy/wiki/Docker#scanning-an-app-running-on-the-host-os

**Comment by SyCode7** [comment]
Do you have any idea of how I can do that on a windows host ? The recommended command :
`$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)` 

does not work in windows. There is no docker0 on windows, infact I have the following error:

`ip : The term 'ip' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
`At line:1 char:3
+ $(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f  ...
+   ~~
+ CategoryInfo          : ObjectNotFound: (ip:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException`

**Comment by thc202** [comment]
The following should give the host IP address `docker network inspect bridge --format="{{range .IPAM.Config}}{{.Gateway}}{{end}}"`.

**Comment by SyCode7** [comment]
@thc202 , unfortuntely this does not resolve the problem. I realized that the ip address from the command is that of the gateway, and still it does not work.

**Comment by thc202** [comment]
Same error? Might worth checking that the host is not blocking access from the Docker addresses. Also, that the target application is listening on all addresses.

**Comment by kingthorin** [comment]
@SyCode7 we’re you able to check and verify that there isn’t a host firewall or something blocking access from the docker addresses and also that the target app is listening on all interfaces?

**Comment by kingthorin** [comment]
No follow-up from the requestor in months, closing.
