### ISSUE TITLE
AddOnLoaderUtils  error 

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#5443]
**Describe the bug**
I am not sure if this one is expected
```
17:07:41 
17:07:41 12457 [ZAP-ProxyThread-23] ERROR org.zaproxy.zap.control.AddOnLoaderUtils  - Failed to initialise: org.zaproxy.zap.extension.soap.SOAPActionSpoofingActiveScanner
17:07:41 java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException
17:07:41 	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
17:07:41 	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
17:07:41 	at java.base/java.lang.Class.getConstructor0(Class.java:3343)
17:07:41 	at java.base/java.lang.Class.getConstructor(Class.java:2152)
17:07:41 	at org.zaproxy.zap.control.AddOnLoaderUtils.loadAndInstantiateClassImpl(AddOnLoaderUtils.java:114)
17:07:41 	at org.zaproxy.zap.control.AddOnLoaderUtils.loadDeclaredClasses(AddOnLoaderUtils.java:153)
17:07:41 	at org.zaproxy.zap.control.AddOnLoaderUtils.getActiveScanRules(AddOnLoaderUtils.java:179)
17:07:41 	at org.zaproxy.zap.control.AddOnLoader.getActiveScanRules(AddOnLoader.java:829)
17:07:41 	at org.parosproxy.paros.core.scanner.PluginFactory.init(PluginFactory.java:108)
17:07:41 	at org.parosproxy.paros.core.scanner.PluginFactory.initPlugins(PluginFactory.java:100)
17:07:41 	at org.parosproxy.paros.core.scanner.PluginFactory.getLoadedPlugins(PluginFactory.java:140)
17:07:41 	at org.parosproxy.paros.core.scanner.PluginFactory.loadAllPlugin(PluginFactory.java:406)
17:07:41 	at org.zaproxy.zap.extension.ascan.ScanPolicy.<init>(ScanPolicy.java:31)
17:07:41 	at org.zaproxy.zap.extension.ascan.PolicyManager.loadPolicy(PolicyManager.java:142)
17:07:41 	at org.zaproxy.zap.extension.ascan.PolicyManager.loadPolicy(PolicyManager.java:129)
17:07:41 	at org.zaproxy.zap.extension.ascan.PolicyManager.getDefaultScanPolicy(PolicyManager.java:205)
17:07:41 	at org.zaproxy.zap.extension.ascan.ActiveScanController.startScan(ActiveScanController.java:161)
17:07:41 	at org.zaproxy.zap.extension.ascan.ExtensionActiveScan.startScan(ExtensionActiveScan.java:274)
17:07:41 	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.scanURL(ActiveScanAPI.java:811)
17:07:41 	at org.zaproxy.zap.extension.ascan.ActiveScanAPI.handleApiAction(ActiveScanAPI.java:290)
17:07:41 	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:449)
17:07:41 	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:463)
17:07:41 	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:320)
17:07:41 	at java.base/java.lang.Thread.run(Thread.java:834)
17:07:41 Caused by: java.lang.ClassNotFoundException
17:07:41 	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:269)
17:07:41 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
17:07:41 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
17:07:41 	... 24 more
```

**Software versions**
- Official OWASP ZAP Jenkins Plugin - 1.1.0
- ZAP D-2019-05-28
 - Java: openjdk version 11.0.2

**Comment by thc202** [comment]
That was addressed in #4037. The add-on is no longer available in the marketplace though (#4866).

**Comment by hnestorova** [comment]
@thc202  so I should uninstall the SOAP Scanner, right?

**Comment by kingthorin** [comment]
Yes.

**Comment by hnestorova** [comment]
no plans for that. I will then uninstall it, thanks
