### ISSUE TITLE
Failed to start/connect to 'Firefox' on AWS Linux and Firefox 67.0.4

### ISSUE THREAD

**Issue by 37b** [zaproxy/zaproxy#5447]
**Describe the bug**
OWASP ZAP/Selenium cannot connect to the Firefox after it launches

**To Reproduce**

1. Steps to reproduce the behavior:
2. Launch ZAP
3. Open Ajax Spider -> New Scan
4. Add starting point URL
5. Choose Firefox for browser
6. Click Start Scan
7. Browser starts and closes after a few seconds
8. Error message is shown 

`Failed to start/connect to 'Firefox', is the browser available/supported?`

**Expected behavior**
Firefox launches and ZAP begins traversing the application via Selenium

**Screenshots**

**Software versions**
 - ZAP: 2.7.0 and 2.8.0
 - Add-on: Selenium 15.0.0, Linux WebDrivers 10.0.0
 - OS: Ubuntu 16.04.6 
 - Java: openjdk version "1.8.0_212"
 - Browser: Firefox 67.0.4

**Errors from the zap.log file**
```
2019-06-27 14:49:14,942 [ZAP-AjaxSpider] INFO  SpiderThread - Running Crawljax (with firefox): https://********.net
2019-06-27 14:49:14,943 [ZAP-AjaxSpider] INFO  SpiderThread - Starting proxy...
2019-06-27 14:49:14,944 [ZAP-AjaxSpider] INFO  SpiderThread - Proxy started, listening at port [33422].
2019-06-27 14:49:14,966 [ZAP-AjaxSpider] INFO  Plugins - Loaded org.zaproxy.zap.extension.spiderAjax.SpiderThread$DummyPlugin@1092a659 as a OnBrowserCreatedPlugin
2019-06-27 14:49:18,187 [Forwarding newSession on session null to remote] INFO  ErrorCodes - HTTP Status: '404' -> incorrect JSON status mapping for 'unknown error' (500 expected)
2019-06-27 14:49:18,188 [ZAP-AjaxSpider] WARN  SpiderThread - Failed to start browser firefox
com.google.inject.ProvisionException: Guice provision errors:

1) Error in custom provider, org.openqa.selenium.WebDriverException: newSession
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Unknown', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1085-aws', java.version: '1.8.0_212'
Driver info: driver.version: FirefoxDriver
remote stacktrace: WebDriverError@chrome://marionette/content/error.js:179:5
UnknownCommandError@chrome://marionette/content/error.js:473:5
despatch@chrome://marionette/content/server.js:281:13
execute@chrome://marionette/content/server.js:262:16
onPacket/<@chrome://marionette/content/server.js:235:20
onPacket@chrome://marionette/content/server.js:236:9
onJSONObjectReady/<@chrome://marionette/content/transport.js:492:20

  at com.crawljax.di.ConfigurationModule.configure(ConfigurationModule.java:47)
  while locating com.crawljax.browser.EmbeddedBrowser
    for parameter 0 at com.crawljax.core.CrawlerContext.<init>(CrawlerContext.java:33)
  while locating com.crawljax.core.CrawlerContext
    for parameter 0 at com.crawljax.core.Crawler.<init>(Crawler.java:75)
  while locating com.crawljax.core.Crawler
    for parameter 2 at com.crawljax.core.CrawlTaskConsumer.<init>(CrawlTaskConsumer.java:30)
  while locating com.crawljax.core.CrawlTaskConsumer

1 error
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at com.crawljax.core.CrawlController.call(CrawlController.java:66)
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37)
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread.run(SpiderThread.java:248)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.WebDriverException: newSession
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Unknown', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1085-aws', java.version: '1.8.0_212'
Driver info: driver.version: FirefoxDriver
remote stacktrace: WebDriverError@chrome://marionette/content/error.js:179:5
UnknownCommandError@chrome://marionette/content/error.js:473:5
despatch@chrome://marionette/content/server.js:281:13
execute@chrome://marionette/content/server.js:262:16
onPacket/<@chrome://marionette/content/server.js:235:20
onPacket@chrome://marionette/content/server.js:236:9
_onJSONObjectReady/<@chrome://marionette/content/transport.js:492:20

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:120)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:777)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:700)
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:639)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:509)
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:471)
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:439)
	at com.google.inject.util.Providers$3.get(Providers.java:109)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	... 4 more
```

**Additional context**
Seems to work fine on the same version of Firefox and ZAP on macOS

**Comment by thc202** [comment]
This is most likely caused by incompatible versions between geckodriver and Firefox. If you need to use a specific Firefox version not supported by the geckodriver version bundled in the WebDriver add-ons you'd have to download it and specify it in the Selenium options.

https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
https://www.zaproxy.org/docs/desktop/addons/linux-webdrivers/
https://www.zaproxy.org/docs/desktop/addons/selenium/options/
