### ISSUE TITLE
Certificate refused by Chrome

### ISSUE THREAD

**Issue by JurgenG** [zaproxy/zaproxy#5456]
**Describe the bug**
When trying to import the self signed certificate from ZAP 2.8.0 into Google Chrome (v. 75.0.3770.100) under ubuntu (19.04), I'm getting the following error: "The Private Key for this Client Certificate is missing or invalid" after which the certificate is not imported.
Since I am also having issues with Firefox, I'm assuming there is a problem with the certificate. Here, I can import, the certificate shows up in the list. But when trying to load a page, I'm getting a JAVA error "connection refused":

ZAP Error [java.net.ConnectException]: Connection refused (Connection refused)

Stack Trace:
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.commons.httpclient.protocol.ReflectionSocketFactory.createSocket(ReflectionSocketFactory.java:140)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:125)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:449)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:201)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:398)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:633)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:589)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:565)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:553)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:458)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:428)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:564)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:321)
	at java.base/java.lang.Thread.run(Thread.java:835)

I have tried switching between openJDK and Oracle JDK (both latest stable version)

As this might be relevant: I did a nuke and pave install of Ubuntu 19.04 last week (there, I had ZAP 2.7.0 installed) while remaining the /home folder (separate partition).

**Expected behavior**
Opening the browser through the "Launch browser" button, results in a working (but proxied) browser.

**Screenshots**

**Software versions**
 - ZAP: 2.8.0
 - OS: Ubuntu 19.04
 - Java: java version "12.0.1" 2019-04-16 (also tried openjdk version "13" 2019-09-17)
 - Browser: Google Chrome (v. 75.0.3770.100)
- Browser: Firefox (67.0.4 (64-bit))

**Errors from the zap.log file**
2019-06-30 16:09:22,875 [main ] INFO  Constant - Creating directory /home/jurgen/.ZAP/session
2019-06-30 16:09:22,876 [main ] INFO  Constant - Creating directory /home/jurgen/.ZAP/dirbuster
2019-06-30 16:09:22,876 [main ] INFO  Constant - Creating directory /home/jurgen/.ZAP/fuzzers
2019-06-30 16:09:22,960 [main ] INFO  Constant - Creating directory /home/jurgen/.ZAP/plugin
2019-06-30 16:09:23,177 [main ] INFO  GuiBootstrap - OWASP ZAP 2.8.0 started 30/06/2019, 16:09:23 with home /home/jurgen/.ZAP/
2019-06-30 16:09:23,602 [AWT-EventQueue-0] INFO  SSLConnector - Reading supported SSL/TLS protocols...
2019-06-30 16:09:23,603 [AWT-EventQueue-0] INFO  SSLConnector - Using a SSLEngine...
2019-06-30 16:09:23,676 [AWT-EventQueue-0] INFO  SSLConnector - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
2019-06-30 16:09:23,681 [AWT-EventQueue-0] INFO  OptionsParamCertificate - Unsafe SSL renegotiation disabled.
2019-06-30 16:09:24,270 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open start
2019-06-30 16:09:24,280 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open end
2019-06-30 16:09:24,516 [AWT-EventQueue-0] INFO  View - Initialising View
2019-06-30 16:09:25,353 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Loading extensions
2019-06-30 16:09:26,793 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Installed add-ons: [[id=alertFilters, version=8.0.0], [id=ascanrules, version=33.0.0], [id=bruteforce, version=8.0.0], [id=diff, version=9.0.0], [id=directorylistv1, version=3.0.0], [id=fuzz, version=11.0.0], [id=gettingStarted, version=10.0.0], [id=help, version=9.0.0], [id=hud, version=0.4.0], [id=importurls, version=6.0.0], [id=invoke, version=9.0.0], [id=jxbrowser, version=14.0.0], [id=jxbrowserlinux64, version=12.0.0], [id=onlineMenu, version=6.0.0], [id=pscanrules, version=24.0.0], [id=quickstart, version=26.0.0], [id=replacer, version=7.0.0], [id=reveal, version=2.0.0], [id=saverawmessage, version=4.0.0], [id=savexmlmessage, version=0.0.1], [id=scripts, version=25.0.0], [id=selenium, version=15.0.0], [id=spiderAjax, version=23.0.0], [id=tips, version=6.0.0], [id=webdriverlinux, version=10.0.0], [id=websocket, version=19.0.0], [id=zest, version=29.0.0]]
2019-06-30 16:09:26,957 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Extensions loaded
2019-06-30 16:09:27,612 [ZAP-BootstrapGUI] INFO  ExtensionJxBrowser - Using version 6.23.1 of JxBrowser.
2019-06-30 16:09:27,834 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows ZAP to check for updates
2019-06-30 16:09:27,939 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Options Extension
2019-06-30 16:09:28,412 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Edit Menu Extension
2019-06-30 16:09:28,420 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides a rest based API for controlling and accessing ZAP
2019-06-30 16:09:28,458 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Session State Extension
2019-06-30 16:09:28,459 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Report Extension
2019-06-30 16:09:28,482 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing History Extension
2019-06-30 16:09:28,616 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Show hidden fields and enable disabled fields
2019-06-30 16:09:28,636 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Search messages for strings and regular expressions
2019-06-30 16:09:28,742 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Encode/Decode/Hash...
2019-06-30 16:09:28,755 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to intercept and modify requests and responses
2019-06-30 16:09:28,837 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Passive scanner
2019-06-30 16:09:28,926 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Script Passive Scan Rules
2019-06-30 16:09:28,926 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Stats Passive Scan Rule
2019-06-30 16:09:28,926 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Application Error Disclosure
2019-06-30 16:09:28,927 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Absence of Anti-CSRF Tokens
2019-06-30 16:09:28,928 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Incomplete or No Cache-control and Pragma HTTP Header Set
2019-06-30 16:09:28,928 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Charset Mismatch
2019-06-30 16:09:28,929 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: CSP Scanner
2019-06-30 16:09:28,930 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Content-Type Header Missing
2019-06-30 16:09:28,931 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cookie No HttpOnly Flag
2019-06-30 16:09:28,932 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Loosely Scoped Cookie
2019-06-30 16:09:28,934 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cookie Without Secure Flag
2019-06-30 16:09:28,935 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cross-Domain JavaScript Source File Inclusion
2019-06-30 16:09:28,937 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Web Browser XSS Protection Not Enabled
2019-06-30 16:09:28,938 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Information Disclosure - Debug Error Messages
2019-06-30 16:09:28,940 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Weak Authentication Method
2019-06-30 16:09:28,942 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Insecure JSF ViewState
2019-06-30 16:09:28,943 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Secure Pages Include Mixed Content
2019-06-30 16:09:28,945 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Private IP Disclosure
2019-06-30 16:09:28,946 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Session ID in URL Rewrite
2019-06-30 16:09:28,948 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Viewstate Scanner
2019-06-30 16:09:28,949 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: X-Content-Type-Options Header Missing
2019-06-30 16:09:28,951 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: X-Frame-Options Header Scanner
2019-06-30 16:09:28,992 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to view and manage alerts
2019-06-30 16:09:29,055 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Active scanner, heavily based on the original Paros active scanner, but with additional tests added
2019-06-30 16:09:29,155 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Spider used for automatically finding URIs on a site
2019-06-30 16:09:29,286 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing A set of common popup menus for miscellaneous tasks
2019-06-30 16:09:29,306 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Forced browsing of files and directories using code from the OWASP DirBuster tool
2019-06-30 16:09:29,373 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Manual Request Editor Extension
2019-06-30 16:09:29,376 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Compares 2 sessions and generates an HTML file showing the differences
2019-06-30 16:09:29,379 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Invoke external applications passing context related information such as URLs and parameters
2019-06-30 16:09:29,415 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Handles anti cross site request forgery (CSRF) tokens
2019-06-30 16:09:29,439 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Authentication Extension
2019-06-30 16:09:29,455 [ZAP-BootstrapGUI] INFO  ExtensionAuthentication - Loaded authentication method types: [Form-based Authentication, HTTP/NTLM Authentication, Manual Authentication, Script-based Authentication, JSON-based Authentication]
2019-06-30 16:09:29,462 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Creates a dynamic SSL certificate to allow SSL communications to be intercepted without warnings being generated by the browser
2019-06-30 16:09:29,698 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Logs errors to the Output tab in development mode only
2019-06-30 16:09:29,706 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Users Extension
2019-06-30 16:09:29,713 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Summarise and analyse FORM and URL parameters as well as cookies
2019-06-30 16:09:29,755 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Script integration
2019-06-30 16:09:29,801 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Scripting console, supports all JSR 223 scripting languages
2019-06-30 16:09:30,091 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Forced User Extension
2019-06-30 16:09:30,100 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Extension handling HTTP sessions
2019-06-30 16:09:30,150 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Zest is a specialized scripting language from Mozilla specifically designed to be used in security tools
2019-06-30 16:09:30,356 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionDiff
2019-06-30 16:09:30,361 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Post Table View Extension
2019-06-30 16:09:30,377 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Session Management Extension
2019-06-30 16:09:30,383 [ZAP-BootstrapGUI] INFO  ExtensionSessionManagement - Loaded session management method types: [Cookie-based Session Management, HTTP Authentication Session Management]
2019-06-30 16:09:30,384 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Form Table View Extension
2019-06-30 16:09:30,427 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Capture messages from WebSockets with the ability to set breakpoints.
2019-06-30 16:09:30,658 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to import a file containing URLs which ZAP will access, adding them to the Sites tree
2019-06-30 16:09:30,661 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Core UI related functionality.
2019-06-30 16:09:30,663 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Authorization Extension
2019-06-30 16:09:30,666 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing AJAX Spider, uses Crawljax
2019-06-30 16:09:30,755 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides WebDrivers to control several browsers using Selenium and includes HtmlUnit browser.
2019-06-30 16:09:30,772 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Manages the local proxy configurations
2019-06-30 16:09:30,807 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Handles adding Global Excluded URLs
2019-06-30 16:09:30,820 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds menu item to refresh the Sites tree
2019-06-30 16:09:30,823 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing OWASP ZAP User Guide
2019-06-30 16:09:30,953 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides a URL suitable for calling from target sites
2019-06-30 16:09:30,988 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to configure which extensions are loaded when ZAP starts
2019-06-30 16:09:31,019 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Combined HTTP Panels Extension
2019-06-30 16:09:31,054 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Hex View Extension
2019-06-30 16:09:31,102 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Image View Extension
2019-06-30 16:09:31,108 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Large Request View Extension
2019-06-30 16:09:31,121 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Large Response View Extension
2019-06-30 16:09:31,130 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Query Table View Extension
2019-06-30 16:09:31,165 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Syntax Highlighter View Extension
2019-06-30 16:09:31,305 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds support for configurable keyboard shortcuts for all of the ZAP menus.
2019-06-30 16:09:31,315 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Active and passive rule configuration
2019-06-30 16:09:31,326 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Statistics
2019-06-30 16:09:31,335 [ZAP-BootstrapGUI] INFO  ExtensionStats - Start recording in memory stats
2019-06-30 16:09:31,336 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides the foundation for concrete message types (for example, HTTP, WebSockets) expose fuzzer implementations.
2019-06-30 16:09:31,354 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows to fuzz HTTP messages.
2019-06-30 16:09:31,425 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows to fuzz WebSocket messages.
2019-06-30 16:09:31,427 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionJxBrowser
2019-06-30 16:09:31,429 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Active Scan Rules
2019-06-30 16:09:31,431 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionJxBrowserLinux64
2019-06-30 16:09:31,436 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtSelJxBrowserLinux64
2019-06-30 16:09:31,445 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Heads Up Display
2019-06-30 16:09:31,509 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionHUDlaunch
2019-06-30 16:09:31,511 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionSaveRawHttpMessage
2019-06-30 16:09:31,521 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Tips and Tricks
2019-06-30 16:09:31,524 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Easy way to replace strings in requests and responses
2019-06-30 16:09:31,539 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Passive Scan Rules
2019-06-30 16:09:31,539 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing The Online menu links
2019-06-30 16:09:31,546 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionSaveXMLHttpMessage
2019-06-30 16:09:31,556 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing The ZAP Getting Started Guide
2019-06-30 16:09:31,558 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Context alert rules filter
2019-06-30 16:09:31,564 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds the Quick Start panel for scanning and exploring applications
2019-06-30 16:09:31,604 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Add the option to use the Ajax Spider in the Quick Start scan
2019-06-30 16:09:31,616 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Launch browsers proxying through ZAP
2019-06-30 16:09:31,621 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Launch browsers proxying through ZAP
2019-06-30 16:09:32,342 [ZAP-BootstrapGUI] INFO  ExtensionCallback - Started callback server on 0.0.0.0:42275
2019-06-30 16:09:32,342 [ZAP-BootstrapGUI] INFO  ExtensionKeyboard - Initializing keyboard shortcuts
2019-06-30 16:09:32,726 [AWT-EventQueue-0] INFO  Control - New Session
2019-06-30 16:09:32,740 [AWT-EventQueue-0] INFO  Control - Create and Open Untitled Db
2019-06-30 16:09:32,761 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2019-06-30 16:09:32,770 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2019-06-30 16:09:32,786 [AWT-EventQueue-0] INFO  ENGINE - Database closed
2019-06-30 16:09:32,991 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open start
2019-06-30 16:09:33,001 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open end
2019-06-30 16:09:33,273 [Thread-6] INFO  ENGINE - dataFileCache commit start
2019-06-30 16:09:33,290 [Thread-6] INFO  ENGINE - dataFileCache commit end
2019-06-30 16:09:33,306 [Thread-6] INFO  ENGINE - Database closed
2019-06-30 16:09:33,446 [Thread-6] INFO  ENGINE - dataFileCache open start
2019-06-30 16:09:33,448 [Thread-6] INFO  ENGINE - dataFileCache open end

**Additional context**
Not sure it's a ZAP bug, rather an interaction bug. Maybe has to do with artefacts from previous install...

**Comment by psiinon** [comment]
"The Private Key for this Client Certificate is missing or invalid" 
It looks like you're trying to import to ZAP cert as a client cert, thts not going to work as its not a client cert and therefore doesnt have a private key :)
You need to import it as a trusted root CA cert: https://github.com/zaproxy/zap-core-help/wiki/HelpUiDialogsOptionsDynsslcert#install-zap-root-ca-certificate

Note that you can also use the Quick Start / Manual Explore screen which can launch both Firefox and Chrome correctly configued to use ZAP: https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsQuickstartQuickstart#manual-explore

**Comment by thc202** [comment]
Closing with previous comment.
