### ISSUE TITLE
Auth request without request-target from auth script causes exceptions

### ISSUE THREAD

**Issue by aynacisevda** [zaproxy/zaproxy#5491]
**Describe the bug**
**Receive NullPointerException while spider with user authentication and HTTPSender enabled **
**To Reproduce**
1. Add Authorization script (https://gist.github.com/aynacisevda/ab3c15304b861297d9dcd1891d2df4fb) and HTTP Sender (https://gist.github.com/aynacisevda/f3053b8ca1ae42e88990d60909a92e28) script
2. Start spider by right click on context
3. Go to spider tab
java.lang.NullPointerException: null

Stack Trace:
java.lang.NullPointerException
	at org.zaproxy.zap.model.SessionStructure.getHostName(SessionStructure.java:384)
	at org.zaproxy.zap.model.SessionStructure.getHostName(SessionStructure.java:378)
	at org.zaproxy.zap.authentication.AuthenticationMethod.isAuthenticated(AuthenticationMethod.java:225)
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$ScriptBasedAuthenticationMethod.authenticate(ScriptBasedAuthenticationMethodType.java:300)
	at org.zaproxy.zap.users.User.authenticate(User.java:265)
	at org.zaproxy.zap.users.User.processMessageToMatchUser(User.java:175)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:578)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:553)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:458)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:428)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(SpiderTask.java:445)
	at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:218)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Screenshot:
![image](https://user-images.githubusercontent.com/44896069/61805332-4cba6480-ae3e-11e9-9179-dbce878faf21.png)

**Software versions**
 - ZAP: 2.8.0
 - OS: Windows 10
 - Java: 1.8.0_192

**Comment by thc202** [comment]
The authentication message should be sent (ideally) with `helper.sendAndReceive(msg)` not using Python libs.

The message returned by the `authenticate` method should be the one sent (or at least crafted to contain the expected request/response data), this is causing the exception.

**Comment by aynacisevda** [comment]
@thc202 Could you give me a code example for your solution?

**Comment by thc202** [comment]
The following should be the equivalent:
```Python
    msg = helper.prepareMessage();
    requestHeader = msg.getRequestHeader()
    requestHeader.setURI(requestUri)
    requestHeader.setMethod(requestMethod)
    requestHeader.setHeader("Content-Type", "application/json")
    requestHeader.setHeader("Authorization", "Basic " + base64.encodestring('%s:%s' % (username, password)).replace('\n', ''))
    msg.getRequestBody().setBody(str(obje))
    helper.sendAndReceive(msg)
    print msg.getResponseBody().toString()
```
