### ISSUE TITLE
Process basic auth challenge without realm

### ISSUE THREAD

**Issue by meetinthemiddle-be** [zaproxy/zaproxy#5538]
**Describe the bug**
When filling out all the forms in the "Session Properties" Dialog under the correct context, the "Authorization: Basic {B64(user:pass)}" does not get added to any request when starting a Spidering action from right-clicking the context. Zap.log shows a Java stack trace (repro steps and error below).

**To Reproduce**
- Start a new session
- Go to quick start, enter URL that requires HTTP Basic Auth.
- enable HUD and click "Launch Browser" -> "Firefox"
- Observe the realm that user/pass popup might show (in my case this was empty)
- Enter the correct user/pass combo in FireFox
- See the site render, including the HUD
- Right click URL in Site Tree -> "Add To Context" -> "Default Context"
- "Session Properties" dialog opens and auto-fills the URL in the "Include in context" Form
- Go to the "Authentication" form and choose "HTTP/NTLM Authentication"
- type the FQDN of your site into "Hostname" and complete the realm (if any)
- Adjust the port to 443 if HTTPS; if HTTP, leave at default 80
- Type "\Q{Words in body or header you would find after authenticating, but not before}\E" in the Logged Out indicator. (Mind the prefixing and suffixing with "\Q" and "\E" !!)
- Go to the "Users" form and create a new user with the username/password for the HTTP/Basic auth. Make sure the user is "enabled".
- Go to the "Forced User" form and make sure that the user you just created is selected in the dropdown.
- Go to the "Session Management" form and select "HTTP Authentication Session Management"
- Go to the "Authorization" form, select the correct HTTP response code that was given by the webpage (usually 401), leave the rest blank and select "At least one of the..." in the drop down at the bottom
- Close this dialog with "OK"
- In the top toolbar, find the "Forced User" button (open padlock with user icon) and click it so the padlock displays as being closed.
- Right click the Default Context and click "Spider..."
- Change the "User" drop down to reflect the user that you set for the authentication
- Check "Recurse", uncheck "Spider subtree only" and uncheck "Show Advanced Options"
- Click "start scan"

**Expected behavior**
Requests are being made with a  "Authorization: Basic " header. However, the header is not added to any of the requests.

**Software versions**
 - ZAP: 2.8.0
 - Add-on: - 
 - OS: Mac OSX 10.14.5
 - Java: 1.8.0_181-b13
 - Browser: Firefox 68.0.2

**Errors from the zap.log file**
```
2019-08-22 16:43:51,993 [ZAP-SpiderThreadPool-0-thread-5] ERROR HttpMethodDirector - Invalid challenge: Basic
org.apache.commons.httpclient.auth.MalformedChallengeException: Invalid challenge: Basic
	at org.apache.commons.httpclient.auth.AuthChallengeParser.extractParams(AuthChallengeParser.java:98)
	at org.apache.commons.httpclient.auth.RFC2617Scheme.processChallenge(RFC2617Scheme.java:94)
	at org.apache.commons.httpclient.auth.BasicScheme.processChallenge(BasicScheme.java:112)
	at org.apache.commons.httpclient.auth.AuthChallengeProcessor.processChallenge(AuthChallengeProcessor.java:162)
	at org.apache.commons.httpclient.HttpMethodDirector.processWWWAuthChallenge(HttpMethodDirector.java:775)
	at org.apache.commons.httpclient.HttpMethodDirector.processAuthenticationResponse(HttpMethodDirector.java:749)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:223)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:398)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:631)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:589)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:565)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:553)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:458)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:428)
	at org.zaproxy.zap.spider.SpiderTask.fetchResource(SpiderTask.java:445)
	at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:218)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by thc202** [comment]
Could you show the whole WWW-Authenticate header? Does it have the realm?

**Comment by meetinthemiddle-be** [comment]
Also no realm.

This is the full req/resp:

-----REQ-----
GET https://evenitypsp-de-preview.ucbweb.net/index.php HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101
Firefox/39.0
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0
Cookie: 2822REDACTED8a6e=08ee9REDACTEDd49
Host: REDACTED.io

-----RESP-----
HTTP/1.1 401 Unauthorized
Date: Thu, 22 Aug 2019 14:51:56 GMT
Server: Varnish
X-Varnish: 852497
WWW-Authenticate: Basic
Content-Length: 0

**Comment by thc202** [comment]
The realm is required, I guess ZAP could be more lax and accept that anyway.

**Comment by pauldzy** [comment]
I have followed @meetinthemiddle-be's steps precisely and regardless of the existence of the realm value or not, basic authentication is not working in version 2.9.0.  E.g. the headers are never inserted for any spider actions.

This seems like it should be a bug or perhaps officially drop support for basic authentication.

**Comment by kingthorin** [comment]
Did you set a good logged in/out indicator?

**Comment by pauldzy** [comment]
I've tried everything from .* to words to various html tags.  But you raise a good point in that there really is not a good indicator for all the pages I would like to scan.  Basic Authentication in this sense is just being used as an short-term cover over a non-sensitive site under final review before removing the auth to make it public.  That probably is not a good fit for zap - not to mention we have no realm value at all.

There is another post here that lead me to just using the replacer to inject the basic authentication header.  That seems like the best way forward. 

Thanks.

**Comment by ekini** [comment]
I've just thoroughly followed "ZAP HUD: Authentication - Basic and Digest" tutorial and basic auth didn't work for me. The header doesn't get inserted.

I've got version 2.9.0 for Mac.

**Comment by wersas1** [comment]
Unfortunately the problem still stands.
Trying to use outgoing proxy without realm (it doesn't have one) and authenticating with user/pass combo produces the following log with error on ZAP 2.11.1:

`2021-12-25 02:57:22,519 [ZAP-telemetry-start] DEBUG HttpSender - sendAndReceive POST https://tel.zaproxy.org/ZAPtel start
2021-12-25 02:57:22,520 [ZAP-telemetry-start] DEBUG HttpSender - Sending message to: https://tel.zaproxy.org/ZAPtel
2021-12-25 02:57:22,571 [ZAP-telemetry-start] DEBUG ZapProxySelector - Selected proxies for socket://REDACTED_PROXY_IP:PORT [DIRECT]
2021-12-25 02:57:22,629 [ZAP-telemetry-start] ERROR HttpMethodDirector - Invalid challenge: Basic
org.apache.commons.httpclient.auth.MalformedChallengeException: Invalid challenge: Basic
	at org.apache.commons.httpclient.auth.AuthChallengeParser.extractParams(AuthChallengeParser.java:98) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.auth.RFC2617Scheme.processChallenge(RFC2617Scheme.java:94) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.auth.BasicScheme.processChallenge(BasicScheme.java:112) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.auth.AuthChallengeProcessor.processChallenge(AuthChallengeProcessor.java:162) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.processProxyAuthChallenge(HttpMethodDirector.java:847) ~[zap-2.11.1.jar:2.11.1]
	at org.apache.commons.httpclient.HttpMethodDirector.processAuthenticationResponse(HttpMethodDirector.java:759) ~[zap-2.11.1.jar:2.11.1]
	at org.apache.commons.httpclient.HttpMethodDirector.executeConnect(HttpMethodDirector.java:592) ~[zap-2.11.1.jar:2.11.1]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:463) ~[zap-2.11.1.jar:2.11.1]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207) ~[zap-2.11.1.jar:2.11.1]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:430) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:672) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:627) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:602) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:585) ~[zap-2.11.1.jar:2.11.1]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:495) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.addon.callhome.ExtensionCallHome.sendServiceRequest(ExtensionCallHome.java:219) ~[?:?]
	at org.zaproxy.addon.callhome.ExtensionCallHome.lambda$uploadTelemetryStartData$5(ExtensionCallHome.java:330) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-12-25 02:57:22,630 [ZAP-telemetry-start] DEBUG HttpSender - SUCCESSFUL
2021-12-25 02:57:22,630 [ZAP-telemetry-start] DEBUG HttpSender - sendAndReceive POST https://tel.zaproxy.org/ZAPtel took 111
2021-12-25 02:57:22,631 [ZAP-telemetry-start] ERROR ExtensionCallHome - Expected '200 OK' but got '407 Proxy Authentication Required'`

**Comment by thc202** [comment]
This would be an add-on issue now, need to recheck.

**Comment by thc202** [comment]
Removed digest since the realm is included in the hash (browsers do not even prompt for credentials if not present).
