### ISSUE TITLE
Command line quick scan throws fatal ActiveScan error: "dataFileCache CACHE SIZE limit reached"

### ISSUE THREAD

**Issue by ggallo** [zaproxy/zaproxy#5600]
**Describe the bug**
A quickscan run from the command line is showing errors that the HSQLDB cache limit was hit, though the scan completes.
**To Reproduce**
1. Run an Angular project locally on port 4200 (the specific project in question is private)
2. `zap.sh -cmd -quickurl http://localhost:4200/ -quickout $(pwd)/zapreport.xml`
3. Open `zapreport.xml`, no problems
4. Open the logs

**Expected behavior**
The scan completes without errors

**Software versions**
 - ZAP: 2.8.1
 - Add-on: Not sure
 - OS: Windows 10
 - Java: 1.8.0_222
 - Browser: N/A

**Errors from the zap.log file**
```
2019-09-25 21:36:00,106 [ZAP-QuickStart-AttackThread] INFO  Scanner - scanner started
2019-09-25 21:36:00,141 [Thread-7] INFO  HostProcess - Scanning 10 node(s) from http://localhost:4200
2019-09-25 21:36:00,142 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestPathTraversal strength MEDIUM threshold MEDIUM
2019-09-25 21:36:00,776 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestPathTraversal in 0.635s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:00,776 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestRemoteFileInclude strength MEDIUM threshold MEDIUM
2019-09-25 21:36:01,007 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestRemoteFileInclude in 0.231s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:01,008 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | SourceCodeDisclosureWEBINF strength MEDIUM threshold MEDIUM
2019-09-25 21:36:01,010 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestServerSideInclude strength MEDIUM threshold MEDIUM
2019-09-25 21:36:01,051 [ZAP-ActiveScanner-0] INFO  HostProcess - completed host/plugin http://localhost:4200 | SourceCodeDisclosureWEBINF in 0.043s with 4 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:01,500 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestServerSideInclude in 0.49s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:01,500 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestCrossSiteScriptV2 strength MEDIUM threshold MEDIUM
2019-09-25 21:36:01,975 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestCrossSiteScriptV2 in 0.475s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:01,975 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestPersistentXSSPrime strength MEDIUM threshold MEDIUM
2019-09-25 21:36:02,002 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestPersistentXSSPrime in 0.027s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:02,002 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestPersistentXSSSpider strength MEDIUM threshold MEDIUM
2019-09-25 21:36:02,890 [ZAP-ActiveScanner-1] INFO  ENGINE - dataFileCache CACHE SIZE limit reached
2019-09-25 21:36:02,890 [ZAP-ActiveScanner-1] FATAL ENGINE - /root/.ZAP/session/untitled1.data getFromFile failed 14847
org.hsqldb.HsqlException: Data cache size limit is reached: 10000
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.persist.Cache.put(Unknown Source)
        at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
        at org.hsqldb.persist.DataFileCache.get(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.child(Unknown Source)
        at org.hsqldb.index.IndexAVL.insert(Unknown Source)
        at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source)
        at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
        at org.hsqldb.Session.addInsertAction(Unknown Source)
        at org.hsqldb.Table.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementInsert.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:515)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:427)
        at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:368)
        at org.zaproxy.zap.extension.ascan.ActiveScan.notifyNewMessage(ActiveScan.java:270)
        at org.parosproxy.paros.core.scanner.HostProcess.notifyNewMessage(HostProcess.java:788)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:318)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
        at org.zaproxy.zap.extension.ascanrules.TestPersistentXSSSpider.scan(TestPersistentXSSSpider.java:80)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:372)
        at java.lang.Thread.run(Thread.java:748)
2019-09-25 21:36:02,892 [ZAP-ActiveScanner-1] ERROR ActiveScan - java.sql.SQLException: Data cache size limit is reached: 10000
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Data cache size limit is reached:
10000
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:443)
        at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:368)
        at org.zaproxy.zap.extension.ascan.ActiveScan.notifyNewMessage(ActiveScan.java:270)
        at org.parosproxy.paros.core.scanner.HostProcess.notifyNewMessage(HostProcess.java:788)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:318)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
        at org.zaproxy.zap.extension.ascanrules.TestPersistentXSSSpider.scan(TestPersistentXSSSpider.java:80)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:372)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Data cache size limit is reached: 10000
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:515)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:427)
        ... 8 more
Caused by: org.hsqldb.HsqlException: Data cache size limit is reached: 10000
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.persist.Cache.put(Unknown Source)
        at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
        at org.hsqldb.persist.DataFileCache.get(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.child(Unknown Source)
        at org.hsqldb.index.IndexAVL.insert(Unknown Source)
        at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source)
        at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
        at org.hsqldb.Session.addInsertAction(Unknown Source)
        at org.hsqldb.Table.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementInsert.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 12 more
2019-09-25 21:36:02,912 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestPersistentXSSSpider in 0.91s with 10 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:02,912 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestPersistentXSSAttack strength MEDIUM threshold MEDIUM
2019-09-25 21:36:03,144 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestPersistentXSSAttack in 0.232s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:03,144 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestSQLInjection strength MEDIUM threshold MEDIUM
2019-09-25 21:36:03,380 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestSQLInjection in 0.236s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:03,381 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | CodeInjectionPlugin strength MEDIUM threshold MEDIUM
2019-09-25 21:36:03,603 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | CodeInjectionPlugin in 0.222s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:03,603 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | CommandInjectionPlugin strength MEDIUM threshold MEDIUM
2019-09-25 21:36:03,616 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | CommandInjectionPlugin in 0.013s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:03,616 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestDirectoryBrowsing strength MEDIUM threshold MEDIUM
2019-09-25 21:36:04,486 [ZAP-ActiveScanner-1] INFO  ENGINE - dataFileCache CACHE SIZE limit reached
2019-09-25 21:36:04,486 [ZAP-ActiveScanner-1] FATAL ENGINE - /root/.ZAP/session/untitled1.data getFromFile failed 14847
org.hsqldb.HsqlException: Data cache size limit is reached: 10000
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.persist.Cache.put(Unknown Source)
        at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
        at org.hsqldb.persist.DataFileCache.get(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.child(Unknown Source)
        at org.hsqldb.index.IndexAVL.insert(Unknown Source)
        at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source)
        at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
        at org.hsqldb.Session.addInsertAction(Unknown Source)
        at org.hsqldb.Table.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementInsert.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:515)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:427)
        at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:368)
        at org.zaproxy.zap.extension.ascan.ActiveScan.notifyNewMessage(ActiveScan.java:270)
        at org.parosproxy.paros.core.scanner.HostProcess.notifyNewMessage(HostProcess.java:788)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:318)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:209)
        at org.zaproxy.zap.extension.ascanrules.TestDirectoryBrowsing.scan(TestDirectoryBrowsing.java:119)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:372)
        at java.lang.Thread.run(Thread.java:748)
2019-09-25 21:36:04,487 [ZAP-ActiveScanner-1] ERROR ActiveScan - java.sql.SQLException: Data cache size limit is reached: 10000
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: Data cache size limit is reached:
10000
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:443)
        at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:368)
        at org.zaproxy.zap.extension.ascan.ActiveScan.notifyNewMessage(ActiveScan.java:270)
        at org.parosproxy.paros.core.scanner.HostProcess.notifyNewMessage(HostProcess.java:788)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:318)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:237)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:209)
        at org.zaproxy.zap.extension.ascanrules.TestDirectoryBrowsing.scan(TestDirectoryBrowsing.java:119)
        at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:372)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Data cache size limit is reached: 10000
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:515)
        at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:427)
        ... 9 more
Caused by: org.hsqldb.HsqlException: Data cache size limit is reached: 10000
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.error.Error.error(Unknown Source)
        at org.hsqldb.persist.Cache.put(Unknown Source)
        at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
        at org.hsqldb.persist.DataFileCache.get(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.child(Unknown Source)
        at org.hsqldb.index.IndexAVL.insert(Unknown Source)
        at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source)
        at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source)
        at org.hsqldb.Session.addInsertAction(Unknown Source)
        at org.hsqldb.Table.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementDML.insertSingleRow(Unknown Source)
        at org.hsqldb.StatementInsert.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        ... 13 more
2019-09-25 21:36:05,042 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestDirectoryBrowsing in 1.425s with 10 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:05,042 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | TestExternalRedirect strength MEDIUM threshold MEDIUM
2019-09-25 21:36:05,055 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | TestExternalRedirect in 0.013s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:05,056 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | BufferOverflow strength MEDIUM threshold MEDIUM
2019-09-25 21:36:05,066 [Thread-7] INFO  HostProcess - completed host/plugin http://localhost:4200 | BufferOverflow in 0.01s with 0 message(s) sent and 0 alert(s) raised.
2019-09-25 21:36:05,067 [Thread-7] INFO  HostProcess - start host http://localhost:4200 | FormatString strength MEDIUM threshold MEDIUM

...
```

**Comment by kingthorin** [comment]
You can update this entry  in file `<zap_install_dir>/db/zapdb.script` to increase size: `SET FILES CACHE SIZE 10000`

However, it would also be great to know how long you had zap running and how much data was in the site tree/history.

**Comment by ggallo** [comment]
@kingthorin The run took 5.762s. I am unsure about how to check the size of data parsed.

After increasing the files cache (to 50000), we're now running without errors. Apologize if this wasn't a bug, I'm in a GUI-free environment and it's difficult to learn the ropes with only the shell script.

**Comment by kingthorin** [comment]
Zap was running for a total of 6 sec and you hit that state? Or the active scan had run for 6 sec? What about spidering/proxying?

I wasn’t thinking data parsed I was thinking number of history items or site nodes.
