### ISSUE TITLE
ZAP Error [java.net.SockZAP Error [java.net.SocketException]: Bad file descriptor (Write failed)etException]: Bad file descriptor (Write failed)

### ISSUE THREAD

**Issue by usmctoady** [zaproxy/zaproxy#5638]
**Describe the bug**
I'm not sure what the bug is I've included some screenshots of the error msgs below. Sometimes it times out with:
Failed to read https://example.com/ within 60 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.

other times I get the following:
```
ZAP Error [java.net.SocketException]: Bad file descriptor (Write failed)


Stack Trace:
java.net.SocketException: Bad file descriptor (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:860)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2248)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1154)
	at org.apache.commons.httpclient.ConnectMethod.execute(ConnectMethod.java:185)
	at org.apache.commons.httpclient.HttpMethodDirector.executeConnect(HttpMethodDirector.java:578)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:455)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:201)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:398)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:633)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:589)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:565)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:553)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:458)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:428)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:564)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:321)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**

**Screenshots**

**Software versions**
 - ZAP: 2.8.0
 - Add-on: N/A
 - OS: Mac OSX
 - Java: java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
 - Browser: Firefox Browser Developer 71.0b1 (64-bit) with FoxyProxy 7.4

![25fca747-6d6e-4478-8028-00627a5c62ad](https://user-images.githubusercontent.com/54143381/67114994-2d1ba980-f1ab-11e9-9eb1-9ff35b120364.jpg)
![5196b7e9-0142-481d-81a1-2e0046cdb2f7](https://user-images.githubusercontent.com/54143381/67114995-2d1ba980-f1ab-11e9-9f5d-379b937ef208.jpg)

**Errors from the zap.log file**
~/Library/Application Support/ZAP doesn't exist

**Additional context**
same results for both HTTPS/HTTP
The sites that I'm attempting to reach are available e.g. example.com

**Comment by kingthorin** [comment]
What browser are you using? Did you import ZAP's CA cert?

**Comment by kingthorin** [comment]
Oops just saw that you mentioned beta Firefox. 

Did you import the CA cert?

**Comment by usmctoady** [comment]
Yes. I tried both with and without the cert. Burp works (also with it's cert), and the proxy settings are the same just different ports. I think it might be related to Java.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thc202** [comment]
Did you configure an outgoing proxy (Options > Connection) in ZAP?

**Comment by usmctoady** [comment]
@thc202 that was it. Thanks for helping out a n00b. Seems like a candidate for a graceful error msg.

**Comment by thc202** [comment]
That will be #5308 (I think). Thanks for letting us know.
