### ISSUE TITLE
openapi: Spider Check for JSON/YAML'ish content

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#5725]
I encountered the following while doing some test crawls of JuiceShop this morning:

```java
436804 [ZAP-SpiderThreadPool-0-thread-2] ERROR io.swagger.parser.SwaggerCompatConverter  - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'angular': was expecting ('true', 'false' or 'null')
 at [Source: (StringReader); line: 1, column: 8]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1899)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4042)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2551)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:210)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:114)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:101)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:76)
	at org.zaproxy.zap.extension.openapi.OpenApiSpider.parseResource(OpenApiSpider.java:58)
	at org.zaproxy.zap.spider.SpiderTask.processResource(SpiderTask.java:415)
	at org.zaproxy.zap.spider.SpiderTask.runImpl(SpiderTask.java:267)
	at org.zaproxy.zap.spider.SpiderTask.run(SpiderTask.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

To work around such issues we could/should validate that the input seems JSON/YAML'ish before trying to parse further.
At the very least we could add debug logging of the URL when trying to parse it.

**Comment by kingthorin** [comment]
In v14 of the OpenAPI addon this now implicates [L55 of OpenApiSpider](https://github.com/zaproxy/zap-extensions/blob/d78161a30d383345a792bfeef87493c6a1188f86/addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiSpider.java#L55). Perhaps content type check in `canPraseResource(Httpmessage, String, boolean)` should be more specific?

Currently only checks that [content type starts with `application`](https://github.com/zaproxy/zap-extensions/blob/d78161a30d383345a792bfeef87493c6a1188f86/addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiSpider.java#L71), which would collide with standard javascript? `application/javascript`

**Comment by thc202** [comment]
https://github.com/zaproxy/zap-extensions/pull/765#discussion_r107647539 :)

I'm ok with making that more specific but we should not forget YAML. We could also tweak the log level of `SwaggerCompatConverter` (though it has some maybe useful warnings).

**Comment by kingthorin** [comment]
I had assumed (maybe incorrectly) that the [if immediately above handled yaml](https://github.com/zaproxy/zap-extensions/blob/d78161a30d383345a792bfeef87493c6a1188f86/addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/OpenApiSpider.java#L68-L69).

**Comment by thc202** [comment]
It might be `application` as well (also, that will no longer work with OpenAPI v3, no longer uses `swagger` field).

**Comment by kingthorin** [comment]
Okay, I'll do some research.

**Comment by ricekot** [comment]
Hi, may I work on this issue? I read around a bit, and I think I have a rough idea on what is required to be done.

_Some questions I had:_ 
1. Are we certain that we will not miss any valid definitions by making this change?
2. Can we simply return `true` for any ResponseBody that starts with `swagger` (for OpenAPI v2) or  `openapi` (for OpenAPI v3)? If not,
3. How will we check for YAML content? There are no registered media types for YAML on [IANA's website](https://www.iana.org/assignments/media-types/media-types.xhtml). Some workarounds have been mentioned [here](https://stackoverflow.com/questions/332129/yaml-mime-type).
4. Can we be certain that the `CONTENT_TYPE` in the ResponseHeader is valid? I mean, what if the file is a valid OpenAPI definition but has an invalid `CONTENT_TYPE`? Is this possible?
5. What is the meaning of "tweaking the log level of `SwaggerCompatConverter`"?

**Comment by kingthorin** [comment]
Absolutely.

1. Fairly ☺
2. Yes, if that's part of the spec.
3. You can do compound checks, if content type contains yaml, etc
4. We should trust the server, if an invalid header field is sent that's out of ZAP's control.
5. Not sure, @thc202 ?

**Comment by thc202** [comment]
2. That would still result in warns/errors if not really an OpenAPI spec.
5. Change the log level of that class (or the instance when spidering) so that the errors/warns are not logged (by setting the level to fatal or simply off).

**Comment by thc202** [comment]
Released in version 16 of OpenAPI add-on.
