### ISSUE TITLE
Error: No write access to directory /home/zap/.ZAP/plugin

### ISSUE THREAD

**Issue by hazcod** [zaproxy/zaproxy#6168]
**Describe the bug**
Running ZAP in Docker returns the following error on startup: ` java.security.InvalidParameterException: No write access to directory /home/zap/.ZAP/plugin`. This is Docker on Mac latest.

**To Reproduce**
Compose:
```yaml
volumes:
  data-zap:

services:
  zap:
    image: owasp/zap2docker-stable:2.9.0
    restart: "on-failure:8"
    volumes:
    - data-zap:/home/zap/.ZAP/plugin
    command:
    - "zap-x.sh"
    - "-addoninstall"
    - "spiderAjax"
    - "-addoninstall"
    - "vulncheck"
    - "-addoninstall"
    - "ascanrulesBeta"
    - "-addoninstall"
    - "pscanrulesBeta"
    - "-daemon"
    - "-host"
    - "0.0.0.0"
    - "-port"
    - "8080"
    - "-config"
    - "api.addrs.addr.name=.*"
    - "-config"
    - "api.addrs.addr.regex=true"
    - "-config"
    - "api.key=xxx"
    ports:
    - 8080
    networks:
    - backend
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8080"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 8m
```

**Expected behavior**
Starts up fine.

**Errors from the zap.log file**
```

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

_XSERVTransmkdir: ERROR: Cannot create /tmp/.X11-unix

_XSERVTransSocketUNIXCreateListener: mkdir(/tmp/.X11-unix) failed, errno = 28

_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix

Found Java version 1.8.0_242

Available memory: 7966 MB

Using JVM args: -Xmx1991m

Failed to create directory /home/zap/.ZAP/session

Failed to create directory /home/zap/.ZAP/dirbuster

Failed to create directory /home/zap/.ZAP/fuzzers

849 [main] INFO org.zaproxy.zap.DaemonBootstrap - OWASP ZAP 2.9.0 started 11/09/20 10:07:32 with home /home/zap/.ZAP/

927 [main] INFO org.parosproxy.paros.common.AbstractParam - Setting config api.addrs.addr.name = .* was null

928 [main] INFO org.parosproxy.paros.common.AbstractParam - Setting config api.addrs.addr.regex = true was null

930 [main] INFO org.parosproxy.paros.common.AbstractParam - Setting config api.key = FFDMn3jwi4oru2qiwaoehfwjvbnkw324 was null

941 [main] INFO org.parosproxy.paros.network.SSLConnector - Reading supported SSL/TLS protocols...

941 [main] INFO org.parosproxy.paros.network.SSLConnector - Using a SSLEngine...

1206 [main] INFO org.parosproxy.paros.network.SSLConnector - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]

1227 [main] INFO org.parosproxy.paros.extension.option.OptionsParamCertificate - Unsafe SSL renegotiation disabled.

1230 [main] ERROR org.parosproxy.paros.common.AbstractParam - No write access to directory /home/zap/.ZAP/plugin

java.security.InvalidParameterException: No write access to directory /home/zap/.ZAP/plugin

at org.zaproxy.zap.extension.autoupdate.OptionsParamCheckForUpdates.setDownloadDirectory(OptionsParamCheckForUpdates.java:329)

at org.zaproxy.zap.extension.autoupdate.OptionsParamCheckForUpdates.parse(OptionsParamCheckForUpdates.java:99)

at org.parosproxy.paros.common.AbstractParam.load(AbstractParam.java:60)

at org.parosproxy.paros.model.OptionsParam.parse(OptionsParam.java:171)

at org.parosproxy.paros.common.AbstractParam.load(AbstractParam.java:97)

at org.parosproxy.paros.model.Model.init(Model.java:189)

at org.zaproxy.zap.ZapBootstrap.initModel(ZapBootstrap.java:96)

at org.zaproxy.zap.DaemonBootstrap.start(DaemonBootstrap.java:60)

at org.zaproxy.zap.ZAP.main(ZAP.java:123)

1297 [main] FATAL org.zaproxy.zap.DaemonBootstrap -

java.lang.NullPointerException

at org.parosproxy.paros.model.Model.createAndOpenUntitledDb(Model.java:377)

at org.parosproxy.paros.model.Model.init(Model.java:200)

at org.zaproxy.zap.ZapBootstrap.initModel(ZapBootstrap.java:96)

at org.zaproxy.zap.DaemonBootstrap.start(DaemonBootstrap.java:60)

at org.zaproxy.zap.ZAP.main(ZAP.java:123)
```

**Comment by thc202** [comment]
This is most likely a configuration problem not a ZAP issue, ZAP needs permissions to write to its home, otherwise it will not be able to, e.g. install add-ons, create default session, save configurations. The error message could be more explicit/clear though.

**Comment by hazcod** [comment]
Oddly enough I removed the container & images and it magically worked.. weird.
