### ISSUE TITLE
Cannot run ajax spider in .net job anymore

### ISSUE THREAD

**Issue by epanzero** [zaproxy/zaproxy#6174]
**Describe the bug**
We've integrated zap into a weekly job within the .net framework with chrome headless, and have been using it since December of last year. Suddenly a few months ago, the ajax spider completely stopped working.

The reported error is "root element missing". 

Here is the exception:
```
Root element is missing.    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at OWASPZAPDotNetAPI.ClientApi.CallApiRaw(String component, String operationType, String operationName, Dictionary`2 parameters)
   at OWASPZAPDotNetAPI.ClientApi.CallApi(String component, String operationType, String operationName, Dictionary`2 parameters)
   at OWASPZAPDotNetAPI.Generated.AjaxSpider.status()
  ...
```

Running in the Zap GUI, the error is a popup window that says "Failed to start/connect to 'Chrome Headless'. Is the browser available/supported?"

**Expected behavior**
That the ajax spider is able to run as it was before.

**Software versions**
 - ZAP: 2.9.0
 - OS: Windows 10
 - Java: version 8 update 261
 - Browser: chrome 85.0.4183.102

**Errors from the zap.log file**
```
[0127/113421.069:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0127/113743.197:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0127/113808.494:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0127/120855.340:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0127/120959.354:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0127/121206.432:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0127/121206.839:ERROR:ssl_client_socket_impl.cc(935)] handshake failed; returned -1, SSL error code 1, net_error -107
[0329/024336.612:ERROR:process_reader_win.cc(151)] SuspendThread: Access is denied. (0x5)
[0329/024336.612:ERROR:exception_snapshot_win.cc(98)] thread ID 3556 not found in process
[0412/020119.876:ERROR:process_reader_win.cc(151)] SuspendThread: Access is denied. (0x5)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0xdfca7fa000 of 24576 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0xdfc9f8a000 of 852 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0xdfc9f8b000 of 6024 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c70fe0 of 3044 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c71bd0 of 1012 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c721f8 of 118 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72270 of 912 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72602 of 118 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72690 of 58 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72790 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72920 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72ae0 of 126 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c72ec0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c73050 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c734b0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c73640 of 68 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c74780 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c748b0 of 146 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c74990 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c74b20 of 154 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c75c40 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c761d0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c76390 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c76520 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c77944 of 512 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c786d0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c78800 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7ae00 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7af30 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7b0c0 of 80 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7ba70 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7bb10 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7bb60 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7bf20 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7bf70 of 66 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7bfc0 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7c010 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7c0b0 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7c1a0 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7ca40 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7cda0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7cfb0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7daf0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7dc20 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7dd50 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7de80 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7dfb0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e0e0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e210 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e340 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e470 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e5a0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e6d0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e800 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7e930 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c7fff0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c84020 of 54 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.908:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c84d00 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85590 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c855e0 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85680 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85810 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c858b0 of 58 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85950 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85ae0 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85b30 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85b80 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85d10 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85e50 of 68 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85f90 of 66 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c85fe0 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c86030 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c86080 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c86120 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c86170 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c862b0 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c86300 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c870f0 of 76 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c87330 of 80 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c87c20 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c87d50 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c880e0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88210 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88470 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c885a0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c886d0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88800 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88930 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88a60 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88b90 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88cc0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88df0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c88f20 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c89050 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c89180 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c892b0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c893e0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c89510 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c89640 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c898a0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c899d0 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94520 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c946b0 of 66 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94750 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c947f0 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94890 of 66 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c948e0 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94a70 of 66 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94ca0 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94d40 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94de0 of 60 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c94f20 of 58 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5c950b0 of 62 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5cd45a0 of 58 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x275b5cd8660 of 132 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fff9f6f0000 of 384 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fff9fe1dff8 of 512 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffa59124c4 of 512 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffbd59fb90 of 512 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffbd5afd64 of 512 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffbd63c0c8 of 18 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffbd66f4f8 of 40 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffbd66f978 of 48 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:process_memory_win.cc(73)] ReadMemory at 0x7fffbd6753a0 of 64 bytes failed: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x12B)
[0412/020119.923:ERROR:scoped_process_suspend.cc(40)] NtResumeProcess: An attempt was made to access an exiting process. (0xc000010a)
[0528/095025.000:ERROR:process_info.cc(329)] VirtualQueryEx: Access is denied. (0x5)
[0528/095025.000:ERROR:process_info.cc(556)] ReadMemoryInfo failed
[0528/095025.000:ERROR:scoped_process_suspend.cc(40)] NtResumeProcess: An attempt was made to access an exiting process. (0xc000010a)
[0614/020145.418:ERROR:process_info.cc(329)] VirtualQueryEx: Access is denied. (0x5)
[0614/020145.418:ERROR:process_info.cc(556)] ReadMemoryInfo failed
[0614/020145.418:ERROR:scoped_process_suspend.cc(40)] NtResumeProcess: An attempt was made to access an exiting process. (0xc000010a)
```

**Additional context**
the regular spider works just fine

**Would you like to help fix this issue?**
I would very much like help fixing the issue if possible!

**Comment by thc202** [comment]
There's a new version of WebDriver add-on which includes the latest (stable) version of the ChromeDriver that should address this issue. Could you give it a try?

**Comment by epanzero** [comment]
I see linux and macos webdriver addons, is it okay to use one of those with windows 10?

**Comment by epanzero** [comment]
I went ahead and downloaded the linux Webdriver addon, and that did the trick! Thank you for your help.
