### ISSUE TITLE
Firefox/Chrome doesn't start with 20 version of Linux WebDriver at Debian 10.5 stable zap 2.9.0

### ISSUE THREAD

**Issue by Liubimov-it** [zaproxy/zaproxy#6179]
**Describe the bug**
After update Linux WebDriver plugin to 20 version start web browser via manual explore not working, same with Firefox and chrome, before update it worked.

**To Reproduce**
1. Open plugin manager
2. update Linux WebDrivers to 20 version
3. Restart ZAP
4. Open Manual Explore
5. Click at "launch Browser" button opposite "Explore your application"

**Expected behavior**
firefox/chrome should start well

**Software versions**
 - ZAP: 
```
OWASP ZAP
Version: 2.9.0
---
Installed Add-ons: [[id=accessControl, version=5.0.0],
[id=alertFilters, version=10.0.0], [id=ascanrules,
version=36.0.0], [id=ascanrulesBeta, version=31.0.0],
[id=bruteforce, version=9.0.0], [id=commonlib,
version=1.1.0], [id=custompayloads, version=0.9.0],
[id=diff, version=10.0.0], [id=directorylistv1,
version=4.0.0], [id=directorylistv2_3, version=3.0.0],
[id=directorylistv2_3_lc, version=3.0.0], [id=fuzz,
version=13.0.1], [id=fuzzdb, version=7.0.0],
[id=fuzzdboffensive, version=3.0.0], [id=gettingStarted,
version=11.0.0], [id=help, version=10.0.0], [id=hud,
version=0.11.0], [id=importurls, version=7.0.0], [id=invoke,
version=10.0.0], [id=jython, version=10.0.0],
[id=onlineMenu, version=7.0.0], [id=openapi,
version=16.0.0], [id=pscanrules, version=29.0.0],
[id=quickstart, version=28.0.0], [id=replacer,
version=8.0.0], [id=reveal, version=3.0.0],
[id=saverawmessage, version=5.0.0], [id=savexmlmessage,
version=0.1.0], [id=scripts, version=26.0.0], [id=selenium,
version=15.2.0], [id=spiderAjax, version=23.1.0], [id=tips,
version=7.0.0], [id=tokengen, version=13.0.0],
[id=webdriverlinux, version=20.0.0], [id=websocket,
version=22.0.0], [id=zest, version=32.0.0]]
---
Operating System: Linux
Java Version: Debian 11.0.8
System''s Locale: ru_RU
Display Locale: ru_RU
Format Locale: ru_RU
ZAP Home Directory: /home/user/.ZAP/
ZAP Installation Directory: /opt/zaproxy/./
Look and Feel: Nimbus (javax.swing.plaf.nimbus.NimbusLookAndFeel)
```
 - Add-on: Name and version 
`Linux WebDrivers  veriosn: 20.0.0`
 - OS: `Linux linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
 - Java: 
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1deb10u1, mixed mode, sharing)
```
 - Browser: Firefox 80.0.1 (64-bit), Firefox-esr 68.12.0esr (64-bit), Chromium Version 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.5 (64-bit)

**Errors from the zap.log file**
```
1600278590457	geckodriver	INFO	Listening on 127.0.0.1:3210
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/user/.Xauthority which is owned by user)
40320 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch  - Unable to find a matching set of capabilities
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'linux', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.0-10-amd64', java.version: '11.0.8'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
org.openqa.selenium.SessionNotCreatedException: Unable to find a matching set of capabilities
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'linux', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.0-10-amd64', java.version: '11.0.8'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:866)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:786)
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:685)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:553)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:646)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:610)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:596)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:586)
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$2.run(ExtensionQuickStartLaunch.java:240)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Additional context**
By default launched firefox-esr, before update, all worked fine

**Comment by kingthorin** [comment]
Which of the two Firefoxes is in your $PATH?

**Comment by Liubimov-it** [comment]
> Which of the two Firefoxes is in your $PATH?

Firefox-esr
`$ firefox --version
Mozilla Firefox 68.12.0esr`

**Comment by thc202** [comment]
For Firefox see #6115 for a workaround. For Chrome, unfortunately ChromeDriver (now) just targets specific Chrome versions (we bundle the one for latest stable), if you need to work with an older version you'd have to download the corresponding ChromeDriver and specify it in the Selenium options.

https://www.zaproxy.org/docs/desktop/addons/selenium/options/

**Comment by Liubimov-it** [comment]
with latest version of firefox (set firefox binary destiny in parameters -> selenium -> binaries) work well

**Comment by kingthorin** [comment]
Thanks for letting us know.
