### ISSUE TITLE
Unable to import context without session management method

### ISSUE THREAD

**Issue by orionCook** [zaproxy/zaproxy#6206]
[fuse_api.txt](https://github.com/zaproxy/zaproxy/files/5306565/fuse_api.txt)
**Describe the bug**

I receive this error when trying to load in a context file 
`Failed to load context file /zap/wrk/fuse_api.context : internal_error`
It doesn't happen when running the same script (below) with zap2docker-stable

This is the script I'm running to get the error
```docker stop owasp && docker rm owasp
docker pull owasp/zap2docker-weekly
docker create --name=owasp --network="host" -t owasp/zap2docker-weekly
docker start owasp
docker exec owasp mkdir /zap/wrk
docker cp fuse_api.context owasp:/zap/wrk/fuse_api.context
docker cp warnings_config.txt owasp:/zap/wrk/warnings_config.txt
docker cp scan_config.txt owasp:/zap/wrk/scan_config.txt
docker exec owasp zap-api-scan.py -t https://docker.for.win.localhost:8443/openapi.json -f openapi -z "-configfile /zap/wrk/scan_config.txt" -c warnings_config.txt -r report.html -n fuse_api.context -J report.json
```

**To Reproduce**
1. Copy the attached files to a local directory
2. Rename fuse_api.txt to fuse_api.context (it doesn't really matter if this is the context file, though. It still happens with the default context created by the ZAP GUI)
3. replace the target `-t https://docker.for.win.localhost:8443/openapi.json` with your own openapi.json endpoint
4. Run the above script from the directory where you stored the attached files
5. See error

**Expected behavior**
The context file is loaded without an error (as seen when running the above script with `-stable` instead of `-weekly`

**Software versions**
 - ZAP: latest
 - Add-on: N/A
 - OS: Windows 10 & Amazon Linux
 - Java: openjdk 11.0.8 2020-07-14 LTS
 - Browser: N/A

**Errors from the zap.log file**
```
020-09-30 15:02:03,240 [ZAP-daemon] INFO  DaemonBootstrap - ZAP is now listening on 0.0.0.0:33573
2020-09-30 15:02:03,474 [ZAP-ProxyThread-2] ERROR ContextAPI - 'context.session.type' doesn't map to an existing object
java.util.NoSuchElementException: 'context.session.type' doesn't map to an existing object
        at org.apache.commons.configuration.AbstractConfiguration.getInt(AbstractConfiguration.java:816)
        at org.zaproxy.zap.extension.sessions.ExtensionSessionManagement.importContextData(ExtensionSessionManagement.java:212)
        at org.parosproxy.paros.model.Model.importContext(Model.java:552)
        at org.parosproxy.paros.model.Session.importContext(Session.java:1547)
        at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:204)
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:506)
        at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Would you like to help fix this issue?**
Yes, I would.
[scan_config.txt](https://github.com/zaproxy/zaproxy/files/5306556/scan_config.txt)
[warnings_config.txt](https://github.com/zaproxy/zaproxy/files/5306557/warnings_config.txt)

**Comment by thc202** [comment]
Thanks for reporting.

**Comment by thc202** [comment]
This is also happening in 2.9.0, updated accordingly.

**Comment by sabtom** [comment]
Tried it with the current owasp/zap2docker-weekly build 2 days ago as well, but still has the same issue.
Is the image not build from the develop branch? Although I cannot imagine that since master hasn't been commited to in months.
Dockerhub showed that the weekly image was build 2 days ago though?

**Comment by thc202** [comment]
Could you provide the image ID and the exception? Yes, weekly releases are built from the develop branch.

**Comment by sabtom** [comment]
Sure, image ID: 26e7baf904ec
I'm not sure how to get a better exception than this one:
```
2020-10-23 08:58:37,080 Trigger hook: cli_opts, args: 1
2020-10-23 08:58:37,081 Using port: 55686
2020-10-23 08:58:37,081 Trigger hook: start_zap, args: 2
2020-10-23 08:58:37,081 Starting ZAP
2020-10-23 08:58:37,081 Params: ['zap-x.sh', '-daemon', '-port', '55686', '-host', '0.0.0.0', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=0', '-addonupdate', '-addoninstall', 'pscanrulesBeta', '-addoninstall', 'ascanrulesBeta', '-addoninstall', 'pscanrulesAlpha', '-addoninstall', 'ascanrulesAlpha', '-config', 'dirs=/zwp/wrk/custom_scripts', '-config', 'script.enable=zap_http-sender_lytho_token_header.js']
2020-10-23 08:58:37,084 Starting new HTTP connection (1): localhost:55686
[snip]2 more times[/snip]
Oct 23, 2020 8:58:39 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
2020-10-23 08:58:40,092 Starting new HTTP connection (1): localhost:55686
[snip]5 more times[/snip]
2020-10-23 08:58:45,129 http://localhost:55686 "GET http://zap/JSON/core/view/version/ HTTP/1.1" 200 26
2020-10-23 08:58:45,130 ZAP Version D-2020-10-20
2020-10-23 08:58:45,130 Took 8 seconds
2020-10-23 08:58:45,130 Trigger hook: zap_started, args: 2
2020-10-23 08:58:45,130 Trigger hook: zap_import_context, args: 2
2020-10-23 08:58:45,131 Starting new HTTP connection (1): localhost:55686
2020-10-23 08:58:45,176 http://localhost:55686 "GET http://zap/JSON/context/action/importContext/?contextFile=%2Fzap%2Fwrk%2Ftom.context&apikey= HTTP/1.1" 500 52
2020-10-23 08:58:45,177 Failed to load context file /zap/wrk/tom.context : internal_error
```

**Comment by sabtom** [comment]
Hmm, wait a minute, found the  zap.log, might be my fault completely.
Let me get back to you.

**Comment by sabtom** [comment]
The root cause is, that i exported the context with a script in it.
That script cannot be found during the execution in this container. Is there a way to give it the correct file path, or reconfigure the context so it knows where to find the file?

**Comment by thc202** [comment]
You'd have to manually tweak the path in the context file to match the location in the container.

**Comment by sabtom** [comment]
Thank you for the quick response!
Going to check if there's some sort of documentationa available for the context xml :).

**Comment by thc202** [comment]
Sorry, you don't need to edit the context file (it just has the name of the script not the whole path). You do need to add the script (with the same name) into ZAP though.

**Comment by AbhishekPuranam** [comment]
I am still getting error while using context file which points to script based Authentication. Need assistance. 

I generated a Zest script to login and created context with authentication: Script-based Authentication.

Placed both the context file and zest file inside the zap/wrk
root@7332b00851e2:/zap/wrk# ls
ocsm.context  oscm-login.zst

ocsm.context
==============
 <urlparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </urlparser>
        <postparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </postparser>
        <authentication>
            <type>4</type>
            <loggedin>Path=/; SameSite=lax</loggedin>
            <loggedout>Set-Cookie: DOT-CSRF=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT</loggedout>
            <script>
                    <name>oscm-login</name>
                <params/>
            </script>
        </authentication>
        <forceduser>-1</forceduser>
        <session>
            <type>0</type>
        </session>
        <authorization>
            <type>0</type>
            <basic>
==================
When i run the docker 
docker run --user $(id -u):$(id -g) -v $(pwd):/zap/wrk/:rw --rm -t owasp/zap2docker-weekly zap-full-scan.py -t https://x.x.x.x/sysmgr/ -n ocsm.context -d -m 3

I get below error:
```
2020-11-27 16:31:58,958 http://localhost:37843 "GET http://zap/JSON/context/action/importContext/?contextFile=%2Fzap%2Fwrk%2Focsm.context&apikey= HTTP/1.1" 500 52
2020-11-27 16:31:58,959 Failed to load context file /zap/wrk/ocsm.context : internal_error
```
Trying to import the context using zap-cli also gives me error. 
root@7332b00851e2:/zap/wrk# zap-cli -v context import ocsm.context 
[ERROR]           Importing context from file failed: does_not_exist

**Comment by thc202** [comment]
Did you add the script into ZAP? https://www.zaproxy.org/docs/api/#script-based-authentication explains how to add it.

**Comment by AbhishekPuranam** [comment]
I was able successfully load the zest script in the context authentication for zap desktop version, since I placed the zest Script in zap folder. However, the problem I face is when I use the docker version.

**Comment by thc202** [comment]
You can mount a local directory (or copy to the container) to load the script.

**Comment by AbhishekPuranam** [comment]
The script is copied inside the container in zap/wrk folder. I even opened container in interactive mode, went to the folder and did a zap-cli and it gives me internal error. 

To test further I created one more context file which has authentication which is form based. That loaded without any issues in dockerized version. 

Issue is for context files where authentication is via script based.

**Comment by thc202** [comment]
If the script is already in the container you just need to load it before importing the context.

**Comment by thc202** [comment]
You need to load the script with type `authentication`. Also, worth confirming that the script was added to correct home.

**Comment by AbhishekPuranam** [comment]
zest file fails to load script 

```
[root@scspa1961335001 ~]# docker run --detach --name zap -u zap -v "$(pwd)/reports":/zap/reports/:rw \
>   -i owasp/zap2docker-weekly zap.sh -daemon -host 0.0.0.0 -port 8080 \
>   -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true \
>   -config api.disablekey=true
a99c76f3f91930c608477c25582a2b531d13bbac3d373acb51d54c3aea93b3d0
[root@scspa1961335001 ~]# docker exec zap mkdir /zap/wrk
[root@scspa1961335001 ~]# docker cp ocsm.context zap:/zap/wrk/ocsm.context
[root@scspa1961335001 ~]# docker cp oscm-login.zst zap:/zap/wrk/oscm-login.zst
[root@scspa1961335001 ~]# docker exec -u root zap zap-cli -v scripts load -n oscm -t authentication -e 'Zest : Mozilla Zest' -f '/zap/wrk/oscm-login.zst'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 158, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 167, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f40fb421760>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://zap/JSON/script/view/listEngines/?apikey= (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40fb421760>: Failed to establish a new connection: [Errno 111] Connection refused')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zap-cli", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return ctx.invoke(f, ctx.obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/zapcli/commands/scripts.py", line 108, in load_script
    if not _is_valid_script_engine(zap_helper.zap, options['engine']):
  File "/usr/local/lib/python3.8/dist-packages/zapcli/commands/scripts.py", line 124, in _is_valid_script_engine
    engine_names = zap.script.list_engines
  File "/usr/local/lib/python3.8/dist-packages/zapv2/script.py", line 35, in list_engines
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'script/view/listEngines/')))
  File "/usr/local/lib/python3.8/dist-packages/zapv2/__init__.py", line 192, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python3.8/dist-packages/zapv2/__init__.py", line 172, in _request_api
    response = self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: http://zap/JSON/script/view/listEngines/?apikey= (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40fb421760>: Failed to establish a new connection: [Errno 111] Connection refused')))



[root@scspa1961335001 ~]# docker exec -u root -it zap /bin/bash
root@a99c76f3f919:/zap# 
root@a99c76f3f919:/zap# ls
AcceptedLicense  README  lang  license  reports  webswing  xml                   zap-api-scan.py  zap-full-scan.py  zap-x.sh  zap.ico  zap_common.py
CHANGELOG.md     db      lib   plugin   scripts  wrk       zap-D-2020-11-23.jar  zap-baseline.py  zap-webswing.sh   zap.bat   zap.sh
root@a99c76f3f919:/zap# cd wrk
root@a99c76f3f919:/zap/wrk# ls
ocsm.context  oscm-login.zst
root@a99c76f3f919:/zap/wrk# zap-cli -v scripts load -n oscm -t authentication -e 'Zest : Mozilla Zest' -f '/zap/wrk/oscm-login.zst'
[DEBUG]           Loading script "oscm" from "/zap/wrk/oscm-login.zst"
[INFO]            Script "oscm" loaded
root@a99c76f3f919:/zap/wrk# 

root@a99c76f3f919:/zap/wrk# ls
ocsm.context  oscm-login.zst
root@a99c76f3f919:/zap/wrk#

**Comment by AbhishekPuranam** [comment]
Thanks created a new container and loaded  the script with type authentication. However, still unable to load the context. 
+----------------------------------+----------------+----------------+-----------+
| oscm                             | authentication | Mozilla Zest   | N/A       |
+----------------------------------+----------------+----------------+-----------+
```
root@a99c76f3f919:/zap/wrk# zap-cli context import ocsm.context 
[ERROR]           Importing context from file failed: does_not_exist
root@a99c76f3f919:/zap/wrk# ls
ocsm.context  oscm-login.zst
root@a99c76f3f919:/zap/wrk# 

docker exec -u root zap zap-full-scan.py -t https://x.x.x.x/sysmgr/v4/ -n /zap/wrk/ocsm.context -d -m 3

2020-11-30 05:40:01,949 http://localhost:35137 "GET http://zap/JSON/context/action/importContext/?contextFile=%2Fzap%2Fwrk%2Focsm.context&apikey= HTTP/1.1" 500 52
2020-11-30 05:40:01,949 Failed to load context file /zap/wrk/ocsm.context : internal_error

**Comment by AbhishekPuranam** [comment]
Below is zest file

```
root@a99c76f3f919:/zap/wrk# cat oscm-login.zst 
{
  "about": "This is a Zest script. For more details about Zest visit https://developer.mozilla.org/en-US/docs/Zest",
  "zestVersion": "0.8",
  "title": "oscm-login",
  "description": "",
  "prefix": "https://x.x.x.x/security",
  "type": "StandAlone",
  "parameters": {
    "tokenStart": "{{",
    "tokenEnd": "}}",
    "tokens": {},
    "elementType": "ZestVariables"
  },
  "statements": [
    {
      "url": "https://x.x.x.x/security/login",
      "data": "",
      "method": "POST",
      "headers": "Authorization: Basic YWRtaW46TmV0YXBwMSE\u003d\r\nDOT-Request-CSRF-Token: true\r\nOrigin: https://x.x.x.x\r\nContent-Type: text/plain; charset\u003dISO-8859-1\r\nContent-Length: 0\r\n",
      "response": {
        "url": "https://x.x.x.x/security/login",
        "headers": "HTTP/1.1 200 OK\r\nDate: Fri, 27 Nov 2020 07:23:19 GMT\r\nServer: Apache\r\nX-Content-Type-Options: nosniff\r\nSet-Cookie: DOT-CSRF\u003d0D30231C9F1C67BE51C7C3637C97ED925F682DE1F34EE75CD170F330790C6536; Path\u003d/; SameSite\u003dlax\r\nContent-Length: 0\r\nKeep-Alive: timeout\u003d5, max\u003d100\r\nConnection: Keep-Alive\r\n\r\n",
        "body": "",
        "statusCode": 200,
        "responseTimeInMs": 1050,
        "elementType": "ZestResponse"
      },
      "assertions": [
        {
          "rootExpression": {
            "code": 200,
            "not": false,
            "elementType": "ZestExpressionStatusCode"
          },
          "elementType": "ZestAssertion"
        },
        {
          "rootExpression": {
            "length": 0,
            "approx": 1,
            "variableName": "response.body",
            "not": false,
            "elementType": "ZestExpressionLength"
          },
          "elementType": "ZestAssertion"
        }
      ],
      "followRedirects": false,
      "timestamp": 1606461798278,
      "cookies": [],
      "index": 1,
      "enabled": true,
      "elementType": "ZestRequest"
    }
  ],
  "authentication": [
    {
      "site": "x.x.x.x",
      "realm": "",
      "username": "admin",
      "password": "password",
      "elementType": "ZestHttpAuthentication"
    }
  ],
  "index": 0,
  "enabled": true,
  "elementType": "ZestScript"
}

**Comment by AbhishekPuranam** [comment]
Below is context file
```
root@a99c76f3f919:/zap/wrk# cat ocsm.context 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
    <context>
        <name>ocsm</name>
        <desc/>
        <inscope>true</inscope>
        <incregexes>https://10.216.13.76.*</incregexes>
        <tech>
            <include>Db</include>
            <include>Db.CouchDB</include>
            <include>Db.Firebird</include>
            <include>Db.HypersonicSQL</include>
            <include>Db.IBM DB2</include>
            <include>Db.Microsoft Access</include>
            <include>Db.Microsoft SQL Server</include>
            <include>Db.MongoDB</include>
            <include>Db.MySQL</include>
            <include>Db.Oracle</include>
            <include>Db.PostgreSQL</include>
            <include>Db.SAP MaxDB</include>
            <include>Db.SQLite</include>
            <include>Db.Sybase</include>
            <include>Language</include>
            <include>Language.ASP</include>
            <include>Language.C</include>
            <include>Language.JSP/Servlet</include>
            <include>Language.Java</include>
            <include>Language.JavaScript</include>
            <include>Language.PHP</include>
            <include>Language.Python</include>
            <include>Language.Ruby</include>
            <include>Language.XML</include>
            <include>OS</include>
            <include>OS.Linux</include>
            <include>OS.MacOS</include>
            <include>OS.Windows</include>
            <include>SCM</include>
            <include>SCM.Git</include>
            <include>SCM.SVN</include>
            <include>WS</include>
            <include>WS.Apache</include>
            <include>WS.IIS</include>
            <include>WS.Tomcat</include>
        </tech>
        <urlparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </urlparser>
        <postparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </postparser>
        <authentication>
            <type>4</type>
            <loggedin>Path=/; SameSite=lax</loggedin>
            <loggedout>Set-Cookie: DOT-CSRF=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT</loggedout>
            <script>
		    <name>oscm-login</name>
                <params/>
            </script>
        </authentication>
        <forceduser>-1</forceduser>
        <session>
            <type>0</type>
        </session>
        <authorization>
            <type>0</type>
            <basic>
                <header>Content-Length: 381</header>
                <body>Unauthorized</body>
                <logic>AND</logic>
                <code>401</code>
            </basic>
        </authorization>
    </context>
</configuration>

**Comment by thc202** [comment]
In the context the script is named `oscm-login` but the script is being loaded with name `oscm`.

**Comment by AbhishekPuranam** [comment]
Thanks again, I was not able to import the context using the zap-cli. However, when i run zap-full-scan.py, still i get the  internal_error. 

```
root@1d763258270f:/zap/wrk# zap-cli context info ocsm
[INFO]            ID: 1
[INFO]            Name: ocsm
[INFO]            Authentication type: Script-based Authentication
[INFO]            Included regexes: ["https://x.x.x.x*"]
[INFO]            Excluded regexes: []

zap-full-scan.py -t https://x.x.x.x/sysmgr/v4/ -n /zap/wrk/ocsm.context -d -m 3

2020-11-30 13:02:25,999 http://localhost:58063 "GET http://zap/JSON/context/action/importContext/?contextFile=%2Fzap%2Fwrk%2Focsm.context&apikey= HTTP/1.1" 500 52
2020-11-30 13:02:25,999 Failed to load context file /zap/wrk/ocsm.context : internal_error

**Comment by kingthorin** [comment]
zap-cli is a third party interface for zap it has nothing to do with zap-full-scan.py.
