### ISSUE TITLE
ZAP Proxy not intercepting requests from Genymotion

### ISSUE THREAD

**Issue by JacobPimental** [zaproxy/zaproxy#6208]
**Describe the bug**
Hi all, I've been trying to analyze traffic from an Android emulator hosted in Genymotion in ZAP but I am not seeing any requests. I have not had this issue before and did not change any settings as far as I am aware. I set logging to DEBUG to see what was going on and am seeing a lot of "certificate_unknown" errors, but I am not sure how to fix it.

**To Reproduce**
1. Set Genymotion proxy to 10.0.3.2 (special IP for localhost)
2. Go to website in Genymotion emulator
3. No results appear in ZAP

**Expected behavior**
Visited sites appearing in the history field and for emulator to go to website.

**Screenshots**
![image](https://user-images.githubusercontent.com/12945366/94874255-90840300-041f-11eb-9da3-00377c12a7cb.png)

Site hangs in Genymotion:
![image](https://user-images.githubusercontent.com/12945366/94874272-9bd72e80-041f-11eb-9e82-710d1beacc86.png)

**Software versions**
 - ZAP: D-2020-09-29
 - OS: Manjaro
 - Java: openjdk_11

**Errors from the zap.log file**
```log
706085 [ZAP-ProxyThread-14] DEBUG org.parosproxy.paros.core.proxy.ProxyThread  - IOException: 
java.io.IOException: Error while establishing SSL connection for 'www.google.com'!
        at org.parosproxy.paros.core.proxy.ProxyThread.beginSSL(ProxyThread.java:241)
        at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:316)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1475)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1381)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)
        at org.parosproxy.paros.network.SSLConnector.createTunnelServerSocket(SSLConnector.java:609)
        at org.parosproxy.paros.core.proxy.ProxyThread.beginSSL(ProxyThread.java:227)
        ... 2 more
```

**Comment by arpitrohela** [comment]
Hello @JacobPimental, Can you please let us know if you have made sure to add certificate of zap on to the device and made sure it is properly installed?

**Comment by JacobPimental** [comment]
Hi @arpitrohela, the certificate is installed on the device and was working in the past. I was unsure if this was due to a recent update or not.

**Comment by kingthorin** [comment]
@JacobPimental did you sort this out?

>I was unsure if this was due to a recent update or not.

**Comment by kingthorin** [comment]
The error means the client didn't accept the ZAP cert, so a client side configuration (maybe the cert is no longer the same, ZAP home change or new cert created).
