### ISSUE TITLE
Exception while authenticating with form-based and anti-csrf tokens

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#6223]
**Describe the bug**
An exception occurs while authenticating:
```
170689 [Thread-7] ERROR org.zaproxy.zap.authentication.PostBasedAuthenticationMethodType  - Unable to prepare authentication message: Index 0 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.zaproxy.zap.authentication.PostBasedAuthenticationMethodType$PostBasedAuthenticationMethod.extractParametersFromPostData(PostBasedAuthenticationMethodType.java:458)
	at org.zaproxy.zap.authentication.PostBasedAuthenticationMethodType$PostBasedAuthenticationMethod.replaceAntiCsrfTokenValueIfRequired(PostBasedAuthenticationMethodType.java:420)
	at org.zaproxy.zap.authentication.PostBasedAuthenticationMethodType$PostBasedAuthenticationMethod.authenticate(PostBasedAuthenticationMethodType.java:339)
	at org.zaproxy.zap.users.User.authenticate(User.java:265)
	at org.zaproxy.zap.users.User.processMessageToMatchUser(User.java:175)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:581)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup form-based authentication that uses anti-csrf tokens, but do not include the login page in the context.
2. Try to authenticate.

**Expected behaviour**
No exception.

**Software versions**
 - ZAP: 2.9.0

**Comment by thc202** [comment]
(Reported in IRC channel.)
