### ISSUE TITLE
Recording a new Zest script get stucks with bigger http messages

### ISSUE THREAD

**Issue by rshursti** [zaproxy/zaproxy#6241]
Recording a new Zest script get stuck with bigger (over 1MB) http messages.
I also disabled all the passive scan rules so that Zap can handle http messages quicker.
It takes several minutes that Zap reacts user's actions.
Also Zap prints error messages:

358098 [ZAP-ProxyThread-164] ERROR org.zaproxy.zap.extension.hud.HudAPI  - No such file /target/injectionHtml.html
java.io.FileNotFoundException: target/injectionHtml.html
	at org.zaproxy.zap.extension.hud.HudAPI.getFile(HudAPI.java:424)
	at org.zaproxy.zap.extension.hud.ExtensionHUD.onHttpResponseReceive(ExtensionHUD.java:375)
...
359904 [ZAP-ProxyThread-170] ERROR org.zaproxy.zap.extension.hud.ExtensionHUD  - 
java.lang.NullPointerException
	at org.zaproxy.zap.extension.hud.ExtensionHUD.onHttpResponseReceive(ExtensionHUD.java:378)
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyListenerResponseReceive(ProxyThread.java:764)

**Comment by psiinon** [comment]
If you are recording scripts then disable the HUD - that will only confuse things :)

**Comment by thc202** [comment]
This has the same cause as #5791, the fix done in core should be applied to the Script Console add-on.
