### ISSUE TITLE
Exception while loading session in weeklies

### ISSUE THREAD

**Issue by hnestorova** [zaproxy/zaproxy#6265]
**Describe the bug**
We run our recorded clean sessions using Jenkins and get the error below . This is not the case before we upgraded 

**To Reproduce**
From the Jenkins console:
```
16:31:31 65740 [ZAP-ProxyThread-2] ERROR org.parosproxy.paros.model.SiteMap - null
16:31:31 java.lang.NullPointerException: null
16:31:31 	at org.parosproxy.paros.network.HttpRequestHeader.setMethod(HttpRequestHeader.java:325) ~[zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.model.Session.getLeafName(Session.java:1733) ~[zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.model.SiteMap.findNode(SiteMap.java:279) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.model.SiteMap.findNode(SiteMap.java:248) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:634) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.restructureSiteTreeEventHandler(Context.java:608) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.model.Context.restructureSiteTree(Context.java:588) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.model.Session.open(Session.java:535) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.model.Model.openSession(Model.java:143) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.control.Control.runCommandLineOpenSession(Control.java:430) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.extension.api.CoreAPI.handleApiAction(CoreAPI.java:586) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:506) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335) [zap-D-2020-10-20.jar:D-2020-10-20]
16:31:31 	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Expected behavior**
No such errors

**Software versions**
Official OWASP ZAP Jenkins Plugin - 1.1.0
ZAP D-2020-10-20
Browser: Chrome

**Errors from the zap.log file**
```
2020-10-28 16:30:34,054 [ZAP-daemon] INFO  ExtensionCallback - Started callback server on 0.0.0.0:49443
2020-10-28 16:30:34,407 [ZAP-daemon] INFO  DaemonBootstrap - ZAP is now listening on 127.0.0.1:8090
2020-10-28 16:30:34,946 [ZAP-ProxyThread-2] INFO  ENGINE - dataFileCache commit start
2020-10-28 16:30:34,947 [ZAP-ProxyThread-2] INFO  ENGINE - dataFileCache commit end
2020-10-28 16:30:34,953 [ZAP-ProxyThread-2] INFO  ENGINE - Database closed
2020-10-28 16:30:35,142 [ZAP-ProxyThread-2] INFO  ENGINE - dataFileCache open start
2020-10-28 16:30:35,146 [ZAP-ProxyThread-2] INFO  ENGINE - dataFileCache open end
2020-10-28 16:31:11,061 [ZAP-ProxyThread-2] ERROR SiteMap - null
java.lang.NullPointerException: null
	at org.parosproxy.paros.network.HttpRequestHeader.setMethod(HttpRequestHeader.java:325) ~[zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.model.Session.getLeafName(Session.java:1733) ~[zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.model.SiteMap.findNode(SiteMap.java:279) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.model.SiteMap.findNode(SiteMap.java:248) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.model.Context.checkNode(Context.java:634) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.model.Context.checkNode(Context.java:618) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.model.Context.restructureSiteTreeEventHandler(Context.java:608) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.model.Context.restructureSiteTree(Context.java:588) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.model.Session.open(Session.java:535) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.model.Model.openSession(Model.java:143) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.control.Control.runCommandLineOpenSession(Control.java:430) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.extension.api.CoreAPI.handleApiAction(CoreAPI.java:586) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:506) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:499) [zap-D-2020-10-20.jar:D-2020-10-20]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:335) [zap-D-2020-10-20.jar:D-2020-10-20]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-28 16:31:11,158 [ZAP-ProxyThread-2] ERROR SiteMap - null
java.lang.NullPointerException: null
	at org.parosproxy.paros.network.HttpRequestHeader.setMethod(HttpRequestHeader.java:325) ~[zap-D-2020-10-20.jar:D-2020-10-20]
```

**Would you like to help fix this issue?**
Just say if you'd like to try and help fix this issue. We'll provide any advice and guidance you need.

**Comment by thc202** [comment]
This is being worked on, should be fixed in the next weekly.

**Comment by hnestorova** [comment]
Thanks! Please, let me know when ready
It seems we fail here:

04:31:11 8800 [ZAP-ProxyThread-2] INFO org.parosproxy.paros.control.Control  - Session file opened

**Comment by psiinon** [comment]
@hnestorova this should not prevent ZAP from working - are you actually having any problems with ZAP?

**Comment by hnestorova** [comment]
@psiinon  what I have noticed in addition to the NPEs in the logs is the following:

Before the version upgrade, for one of our recorded clean sessions we got 2 high alerts:

Source Code Disclosure -   File Inclusion
http://PRIVATE/PRIVATE/resources/get?id=JS&ver=655406725
--
SQL Injection
GET : http://PRIVATE/PRIVATE/login.jsp?%2FPRIVATE%2F=+AND+1%3D1+--+

Then, after the upgrade, the high alerts disappeared. Yesterday, I recorded again the session, run the Jenkins job and got one of the two alerts types:
SQL Injection 

GET   : http://PRIVATE/PRIVATE/login.jsp?%2FCognity=&userName=USER+AND+1%3D1+--+
--


Today, after our daily run of the tests and with no fixes from our side, the high alert is again not present

**Comment by psiinon** [comment]
Yes, that can happen.
For complex real world apps the ZAP spidering is not completely deterministic - sometimes some urls will be found in one scan and not in another. Thats because of timing issues and because apps change over time.
You should investigate any issues found to see if they are real issues or false positives.
Ideally you should examine the URLs found and compare see how effectively ZAP is exploring your app. If its missing significant parts then see if tuning ZAP helps, and/or reporting the problem to us of course.

**Comment by hnestorova** [comment]
@psiinon yes, this sounds reasonable
the problem, however, is that with the previous version we had the same exceptions each day + maybe some new ones. But the SQL Injection and Source Code Disclosure -   File Inclusion were known to us and they did get caught every day while after the upgrade this is not the case. So i am not sure how to approach this.

**Comment by kingthorin** [comment]
No matter what it is it’s not related to the issue this ticket is for. Please take the discussion of this second topic to the [user group](https://groups.google.com/g/zaproxy-users)

**Comment by hnestorova** [comment]
sure , I will.
I was just answering the questions by psiinon
