### ISSUE TITLE
Saving configuration fails with INVALID_CHARACTER_ERR, config is 0 in size.

### ISSUE THREAD

**Issue by wadim-al** [zaproxy/zaproxy#6287]
**Describe the bug**
After installing the latest weekly build it fails to generate the default configuration, or trying to edit it via GUI fails with error.

**To Reproduce**
1. Install latest weekly to c:\zap
2. Create c:\zap\data folder
3. Run zap with 
set jvmopts=-Xmx6192m -Dsun.java2d.noddraw=true
java %jvmopts% -jar "zap.jar" -installdir C:\\zap\\ -dir C:\\zap\\data -host 192.168.0.2 -port 8080
4. Open Tools-Options - click Ok
5. See error
6. Quit ZAP
7. Check data dir for config file > 0 in size.

**Expected behavior**
Config saved.

**Actual behavior**
Config not saved. (0 size), error in log.

**Screenshots**
![java-2020-11-10-13-42-00](https://user-images.githubusercontent.com/29713984/98663759-8c220280-235a-11eb-9a16-8d8d4e3658a8.png)

**Software versions**
 - ZAP: ZAP_WEEKLY_D-2020-10-26
 - OS: Windows 10 x64 2004
 - Java: Oracle JRE 1.8.0_251

**Errors from the zap.log file**
```
2020-11-10 13:37:20,171 [ZAP-Shutdown] ERROR Control - Error saving configurations:
org.apache.commons.configuration.ConfigurationException: org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at org.apache.commons.configuration.XMLConfiguration.createDocument(XMLConfiguration.java:914) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.XMLConfiguration.save(XMLConfiguration.java:1034) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration$FileConfigurationDelegate.save(AbstractHierarchicalFileConfiguration.java:570) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.save(AbstractFileConfiguration.java:557) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.save(AbstractFileConfiguration.java:524) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.save(AbstractFileConfiguration.java:474) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.save(AbstractFileConfiguration.java:414) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.save(AbstractHierarchicalFileConfiguration.java:214) ~[commons-configuration-1.10.jar:1.10]
	at org.parosproxy.paros.control.Control.saveConfigurations(Control.java:218) [zap.jar:D-2020-10-26]
	at org.parosproxy.paros.control.Control.shutdown(Control.java:212) [zap.jar:D-2020-10-26]
	at org.parosproxy.paros.control.Control$1.run(Control.java:288) [zap.jar:D-2020-10-26]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createElement(Unknown Source) ~[?:1.8.0_251]
	at org.apache.commons.configuration.XMLConfiguration$XMLBuilderVisitor.insert(XMLConfiguration.java:1529) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.HierarchicalConfiguration$BuilderVisitor.visitBeforeChildren(HierarchicalConfiguration.java:1734) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.HierarchicalConfiguration$Node.visit(HierarchicalConfiguration.java:1401) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.XMLConfiguration$XMLBuilderVisitor.processDocument(XMLConfiguration.java:1504) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.XMLConfiguration.createDocument(XMLConfiguration.java:908) ~[commons-configuration-1.10.jar:1.10]
	... 11 more
```

**Additional context**
Previous workaround to select fuzzer category fails.
Manually providing a working config from a previous install doesn't help, because it is being corrupted on exit.

**Would you like to help fix this issue?**
Yes

**Comment by thc202** [comment]
Which option are being changed? Or, is just opening and closing the Options dialogue?

**Comment by wadim-al** [comment]
For that build just opening closing, OR just closing fresh zap fails to save anything to config, OR good config being not saved (0 size file) after just closing zap.

**Comment by thc202** [comment]
Not able to reproduce that, could you try with the previous weekly? (Or even with 2.9.0.)

**Comment by wadim-al** [comment]
Reproduced only when using custom data dir with ZAP_WEEKLY_D-2020-09-29 and a new install.
Previous ZAP_WEEKLY_D-2020-09-29 install doesn't have this problem, only new ZAP_WEEKLY_D-2020-09-29 install. Can't determine the cause. Not version dependent.

**Comment by wadim-al** [comment]
Ok, the steps are not full, investigating.

**Comment by wadim-al** [comment]
I can't reproduce no more, configuration related.
