### ISSUE TITLE
Chrome crashes immediately when starting from manual explore

### ISSUE THREAD

**Issue by dan-lind** [zaproxy/zaproxy#6308]
**Describe the bug**
Doing manual explore and choosing Chrome, when pressing "Launch browser" chrome starts and then immidiately exits without any error message. Looking in the zap,log I see " This version of ChromeDriver only supports Chrome version 79" (full stacktrace below)

**To Reproduce**
1. Manual explore
2. Select "Chrome" as the browser
3. Press "Launch browser"
4. (HUD enabled or disabled doesn't make a difference)

**Expected behavior**
Chrome starts as normal 

**Screenshots**
N/A

**Software versions**
 - ZAP: 2.9
 - Add-on: N/A
 - OS: Windows 10
 - Java: 11.0.9.1
 - Browser: chrome 87.0.4280.66

**Errors from the zap.log file**
```
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 79
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'RD0066943', ip: '10.201.33.183', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.9.1'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00EFA113+1548563]
	Ordinal0 [0x00E7DDA1+1039777]
	Ordinal0 [0x00DFE485+517253]
	Ordinal0 [0x00D8FD34+64820]
	Ordinal0 [0x00D8C61E+50718]
	Ordinal0 [0x00DAB797+178071]
	Ordinal0 [0x00DAB59D+177565]
	Ordinal0 [0x00DA95FB+169467]
	Ordinal0 [0x00D9160A+71178]
	Ordinal0 [0x00D92690+75408]
	Ordinal0 [0x00D92629+75305]
	Ordinal0 [0x00E971B7+1143223]
	GetHandleVerifier [0x00F92B46+507814]
	GetHandleVerifier [0x00F92864+507076]
	GetHandleVerifier [0x00F99F47+537511]
	GetHandleVerifier [0x00F93402+510050]
	Ordinal0 [0x00E8F29C+1110684]
	Ordinal0 [0x00E9938B+1151883]
	Ordinal0 [0x00E994F3+1152243]
	Ordinal0 [0x00E983F5+1147893]
	BaseThreadInitThunk [0x772D6359+25]
	RtlGetAppContainerNamedObjectPath [0x774B7C24+228]
	RtlGetAppContainerNamedObjectPath [0x774B7BF4+180]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:728)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:700)
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:639)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:509)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:602)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:566)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:552)
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:542)
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$2.run(ExtensionQuickStartLaunch.java:227)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Would you like to help fix this issue?**
Sure!

**Comment by psiinon** [comment]
Check for updates and then install the latest webdrivers.
FYI the latest ones we have support Chrome 86 but it looks like there are new ones for 87, will update to support those asap..

**Comment by dan-lind** [comment]
Tried updating and the it now says that my windows webdrivers are on v22.0.0.
Strangely though I still get "This version of ChromeDriver only supports Chrome version 79"

**Comment by psiinon** [comment]
Have you tried restarting ZAP?
The update for Chrome 87 is pending...

**Comment by dan-lind** [comment]
Yep, Zip restarted. Let me know when that update is out and I'll test it ASAP.

**Comment by psiinon** [comment]
The new webdrivers are available now.
If you're still not picking them up after updating then go to Options / Selenium and make sure that you select the "Bundled" ChromeDriver

**Comment by dan-lind** [comment]
Updated, v23.0.0 now. Still the same error... Check options, clicked "Bundled". This is the path.
C:\Users\<myuserid>\OWASP ZAP\webdriver\windows\32\chromedriver.exe
Tried restarting, same thing...

**Comment by thc202** [comment]
Remove that file and start ZAP again.

**Comment by dan-lind** [comment]
Yeah, something was fishy with that. Tried removing it after closing ZAP, but got an error saying the file was still in use. Opened up the activity manager and hade something like 30 instances of chromedriver.exe running. Killed all of them and restarted, now it works! :-) 
The strange thing is that this was a completly fresh install of Zap. 

Anyway, thanks so much!

**Comment by psiinon** [comment]
Np.
Windows can be a pain in preventing files in use from being deleted - thats almost certainly why ZAP was unable to replace it when updating the webdrivers.
