### ISSUE TITLE
Unable to run the docker zap-full-scan.py with context which is aligned to script-based authentication.

### ISSUE THREAD

**Issue by AbhishekPuranam** [zaproxy/zaproxy#6401]
**Describe the bug**
Continuation of the issue: https://github.com/zaproxy/zaproxy/issues/6206#issuecomment-735795934
Unable to run the docker zap-full-scan.py with context which is aligned to script-based authentication.

**To Reproduce**

Went to ZAP Desktop, Created context: project.context, created project_login.zst. Updated the authentication to scriptbased and loaded project_login.zst. exported the context 

Created a container: 
docker run --detach --name zap -u zap -v "$(pwd)/reports":/zap/reports/:rw \
  -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 \
  -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true \
  -config api.disablekey=true

docker exec zap mkdir /zap/wrk
docker cp project.context zap:/zap/wrk/project.context
docker cp project_login.zst zap:/zap/wrk/project_login.zst

docker exec -u root zap zap-baseline.py -t https://project.com -n project.context -d -m 3
2021-01-15 08:57:44,389 Could not find custom hooks file at /home/zap/.zap_hooks.py 
2021-01-15 08:57:44,390 Trigger hook: cli_opts, args: 1
2021-01-15 08:57:44,390 Using port: 59254
2021-01-15 08:57:44,390 Trigger hook: start_zap, args: 2
2021-01-15 08:57:44,390 Starting ZAP
2021-01-15 08:57:44,391 Params: ['zap-x.sh', '-daemon', '-port', '59254', '-host', '0.0.0.0', '-config', 'database.recoverylog=false', '-config', 'api.disablekey=true', '-config', 'api.addrs.addr.name=.*', '-config', 'api.addrs.addr.regex=true', '-config', 'spider.maxDuration=3', '-addonupdate', '-addoninstall', 'pscanrulesBeta']
2021-01-15 09:00:22,261 http://localhost:59254 "GET http://zap/JSON/context/action/importContext/?contextFile=%2Fzap%2Fwrk%2Fproject.context&apikey= HTTP/1.1" 500 52
2021-01-15 09:00:22,262 Failed to load context file /zap/wrk/keystone.context : internal_error

**Expected behavior**
docker should authenticate by understanding the zest script which is aligned to the context file. Else ZAP docker should be able to talk to Zest file directly to authenticate. 

**Screenshots**

**Software versions**
 - ZAP: docker stable and weekly
 - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]
 - OS: docker
 - Browser: Headless

**Comment by psiinon** [comment]
Do you know why its trying to load keystone.context via the call GET http://zap/JSON/context/action/importContext/?contextFile=%2Fzap%2Fwrk%2Fkeystone.context&apikey=
That looks very confusing to me.

**Comment by AbhishekPuranam** [comment]
had replaced keystone with project everywhere to avoid sensitive information in public git.

**Comment by psiinon** [comment]
Did you notice `Failed to load context file /zap/wrk/keystone.context : internal_error` ?
Have you updated the context file to point to the new script location, ie /zap/wrk/project_login.zst ?

**Comment by thc202** [comment]
Also better check the zap.log which should contain more information.

**Comment by AbhishekPuranam** [comment]
This is the authentication part of the context. context file and zst file are in same location.
 
<authentication>
            <type>4</type>
            <strategy>EACH_REQ_RESP</strategy>
            <pollurl/>
            <polldata/>
            <pollheaders/>
            <pollfreq>60</pollfreq>
            <pollunits>REQUESTS</pollunits>
            <loggedin>Content-Length: 47</loggedin>
            <loggedout>Pragma: no-cache</loggedout>
            <script>
                <name>project_login</name>
                <params/>
            </script>
        </authentication>
        <forceduser>-1</forceduser>
        <session>
            <type>0</type>
        </session>
        <authorization>
            <type>0</type>
            <basic>
                <header>Pragma: no-cache</header>
                <body>Authentication succeeeded.</body>
                <logic>AND</logic>
                <code>200</code>
            </basic>
        </authorization>
    </context>
</configuration>

**Comment by thc202** [comment]
At which point are you adding the script to ZAP? Does not seem to be being done.

**Comment by AbhishekPuranam** [comment]
Unable to find script while loading Script Based Authentication Method for name: project_login
```
57545 [ZAP-ProxyThread-4] ERROR org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType - Unable to find script while loading Script Based Authentication Method for name: project_login
157597 [ZAP-ProxyThread-4] ERROR org.zaproxy.zap.extension.api.ContextAPI - null
java.lang.NullPointerException: null
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType.persistMethodToSession(ScriptBasedAuthenticationMethodType.java:754) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.authentication.ExtensionAuthentication.persistContextData(ExtensionAuthentication.java:407) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.model.Model.saveContext(Model.java:547) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.model.Session.saveContext(Session.java:1306) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1605) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:279) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:507) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:497) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by thc202** [comment]
You need to add the script beforehand, e.g. using hooks or specifying the config.xml.

**Comment by AbhishekPuranam** [comment]
> At which point are you adding the script to ZAP? Does not seem to be being done.

Once I create a container, I add it 
```
Created a container:
docker run --detach --name zap -u zap -v "$(pwd)/reports":/zap/reports/:rw
-i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080
-config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
-config api.disablekey=true

docker exec zap mkdir /zap/wrk
docker cp project.context zap:/zap/wrk/project.context
docker cp project_login.zst zap:/zap/wrk/project_login.zst

**Comment by thc202** [comment]
That does not add it to ZAP just to the container. e.g. https://www.zaproxy.org/faq/how-do-you-add-a-script-to-zap-from-the-command-line/

**Comment by AbhishekPuranam** [comment]
Don't know if the command executed properly
```
./zap.sh -config script.scripts.name="project"
Found Java version 11.0.9.1
Available memory: 7822 MB
Using JVM args: -Xmx1955m
1915 [main] INFO  org.zaproxy.zap.GuiBootstrap - OWASP ZAP 2.10.0 started 15/01/2021, 11:44:08 with home /root/.ZAP/
1921 [main] FATAL org.zaproxy.zap.GuiBootstrap - ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.
ZAP GUI is not supported on a headless environment.
Run ZAP inline or in daemon mode, use -help command line argument for more details.

**Comment by psiinon** [comment]
If thats all you specified then no, it will not have added the script. You need to specify all of the parameters detailed in https://www.zaproxy.org/faq/how-do-you-add-a-script-to-zap-from-the-command-line/

**Comment by thc202** [comment]
You also need to start ZAP in command line or daemon mode, or pass the arguments when running the scan script (e.g. `-z`).

**Comment by AbhishekPuranam** [comment]
I think this time, it was able to load the context file. 
```
root@4216e567abab:/zap# zap.sh -cmd -config script.scripts.name=“project”
Found Java version 11.0.9.1
Available memory: 7822 MB
Using JVM args: -Xmx1955m
root@4216e567abab:/zap# zap.sh -cmd -config script.scripts.engine="Mozilla Zest"
Found Java version 11.0.9.1
Available memory: 7822 MB
Using JVM args: -Xmx1955m
root@4216e567abab:/zap# zap.sh -cmd -config script.scripts.type=authentication
Found Java version 11.0.9.1
Available memory: 7822 MB
Using JVM args: -Xmx1955m
root@4216e567abab:/zap# zap.sh -cmd -config script.scripts.enabled=true
Found Java version 11.0.9.1
Available memory: 7822 MB
Using JVM args: -Xmx1955m
root@4216e567abab:/zap# zap.sh -cmd -config script.scripts.file="/zap/wrk/project_login.zst"
Found Java version 11.0.9.1
Available memory: 7822 MB
Using JVM args: -Xmx1955m

```
However, I am getting error in parsing the zest file. Zest file was able to login successfully from UI. 

```
7455 [ZAP-daemon] INFO  org.parosproxy.paros.extension.ExtensionLoader - Initializing Allows to fuzz WebSocket messages.
7456 [ZAP-daemon] INFO  org.parosproxy.paros.extension.ExtensionLoader - Initializing Passive Scan Rules - beta
7465 [ZAP-daemon] INFO  org.zaproxy.zap.extension.callback.ExtensionCallback - Started callback server on 0.0.0.0:38696
9947 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on update check complete
9951 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on already installed: /root/.ZAP/plugin/pscanrulesBeta-beta-24.zap
9955 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Downloading add-on from: https://github.com/zaproxy/zap-extensions/releases/download/ascanrulesBeta-v33/ascanrulesBeta-beta-33.zap
10980 [ZAP-DownloadInstaller] INFO  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Installing new addon ascanrulesBeta v33.0.0
11083 [ZAP-DownloadInstaller] INFO  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - Finished installing new addon ascanrulesBeta v33.0.0
11159 [ZAP-daemon] INFO  org.parosproxy.paros.CommandLine - Add-on downloaded to: /root/.ZAP/plugin/ascanrulesBeta-beta-33.zap
11160 [ZAP-daemon] INFO  org.zaproxy.zap.DaemonBootstrap - ZAP is now listening on 0.0.0.0:58331
11905 [ZAP-ProxyThread-4] ERROR org.zaproxy.zap.extension.api.ContextAPI - Error parsing file:/zap/wrk/project_login.zst
org.apache.commons.configuration.ConfigurationException: Error parsing file:/zap/wrk/project_login.zst
	at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:1014) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:972) ~[commons-configuration-1.10.jar:1.10]
	at org.zaproxy.zap.utils.ZapXmlConfiguration.load(ZapXmlConfiguration.java:181) ~[zap-2.10.0.jar:2.10.0]
	at org.apache.commons.configuration.XMLConfiguration$XMLFileConfigurationDelegate.load(XMLConfiguration.java:1647) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:324) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:261) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractFileConfiguration.load(AbstractFileConfiguration.java:238) ~[commons-configuration-1.10.jar:1.10]
	at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.load(AbstractHierarchicalFileConfiguration.java:184) ~[commons-configuration-1.10.jar:1.10]
	at org.zaproxy.zap.utils.ZapXmlConfiguration.<init>(ZapXmlConfiguration.java:96) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1532) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:279) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:507) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:497) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
	at org.apache.commons.configuration.XMLConfiguration.load(XMLConfiguration.java:1006) ~[commons-configuration-1.10.jar:1.10]
	... 14 more

**Comment by thc202** [comment]
`<name>project_login.zst</name>` → `<name>project_login</name>`

**Comment by AbhishekPuranam** [comment]
Thanks a lot, it worked :)
