### ISSUE TITLE
Unable to properly use HUD, tools don't activate

### ISSUE THREAD

**Issue by BeagelTheBurger** [zaproxy/zaproxy#6429]
**Describe the bug**
Hi folks
I have problems with using the HUD . The only tool that seems to work is the bulb. 
For example, if i click on the scope, it asks me if i want to add current domain to scope. I click add and nothing happens.The other buttons don't even seem to do anything. It doesn't matter if i use the browser inside zap or not.

There is also an error when i start the program:
"An error occurred while starting the proxy. Adress is already used."

 - ZAP: 2.10.0

 - OS: Parrot GNU/Linux 4.10
 - Java: openjdk version "14.0.2" 
 - Browser:Firefox 84.0.2

**Errors from the zap.log file**
From zap.log:
java.net.BindException: Die Adresse wird bereits verwendet
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:479) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:468) ~[?:?]
	at sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:396) ~[?:?]
	at java.net.ServerSocket.<init>(ServerSocket.java:282) ~[?:?]
	at org.parosproxy.paros.core.proxy.ProxyServer.createServerSocket(ProxyServer.java:345) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyServer.startServer(ProxyServer.java:167) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Proxy.startServer(Proxy.java:105) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.init(Control.java:160) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:832) [?:?]

Anyone any Ideas?
I think it has to do with java but i have no clue how to fix it
Thanks in advance!

**Comment by syisunny** [comment]
In my opinion, you could ask this question in the user group instead of adding a bug(it is not a bug):
https://groups.google.com/g/zaproxy-users
For the binding issue, I think you have already an app running with port 8080. During the starting process, ZAP would ask you to change the default port. for the HUD, I think you would go back to the ZAP GUI to check if there are some logs generating. if yes, it means ZAP is doing something.
btw, it is better to run ZAP with a LTE java version (8 or 11).

**Comment by psiinon** [comment]
As per what @syisunny said :)
