### ISSUE TITLE
Unable to set only breaks on message in scope

### ISSUE THREAD

**Issue by ballomatic** [zaproxy/zaproxy#6437]
Welcome. While "mark" set only breaks on message in scope  box click OK and back to settings, this is unmark again (while trying few others, looks like works fine). No error in zap, but in log file 

```
2021-02-03 14:17:00,393 [AWT-EventQueue-0] INFO  SSLConnector - ClientCert disabled
2021-02-03 14:17:00,709 [AWT-EventQueue-0] ERROR ExtensionQuickStartHud - object is not an instance of declaring class
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.zaproxy.zap.extension.quickstart.hud.ExtensionQuickStartHud.isInScopeOnly(ExtensionQuickStartHud.java:98) [quickstart-release-29.zap:?]
	at org.zaproxy.zap.extension.quickstart.launch.LaunchPanel.setHudIsInScopeOnlyText(LaunchPanel.java:228) [quickstart-release-29.zap:?]
	at org.zaproxy.zap.extension.quickstart.launch.LaunchPanel.optionsChanged(LaunchPanel.java:396) [quickstart-release-29.zap:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.optionsChanged(ExtensionQuickStartLaunch.java:158) [quickstart-release-29.zap:?]
	at org.parosproxy.paros.extension.ExtensionLoader.optionsChangedAllPlugin(ExtensionLoader.java:535) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:84) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:64) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.view.MainMenuBar$3.actionPerformed(MainMenuBar.java:240) [zap-2.10.0.jar:2.10.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:369) [?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020) [?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```
while run zap fron console i get `org.parosproxy.paros.network.SSLConnector - ClientCert disabled`
Im also trying to set it true in config file, but zap back it to false. Before in zap 2.9 it works correct, but that version don work for me anymore

Im using latest Linux mint and have java is:

```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode)
```

**Comment by ballomatic** [comment]
After few reinstall, version 2.9 back to work full correctly, so i stuck on them until problem is solved

**Comment by thc202** [comment]
As workaround you could add a custom breakpoint using the regular expression of the context.
