### ISSUE TITLE
Failed to start ZAP on Mac OS X

### ISSUE THREAD

**Issue by ssxcxS45XT** [zaproxy/zaproxy#6445]
**Describe the bug**

**To Reproduce**

I downloaded the MacOS Installer below.

https://www.zaproxy.org/download/

When I open it, I get the following error.

```
Failed to start ZAP
 

Message:
    java.lang.NoClassDefFoundError: org/apache/commons/jxpath/ri/model/NodePointerFactory
Level:
    SEVERE
Stack Trace:
org/apache/commons/jxpath/ri/model/NodePointerFactory
    org.zaproxy.zap.control.BaseZapAddOnXmlData.<init>(BaseZapAddOnXmlData.java:172)
    org.zaproxy.zap.control.ZapAddOnXmlFile.<init>(ZapAddOnXmlFile.java:58)
    org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:434)
    org.zaproxy.zap.control.AddOn.<init>(AddOn.java:550)
    org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:482)
    org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:194)
    org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:166)
    org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:147)
    org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:70)
    org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:108)
    org.parosproxy.paros.control.Control.addExtension(Control.java:185)
    org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:54)
    org.parosproxy.paros.control.Control.init(Control.java:141)
    org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361)
    org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221)
    org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64)
    org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175)
    java.lang.Thread.run(Thread.java:748)
org.apache.commons.jxpath.ri.model.NodePointerFactory
    java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    org.zaproxy.zap.control.BaseZapAddOnXmlData.<init>(BaseZapAddOnXmlData.java:172)
    org.zaproxy.zap.control.ZapAddOnXmlFile.<init>(ZapAddOnXmlFile.java:58)
    org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:434)
    org.zaproxy.zap.control.AddOn.<init>(AddOn.java:550)
    org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:482)
    org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:194)
    org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:166)
    org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:147)
    org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:70)
    org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:108)
    org.parosproxy.paros.control.Control.addExtension(Control.java:185)
    org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:54)
    org.parosproxy.paros.control.Control.init(Control.java:141)
    org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361)
    org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221)
    org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64)
    org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175)
    java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
It should start correctly.

**Screenshots**
NA

**Software versions**
 - ZAP: the latest version
 - OS: Catalina
 - Java:
```
$ java --version
openjdk 15 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
```
 - Browser: Not relevant 

**Errors from the zap.log file**

```
$ cat  ~/Library/Application\ Support/ZAP/zap.log
2021-02-09 23:41:02,904 [main ] INFO  Constant - Copying default configuration to /Users/myuser/Library/Application Support/ZAP/config.xml
2021-02-09 23:41:03,073 [main ] INFO  Constant - Creating directory /Users/myuser/Library/Application Support/ZAP/session
2021-02-09 23:41:03,074 [main ] INFO  Constant - Creating directory /Users/myuser/Library/Application Support/ZAP/dirbuster
2021-02-09 23:41:03,074 [main ] INFO  Constant - Creating directory /Users/myuser/Library/Application Support/ZAP/fuzzers
2021-02-09 23:41:03,074 [main ] INFO  Constant - Creating directory /Users/myuser/Library/Application Support/ZAP/plugin
2021-02-09 23:41:03,120 [main ] INFO  GuiBootstrap - OWASP ZAP 2.10.0 started 09/02/21 23:41:03 with home /Users/myuser/Library/Application Support/ZAP/
2021-02-09 23:41:03,362 [AWT-EventQueue-0] INFO  SSLConnector - Reading supported SSL/TLS protocols...
2021-02-09 23:41:03,362 [AWT-EventQueue-0] INFO  SSLConnector - Using a SSLEngine...
2021-02-09 23:41:03,409 [AWT-EventQueue-0] INFO  SSLConnector - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
2021-02-09 23:41:03,412 [AWT-EventQueue-0] INFO  OptionsParamCertificate - Unsafe SSL renegotiation disabled.
2021-02-09 23:41:03,762 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open start
2021-02-09 23:41:03,766 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2021-02-09 23:41:03,767 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2021-02-09 23:41:03,767 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open end
2021-02-09 23:41:03,811 [AWT-EventQueue-0] INFO  OsXGui - Initializing OS X specific settings, despite Apple's best efforts
2021-02-09 23:41:05,229 [AWT-EventQueue-0] INFO  View - Initialising View
2021-02-09 23:41:05,785 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Loading extensions
```

**Additional context**
NA

**Would you like to help fix this issue?**
No.

**Comment by ablewitt** [comment]
Hi @ssxcxS45XT. I have attempted to recreate the issue however I am not seeing the same results as you.  

Are you able to provide more information on your environment and how you are installing and executing the program?

**Comment by ssxcxS45XT** [comment]
My OS is macOS Catalina Version  10.15.6.

https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0.dmg

I downloade the above file. Then I open it and move "OWASP ZAP" in /Applications. Then, I click "OWASP ZAP" in the /Applications fold, then I see a windows pops up, saying "Failed to start ZAP. A fatal error occured that prevents ZAP from start. Consider reporting the error with the following details."

The details are

```

Failed to start ZAP
 

Message:
    java.lang.NoClassDefFoundError: org/apache/commons/jxpath/ri/model/NodePointerFactory
Level:
    SEVERE
Stack Trace:
org/apache/commons/jxpath/ri/model/NodePointerFactory
    org.zaproxy.zap.control.BaseZapAddOnXmlData.<init>(BaseZapAddOnXmlData.java:172)
    org.zaproxy.zap.control.ZapAddOnXmlFile.<init>(ZapAddOnXmlFile.java:58)
    org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:434)
    org.zaproxy.zap.control.AddOn.<init>(AddOn.java:550)
    org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:482)
    org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:194)
    org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:166)
    org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:147)
    org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:70)
    org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:108)
    org.parosproxy.paros.control.Control.addExtension(Control.java:185)
    org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:54)
    org.parosproxy.paros.control.Control.init(Control.java:141)
    org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361)
    org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221)
    org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64)
    org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175)
    java.lang.Thread.run(Thread.java:748)
org.apache.commons.jxpath.ri.model.NodePointerFactory
    java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    org.zaproxy.zap.control.BaseZapAddOnXmlData.<init>(BaseZapAddOnXmlData.java:172)
    org.zaproxy.zap.control.ZapAddOnXmlFile.<init>(ZapAddOnXmlFile.java:58)
    org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:434)
    org.zaproxy.zap.control.AddOn.<init>(AddOn.java:550)
    org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:482)
    org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:194)
    org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:166)
    org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:147)
    org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:70)
    org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:108)
    org.parosproxy.paros.control.Control.addExtension(Control.java:185)
    org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:54)
    org.parosproxy.paros.control.Control.init(Control.java:141)
    org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361)
    org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221)
    org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64)
    org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175)
    java.lang.Thread.run(Thread.java:748)
```

**Comment by ablewitt** [comment]
Thanks @ssxcxS45XT,

I would start with the following;

- Ensure the application isn't blocked by MacOS (System Preferences - > Security & Privacy -> General)
- Try uninstalling and downloading again
- Update to MacOS 11+

**Comment by ssxcxS45XT** [comment]
Upgrading MacOS is not an option to me. I don't think the app is blocked by my OS.

> Try uninstalling and downloading again

This is useless. I already tried several times.

**Comment by ablewitt** [comment]
Are you running Hackintosh setup?

**Comment by ssxcxS45XT** [comment]
No.

**Comment by psiinon** [comment]
It's worked fine on all of the MacOS boxes that the core team has access to.
I've tweeted this to see if anyone else has hit similar problems: https://twitter.com/psiinon/status/1364217614038351872

**Comment by ssxcxS45XT** [comment]
Did you use the exact same version of Mac OS X that I use?

**Comment by psiinon** [comment]
I'm using Cataline 10.15.7
The ZAP Mac installer includes jre-jdk8u275-b01-jre

**Comment by psiinon** [comment]
Do you have any add-ons in ~/Library/Application\ Support/ZAP/plugin/ ?
If so try deleting (or moving) them and trying to start ZAP again.

**Comment by psiinon** [comment]
Also, do you have a file called `/Applications/OWASP\ ZAP.app/Contents/Java/lib/commons-jxpath-1.3.jar` ?
If so, is it readable? What size is it?

**Comment by ssxcxS45XT** [comment]
```
$ ls -lgG /Applications/OWASP\ ZAP.app/Contents/Java/lib/commons-jxpath-1.3.jar 
-rw-r--r-- 1 299994 2020/12/17-04:08:00 '/Applications/OWASP ZAP.app/Contents/Java/lib/commons-jxpath-1.3.jar'
```

I have nothing in `~/Library/Application\ Support/ZAP/plugin/`.

Is there something I can run in the command line so I can have more control to see what is wrong?

**Comment by psiinon** [comment]
Yes, you can start ZAP from the command line on MacOS using: `/Applications/OWASP\ ZAP.app/Contents/Java/zap.sh`

**Comment by ssxcxS45XT** [comment]
Here is output. Is a simpler test case to tell what is wrong with my java?

```
$ /Applications/OWASP\ ZAP.app/Contents/Java/zap.sh
Found Java version 1.8.0_275
Available memory: 65536 MB
Using JVM args: -Xmx16384m
646 [main] INFO  org.zaproxy.zap.GuiBootstrap - OWASP ZAP 2.10.0 started 24/02/21 08:39:01 with home /Users/ssxcxS45XT/Library/Application Support/ZAP/
1005 [AWT-EventQueue-0] INFO  org.parosproxy.paros.network.SSLConnector - Reading supported SSL/TLS protocols...
1005 [AWT-EventQueue-0] INFO  org.parosproxy.paros.network.SSLConnector - Using a SSLEngine...
1044 [AWT-EventQueue-0] INFO  org.parosproxy.paros.network.SSLConnector - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
1048 [AWT-EventQueue-0] INFO  org.parosproxy.paros.extension.option.OptionsParamCertificate - Unsafe SSL renegotiation disabled.
1344 [AWT-EventQueue-0] INFO  hsqldb.db.HSQLDB379AF3DEBD.ENGINE - dataFileCache open start
1347 [AWT-EventQueue-0] INFO  hsqldb.db.HSQLDB379AF3DEBD.ENGINE - dataFileCache commit start
1348 [AWT-EventQueue-0] INFO  hsqldb.db.HSQLDB379AF3DEBD.ENGINE - dataFileCache commit end
1348 [AWT-EventQueue-0] INFO  hsqldb.db.HSQLDB379AF3DEBD.ENGINE - dataFileCache open end
1385 [AWT-EventQueue-0] INFO  org.zaproxy.zap.OsXGui - Initializing OS X specific settings, despite Apple's best efforts
4786 [AWT-EventQueue-0] INFO  org.parosproxy.paros.view.View - Initialising View
5376 [ZAP-BootstrapGUI] INFO  org.zaproxy.zap.control.ExtensionFactory - Loading extensions
7533 [ZAP-BootstrapGUI] FATAL org.zaproxy.zap.GuiBootstrap - Failed to initialise GUI: 
java.lang.NoClassDefFoundError: org/apache/commons/jxpath/ri/model/NodePointerFactory
	at org.zaproxy.zap.control.BaseZapAddOnXmlData.<init>(BaseZapAddOnXmlData.java:172) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.ZapAddOnXmlFile.<init>(ZapAddOnXmlFile.java:58) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.AddOn.isValidAddOn(AddOn.java:434) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:550) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.AddOn.createAddOn(AddOn.java:482) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.AddOnCollection.addDirectory(AddOnCollection.java:194) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:166) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.AddOnLoader.<init>(AddOnLoader.java:147) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.ExtensionFactory.getAddOnLoader(ExtensionFactory.java:70) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.control.ExtensionFactory.loadAllExtension(ExtensionFactory.java:108) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.addExtension(Control.java:185) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:54) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.init(Control.java:141) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.jxpath.ri.model.NodePointerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	... 18 more
```

**Comment by tsluyter** [comment]
Would it be possible for you to create a temporary, new user account on this Mac @ssxcxS45XT ? This new user account will have a perfectly new/clean home directory. If ZAP runs properly with that user account, that would be a clear indicator of some issues with files in your home dir.

**Comment by tsluyter** [comment]
@ssxcxS45XT if your problem no longer exists, please close this issue record.

**Comment by kingthorin** [comment]
No further input in months.
