### ISSUE TITLE
Export Report - Generating a PDF report via the command line produces an error and a 0 byte PDF file

### ISSUE THREAD

**Issue by adrianer** [zaproxy/zaproxy#6465]
**Describe the bug**
Generating a PDF report via the command line produces an error and a 0 byte PDF file. Generating an xhtml report with the same command works as expected. Generating the PDF report from the ZAP UI works too - so it only fails, when run trying to generate it on the command line.

**To Reproduce**

$ ./zap.sh -export_report "/home/dev/Desktop/report.pdf" -source_info "Vulnerability Report;Jenkins;For;Scan Date;Report Date;Scan Ver;Report Ver;Description" -alert_severity "t;t;t;t" -alert_details "t;t;t;t;t;t;f;f;f;f" -session "/home/dev/.ZAP/sessions/20210217-125853.session" -cmd
Found Java version 11.0.10
Available memory: 24335 MB
Using JVM args: -Xmx6083m
Ignoring legacy log4j.properties file, backup already exists.                                                                                 
[INFO] Path: Valid and Writable                                                                                                                                        
[INFO] Source Info Length: Valid                                                                                                                                       
[INFO] Source Info Content: Unchecked                                                                                                                                  
[INFO] Alert Severity Length: Valid                                                                                                                                    
[INFO] Alert Severity Content: Valid                                                                                                                                   
[INFO] Alert Details Length: Valid                                                                                                                                     
[INFO] Alert Details Content: Valid                                                                                                                                    
[INFO] All checks passed.. Generating Report..                                                                                                                         
[ERROR] null 

**Software versions**
 - ZAP: 2.10.0
 - Add-on: Export Report Alpha v7
 - OS: Ubuntu 18.04
 - Java: openjdk version "11.0.10"

**Errors from the zap.log file**
2021-02-24 11:01:50,604 [main ] ERROR CommandLine - [ERROR] null
java.lang.NullPointerException: null
	at org.zaproxy.zap.extension.exportreport.ExtensionExportReport.getIncludedAlertSeverity(ExtensionExportReport.java:300) ~[exportreport-alpha-7.zap:?]
	at org.zaproxy.zap.extension.exportreport.export.ReportExportPDF.filterAlertsByRiskLevel(ReportExportPDF.java:371) ~[exportreport-alpha-7.zap:?]
	at org.zaproxy.zap.extension.exportreport.export.ExportReport.generateReport(ExportReport.java:331) ~[exportreport-alpha-7.zap:?]
	at org.zaproxy.zap.extension.exportreport.ExtensionExportReport.generateReport(ExtensionExportReport.java:344) ~[exportreport-alpha-7.zap:?]
	at org.zaproxy.zap.extension.exportreport.ExtensionExportReport.execute(ExtensionExportReport.java:563) [exportreport-alpha-7.zap:?]
	at org.parosproxy.paros.extension.ExtensionLoader.runCommandLine(ExtensionLoader.java:551) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.runCommandLine(Control.java:399) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.CommandLineBootstrap.start(CommandLineBootstrap.java:85) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) [zap-2.10.0.jar:2.10.0]

**Would you like to help fix this issue?**
Yes

**Comment by adrianer** [comment]
g4z: you are using Export Report Alpha v6 - you must Upgrade to v7

**Comment by psiinon** [comment]
FYI we are working on a new reporting add-on which will replace all of the other reporting add-ons on the marketplace. No eta yet :)

**Comment by thc202** [comment]
Closing, the Export Report add-on is being superseded by the Report Generation add-on:
https://www.zaproxy.org/docs/desktop/addons/report-generation/
