### ISSUE TITLE
Extension ImportWDSL still has a dependancy on Nashorn which is deprecated

### ISSUE THREAD

**Issue by globeone** [zaproxy/zaproxy#6500]
**Describe the bug**
When starting ZAP java throws an exception that the ImportWDSL extension is still dependent on the now deprecated and removed Oracle Nashorn.

**To Reproduce**
1. Go to 'zap.bat'
2. DoubleClick on 'zap.bat'
3. Scroll back in the CMD terminal to ' Failed to initialise extension org.zaproxy.zap.extension.soap.ExtensionImportWSDL'

**Expected behavior**
ImportWDSL should load without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/10052587/112825847-8c623680-908c-11eb-84e2-91fb1b661f88.png)

**Software versions**
 - ZAP: Weekly D-2021-03-22
 - Add-on: ImportWDSL (from add-on [id=soap, version=6.0.0])
 - OS: Windows 10
 - Java:  openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36)
OpenJDK 64-Bit Server VM (build 15+36, mixed mode, sharing)

 - Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Errors from the zap.log file**
```
15857 [ZAP-BootstrapGUI] ERROR org.parosproxy.paros.extension.ExtensionLoader - Failed to initialise extension org.zaproxy.zap.extension.soap.ExtensionImportWSDL (from add-on [id=soap, version=6.0.0]), cause: InvalidParameterException: No such engine: Oracle Nashorn
java.security.InvalidParameterException: No such engine: Oracle Nashorn
        at org.zaproxy.zap.extension.script.ExtensionScript.getEngineWrapper(ExtensionScript.java:472) ~[zap-D-2021-03-22.jar:D-2021-03-22]
        at org.zaproxy.zap.extension.soap.ExtensionImportWSDL.addScript(ExtensionImportWSDL.java:194) ~[?:?]
        at org.zaproxy.zap.extension.soap.ExtensionImportWSDL.postInit(ExtensionImportWSDL.java:95) ~[?:?]
        at org.parosproxy.paros.extension.ExtensionLoader.hookAllExtension(ExtensionLoader.java:934) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:798) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:58) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.parosproxy.paros.control.Control.init(Control.java:141) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:361) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:221) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.zaproxy.zap.GuiBootstrap.access$100(GuiBootstrap.java:64) [zap-D-2021-03-22.jar:D-2021-03-22]
        at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:175) [zap-D-2021-03-22.jar:D-2021-03-22]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Additional context**
none at the moment it's a pretty straightforward library deprecation and change to new library bug.

**Would you like to help fix this issue?**
Unfortunately, still beyond my programming skills am happy to test though.

**Comment by thc202** [comment]
The latest version available in the marketplace no longer fails at the start.

The add-on still needs to be changed to use other script engine going forward.
