### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by beatquantum** [zaproxy/zaproxy#6551]
Chrome is able to visit the website https://45.153.185.227/ however Zaproxy says "Failed to attack the URL: Received fatal alert: handshake_failure". This is not a duplication of #3362 and #5357. I suspect the handshake failure happens because it is not replicating the Chrome handshake properly when a server is using stronger cryptography.

**To Reproduce**
1. Install nginx server and issue a self-signed certificate (--rsa-key-size 4096) for the default server.
2. Use the following settings for stronger cryptography.

        listen 443 ssl http2 default_server;
        listen [::443] ssl http2 default_server;

        ssl_session_cache shared:le_nginx_SSL:10m;
        ssl_session_timeout 10m;
        ssl_session_tickets off;

        ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
        ssl_dhparam /etc/nginx/dsa4096.pem;
        ssl_protocols TLSv1.3 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ecdh_curve secp384r1;
        ssl_ciphers "TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305";

3. Run zaproxy and attack the server using https://<ip address>.  If you wish, you can attack my experimental server (https://45.153.185.227).

**Expected behavior**
Zaproxy should reproduce the secure connection that Chrome does.

**Software versions**
 - ZAP: 2.10.0 (Run on Windows 10 latest update)
 - Nginx: 1.19.0
 - Server: Debian Testing
 
**Errors from the zap.log file**
```
2021-04-19 06:12:03,382 [ZAP-QuickStart-AttackThread] ERROR AttackThread - Received fatal alert: handshake_failure
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLSocketImpl.ensureNegotiated(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLSocketImpl.access$200(Unknown Source) ~[?:1.8.0_281]
	at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source) ~[?:1.8.0_281]
	at java.io.BufferedOutputStream.flush(Unknown Source) ~[?:1.8.0_281]
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:860) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2248) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1154) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:470) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:?]
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:429) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:671) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:626) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:601) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:584) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:489) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.quickstart.AttackThread.accessNode(AttackThread.java:234) [quickstart-release-29.zap:?]
	at org.zaproxy.zap.extension.quickstart.AttackThread.run(AttackThread.java:86) [quickstart-release-29.zap:?]
```

**Would you like to help fix this issue?**
Yes, sure. I can change some of the ciphers on the experimental server if you wish to investigate.

**Extra info**
ZAP works very well on basic / default nginx installation without the above cryptography strengthening.

**Comment by thc202** [comment]
What Java version are you using? ZAP relies on the JRE to handle SSL/TLS connections.

**Comment by beatquantum** [comment]
About Java:
Version 8 Update 281 (build 1.8.0_281-b09)

**Comment by thc202** [comment]
I'd suggest trying with latest Java 11.

**Comment by beatquantum** [comment]
I think I found the reason without changing to Java 11.

OWASP ZAP needs some ciphers. I expanded the above list with the following.

ssl_ciphers "TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384";

It works now.

**Comment by thc202** [comment]
It's the JRE that has the ciphers not ZAP, that's why the suggestion to try with Java 11 (which has newer ciphers, e.g. ChaCha-Poly).
