### ISSUE TITLE
Wappalyzer should handle new DOM patterns

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#6607]
The wappalyzer add-on logs a load of errors like:
```
Scanner Wappalyzer Scanner (Tech Detection) failed on record 1 from History table: GET https://firefox.settings.services.mozilla.com/v1/buckets/monitor/collections/changes/changeset?collection=message-groups&bucket=main&_expected=0
org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'src*='
	at org.jsoup.select.QueryParser.parse(QueryParser.java:47) ~[?:?]
	at org.jsoup.select.Selector.select(Selector.java:92) ~[?:?]
	at org.jsoup.nodes.Element.select(Element.java:396) ~[?:?]
	at org.zaproxy.zap.extension.wappalyzer.WappalyzerPassiveScanner.checkDomElementMatches(WappalyzerPassiveScanner.java:175) ~[?:?]
	at org.zaproxy.zap.extension.wappalyzer.WappalyzerPassiveScanner.checkAppMatches(WappalyzerPassiveScanner.java:123) ~[?:?]
	at org.zaproxy.zap.extension.wappalyzer.WappalyzerPassiveScanner.scanHttpResponseReceive(WappalyzerPassiveScanner.java:73) ~[?:?]
	at org.zaproxy.zap.extension.pscan.PassiveScanThread.run(PassiveScanThread.java:227) [main/:?]
```

These can be reproduced by just launching Firefox from ZAP, waiting until it "calls home" then waiting for the passive scanning to complete.
If it is a real problem then it should be fixed.
If its not something that needs fixing then we should log an error for it :)

**Comment by kingthorin** [comment]
I wasn't able to recreate, however I do see in the code that at `org.zaproxy.zap.extension.wappalyzer.WappalyzerPassiveScanner.checkDomElementMatches` should ensure it's analyzing html trying to parse other content is just a waste.

**Comment by kingthorin** [comment]
@psiinon could you try to capture the response that caused the issue? (Add it here so that I have something to test/fix against.)

**Comment by psiinon** [comment]
@kingthorin have you turned the Global Excludes on? If so turn them off ;)

I get loads just by launching Firefox and not going to any sites.

Request Header 
```
GET https://firefox.settings.services.mozilla.com/v1/buckets/monitor/collections/changes/changeset?collection=message-groups&bucket=main&_expected=0 HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Connection: keep-alive
Host: firefox.settings.services.mozilla.com
```

Response Header
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 222
Connection: keep-alive
Access-Control-Expose-Headers: Content-Type, Content-Length, Retry-After, Backoff, Alert
Cache-Control: max-age=3600
Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; base-uri 'none';
Date: Tue, 18 May 2021 11:38:19 GMT
Expires: Tue, 18 May 2021 12:08:34 GMT
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Cache: Hit from cloudfront
Via: 1.1 8371fbc9826c0484f800a3b97c726733.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: MAN50-C1
X-Amz-Cf-Id: 0jiuxnIvARVItxl-TRxyUD7tjlihStXWZDrJesO-drqvFSTUOTLM7Q==
Age: 2544
```

Response Body
```
{"metadata":{},"timestamp":1621324679453,"changes":[{"id":"8e0dffc7-d526-aa8d-759c-0882dfda733c","last_modified":1595616291726,"bucket":"main","collection":"message-groups","host":"firefox.settings.services.mozilla.com"}]}
```

**Comment by kingthorin** [comment]
Thanks

**Comment by thc202** [comment]
This is already fixed upstream, but the format changed.

**Comment by kingthorin** [comment]
Per: https://github.com/AliasIO/wappalyzer/blob/master/schema.json the dom patterns can now be a string, an array of strings, or an object.

**Comment by kingthorin** [comment]
For the record, the unbalanced item was in the pattern not the content being analyzed.

**Comment by blshkv** [comment]
Hi guys, I'm not sure  if this bug is fixed, but I'm seeing more errors with the current version 21.2.0:
```
4695 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.33across.com'], link[href*='.33across.com'] : java.lang.String
4702 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='.a8.net'] : java.lang.String
4727 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='cdn.atshop.io'] : java.lang.String
4736 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='.accesstrade.net'],img[data-src*='.accesstrade.net'] : java.lang.String
4752 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [data-ackee-domain-id], [data-ackee-server] : java.lang.String
4760 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='app.acuityscheduling.com'] : java.lang.String
4816 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [object[type='application/x-shockwave-flash'], param[value*='.swf']] : net.sf.json.JSONArray
4837 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='www.afi-b.com'] : java.lang.String
4841 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='banners.affiliatefuture.com'] : java.lang.String
4888 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='amazonpay'] : java.lang.String
4926 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='.anyclip.com'], video[poster*='.anyclip.com'] : java.lang.String
4981 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.adnxs.com'], img[src*='.adnxs.com'] : java.lang.String
4993 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #arc-widget : java.lang.String
4999 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.iperceptions.com'], link[href*='.iperceptions.com'] : java.lang.String
5002 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='athena/autocomplete/css/autocomplete.css'] : java.lang.String
5012 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #jira : java.lang.String
5031 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for form[action*='aweber.com'] : java.lang.String
5056 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[data-src*='.bigcommerce.com'], img[src*='.bigcommerce.com'], link[href*='.bigcommerce.com'] : java.lang.String
5068 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.getblue.io'] : java.lang.String
5076 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for bolt-checkout-button : java.lang.String
5257 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #BorlabsCookieBox : java.lang.String
5269 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #bread-mini-cart-btn : java.lang.String
5276 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='browniesuite.com'][target='_blank'] img[src*='brownie'] : java.lang.String
5284 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [data-builder-content-id], img[src*='cdn.builder.io'] : java.lang.String
5287 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='buildertrend.net'], script[src*='buildertrend.net'] : java.lang.String
5321 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='/cart'], a[href*='/basket'], a[href*='/trolley'], a[href*='/bag'], a[href*='/shoppingbag'], a[href*='/checkout'], [aria-controls='cart'] : java.lang.String
5343 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='st.chatango.com'] : java.lang.String
5364 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='pay.clickbank.net?cbfid'], img[width='1'][src*='hop.clickbank.net?affiliate'] : java.lang.String
5376 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='clustrmaps.com'] : java.lang.String
5377 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='co-construct.com/skins'], iframe[src*='co-construct.com'] : java.lang.String
5380 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [meta[property='og:image'][content*='static.cococart.co'], div[style*='static.cococart.co']] : net.sf.json.JSONArray
5388 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href^='https://commerce.coinbase.com/checkout/'] : java.lang.String
5403 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for form[action*='.convertkit.com'], link[href*='.convertkit.com'] : java.lang.String
5407 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #cookie-law-info-bar : java.lang.String
5444 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for meta[name='author'][content*='Dealer Spike'] : java.lang.String
5461 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.districtm.io'] : java.lang.String
5491 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for aside#cart-offcanvas, form.commerce-order-item-add-to-cart-form,form.commerce-add-to-cart : java.lang.String
5540 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for style[data-emotion], style[data-emotion-css] : java.lang.String
5563 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='facebook.com/tr'] : java.lang.String
5577 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='js.financeads.net'], link[href*='js.financeads.com'], a[href*='www.financeads.net/tc.php'] : java.lang.String
5582 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='cdn.firepush.net'] : java.lang.String
5658 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [aria-labelledby='pi-google_pay'], ul[data-shopify-buttoncontainer] li : java.lang.String
5687 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='ib.guestonline.'] : java.lang.String
5691 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='gumgum.com'], img[src*='gumgum.com'] : java.lang.String
5703 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for header#sp-header, body.helix-ultimate : java.lang.String
5753 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='.j-a-net.jp'],img[data-src*='.j-a-net.jp'] : java.lang.String
5761 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for div[data-video-provider*=jwplayer] : java.lang.String
5778 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [a[href*='kqsdesign.pl'][target='_blank'], a[href*='kqs.pl'][target='_blank'], #kqs-box,kqs-cookie] : net.sf.json.JSONArray
5783 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='.kameleoon.eu/kameleoon.js'] : java.lang.String
5796 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for form[action*='property.infusionsoft.com'] : java.lang.String
5810 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='.konduto.com'] : java.lang.String
5816 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='.kooomo-cloud.com'] : java.lang.String
5822 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.lkqd.net'] : java.lang.String
5840 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for noscript > img[src*='dc.ads.linkedin.com'] : java.lang.String
5853 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='gdpr-consent-tool\.privacymanager\.io'] : java.lang.String
5855 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #lz_overlay_chat : java.lang.String
5891 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='mapbox-gl.css'] : java.lang.String
5912 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='bookmenow.info/book'] : java.lang.String
5987 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for #svr[value^="NEOWEBV"] : java.lang.String
5988 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for .nsw-container, .nsw-header, .nsw-icon, link[href*='nsw-design-system'] : java.lang.String
5998 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='.newrelic.com'] : java.lang.String
6021 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [iframe[src*='app.getoccasion.com'], a[href*='app.getoccasion.com']] : net.sf.json.JSONArray
6030 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for form[action*='api.ometria.com'] : java.lang.String
6036 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='app.omniconvert.com'] : java.lang.String
6062 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='openstreetmap.org'],iframe[data-lazy-src*='openstreetmap.org'] : java.lang.String
6077 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='.openx.net'], img[src*='.openx.net'] : java.lang.String
6095 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='app.paybright.com'] : java.lang.String
6123 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for iframe[src*='app.picreel.com'] : java.lang.String
6125 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for .pimcore_area_content : java.lang.String
6130 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='ct.pinterest.com/v3/?tid'] : java.lang.String
6200 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for [.reservio-booking-button, a[href*='.reservio.com'][target='_blank'], a[href*='bookings.reservio.com']] : net.sf.json.JSONArray
6235 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for .StudioCanvas, .publish-studio-style : java.lang.String
6318 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for .skyshop-container : java.lang.String
6443 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for img[src*='main.takedropstorage.com'] : java.lang.String
6622 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for link[href*='res2.weblium.site'] : java.lang.String
6698 [ZAP-BootstrapGUI] ERROR org.zaproxy.zap.extension.wappalyzer.WappalyzerJsonParser - Unexpected header type for a[href*='www.zocdoc.com'][target='_blank'] : java.lang.String

```

**Comment by kingthorin** [comment]
I believe that’s a different issue I’m still working on. Thanks for following up.

**Comment by kingthorin** [comment]
I'm un-assigning myself. I can't quite figure out the bit for the handling for newer DOM patterns that use an array or string (instead of the earlier object based set).

It seems that in WappalyzerJsonParser.jsonToAppPatternNestedMapList(String, Object), there's already an if checking for JSONObject, it could also check for JSONArray, and String then somehow convert those into simpler nested maps. (Or at least that was my thoughts on it....).

**Comment by thc202** [comment]
Update the issue to match the other problem.

**Comment by kingthorin** [comment]
I have further handling for this ready once https://github.com/zaproxy/zap-extensions/pull/3505 is merged.
