### ISSUE TITLE
[CodeInjectionScanRule] isStop() not checked on IOException leads to max rule duration not enforced

### ISSUE THREAD

**Issue by FiveOFive** [zaproxy/zaproxy#6647]
**Describe the bug**
If the CodeInjectionScanRule is consistently getting an IOException, then the isStop() check never happens and the MaxRuleDuration setting is not enforced.

**To Reproduce**
1. Set optionMaxScanRuleDurationInMins - https://www.zaproxy.org/docs/api/#ascanactionsetoptionmaxruledurationinmins
2. Start an active scan
3. Let the scan start
4. Create a network rule to block ZAP's requests to the web app
5. Check that logs show a steady stream of SocketTimeoutExceptions for CodeInjectionScanRule tests. 
5. Wait for longer than the MaxScanRuleDurationInMins and observe that the CodeInjectionScanRule is running much longer than the set duration. Because timing out requests are inherently slower than successful requests, I've seen it stuck running for days if the scan is not manually stopped.

**Expected behavior**
All scan rules should stop after MaxScanRuleDurationInMins.

**Screenshots**

**Software versions**
 - ZAP: Latest zap2sdocker-stable (owasp/zap2docker-stable:2.10.0) There have been a few changes to the extensions since this release, but looks like the issue still exists.
 - Add-on: Name and version [CodeInjectionScanRule and other active scan rules]
 - OS: [e.g. Windows 10]
 - Java: [e.g. openjdk version "1.8.0_171"]
 - Browser: [e.g. chrome 66, firefox 59, safari 11.1]

**Errors from the zap.log file**
See https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/ for the location of the zap.log file for your OS.

This bug occurs when the tests for a rule are consistently throwing an IOException, such as a SocketTimeoutException.

```
160200672 [ZAP-ActiveScanner-0] WARN  org.zaproxy.zap.extension.ascanrules.CodeInjectionScanRule - PHP Code Injection vulnerability check failed for parameter [ajax] and payload [${@print(chr(122).chr(97).chr(112).chr(95).chr(116).chr(111).chr(107).chr(101).chr(110))}\] due to an I/O error
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) ~[?:?]
	at org.parosproxy.paros.network.SSLConnector.createSocket(SSLConnector.java:460) ~[zap-2.10.0.jar:2.10.0]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:457) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:?]
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:429) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:671) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:626) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:601) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:584) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:489) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:314) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.scanner.AbstractPlugin.sendAndReceive(AbstractPlugin.java:244) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.ascanrules.CodeInjectionScanRule.testPhpInjection(CodeInjectionScanRule.java:193) [ascanrules-release-38.zap:?]
	at org.zaproxy.zap.extension.ascanrules.CodeInjectionScanRule.scan(CodeInjectionScanRule.java:158) [ascanrules-release-38.zap:?]
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:189) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scanVariant(AbstractAppParamPlugin.java:113) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.scanner.AbstractAppParamPlugin.scan(AbstractAppParamPlugin.java:84) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.scanner.AbstractPlugin.run(AbstractPlugin.java:332) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Additional context**

Here is where the isStop() check is done - https://github.com/zaproxy/zap-extensions/blob/5f3f86cb6f649b233fe7f736afced0244cd88ff6/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java#L213

And here is where earlier in the code the IOException is caught and the loop continues to the next iteration, skipping the isStop() check - https://github.com/zaproxy/zap-extensions/blob/5f3f86cb6f649b233fe7f736afced0244cd88ff6/addOns/ascanrules/src/main/java/org/zaproxy/zap/extension/ascanrules/CodeInjectionScanRule.java#L180-L187

Proposed fix is to move the isStop() check to the beginning of the code so that it is never skipped.

**Would you like to help fix this issue?**
Yes!

**Comment by kingthorin** [comment]
@FiveOFive good catch. There's info over here: https://www.zaproxy.org/docs/developer/ on setting up your development environment.
