### ISSUE TITLE
Launched Chromium browser crashes after about 1 minute

### ISSUE THREAD

**Issue by DavidFarago** [zaproxy/zaproxy#6709]
**Describe the bug**
My launched chromium browser crashes after about 1 minute. This is independent of how I am using it and whether HUD is enabled. (The address bar in chromium contains "data:,", which is not a problem because I can simply fill in another address, but maybe it is related to the crash).

**To Reproduce**
1. Go to Manual Explore in ZAP
2. Click on "Launch Browser" with "Chrome" selected
3. wait a minute

**Expected behavior**
Chromium keeps running (and starts by automatically opening the "URL to explore"). 

**Software versions**
 - ZAP: 2.10.0
 - Add-on: Linux WebDrivers 29.0.0, Selenium 15.3.0
 - OS: `5.4.0-77-generic #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Java:  openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~18.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
 - Browser: Chromium Version 92.0.4515.107 (Official Build) snap (64-bit)

**Errors from standard out and the zap.log file**
```
107904 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch - unknown error: DevToolsActivePort file doesn't exist
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'davef-ThinkPad-T480', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '1.8.0_292'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x55e99a31f6a9 <unknown>

org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'davef-ThinkPad-T480', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-77-generic', java.version: '1.8.0_292'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x55e99a31f6a9 <unknown>

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_292]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_292]
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126) ~[selenium-release-15.3.0.zap:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_292]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_292]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_292]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_292]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_292]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168) ~[selenium-release-15.3.0.zap:?]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:813) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:785) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:62) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:680) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:548) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:641) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:605) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:591) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:581) ~[selenium-release-15.3.0.zap:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch$2.run(ExtensionQuickStartLaunch.java:224) [quickstart-release-29.zap:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Would you like to help fix this issue?**
I am happy to help, but have next to no experience with ZAP and would love to continue experimenting with ZAP HUD on Chromium (i.e. with a fixed version) this weekend.

**Comment by psiinon** [comment]
How are you running ZAP?
This is not a ZAP error but I found this issue which may be related: https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t
That appears to happen when running chromium as root.

**Comment by thc202** [comment]
It might also have to do with "permissions" (being a snap).

**Comment by njmulsqb** [comment]
This issue still exists in 2.11.1 The chromium browser crashes itself and yes chromium is installed via Snap

**Comment by thc202** [comment]
If the issues are still open it means the issues were not addressed.

**Comment by thc202** [comment]
Merging into #7095.
