### ISSUE TITLE
zaproxy need root privilges for updates on kali 

### ISSUE THREAD

**Issue by TNTBOMBOM** [zaproxy/zaproxy#6714]
**Is your feature request related to a problem? Please describe.**
Kali switched from root access by default to user access by default (like normal distro), So the behavior of the apps should be changed as well to fit this change. Zaproxy need root access to make an upgrade to the plugins.

**Describe the solution you'd like**
Make zaproxy work within user privileges or make it request root rights access similar to gparted (from the gui) 

Note: Running GUI applications using sudo can lead to security disaster, Best to be used with lxsudo then the application name e.g lxsudo zaproxy (sudo apt install [lxqt-sudo](https://packages.debian.org/bullseye/lxqt-sudo) need to be preinstalled)  <- This is just a workaround to the issue but not the solution.

More about it: 

https://askubuntu.com/questions/270006/why-should-users-never-use-normal-sudo-to-start-graphical-applications

https://help.ubuntu.com/community/RootSudo#Graphical_sudo

https://www.psychocats.net/ubuntu/graphicalsudo

https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/

**Zaproxy logs for the issue**

```
2021-07-29 07:01:48,680 [main ] INFO  GuiBootstrap - OWASP ZAP 2.10.0 started 29/07/2021, 07:01:48 with home /home/user/.ZAP/
2021-07-29 07:01:48,858 [AWT-EventQueue-0] INFO  SSLConnector - Reading supported SSL/TLS protocols...
2021-07-29 07:01:48,859 [AWT-EventQueue-0] INFO  SSLConnector - Using a SSLEngine...
2021-07-29 07:01:48,970 [AWT-EventQueue-0] INFO  SSLConnector - Done reading supported SSL/TLS protocols: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
2021-07-29 07:01:48,974 [AWT-EventQueue-0] INFO  OptionsParamCertificate - Unsafe SSL renegotiation enabled.
2021-07-29 07:01:49,463 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open start
2021-07-29 07:01:49,484 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2021-07-29 07:01:49,496 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2021-07-29 07:01:49,499 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open end
2021-07-29 07:01:49,985 [AWT-EventQueue-0] INFO  View - Initialising View
2021-07-29 07:01:50,831 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Loading extensions
2021-07-29 07:01:52,034 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Installed add-ons: [[id=alertFilters, version=10.0.0], [id=ascanrules, version=40.0.0], [id=bruteforce, version=10.0.0], [id=commonlib, version=1.4.0], [id=custompayloads, version=0.10.0], [id=diff, version=10.0.0], [id=directorylistv1, version=4.0.0], [id=domxss, version=10.0.0], [id=encoder, version=0.5.0], [id=formhandler, version=3.0.0], [id=fuzz, version=13.2.0], [id=gettingStarted, version=12.0.0], [id=graaljs, version=0.1.0], [id=graphql, version=0.3.0], [id=help, version=11.0.0], [id=hud, version=0.12.0], [id=importurls, version=7.0.0], [id=invoke, version=10.0.0], [id=onlineMenu, version=8.0.0], [id=openapi, version=19.0.0], [id=pscanrules, version=35.0.0], [id=quickstart, version=29.0.0], [id=replacer, version=8.0.0], [id=retire, version=0.7.0], [id=reveal, version=3.0.0], [id=saverawmessage, version=5.0.0], [id=savexmlmessage, version=0.1.0], [id=scripts, version=28.0.0], [id=selenium, version=15.3.0], [id=soap, version=7.0.0], [id=spiderAjax, version=23.3.0], [id=tips, version=8.0.0], [id=webdriverlinux, version=29.0.0], [id=websocket, version=23.0.0], [id=zest, version=34.0.0]]
2021-07-29 07:01:52,244 [ZAP-BootstrapGUI] INFO  ExtensionFactory - Extensions loaded
2021-07-29 07:01:52,705 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows ZAP to check for updates
2021-07-29 07:01:52,788 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Options Extension
2021-07-29 07:01:53,237 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Edit Menu Extension
2021-07-29 07:01:53,244 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides a rest based API for controlling and accessing ZAP
2021-07-29 07:01:53,273 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Session State Extension
2021-07-29 07:01:53,277 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Report Extension
2021-07-29 07:01:53,283 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing History Extension
2021-07-29 07:01:53,460 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Show hidden fields and enable disabled fields
2021-07-29 07:01:53,470 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Search messages for strings and regular expressions
2021-07-29 07:01:53,542 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to intercept and modify requests and responses
2021-07-29 07:01:53,614 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Passive scanner
2021-07-29 07:01:53,665 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Script Passive Scan Rules
2021-07-29 07:01:53,669 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Stats Passive Scan Rule
2021-07-29 07:01:53,673 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Application Error Disclosure
2021-07-29 07:01:53,676 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Incomplete or No Cache-control Header Set
2021-07-29 07:01:53,679 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Charset Mismatch
2021-07-29 07:01:53,683 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: CSP
2021-07-29 07:01:53,686 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Content-Type Header Missing
2021-07-29 07:01:53,690 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cookie No HttpOnly Flag
2021-07-29 07:01:53,694 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Loosely Scoped Cookie
2021-07-29 07:01:53,697 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cookie without SameSite Attribute
2021-07-29 07:01:53,701 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cookie Without Secure Flag
2021-07-29 07:01:53,705 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cross-Domain Misconfiguration
2021-07-29 07:01:53,709 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Cross-Domain JavaScript Source File Inclusion
2021-07-29 07:01:53,713 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Absence of Anti-CSRF Tokens
2021-07-29 07:01:53,717 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Private IP Disclosure
2021-07-29 07:01:53,721 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Session ID in URL Rewrite
2021-07-29 07:01:53,725 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Information Disclosure - Debug Error Messages
2021-07-29 07:01:53,728 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Information Disclosure - Sensitive Information in URL
2021-07-29 07:01:53,731 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Information Disclosure - Sensitive Information in HTTP Referrer Header
2021-07-29 07:01:53,735 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Information Disclosure - Suspicious Comments
2021-07-29 07:01:53,739 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Weak Authentication Method
2021-07-29 07:01:53,743 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Insecure JSF ViewState
2021-07-29 07:01:53,746 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Secure Pages Include Mixed Content
2021-07-29 07:01:53,750 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Timestamp Disclosure
2021-07-29 07:01:53,753 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Username Hash Found
2021-07-29 07:01:53,757 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Viewstate
2021-07-29 07:01:53,760 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: X-AspNet-Version Response Header
2021-07-29 07:01:53,764 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: X-Content-Type-Options Header Missing
2021-07-29 07:01:53,767 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: X-Debug-Token Information Leak
2021-07-29 07:01:53,771 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: X-Frame-Options Header
2021-07-29 07:01:53,774 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s)
2021-07-29 07:01:53,778 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: Vulnerable JS Library
2021-07-29 07:01:53,781 [ZAP-BootstrapGUI] INFO  ExtensionPassiveScan - loaded passive scan rule: WSDL File Detection
2021-07-29 07:01:53,824 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to view and manage alerts
2021-07-29 07:01:53,993 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Active scanner, heavily based on the original Paros active scanner, but with additional tests added
2021-07-29 07:01:54,083 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Spider used for automatically finding URIs on a site
2021-07-29 07:01:54,165 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing A set of common popup menus for miscellaneous tasks
2021-07-29 07:01:54,176 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Forced browsing of files and directories using code from the OWASP DirBuster tool
2021-07-29 07:01:54,243 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Manual Request Editor Extension
2021-07-29 07:01:54,246 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Compares 2 sessions and generates an HTML file showing the differences
2021-07-29 07:01:54,251 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Invoke external applications passing context related information such as URLs and parameters
2021-07-29 07:01:54,276 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Handles anti cross site request forgery (CSRF) tokens
2021-07-29 07:01:54,297 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Authentication Extension
2021-07-29 07:01:54,318 [ZAP-BootstrapGUI] INFO  ExtensionAuthentication - Loaded authentication method types: [Form-based Authentication, HTTP/NTLM Authentication, Manual Authentication, Script-based Authentication, JSON-based Authentication]
2021-07-29 07:01:54,339 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Creates a dynamic SSL certificate to allow SSL communications to be intercepted without warnings being generated by the browser
2021-07-29 07:01:54,593 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Logs errors to the Output tab in development mode only
2021-07-29 07:01:54,597 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Users Extension
2021-07-29 07:01:54,602 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Summarise and analyse FORM and URL parameters as well as cookies
2021-07-29 07:01:54,617 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Script integration
2021-07-29 07:01:54,636 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Scripting console, supports all JSR 223 scripting languages
2021-07-29 07:01:54,941 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Forced User Extension
2021-07-29 07:01:54,949 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Extension handling HTTP sessions
2021-07-29 07:01:54,994 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Zest is a specialized scripting language, originally, from Mozilla specifically designed to be used in security tools
2021-07-29 07:01:55,360 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionDiff
2021-07-29 07:01:55,362 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Post Table View Extension
2021-07-29 07:01:55,380 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds support for scriptable encoders to ZAP.
2021-07-29 07:01:55,456 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Session Management Extension
2021-07-29 07:01:55,463 [ZAP-BootstrapGUI] INFO  ExtensionSessionManagement - Loaded session management method types: [Cookie-based Session Management, HTTP Authentication Session Management, Script-based Session Management]
2021-07-29 07:01:55,476 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Form Table View Extension
2021-07-29 07:01:55,494 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Capture messages from WebSockets with the ability to set breakpoints.
2021-07-29 07:01:55,683 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to import a file containing URLs which ZAP will access, adding them to the Sites tree
2021-07-29 07:01:55,687 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to import a WSDL file containing operations which ZAP will access, adding them to the Sites tree.
2021-07-29 07:01:55,690 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Core UI related functionality.
2021-07-29 07:01:55,693 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Authorization Extension
2021-07-29 07:01:55,696 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing AJAX Spider, uses Crawljax
2021-07-29 07:01:55,809 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides WebDrivers to control several browsers using Selenium and includes HtmlUnit browser.
2021-07-29 07:01:55,828 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Manages the local proxy configurations
2021-07-29 07:01:55,859 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Handles adding Global Excluded URLs
2021-07-29 07:01:55,882 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds menu item to refresh the Sites tree
2021-07-29 07:01:55,886 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing OWASP ZAP User Guide
2021-07-29 07:01:56,018 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides a URL suitable for calling from target sites
2021-07-29 07:01:56,066 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to configure which extensions are loaded when ZAP starts
2021-07-29 07:01:56,148 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Combined HTTP Panels Extension
2021-07-29 07:01:56,191 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Hex View Extension
2021-07-29 07:01:56,231 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Image View Extension
2021-07-29 07:01:56,240 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Large Request View Extension
2021-07-29 07:01:56,256 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Large Response View Extension
2021-07-29 07:01:56,272 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Query Table View Extension
2021-07-29 07:01:56,308 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing HTTP Panel Syntax Highlighter View Extension
2021-07-29 07:01:56,445 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds support for configurable keyboard shortcuts for all of the ZAP menus.
2021-07-29 07:01:56,466 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Active and passive rule configuration
2021-07-29 07:01:56,479 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Statistics
2021-07-29 07:01:56,492 [ZAP-BootstrapGUI] INFO  ExtensionStats - Start recording in memory stats
2021-07-29 07:01:56,496 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Custom Pages Definition
2021-07-29 07:01:56,504 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing The ZAP Getting Started Guide
2021-07-29 07:01:56,511 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing This extension allows a user to change the default values used by ZAP Spiders.
2021-07-29 07:01:56,536 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Easy way to replace strings in requests and responses
2021-07-29 07:01:56,547 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionSaveRawHttpMessage
2021-07-29 07:01:56,555 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Adds the Quick Start panel for scanning and exploring applications
2021-07-29 07:01:56,679 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Add the option to use the Ajax Spider in the Quick Start scan
2021-07-29 07:01:56,706 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Launch browsers proxying through ZAP
2021-07-29 07:01:56,709 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Launch browsers proxying through ZAP
2021-07-29 07:01:56,763 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Context alert rules filter
2021-07-29 07:01:56,776 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing DOM XSS Active Scan Rule
2021-07-29 07:01:56,807 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing The Online menu links
2021-07-29 07:01:56,813 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionSaveXMLHttpMessage
2021-07-29 07:01:56,819 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides the GraalVM JavaScript engine for ZAP scripting.
2021-07-29 07:01:57,118 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Heads Up Display
2021-07-29 07:01:57,183 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing ExtensionHUDlaunch
2021-07-29 07:01:57,187 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to inspect and attack GraphQL endpoints.
2021-07-29 07:01:57,211 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Passive Scan Rules
2021-07-29 07:01:57,215 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides support for custom payloads in scan rules.
2021-07-29 07:01:57,220 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows to fuzz WebSocket messages.
2021-07-29 07:01:57,224 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Tips and Tricks
2021-07-29 07:01:57,239 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Provides the foundation for concrete message types (for example, HTTP, WebSockets) expose fuzzer implementations.
2021-07-29 07:01:57,248 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows to fuzz HTTP messages.
2021-07-29 07:01:57,298 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Active Scan Rules
2021-07-29 07:01:57,301 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Allows you to spider and import OpenAPI (Swagger) definitions 
2021-07-29 07:01:57,312 [ZAP-BootstrapGUI] INFO  ExtensionLoader - Initializing Ability to add, edit or remove payloads that are used i.e. by active scanners
2021-07-29 07:01:57,886 [ZAP-BootstrapGUI] INFO  ExtensionCallback - Started callback server on 0.0.0.0:37011
2021-07-29 07:01:57,893 [ZAP-BootstrapGUI] INFO  ExtensionKeyboard - Initializing keyboard shortcuts
2021-07-29 07:02:04,210 [AWT-EventQueue-0] INFO  Control - New Session
2021-07-29 07:02:04,230 [AWT-EventQueue-0] INFO  Control - Create and Open Untitled Db
2021-07-29 07:02:04,292 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2021-07-29 07:02:04,303 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2021-07-29 07:02:04,332 [AWT-EventQueue-0] INFO  ENGINE - Database closed
2021-07-29 07:02:04,537 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open start
2021-07-29 07:02:04,555 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit start
2021-07-29 07:02:04,571 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache commit end
2021-07-29 07:02:04,572 [AWT-EventQueue-0] INFO  ENGINE - dataFileCache open end
2021-07-29 07:02:09,137 [ZAP-cfu] WARN  ExtensionAutoUpdate - Failed to check for updates using: https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions-2.10.xml
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at org.zaproxy.zap.ZAP$ProtocolSocketFactoryImpl.createSocket(ZAP.java:434) ~[zap-2.10.0.jar:2.10.0]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:457) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207) ~[zap-2.10.0.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:?]
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:429) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:671) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:626) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:601) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:584) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:489) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getRemoteConfigurationUrl(ExtensionAutoUpdate.java:1036) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.access$900(ExtensionAutoUpdate.java:92) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$8.run(ExtensionAutoUpdate.java:1205) [zap-2.10.0.jar:2.10.0]
2021-07-29 07:02:18,487 [ZAP-Shutdown] INFO  ENGINE - dataFileCache commit start
2021-07-29 07:02:18,526 [ZAP-Shutdown] INFO  ENGINE - dataFileCache commit end
2021-07-29 07:02:18,554 [ZAP-Shutdown] INFO  ENGINE - Database closed
2021-07-29 07:02:18,690 [ZAP-Shutdown] INFO  Control - OWASP ZAP 2.10.0 terminated.

```

**Comment by thc202** [comment]
ZAP creates its directory in the user home (e.g. `.ZAP`) where it places the add-ons.

**Comment by kingthorin** [comment]
If Kali changed something that's problematic for a specific program thats kinda on the distro to deal with. (From my perspective.) 

I don't have any problems updating ZAP on my Kali VM.

**Comment by TNTBOMBOM** [comment]
> ZAP creates its directory in the user home (e.g. `.ZAP`) where it places the add-ons.

**Comment by kingthorin** [comment]
https://www.kali.org/docs/community/submitting-issues-kali-bug-tracker/

**Comment by kingthorin** [comment]
> Depend on who upload package zaproxy in kali , if kali itself or an outside contributor then yeah their issue but if zaproxy team then no its on zaproxy to fix that.

When we have a new stable release we simply notify them and they package it.

**Comment by TNTBOMBOM** [comment]
> When we have a new stable release we simply notify them and they package it.

Deleted zaproxy from kali , added zaproxy repository and installed owasp-zap from it = Same issue.
