### ISSUE TITLE
Zap throws bunch of exceptions when running for a long time or using saved persisted sessions

### ISSUE THREAD

**Issue by otuva** [zaproxy/zaproxy#6719]
**Describe the bug**
Zap stops responding and throws bunch of errors from terminal 

**To Reproduce**
1- Open ZAP
2- spend time 
3- couple hours later gui freezes, only way to close it is ^C

**Expected behavior**
Not freeze and be able to respond

**Software versions**
 - ZAP: 2.10
 - Add-on: HUNT and HUD
 - OS: Linux Mint 20.1 x86_64 Cinnamon
 - Browser: Mozilla Firefox 90.0.2
 - Java: 
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

<br>

**Errors from the zap.log file**

```
2021-08-02 13:51:24,611 [ZAP-ProxyThread-9] WARN  ProxyListenerLog - java.sql.SQLNonTransientConnectionException: connection exception: closed
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:445) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.model.HistoryReference.<init>(HistoryReference.java:370) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.extension.history.ProxyListenerLog.createHistoryReference(ProxyListenerLog.java:177) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.extension.history.ProxyListenerLog.onHttpResponseReceive(ProxyListenerLog.java:135) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.notifyListenerResponseReceive(ProxyThread.java:733) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:570) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:319) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:517) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:429) ~[zap-2.10.0.jar:2.10.0]
	... 7 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:517) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.db.paros.ParosTableHistory.write(ParosTableHistory.java:429) ~[zap-2.10.0.jar:2.10.0]
	... 7 more
2021-08-02 13:51:24,820 [ZAP-ProxyThread-9] WARN  WebSocketStorage - Could not update state of WebSocket channel to 'OPEN'!
2021-08-02 13:51:24,898 [ZAP-WS-Listener (local) 'push.services.mozilla.com:443 (#1)'] WARN  WebSocketProxy - null
java.lang.NullPointerException: null
	at org.zaproxy.zap.extension.websocket.db.WebSocketStorage.onMessageFrame(WebSocketStorage.java:59) ~[websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:769) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:622) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:78) [websocket-release-23.zap:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-08-02 13:51:25,137 [ZAP-WS-Listener (remote) 'push.services.mozilla.com:443 (#1)'] WARN  WebSocketProxy - null
java.lang.NullPointerException: null
	at org.zaproxy.zap.extension.websocket.db.WebSocketStorage.onMessageFrame(WebSocketStorage.java:59) ~[websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:769) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:622) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:78) [websocket-release-23.zap:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2021-08-02 13:51:28,406 [ZAP-WS-PassiveScanner] WARN  WebSocketPassiveScanThread - Could not get messages from database
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:405) ~[websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread.run(WebSocketPassiveScanThread.java:133) [websocket-release-23.zap:?]
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:396) ~[websocket-release-23.zap:?]
	... 1 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:396) ~[websocket-release-23.zap:?]
	... 1 more
2021-08-02 13:51:28,407 [ZAP-WS-PassiveScanner] WARN  WebSocketPassiveScanThread - Could not get messages from database
org.parosproxy.paros.db.DatabaseException: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:405) ~[websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.pscan.WebSocketPassiveScanThread.run(WebSocketPassiveScanThread.java:133) [websocket-release-23.zap:?]
Caused by: java.sql.SQLNonTransientConnectionException: connection exception: closed
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:396) ~[websocket-release-23.zap:?]
	... 1 more
Caused by: org.hsqldb.HsqlException: connection exception: closed
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.getMessage(TableWebSocket.java:396) ~[websocket-release-23.zap:?]
	... 1 more
2021-08-02 13:51:30,946 [Thread-8] INFO  ENGINE - checkpointClose start
2021-08-02 13:51:30,947 [Thread-8] INFO  ENGINE - checkpointClose synched
2021-08-02 13:51:31,088 [Thread-8] INFO  ENGINE - checkpointClose script done
2021-08-02 13:51:31,089 [Thread-8] INFO  ENGINE - dataFileCache commit start
2021-08-02 13:51:31,612 [Thread-8] INFO  ENGINE - dataFileCache commit end
2021-08-02 13:51:31,670 [Thread-8] INFO  ENGINE - checkpointClose end
2021-08-02 13:56:55,467 [ZAP-ProxyThread-279] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 13:56:55,485 [ZAP-ProxyThread-277] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 13:56:55,582 [ZAP-ProxyThread-278] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 13:56:55,598 [ZAP-ProxyThread-280] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 13:56:57,956 [ZAP-ProxyThread-281] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:24,264 [ZAP-ProxyThread-803] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:24,283 [ZAP-ProxyThread-806] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:25,590 [ZAP-ProxyThread-827] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:26,139 [ZAP-ProxyThread-835] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:26,343 [ZAP-ProxyThread-834] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:26,741 [ZAP-ProxyThread-839] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:26,775 [ZAP-ProxyThread-840] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:27,311 [ZAP-ProxyThread-843] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:04:27,435 [ZAP-ProxyThread-842] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:19:38,815 [ZAP-ProxyThread-1364] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:20:00,079 [ZAP-ProxyThread-1424] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:20:59,784 [ZAP-ProxyThread-1559] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:21:25,162 [ZAP-WS-Listener (local) 'push.services.mozilla.com:443 (#1)'] ERROR WebSocketStorage - java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
org.parosproxy.paros.db.DatabaseException: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.insertMessage(TableWebSocket.java:850) ~[websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.db.WebSocketStorage.onMessageFrame(WebSocketStorage.java:59) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:769) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:622) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:78) [websocket-release-23.zap:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.insertMessage(TableWebSocket.java:834) ~[websocket-release-23.zap:?]
	... 7 more
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Constraint.getException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.index.IndexAVL.insert(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.addInsertAction(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.insertMessage(TableWebSocket.java:834) ~[websocket-release-23.zap:?]
	... 7 more
2021-08-02 14:21:35,186 [ZAP-WS-Listener (local) 'push.services.mozilla.com:443 (#1)'] ERROR WebSocketStorage - java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
org.parosproxy.paros.db.DatabaseException: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.insertMessage(TableWebSocket.java:850) ~[websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.db.WebSocketStorage.onMessageFrame(WebSocketStorage.java:59) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.notifyMessageObservers(WebSocketProxy.java:769) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketProxy.processRead(WebSocketProxy.java:622) [websocket-release-23.zap:?]
	at org.zaproxy.zap.extension.websocket.WebSocketListener.run(WebSocketListener.java:78) [websocket-release-23.zap:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.insertMessage(TableWebSocket.java:834) ~[websocket-release-23.zap:?]
	... 7 more
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation; SYS_PK_10183 table: WEBSOCKET_MESSAGE
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Constraint.getException(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.index.IndexAVL.insert(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.TransactionManager2PL.addInsertAction(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.addInsertAction(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.1.jar:2.5.1]
	at org.zaproxy.zap.extension.websocket.db.TableWebSocket.insertMessage(TableWebSocket.java:834) ~[websocket-release-23.zap:?]
	... 7 more
2021-08-02 14:31:30,577 [AWT-EventQueue-0] INFO  SSLConnector - ClientCert disabled
2021-08-02 14:39:31,112 [ZAP-ProxyThread-2317] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:40:38,933 [ZAP-ProxyThread-2338] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:41:17,392 [ZAP-ProxyThread-2341] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:41:17,400 [ZAP-ProxyThread-2342] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
2021-08-02 14:41:17,409 [ZAP-ProxyThread-2343] WARN  ProxyThread - Failed to write/forward the HTTP response to the client: java.net.SocketException: Broken pipe (Write failed)
```

**Comment by kingthorin** [comment]
This is likely due to Java being out of memory.

**Comment by thc202** [comment]
The first exceptions are caused by the history/websocket trying to use the session while it's being closed, later errors might be related.

**Comment by kingthorin** [comment]
Without specifics to recreate the issue there isn’t much we can do. There’s already an issue open for the web socket exceptions.
