### ISSUE TITLE
Extension's errors during shutdown prevent ZAP to exit

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#6755]
**Describe the bug**
ZAP does not terminate. I think it's a problem after installation of automation framework.

**To Reproduce**
1. Run ZAP (Installed automation framework / 0.4.1)
2. Click window close button or `Menu` > `File` > `Exit`. but not terminated.
3. See logs below.

**Expected behavior**
Terminated ZAP

**Screenshots**
![1414](https://user-images.githubusercontent.com/13212227/129483729-8c37fe1c-e62e-48b2-a5a4-7f82bb8dd3a8.jpg)

**Software versions**
 - ZAP: latest(ZAP 2.10.0)
 - Add-on: Automation framework 0.4.1
 - OS: Macos Bigsur and Ubuntu 20.04 (Both was installed with package)

**Errors from the zap.log file**
```
29484 [AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "AWT-EventQueue-0"
java.lang.NoClassDefFoundError: Could not initialize class org.zaproxy.addon.automation.gui.AutomationPanel
	at org.zaproxy.addon.automation.ExtensionAutomation.getAutomationPanel(ExtensionAutomation.java:143) ~[?:?]
	at org.zaproxy.addon.automation.ExtensionAutomation.getUnsavedResources(ExtensionAutomation.java:136) ~[?:?]
	at org.parosproxy.paros.extension.ExtensionLoader.getUnsavedResources(ExtensionLoader.java:1584) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.Control.exit(Control.java:247) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.control.MenuFileControl.exit(MenuFileControl.java:105) ~[zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.view.MainFrame$1.windowClosing(MainFrame.java:269) ~[zap-2.10.0.jar:2.10.0]
	at java.awt.Window.processWindowEvent(Window.java:2078) ~[?:?]
	at javax.swing.JFrame.processWindowEvent(JFrame.java:298) ~[?:?]
	at java.awt.Window.processEvent(Window.java:2037) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

**Comment by thc202** [comment]
The issue (zaproxy/zap-extensions#3060) with the Automation add-on was fixed in 0.4.1. If you launch ZAP with the newer version is should no longer block.

**Comment by hahwul** [comment]
Hi @thc202 
Oh yes, my mistake to version. 
(I thought it was version 0.4.1 because it was clicked update button in marketplace.. not actually updated)

It closed well in 0.4.1. However, update is not possible if version 0.4.0 is already installed. (similar error)

There may be other people who have a similar phenomenon to me, so I write a solution for update.
And now that I understand the problem, I'll close the issue! Thank you so much 😍

## Workaround if 0.4.0 is installed
1) Find your ZAP working dir (https://www.zaproxy.org/faq/what-is-the-default-directory-that-zap-uses/)
2) Remove automation framework 0.4.0 
```
$ rm -rf ~/.ZAP/plugin/automation-alpha-0.4.0.zap
```
3) Reboot ZAP, and install automation framework version 0.4.1

**Comment by hahwul** [comment]
@thc202 
Oh sorry, was there any additional work scheduled? so I reopen. Let me know if I can close it.

**Comment by thc202** [comment]
We do need to change core to not fail to exit in case of errors, it will be closed automatically once that's done.
