### ISSUE TITLE
Can not get successful result from zap proxy while configure setAuthenticationmethod and also setAuthenticationCredentials 

### ISSUE THREAD

**Issue by devtrap** [zaproxy/zaproxy#6929]
Hi,

I'm not able to get successful result from zap server while I'm trying to set authentication method as formBasedAuthentication, also can not setAuthenticationCredentials.
I faced with below message with no error for both functions :
```
map[code:missing_parameter message:Missing Parameter]
```

I'm using golang sdk with below sample code : 
```
func (rcv PentestRcv) SetupAuthentication(cred interface{}, ctx Context, AuthMethod string) {
	switch AuthMethod {
	case FormBased:
		FormBasedAuthentication(rcv, ctx, cred)
	}

}

func FormBasedAuthentication(zapCli PentestRcv, ctx Context, cred interface{}) {
	// authConfigParams := loginUrl
	formCred := cred.(FomeBasedAuth)
	loginRequestData := `username={%username%}&password={%password%}`
	config := PrepareConifgParam(formCred.LoginUrl, loginRequestData)
	a, e := zapCli.Interface.Authentication().SetAuthenticationMethod(ctx.ID, FormBased, config)
	fmt.Println("//////////")
	fmt.Println(a, e)
	SetLoggedInIndicator(zapCli, ctx)
	SetUserAuthConfig(zapCli, ctx)

}

func PrepareConifgParam(loginUrl, loginRequestData string) string {
	return url.QueryEscape(fmt.Sprintf("loginUrl=%s&loginRequestData=%s", loginUrl, loginRequestData))
}

func SetLoggedInIndicator(zapCli PentestRcv, ctx Context) {
	logged_in_regex := `\Q<a href="logout.jsp">Logout</a>\E`
	zapCli.Interface.Authentication().SetLoggedInIndicator(ctx.ID, logged_in_regex)
}

func SetUserAuthConfig(zapCli PentestRcv, ctx Context) {
	user := "prancer-test"
	username := "rm.mehrad@gmail.com"
	password := "mehrad"

	userId, err := zapCli.Interface.Users().NewUser(ctx.ID, user)
	fmt.Println(userId)
	_ = err
	userAuthConfig := fmt.Sprintf("username=%s&password=%s", url.QueryEscape(username), url.QueryEscape(password))
	_ = userAuthConfig
	strUserId := userId["userId"].(string)
	fmt.Println(ctx.ID, userId["userId"].(string), userAuthConfig)
	resp, err := zapCli.Interface.Users().SetAuthenticationCredentials(ctx.ID, strUserId, userAuthConfig)
	fmt.Println(resp, err)
	b, e := zapCli.Interface.Users().GetAuthenticationCredentials(ctx.ID, strUserId)
	fmt.Println(b, e)
	d, e := zapCli.Interface.Users().UsersList(ctx.ID)
	fmt.Println("d,e :", d, e)

}

```

Also here it's zap log : 
```
6244 [ZAP-ProxyThread-1] INFO  net.sf.json.xml.XMLSerializer - Using default type string
155846 [ZAP-ProxyThread-38] ERROR org.zaproxy.zap.extension.api.API - illegal_parameter
org.zaproxy.zap.extension.api.ApiException: illegal_parameter
	at org.zaproxy.zap.extension.api.API.getParams(API.java:839) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.authentication.AuthenticationAPI.handleApiAction(AuthenticationAPI.java:178) [zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:507) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:497) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
155863 [ZAP-ProxyThread-38] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/authentication/action/setAuthenticationMethod/] from [172.17.0.1]:
org.zaproxy.zap.extension.api.ApiException: missing_parameter
	at org.zaproxy.zap.utils.ApiUtils.getNonEmptyStringParam(ApiUtils.java:104) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.authentication.PostBasedAuthenticationMethodType$2.handleAction(PostBasedAuthenticationMethodType.java:1365) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.authentication.AuthenticationAPI.handleApiAction(AuthenticationAPI.java:186) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:507) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:497) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
156021 [ZAP-ProxyThread-41] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/users/action/setAuthenticationCredentials/] from [172.17.0.1]:
org.zaproxy.zap.extension.api.ApiException: missing_parameter
	at org.zaproxy.zap.utils.ApiUtils.getNonEmptyStringParam(ApiUtils.java:104) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.authentication.ManualAuthenticationMethodType$2.handleAction(ManualAuthenticationMethodType.java:459) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.users.UsersAPI.handleApiAction(UsersAPI.java:301) ~[zap-2.10.0.jar:2.10.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:507) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:497) [zap-2.10.0.jar:2.10.0]
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333) [zap-2.10.0.jar:2.10.0]
	at java.lang.Thread.run(Thread.java:834) [?:?]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/zap/./plugin/soap-alpha-4.zap) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
158158 [ZAP-Import-WSDL-1] ERROR org.zaproxy.zap.extension.soap.WSDLCustomParser - There was an error while parsing WSDL content. 
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652) ~[?:?]
	at javax.xml.stream.XMLStreamReader$next$1.call(Unknown Source) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[soap-alpha-4.zap:?]
	at com.predic8.wsdl.WSDLParser.parseLocal(WSDLParser.groovy:53) ~[soap-alpha-4.zap:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174) ~[soap-alpha-4.zap:?]
	at com.predic8.soamodel.AbstractParser.parse(AbstractParser.groovy:35) ~[soap-alpha-4.zap:?]
	at com.predic8.wsdl.WSDLParser.super$2$parse(WSDLParser.groovy) ~[soap-alpha-4.zap:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[soap-alpha-4.zap:?]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[soap-alpha-4.zap:?]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215) ~[soap-alpha-4.zap:?]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132) ~[soap-alpha-4.zap:?]
	at com.predic8.wsdl.WSDLParser.parse(WSDLParser.groovy:28) ~[soap-alpha-4.zap:?]
	at org.zaproxy.zap.extension.soap.WSDLCustomParser.parseWSDLContent(WSDLCustomParser.java:225) [soap-alpha-4.zap:?]
	at org.zaproxy.zap.extension.soap.WSDLCustomParser.parseWSDLContent(WSDLCustomParser.java:237) [soap-alpha-4.zap:?]
	at org.zaproxy.zap.extension.soap.WSDLCustomParser.parseWSDLUrl(WSDLCustomParser.java:209) [soap-alpha-4.zap:?]
	at org.zaproxy.zap.extension.soap.WSDLCustomParser.access$000(WSDLCustomParser.java:69) [soap-alpha-4.zap:?]
	at org.zaproxy.zap.extension.soap.WSDLCustomParser$1.run(WSDLCustomParser.java:90) [soap-alpha-4.zap:?]
216061 [ZAP-ProxyThread-57] INFO  net.sf.json.xml.XMLSerializer - Using default type string

```

would you please help me to understand if there is any problem with this case ?

**Comment by psiinon** [comment]
These kind of issues are likely to be bugs in your code rather than in ZAP (unless we find otherwise;)
So please as on the ZAP User Group as thats a better forum for them: https://groups.google.com/group/zaproxy-users
