### ISSUE TITLE
Use of commas within regex for contexts renders them unloadable 

### ISSUE THREAD

**Issue by Z2gwNTcK** [zaproxy/zaproxy#6957]
## Summary
When regular expressions are created using braces, the GUI will save the user input during the current working session and behave as expected. However, if the user restarts OWASP Zap and attempts to import the context into a new session, the resulting action creates an exception. This is based upon how the rendered context file is created where braces and commas are involved.

## System Information
* OWASP ZAP version 2.11.0
* Tested on both Ubuntu and OSX

## Steps to Reproduce
1. Launch OWASP Zap.
2. Double-click on the Default Context to launch the Session Properties modal. Select "Include In Context".
3. Click the "Add..." button and enter the following regular expression: `http[s]{0,1}:\/\/[a-zA-Z0-9.-]{1,}(google.com)\/{0,1}(.*)`. Click the "Add" button when done.
4. Click the "OK" button to close the Session Properties modal.
5. Right-click on the Default Context and select "Export Context..".
6. Save the context somewhere on your local drive.
7. Locate the context file on your local drive and view the contents. For the example above, here is the first few nodes of the XML content:
    ```<configuration>
        <context>
            <name>Default Context</name>
            <desc/>
            <inscope>true</inscope>
            <incregexes>http[s]{0</incregexes>
            <incregexes>1}:\/\/[a-zA-Z0-9.-]{1</incregexes>
            <incregexes>}(google.com)\/{0</incregexes>
            <incregexes>1}(.*)</incregexes>
8. Exit OWASP Zap and re-open the application.
9. Click the "Import Context..." icon and select the context you just created.
10. _*NOTICE:* You now see a "Failed to import Context" error suggesting that the issue is the first node containing some portion of the regular expression (i.e. `http[s]{0`).
11. Repeat the same process as above, exept this time use the following regular expression: `http[s]?:\/\/[a-zA-Z0-9.-]+(google.com)\/?(.*)`. Note that the difference is that quantifiers used have the same meaning but use different symbols (i.e. https://docs.microsoft.com/en-us/dotnet/standard/base-types/quantifiers-in-regular-expressions). The resulting XML now looks like this when viewing the contents of the new context file:
      ```<configuration>
          <context>
              <name>New Context</name>
              <desc/>
              <inscope>true</inscope>
              <incregexes>http[s]?:\/\/[a-zA-Z0-9.-]+(google.com)\/?(.*)</incregexes>

## Log Output (from zap.log)
```
java.util.regex.PatternSyntaxException: Unclosed counted closure near index 9
http[s]{0
	at java.util.regex.Pattern.error(Pattern.java:2027) ~[?:?]
	at java.util.regex.Pattern.closure(Pattern.java:3304) ~[?:?]
	at java.util.regex.Pattern.sequence(Pattern.java:2213) ~[?:?]
	at java.util.regex.Pattern.expr(Pattern.java:2068) ~[?:?]
	at java.util.regex.Pattern.compile(Pattern.java:1782) ~[?:?]
	at java.util.regex.Pattern.<init>(Pattern.java:1428) ~[?:?]
	at java.util.regex.Pattern.compile(Pattern.java:1094) ~[?:?]
	at org.zaproxy.zap.model.Context.validateRegex(Context.java:364) ~[zap-2.11.0.jar:2.11.0]
	at org.zaproxy.zap.model.Context.addIncludeInContextRegex(Context.java:402) ~[zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1542) ~[zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.control.MenuFileControl.importContext(MenuFileControl.java:594) [zap-2.11.0.jar:2.11.0]
	at org.parosproxy.paros.view.SiteMapPanel$3.actionPerformed(SiteMapPanel.java:283) [zap-2.11.0.jar:2.11.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) [?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```

## Bug Fix Suggestion
Both syntax structures should be honored. Serialization of the regular expression might help resolve characters being accidentally interpreted by the underlying code.

## Success
Regular expressions which utilize braces can now be accepted as input for the development of contexts.

**Comment by thc202** [comment]
The problem is caused by the commas, tweaked issue tittle.

**Comment by thc202** [comment]
@kingthorin are you working on this or plan to? Added to the 2.13 milestone.

**Comment by kingthorin** [comment]
I had planned to, but I honestly haven't dug into the code at all yet. If you're up for it don't let me stop you.

**Comment by kingthorin** [comment]
I've started to look at this.
According to the JavaDoc `ZapXmlConfiguration` has `setDelimiterParsingDisabled` disabled (true). I tried setting `setListDelimiter` to a totally irrelevant character. Neither of those seemed to help. Changing the export of the context o use `        c.getIncludeInContextRegexs().forEach(regex -> config.addProperty(Context.CONTEXT_CONFIG_INC_REGEXES, regex));` does seem to work.

Any objection to me changing Session.exportContext to that mechanism for include/exclude regexs?

**Comment by thc202** [comment]
I also looked at this, and this is a general problem (I'd say a bug in Commons Configuration, since we have delimiter parsing disabled), setting anything that is not a `String` leads to (potential) splits (see `HierarchicalConfiguration` line 742 and the `flatten` behaviour). Using `addProperty` on each call site is a workaround, we should fix the underlying issue for everything (IMO, override the `setProperty`).

These properties are affected in the Context export:
```
context.incregexes
context.excregexes
context.tech.include
context.tech.exclude
```
(The latter two are not an actual problem, since we don't use commas in the names.)

Whatever we do we should add tests and review all code that sets lists.

**Comment by thc202** [comment]
Rereading the code again a better(?) fix is to explicitly set the list delimiter to the disabled char (i.e. in `ZapXmlConfiguration` constructor call `super.setListDelimiter('\0');`), once we have unit tests in `ZapXmlConfiguration` we can play with the fixes :)

**Comment by kingthorin** [comment]
Thanks.

I’ll start looking at adding some tests, that we can build on for future fixes.

**Comment by kingthorin** [comment]
So here's what I've added so far:
- A test that sets and retrieves values for string, int, float, boolean
- A test that sets and retrieves values as lists for string, int, float, boolean
- A test that sets a list of string values that includes comma values and manifests this issue (currently `@Disabled`).

What other scenarios should I add?

**Comment by thc202** [comment]
Set a list of objects (other than `String`), to cover cases like `OptionsParamCheckForUpdates.setAddonDirectories(List<File>)`.
