### ISSUE TITLE
Unable to generate "Risk and Confidence HTML" report with newer Java versions

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7026]
From OWASP ZAP User Group: https://groups.google.com/g/zaproxy-users/c/tZi6U4fbTPo/m/pzOmyJ59AQAJ

Attempting to generate a Risk and Confidence HTML report with Java 17 leads to an exception:
```
ERROR org.zaproxy.addon.reports.ReportDialog - Failed to generate a report using template org.zaproxy.addon.reports.Template@40afba15
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "alertTree.children.hasMoreElements()? alertTree.depthFirstEnumeration().{? #this.isLeaf()}: {}" (template: "/ZAP_D/reports/risk-confidence-html/report.html" - line 32, col 3)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[?:?]
	at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
[...]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$EmptyEnumeration.hasMoreElements() accessible: module java.base does not "opens java.util" to unnamed module @4b0edff5
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
```

That's the only report failing.

Updating to latest version (`3.0.14.RELEASE`) does not address the issue, some of the unit tests start failing:
```
[1] traditional-json shouldGenerateExpectedReport
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "helper.legacyEscapeText(instance.param, true)" (template: "/zaproxy/zap-extensions/addOns/reports/build/resources/main/reports/traditional-json/report.json" - line 24, col 20)
[...]
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Instantiation of new objects and access to static classes or parameters is forbidden in this context
	at app//org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.obtainComputedOGNLExpression(OGNLVariableExpressionEvaluator.java:207)
	at app//org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:123)
	... 170 more
```

```
shouldGenerateValidJsonReport()
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "helper.legacyEscapeText(instance.param, true)" (template: "/zaproxy/zap-extensions/addOns/reports/build/resources/main/reports/traditional-json/report.json" - line 24, col 20)
[...]
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Instantiation of new objects and access to static classes or parameters is forbidden in this context
	at app//org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.obtainComputedOGNLExpression(OGNLVariableExpressionEvaluator.java:207)
	at app//org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:123)
	... 119 more
```

**Comment by psiinon** [comment]
As per #7070 for the time being the workaround is to use an older Java version (e.g. 11).

**Comment by psiinon** [comment]
The unit test failures appear to be related to this issue: https://github.com/thymeleaf/thymeleaf-spring/issues/275

**Comment by psiinon** [comment]
This problem is fixed in the latest version of the reports add-on now available via the ZAP Marketplace.
