### ISSUE TITLE
Automation Framework - Add-On Job - Add UI - Save button - java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by tspearconquest** [zaproxy/zaproxy#7075]
**Describe the bug**
When trying to configure the automation framework via the ZAP Desktop GUI to install an addon such as ascanrulesAlpha or pscanrulesAlpha, the Save button does not save nor close the dialog, and instead produces a stack trace as per https://groups.google.com/g/zaproxy-users/c/dyQ9U9MPF20/m/ZixcQvPKAwAJ

**To Reproduce**
1. Open ZAP Desktop
2. Add the Automation Framework in the bottom half of the GUI
3. Create a new plan based on the zap full scan profile
4. Double click on the second job (addOns)
5. Click on Add next to Install or Uninstall
6. Type in a valid addon ID such as pscanrulesAlpha
7. Click Save

**Expected behavior**
Addon ID saves

**Screenshots**
![image](https://user-images.githubusercontent.com/81998567/152845103-05182316-c857-4ad3-a40f-912119238547.png)

**Software versions**
 - ZAP: 2.11.1
 - Add-on: Automation Framework v0.12.0
 - OS: Mac
 - Java: 17.0.1
 - Browser: n/a

**Errors from the zap.log file**
```
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_252]
        at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_252]
        at org.zaproxy.addon.automation.gui.AddOnsTableModel.add(AddOnsTableModel.java:88) ~[?:?]
        at org.zaproxy.addon.automation.gui.AddAddOnsDialog.save(AddAddOnsDialog.java:45) ~[?:?]
        at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:427) ~[main/:?]
        at org.zaproxy.zap.view.StandardFieldsDialog.access$1(StandardFieldsDialog.java:417) ~[main/:?]
        at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:410) ~[main/:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_252]
```

**Comment by kingthorin** [comment]
>  - Add-on: Name and version [e.g. Passive Scan Rules Alpha v19. https://www.zaproxy.org/faq/how-do-i-see-what-version-of-an-add-on-extension-i-have-installed/]

What version of the automation add-on?
