### ISSUE TITLE
exim: Unhandled exception importing URLs

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#7081]
https://groups.google.com/g/zaproxy-develop/c/k8uf5EJ5sko

```
Output  "Error importing /Users/Me/Desktop/url.txt"

It doesn't matter if  url.txt exists or not
Same issue for importing OpenAPI defs

On a Mac Big Sur 11.6.2
OWASP ZAP  2.11.1

2022-02-09 14:52:52,581 [ZAP-Exim-Import-Urls-9] ERROR UrlsImporter - /Users/Me/Downloads/url.txt: Operation not permitted
java.nio.file.FileSystemException: /Users/mhankel/Downloads/url.txt: Operation not permitted
        at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newInputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:?]
        at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:?]
        at org.zaproxy.addon.exim.urls.UrlsImporter.importUrlFile(UrlsImporter.java:55) ~[?:?]
        at org.zaproxy.addon.exim.urls.MenuItemImportUrls.lambda$new$0(MenuItemImportUrls.java:50) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

> Changed the download directory.  It works now

**Comment by kingthorin** [comment]
Technically it isn't unhandled, it's just overly verbose.

**Comment by thc202** [comment]
It would be better to validate if the file being chosen is readable.
