### ISSUE TITLE
ZAP Error [java.net.SocketException]: Connection reset

### ISSUE THREAD

**Issue by b8045** [zaproxy/zaproxy#7091]
### Describe the bug

When trying to access when of our internal applications while proxying through ZAP, I am getting an error in the browser 'ZAP Error [java.net.SocketException]: Connection reset'.
I've tried using both the in-built browser and external browsers.
The error only occurs when proxying through ZAP.
The application I'm trying to access does not require an outgoing proxy.

### Steps to reproduce the behavior

n/a (internal site that can't be accessed from outside the organisation)

### Expected behavior

Site opens

### Software versions

ZAP v2.11.1
java openjdk version "11.0.8" 2020-07-14
OS Windows10

### Screenshots

ZAP Error [java.net.SocketException]: Connection reset

Stack Trace:
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:860)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2278)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1160)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:470)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:430)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:672)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:627)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:602)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:585)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:460)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:562)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:319)
	at java.lang.Thread.run(Thread.java:745)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
Does ZAP proxy browser connections when started using the .bat file?
Can ZAP scan your app when started via the exe?

**Comment by b8045** [comment]
I think I've solved the issue.
I was using Openjdk  java version "11.0.8" 2020-07-14 

I've changed this to Oracle java version "16.0.1" 2021-04-20 and everything is working as expected now.

**Comment by kingthorin** [comment]
Since the connection was actively being reset I'm going to suggest that this was more likely a Windows FW issue that was resolved when you installed a different package, it asked about access and you chose the right option :wink:
