### ISSUE TITLE
Exception when importing OpenAPI definition

### ISSUE THREAD

**Issue by costelacostanza** [zaproxy/zaproxy#7115]
### Describe the bug

When trying to import an Oauth Specification yaml file, a Null pointer exception is thrown:
```yaml
openapi: 3.0.3
info:
  title: Test Service
  version: 2.0.0-draft34
  contact:
    name: Test Engineering
    email: test
paths:
 /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
```

```
java.lang.NullPointerException
	at org.zaproxy.zap.extension.openapi.generators.HeadersGenerator.generateAcceptHeaders(HeadersGenerator.java:123)
	at org.zaproxy.zap.extension.openapi.generators.HeadersGenerator.generate(HeadersGenerator.java:52)
	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.generateHeaders(RequestModelConverter.java:55)
	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.convert(RequestModelConverter.java:49)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertToRequest(SwaggerConverter.java:191)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:185)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:365)
Failed to parse OpenAPI definition.
```
Other locations that trigger NPEs are:
```
java.lang.NullPointerException
	at org.zaproxy.zap.extension.openapi.generators.DataGenerator.getDefaultValue(DataGenerator.java:103)
	at org.zaproxy.zap.extension.openapi.generators.DataGenerator.generateValue(DataGenerator.java:170)
	at org.zaproxy.zap.extension.openapi.generators.DataGenerator.generateBodyValue(DataGenerator.java:166)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generateJsonPrimitiveValue(BodyGenerator.java:200)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:119)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generateFromArraySchema(BodyGenerator.java:147)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:105)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:94)
	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.generateBody(RequestModelConverter.java:71)
	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.convert(RequestModelConverter.java:47)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertToRequest(SwaggerConverter.java:191)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:185)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:365)
Failed to parse OpenAPI definition.
```
and 
```
java.lang.NullPointerException
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:205)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:184)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:365)
Failed to parse OpenAPI definition.
```

### Steps to reproduce the behavior

Import --> An openAPI definition from the local file system
select a file containing a file such as follows:
```yaml
openapi: 3.0.3
info:
  title: Test Service
  version: 2.0.0-draft34
  contact:
    name: Test Engineering
    email: test
paths:
 /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
```

### Expected behavior

An explanation is provided stating that the file is invalid/valid for whichever reason, allowing easier debugging and fixing of the spec if required. Or error is caught and ignored if not required for creating url map.

### Software versions

from owasp/zap2docker-weekly:latest as of Mar 3 2022

### Screenshots

![image](https://user-images.githubusercontent.com/6401386/156779390-7c021944-8261-49c8-835a-71fb701daa87.png)

### Errors from the zap.log file

```
java.lang.NullPointerException
	at org.zaproxy.zap.extension.openapi.generators.DataGenerator.getDefaultValue(DataGenerator.java:103)
	at org.zaproxy.zap.extension.openapi.generators.DataGenerator.generateValue(DataGenerator.java:170)
	at org.zaproxy.zap.extension.openapi.generators.DataGenerator.generateBodyValue(DataGenerator.java:166)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generateJsonPrimitiveValue(BodyGenerator.java:200)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:119)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generateFromArraySchema(BodyGenerator.java:147)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:105)
	at org.zaproxy.zap.extension.openapi.generators.BodyGenerator.generate(BodyGenerator.java:94)
	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.generateBody(RequestModelConverter.java:71)
	at org.zaproxy.zap.extension.openapi.converter.swagger.RequestModelConverter.convert(RequestModelConverter.java:47)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.convertToRequest(SwaggerConverter.java:191)
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:185)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:365)
Failed to parse OpenAPI definition.
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
For the dev docs: https://www.zaproxy.org/docs/developer/

Let us know if you have any question.

**Comment by thc202** [comment]
@costelacostanza do you still plan to work on this?

**Comment by costelacostanza** [comment]
Hi,

I'm working around it at the moment. It seems like the issues are in the external library so not much can be done I don't think. Simon emailed me and I said he could reassign.
________________________________

**Comment by thc202** [comment]
OK, thank you.

**Comment by kingthorin** [comment]
I've put together a fix for the reported NPE and the provided test yaml. However, this will simply allow the proper warning to bubble up since the provided spec doesn't define any responses.
