### ISSUE TITLE
pscanrules: test error on InformationDisclosureReferrerScanRuleUnitTest with Eclipse

### ISSUE THREAD

**Issue by rugk** [zaproxy/zaproxy#7121]
### Describe the bug

The test `InformationDisclosureReferrerScanRuleUnitTest`->`shouldRaiseAlertWhenCreditCardInReferer` fails for me.
All others work.

### Steps to reproduce the behavior

0. I installed Eclipse (Java) on Linux via [Flathub](https://flathub.org/apps/details/org.eclipse.Java). 
1. I accidentally opened the `zap-extensions` project just as a project dir, which kinda looked, good but then looked into the doc (point below) and set it up properly using gradle import…
2. I set up the project [as stated there](https://www.zaproxy.org/docs/developer/building-zap-with-eclipse/#import-the-zap-repositories) i.e. import via gradle, but only for `zap-extensions`, because I do not want to run the actual code, but just tests (of this particular repository), so I think this is fine. (BTW that import process took _ages_ wtf, which gradle stuff, does it download and so on.)
4. I run all the JUnit tests for pscanrules:
![grafik](https://user-images.githubusercontent.com/11966684/157034998-c5a7c7a7-5266-49ae-a259-1abd16e229ab.png)

-> Ran: 430; Failed: 1 ("Errors", no "Failures" whatever that means), Skipped: 3

I can also run all the tests for the `InformationDisclosureReferrerScanRuleUnitTest` file too and it's the same, 15 tests run, one fails.
All others work.

It fails with this bbasically as far as I see:
```
13:36:17.954 [main] ERROR org.parosproxy.paros.common.AbstractParam - No write access to directory /tmp/junit8938835657286392160/home/plugin
java.security.InvalidParameterException: No write access to directory /tmp/junit8938835657286392160/home/plugin
	at org.zaproxy.zap.extension.autoupdate.OptionsParamCheckForUpdates.setDownloadDirectory(OptionsParamCheckForUpdates.java:330) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.extension.autoupdate.OptionsParamCheckForUpdates.parse(OptionsParamCheckForUpdates.java:100) ~[zap-2.11.1.jar:2.11.1]
```

### Expected behavior

No test failures.

### Software versions

Eclipse IDE for Java Developers (includes Incubating components)

Version: 2021-12 (4.22.0)
Build id: 20211202-1639

<details>
<summary>Flatpak details</summary>

```
$ flatpak info org.eclipse.Java

Eclipse IDE for Java Developers - The essential tools for any Java developer,
including a Java IDE, a Git client, XML Editor, Maven and Gradle integration

          ID: org.eclipse.Java
         Ref: app/org.eclipse.Java/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.22
     License: EPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 365.8�MB
     Runtime: org.gnome.Platform/x86_64/41
         Sdk: org.gnome.Sdk/x86_64/41

      Commit: fa98ae04d6872b2f2d84b578905c1514c248e00ce1e8df0fa9c931a3497c02a8
      Parent: 8e557316ab7b190499cd046e5770a6585352998c88ea97322b884de225974f31
     Subject: Update README.md (1b5a5a2a)
        Date: 2022-01-26 09:42:47 +0000
$ flatpak --version
Flatpak 1.12.5
```

</details>

source code:
* reproduced at https://github.com/zaproxy/zap-extensions/commit/f1a4eda62
* reproduced at https://github.com/zaproxy/zap-extensions/commit/10f37b77e now (all further tests done with that state)

Fedora Linux 35 (Workstation Edition)
GNOME 41.3

Eclipse configuration: https://gist.github.com/rugk/419fe08b9b6bb30d2ab7d1309faa8244

### Screenshots

![grafik](https://user-images.githubusercontent.com/11966684/157035206-4a60cb37-d52e-41bd-8e83-a35991d097ad.png)

### Errors from the zap.log file

Stacktrace: https://gist.github.com/rugk/302bc49794a8fdc6be284f68118aaaa1

### Additional context

Note Flatpak may have permission constraint of what can be accessed. However as far as I read what is is written to just a `/tmp` directory, so that should not fail and is of course always available.

Discovered while working on https://github.com/zaproxy/zap-extensions/pull/3627

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
From the Console stack trace `No write access to directory /tmp`...
Note that these tests run on all PRs and work fine in that environment.

**Comment by rugk** [comment]
Found https://github.com/flathub/org.eclipse.Java/issues/42 which is very similar, but it seems to be already solved, also in the latest version that flatpak has access to `/tmp`:
https://github.com/flathub/org.eclipse.Java/blob/1b5a5a2a7da75a421a37d4511fa0e6396abf5996/org.eclipse.Java.json#L11

Also I wonder why only this one test fails and all others work, does only this one run/use `/tmp`?

**Comment by thc202** [comment]
Run just that test class and provide the whole stacktrace.

**Comment by rugk** [comment]
Did not I? That was a huge crazy thing? It's already linked?

I have now ran the _class_ only again.

```
java.lang.NoSuchMethodError: 'java.lang.String org.apache.commons.csv.CSVFormat.access$000(org.apache.commons.csv.CSVFormat)'
	at org.apache.commons.csv.CSVFormat$Builder.<init>(CSVFormat.java:230)
	at org.apache.commons.csv.CSVFormat$Builder.create(CSVFormat.java:178)
	at org.zaproxy.addon.commonlib.binlist.BinList.createTrie(BinList.java:74)
	at org.zaproxy.addon.commonlib.binlist.BinList.<init>(BinList.java:49)
	at org.zaproxy.addon.commonlib.binlist.BinList.createSingleton(BinList.java:61)
	at org.zaproxy.addon.commonlib.binlist.BinList.getSingleton(BinList.java:54)
	at org.zaproxy.zap.extension.pscanrules.InformationDisclosureReferrerScanRule.scanHttpRequestSend(InformationDisclosureReferrerScanRule.java:89)
	at org.zaproxy.zap.testutils.PassiveScannerTestUtils.scanHttpRequestSend(PassiveScannerTestUtils.java:98)
	at org.zaproxy.zap.extension.pscanrules.InformationDisclosureReferrerScanRuleUnitTest.shouldRaiseAlertWhenCreditCardInReferer(InformationDisclosureReferrerScanRuleUnitTest.java:265)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

Okay wtf this is a different error…

The installed java **on the host** is BTW this one (but AFAIK/I guess it uses the java internally in the flatpak – or maybe it does not, after all :astonished:)

```
$ java --version                              
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1, mixed mode, sharing)
```

**Comment by rugk** [comment]
> Are you able to run the tests from the command line without errors?

How would one do that? [This guide](https://www.zaproxy.org/docs/developer/quick-start-build/) does not mention the tests at all…

 >That one is a known problem with Eclipse classpath ordering…
 
 Wtf? And Eclipse fails your tests? What the hell is that? Is there any link/doc on that problem… or… after all… some bug in Eclipse to fix it, if it is really it's fault?

**Comment by kingthorin** [comment]
No it’s not covered I the Quick Start guide 😉 (Though off the top of my head I’ll admit I don’t know where/if it’s covered).

The Eclipse issue is fixable, though not necessarily easily explained. I’ll see if I can get a fresh dev VM setup next week and knock something together.

**Comment by thc202** [comment]
Run the test task, e.g.: `./gradlew aO:pscanrules:test`.

It's actually called "JAR hell", different versions of the same library one has the constructor the other doesn't. Either in Eclipse or Buildship.

**Comment by rugk** [comment]
> The Eclipse issue is fixable, though not necessarily easily explained. I’ll see if I can get a fresh dev VM setup next week and knock something together.

Well but is it really your task to fix it or rather Eclipse's one? Note my Java knowledge is quite limited here (at least I did not found such in-depth problems when I used it in the past.)

> It's actually called "JAR hell", different versions of the same library one has the constructor the other doesn't. Either in Eclipse or Buildship.

Welll… uuhh wtf… to me this still sounds like an issue of these IDEs and they should fix it… (note I already posted my exact configuration and the flatpak should alos make it easy to reproduce the issue)

**Comment by rugk** [comment]
> Run the test task, e.g.: ./gradlew aO:pscanrules:test.

Thanks, that worked. I could only run it at the host though (as it is AFAIK not easy to get a shell in a flatpak), but it worked:
```
zap-extensions on  patch-1 
➜ ./gradlew aO:pscanrules:test

Welcome to Gradle 7.3.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3.3/release-notes.html

Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins

> Task :addOns:pscanrules:test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

BUILD SUCCESSFUL in 56s
32 actionable tasks: 25 executed, 7 up-to-date
```

ref https://github.com/zaproxy/zap-extensions/commit/81ab76ca6

**Comment by thc202** [comment]
Closing, this is not an issue with the codebase. You can reorder the classpath entries to avoid it, dev mailing list is better place for these questions.

**Comment by rugk** [comment]
> dev mailing list is better place for these questions.

Besides the fact that I did not know this exists, it is certainly not, because when someone else has the same issue, they can at least find it here now and not hidden in some mailing list one cannot easily search.

**Comment by psiinon** [comment]
The mailing lists can be easily searched, you just need to join them.

**Comment by thc202** [comment]
Search works fine: https://groups.google.com/g/zaproxy-develop/search?q=eclipse

The mailing lists are linked from [Get In Touch](https://www.zaproxy.org/community/) in the Community page, they are also mentioned when trying to raise issues: https://github.com/zaproxy/zaproxy/issues/new/choose
