### ISSUE TITLE
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper [ZAP 2.11.1, Ubuntu 20.04.4 LTS]

### ISSUE THREAD

**Issue by aenagy** [zaproxy/zaproxy#7217]
### Describe the bug

(1) Running "ZAP_2_11_1_unix.sh" did not display GUI window. Install ran in terminal.
(2) zap.sh generates error "java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper"
(3) Launching ZAP from desktop does nothing.

### Steps to reproduce the behavior

```
$` zap.sh
Found Java version 1.8.0_312
Available memory: 3925 MB
Using JVM args: -Xmx981m
441 [main] INFO  org.zaproxy.zap.GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 03:46:19 with home /home/aenagy1/.ZAP/
472 [main] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
```

### Expected behavior

(1) Running "ZAP_2_11_1_unix.sh" should launch GUI installer.
(2) zap.sh should not generate errors.
(3) Launching ZAP should launch GUI window.

### Software versions

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

### Errors from the zap.log file

```
$ cat /home/aenagy1/.ZAP/zap.log
2022-04-18 01:43:41,174 [main ] INFO  Constant - Copying default configuration to /home/aenagy1/.ZAP/config.xml
2022-04-18 01:43:41,234 [main ] INFO  Constant - Creating directory /home/aenagy1/.ZAP/session
2022-04-18 01:43:41,235 [main ] INFO  Constant - Creating directory /home/aenagy1/.ZAP/dirbuster
2022-04-18 01:43:41,235 [main ] INFO  Constant - Creating directory /home/aenagy1/.ZAP/fuzzers
2022-04-18 01:43:41,235 [main ] INFO  Constant - Creating directory /home/aenagy1/.ZAP/plugin
2022-04-18 01:43:41,263 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 01:43:41 with home /home/aenagy1/.ZAP/
2022-04-18 01:43:41,294 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
2022-04-18 02:00:44,843 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 02:00:44 with home /home/aenagy1/.ZAP/
2022-04-18 02:00:44,873 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
2022-04-18 02:01:44,460 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 02:01:44 with home /home/aenagy1/.ZAP/
2022-04-18 02:01:44,491 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
2022-04-18 02:01:57,665 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 02:01:57 with home /home/aenagy1/.ZAP/
2022-04-18 02:01:57,694 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
2022-04-18 03:44:32,604 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 03:44:32 with home /home/aenagy1/.ZAP/
2022-04-18 03:44:32,657 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
2022-04-18 03:44:39,045 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 03:44:39 with home /home/aenagy1/.ZAP/
2022-04-18 03:44:39,074 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
2022-04-18 03:46:19,994 [main ] INFO  GuiBootstrap - OWASP ZAP 2.11.1 started 18/04/22 03:46:19 with home /home/aenagy1/.ZAP/
2022-04-18 03:46:20,025 [main ] ERROR UncaughtExceptionLogger - Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807) ~[?:1.8.0_312]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886) ~[?:1.8.0_312]
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736) ~[?:1.8.0_312]
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294) ~[?:1.8.0_312]
	at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:96) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.ZAP.main(ZAP.java:131) ~[zap-2.11.1.jar:2.11.1]
aenagy1@aenagy1-VirtualBox:~$
```

### Additional context

This works find in Kali Linux 2022.1

$ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1, mixed mode, sharing)

I have a requirement to run Java EE. The answer from '[Naman]' in this article explains better.

How to resolve java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception

This article talks about headless Java:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798794

... which I got from this article:

https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror

(1) What do I need to do to fix this?
(2) Is there something that can be put in the installer script to detect if you have the correct prerequisites?

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
Remove the headless jre you have installed and install a normal jre with gui support.

**Comment by thc202** [comment]
@aenagy did you try reinstall the JRE? We can't address this from within ZAP (nor from the installer, that one is maintained by a 3rd party), the most we can do is show a different error.

**Comment by aenagy** [comment]
It looks like I was able to solve the problem.


```
aenagy1@aenagy1-VirtualBox:~$ java -version # before fix
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

aenagy1@aenagy1-VirtualBox:~$ history | grep -i jdk # try to find my mistake
   61  sudo apt install openjdk-8-jre-headless
   62  sudo apt install -y openjdk-8-jre-headless
   74  sudo apt install -y openjdk-8-jre-headless
   75  sudo apt install -y openjdk-8-jdk-headless
  123  history | grep -i jdk

aenagy1@aenagy1-VirtualBox:~$ sudo apt remove -y openjdk-8-jdk-headless
[sudo] password for aenagy1: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libllvm11
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  openjdk-8-jdk-headless
0 upgraded, 0 newly installed, 1 to remove and 2 not upgraded.
After this operation, 39.7 MB disk space will be freed.
(Reading database ... 219366 files and directories currently installed.)
Removing openjdk-8-jdk-headless:amd64 (8u312-b07-0ubuntu1~20.04) ...

aenagy1@aenagy1-VirtualBox:~$ java -version # after undoing install of java headless
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

aenagy1@aenagy1-VirtualBox:~$ sudo apt install -y openjdk-8-jre #try again but without 'headless'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libllvm11
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  fonts-dejavu-extra libatk-wrapper-java libatk-wrapper-java-jni
Suggested packages:
  icedtea-8-plugin
The following NEW packages will be installed:
  fonts-dejavu-extra libatk-wrapper-java libatk-wrapper-java-jni openjdk-8-jre
0 upgraded, 4 newly installed, 0 to remove and 2 not upgraded.
Need to get 2,121 kB of archives.
After this operation, 7,932 kB of additional disk space will be used.
Get:1 http://ca.archive.ubuntu.com/ubuntu focal/main amd64 fonts-dejavu-extra all 2.37-1 [1,953 kB]
Get:2 http://ca.archive.ubuntu.com/ubuntu focal/main amd64 libatk-wrapper-java all 0.37.1-1 [53.0 kB]
Get:3 http://ca.archive.ubuntu.com/ubuntu focal/main amd64 libatk-wrapper-java-jni amd64 0.37.1-1 [45.1 kB]
Get:4 http://ca.archive.ubuntu.com/ubuntu focal-updates/universe amd64 openjdk-8-jre amd64 8u312-b07-0ubuntu1~20.04 [69.9 kB]
Fetched 2,121 kB in 1s (2,075 kB/s)     
Selecting previously unselected package fonts-dejavu-extra.
(Reading database ... 219258 files and directories currently installed.)
Preparing to unpack .../fonts-dejavu-extra_2.37-1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-1) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../libatk-wrapper-java_0.37.1-1_all.deb ...
Unpacking libatk-wrapper-java (0.37.1-1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../libatk-wrapper-java-jni_0.37.1-1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.37.1-1) ...
Selecting previously unselected package openjdk-8-jre:amd64.
Preparing to unpack .../openjdk-8-jre_8u312-b07-0ubuntu1~20.04_amd64.deb ...
Unpacking openjdk-8-jre:amd64 (8u312-b07-0ubuntu1~20.04) ...
Setting up fonts-dejavu-extra (2.37-1) ...
Setting up libatk-wrapper-java (0.37.1-1) ...
Setting up libatk-wrapper-java-jni:amd64 (0.37.1-1) ...
Setting up openjdk-8-jre:amd64 (8u312-b07-0ubuntu1~20.04) ...
update-alternatives: using /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/policytool to provide /usr/bin/policytool (policytool) 
in auto mode
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
Processing triggers for fontconfig (2.13.1-2ubuntu3) ...

aenagy1@aenagy1-VirtualBox:~$ zap.sh #ZAP now launches with GUI
```

As a suggestion it would be helpful if ZAP would detect that the current Java is headless and produce a clearer error message.

https://www.baeldung.com/java-headless-mode

Thanks for your suggestion.
