### ISSUE TITLE
Firefox tmp profile gets deleted during launch -> ff: Missing Profile -> zap: browser was not found

### ISSUE THREAD

**Issue by zesty** [zaproxy/zaproxy#7239]
### Describe the bug

fails to launch firefox (snap version on Ubuntu 22.04 LTS)

firefox /tmp/rust* profile gets created, but quickly deleted during startup (I was able to copy out the user.js file in a tight loop during launch)

ZAP_D-2022-04-20
ZAP_2.11.1

### Steps to reproduce the behavior

1. start zap using zap.sh
2. don't save session
3. click manual explore button
4. click launch browser with firefox selected

firefox dialog popup:
title: Missing Profile
warning: Your Firefox profile cannot be loaded. It may be missing or inaccessible.

zap dialog popup
title: OWASP ZAP
warning: The provided browser was not found.

### Expected behavior

firefox launched

### Software versions

(K)Ubuntu 22.04 LTS which uses firefox snap release
ZAP_D-2022-04-20
ZAP_2.11.1

### Additional context

```
1650841816248   geckodriver     INFO    Listening on 127.0.0.1:6405
1650841816408   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "-no-remote" "-profile" "/tmp/rust_mozprofilehZwiEY"

Gtk-Message: 16:10:16.959: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 16:10:16.959: Failed to load module "colorreload-gtk-module"

1151801 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch - Process unexpectedly closed with status 1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'darkstar', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-25-generic', java.version: '11.0.14.1'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'darkstar', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.15.0-25-generic', java.version: '11.0.14.1'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62) ~[?:?]
        at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30) ~[?:?]
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128) ~[?:?]
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) ~[?:?]
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[?:?]
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[?:?]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[?:?]
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[?:?]
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[?:?]
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1037) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:881) ~[?:?]
        at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:766) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:566) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:727) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:667) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:643) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:627) ~[?:?]
        at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:617) ~[?:?]
        at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:209) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### Would you like to help fix this issue?

- [x] Yes

**Comment by kingthorin** [comment]
> Please add version information from ZAPs menu Help > Support Info, or from the CLI using the -suppinfo switch

**Comment by zesty** [comment]
both weekly and stable:

```
% ./zap.sh -suppinfo 
Found Java version 11.0.14.1
Available memory: 32027 MB
Using JVM args: -Xmx8006m
OWASP ZAP
Version: D-2022-04-20
Installed Add-ons: [[id=accessControl, version=8.0.0], [id=alertFilters, version=14.0.0], [id=ascanrules, version=47.0.0], [id=ascanrulesBeta, version=41.0.0], [id=automation, version=0.15.0], [id=bruteforce, version=12.0.0], [id=callhome, version=0.4.0], [id=commonlib, version=1.10.0], [id=coreLang, version=16.0.0], [id=diff, version=12.0.0], [id=directorylistv1, version=6.0.0], [id=domxss, version=13.0.0], [id=encoder, version=0.7.0], [id=exim, version=0.2.0], [id=formhandler, version=5.0.0], [id=fuzz, version=13.7.0], [id=gettingStarted, version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql, version=0.10.0], [id=help, version=15.0.0], [id=hud, version=0.14.0], [id=invoke, version=12.0.0], [id=network, version=0.3.0], [id=oast, version=0.11.0], [id=onlineMenu, version=10.0.0], [id=openapi, version=28.0.0], [id=plugnhack, version=13.0.0], [id=portscan, version=10.0.0], [id=pscanrules, version=41.0.0], [id=pscanrulesBeta, version=30.0.0], [id=quickstart, version=34.0.0], [id=replacer, version=10.0.0], [id=reports, version=0.14.0], [id=retest, version=0.3.0], [id=retire, version=0.11.0], [id=reveal, version=5.0.0], [id=scripts, version=31.0.0], [id=selenium, version=15.9.0], [id=sequence, version=7.0.0], [id=soap, version=14.0.0], [id=spiderAjax, version=23.8.0], [id=tips, version=10.0.0], [id=webdriverlinux, version=38.0.0], [id=webdrivermacos, version=39.0.0], [id=webdriverwindows, version=38.0.0], [id=websocket, version=26.0.0], [id=zest, version=36.0.0]]
Operating System: Linux
Java Version: Ubuntu 11.0.14.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_GB
ZAP Home Directory: /home/leary/.ZAP_D/
ZAP Installation Directory: /home/leary/Downloads/ZAP_D-2022-04-20/./
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)
```

```
% ./zap.sh -suppinfo
Found Java version 11.0.14.1
Available memory: 32027 MB
Using JVM args: -Xmx8006m
OWASP ZAP
Version: 2.11.1
Installed Add-ons: [[id=alertFilters, version=13.0.0], [id=ascanrules, version=46.0.0], [id=automation, version=0.14.0], [id=bruteforce, version=11.0.0], [id=callhome, version=0.3.0], [id=commonlib, version=1.9.0], [id=diff, version=11.0.0], [id=directorylistv1, version=5.0.0], [id=domxss, version=12.0.0], [id=encoder, version=0.6.0], [id=exim, version=0.1.0], [id=formhandler, version=4.0.0], [id=fuzz, version=13.6.0], [id=gettingStarted, version=13.0.0], [id=graaljs, version=0.2.0], [id=graphql, version=0.9.0], [id=help, version=14.0.0], [id=hud, version=0.13.0], [id=importurls, version=9.0.0], [id=invoke, version=11.0.0], [id=network, version=0.2.0], [id=oast, version=0.10.0], [id=onlineMenu, version=9.0.0], [id=openapi, version=27.0.0], [id=pscanrules, version=40.0.0], [id=quickstart, version=33.0.0], [id=replacer, version=9.0.0], [id=reports, version=0.13.0], [id=retest, version=0.2.0], [id=retire, version=0.10.0], [id=reveal, version=4.0.0], [id=saverawmessage, version=7.0.0], [id=savexmlmessage, version=0.3.0], [id=scripts, version=30.0.0], [id=selenium, version=15.8.0], [id=soap, version=13.0.0], [id=spiderAjax, version=23.7.0], [id=tips, version=9.0.0], [id=webdriverlinux, version=37.0.0], [id=websocket, version=25.0.0], [id=zest, version=35.0.0]]
Operating System: Linux
Java Version: Ubuntu 11.0.14.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_GB
ZAP Home Directory: /home/leary/.ZAP/
ZAP Installation Directory: /home/leary/z/ZAP_2.11.1/./
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)
```

**Comment by kingthorin** [comment]
Thanks, that gets us webdriber, quickStart, etc version numbers 😉

I suspect it’s something specific to the snap’d Firefox that’s outside ZAP’s control but we’ll look into it.

**Comment by zesty** [comment]
Yep, confirmed no repro on regular flavor firefox. Fwiw, snap is the new default firefox for Ubuntu 22.04 LTS, so might be seeing more interest in this when the point release drops and everyone gets the update.

Workaround: manipulate PATH to put working firefox first and/or uninstall snap flavor of firefox

**Comment by zesty** [comment]
missing long-option dashes in command (doesn't affect regular firefox, just fyi):

`"/usr/bin/firefox" "--marionette" "-no-remote" "-profile" "/tmp/rust_mozprofilehZwiEY"`

```
% firefox --help | grep -P '(marion|no-remote|--profile)' 
  --profile <path>   Start with profile at <path>.
  --no-remote        Do not accept or send remote commands; implies
  --marionette       Enable remote control server.
```
