### ISSUE TITLE
Failed to generate report with Modern HTML template : Exception evaluating OGNL expression

### ISSUE THREAD

**Issue by s23hck** [zaproxy/zaproxy#7284]
### Describe the bug

Hi !
I have a bug when i generate a report via gui on zap v2.11.1 :
I made some manual testing via HUD and generate some report without any issue last days.
Today, that's my error trace:

`14058232 [AWT-EventQueue-0] ERROR org.zaproxy.addon.reports.ReportDialog - Failed to generate a report using template org.zaproxy.addon.reports.Template@1ef16e75
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "instance.userObject.message.requestHeader.toString.length" (template: "/home/s23/.ZAP/reports/modern/report.html" - line 464, col 13)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.MessageExpression.executeMessageExpression(MessageExpression.java:256) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:69) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:367) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:293) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:367) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:293) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1067) ~[reports-release-0.13.0.zap:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:433) ~[reports-release-0.13.0.zap:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:500) [reports-release-0.13.0.zap:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:427) [zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.view.StandardFieldsDialog.access$100(StandardFieldsDialog.java:83) [zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:410) [zap-2.11.1.jar:2.11.1]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) [?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) [?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) [?:?]
	at java.awt.Component.processEvent(Component.java:6400) [?:?]
	at java.awt.Container.processEvent(Container.java:2263) [?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) [?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) [?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2772) [?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: ognl.OgnlException: source is null for getProperty(null, "requestHeader")
	at ognl.OgnlRuntime.getProperty(OgnlRuntime.java:3229) ~[reports-release-0.13.0.zap:?]
	at ognl.ASTProperty.getValueBody(ASTProperty.java:114) ~[reports-release-0.13.0.zap:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[reports-release-0.13.0.zap:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[reports-release-0.13.0.zap:?]
	at ognl.ASTChain.getValueBody(ASTChain.java:141) ~[reports-release-0.13.0.zap:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[reports-release-0.13.0.zap:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[reports-release-0.13.0.zap:?]
	at ognl.Ognl.getValue(Ognl.java:537) ~[reports-release-0.13.0.zap:?]
	at ognl.Ognl.getValue(Ognl.java:501) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:328) ~[reports-release-0.13.0.zap:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170) ~[reports-release-0.13.0.zap:?]
`

Zaproxy version:
`zaproxy -version
Found Java version 11.0.14.1
Available memory: 6752 MB
Using JVM args: -Xmx1688m
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
2.11.1
`

OS:
`Linux kali 5.16.0-kali7-amd64 #1 SMP PREEMPT Debian 5.16.18-1kali1 (2022-04-01) x86_64 GNU/Linux`

Have you got any recommendation to avoid this issue ?

Cheers

### Steps to reproduce the behavior

1. Insatll zaproxy on latest kali linux stable with xfce
2. Run zaproxy, type in terminal : > zaproxy
3. Run manual testing with HUD / Firefox
4. Navigate in app
5. Attack
6. Generate report

### Expected behavior

Generate report with Modern HTML Report template

### Software versions

OWASP ZAP
Version: 2.11.1
---
Installed Add-ons: [[id=alertFilters, version=13.0.0],
[id=ascanrules, version=46.0.0], [id=automation,
version=0.15.0], [id=bruteforce, version=11.0.0],
[id=callhome, version=0.3.0], [id=commonlib, version=1.9.0],
[id=diff, version=11.0.0], [id=directorylistv1,
version=5.0.0], [id=domxss, version=12.0.0], [id=encoder,
version=0.6.0], [id=exim, version=0.1.0], [id=formhandler,
version=4.0.0], [id=fuzz, version=13.6.0],
[id=gettingStarted, version=13.0.0], [id=graaljs,
version=0.2.0], [id=graphql, version=0.9.0], [id=help,
version=14.0.0], [id=hud, version=0.13.0], [id=importurls,
version=9.0.0], [id=invoke, version=11.0.0], [id=network,
version=0.2.0], [id=oast, version=0.10.0], [id=onlineMenu,
version=9.0.0], [id=openapi, version=27.0.0],
[id=pscanrules, version=40.0.0], [id=quickstart,
version=33.0.0], [id=replacer, version=9.0.0], [id=reports,
version=0.13.0], [id=retest, version=0.2.0], [id=retire,
version=0.11.0], [id=reveal, version=4.0.0],
[id=saverawmessage, version=7.0.0], [id=savexmlmessage,
version=0.3.0], [id=scripts, version=30.0.0], [id=selenium,
version=15.9.0], [id=soap, version=13.0.0], [id=spiderAjax,
version=23.7.0], [id=tips, version=9.0.0],
[id=webdriverlinux, version=38.0.0], [id=websocket,
version=25.0.0], [id=zest, version=35.0.0]]
---
Operating System: Linux
Java Version: Debian 11.0.14.1
System''s Locale: fr_FR
Display Locale: fr_FR
Format Locale: fr_FR
ZAP Home Directory: /home/s23/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Screenshots

![image](https://user-images.githubusercontent.com/51639079/168099853-3c5176d7-28c6-4c31-80d5-219253ddff08.png)

### Errors from the zap.log file

[zap.log](https://github.com/zaproxy/zaproxy/files/8680046/zap.log)

### Additional context

ZAp was installed from 

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
This seems to be a duplicate of: zaproxy/zaproxy#6880

I'll add the content over there.
