### ISSUE TITLE
pscan could be less chatty/loggy

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#7352]
I deleted a bunch of stuff from the Sites Tree while there was still a passive scan queue. 

1. The passive scanner probably doesn't need to log the full trace on these.
2. Could the queue be modified when things are deleted from the Sites Tree?

Versions:
Java: 11.0.13
ZAP: Dev

```console
68347 [ZAP-PassiveScan-4] ERROR org.zaproxy.zap.extension.pscan.PassiveScanTask - Parser failed on record 387 from History table
org.parosproxy.paros.network.HttpMalformedHeaderException: No history reference for id 387 type=2
	at org.parosproxy.paros.model.HistoryReference.getHttpMessage(HistoryReference.java:454) ~[main/:?]
	at org.zaproxy.zap.extension.pscan.PassiveScanTask.run(PassiveScanTask.java:101) ~[main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
68348 [ZAP-PassiveScan-1] ERROR org.zaproxy.zap.extension.pscan.PassiveScanTask - Parser failed on record 388 from History table
org.parosproxy.paros.network.HttpMalformedHeaderException: No history reference for id 388 type=2
	at org.parosproxy.paros.model.HistoryReference.getHttpMessage(HistoryReference.java:454) ~[main/:?]
	at org.zaproxy.zap.extension.pscan.PassiveScanTask.run(PassiveScanTask.java:101) ~[main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
68348 [ZAP-PassiveScan-4] ERROR org.zaproxy.zap.extension.pscan.PassiveScanTask - Parser failed on record 389 from History table
org.parosproxy.paros.network.HttpMalformedHeaderException: No history reference for id 389 type=2
	at org.parosproxy.paros.model.HistoryReference.getHttpMessage(HistoryReference.java:454) ~[main/:?]
	at org.zaproxy.zap.extension.pscan.PassiveScanTask.run(PassiveScanTask.java:101) ~[main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
68348 [ZAP-PassiveScan-1] ERROR org.zaproxy.zap.extension.pscan.PassiveScanTask - Parser failed on record 390 from History table
org.parosproxy.paros.network.HttpMalformedHeaderException: No history reference for id 390 type=2
	at org.parosproxy.paros.model.HistoryReference.getHttpMessage(HistoryReference.java:454) ~[main/:?]
	at org.zaproxy.zap.extension.pscan.PassiveScanTask.run(PassiveScanTask.java:101) ~[main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by kingthorin** [comment]
I can address no.1. Not sure I can address no.2 or if it's even practical.

**Comment by psiinon** [comment]
1. is a good start :)

**Comment by thc202** [comment]
The passive scanner does not have a queue as such, it's just a counter for the history ID.

IMO it could just log as debug. If the user deleted the message it's safe to assume that the message will no longer be scanned.
