### ISSUE TITLE
SSE URL column size is small

### ISSUE THREAD

**Issue by stasha** [zaproxy/zaproxy#7354]
### Describe the bug

In SSE plugin, URL column is 255 char long, but it's not enough in some cases.

### Steps to reproduce the behavior

Example:
`https://my.domain.withsomesuperlargesubdomain.and.additional.subdomain/somecool/context/event/?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.2-javascript&X-Atmosphere-Transport=sse&X-Atmosphere-TrackMessageSize=true&Content-Type=application%2Fjson&X-atmo-protocol=true`

### Expected behavior

URLs larger than 255 characters should also work

### Software versions

Latest from source.

### Errors from the zap.log file
```
2022-06-22 10:12:42,190 [ZAP-IO-EventExecutor-3-4] ERROR EventStreamStorage - java.sql.SQLDataException: data exception: string data, right truncation;  table: EVENT_STREAM column: URL
org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: data exception: string data, right truncation;  table: EVENT_STREAM column: URL
	at org.zaproxy.zap.extension.sse.db.TableEventStream.insertOrUpdateStream(TableEventStream.java:530) ~[?:?]
	at org.zaproxy.zap.extension.sse.db.EventStreamStorage.onServerSentEventStateChange(EventStreamStorage.java:69) ~[?:?]
	at org.zaproxy.zap.extension.sse.EventStreamProxy.notifyStateObservers(EventStreamProxy.java:240) ~[?:?]
	at org.zaproxy.zap.extension.sse.EventStreamProxy.start(EventStreamProxy.java:101) ~[?:?]
	at org.zaproxy.zap.extension.sse.ExtensionServerSentEvents.addEventStream(ExtensionServerSentEvents.java:211) ~[?:?]
	at org.zaproxy.zap.extension.sse.ExtensionServerSentEvents.onHandshakeResponse(ExtensionServerSentEvents.java:240) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.LegacyProxyListenerHandler.lambda$notifyPersistentConnectionListener$6(LegacyProxyListenerHandler.java:204) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.LegacyProxyListenerHandler.handleErrors(LegacyProxyListenerHandler.java:184) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.LegacyProxyListenerHandler.notifyPersistentConnectionListener(LegacyProxyListenerHandler.java:203) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainProxyHandler.postWriteResponse(MainProxyHandler.java:72) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:90) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:72) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.channelRead0(MainServerHandler.java:37) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) ~[?:?]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_202]
Caused by: java.sql.SQLDataException: data exception: string data, right truncation;  table: EVENT_STREAM column: URL
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.5.2.jar:2.5.2]
	at org.zaproxy.zap.extension.sse.db.TableEventStream.insertOrUpdateStream(TableEventStream.java:509) ~[?:?]
	... 21 more
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
@stasha the code in question is here: https://github.com/zaproxy/zap-extensions/blob/main/addOns/sse/src/main/java/org/zaproxy/zap/extension/sse/db/TableEventStream.java

There's info on setting up a development environment, etc. here: https://www.zaproxy.org/docs/developer/
