### ISSUE TITLE
ERROR org.zaproxy.addon.callhome.ExtensionCallHome - Expected '200 OK' but got '403 Forbidden'

### ISSUE THREAD

**Issue by Damuammu** [zaproxy/zaproxy#7387]
### Describe the bug

ERROR org.zaproxy.addon.callhome.ExtensionCallHome - Expected '200 OK' but got '403 Forbidden'
java.io.IOException: Expected '200 OK' but got '403 Forbidden'
        at org.zaproxy.addon.callhome.ExtensionCallHome.sendServiceRequest(ExtensionCallHome.java:230) ~[?:?]
        at org.zaproxy.addon.callhome.ExtensionCallHome.lambda$uploadTelemetryStartData$5(ExtensionCallHome.java:351) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

### Steps to reproduce the behavior

open ZAP and add url in automated scan or try to browse url on firefox getting same excpetion

### Expected behavior

zap should run without any errors.

### Software versions

2.11.1

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
If you have an outgoing proxy configured in ZAP ensure that the details are correct.

Questions like this are better for the OWASP ZAP User Group: https://groups.google.com/group/zaproxy-users

**Comment by Damuammu** [comment]
i have configured proxy in both zap and browser 
ip: 127.0.0.1
port: 8080

any thing mising
