### ISSUE TITLE
ZAP Error [java.net.ConnectException]: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by Martinez1991** [zaproxy/zaproxy#7442]
### Describe the bug

Describe the bug
I can't use zaproxy docker installation behind a reverse proxy (nginx)

Both servers are in Docker

Zaproxy configuration

```
version: '3.8'
services:
  zap:
    build:
      context: .
      dockerfile: Dockerfile-stable
    container_name: zaproxy
    restart: always
    user: zap
    ports:
            - "8090:8090"
    command: zap.sh -daemon -host 0.0.0.0 -port 8090 -config api.key=XXXXXXXXXXX -config connection.timeoutInSecs=120 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

networks:
  default:
     name: nginx_default
     external: true
```

nginx configuration
```
http {

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile on;

    upstream zaproxy {
        server zaproxy:8090;
    }

    upstream app2 {
        server app2:8443;
    }

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;

    server {
        listen 80;
        server_tokens off;
        location / {
            return 301 https://$host$request_uri;
        }
    }

  
    server {
        listen 80;
        server_tokens off;
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_tokens off;
        server_name xxxx.com;
        ssl_certificate /etc/nginx/ssl/xxxx.com.crt;
        ssl_certificate_key /etc/nginx/ssl/xxxx.com.key;
        ssl_session_cache builtin:1000 shared:SSL:10m;
        # ciphers from https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.4
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256;
        ssl_prefer_server_ciphers off;

        location / {
            proxy_buffering off;
            add_header X-Upstream $upstream_addr;
            proxy_pass http://zaproxy;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
        }
    }
```

### Steps to reproduce the behavior

docker-compose up

docker-compose.yml

### Expected behavior

I hope Zaproxy works norm

### Software versions

Dockerfile-stable

### Screenshots
```
ZAP Error [java.net.ConnectException]: Connection refused (Connection refused)


Stack Trace:
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:210)
	at java.base/sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:153)
	at org.parosproxy.paros.network.DecoratedSocketsSslSocketFactory.createSocket(DecoratedSocketsSslSocketFactory.java:99)
	at org.parosproxy.paros.network.SSLConnector.createSocket(SSLConnector.java:437)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:728)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:457)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:207)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.parosproxy.paros.network.HttpSender.executeMethod(HttpSender.java:430)
	at org.parosproxy.paros.network.HttpSender.runMethod(HttpSender.java:672)
	at org.parosproxy.paros.network.HttpSender.send(HttpSender.java:627)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:602)
	at org.parosproxy.paros.network.HttpSender.sendAuthenticated(HttpSender.java:585)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:490)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:460)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(ProxyThread.java:562)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(ProxyThread.java:333)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
This is not a ZAP issue, OWASP ZAP User Group is a better place to resolve these questions: https://groups.google.com/group/zaproxy-users

You should provide more details of what is being done.
