### ISSUE TITLE
Failed to generate report: Exception evaluating OGNL expression.

### ISSUE THREAD

**Issue by spothound** [zaproxy/zaproxy#7540]
### Describe the bug

I am getting started with zaproxy. I have run an instance of the OWASP juice shop on a docker container and then run a Zap active scan against it, finding 23 alerts.

I wanted to generate a report to see what it looks like, but when I try to do so, I get the following error:

### Steps to reproduce the behavior

1. `docker run --rm -p 3000:3000 bkimminich/juice-shop`
2. Open zaproxy 2.11.1 and run an active scan against the localhost port associated with juice-shop (default 3000)
3. Wait for the scan to end, you should now see about 20 alers
![image](https://user-images.githubusercontent.com/15269938/197627519-c3d6bcd5-cd01-4b6e-a513-c4ff5787e7e0.png)
4. Click on Report>Generate Report and then in Generate report
5. An error appears, and an incomplete HTML report is generated.

### Expected behavior

The report should be correctly generated!

### Software versions

2.11.1

### Screenshots

![image](https://user-images.githubusercontent.com/15269938/197628035-d6b3692c-bb8f-4a3b-a545-f20dd89dd029.png)
![image](https://user-images.githubusercontent.com/15269938/197628326-cf5f60b0-1293-4def-8c7f-a8dda24067b8.png)

### Errors from the zap.log file

```
187848 [AWT-EventQueue-0] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][AWT-EventQueue-0] Exception processing template "/home/grg121/.ZAP/reports/risk-confidence-html/report.html": Exception evaluating OGNL expression: "alertTree.children.hasMoreElements()? alertTree.depthFirstEnumeration().{? #this.isLeaf()}: {}" (template: "/home/grg121/.ZAP/reports/risk-confidence-html/report.html" - line 32, col 3)
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "alertTree.children.hasMoreElements()? alertTree.depthFirstEnumeration().{? #this.isLeaf()}: {}" (template: "/home/grg121/.ZAP/reports/risk-confidence-html/report.html" - line 32, col 3)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:191) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:95) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[?:?]
	at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[?:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[?:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[?:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[?:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[?:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1067) ~[?:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:429) ~[?:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:500) ~[?:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:427) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.view.StandardFieldsDialog.access$100(StandardFieldsDialog.java:83) ~[zap-2.11.1.jar:2.11.1]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:410) ~[zap-2.11.1.jar:2.11.1]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6620) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3398) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6385) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4995) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4827) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4827) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Vector$1.hasMoreElements() accessible: module java.base does not "opens java.util" to unnamed module @451d2c53
	at java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:201) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:195) ~[?:?]
	at ognl.AccessibleObjectHandlerPreJDK9.setAccessible(AccessibleObjectHandlerPreJDK9.java:58) ~[?:?]
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:1192) ~[?:?]
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1920) ~[?:?]
	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68) ~[?:?]
	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1996) ~[?:?]
	at ognl.ASTMethod.getValueBody(ASTMethod.java:91) ~[?:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[?:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[?:?]
	at ognl.ASTChain.getValueBody(ASTChain.java:141) ~[?:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[?:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[?:?]
	at ognl.ASTTest.getValueBody(ASTTest.java:51) ~[?:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[?:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[?:?]
	at ognl.Ognl.getValue(Ognl.java:537) ~[?:?]
	at ognl.Ognl.getValue(Ognl.java:501) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:328) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:170) ~[?:?]
	... 56 more
```

### Additional context

I would like to help to solve this issue with a little bit of guidance : ) 

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Merging into #6880.

**Comment by spothound** [comment]
Oh, sorry I didn't show that one, thanks!
