### ISSUE TITLE
Outgoing proxy connection done with TLS for HTTPS requests

### ISSUE THREAD

**Issue by mino-txa** [zaproxy/zaproxy#7594]
### Describe the bug

Please forgive my poor English.

I am working in an environment where I connect to the internet via a proxy server.
I want to check for zap and addon updates, but an error occurs.

I was able to update it in 2.11.
I can no longer do this with 2.12.

I have already set up a proxy server as follows
　Tool -> option -> Network -> Connection -> HTTP Proxy

Checking the ZAP logs, the cause is that the proxy server is being accessed via https.
The Proxy server only supports http.

How can I configure it for http access?

### Steps to reproduce the behavior

1. Setting HTTP Proxy
Tool -> option -> Network -> Connection ->　HTTP Proxy
2. Open add-on menu
3. Check Update
Error occurred
4. Check log
[ZAP-telemetry-start] ERROR ExtensionCallHome - Connect to https://XXXXXXXXXXXXXXXX [XXXXXXXXXXX/XXXXXXXXXXX] failed: Read timed out
org.zaproxy.addon.network.common.ZapSocketTimeoutException: Connect to https://XXXXXXXXXXXXXXXX [XXXXXXXXXXX/XXXXXXXXXXX] failed: Read timed out

### Expected behavior

1. Setting HTTP Proxy
Tool -> option -> Network -> Connection ->　HTTP Proxy
2. Open add-on menu
I can update it.

### Software versions

2.12.0
I was able to update it in 2.11.

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Does the proxy accept CONNECT requests?

**Comment by mino-txa** [comment]
Not accessible at https://<proxy_ip>:<proxy_port>.

Must be http://<proxy_ip>:<proxy_port>.
Web browsers can access Internet through proxies.

**Comment by mino-txa** [comment]
It would be nice if zap could access the Proxy used to update the addon at http://<proxy_ip>:<proxy_port>.
Did you change the specifications in this area in v2.12.0?

**Comment by thc202** [comment]
The scheme of the error message is misleading, ZAP is connecting to the provided address/hostname and port. Are the values correct? Is ZAP able to access that proxy?

If something changed it was not intentional, ZAP is able to connect to HTTP proxies.

**Comment by mino-txa** [comment]
I am doing the following, but do I need to take any other action?

* I can start a command prompt and use the ping command to check the response from the proxy server.
* I can start chrome browser and connect to the internet through the proxy server.
* I add a zscaler certificate for java11 running zap.
* A proxy server is specified with zap.
Tool -> option -> Network -> Connection -> HTTP Proxy
* The zap log records the IP and port of the configured proxy.

**Comment by mino-txa** [comment]
The stack traces are as follows
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:300) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:103) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:298) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:266) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:222) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:193) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:57) ~[?:?]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:478) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.addon.callhome.ExtensionCallHome.sendServiceRequest(ExtensionCallHome.java:211) ~[?:?]
	at org.zaproxy.addon.callhome.ExtensionCallHome.lambda$uploadTelemetryStartData$5(ExtensionCallHome.java:339) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
[ZAP-cfu] DEBUG ExtensionAutoUpdate - Calling callback with null
[ZAP-cfu] DEBUG ExtensionAutoUpdate - Done

**Comment by thc202** [comment]
Enable debug logging for `org.apache.hc` and attach zap.log file (replace sensitive information as needed). https://www.zaproxy.org/faq/how-do-you-configure-zap-logging/

**Comment by thc202** [comment]
The log is no longer necessary I can reproduce the issue, for the record, the error message was not misleading it was correct, the connection to the proxy was using the wrong scheme when the request was HTTPS.
