### ISSUE TITLE
Error in spider

### ISSUE THREAD

**Issue by andresghelarducci** [zaproxy/zaproxy#7625]
### Describe the bug

Hi, 
when I try to run from zap UI a spider scan I got an error:
ZAP-SpiderThreadPool-1-thread-1] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while parsing:
com.fasterxml.jackson.core.JsonParseException: Duplicate field 'dataType'
 at [Source: (String)"{"dataType":"BOOLEAN","dataType":"BOOLEAN","id":"policy.external","description":"aimPortalWebApp.webapiSystemOption.policy_external","hidden":false,"nullable":false,"stringValue":"false","value":false,"defaultValue":null}"; line: 1, column: 33]
        at com.fasterxml.jackson.core.json.JsonReadContext._checkDup(JsonReadContext.java:225) ~[?:?]
        at com.fasterxml.jackson.core.json.JsonReadContext.setCurrentName(JsonReadContext.java:219) ~[?:?]
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:963) ~[?:?]
        at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:440) ~[?:?]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:84) ~[?:?]
        at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:20) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4716) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076) ~[?:?]
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:167) ~[?:?]
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:104) ~[?:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOpenAPI(SwaggerConverter.java:253) ~[?:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:202) ~[?:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOperationModels(SwaggerConverter.java:183) ~[?:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:190) ~[?:?]
        at org.zaproxy.zap.extension.openapi.spider.OpenApiSpider.parseResource(OpenApiSpider.java:60) ~[?:?]
        at org.zaproxy.addon.spider.SpiderTask.processResource(SpiderTask.java:374) ~[?:?]
        at org.zaproxy.addon.spider.SpiderTask.runImpl(SpiderTask.java:224) ~[?:?]
        at org.zaproxy.addon.spider.SpiderTask.run(SpiderTask.java:142) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]

### Steps to reproduce the behavior

1. Go to Context
2. Right click "Spider"
3. Select user and press ok
4. Spider is stopped with error

### Expected behavior

spider shall crawl the context URLs

### Software versions

ZAP 2.12.0 on Windows

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
That's a warning not an error, the spider will continue spidering.
