### ISSUE TITLE
Consider shipping the Linux aarch64 gecko webdriver with the Crossplatform package

### ISSUE THREAD

**Issue by tkisason** [zaproxy/zaproxy#7650]
### Describe the bug

If we try to run OWASP ZAP in an arm64 / aarch64 Linux based OS (eg, kali in vmware fusion on a m1 macbook) the "open preconfigured browser" feature won't work, with the below stated errors.

The reason why this happens is that ZAP fails as there is no aarch64 linux geckodriver shipped by default. The solution for this is to:

1. Go to the following URL: https://github.com/mozilla/geckodriver/releases
2. Download and extract the latest aarch64 geckodriver
3. Go to Tools -> Options -> Selenium, and select the newly extracted aarch64 geckodriver instead of the default x64 one. 

After that, Firefox pops up and works without issues. 

Can we consider shipping an aarch64 geckodriver by default in future Linux / Crossplatform packages?

### Steps to reproduce the behavior

1.  Click on the "Open browser pre-configured to proxy through ZAP" button on the toolbar.
2. ZAP will return the message saying "The provided browser was not found".
3. Nothing happens. (Zap log does show a failure)

### Expected behavior

An autoconfigured Firefox instance should pop-up and proxy everything through ZAP. 

### Software versions

ZAP_2.12.0_Crossplatform.zip

```
OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=14.0.0],
[id=ascanrules, version=49.0.0], [id=automation,
version=0.19.0], [id=bruteforce, version=12.0.0],
[id=callhome, version=0.5.0], [id=commonlib,
version=1.11.0], [id=database, version=0.1.0], [id=diff,
version=12.0.0], [id=directorylistv1, version=5.0.0],
[id=domxss, version=14.0.0], [id=encoder, version=0.7.0],
[id=exim, version=0.3.0], [id=formhandler, version=6.1.0],
[id=fuzz, version=13.8.0], [id=gettingStarted,
version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql,
version=0.11.0], [id=help, version=15.0.0], [id=hud,
version=0.15.0], [id=invoke, version=12.0.0], [id=network,
version=0.3.0], [id=oast, version=0.13.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=29.0.0],
[id=pscanrules, version=44.0.0], [id=quickstart,
version=35.0.0], [id=replacer, version=11.0.0], [id=reports,
version=0.16.0], [id=requester, version=7.0.0], [id=retest,
version=0.4.0], [id=retire, version=0.16.0], [id=reveal,
version=5.0.0], [id=scripts, version=33.0.0], [id=selenium,
version=15.11.0], [id=soap, version=15.0.0], [id=spider,
version=0.1.0], [id=spiderAjax, version=23.10.0], [id=tips,
version=10.0.0], [id=webdriverlinux, version=46.0.0],
[id=webdrivermacos, version=47.0.0], [id=webdriverwindows,
version=46.0.0], [id=websocket, version=27.0.0], [id=zest,
version=37.0.0]]

Operating System: Linux
Architecture: aarch64
Java Version: Debian 17.0.5
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/user/.ZAP/
ZAP Installation Directory: /home/user/Downloads/ZAP_2.12.0/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

```

### Errors from the zap.log file

```
/home/user/.ZAP/webdriver/linux/32/geckodriver: 1: Syntax error: word unexpected (expecting ")")
506437 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch - The driver server has unexpectedly died!
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vm', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'aarch64', os.version: '6.0.0-kali5-arm64', java.version: '17.0.5'
Driver info: driver.version: FirefoxDriver
org.openqa.selenium.WebDriverException: The driver server has unexpectedly died!
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'vm', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'aarch64', os.version: '6.0.0-kali5-arm64', java.version: '17.0.5'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:89) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1052) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:896) ~[?:?]
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:773) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:573) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:734) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:674) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:650) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:634) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:624) ~[?:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:214) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:6181
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247) ~[?:?]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165) ~[?:?]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[?:?]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[?:?]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[?:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[?:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[?:?]
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) ~[?:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[?:?]
	... 16 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129) ~[?:?]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245) ~[?:?]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165) ~[?:?]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) ~[?:?]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) ~[?:?]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) ~[?:?]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[?:?]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[?:?]
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) ~[?:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[?:?]
	... 16 more

```

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Updated the title to make it clear it's for Linux.

**Comment by jkuehnemundt** [comment]
I can confirm that @tkisason solution works.

**Comment by str-append** [comment]
Thank you so much.... Finally it worked!!!!!
