### ISSUE TITLE
Ruby (Jruby)-based script does not work

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#7657]
### Describe the bug

Ruby (Jruby)-based script does not work. The script loads normally, but does not work at runtime, and checking zap.log results in an initialization-related error. (`Could not initialize class org.jruby.RubyInstanceConfig`)

I try re-installed addon and the same problem is occurring with various devices. Is there any way I can solve it?

## Test script
```
# Test - Stand Alone
puts 'a'
```

and template scripts (`Split download extract.rb`, etc...)

## zap.log
```
ERROR UncaughtExceptionLogger - Exception in thread "ZAP-ScriptExecutor-Test"
java.lang.NoClassDefFoundError: Could not initialize class org.jruby.RubyInstanceConfig
	at org.jruby.embed.internal.AbstractLocalContextProvider.<init>(AbstractLocalContextProvider.java:42) ~[?:?]
	at org.jruby.embed.internal.SingletonLocalContextProvider.<init>(SingletonLocalContextProvider.java:88) ~[?:?]
	at org.jruby.embed.ScriptingContainer.getProviderInstance(ScriptingContainer.java:246) ~[?:?]
	at org.jruby.embed.ScriptingContainer.<init>(ScriptingContainer.java:226) ~[?:?]
	at org.jruby.embed.jsr223.JRubyEngineFactory.getScriptEngine(JRubyEngineFactory.java:170) ~[?:?]
	at org.zaproxy.zap.extension.script.ScriptEngineWrapper.getEngine(ScriptEngineWrapper.java:63) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.script.ExtensionScript.invokeScriptImpl(ExtensionScript.java:1479) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.script.ExtensionScript.invokeScript(ExtensionScript.java:1427) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.scripts.ConsolePanel$ScriptExecutorThread.run(ConsolePanel.java:592) ~[?:?]
```

### Steps to reproduce the behavior

1. Open Scripts and Script Console
2. Run any Ruby script
3. The code is not executed and an error is logged in the zap.log.

### Expected behavior

Run script

### Software versions

ZAP: ZAP 2.12.0
OS: Ventura 13.0.1 (intel and M1)
Ruby Scripting Addon: 8.0.0

```
OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=accessControl, version=8.0.0],
[id=alertFilters, version=14.0.0], [id=allinonenotes,
version=2.0.0], [id=amf, version=3.0.0], [id=ascanrules,
version=50.0.0], [id=ascanrulesAlpha, version=42.0.0],
[id=ascanrulesBeta, version=44.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authstats,
version=2.0.0], [id=automation, version=0.20.0],
[id=browserView, version=5.0.0], [id=bruteforce,
version=12.0.0], [id=callgraph, version=5.0.0],
[id=callhome, version=0.6.0], [id=commonlib,
version=1.12.0], [id=custompayloads, version=0.12.0],
[id=database, version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=14.0.0], [id=encoder, version=1.0.0],
[id=evalvillain, version=0.1.1], [id=exim, version=0.3.0],
[id=fileupload, version=1.1.0], [id=formhandler,
version=6.1.0], [id=fuzz, version=13.8.0], [id=fuzzdb,
version=9.0.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.12.0],
[id=groovy, version=3.1.0], [id=help, version=15.0.0],
[id=highlighter, version=8.0.0], [id=hud, version=0.15.0],
[id=imagelocationscanner, version=4.0.0], [id=importurls,
version=9.0.0], [id=invoke, version=12.0.0], [id=jruby,
version=8.0.0], [id=jsonview, version=2.0.0], [id=jwt,
version=1.0.2], [id=jython, version=12.0.0], [id=kotlin,
version=1.1.0], [id=neonmarker, version=1.5.0], [id=network,
version=0.5.0], [id=oast, version=0.14.0], [id=onlineMenu,
version=10.0.0], [id=openapi, version=30.0.0],
[id=plugnhack, version=13.0.0], [id=portscan,
version=10.0.0], [id=pscanrules, version=44.0.0],
[id=pscanrulesAlpha, version=37.0.0], [id=pscanrulesBeta,
version=31.0.0], [id=quickstart, version=35.0.0],
[id=reflect, version=0.0.11], [id=regextester,
version=2.0.0], [id=replacer, version=11.0.0], [id=reports,
version=0.17.0], [id=requester, version=7.0.0], [id=retest,
version=0.4.0], [id=retire, version=0.18.0], [id=reveal,
version=5.0.0], [id=revisit, version=4.0.0], [id=saml,
version=10.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scriptgen,
version=5.0.0], [id=scripts, version=33.0.0], [id=selenium,
version=15.11.0], [id=sequence, version=6.0.0], [id=soap,
version=16.0.0], [id=spider, version=0.1.0], [id=spiderAjax,
version=23.10.0], [id=sqliplugin, version=15.0.0], [id=sse,
version=12.0.0], [id=tips, version=10.0.0], [id=tokengen,
version=15.0.0], [id=treetools, version=8.0.0],
[id=viewstate, version=3.0.0], [id=wappalyzer,
version=21.17.0], [id=webdrivermacos, version=48.0.0],
[id=websocket, version=27.0.0], [id=zest, version=37.0.0]]

Operating System: Mac OS X
Architecture: x86_64
Java Version: Eclipse Adoptium 11.0.16.1
System's Locale: ko_KR
Display Locale: en_GB
Format Locale: ko_KR
Default Charset: UTF-8
ZAP Home Directory: /Users/hahwul/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Darcula (com.formdev.flatlaf.FlatDarculaLaf)
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
The root cause:
```
Caused by: java.lang.RuntimeException: unsupported Java version: 11
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1693) ~[?:?]
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1398) ~[?:?]
	... 9 more
```

Merging into #3944.
