### ISSUE TITLE
Issue with HttpSenderApache -  AuthScheme is null

### ISSUE THREAD

**Issue by cristoji88** [zaproxy/zaproxy#7685]
### Describe the bug

Hi, I just upgraded ZAP to v2.12 and started to get this error whenever I log in to my application with Zap proxy enabled.

My application is using NTLM authentication and HTTP-based authentication session Management, right after I enter my valid credentials I get the following error.

![image](https://user-images.githubusercontent.com/98680130/211827718-95150ab2-02ad-4eee-b0dc-65668eb8cc0f.png)

### Steps to reproduce the behavior

Enable ZAP proxy and Windows proxy configuration.
Go to the application URL
Enter application credentials
The error shows up on the browser response and log file.

### Expected behavior

I should be able to login to my application with ZAP proxy enabled

### Software versions

OWASP ZAP 2.12.0

### Errors from the zap.log file

2023-01-11 05:30:29,712 [ZAP-IO-Server-1-4] WARN  HttpSenderApache - An error occurred while sending the request:
java.lang.IllegalStateException: AuthScheme is null
	at org.apache.hc.core5.util.Asserts.notNull(Asserts.java:56) ~[?:?]
	at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.updateAuthState(HttpAuthenticator.java:216) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.needAuthentication(ZapProtocolExec.java:276) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:188) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:158) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:363) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:331) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:287) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:258) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:63) ~[?:?]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:303) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:147) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:129) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:66) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Are the add-ons up-to-date?

**Comment by thc202** [comment]
Similar to #7566.

**Comment by cristoji88** [comment]
All add-ons are updated.
Right now I'm not configuring any authentication within Zap, just entering my application credentials manually

**Comment by thc202** [comment]
Thank you.

**Comment by catn0b0t** [comment]
Having the same situation here. "AuthScheme is null" when trying to login with NTLM over the proxy. Are there any intermediate fixes that we can try until a final resolution is found?

**Comment by thc202** [comment]
I don't think there is but will check.

**Comment by thc202** [comment]
@catn0b0t could you provide the information in Help > Support Info... and the exception's stack trace you are seeing?

**Comment by pavelsukhahevvolo** [comment]
I have the same problem, there is the Support Info:
`OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=15.0.0],
[id=ascanrules, version=55.0.0], [id=authhelper,
version=0.8.0], [id=automation, version=0.29.0],
[id=bruteforce, version=13.0.0], [id=callhome,
version=0.6.0], [id=commonlib, version=1.14.0],
[id=custompayloads, version=0.12.0], [id=database,
version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=15.0.0], [id=encoder, version=1.1.0], [id=exim,
version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz,
version=13.9.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.16.0],
[id=help, version=15.0.0], [id=hud, version=0.16.0],
[id=invoke, version=12.0.0], [id=network, version=0.9.0],
[id=oast, version=0.15.0], [id=onlineMenu, version=10.0.0],
[id=openapi, version=33.0.0], [id=pscanrules,
version=49.0.0], [id=quickstart, version=37.0.0],
[id=replacer, version=12.0.0], [id=reports, version=0.21.0],
[id=requester, version=7.2.0], [id=retest, version=0.5.0],
[id=retire, version=0.23.0], [id=reveal, version=5.0.0],
[id=scripts, version=38.0.0], [id=selenium,
version=15.12.1], [id=soap, version=17.0.0], [id=spider,
version=0.4.0], [id=spiderAjax, version=23.14.1], [id=tips,
version=10.0.0], [id=webdrivermacos, version=56.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Mac OS X
Architecture: x86_64
Java Version: Eclipse Adoptium 11.0.16.1
System's Locale: uk_UA
Display Locale: uk_UA
Format Locale: uk_UA
Default Charset: UTF-8
ZAP Home Directory: /Users/.../Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/OWASP ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
`

**Comment by thc202** [comment]
Could you also provide the whole exception stacktrace?

**Comment by pavelsukhahevvolo** [comment]
Sure:
`ZAP Error [java.io.IOException]: java.lang.IllegalStateException: AuthScheme is null


Stack Trace:
java.lang.IllegalStateException: AuthScheme is null
	at org.apache.hc.core5.util.Asserts.notNull(Asserts.java:56)
	at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.updateAuthState(HttpAuthenticator.java:216)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.needAuthentication(ZapProtocolExec.java:276)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
 [wrapped] java.io.IOException: java.lang.IllegalStateException: AuthScheme is null
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:374)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:363)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:331)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:287)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:258)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:63)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:303)
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131)
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)`
And I also get such error on the Win env:
`OWASP ZAP
Version: 2.12.0

Installed Add-ons: [[id=alertFilters, version=15.0.0],
[id=ascanrules, version=55.0.0], [id=automation,
version=0.29.0], [id=bruteforce, version=13.0.0],
[id=callhome, version=0.6.0], [id=commonlib,
version=1.14.0], [id=custompayloads, version=0.12.0],
[id=database, version=0.1.0], [id=diff, version=12.0.0],
[id=directorylistv1, version=5.0.0], [id=domxss,
version=15.0.0], [id=encoder, version=1.1.0], [id=exim,
version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz,
version=13.9.0], [id=gettingStarted, version=14.0.0],
[id=graaljs, version=0.3.0], [id=graphql, version=0.16.0],
[id=help, version=15.0.0], [id=hud, version=0.16.0],
[id=invoke, version=12.0.0], [id=network, version=0.9.0],
[id=oast, version=0.15.0], [id=onlineMenu, version=10.0.0],
[id=openapi, version=33.0.0], [id=pscanrules,
version=49.0.0], [id=quickstart, version=37.0.0],
[id=replacer, version=12.0.0], [id=reports, version=0.21.0],
[id=requester, version=7.2.0], [id=retest, version=0.5.0],
[id=retire, version=0.23.0], [id=reveal, version=5.0.0],
[id=scripts, version=38.0.0], [id=selenium,
version=15.12.1], [id=soap, version=17.0.0], [id=spider,
version=0.4.0], [id=spiderAjax, version=23.14.1], [id=tips,
version=10.0.0], [id=webdriverwindows, version=55.0.0],
[id=websocket, version=28.0.0], [id=zest, version=38.0.0]]

Operating System: Windows 10
Architecture: amd64
Java Version: Oracle Corporation 20.0.1
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: C:\Users\...\OWASP ZAP\
ZAP Installation Directory: C:\Program Files\OWASP\Zed Attack Proxy\.\
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)
`

**Comment by thc202** [comment]
Thank you!

**Comment by mttaggart** [comment]
I'm also having this issue. ZAP 2.13.0.

<details>
<summary>Support Info</summary>

```
OWASP ZAP
Version: 2.13.0

Installed Add-ons: [[id=alertFilters, version=17.0.0],
[id=allinonenotes, version=2.0.0], [id=ascanrules,
version=56.0.0], [id=ascanrulesAlpha, version=42.0.0],
[id=ascanrulesBeta, version=46.0.0], [id=authhelper,
version=0.9.0], [id=authstats, version=2.0.0],
[id=automation, version=0.30.0], [id=bruteforce,
version=14.0.0], [id=callgraph, version=5.0.0],
[id=callhome, version=0.7.0], [id=commonlib,
version=1.15.0], [id=communityScripts, version=17.0.0],
[id=custompayloads, version=0.12.0], [id=database,
version=0.2.0], [id=diff, version=13.0.0],
[id=directorylistv1, version=6.0.0], [id=directorylistv2_3,
version=4.0.0], [id=directorylistv2_3_lc, version=4.0.0],
[id=domxss, version=16.0.0], [id=encoder, version=1.2.0],
[id=exim, version=0.6.0], [id=fileupload, version=1.1.0],
[id=formhandler, version=6.4.0], [id=fuzz, version=13.10.0],
[id=fuzzdb, version=9.0.0], [id=fuzzdboffensive,
version=4.0.0], [id=gettingStarted, version=15.0.0],
[id=graaljs, version=0.4.0], [id=graphql, version=0.18.0],
[id=help, version=16.0.0], [id=hud, version=0.17.0],
[id=invoke, version=13.0.0], [id=jsonview, version=2.0.0],
[id=jwt, version=1.0.3], [id=jython, version=12.0.0],
[id=neonmarker, version=1.5.0], [id=network,
version=0.10.0], [id=oast, version=0.16.0], [id=onlineMenu,
version=11.0.0], [id=openapi, version=35.0.0],
[id=pscanrules, version=50.0.0], [id=pscanrulesBeta,
version=33.0.0], [id=quickstart, version=38.0.0],
[id=reflect, version=0.0.11], [id=regextester,
version=2.0.0], [id=replacer, version=13.0.0], [id=reports,
version=0.23.0], [id=requester, version=7.3.0], [id=retest,
version=0.6.0], [id=retire, version=0.24.0], [id=reveal,
version=6.0.0], [id=saml, version=10.0.0], [id=scripts,
version=39.0.0], [id=selenium, version=15.13.0], [id=soap,
version=18.0.0], [id=spider, version=0.5.0], [id=spiderAjax,
version=23.15.0], [id=sqliplugin, version=15.0.0], [id=sse,
version=12.0.0], [id=tips, version=11.0.0], [id=tokengen,
version=15.0.0], [id=treetools, version=8.0.0],
[id=viewstate, version=3.0.0], [id=wappalyzer,
version=21.22.0], [id=webdriverlinux, version=57.0.0],
[id=websocket, version=29.0.0], [id=zest, version=39.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: Debian 17.0.6
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/mtaggart/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Dark (com.formdev.flatlaf.FlatDarkLaf)
```
</details>

Stack trace:

```
Error: Connection disconnected with error 'Error: ZAP Error [java.io.IOException]: java.lang.IllegalStateException: AuthScheme is null


Stack Trace:
java.lang.IllegalStateException: AuthScheme is null
	at org.apache.hc.core5.util.Asserts.notNull(Asserts.java:56)
	at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.updateAuthState(HttpAuthenticator.java:216)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.needAuthentication(ZapProtocolExec.java:276)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
 [wrapped] java.io.IOException: java.lang.IllegalStateException: AuthScheme is null
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:374)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendRateLimited(BaseHttpSender.java:412)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:381)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:349)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:305)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:276)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:233)
	at org.parosproxy.paros.network.HttpSender.sendImpl(HttpSender.java:524)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:344)
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131)
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
: Status code '502''.
```

**Comment by thc202** [comment]
Is there the possibility of someone providing the messages that reproduce the issue? I tried proxy the example NTLM messages and the error does not occur, but will check the code again.

**Comment by thc202** [comment]
Proxying that request does not trigger the issue here, does it on your side?

**Comment by mttaggart** [comment]
It surely does. Of course I redacted the actual host information, so I'm not sure how you tested it.

**Comment by thc202** [comment]
I'm using a local server. What's the response? (e.g. a 200) I assume that's the NTLM authenticate message already?

**Comment by mttaggart** [comment]
The response is a 502 with the error message listed above.

I believe this may be related to the fact that the `WWW-Authenticate` header from this particular server does not provide any realm or other information—simply `NTLM`.

**Comment by trinakas** [comment]
Any update to this?  Just started getting it on 2.13.0  I tried installing the latest 2.14.0 and I'm getting the same thing?

`ZAP Error [java.io.IOException]: java.lang.IllegalStateException: AuthScheme is null


Stack Trace:
java.lang.IllegalStateException: AuthScheme is null
	at org.apache.hc.core5.util.Asserts.notNull(Asserts.java:56)
	at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.updateAuthState(HttpAuthenticator.java:216)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.needAuthentication(ZapProtocolExec.java:276)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
 [wrapped] java.io.IOException: java.lang.IllegalStateException: AuthScheme is null
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:374)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendRateLimited(BaseHttpSender.java:413)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:382)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:350)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:306)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:277)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:233)
	at org.parosproxy.paros.network.HttpSender.sendImpl(HttpSender.java:529)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:349)
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131)
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)`

**Comment by trinakas** [comment]
Any update to this?  Just started getting it on 2.13.0.  I tried installing the latest 2.14.0 and I'm getting the same thing.

`ZAP Error [java.io.IOException]: java.lang.IllegalStateException: AuthScheme is null


Stack Trace:
java.lang.IllegalStateException: AuthScheme is null
	at org.apache.hc.core5.util.Asserts.notNull(Asserts.java:56)
	at org.apache.hc.client5.http.impl.auth.HttpAuthenticator.updateAuthState(HttpAuthenticator.java:216)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.needAuthentication(ZapProtocolExec.java:276)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:188)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
 [wrapped] java.io.IOException: java.lang.IllegalStateException: AuthScheme is null
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:374)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendRateLimited(BaseHttpSender.java:413)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:382)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:350)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:306)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:277)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:233)
	at org.parosproxy.paros.network.HttpSender.sendImpl(HttpSender.java:529)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:349)
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131)
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)`

**Comment by thc202** [comment]
It someone is able to provide the steps to reproduce it.

**Comment by trinakas** [comment]
It's happening to me in the latest version of ZAP 2.14.0, using Chrome, on a site that uses Windows Authentication, e.g.- prompts for a user/pass before it loads the site, with the Response Type "HTTP 401 Challenge".  
![image](https://github.com/zaproxy/zaproxy/assets/17303642/48e675ae-72eb-419e-bee2-da6056a7e107)

In the "Advanced Settings..." action window, "Extended Production" is set to "Off" and "Enable Kernel-mode authentication" is "checked".
![image](https://github.com/zaproxy/zaproxy/assets/17303642/6a8e79b2-7b6c-49e3-91bc-dbc955210c20)

In the "Providers..." action window.  "Enabled Providers" has (in order) "Negotiate, NTLM".  
![image](https://github.com/zaproxy/zaproxy/assets/17303642/82b592c7-c134-4aa1-81b1-8142a7a5ee93)

**Comment by SteveSterleyNSC** [comment]
Our team have spent hours trying to get ZAP working last week and we are running into the exact same issue. It does not seem to pass an authentication token through when connecting through the proxy.

I have actually noticed that there are two errors in the history when trying to visit an app that requires Windows Auth. 

The first error is the regular 401 Unauthorised that you would expect IIS to return if you were not passing through NTLM authentication details:

![image](https://github.com/zaproxy/zaproxy/assets/135958630/0c75e855-6cce-4a39-8260-4f1e28a6bbdd)

You will notice here that the outgoing request has no Authorization header

`GET http://localhost:28864/api/User/GetCurrentUser HTTP/1.1
host: localhost:28864
Proxy-Connection: keep-alive
sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8`

The next error that gets triggered is a 502 Bad Gateway which is the error that everybody else here is reporting:

![image](https://github.com/zaproxy/zaproxy/assets/135958630/78d7e9da-4250-4d3c-8c80-c6fdb0c4300e)

Currently I am demonstrating the problem above on a development laptop running visual studio. You could replicate it by spinning up any web application application in visual studio that requires windows authentication and then attempting to navigate to one of its pages through ZAP.

I also have this same problem when I publish the app and host it in IIS (and have a set up similar to the person above me)

**Comment by thc202** [comment]
> Currently I am demonstrating the problem above on a development laptop running visual studio. You could replicate it by spinning up any web application application in visual studio that requires windows authentication and then attempting to navigate to one of its pages through ZAP.

Is it possible for you to share a simple/demo project that I can just put in a Windows VM to reproduce this?

**Comment by SteveSterleyNSC** [comment]
> > Currently I am demonstrating the problem above on a development laptop running visual studio. You could replicate it by spinning up any web application application in visual studio that requires windows authentication and then attempting to navigate to one of its pages through ZAP.
> 
> Is it possible for you to share a simple/demo project that I can just put in a Windows VM to reproduce this?

Sure, would you prefer older .net framework or .net core?

**Comment by thc202** [comment]
Whatever is easier to set up with https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by SteveSterleyNSC** [comment]
Thank you for looking into this. It's a simple demo project for an ASP.NET Core Web API. Make sure you run it targeting IIS Express to get the windows authentication features working

[WindowsAuth.zip](https://github.com/zaproxy/zaproxy/files/13399987/WindowsAuth.zip)

**Comment by Hennypics** [comment]
Hi all, is there maybe a fix for this? Running into the same issue with NTLM auth.

**Comment by SteveSterleyNSC** [comment]
We ultimately had to temporarily publish a new version of our app with NTLM auth disabled and the logged-in user spoofed so that we could test that copy instead.

**Comment by psiinon** [comment]
> We ultimately had to temporarily publish a new version of our app with NTLM auth disabled and the logged-in user spoofed so that we could test that copy instead.

Thats a good approach 😁 
As per https://www.zaproxy.org/docs/authentication/make-your-life-easier/

**Comment by Hennypics** [comment]
Sounds kind of strange to me, tbh :-) Is there maybe any other way around this?

**Comment by thc202** [comment]
No, this is still on my radar, I've been trying to set up the project shared earlier but no luck yet.

**Comment by Hennypics** [comment]
Ok, thank you!

**Comment by thc202** [comment]
I'm now able to reproduce this…

**Comment by Hennypics** [comment]
Hi @thc202,
thanks for your effort so far. Do you think that there will be a solution to this?

**Comment by Hennypics** [comment]
Thanks guys. This patched made it!
