### ISSUE TITLE
ZAP 2.12.0 certificate issue after startup

### ISSUE THREAD

**Issue by qweev** [zaproxy/zaproxy#7691]
after GUI app startup cert issue is visible in 2.12
with previous version 2.11 this issue was not visible

LOG:
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Program Files\OWASP\Zed Attack Proxy>zap.bat

C:\Program Files\OWASP\Zed Attack Proxy>if exist "C:\Users\TestRunner\OWASP ZAP\.ZAP_JVM.properties" (set /p jvmopts= 0<"C:\Users\TestRunner\OWASP ZAP\.ZAP_JVM.properties" )  else (set jvmopts=-Xmx512
m )

C:\Program Files\OWASP\Zed Attack Proxy>java -Xmx512m -jar zap-2.12.0.jar
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
2411 [main] INFO  org.zaproxy.zap.GuiBootstrap - OWASP ZAP 2.12.0 started 14/01/2023, 12:52:11 with home C:\Users\TestRunner\OWASP ZAP\
3800 [AWT-EventQueue-0] INFO  org.parosproxy.paros.view.View - Initialising View
6600 [ZAP-BootstrapGUI] INFO  org.zaproxy.zap.control.ExtensionFactory - Installed add-ons: [[id=alertFilters, version=15.0.0], [id=ascanrules, version=51.0.0], [id=automation, version=0.22.0], [id=br
uteforce, version=12.0.0], [id=callhome, version=0.6.0], [id=commonlib, version=1.12.0], [id=database, version=0.1.0], [id=diff, version=12.0.0], [id=directorylistv1, version=5.0.0], [id=domxss, versi
on=14.0.0], [id=encoder, version=1.0.0], [id=exim, version=0.3.0], [id=formhandler, version=6.1.0], [id=fuzz, version=13.9.0], [id=gettingStarted, version=14.0.0], [id=graaljs, version=0.3.0], [id=gra
phql, version=0.12.0], [id=help, version=15.0.0], [id=hud, version=0.15.0], [id=invoke, version=12.0.0], [id=network, version=0.6.0], [id=oast, version=0.14.0], [id=onlineMenu, version=10.0.0], [id=op
enapi, version=31.0.0], [id=pscanrules, version=45.0.0], [id=quickstart, version=36.0.0], [id=replacer, version=12.0.0], [id=reports, version=0.18.0], [id=requester, version=7.1.0], [id=retest, versio
n=0.5.0], [id=retire, version=0.19.0], [id=reveal, version=5.0.0], [id=scripts, version=34.0.0], [id=selenium, version=15.11.0], [id=soap, version=16.0.0], [id=spider, version=0.2.0], [id=spiderAjax,
version=23.10.0], [id=tips, version=10.0.0], [id=webdriverwindows, version=48.0.0], [id=websocket, version=28.0.0], [id=zest, version=38.0.0]]
6618 [ZAP-BootstrapGUI] INFO  org.zaproxy.zap.control.ExtensionFactory - Loading extensions
7682 [ZAP-BootstrapGUI] INFO  org.zaproxy.addon.network.internal.TlsUtils - Using supported SSL/TLS protocols: [TLSv1.2, TLSv1.3]
8152 [ZAP-BootstrapGUI] INFO  org.zaproxy.zap.control.ExtensionFactory - Extensions loaded
9114 [ZAP-BootstrapGUI] INFO  org.parosproxy.paros.extension.ExtensionLoader - Initializing Auto-update Extension - Allows ZAP to check for updates

18657 [ZAP-BootstrapGUI] INFO  org.zaproxy.addon.oast.services.callback.CallbackService - Started callback service on 0.0.0.0:49893
31302 [AWT-EventQueue-0] INFO  org.parosproxy.paros.control.Control - New Session
31335 [AWT-EventQueue-0] INFO  org.parosproxy.paros.control.Control - Create and Open Untitled Db


33470 [ZAP-IO-2-4] WARN  org.zaproxy.addon.network.internal.handlers.ServerExceptionHandler - Failed while establishing secure connection, cause: Received fatal alert: certificate_unknown
33461 [ZAP-telemetry-start] ERROR org.zaproxy.addon.callhome.ExtensionCallHome - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:353) ~[?:?]

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[?:?]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[?:?]
```

**Note:** adding owasp ca cert to java cacert with keytool solves issue for GUI ZAP app (cert error not visible after startup), but then when zap is run in deamon mode it is not possible to open any web page with proxy (connection timeout)

errors like these are visible:
```
8658 [ZAP-daemon] INFO  org.zaproxy.addon.oast.services.callback.CallbackService - Started callback service on 0.0.0.0:59587
8719 [ZAP-daemon] INFO  org.zaproxy.addon.network.ExtensionNetwork - ZAP is now listening on localhost:8090
15530 [ZAP-IO-2-4] WARN  org.zaproxy.addon.network.internal.handlers.ServerExceptionHandler - Failed while establishing secure connection, cause: Received fatal alert: bad_certificate
15916 [ZAP-IO-2-1] WARN  org.zaproxy.addon.network.internal.handlers.ServerExceptionHandler - Failed while establishing secure connection, cause: Received fatal alert: bad_certificate
16163 [ZAP-IO-2-3] WARN  org.zaproxy.addon.network.internal.handlers.ServerExceptionHandler - Failed while establishing secure connection, cause: Received fatal alert: bad_certificate
16457 [ZAP-IO-2-3] WARN  org.zaproxy.addon.network.internal.handlers.ServerExceptionHandler - Failed while establishing secure connection, cause: Received fatal alert: bad_certificate

353428 [ZAP-IO-Server-1-487] INFO  org.zaproxy.addon.graphql.VariantGraphQl - Parsing message body failed: null
353428 [ZAP-IO-Server-1-211] WARN  org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler - Failed to read https://news.zaproxy.org/ZAPnews within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.
```

and in web browser:
Failed to read http://10.20.202.109/Home/Index within 20 seconds, check to see if the site is available and if so consider adjusting ZAP's read time out in the Connection options panel.

**Comment by thc202** [comment]
Is your browser using ZAP's Root CA cert? It seems that there's still a problem in the configuration, ZAP is not able to access the internet.

**Comment by thc202** [comment]
Closing, there's not enough information to address the possible issue (though it looks like a configuration issue rather than a bug).
