### ISSUE TITLE
Client connection closed when ALPN is enabled and no protocol negotiated

### ISSUE THREAD

**Issue by Addygits** [zaproxy/zaproxy#7699]
### Describe the bug

While doing API testing on sites I am seeing an “Error: socket hangup” in postman collection  through ZAP proxy . The error only occurs after an upgrade to 2.12.0.  The 2.11.1 version receives the response back to postman without any issues.  The ZAP log files show an ALPN error. 

### Steps to reproduce the behavior

Use postman collection to test site API and receiving a socket hangup error response

### Expected behavior

Use postman collection to test site API and receive a successful response without error

### Software versions

2.12.0

### Screenshots

![image](https://user-images.githubusercontent.com/123023249/213290137-e02d5588-cd44-4fae-904e-eb137f7ef234.png)

![image](https://user-images.githubusercontent.com/123023249/213290060-b392879f-73d2-4d81-bbb8-ea4a12671848.png)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
That's the expected behaviour when ALPN is enabled, you can disable it. Although we'll probably have to change the behaviour since so many client applications don't seem to support ALPN.

**Comment by Addygits** [comment]
It can be disabled in ZAP? how is this done?

**Comment by thc202** [comment]
In Options > Network > Local Servers/Proxies, depending which proxy you are using either in Main Proxy or one of the additional proxies.
 https://www.zaproxy.org/docs/desktop/addons/network/options/localservers/#alpn

**Comment by Addygits** [comment]
When I try this I get a bad 502 gateway error.

**Comment by thc202** [comment]
You mean after disabling ALPN you get the 502? What's the actual error message?

**Comment by Addygits** [comment]
correct.  its showing as" failed: Connection timed out: no further information" in postman and a 502 bad gateway error in ZAP

**Comment by thc202** [comment]
What's the content of the response body in ZAP for the 502?

**Comment by Addygits** [comment]
`ZAP Error [org.apache.hc.client5.http.HttpHostConnectException]: Connect to https://(redacted):443 [(redacted)] failed: Connection timed out: no further information


Stack Trace:
org.apache.hc.client5.http.HttpHostConnectException: Connect to https://(redacted)443 [(redacted)] failed: Connection timed out: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:666)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.lambda$connectSocket$0(SSLConnectionSocketFactory.java:232)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:231)
	at org.zaproxy.addon.network.internal.client.apachev5.SslConnectionSocketFactory.connectSocket(SslConnectionSocketFactory.java:195)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
	at org.apache.hc.client5.http.impl.io.ZapHttpClientConnectionOperator.connect(ZapHttpClientConnectionOperator.java:95)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:178)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:158)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:363)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:331)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:287)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:258)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:63)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:303)
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:147)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:129)
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:66)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
`

**Comment by jczucco** [comment]
I had the same issue with Postman + ZAP. 

Just disable ALPN in ZAP proxy configuration fixed it.

![ALPN](https://user-images.githubusercontent.com/770087/214685860-3ea022d8-732c-4ac8-822a-38dbb63bf539.png)

**Comment by Zune01** [comment]
How are we supposed to turn it off in a CI/CD environment with headless zap-docker? I've tried with -config network.localServers.mainProxy.alpn.enabled=false but it won't take.

**Comment by thc202** [comment]
For the time being you also need to add: `-config network.localServers.mainProxy.address=0.0.0.0` (adjust the address to match what you want/need).
