### ISSUE TITLE
UncaughtExceptionLogger - Exception in thread "ZAP-DownloadInstaller"

### ISSUE THREAD

**Issue by MikeAnast** [zaproxy/zaproxy#7790]
### Describe the bug

I use the latest zap docker image to perform various scans. Some of the scans hang out and never finish. The docker containers with the following error are continuously running.  I checked the logs on /root/.ZAP/zap.log and found the following error:

2023-03-22 15:59:57,422 [ZAP-DownloadInstaller] ERROR UncaughtExceptionLogger - Exception in thread "ZAP-DownloadInstaller"
java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11.XToolkit
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:315) ~[?:?]
	at java.awt.Toolkit$2.run(Toolkit.java:588) ~[?:?]
	at java.awt.Toolkit$2.run(Toolkit.java:583) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582) ~[?:?]
	at javax.swing.ImageIcon.<init>(ImageIcon.java:198) ~[?:?]
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217) ~[?:?]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.getScanStatus(ExtensionAutoUpdate.java:705) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(ExtensionAutoUpdate.java:552) ~[zap-2.12.0.jar:2.12.0]

### Steps to reproduce the behavior

1. Run -> sudo docker run --net=host --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -m 1 -t <host> -T 1 -J report.json
2. docker ps (docker container never stops)

### Expected behavior

Even with errors and exceptions on the zap tool the docker container should eventually stop running.

### Software versions

Docker image id: 508bc775de4d
RepoDigests: owasp/zap2docker-stable@sha256:479cfb4dc3de273ed3d47f6a1a1a2dead4b257756e1d547455f3e779a39bad66

### Screenshots

![image](https://user-images.githubusercontent.com/24854891/226978163-1a0f4ee0-b3c6-4d03-9dea-7aec06c81f35.png)

### Additional context

I dont know if its important but the machine that i use has aarch64 cpu architecture. 

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Merging into #3798.
