### ISSUE TITLE
UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-18-openjdk-amd64/lib/libawt_xawt.so

### ISSUE THREAD

**Issue by issayevruslan** [zaproxy/zaproxy#7794]
### Describe the bug

When run zap.sh it shows
UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-18-openjdk-amd64/lib/libawt_xawt.so

### Steps to reproduce the behavior

Go to /opt/zaproxy/
run zap.sh (from root)

### Expected behavior

Found Java version 18.0.2-ea
Available memory: 15781 MB
Using JVM args: -Xmx3945m
472 [main] INFO  org.zaproxy.zap.GuiBootstrap - OWASP ZAP 2.12.0 started 23/03/2023, 08:51:00 with home /root/.ZAP/
479 [main] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "main"
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-18-openjdk-amd64/lib/libawt_xawt.so
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:785) ~[?:?]
        at java.lang.System.load(System.java:1979) ~[?:?]
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176) ~[?:?]
        at jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:322) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:289) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403) ~[?:?]
        at java.lang.Runtime.loadLibrary0(Runtime.java:848) ~[?:?]
        at java.lang.System.loadLibrary(System.java:2015) ~[?:?]
        at java.awt.Toolkit$2.run(Toolkit.java:1392) ~[?:?]
        at java.awt.Toolkit$2.run(Toolkit.java:1390) ~[?:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at java.awt.Toolkit.loadLibraries(Toolkit.java:1389) ~[?:?]
        at java.awt.Toolkit.initStatic(Toolkit.java:1427) ~[?:?]
        at java.awt.Toolkit.<clinit>(Toolkit.java:1401) ~[?:?]
        at java.awt.EventQueue.invokeLater(EventQueue.java:1316) ~[?:?]
        at org.zaproxy.zap.GuiBootstrap.start(GuiBootstrap.java:95) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.ZAP.main(ZAP.java:94) ~[zap-2.12.0.jar:2.12.0]

### Software versions

zap 2.12.0

My OS
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION="2023.1"
VERSION_ID="2023.1"
VERSION_CODENAME="kali-rolling"
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

Linux ops 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Maybe you have installed only the headless JRE.
