### ISSUE TITLE
Automation panel might use outdated jobs

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7799]
### Describe the bug

The Automation panel dos not refresh the plan when jobs are added/removed which leads to issues.

### Steps to reproduce the behavior

1. Create a plan with the `report` job.
1. Remove the Report Generation add-on.
1. Run the plan. Notice errors in the log/console, e.g.:
   ```
   java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key reports.automation.dialog.summary
   	at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
   	at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
   	at org.zaproxy.zap.utils.I18N.getStringImpl(I18N.java:182) ~[main/:?]
   	at org.zaproxy.zap.utils.I18N.getString(I18N.java:314) ~[main/:?]
   	at org.zaproxy.addon.reports.automation.ReportJob.getSummary(ReportJob.java:405) ~[?:?]
   	at org.zaproxy.addon.automation.gui.PlanTreeTableModel.getValueAt(PlanTreeTableModel.java:190) ~[?:?]
   	at org.jdesktop.swingx.JXTreeTable$TreeTableModelAdapter.getValueAt(JXTreeTable.java:2445) ~[swingx-all-1.6.5-1.jar:1.6.5-1]
   ```
1. Attempt to edit the `report` job which leads to other errors, e.g.:
   ```
   Exception in thread "AWT-EventQueue-0"
   java.lang.NoClassDefFoundError: org/zaproxy/addon/reports/automation/ReportJobDialog
   	at org.zaproxy.addon.reports.automation.ReportJob.showDialog(ReportJob.java:400) ~[?:?]
   	at org.zaproxy.addon.automation.gui.AutomationPanel$3.mouseClicked(AutomationPanel.java:645) ~[?:?]
   	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278) ~[?:?]
   ```

### Expected behavior

The Automation panel should properly handle dynamic changes of jobs (update/removal).

### Software versions

Automation Framework v0.27.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by Avinash-Acharya** [comment]
> 2. Remove the Report Generation add-on.

How to proceed with this? Does it mean to uninstall the Report Generation addon?

**Comment by thc202** [comment]
Yes.

**Comment by Avinash-Acharya** [comment]
> 3. Run the plan. Notice errors in the log/console, e.g.:

I got the same error as yours yesterday. But today I don't get an error,

![image](https://user-images.githubusercontent.com/120123021/229741592-7044b7e8-c93e-425f-9069-8c155be56717.png)

**Comment by code-sparsh** [comment]
Hey! Is something like this okay? - 

Every time someone runs a plan, it would first check if all the jobs mentioned in that plan have their corresponding addOns installed or not. And if not installed, mark that job run as fail and give a message like "spider addOn not installed" in the output window of the automation tab

I mean here - 
![Screenshot (121)](https://user-images.githubusercontent.com/85060248/230572686-633a920d-2384-4068-a6d7-4d5663fb753b.png)

**Comment by aryangupta701** [comment]
hello I want to work on this issue

**Comment by code-sparsh** [comment]
@aryangupta701, ahh sorry but have you actually started working on it? I was actually brainstorming on this issue from past few days and I think I have some progress too. I guess I should have asked for assignment beforehand, but I forgot somehow :(
 
My bad :(
If you have really started working on it, it's totally fair that you take the issue. otherwise if you can handover this to me it would be really great and fair. Please let me know.

**Comment by aryangupta701** [comment]
Not yet. You can take over this issue. :)

**Comment by code-sparsh** [comment]
@aryangupta701 Thanks :)

**Comment by code-sparsh** [comment]
@thc202  @kingthorin, Actually I had few doubts - 
1) Is there any specific event defined in ZAP which is fired whenever an add-on is uninstalled? 
2) I was going through all the files of Automation. and I found an event called "JOB_REMOVED". Initially I thought it must be getting fired automatically after its add-on is uninstalled. But I tested it and its not the case. 

I do need to listen for events right? in order to implement this. Because only then it would show dynamic changes to the GUI tab. Please correct me if I am wrong.

**Comment by kingthorin** [comment]
It looks like there's an event you could use: https://github.com/zaproxy/zaproxy/blob/main/zap/src/main/java/org/zaproxy/zap/extension/autoupdate/UninstallationProgressDialogue.java#L391

**Comment by kingthorin** [comment]
Thanks @thc202

**Comment by code-sparsh** [comment]
> That's internal, you should use an `AddOnInstallationStatusListener` instead, e.g.:
> 
> https://github.com/zaproxy/zaproxy/blob/d771fae234ef5ffa24e6ef9b01ec0796e2555741/zap/src/main/java/org/zaproxy/zap/extension/help/ExtensionHelp.java#L497
> 
> Although, the jobs are added/removed through the `ExtensionAutomation` itself (e.g. `registerAutomationJob`).

Thanks for this! 
I think I got it now :)
