### ISSUE TITLE
Error Parsing OpenAPI definition

### ISSUE THREAD

**Issue by Sperez96** [zaproxy/zaproxy#7876]
### Describe the bug

Hi, 

when I try to "Import an OpenAPI definition from the local file system" from Zap UI, I obtain an error.

At first, message is:
`
OpenAPI definition parsed successfully
`

When I close pop up, I obtain the following message:

`
Job Load Openapi Definition target: null error: Failed to parse OpenAPI definition.
org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: data exception: text data, right truncated ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
    at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:86)
    at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:449)
Caused by: java.sql.SQLDataException: data exception: text data, right truncated ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
    at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
    at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
    at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source)
    at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84)
`

The problem is in zap UI, and zap Automation Framework, because plan has been stopped when error is present.

File tested is 280KB

### Steps to reproduce the behavior

1. Go to Import Options
2. Select: "Import an OpenAPI definition from the local file system"
3. Close pop up: "OpenAPI definition parsed successfully"
4. Process is stopped with error

### Expected behavior

Zap Automation framework should´t receive error and plan continue as expected

### Software versions

ZAP 2.12.0 on Windows

ZAP 2.12.0 on Mac

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/70332695/af0f8673-aa5c-45b2-8f4b-8ac93178c3ee)
![image](https://github.com/zaproxy/zaproxy/assets/70332695/bf743881-d3dd-4561-931b-52514e4fd4f0)

### Errors from the zap.log file

2023-05-24 10:14:41,084 [ZAP-BootstrapGUI] INFO  BaseDatabaseType - Database: jdbc:hsqldb:file:C:\Users\Username\OWASP ZAP\db\permanent (HSQL Database Engine 2.7)
2023-05-24 10:14:41,099 [ZAP-BootstrapGUI] WARN  Database - Flyway upgrade recommended: HSQLDB 2.7 is newer than this version of Flyway and support has not been tested. The latest supported version of HSQLDB is 2.6.
2023-05-24 10:14:41,153 [ZAP-BootstrapGUI] INFO  DbValidate - Successfully validated 1 migration (execution time 00:00.030s)
2023-05-24 10:14:41,168 [ZAP-BootstrapGUI] INFO  DbMigrate - Current version of schema "PUBLIC": 1
2023-05-24 10:14:41,168 [ZAP-BootstrapGUI] INFO  DbMigrate - Schema "PUBLIC" is up to date. No migration necessary.
2023-05-24 10:14:41,184 [ZAP-BootstrapGUI] INFO  CallbackService - Started callback service on 0.0.0.0:1959
2023-05-24 10:14:45,888 [AWT-EventQueue-0] INFO  Control - New Session
2023-05-24 10:14:45,919 [AWT-EventQueue-0] INFO  Control - Create and Open Untitled Db
2023-05-24 10:14:48,309 [ZAP-cfu] WARN  AddOnCollection - Failed to create add-on for openapi
java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1474) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1482) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1320) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1282) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:186) ~[?:?]
	at org.zaproxy.zap.control.AddOn.loadManifestFile(AddOn.java:490) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:578) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnCollection.load(AddOnCollection.java:140) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:59) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$4.run(ExtensionAutoUpdate.java:1122) ~[zap-2.12.0.jar:2.12.0]
2023-05-24 10:14:48,340 [ZAP-cfu] WARN  AddOnCollection - Failed to create add-on for reports
java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1474) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1482) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1320) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1282) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:186) ~[?:?]
	at org.zaproxy.zap.control.AddOn.loadManifestFile(AddOn.java:490) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOn.<init>(AddOn.java:578) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnCollection.load(AddOnCollection.java:140) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.control.AddOnCollection.<init>(AddOnCollection.java:59) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$4.run(ExtensionAutoUpdate.java:1122) ~[zap-2.12.0.jar:2.12.0]
2023-05-24 10:14:49,386 [ZAP-cfu] INFO  ExtensionAutoUpdate - There is/are 3 newer addons
2023-05-24 10:14:59,378 [ZAP-DownloadInstaller] INFO  ExtensionAutoUpdate - Installing new addon domxss v15.0.0
2023-05-24 10:14:59,378 [ZAP-DownloadInstaller] INFO  ExtensionAutoUpdate - Finished installing new addon domxss v15.0.0
2023-05-24 10:15:00,212 [ZAP-DownloadInstaller] INFO  ExtensionAutoUpdate - Installing new addon selenium v15.12.0
2023-05-24 10:15:00,539 [ZAP-DownloadInstaller] INFO  ExtensionPassiveScan - loaded passive scan rule: Authentication Request Identified
2023-05-24 10:15:00,539 [ZAP-DownloadInstaller] INFO  ExtensionPassiveScan - loaded passive scan rule: Session Management Response Identified
2023-05-24 10:15:00,539 [ZAP-DownloadInstaller] INFO  ExtensionPassiveScan - loaded passive scan rule: Verification Request Identified
2023-05-24 10:15:01,194 [ZAP-DownloadInstaller] INFO  ExtensionAutoUpdate - Finished installing new addon selenium v15.12.0
2023-05-24 10:15:01,279 [ZAP-DownloadInstaller] INFO  ExtensionAutoUpdate - Installing new addon authhelper v0.7.0
2023-05-24 10:15:01,324 [ZAP-DownloadInstaller] INFO  ExtensionPassiveScan - loaded passive scan rule: Authentication Request Identified
2023-05-24 10:15:01,324 [ZAP-DownloadInstaller] INFO  ExtensionPassiveScan - loaded passive scan rule: Session Management Response Identified
2023-05-24 10:15:01,324 [ZAP-DownloadInstaller] INFO  ExtensionPassiveScan - loaded passive scan rule: Verification Request Identified
2023-05-24 10:15:01,339 [ZAP-DownloadInstaller] INFO  ExtensionAutoUpdate - Finished installing new addon authhelper v0.7.0
2023-05-24 10:21:20,570 [ZAP-Import-OpenAPI-1] WARN  ExtensionOpenApi - java.sql.SQLDataException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:86) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:449) ~[?:?]
Caused by: java.sql.SQLDataException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84) ~[?:?]
	... 1 more
Caused by: org.hsqldb.HsqlException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84) ~[?:?]
	... 1 more
Caused by: org.hsqldb.HsqlException: excepción de datos: dato de tipo texto, truncado por la derecha
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.types.CharacterType.convertToTypeLimits(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84) ~[?:?]
	... 1 more
2023-05-24 10:31:24,243 [ZAP-Import-OpenAPI-2] WARN  ExtensionOpenApi - java.sql.SQLDataException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:86) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:449) ~[?:?]
Caused by: java.sql.SQLDataException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84) ~[?:?]
	... 1 more
Caused by: org.hsqldb.HsqlException: excepción de datos: dato de tipo texto, truncado por la derecha ; size limit: 16777216 table: OPENAPI_SPECS column: DEFINITION
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84) ~[?:?]
	... 1 more
Caused by: org.hsqldb.HsqlException: excepción de datos: dato de tipo texto, truncado por la derecha
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.types.CharacterType.convertToTypeLimits(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.enforceTypeLimits(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.generateAndCheckData(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDML.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.zaproxy.zap.extension.openapi.TableOpenApi.insertOpenApiSpec(TableOpenApi.java:84) ~[?:?]
	... 1 more

### Would you like to help fix this issue?

- [ ] Yes

**Comment by pauldicarlo** [comment]
Is there any timeline on when this issue might be looked at?  Thank you.

**Comment by kingthorin** [comment]
When we have the file(s) and conditions to recreate the issue and someone is interested in tackling it.

**Comment by pauldicarlo** [comment]
In my local environment, I increased the size for definition to 64M and that seemed to fix the problem for our rather large json file we were seeking to import.  Would it be possible to expose this to a configurable setting?  (apologies, I'm not an expert in Zap). Thank you.

<img width="815" alt="image" src="https://github.com/zaproxy/zaproxy/assets/23062592/87e1b39d-c94c-4a9a-ac43-b4b3e08046a6">

**Comment by thc202** [comment]
What's the size of the definition?

**Comment by pauldicarlo** [comment]
The import file ends up 395 tasks being run.

```
pdicarlo@Pauls-MacBook-Pro vpc-not-public % ls -ltr vpc-scoped.json              
-rw-r--r--  1 pdicarlo  staff  4034889 Jun  5 09:05 vpc-scoped.json

pdicarlo@Pauls-MacBook-Pro vpc-not-public % wc -l vpc-scoped.json  
  105060 vpc-scoped.json

pdicarlo@Pauls-MacBook-Pro vpc-not-public % grep responses vpc-scoped.json |wc -l
     395

```

I'll see if I can modify the code to get the size of the definition string that is created from the import.  I don't think I can provide my employers json file

**Comment by kingthorin** [comment]
Looks like 4meg to me. (Tip: You can add `h` to your `ls` switches for human readable sizes.)

**Comment by pauldicarlo** [comment]
I dumped the definition to a file just before it went to persist it:

```
pdicarlo@Pauls-MacBook-Pro /tmp % ls -ltrh file.txt
-rw-r--r--@ 1 pdicarlo  wheel    19M Jun 20 18:26 file.txt
pdicarlo@Pauls-MacBook-Pro /tmp % wc -l file.txt
  373126 file.txt
```

**Comment by kingthorin** [comment]
Thanks

**Comment by thc202** [comment]
https://github.com/zaproxy/zaproxy/issues/7876#issuecomment-1599722925

What's the difference between the two? Is the definition originally split between several files?

**Comment by pauldicarlo** [comment]
https://github.com/zaproxy/zaproxy/issues/7876#issuecomment-1600265688 "_What's the difference between the two? Is the definition originally split between several files?_"

The first file I mentioned ("**vpc-scoped.json** ")  is the openAPI json file that I am importing into OWASP ZAP.  Single file.  It is not split between files.

The second file I mention above "**file.txt**" is where I took the definition that was created from the import and (by modifying Zap code) had it persist it to a file to get the size of the definition that it was trying to insert into the database.

**Comment by thc202** [comment]
I understand what they are but I was asking what's the difference between the two, i.e. their contents. Why is `file.txt` now 19M. Are the object references now duplicated in each endpoint?

**Comment by pauldicarlo** [comment]
That looks to be the case @thc202 ...

```
pdicarlo@Pauls-MacBook-Pro vpc-not-public % grep \$ref vpc-scoped.json | wc -l
    3824

pdicarlo@Pauls-MacBook-Pro ZAPSTUFF % grep \$ref /tmp/file.txt | wc -l
     276

```

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Version 34 of the OpenAPI add-on is being released right now. You should be able to test the fixes shortly.

**Comment by pauldicarlo** [comment]
Thank you.  Will check it out.

**Comment by megalucio** [comment]
Still seeing the same issue, as reproduced here https://github.com/zaproxy/zaproxy/issues/8193. Same for the automation framework openapi job. Using latest version of ZAP and the addon, so does not seem to be fixed

**Comment by kingthorin** [comment]
Why would you think it's fixed if the issue(s) are still open 😕

**Comment by megalucio** [comment]
Mmm, appologies, I guess I got confused with this comment:

> Version 34 of the OpenAPI add-on is being released right now. You should be able to test the fixes shortly.

Anything I can do to help here? Gladly will try to take a look if pointed in right direction...

**Comment by kingthorin** [comment]
Reproducible examples would help, a lot!

As can be seen here the size of the DB storage was increased but we never got feedback/confirmation.

**Comment by megalucio** [comment]
Can reproduce openapi definition https://github.com/commercetools/commercetools-api-reference/blob/main/oas/api/openapi.yaml

**Comment by megalucio** [comment]
What I really don't get though is that the error only seems to be happening when using local file, but it doesnt when pointing to a URL. Should the functionality not be the same for both cases?

**Comment by kingthorin** [comment]
Should be. Thanks for the sample!

**Comment by thc202** [comment]
It's not exactly the same.
