### ISSUE TITLE
ZAP 2.12 ActivClient Issue

### ISSUE THREAD

**Issue by Foteini7** [zaproxy/zaproxy#7895]
### Describe the bug

With ZAP 2.10 we were able to add CAC/PIV certificates in the keystore by adding the PCKS#11 driver for ActivClient.

ZAP 2.12 displays an error that the driver or password is wrong, the previous functionality is lost.

### Steps to reproduce the behavior

Go to Options, Network, Client Certificates, Check "Use Certificate", select PKCS#11, Manage, Add, Select the acpkcs211.dll ActivClient library.  Select the driver you just added and enter the CAC pin number, add to keystore.
An error will be displayed: Error, Maybe your PIN or library is wrong.

The same process will work in version 2.10 but not in 2.12

### Expected behavior

Expecting ZAP to successfully add the certificate to keystore

### Software versions

ZAP 2.12

### Errors from the zap.log file

2023-06-06 13:20:12,300 [AWT-EventQueue-0] ERROR ClientCertificatesOptionsPanel - Couldn't add key from ActivClient
java.lang.IllegalAccessException: class org.zaproxy.addon.network.internal.client.KeyStores cannot access class sun.security.pkcs11.SunPKCS11 (in module jdk.crypto.cryptoki) because module jdk.crypto.cryptoki does not export sun.security.pkcs11 to unnamed module @21de929d
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:560) ~[?:?]
	at org.zaproxy.addon.network.internal.client.KeyStores.createPkcs11Provider(KeyStores.java:157) ~[?:?]
	at org.zaproxy.addon.network.internal.client.KeyStores.addPkcs11KeyStore(KeyStores.java:134) ~[?:?]
	at org.zaproxy.addon.network.ClientCertificatesOptionsPanel$KeyStorePanel.addPkcs11KeyStore(ClientCertificatesOptionsPanel.java:708) ~[?:?]
	at org.zaproxy.addon.network.ClientCertificatesOptionsPanel$Pkcs11Panel.lambda$new$2(ClientCertificatesOptionsPanel.java:371) ~[?:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1080) ~[?:?]
	at java.awt.Component.show(Component.java:1728) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1675) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1036) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1016) ~[?:?]
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:136) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:445) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:74) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:65) ~[zap-2.12.0.jar:2.12.0]
	at org.zaproxy.zap.view.MainToolbarPanel$8.actionPerformed(MainToolbarPanel.java:453) ~[zap-2.12.0.jar:2.12.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:746) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:744) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:743) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Quote @thc202:

> Did it work in 2.11?

**Comment by kingthorin** [comment]
Quote @Foteini7 

> I have not tried the 2.11 version, this can be an option if it works, since the 2.10 has the log4j issue

**Comment by Foteini7** [comment]
@thc202 we haven't tried the 2.11 version, if it works it will be a work around since we cannot use the 2.10 version due to a an old log4j file present

**Comment by thc202** [comment]
Just wanted to know if it was still working in that version.

What Java version were you using with 2.10 and what Java version are you using with 2.12?

**Comment by Foteini7** [comment]
@thc202 in order to identify the issue I run both ZAP versions on the same environment with the same Java, I used the OpenJDK 17U both x86 and x64 versions. I am using ZAP in a windows environment, tried both win 10 and server 2019. I start ZAP using the desktop shortcut available.

**Comment by mikeweinberg** [comment]
I'm experiencing this same issue attempting to use a smart card with several different drivers, including ActivClient. 

I'm using Windows 11 and Microsoft's OpenJDK 17 with ZAP 2.14.0

From my googling, the problem may be a change that was made in Java 11 and above that makes these classes inaccessible.  (Discussed [here](https://stackoverflow.com/questions/69474685/cant-access-to-sun-security-pkcs11-sunpkcs11-in-java-11), [here](https://blog.polynom.me/android-yubikey-signing/), and [here](https://docs.digicert.com/zf/software-trust-manager/troubleshoot/apksigner-errors-and-solutions.html))

It's proposed to add the java option to work around the issue:
`--add-exports=jdk.crypto.cryptoki/sun.security.pkcs11=ALL-UNNAMED`

I don't think I did it correctly because my various attempts to edit the zap.bat to add the java option resulted in errors and no indication that the jvm had the correct value.

Here is the Java 11 [PKCS#11 reference guide](https://docs.oracle.com/en/java/javase/11/security/pkcs11-reference-guide1.html).

**Comment by thc202** [comment]
What's the error you are getting without adding the `--add-exports` arg?

**Comment by mikeweinberg** [comment]
@thc202 If I don't add the `--add-exports` arg, I get the same problem reported by original poster, including an exception on the same line numbers.

```
2024-04-04 15:15:25,109 [AWT-EventQueue-0] ERROR ClientCertificatesOptionsPanel - Couldn't add key from ActivIdentity 
java.lang.IllegalAccessException: class org.zaproxy.addon.network.internal.client.KeyStores cannot access class sun.security.pkcs11.SunPKCS11 (in module jdk.crypto.cryptoki) because module jdk.crypto.cryptoki does not export sun.security.pkcs11 to unnamed module @3292c666
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:560) ~[?:?]
	at org.zaproxy.addon.network.internal.client.KeyStores.createPkcs11Provider(KeyStores.java:157) ~[?:?]
	at org.zaproxy.addon.network.internal.client.KeyStores.addPkcs11KeyStore(KeyStores.java:134) ~[?:?]
	at org.zaproxy.addon.network.ClientCertificatesOptionsPanel$KeyStorePanel.addPkcs11KeyStore(ClientCertificatesOptionsPanel.java:708) ~[?:?]
	at org.zaproxy.addon.network.ClientCertificatesOptionsPanel$Pkcs11Panel.lambda$new$2(ClientCertificatesOptionsPanel.java:371) ~[?:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1080) ~[?:?]
	at java.awt.Component.show(Component.java:1728) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1675) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1036) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1016) ~[?:?]
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:136) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:445) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:75) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:66) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.view.MainMenuBar$3.actionPerformed(MainMenuBar.java:245) ~[zap-2.14.0.jar:2.14.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.AbstractButton.doClick(AbstractButton.java:374) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028) ~[?:?]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6626) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3389) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6391) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5001) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4833) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
```
