### ISSUE TITLE
Error while uninstalling graphql addon

### ISSUE THREAD

**Issue by NicoAnth** [zaproxy/zaproxy#7896]
### Describe the bug

Yesterday afternoon, I was using the zap2docker-stable image to run a zap scan on a web app. Late afternoon, around 5pm (which coincides with the last update release), I relaunched a zap2docker-stable image and I had this issue :

```
73369 [ZAP-DownloadInstaller] ERROR org.zaproxy.zap.control.AddOnInstaller - An error occurred while uninstalling the extension "org.zaproxy.addon.graphql.spider.ExtensionGraphQlSpider" bundled in the add-on "graphql":
java.lang.NullPointerException: null
        at org.zaproxy.addon.graphql.spider.ExtensionGraphQlSpider.unload(ExtensionGraphQlSpider.java:80) ~[?:?]
        at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtension(AddOnInstaller.java:353) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.control.AddOnInstaller.uninstallAddOnExtensions(AddOnInstaller.java:329) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.control.AddOnInstaller.uninstall(AddOnInstaller.java:199) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.control.AddOnLoader.removeAddOnImpl(AddOnLoader.java:655) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.control.AddOnLoader.removeAddOn(AddOnLoader.java:609) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstall(ExtensionAutoUpdate.java:1258) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstallAddOns(ExtensionAutoUpdate.java:1632) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.uninstallAddOn(ExtensionAutoUpdate.java:1618) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.install(ExtensionAutoUpdate.java:1209) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.lambda$installNewExtensions$0(ExtensionAutoUpdate.java:647) ~[zap-2.12.0.jar:2.12.0]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate.installNewExtensions(ExtensionAutoUpdate.java:643) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate$3.run(ExtensionAutoUpdate.java:568) ~[zap-2.12.0.jar:2.12.0]
73375 [ZAP-DownloadInstaller] WARN  org.zaproxy.zap.extension.autoupdate.ExtensionAutoUpdate - It's recommended to restart ZAP. Not all add-ons were successfully uninstalled: [[id=graphql, version=0.15.0]] 
```

### Steps to reproduce the behavior

1. Run a zap scan using this command : `zap_docker_command = "sudo docker run --rm -u zap -p 8080:8080 --network=host -d -v path/to/a/working/dir:/zap/scripts owasp/zap2docker-stable zap.sh -daemon -config api.disablekey=true  -config sslcert.suppress_warnings=true"`
2. Observe the error.

It may be possible that something in my script triggers the error. However, I also tried with an old version of my script that was working great and the same error occurs.

### Expected behavior

Zap scan to run properly.

### Software versions

owasp/zap2docker-stable:latest

### Errors from the zap.log file

I have a bunch of errors after that one which seems to be the consequences of the first one.

[logs.txt](https://github.com/zaproxy/zaproxy/files/11675336/logs.txt)

### Additional context

I should report that my last zap image crashed after 2 hours of good services before this bug appeared. It happened when my Firefox session (not the one used by zap) also crashed so this wasn't about the image, still this could be correlate to the error. 

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Ensure you are using the latest image, should have the ID `cd51a669ebec`.

**Comment by NicoAnth** [comment]
Works fine thx !
