### ISSUE TITLE
TLS Failure when using ZAP as proxy for Cypress

### ISSUE THREAD

**Issue by james-luther** [zaproxy/zaproxy#7907]
### Describe the bug

I am working to automate using Cypress and ZAP together. Previously I would run the ZAP client and specify it as a proxy for Cypress. While attempting to do this in CI with the latest version of ZAP I am receiving the following error:

```
java.lang.IllegalArgumentException: Duplicate handler name: tls
	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:301) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290) ~[?:?]
	at org.zaproxy.addon.network.internal.handlers.TlsProtocolHandler.upgrade(TlsProtocolHandler.java:121) ~[?:?]
	at org.zaproxy.addon.network.internal.handlers.TlsProtocolHandler.decode(TlsProtocolHandler.java:99) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?
```
In Cypress I receive:

```
We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

> Error: Client network socket disconnected before secure TLS connection was established

Common situations why this would fail:
- you don't have internet access
- you forgot to run / boot your web server
- your web server isn't accessible
- you have weird network configuration settings on your computer
```

### Steps to reproduce the behavior

1. Start ZAP in daemon mode via docker with the following: `docker run -p 8080:8080 -v $(pwd):/zap/wrk/:rw -u zap -i owasp/zap2docker-live zap-x.sh -daemon -port 8080 -host 0.0.0.0 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true -config api.addrs.addr.url=.* -config api.addrs.addr.mask=.*
2. Run `npm ci` to ensure everything is installed and ready
3. Set your env variables for cypress: `export HTTP_PROXY=http://localhost:8080` and `export HTTPS_PROXY=https://localhost:8080`
4. run cypress with `npx cypress run` or use the GUI with `npx cypress open`

### Expected behavior

Cypress runs and uses ZAP as a proxy for all requests. This can then be used to generate a report that shows passive scans of the endpoints Cypress has run tests against.

### Software versions

The docker container used is owasp/zap2docker-live:lastest. When running in CI it is building a container that is using ZAP 2.12.0

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Can you try with `export HTTPS_PROXY=http://localhost:8080`?

**Comment by james-luther** [comment]
> Can you try with `export HTTPS_PROXY=http://localhost:8080`?

Will test it shortly and let you know.

**Comment by james-luther** [comment]
Well, that has everything working as it should be! I am having a CI error where the ZAP daemon is killed randomly but that's due to something I'm doing, not ZAP :-p. Thanks for the help!
