### ISSUE TITLE
Ajax spider not starting in docker image, "WARN  SpiderThread - Failed to start browser firefox-headless"

### ISSUE THREAD

**Issue by mharoonkwentra** [zaproxy/zaproxy#7912]
### Describe the bug

When using the -j flag to run baseline scan inside of the stable docker image, Ajax spider fail to start.

### Steps to reproduce the behavior

`docker run -u root --rm -it -v $(pwd)/:/zap/wrk/:rw owasp/zap2docker-stable:latest zap-baseline.py -t "https://example.com/" -j -m 1 -T 1 -d -s --autooff`

### Expected behavior

The ajax spider to run and scrape website for urls.

### Software versions
```
OWASP ZAP
Version: 2.12.0
Installed Add-ons: [[id=alertFilters, version=15.0.0], [id=ascanrules, version=55.0.0], [id=automation, version=0.29.0], [id=bruteforce, version=13.0.0], [id=callhome, version=0.6.0], [id=commonlib, version=1.14.0], [id=database, version=0.1.0], [id=diff, version=12.0.0], [id=directorylistv1, version=5.0.0], [id=domxss, version=15.0.0], [id=encoder, version=1.1.0], [id=exim, version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz, version=13.9.0], [id=gettingStarted, version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql, version=0.16.0], [id=help, version=15.0.0], [id=hud, version=0.16.0], [id=invoke, version=12.0.0], [id=network, version=0.9.0], [id=oast, version=0.15.0], [id=onlineMenu, version=10.0.0], [id=openapi, version=33.0.0], [id=pscanrules, version=49.0.0], [id=quickstart, version=37.0.0], [id=replacer, version=12.0.0], [id=reports, version=0.21.0], [id=requester, version=7.2.0], [id=retest, version=0.5.0], [id=retire, version=0.23.0], [id=reveal, version=5.0.0], [id=scripts, version=38.0.0], [id=selenium, version=15.12.1], [id=soap, version=17.0.0], [id=spider, version=0.4.0], [id=spiderAjax, version=23.14.1], [id=tips, version=10.0.0], [id=webdriverlinux, version=56.0.0], [id=websocket, version=28.0.0], [id=zest, version=38.0.0]]
Operating System: Linux
Architecture: amd64
Java Version: Debian 11.0.18
System's Locale: en
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /root/.ZAP/
ZAP Installation Directory: /zap/./
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)
```

### Errors from the zap.log file

```2023-06-20 03:15:11,469 [ZAP-SpiderThreadPool-0-thread-800] INFO  Spider - Spidering process has exceeded maxDuration of 1 minute(s)
2023-06-20 03:15:11,469 [ZAP-SpiderThreadPool-0-thread-800] INFO  Spider - Spidering process is complete. Shutting down...
2023-06-20 03:15:11,472 [ZAP-SpiderShutdownThread-0] INFO  SpiderThread - Spider scanning complete: true on https://test.example.com/ at 2023-06-20T03:15:11.471+0000
2023-06-20 03:15:15,876 [ZAP-AjaxSpiderApi] INFO  SpiderThread - Running Crawljax (with firefox-headless): API - https://test.example.com/
2023-06-20 03:15:15,878 [ZAP-AjaxSpiderApi] INFO  SpiderThread - Starting proxy...
2023-06-20 03:15:15,880 [ZAP-AjaxSpiderApi] INFO  SpiderThread - Proxy started, listening at port [44937].
2023-06-20 03:15:16,076 [ZAP-AjaxSpiderApi] INFO  Plugins - Loaded org.zaproxy.zap.extension.spiderAjax.SpiderThread$DummyPlugin@19c2f06d as a OnBrowserCreatedPlugin
2023-06-20 03:15:16,435 [ZAP-AjaxSpiderApi] WARN  SpiderThread - Failed to start browser firefox-headless
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: WebDriverException: Process unexpectedly closed with status 1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '64e9f339b10b', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.102.1-microsoft-standard-WSL2', java.version: '11.0.18'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
  at ConfigurationModule.configure(ConfigurationModule.java:47)
      \_ installed by: CoreModule -> ConfigurationModule
  at CrawlerContext.<init>(CrawlerContext.java:33)
      \_ for 1st parameter
  at Crawler.<init>(Crawler.java:75)
      \_ for 1st parameter
  at CrawlTaskConsumer.<init>(CrawlTaskConsumer.java:30)
      \_ for 3rd parameter
  while locating CrawlTaskConsumer

Learn more:
  https://github.com/google/guice/wiki/ERROR_IN_CUSTOM_PROVIDER

1 error

======================
Full classname legend:
======================
ConfigurationModule: "com.crawljax.di.ConfigurationModule"
CoreModule:          "com.crawljax.di.CoreModule"
CrawlTaskConsumer:   "com.crawljax.core.CrawlTaskConsumer"
Crawler:             "com.crawljax.core.Crawler"
CrawlerContext:      "com.crawljax.core.CrawlerContext"
WebDriverException:  "org.openqa.selenium.WebDriverException"
========================
End of classname legend:
========================

	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[?:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1103) ~[?:?]
	at com.crawljax.core.CrawlController.call(CrawlController.java:66) ~[?:?]
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37) ~[?:?]
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread.run(SpiderThread.java:259) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 1
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '64e9f339b10b', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.102.1-microsoft-standard-WSL2', java.version: '11.0.18'
Driver info: driver.version: FirefoxDriver
remote stacktrace: 
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62) ~[?:?]
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) ~[?:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1060) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:895) ~[?:?]
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:772) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:572) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:545) ~[?:?]
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:469) ~[?:?]
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread$AjaxSpiderBrowserBuilder.get(SpiderThread.java:437) ~[?:?]
	at com.google.inject.util.Providers$GuicifiedProvider.get(Providers.java:121) ~[?:?]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:86) ~[?:?]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57) ~[?:?]
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:60) ~[?:?]
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[?:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[?:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40) ~[?:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113) ~[?:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[?:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296) ~[?:?]
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100) ~[?:?]
	... 4 more
2023-06-20 03:15:16,464 [ZAP-AjaxSpiderApi] INFO  SpiderThread - Stopping proxy...
2023-06-20 03:15:16,468 [ZAP-AjaxSpiderApi] INFO  SpiderThread - Proxy stopped.
2023-06-20 03:15:16,468 [ZAP-AjaxSpiderApi] INFO  SpiderThread - Finished Crawljax: API - https://test.example.com/
2023-06-20 03:15:25,153 [ZAP-Shutdown] INFO  CoreAPI - OWASP ZAP 2.12.0 terminated.
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
Try removing `-u root`.

**Comment by mharoonkwentra** [comment]
> Try removing `-u root`.
Thanks for the fast reply!
You are right it seems to work now, but why would that be an issue?

**Comment by thc202** [comment]
That's a Firefox's restriction, it does not run when using root and other user's home dir.
