### ISSUE TITLE
Unable to save session due to HSQL Error

### ISSUE THREAD

**Issue by az-catch** [zaproxy/zaproxy#7920]
### Describe the bug

I have a script that runs on a linux box that scans a domain and generates and html report. This was working fine, but seems to break now when it goes to save a session. ZAP version, Java version and OS version were updated recently so any of these things might contribute

### Steps to reproduce the behavior

Install ZAP on an Ubuntu 22.04 box with Java 20 and then run a scan using the scripts below. NB the scan needs to run for a while to observe the issue.

Install Script
```
# install zap
cd /opt
sudo wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
sudo tar -zxvf ZAP_2.12.0_Linux.tar.gz
sudo rm ZAP_2.12.0_Linux.tar.gz
sudo ln -s /opt/ZAP_2.12.0/zap.sh /bin/zap
ZAP_API_KEY=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
echo "
ZAP_PATH=/opt/ZAP_2.12.0
ZAP_API_KEY=$ZAP_API_KEY
" | sudo tee -a /etc/environment

# add some extra zap stuff
sudo pip install zapcli
sudo zap -cmd -addoninstall reports
```

Scan Script
```
# domain to scan
DOMAIN="example.com"

# start daemon
zap -daemon -port 8090 -config api.key=$ZAP_API_KEY &
ZAP_PID=$!
sleep 20

# init session
timestamp=$(date '+%s');
zap-cli session new

# do scan
zap-cli open-url "https://$DOMAIN"
zap-cli spider "https://$DOMAIN"
zap-cli active-scan --recursive "https://$DOMAIN"
zap-cli alerts
RESULT=$?

# save session 
# ISSUE HAPPENS HERE
zap-cli session save $timestamp

# remove lock file so we can generate the report
rm ~/.ZAP/session/$timestamp.session.lck

# generate report
zap-cli report -o "/path/to/report.html" -f html

# get the result
RESULT=$?
RESULT_STR="FOUND ISSUES - ACTION MAY BE REQUIRED!!"
if [ "$RESULT" == "0" ]; then
    RESULT_STR="Found no issues"
fi

# kill the zap server
kill $ZAP_PID
```

### Expected behavior

Session should save

### Software versions

Found Java version 20.0.1
Available memory: 3863 MB
Using JVM args: -Xmx1931m
OWASP ZAP
Version: 2.12.0
Installed Add-ons: [[id=alertFilters, version=16.0.0], [id=ascanrules, version=55.0.0], [id=automation, version=0.29.0], [id=bruteforce, version=13.0.0], [id=callhome, version=0.6.0], [id=commonlib, version=1.14.0], [id=database, version=0.1.0], [id=diff, version=12.0.0], [id=directorylistv1, version=5.0.0], [id=domxss, version=15.0.0], [id=encoder, version=1.1.0], [id=exim, version=0.5.0], [id=formhandler, version=6.3.0], [id=fuzz, version=13.9.0], [id=gettingStarted, version=14.0.0], [id=graaljs, version=0.3.0], [id=graphql, version=0.17.0], [id=help, version=15.0.0], [id=hud, version=0.16.0], [id=invoke, version=12.0.0], [id=network, version=0.9.0], [id=oast, version=0.15.0], [id=onlineMenu, version=10.0.0], [id=openapi, version=34.0.0], [id=pscanrules, version=49.0.0], [id=quickstart, version=37.0.0], [id=replacer, version=12.0.0], [id=reports, version=0.22.0], [id=requester, version=7.2.0], [id=retest, version=0.5.0], [id=retire, version=0.23.0], [id=reveal, version=5.0.0], [id=scripts, version=38.0.0], [id=selenium, version=15.12.1], [id=soap, version=17.0.0], [id=spider, version=0.4.0], [id=spiderAjax, version=23.14.1], [id=tips, version=10.0.0], [id=webdriverlinux, version=56.0.0], [id=websocket, version=28.0.0], [id=zest, version=38.0.0]]
Operating System: Linux
Architecture: amd64
Java Version: Oracle Corporation 20.0.1
System's Locale: en
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /root/.ZAP/
ZAP Installation Directory: /opt/ZAP_2.12.0/./
Look and Feel: Metal (javax.swing.plaf.metal.MetalLookAndFeel)

### Errors from the zap.log file

2023-06-28 16:40:45,198 [Thread-11] INFO  Scanner - scanner completed in 14400.47s
2023-06-28 16:40:49,841 [ZAP-IO-Server-1-2] INFO  Control - Save Session
2023-06-28 16:41:17,376 [Thread-101035] WARN  Session - java.sql.SQLException: IO error: RowInputBinary 36112952
org.parosproxy.paros.db.DatabaseException: java.sql.SQLException: IO error: RowInputBinary 36112952
	at org.parosproxy.paros.db.paros.ParosTableHistory.reconnect(ParosTableHistory.java:253) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.db.paros.ParosAbstractTable.databaseOpen(ParosAbstractTable.java:52) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.db.AbstractDatabase.notifyListenersDatabaseOpen(AbstractDatabase.java:114) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.db.paros.ParosDatabase.open(ParosDatabase.java:152) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.model.Model.copySessionDb(Model.java:324) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.model.Model.moveSessionDb(Model.java:252) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.model.Session.save(Session.java:616) ~[zap-2.12.0.jar:2.12.0]
	at org.parosproxy.paros.model.Session$5.run(Session.java:592) ~[zap-2.12.0.jar:2.12.0]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.sql.SQLException: IO error: RowInputBinary 36112952
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.parosproxy.paros.db.paros.ParosTableHistory.reconnect(ParosTableHistory.java:237) ~[zap-2.12.0.jar:2.12.0]
	... 8 more
Caused by: org.hsqldb.HsqlException: IO error: RowInputBinary 36112952
	at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.rowio.RowInputBinary.readInt(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.NodeAVLDisk.<init>(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.DataFileCache.get(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.IndexAVL.lastRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.QuerySpecification.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementQuery.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.parosproxy.paros.db.paros.ParosTableHistory.reconnect(ParosTableHistory.java:237) ~[zap-2.12.0.jar:2.12.0]
	... 8 more
Caused by: java.io.EOFException
	at org.hsqldb.lib.HsqlByteArrayInputStream.readInt(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.rowio.RowInputBinary.readInt(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.NodeAVLDisk.<init>(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.DataFileCache.get(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.index.IndexAVL.lastRow(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.QuerySpecification.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementQuery.getResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source) ~[hsqldb-2.7.1.jar:2.7.1]
	at org.parosproxy.paros.db.paros.ParosTableHistory.reconnect(ParosTableHistory.java:237) ~[zap-2.12.0.jar:2.12.0]
	... 8 more

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
zapcli is maintained by a third party.

If you’re able to reproduce without it, let us know. Otherwise you should reach out to them for support.

**Comment by az-catch** [comment]
zap-cli just wraps the ZapV2 python API client and makes the API less painful to use.

In this context it hits the `core/action/saveSession` API endpoint. So these are interchangeable:

```
zap-cli session save $timestamp
```
and
```
curl -s -X GET http://127.0.0.1:8090/JSON/core/action/saveSession/?name=$timestamp\&apikey=$ZAP_API_KEY
```

**Comment by kingthorin** [comment]
Does it fail if you persist to start with, instead of at the end?

**Comment by az-catch** [comment]
`zap-cli session new` aka `/JSON/core/action/newSession/` creates a new session so it's already being persisted under a temporary session called something like `untitled3` at the point save session is called.

**Comment by kingthorin** [comment]
Then there’s no point saving it 😉

**Comment by kingthorin** [comment]
You’ve check whether or not the disk is full? The location is writable etc? Right

Also the save is actually completed before you remove the lock file?

**Comment by az-catch** [comment]
- I need to know what the session name is in order to do certain things, but yes that could be useful as a work around
- There is write access, but there could be some resource based issue at the time of save

I'll do some diagnostics and get back to you on disk space

**Comment by kingthorin** [comment]
More info is always good, but, zap-cli hasn’t been updated in 5 years and is based on a very old api client. Unless you take it out of the equation there’s not much we can do for you. Unless we know 100% how to recreate the issue without it.

**Comment by kingthorin** [comment]
No further input in months, closing.
