### ISSUE TITLE
 ERROR ScriptBasedAuthenticationMethodType - Unable to find script while loading Script Based Authentication Method for name: zap_authentication

### ISSUE THREAD

**Issue by xanhacks** [zaproxy/zaproxy#7928]
### Describe the bug

Hello !

I'm trying to run the ZAP full scan command inside the `owasp/zap2docker-stable:latest` container. I have the following error:

```
python3 zap-full-scan.py -j -r report.html -n poc_test.context -t http://127.0.0.1:8000 --hook hook_selenium.py
...
2023-06-30 12:17:26,301 Failed to load context file /zap/wrk/poc_test.context : internal_error
```

You can see a more detailed stacktrace on the `zap.log` file:

```
2023-06-30 12:04:50,980 [ZAP-daemon] INFO  ExtensionNetwork - ZAP is now listening on 0.0.0.0:44051
2023-06-30 12:04:52,639 [ZAP-IO-Server-1-1] ERROR ScriptBasedAuthenticationMethodType - Unable to find script while loading Script Based Authentication Method for name: zap_authentication
2023-06-30 12:04:52,696 [ZAP-IO-Server-1-1] ERROR ContextAPI - null
java.lang.NullPointerException: null
        at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType.persistMethodToSession(ScriptBasedAuthenticationMethodType.java:729) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.authentication.ExtensionAuthentication.persistContextData(ExtensionAuthentication.java:405) ~[zap-2.12.0.jar:2.12.0]
        at org.parosproxy.paros.model.Model.saveContext(Model.java:548) ~[zap-2.12.0.jar:2.12.0]
        at org.parosproxy.paros.model.Session.saveContext(Session.java:1266) ~[zap-2.12.0.jar:2.12.0]
        at org.parosproxy.paros.model.Session.importContext(Session.java:1565) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:521) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:100) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:74) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:59) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-06-30 12:04:54,840 [ZAP-SpiderInitThread-0] INFO  SpiderThread - Starting spidering scan on http://127.0.0.1:8000 at 2023-06-30T12:04:54.839+0000
```

Context file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
    <context>
        <name>poc_test</name>
        <desc/>
        <inscope>true</inscope>
        <incregexes>http://127.0.0.1:8000.*</incregexes>
        <excregexes>http://127.0.0.1:8000/logout.php</excregexes>
        <tech>
            <include>Db</include>
            <include>Db.CouchDB</include>
            <include>Db.Firebird</include>
            <include>Db.HypersonicSQL</include>
            <include>Db.IBM DB2</include>
            <include>Db.Microsoft Access</include>
            <include>Db.Microsoft SQL Server</include>
            <include>Db.MongoDB</include>
            <include>Db.MySQL</include>
            <include>Db.Oracle</include>
            <include>Db.PostgreSQL</include>
            <include>Db.SAP MaxDB</include>
            <include>Db.SQLite</include>
            <include>Db.Sybase</include>
            <include>Language</include>
            <include>Language.ASP</include>
            <include>Language.C</include>
            <include>Language.JSP/Servlet</include>
            <include>Language.Java</include>
            <include>Language.Java.Spring</include>
            <include>Language.JavaScript</include>
            <include>Language.PHP</include>
            <include>Language.Python</include>
            <include>Language.Ruby</include>
            <include>Language.XML</include>
            <include>OS</include>
            <include>OS.Linux</include>
            <include>OS.MacOS</include>
            <include>OS.Windows</include>
            <include>SCM</include>
            <include>SCM.Git</include>
            <include>SCM.SVN</include>
            <include>WS</include>
            <include>WS.Apache</include>
            <include>WS.IIS</include>
            <include>WS.Tomcat</include>
        </tech>
        <urlparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </urlparser>
        <postparser>
            <class>org.zaproxy.zap.model.StandardParameterParser</class>
            <config>{"kvps":"&amp;","kvs":"=","struct":[]}</config>
        </postparser>
        <authentication>
            <type>4</type>
            <strategy>POLL_URL</strategy>
            <pollurl>http://127.0.0.1:8000/index.php</pollurl>
            <polldata/>
            <pollheaders/>
            <pollfreq>3</pollfreq>
            <pollunits>REQUESTS</pollunits>
            <loggedin>Hello admin !</loggedin>
            <loggedout>Please sign in</loggedout>
            <script>
                <name>zap_authentication</name>
                <params/>
            </script>
        </authentication>
        <users>
            <user>32;true;YWRtaW4=;4;cGFzc3dvcmQ=:cGFzc3dvcmQ=&amp;dXNlcm5hbWU=:YWRtaW4=</user>
        </users>
        <forceduser>32</forceduser>
        <session>
            <type>0</type>
        </session>
        <authorization>
            <type>0</type>
            <basic>
                <header/>
                <body/>
                <logic>AND</logic>
                <code>-1</code>
            </basic>
        </authorization>
    </context>
</configuration>
``````

I tried to put my authentication script at different paths, but I always get the same error:

```/zap/scripts/authentication/zap_authentication.js
/zap/scripts/zap_authentication.js
/zap/zap_authentication.js
/zap/wrk/zap_authentication.js
/home/zap/.ZAP/scripts/scripts/authentication/zap_authentication.js
```

Could you help me with this issue ?

Regards,
xanhacks

### Steps to reproduce the behavior

See describe

### Expected behavior

See describe

### Software versions

See describe

### Would you like to help fix this issue?

- [ ] Yes

**Comment by kingthorin** [comment]
What's your docker command?

**Comment by kingthorin** [comment]
Please don't ask questions as issues - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

---

Based on the info you did provide you didn't mount the volume with your files and haven't used fille paths to their location.

**Comment by xanhacks** [comment]
Hey,

I have mounted the files and I set the network mode to host, so I can reach my target.

I'm sorry but I'm not a big fan of Google groups, that's why I'm asking here for help.

Regards

**Comment by psiinon** [comment]
Sorry, but we're not big fans of using issues for questions...

**Comment by xanhacks** [comment]
From my point of view, it's more of a bug than a question. The Authentication script is present on the disk and ZAP can't open it without giving more details.

**Comment by xanhacks** [comment]
The script is working well when I'm using the ZAP GUI, but not with the ZAP Docker & Context.

**Comment by thc202** [comment]
For the record, just placing a script somewhere in the file system will not make ZAP aware of it (there are some special places though). You need to add the script into ZAP (you don't seem to be doing that step, which you likely did at some point with the GUI).
