### ISSUE TITLE
Import of empty OpenAPI definition fails silently

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy#7949]
### Describe the bug

The user is not informed that the import of the OpenAPI definition failed, when the file or the response is empty.

### Steps to reproduce the behavior

1. Import an empty OpenAPI definition (URL or file)
2. Note that nothing happens, for the file the dialogue is closed but nothing else. For URL the dialogue is kept open but no further information (though an exception is logged).

Similar issue when URL importing through the ZAP API. (File reports import warnings but still successful API response).

### Expected behavior

The user is informed that the definition is not valid.

### Software versions

OpenAPI Support version 35

### Errors from the zap.log file

```
[AWT-EventQueue-0] ERROR org.zaproxy.zap.ZAP.UncaughtExceptionLogger - Exception in thread "AWT-EventQueue-0"
java.lang.IllegalArgumentException: The definition must not be null or empty.
	at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.<init>(SwaggerConverter.java:127) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinition(ExtensionOpenApi.java:401) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinitionV2(ExtensionOpenApi.java:281) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinition(ExtensionOpenApi.java:267) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ImportFromUrlDialog.importDefinition(ImportFromUrlDialog.java:68) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ImportFromAbstractDialog.lambda$new$0(ImportFromAbstractDialog.java:68) ~[?:?]
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
The behaviour described will not be exactly the same once zaproxy/zap-extensions#4745 is merged, the underlying problem is still the present though.
