### ISSUE TITLE
ZAProxy first time user onboarding / user experience issues

### ISSUE THREAD

**Issue by disconnect3d** [zaproxy/zaproxy#7983]
### Is your feature request related to a problem? Please describe.

Hi,

I think the user experience for the first time user onboarding is poor in ZAP, especially if someone has experience with other proxy tools and I would like to give some suggestions.

Just for clarity, this is how the ZAP window looks like when I launch it:
![image](https://github.com/zaproxy/zaproxy/assets/10009354/af19025e-f13a-41fe-9d50-207de010e351)

So yeah, I am new to ZAP, but the "Welcome to OWASP ZAP" page does not really give me the information I would like to be offered right away, which is:
1. Did it host a proxy server already? On which ip/port? I know this can be seen on the bottom of the window ("Main Proxy: localhost:8080") but it is hard to spot imho: may be good to reiterate it in the welcome page.
2. Everything runs HTTPS nowadays and obviously ZAP generated its own certificate. Where do I find it? 
* There is the documentation page https://www.zaproxy.org/docs/desktop/addons/network/options/servercertificates/#install which lacks this main information. It says things like:
    > When you are running ZAP for the first time then it will generate a Root CA certificate just for you. If you do not use the ‘browser launch’ feature then you have to install it within your browser or HTTP client application. See section [installation](https://www.zaproxy.org/docs/desktop/addons/network/options/servercertificates/#install) for more details.
    
    Or this for Mozilla Firefox installation:
    
    > Click Import and choose the saved owasp_zap_root_ca.cer file
    
    But I still have no idea where to find the `owasp_zap_root_ca.cer` file and it is not there in the directory I ran ZAP (zap.sh) from (Linux here).
   
    Okay, I finally found the certificate in `Options > Network > Server Certificates > Save`, but this is part is missing from the linked documentation. And ideally this should be on the "Welcome to ZAP" page. 

3. How do I intercept a web request? I had to go watch a [youtube video](https://www.youtube.com/watch?v=fa5LAfXmwoo) to find it and this can be done with this little green button up there: 
![image](https://github.com/zaproxy/zaproxy/assets/10009354/a14fd5c0-32f7-43db-a31d-aa0912d53a48)
    I understand there is loads of features, but can we make it easier? Have a button that would say "Intercept ON/OFF"? Or put that button on the bottom border?

Those are just suggestions and of course you don't have to apply them.

### Describe the solution you'd like

I would like ZAP to be easier to use for first-time users.

### Describe alternatives you've considered

Alternative? Using other tools ;).

### Would you like to help fix this issue?

- [ ] Yes

**Comment by psiinon** [comment]
First of all - many thanks for the feedback. We actually get very little detailed user experience feedback, so this is very helpful.
For context: what is your background (dev/qa/security) and what are you looking for in ZAP?
Did you try any of the "big buttons": "Automated Scan|", "Manual Explore", or "Learn More"?
If not, why not?
Many thanks.

**Comment by disconnect3d** [comment]
@psiinon I do security audits of code/pentests/etc. I just wanted quickly to intercept a few requests and see their content and then probably enter a loop of modifying a given request and re-sending it, so just a typical web pentesting flow here.

I didn't want an automated scan, so I haven't tried it. I clicked on "Manual Explore" but I already had my browser running, so I didn't need one to be run for me... Also it doesn't work for me. I have firefox installed but I am getting the following popup: " when I hit "launch browser":
![image](https://github.com/zaproxy/zaproxy/assets/10009354/a2f27293-c322-4517-ad8c-e3be3ec2c012)

And ZAP logs the following stacktrace:
```
69567 [ZAP-BrowserLauncher] ERROR org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch - Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1 
Host info: host: 'dc', ip: '127.0.1.1'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.19.0-35-generic', java.version: '11.0.20'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {prefs: {browser.tabs.documentchannel: false, dom.serviceWorkers.enabled: true, network.captive-portal-service.enabled: false, network.proxy.allow_hijacking_localhost: true, network.proxy.http: localhost, network.proxy.http_port: 8080, network.proxy.no_proxies_on: , network.proxy.share_proxy_settings: true, network.proxy.ssl: localhost, network.proxy.ssl_port: 8080, network.proxy.type: 1}}}]}]
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Process unexpectedly closed with status 1 
Host info: host: 'dc', ip: '127.0.1.1'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.19.0-35-generic', java.version: '11.0.20'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {prefs: {browser.tabs.documentchannel: false, dom.serviceWorkers.enabled: true, network.captive-portal-service.enabled: false, network.proxy.allow_hijacking_localhost: true, network.proxy.http: localhost, network.proxy.http_port: 8080, network.proxy.no_proxies_on: , network.proxy.share_proxy_settings: true, network.proxy.ssl: localhost, network.proxy.ssl_port: 8080, network.proxy.type: 1}}}]}]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96) ~[?:?]
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68) ~[?:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:151) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:146) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:130) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125) ~[?:?]
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:110) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:1059) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:896) ~[?:?]
	at org.zaproxy.zap.extension.selenium.internal.BuiltInSingleWebDriverProvider.getWebDriver(BuiltInSingleWebDriverProvider.java:63) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriverImpl(ExtensionSelenium.java:773) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getWebDriver(ExtensionSelenium.java:573) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowser(ExtensionSelenium.java:734) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:674) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:650) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:634) ~[?:?]
	at org.zaproxy.zap.extension.selenium.ExtensionSelenium.getProxiedBrowserByName(ExtensionSelenium.java:624) ~[?:?]
	at org.zaproxy.zap.extension.quickstart.launch.ExtensionQuickStartLaunch.lambda$launchBrowser$1(ExtensionQuickStartLaunch.java:218) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by psiinon** [comment]
Thanks.
The reason we dont make the port and certificate more obvious is because we think this is actually a worse user experience (apart from the fact it hasnt worked in your case of course;).
Configuring the proxy and importing the cert is time consuming and error prone.
If you launch a browser from ZAP (and assuming it works) then it is configured to proxy via ZAP and ignore cert warnings. We think this is a better option for most people getting started with ZAP.

Having said that, we definitely want to improve the onboarding experience so your input is very helpful.

It sounds like you didnt click on the "Learn More" button and therefore didnt read the ZAP Getting started Guide: https://www.zaproxy.org/getting-started/

This is a problem for us.
Security tools are not intuitive because they dont do intuitive things. If we cant effectively direct people to some form of documentation when they are stuck then there is a limit to what we can do ☹️

**Comment by thc202** [comment]
What OS are you using? Is Firefox a snap?

**Comment by kingthorin** [comment]
What OS are you using? Is Firefox a snap?

**Comment by Krishna-cell-12** [comment]
Hello,

I’m a new contributor to OWASP ZAP and have completed the development setup. I’m interested in working on this onboarding / usability improvement issue.

Before I begin, could you clarify if there are any specific expectations for how this improvement should be implemented? For example:
- Should the onboarding suggestions be implemented in the welcome UI?
- Are there existing docs that should be updated alongside UI changes?
- Is there a preferred place in the codebase to add extra guidance for first-time users?

Thanks!

**Comment by thc202** [comment]
This is not a good first issue, it has no clear outcomes defined yet. What are your interests? [ZAP Developer Group](https://groups.google.com/g/zaproxy-develop) is a better place to talk about this.
(Note that ZAP is no longer part of OWASP.)
