### ISSUE TITLE
Error generating report with automated framework V2.13.0

### ISSUE THREAD

**Issue by Sperez96** [zaproxy/zaproxy#7993]
### Describe the bug

Hi, 

I found a problem with version 2.13.0 of Owasp Zap using the automation framework. 

When i use the following config:

`
  - type: report
    name: JSON Extends Report
    parameters:
      template: traditional-json-plus
      theme: original
      reportDir: /Users/custom/Desktop/reports
      reportFile: example_report-json-plus
      reportTitle: ZAP Scanning Report
      reportDescription: ''
      displayReport: false
    risks:
      - info
      - low
      - medium
      - high
    confidences:
      - falsepositive
      - low
      - medium
      - high
      - confirmed
    sections: []
`

It return this error:
`   
Tarea report iniciada
   Tarea JSON Extends Report Fallo al generar el informe: Exception evaluating OGNL expression: "helper.legacyEscapeText(instance.param, true)" (template: "/Users/custom/Library/Application Support/ZAP/reports/traditional-json-plus/report.json" - line 25, col 41)
   Job report finished, time taken: 00:00:00
`
This was not happening with zap version 2.12.

For the other hand, it does not recognize the options of {risk: - info} and {confidence: -falsepositive}. Both options appear disabled when the automation plan is executed

### Steps to reproduce the behavior

1. Go to Automation.
2. imports an automation plan with a report job with the specified settings
3. Report is stopped with error

### Expected behavior

A file must be written with the same format as version 2.12

### Software versions

Owasp Zap proxy v 2.13.0

### Errors from the zap.log file

`2023-08-08 12:32:04,550 [ZAP-Automation] ERROR TemplateEngine - [THYMELEAF][ZAP-Automation] Exception processing template "/Users/custom/Library/Application Support/ZAP/reports/traditional-json-plus/report.json": Exception evaluating OGNL expression: "helper.legacyEscapeText(instance.param, true)" (template: "/Users/custom/Library/Application Support/ZAP/reports/traditional-json-plus/report.json" - line 25, col 41)
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "helper.legacyEscapeText(instance.param, true)" (template: "/Users/custom/Library/Application Support/ZAP/reports/traditional-json-plus/report.json" - line 25, col 41)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:199) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:104) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.processor.StandardUtextTagProcessor.doProcess(StandardUtextTagProcessor.java:87) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[?:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[?:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[?:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:222) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:222) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:222) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[?:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[?:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:434) ~[?:?]
	at org.zaproxy.addon.reports.automation.ReportJob.runJob(ReportJob.java:259) ~[?:?]
	at org.zaproxy.addon.automation.ExtensionAutomation.runPlan(ExtensionAutomation.java:366) ~[?:?]
	at org.zaproxy.addon.automation.ExtensionAutomation.lambda$runPlanAsync$3(ExtensionAutomation.java:392) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Instantiation of new objects and access to static classes or parameters is forbidden in this context
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.obtainComputedOGNLExpression(OGNLVariableExpressionEvaluator.java:215) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:132) ~[?:?]
	... 38 more`

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Delete the file `/Users/custom/Library/Application Support/ZAP/reports/traditional-json-plus/report.json` and try again.

**Comment by Sperez96** [comment]
It doesn't work, it returns the following error:
`Tarea report iniciada
   Tarea JSON Extends Report Fallo al generar el informe: An error happened during template parsing (template: "/Users/custom/Library/Application Support/ZAP/reports/traditional-json-plus/report.json")
   Job report finished, time taken: 00:00:00`

**Comment by thc202** [comment]
Provide the whole exception.

**Comment by Sperez96** [comment]
When restarting the computer, it seems that everything has worked correctly after deleting that file, so it would be solved

**Comment by thc202** [comment]
Thank you! We should still leave this open since the files should have been updated automatically.
