### ISSUE TITLE
Alert with empty description causes an error with High Level Report Sample

### ISSUE THREAD

**Issue by JanikkinaJ** [zaproxy/zaproxy#8071]
### Describe the bug

When I try to create a High level report Sample I get the error "Failed to generate Report: Exception evaluating OGNL expression: "#strings.arraySplit(alert.userObject.description, '\n')[0]" (template: "/home/user/.ZAP/reports/high-level-report/report.html" - line 253, col 10)" 

### Steps to reproduce the behavior

1. Download Zap on linux via the linux installer and use the default settings.
2. Run a scan on a target
3. click generate report and select the High level report sample
4. Generate the report

### Expected behavior

A report to generate.
I know this is just a sample report but I based another report template on parts of this report and therefore my (yet to be finished) template also doesn't work anymore.

### Software versions

Newest Zap installation via the Linux Installer. Reinstalled today to check if it was due to my Zap home directory.

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/27766253/eafcd935-fd18-4e8c-8a84-2e6768d3033a)

### Errors from the zap.log file

```
2023-09-14 15:46:42,817 [AWT-EventQueue-0] ERROR ReportDialog - Failed to generate a report using template org.zaproxy.addon.reports.Template@31b29d86
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "#strings.arraySplit(alert.userObject.description, '\n')[0]" (template: "/home/user/.ZAP/reports/high-level-report/report.html" - line 253, col 10)
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:199) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:104) ~[?:?]
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166) ~[?:?]
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138) ~[?:?]
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125) ~[?:?]
	at org.thymeleaf.standard.processor.StandardWithTagProcessor.doProcess(StandardWithTagProcessor.java:93) ~[?:?]
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[?:?]
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[?:?]
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[?:?]
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:282) ~[?:?]
	at org.thymeleaf.engine.Model.process(Model.java:290) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:368) ~[?:?]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:294) ~[?:?]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[?:?]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[?:?]
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[?:?]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[?:?]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072) ~[?:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:437) ~[?:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:501) ~[?:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:428) ~[zap-2.13.0.jar:2.13.0]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:411) ~[zap-2.13.0.jar:2.13.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6620) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3398) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6385) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2266) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:4995) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2324) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4827) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2310) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2780) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4827) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:400) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:747) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:400) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:744) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.reflect.Array.get(Native Method) ~[?:?]
	at ognl.ArrayPropertyAccessor.getProperty(ArrayPropertyAccessor.java:91) ~[?:?]
	at ognl.OgnlRuntime.getProperty(OgnlRuntime.java:3344) ~[?:?]
	at ognl.ASTProperty.getValueBody(ASTProperty.java:121) ~[?:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[?:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[?:?]
	at ognl.ASTChain.getValueBody(ASTChain.java:141) ~[?:?]
	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212) ~[?:?]
	at ognl.SimpleNode.getValue(SimpleNode.java:258) ~[?:?]
	at ognl.Ognl.getValue(Ognl.java:586) ~[?:?]
	at ognl.Ognl.getValue(Ognl.java:550) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.executeExpression(OGNLVariableExpressionEvaluator.java:334) ~[?:?]
	at org.thymeleaf.standard.expression.OGNLVariableExpressionEvaluator.evaluate(OGNLVariableExpressionEvaluator.java:178) ~[?:?]
	... 61 more
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by JanikkinaJ** [comment]
Could this be due to the alert api update in commit [2377af14380d5085072f29359030e29f1bd38e5d](https://github.com/zaproxy/zaproxy/commit/2377af14380d5085072f29359030e29f1bd38e5d) ?

**Comment by thc202** [comment]
That's unrelated code.

**Comment by JanikkinaJ** [comment]
Sorry. 
I don't think I quite understand how the reports actually access the info from the alerts as the creating [reports guide](https://www.zaproxy.org/docs/desktop/addons/report-generation/create/#alerttree) points to classes from version 2.10 that don't exist with the same name in version 2.13.

**Comment by JanikkinaJ** [comment]
I Have a custom Alert which does not have a description which I now can see caused the issue

**Comment by JanikkinaJ** [comment]
Removing the Alert fixed the Issue.

**Comment by thc202** [comment]
We should still fix the report template.

**Comment by kingthorin** [comment]
Do we already have that handling somewhere? If not I suspect there are a number of fields and templates it should be applied to.

**Comment by thc202** [comment]
This is the only case where it's failing.

**Comment by kingthorin** [comment]
Okay, tks.
