### ISSUE TITLE
Can't generate root CA certificate

### ISSUE THREAD

**Issue by tyluoxl** [zaproxy/zaproxy#8128]
I use the ZAProxy 2.13 which on Ubunto 20.04, but I can't generate root CA certificate, there's nothing when I click the generate, below please find the error log. I tried restore the Java, but still can't do it.  Any expert can support this case? thanks in advance.

```
java -version
openjdk version "13.0.7" 2021-04-20
OpenJDK Runtime Environment (build 13.0.7+5-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 13.0.7+5-Ubuntu-0ubuntu120.04, mixed mode)
```
log error:
```
2023-10-13 16:31:20,901 [AWT-EventQueue-0] ERROR ServerCertificatesOptionsPanel - An error occurred while generating Root CA certificate
org.zaproxy.addon.network.internal.cert.GenerationException: An error occurred while generating the root CA certificate:
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStore(CertificateUtils.java:151) ~[?:?]
	at org.zaproxy.addon.network.ServerCertificatesOptionsPanel$RootCaCertificatePanel.generateRootCaCert(ServerCertificatesOptionsPanel.java:276) ~[?:?]
	at org.zaproxy.addon.network.ServerCertificatesOptionsPanel$RootCaCertificatePanel.lambda$new$0(ServerCertificatesOptionsPanel.java:149) ~[?:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2762) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) [?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) [?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:?]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:312) ~[?:?]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:?]
	at java.awt.Dialog.show(Dialog.java:1070) ~[?:?]
	at java.awt.Component.show(Component.java:1716) ~[?:?]
	at java.awt.Component.setVisible(Component.java:1663) ~[?:?]
	at java.awt.Window.setVisible(Window.java:1021) ~[?:?]
	at java.awt.Dialog.setVisible(Dialog.java:1005) ~[?:?]
	at org.parosproxy.paros.extension.AbstractDialog.setVisible(AbstractDialog.java:136) ~[zap-2.13.0.jar:2.13.0]
	at org.parosproxy.paros.view.AbstractParamDialog.showDialog(AbstractParamDialog.java:445) ~[zap-2.13.0.jar:2.13.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:75) ~[zap-2.13.0.jar:2.13.0]
	at org.parosproxy.paros.control.MenuToolsControl.options(MenuToolsControl.java:66) ~[zap-2.13.0.jar:2.13.0]
	at org.zaproxy.zap.view.MainToolbarPanel$8.actionPerformed(MainToolbarPanel.java:462) ~[zap-2.13.0.jar:2.13.0]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) ~[?:?]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) ~[?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) ~[?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297) ~[?:?]
	at java.awt.Component.processMouseEvent(Component.java:6635) ~[?:?]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3342) ~[?:?]
	at java.awt.Component.processEvent(Component.java:6400) ~[?:?]
	at java.awt.Container.processEvent(Container.java:2263) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5011) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2321) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918) ~[?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547) ~[?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488) ~[?:?]
	at java.awt.Container.dispatchEventImpl(Container.java:2307) ~[?:?]
	at java.awt.Window.dispatchEventImpl(Window.java:2762) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4843) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:745) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:743) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: org.zaproxy.addon.network.internal.cert.GenerationException: Errors during assembling root CA.
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStoreImpl(CertificateUtils.java:212) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStore(CertificateUtils.java:149) ~[?:?]
	... 85 more
Caused by: java.security.KeyStoreException: Key protection algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:700) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:597) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111) ~[?:?]
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1167) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createKeyStore(CertificateUtils.java:354) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStoreImpl(CertificateUtils.java:210) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStore(CertificateUtils.java:149) ~[?:?]
	... 85 more
Caused by: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
	at sun.security.pkcs12.PKCS12KeyStore.encryptPrivateKey(PKCS12KeyStore.java:934) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:637) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:597) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111) ~[?:?]
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1167) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createKeyStore(CertificateUtils.java:354) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStoreImpl(CertificateUtils.java:210) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStore(CertificateUtils.java:149) ~[?:?]
	... 85 more
Caused by: java.security.NoSuchAlgorithmException: unrecognized algorithm name: PBEWithSHA1AndDESede
	at sun.security.x509.AlgorithmId.get(AlgorithmId.java:448) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.mapPBEAlgorithmToOID(PKCS12KeyStore.java:951) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.encryptPrivateKey(PKCS12KeyStore.java:908) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:637) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:597) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111) ~[?:?]
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1167) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createKeyStore(CertificateUtils.java:354) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStoreImpl(CertificateUtils.java:210) ~[?:?]
	at org.zaproxy.addon.network.internal.cert.CertificateUtils.createRootCaKeyStore(CertificateUtils.java:149) ~[?:?]
	... 85 more
```

**Comment by psiinon** [comment]
Can you try again with ZAP 2.14.0 - thats the latest release, and the only one we support.

**Comment by thc202** [comment]
I'd also suggest use a LTS Java version, (e.g 11, 17, 21).

**Comment by tyluoxl** [comment]
Dear 

> Can you try again with ZAP 2.14.0 - thats the latest release, and the only one we support.

I've installed ZAP 2.14.0 as well, but have the same issue when generate root CA

**Comment by thc202** [comment]
The problem would be in the JRE not ZAP, did you try use a newer Java version? The one you are using is from 2021.

**Comment by tyluoxl** [comment]
> I'd also suggest use a LTS Java version (e.g. 11, 17, 21).

Yes, after I update Java 17, it can generate the root CA, thanks very much!

**Comment by kingthorin** [comment]
Thanks for letting us know.
