### ISSUE TITLE
Browsing support ineffective on Linux

### ISSUE THREAD

**Issue by IlabSentuser** [zaproxy/zaproxy#8129]
### Describe the bug

When trying to access online features like the marketplace, videos, website, etc. No action is visually carried out, in the logs the following error is seen:
```
2023-10-17 10:19:55,395 [AWT-EventQueue-0] ERROR DesktopUtils - The BROWSE action is not supported on the current platform!
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.awt.Desktop.checkActionSupport(Desktop.java:381) ~[?:?]
	at java.awt.Desktop.browse(Desktop.java:531) ~[?:?]
	at org.zaproxy.zap.utils.DesktopUtils.openUrlInBrowser(DesktopUtils.java:43) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.utils.DesktopUtils.openUrlInBrowser(DesktopUtils.java:55) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.utils.DesktopUtils.openUrlInBrowser(DesktopUtils.java:65) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.quickstart.QuickStartPanel.lambda$showNews$4(QuickStartPanel.java:324) ~[?:?]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) ~[?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314) ~[?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407) ~[?:?]
       (...)
```
This is likely to occur as the usage of the Desktop class is not properly supported on all platforms, in several linux distributions it is not, for example Archlinux based ones, although I think it is more likely related to the desktop environment than the distribution itself.

There are several possible fixes to this that I can think about, I do not know if they are applicable to zap though. But I think that at the very least a verification for support should be made and if the current platform does not support this method use an alternative, for example use ```xdg-open``` or equivalents, maybe using the selenium configured browser if this is not possible? At the very least providing an informative message on the UI about the issue would be appropriate instead of failing silently.

### Steps to reproduce the behavior

1. On Archlinux KDE/Plasma
2. Open ZAP
3. Navigate to the online tab
4. Select any option there, like Marketplace for example.

### Expected behavior

A web browser opens on the corresponding URI

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=alertFilters, version=18.0.0],
[id=ascanrules, version=58.0.0], [id=authhelper,
version=0.10.0], [id=automation, version=0.33.0],
[id=bruteforce, version=15.0.0], [id=callhome,
version=0.8.0], [id=commonlib, version=1.18.0],
[id=custompayloads, version=0.12.0], [id=database,
version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0], [id=exim,
version=0.7.0], [id=formhandler, version=6.5.0], [id=fuzz,
version=13.12.0], [id=gettingStarted, version=16.0.0],
[id=graaljs, version=0.5.0], [id=graphql, version=0.20.0],
[id=help, version=17.0.0], [id=hud, version=0.18.0],
[id=invoke, version=14.0.0], [id=network, version=0.12.0],
[id=oast, version=0.17.0], [id=onlineMenu, version=12.0.0],
[id=openapi, version=37.0.0], [id=postman, version=0.2.0],
[id=pscanrules, version=52.0.0], [id=quickstart,
version=43.0.0], [id=replacer, version=15.0.0], [id=reports,
version=0.26.0], [id=requester, version=7.4.0], [id=retest,
version=0.8.0], [id=retire, version=0.26.0], [id=reveal,
version=7.0.0], [id=scripts, version=42.0.0], [id=selenium,
version=15.15.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.17.0], [id=tips,
version=12.0.0], [id=webdriverlinux, version=64.0.0],
[id=websocket, version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Linux
Architecture: amd64
Java Version: N/A 21
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/<REDACTED>/.ZAP/
ZAP Installation Directory: /usr/share/zaproxy/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Errors from the zap.log file

[zap.log](https://github.com/zaproxy/zaproxy/files/12926573/zap.log)

### Would you like to help fix this issue?

- [X] Yes

**Comment by IlabSentuser** [comment]
Hello @thc202 , I do not want to pretend to know better, but while informing of the issue is an awesome step in the right direction, I think that still not being able to use several of the app features just because of using a single way of opening URIs is somewhat a bug. After all ZAP is cross platform and some of its functionalities are not working as expected (even though they could with a little fiddling) in some of those platforms, at least that seems to me from an users perspective.

**Comment by psiinon** [comment]
We're relying on Java to launch the browser.
I guess in this case we could use selenium and not proxy through ZAP?

**Comment by thc202** [comment]
> using a single way of opening URIs is somewhat a bug.

No, it's not, the bug is that the platform is not supported.

> even though they could with a little fiddling

Instead of little fiddling in all Java applications, it would be better to raise an issue in your OS/DE/JRE/?? provider for them to support the action. (This works fine in other Linux distros, e.g. Ubuntu based). To be clear I don't know where in the chain is it failing, maybe it's just a missing config in your DE.

**Comment by alqomar** [comment]
Hi, I'm unable to reproduce. My Online menu work as expected (Zaproxy open Firefox & related URL).

I tried with Java 11 / 21 : all works
Install/uninstall openjfx : all works
System Settings > Applications > Default Applications > Web browser > Firefox/Chromium/FirefoxDev : all works
Uninstall xdg-desktop-portal & xdg-desktop-portal-kde : still work 
Delete all browsers path in Zaproxy > Options > Selenium : still work


OS: Archlinux KDE/Plasma

$ archlinux-java status
Available Java environments:
  java-17-openjdk
  java-21-openjdk (default)

$ pacman -Qs zaproxy
local/zaproxy 2.14.0-1

**Comment by alqomar** [comment]
This turns out to be a known issue:
from https://wiki.archlinux.org/title/Java#Java_applications_cannot_open_external_links

If a Java application is not able to open a link to, for example, your web browser, install gvfs. This is required by the Desktop.Action.BROWSE method. See [1] An application printing the error message java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform! is a solid indicator for this problem.

[1] https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1574879/comments/2


I uninstalled gvfs and the online menu did not work, with Zaproxy logs showing `[AWT-EventQueue-0] ERROR org.zaproxy.zap.utils.DesktopUtils - The BROWSE action is not supported on the current platform!`

After installing gvfs, the online menu started working again (Zaproxy opened Firefox and the related URL).
