### ISSUE TITLE
Non-English Character Handling Issue in the Request Tab (like Korean)

### ISSUE THREAD

**Issue by hahwul** [zaproxy/zaproxy#8155]
### Describe the bug

Hi ZAP :D
I'm having an issue with handling Korean in ZAP's Request tab.
I think it would be an encoding/decoding problem for non-English speaking countries. 
> Both Korean(`e.g 한글`) and Japanese(`e.g ひらがな`) are replaced by the same (`???`)

## When I send it
- When there is Korean in the URL Query: It results in an error.
- When there is Korean in the Header: It's processed correctly.
- When there is Korean in the Body: It's processed correctly, but it's displayed as `???`.

https://github.com/zaproxy/zaproxy/assets/13212227/b9d58a12-40e4-4d63-ab30-40315add5602

## When I read it
When viewing Req/Res in the History tab, Korean text is displayed as `???` in Req under specific conditions, regardless of whether it's in Form or JSON. (I don't know the conditions 😭)

**Normal case (httpie to zaproxy)**
![](https://github.com/zaproxy/zaproxy/assets/13212227/22ae8035-4519-4010-8275-6edb352c7f33)

**Broken text case (mobile app to X)**
Original
```json
{"message": "ㅋㅋㅋㅋㅋㅋㅋㅋㅋ"}
```

to ZAP
```json
{"message" : "ããããããããã"}
```
![](https://github.com/zaproxy/zaproxy/assets/13212227/75ba2d2b-3367-49ab-8fc6-bb780804692b)

to Caido
```json
{"message": "ㅋㅋㅋㅋㅋㅋㅋㅋㅋ"}
```

![](https://github.com/zaproxy/zaproxy/assets/13212227/11737d53-7b85-4ad7-8c8d-ae3b0a4a9d32)

### Steps to reproduce the behavior

1. `Open Manual Request Editor`
2. Send this
```
POST https://www.hahwul.com?query= HTTP/1.1
host: www.hahwul.com
header: 한글

body=한글
```

### Expected behavior

- I'd like Korean to be displayed correctly in the Request tab, just like in the Response tab.
- Instead of URL Query error, encoding like `%ED%95%9C%EA%B8%80` is likely to be required.

### Software versions

ZAP
Version: 2.14.0

Installed Add-ons: [[id=accessControl, version=9.0.0],
[id=alertFilters, version=18.0.0], [id=allinonenotes,
version=2.0.0], [id=amf, version=3.0.0], [id=ascanrules,
version=58.0.0], [id=ascanrulesAlpha, version=44.0.0],
[id=ascanrulesBeta, version=48.0.0],
[id=attacksurfacedetector, version=1.1.4], [id=authhelper,
version=0.10.0], [id=authstats, version=2.0.0],
[id=automation, version=0.33.0], [id=beanshell,
version=7.0.0], [id=browserView, version=6.0.0],
[id=bruteforce, version=15.0.0], [id=callgraph,
version=5.0.0], [id=callhome, version=0.8.0], [id=client,
version=0.3.0], [id=commonlib, version=1.18.0],
[id=communityScripts, version=17.0.0], [id=custompayloads,
version=0.12.0], [id=database, version=0.3.0], [id=dev,
version=0.3.0], [id=diff, version=14.0.0],
[id=directorylistv1, version=7.0.0],
[id=directorylistv2_3_lc, version=4.0.0], [id=domxss,
version=18.0.0], [id=encoder, version=1.4.0],
[id=evalvillain, version=0.3.0], [id=exim, version=0.7.0],
[id=fileupload, version=1.2.1], [id=formhandler,
version=6.5.0], [id=fuzz, version=13.12.0],
[id=gettingStarted, version=16.0.0], [id=graaljs,
version=0.5.0], [id=graphql, version=0.20.0], [id=groovy,
version=3.1.0], [id=help, version=17.0.0], [id=highlighter,
version=8.0.0], [id=hud, version=0.18.0],
[id=imagelocationscanner, version=4.0.0], [id=invoke,
version=14.0.0], [id=jruby, version=8.0.0], [id=jsonview,
version=3.0.0], [id=jwt, version=1.0.3], [id=jython,
version=13.0.0], [id=kotlin, version=1.1.0], [id=maplocal,
version=0.0.1], [id=neonmarker, version=1.6.0], [id=network,
version=0.12.0], [id=oast, version=0.17.0], [id=onlineMenu,
version=12.0.0], [id=openapi, version=38.0.0],
[id=paramdigger, version=0.2.0], [id=plugnhack,
version=13.0.0], [id=portscan, version=10.0.0], [id=postman,
version=0.2.0], [id=pscanrules, version=52.0.0],
[id=pscanrulesAlpha, version=41.0.0], [id=pscanrulesBeta,
version=35.0.0], [id=reflect, version=0.0.11],
[id=regextester, version=2.0.0], [id=replacer,
version=15.0.0], [id=reports, version=0.26.0],
[id=requester, version=7.4.0], [id=retest, version=0.8.0],
[id=retire, version=0.26.0], [id=reveal, version=7.0.0],
[id=revisit, version=5.0.0], [id=saml, version=10.0.0],
[id=scriptgen, version=5.0.0], [id=scripts, version=42.0.0],
[id=selenium, version=15.15.0], [id=sequence,
version=7.0.0], [id=soap, version=20.0.0], [id=spider,
version=0.7.0], [id=spiderAjax, version=23.17.0],
[id=sqliplugin, version=15.0.0], [id=sse, version=12.0.0],
[id=tips, version=12.0.0], [id=tokengen, version=15.0.0],
[id=treetools, version=8.0.0], [id=viewstate,
version=3.0.0], [id=wappalyzer, version=21.26.0],
[id=webdrivermacos, version=64.0.0], [id=websocket,
version=30.0.0], [id=zest, version=42.0.0]]

Operating System: Mac OS X
Architecture: x86_64
Java Version: Eclipse Adoptium 11.0.20.1
System's Locale: ko_KR
Display Locale: en_GB
Format Locale: en_GB
Default Charset: UTF-8
ZAP Home Directory: /Users/hahwul/Library/Application Support/ZAP/
ZAP Installation Directory: /Applications/ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Darcula (com.formdev.flatlaf.FlatDarculaLaf)

### Errors from the zap.log file

zap.log
```
org.apache.commons.httpclient.URIException: Invalid query
	at org.apache.commons.httpclient.URI.parseUriReference(URI.java:2072) ~[zap-2.14.0.jar:2.14.0]
	at org.apache.commons.httpclient.URI.<init>(URI.java:183) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.network.HttpRequestHeader.parseURI(HttpRequestHeader.java:672) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.network.HttpRequestHeader.parse(HttpRequestHeader.java:465) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:293) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.network.HttpRequestHeader.setMessage(HttpRequestHeader.java:314) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.network.HttpRequestHeader.<init>(HttpRequestHeader.java:193) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.network.HttpMessage.setRequestHeader(HttpMessage.java:405) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.httppanel.view.impl.models.http.request.RequestHeaderStringHttpPanelViewModel.setData(RequestHeaderStringHttpPanelViewModel.java:52) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.httppanel.view.syntaxhighlight.HttpPanelSyntaxHighlightTextView.save(HttpPanelSyntaxHighlightTextView.java:193) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.httppanel.component.HttpPanelComponentViewsManager.save(HttpPanelComponentViewsManager.java:300) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.httppanel.component.split.request.RequestSplitComponent.save(RequestSplitComponent.java:195) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.httppanel.HttpPanel.saveData(HttpPanel.java:349) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.requester.MessageEditorPanel.sendButtonTriggered(MessageEditorPanel.java:134) ~[?:?]
	at org.zaproxy.addon.requester.MessageEditorPanel.lambda$getBtnSend$0(MessageEditorPanel.java:178) ~[?:?]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [?:?]
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) [?:?]
	at java.awt.Component.processMouseEvent(Unknown Source) [?:?]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:?]
	at java.awt.Component.processEvent(Unknown Source) [?:?]
	at java.awt.Container.processEvent(Unknown Source) [?:?]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:?]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.EventQueue$4.run(Unknown Source) [?:?]
	at java.awt.EventQueue$4.run(Unknown Source) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue$5.run(Unknown Source) [?:?]
	at java.awt.EventQueue$5.run(Unknown Source) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
[AWT-EventQueue-0] WARN  RequestHeaderStringHttpPanelViewModel - Could not Save Header: POST https://www.hahwul.com?query=한글 HTTP/1.1
```

If replaced with '???', no log is left

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
Probably same as: https://github.com/zaproxy/zaproxy/issues/2794

**Comment by thc202** [comment]
I don't think it's that one, this seems to be about the charset (i.e. #6656).
