### ISSUE TITLE
ConcurrentModificationException in Scan rule 'Session Management Response Identified'

### ISSUE THREAD

**Issue by double16** [zaproxy/zaproxy#8187]
### Describe the bug

Many instances of this in `zap.log` for different record numbers.
```
2023-11-13 06:04:25,573 [ZAP-PassiveScan-4] ERROR PassiveScanTask - Scan rule 'Session Management Response Identified' failed on record 124740 from History table: GET ---redacted--
java.util.ConcurrentModificationException: null
        at java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1873) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at org.zaproxy.addon.authhelper.AuthUtils.containsSessionToken(AuthUtils.java:641) ~[?:?]
        at org.zaproxy.addon.authhelper.SessionDetectionScanRule.scanHttpResponseReceive(SessionDetectionScanRule.java:88) ~[?:?]
        at org.zaproxy.zap.extension.pscan.PassiveScanTask.run(PassiveScanTask.java:148) [zap-D-2023-11-07.jar:D-2023-11-07]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

### Steps to reproduce the behavior

Crawl site with session management set to 'auto-detect'.

### Expected behavior

No exceptions :)

### Software versions

ZAP weekly 2023-11-07

### Would you like to help fix this issue?

- [ ] Yes

**Comment by pvuappsecfasttrack** [comment]
I just wonder if we have a fix for this bug, also what is the impact with the active scan (attack)?

**Comment by psiinon** [comment]
Potential impact: the session detection passive scan rule might not identify some sessions https://www.zaproxy.org/docs/alerts/10112/
If you dont use this rule then no impact.

**Comment by thc202** [comment]
Though as the traffic is scanned the session would be picked up later eventually(?).
