### ISSUE TITLE
Import of OpenAPI definition might hit reading/parsing size limits

### ISSUE THREAD

**Issue by megalucio** [zaproxy/zaproxy#8193]
### Describe the bug

When importing a very big openapi definition fail I get `com.fasterxml.jackson.databind.JsonMappingException`. See above. 

Notice that when pointing directly to the url of the file, the import results successful

### Steps to reproduce the behavior

1. Download openapi definition https://raw.githubusercontent.com/commercetools/commercetools-api-reference/main/oas/api/openapi.yaml
2. Open OWASP ZAP
3. Menu --> Import --> Import an OpenAPI definition --> Select downloaded file

### Expected behavior

It should work the same way as if importing the file using its url, which actually works.

### Software versions

2.14.0

### Errors from the zap.log file
```
com.fasterxml.jackson.databind.JsonMappingException: TextBuffer overrun: size reached (2147483648) exceeds maximum of 2147483647 (through reference chain: io.swagger.v3.oas.models.OpenAPI["paths"]->io.swagger.v3.oas.models.Paths["/ignacio-test-4/in-store/key={storeKey}/orders"]->io.swagger.v3.oas.models.PathItem["get"]->io.swagger.v3.oas.models.Operation["responses"]->io.swagger.v3.oas.models.responses.ApiResponses["200"]->io.swagger.v3.oas.models.responses.ApiResponse["content"]->io.swagger.v3.oas.models.media.Content["application/json"]->io.swagger.v3.oas.models.media.MediaType["schema"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["results"]->io.swagger.v3.oas.models.media.ArraySchema["items"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["quote"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["obj"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["stagedQuote"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["obj"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["quoteRequest"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["obj"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["lineItems"]->io.swagger.v3.oas.models.media.ArraySchema["items"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["productType"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["obj"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["lastModifiedBy"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["customer"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["obj"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["addresses"]->io.swagger.v3.oas.models.media.ArraySchema["items"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["custom"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["type"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["obj"]->io.swagger.v3.oas.models.media.Schema["properties"]->java.util.LinkedHashMap["lastModifiedBy"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:871)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:41)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at io.swagger.v3.core.jackson.MediaTypeSerializer.serialize(MediaTypeSerializer.java:38)
	at io.swagger.v3.core.jackson.MediaTypeSerializer.serialize(MediaTypeSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:1150)
	at io.swagger.v3.core.jackson.ApiResponsesSerializer.serialize(ApiResponsesSerializer.java:33)
	at io.swagger.v3.core.jackson.ApiResponsesSerializer.serialize(ApiResponsesSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:1150)
	at io.swagger.v3.core.jackson.PathsSerializer.serialize(PathsSerializer.java:33)
	at io.swagger.v3.core.jackson.PathsSerializer.serialize(PathsSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:732)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1140)
	at io.swagger.v3.core.util.Json.pretty(Json.java:24)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinitionV2(ExtensionOpenApi.java:348)
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinition(ExtensionOpenApi.java:318)
	at org.zaproxy.zap.extension.openapi.ImportDialog.importDefinition(ImportDialog.java:335)
	at org.zaproxy.zap.extension.openapi.ImportDialog.lambda$getImportButton$4(ImportDialog.java:249)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: TextBuffer overrun: size reached (2147483648) exceeds maximum of 2147483647
	at com.fasterxml.jackson.core.util.TextBuffer._reportBufferOverflow(TextBuffer.java:1165)
	at com.fasterxml.jackson.core.util.TextBuffer.expand(TextBuffer.java:1099)
	at com.fasterxml.jackson.core.util.TextBuffer.append(TextBuffer.java:783)
	at com.fasterxml.jackson.core.io.SegmentedStringWriter.write(SegmentedStringWriter.java:63)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._flushBuffer(WriterBasedJsonGenerator.java:2060)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeRaw(WriterBasedJsonGenerator.java:618)
	at com.fasterxml.jackson.core.util.DefaultIndenter.writeIndentation(DefaultIndenter.java:94)
	at com.fasterxml.jackson.core.util.DefaultPrettyPrinter.beforeObjectEntries(DefaultPrettyPrinter.java:303)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writePPFieldName(WriterBasedJsonGenerator.java:371)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator._writeFieldName(WriterBasedJsonGenerator.java:172)
	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeFieldName(WriterBasedJsonGenerator.java:155)
	at com.fasterxml.jackson.core.JsonGenerator.writeStringField(JsonGenerator.java:2187)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:47)
	at io.swagger.v3.core.jackson.SchemaSerializer.serialize(SchemaSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	... 222 more
```

### Would you like to help fix this issue?

- [X] Yes

**Comment by Sperez96** [comment]
Hi, 
I have a similar issue when loading large openapi documents using the authentication framework. In my case the error is:
`
org.parosproxy.paros.db.DatabaseException: java.sql.SQLDataException: data exception: data of type text, truncated on the right; size limit: 67108864 table: OPENAPI_SPECS column: DEFINITION
`
Could it be the same issue?

**Comment by kingthorin** [comment]
Not the same but similar. What version of the OpenAPI add-on are you using? Is your Definition really more than 67MB?

**Comment by Sperez96** [comment]
The size of my openapi file is 315 KB and the number of lines is 6933. OpenAPI support version is 38.0.0

**Comment by kingthorin** [comment]
Are you able to share the definition?

**Comment by thc202** [comment]
Better continue this in #7876, though the cause of the issue is known.

**Comment by thc202** [comment]
Mentioned in #8281, other exception might be:
```
com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.
```

**Comment by megalucio** [comment]
This also happens with the automation framework

**Comment by psiinon** [comment]
No surprise there, its the same underlying code 😁

**Comment by megalucio** [comment]
So, now that the PR is merged, when will the new version of the addon be released? Is there a process to request this?

**Comment by thc202** [comment]
There's no formal process, one just needs to ask/poke.

**Comment by kingthorin** [comment]
The add-on with the fix has now been released.

**Comment by megalucio** [comment]
Thanks very much!

**Comment by kingthorin** [comment]
@megalucio please give it a try and let us know how it goes.

**Comment by megalucio** [comment]
Absolutely, will wait for zap-nightly and give it a try tomorrow

**Comment by megalucio** [comment]
The fix worked for me, we are now able to scan api even if the full resource definition is too big.

**Comment by kingthorin** [comment]
Thanks for letting us know

**Comment by thc202** [comment]
Please keep it open since what was merged is a workaround.
