### ISSUE TITLE
NumberFormatException when context file contains alert filter with dash in Alert ID

### ISSUE THREAD

**Issue by justinschw** [zaproxy/zaproxy#8204]
### Describe the bug

This behavior did not exist in 2.11.1. We recently upgraded to 2.14.0 and it began happening.

We have a zap context file with the following alert filter:
```
<filter>true;10055-6;0;XigoPyEvb2JqZWN0c3RvcmFnZSkuKSok;true;;false;;false;;false;</filter>
```
This used to work, now I get a stack trace:
```
09:20:28  [info] [zap] 10892 [ZAP-IO-Server-1-1] ERROR org.zaproxy.zap.extension.alertFilters.AlertFilter - An error occurred while decoding alertFilter from: true;10055-6;0;XigoPyEvb2JqZWN0c3RvcmFnZSkuKSok;true;;false;;false;;false;
java.lang.NumberFormatException: For input string: "10055-6"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:784) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.AlertFilter.decode(AlertFilter.java:344) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.importContextData(ExtensionAlertFilters.java:351) ~[?:?]
	at org.parosproxy.paros.model.Model.importContext(Model.java:576) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1632) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1537) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:538) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to reproduce the behavior

1. Create a context file with an alert filter that references an alert ID with a dash (-) in it, like the example I provided
2. Import this context file to ZAP

### Expected behavior

All valid alert IDs should be accepted

### Software versions

2.14.0

### Errors from the zap.log file
```
ERROR org.zaproxy.zap.extension.alertFilters.AlertFilter - An error occurred while decoding alertFilter from: true;10055-6;0;XigoPyEvb2JqZWN0c3RvcmFnZSkuKSok;true;;false;;false;;false;
java.lang.NumberFormatException: For input string: "10055-6"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:784) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.AlertFilter.decode(AlertFilter.java:344) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.importContextData(ExtensionAlertFilters.java:351) ~[?:?]
	at org.parosproxy.paros.model.Model.importContext(Model.java:576) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1632) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1537) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:538) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
ERROR org.zaproxy.zap.extension.alertFilters.AlertFilter - An error occurred while decoding alertFilter from: true;10055-5;0;XigoPyEvb2JqZWN0c3RvcmFnZSkuKSok;true;;false;;false;;false;
java.lang.NumberFormatException: For input string: "10055-5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:784) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.AlertFilter.decode(AlertFilter.java:344) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.importContextData(ExtensionAlertFilters.java:351) ~[?:?]
	at org.parosproxy.paros.model.Model.importContext(Model.java:576) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1632) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1537) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:538) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
ERROR org.zaproxy.zap.extension.alertFilters.AlertFilter - An error occurred while decoding alertFilter from: true;10055-4;0;XigoPyEvb2JqZWN0c3RvcmFnZSkuKSok;true;;false;;false;;false;
java.lang.NumberFormatException: For input string: "10055-4"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:784) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.AlertFilter.decode(AlertFilter.java:344) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.importContextData(ExtensionAlertFilters.java:351) ~[?:?]
	at org.parosproxy.paros.model.Model.importContext(Model.java:576) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1632) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1537) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:538) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

ERROR org.zaproxy.zap.extension.alertFilters.AlertFilter - An error occurred while decoding alertFilter from: true;10055-3;0;XigoPyEvb2JqZWN0c3RvcmFnZSkuKSok;true;;false;;false;;false;
java.lang.NumberFormatException: For input string: "10055-3"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:784) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.AlertFilter.decode(AlertFilter.java:344) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.importContextData(ExtensionAlertFilters.java:351) ~[?:?]
	at org.parosproxy.paros.model.Model.importContext(Model.java:576) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1632) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1537) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:538) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

ERROR org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters - Unable to persist AlertFilters
java.lang.NullPointerException: Cannot invoke "org.zaproxy.zap.extension.alertFilters.AlertFilter.isEnabled()" because "alertFilter" is null
	at org.zaproxy.zap.extension.alertFilters.AlertFilter.encode(AlertFilter.java:294) ~[?:?]
	at org.zaproxy.zap.extension.alertFilters.ExtensionAlertFilters.persistContextData(ExtensionAlertFilters.java:327) ~[?:?]
	at org.parosproxy.paros.model.Model.saveContext(Model.java:556) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.saveContext(Session.java:1306) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1637) ~[zap-2.14.0.jar:2.14.0]
	at org.parosproxy.paros.model.Session.importContext(Session.java:1537) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.ContextAPI.handleApiAction(ContextAPI.java:284) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:538) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
Seems you are using different versions of the Alert Filters add-on, creating a context with a newer version but using an older one when importing.

**Comment by thc202** [comment]
Closing, the solution is to use the same version (preferably, the latest) in both cases.
