### ISSUE TITLE
Bad request to API endpoint

### ISSUE THREAD

**Issue by alchu4n** [zaproxy/zaproxy#8207]
### Describe the bug

189457 [ZAP-IO-Server-1-1] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/spider/action/excludeFromScan/] from [172.17.0.1]:

org.zaproxy.zap.extension.api.ApiException: MISSING_PARAMETER (regex)

### Steps to reproduce the behavior

system: ubuntu 
install: docker run -u zap -p 8080:8080 -i softwaresecurityproject/zap-stable zap-x.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=11111111

![image](https://github.com/zaproxy/zaproxy/assets/97670155/8c6104c1-584c-49ea-b617-28adcf14f401)

error info 

```
189457 [ZAP-IO-Server-1-1] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/spider/action/excludeFromScan/] from [172.17.0.1]:
org.zaproxy.zap.extension.api.ApiException: MISSING_PARAMETER (regex)
	at org.zaproxy.zap.extension.api.API.validateMandatoryParams(API.java:681) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:534) ~[zap-2.14.0.jar:2.14.0]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:111) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:85) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:70) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [network-beta-0.12.0.zap:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Expected behavior

i try some ways but ....

### Software versions

last

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/97670155/9478185e-5bd9-4ff1-885d-c63678517ffe)

### Would you like to help fix this issue?

- [ ] Yes

**Comment by alchu4n** [comment]
errorr
