### ISSUE TITLE
ZAP hanged when creating new session after completed autoscan of specific site

### ISSUE THREAD

**Issue by JuraLys** [zaproxy/zaproxy#8266]
### Describe the bug

Run ZAP and complete autoscan of specific site armyinform.com.ua
Generate report and try to create new session

### Steps to reproduce the behavior

Run ZAP and complete autoscan of specific site armyinform.com.ua
Generate report and try to create new session
ZAP hangs

### Expected behavior

ZAP should create new session

### Software versions

ZAP 2.14 on updated Windows 10 x64

### Errors from the zap.log file

see java trace 
[java-hang-after-scan.txt](https://github.com/zaproxy/zaproxy/files/13763025/java-hang-after-scan.txt)

### Would you like to help fix this issue?

- [X] Yes

**Comment by JuraLys** [comment]
just reproduced with other site, see java trace
[java-hang-after-scan2.txt](https://github.com/zaproxy/zaproxy/files/13764329/java-hang-after-scan2.txt)

**Comment by thc202** [comment]
It's not hanged but it does not look like it should be doing that and much less in the EDT. Relevant stack trace:
```
"AWT-EventQueue-0" #34 [18512] prio=6 os_prio=0 cpu=1363703.12ms elapsed=24722.19s tid=0x000001bf7f365de0 nid=18512 runnable  [0x00000085209fd000]
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.readBytes0(java.base@21.0.1/Native Method)
        at java.io.RandomAccessFile.readBytes(java.base@21.0.1/RandomAccessFile.java:400)
        at java.io.RandomAccessFile.read(java.base@21.0.1/RandomAccessFile.java:434)
        at java.io.RandomAccessFile.readFully(java.base@21.0.1/RandomAccessFile.java:498)
        at org.hsqldb.persist.RAFile.read(Unknown Source)
        at org.hsqldb.persist.RAFileHybrid.read(Unknown Source)
        at org.hsqldb.persist.DataFileCache.readObject(Unknown Source)
        at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
        at org.hsqldb.persist.DataFileCache.get(Unknown Source)
        at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
        at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
        at org.hsqldb.index.IndexAVL.next(Unknown Source)
        at org.hsqldb.index.IndexAVL.next(Unknown Source)
        at org.hsqldb.index.IndexAVL$IndexRowIterator.getNextRow(Unknown Source)
        at org.hsqldb.index.IndexAVL$IndexRowIterator.next(Unknown Source)
        at org.hsqldb.RangeVariable$RangeIteratorMain.findNext(Unknown Source)
        at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
        at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
        at org.hsqldb.QuerySpecification.getResult(Unknown Source)
        at org.hsqldb.StatementQuery.getResult(Unknown Source)
        at org.hsqldb.StatementDMQL.execute(Unknown Source)
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
        at org.hsqldb.Session.execute(Unknown Source)
        - locked <0x000000070f543420> (a org.hsqldb.Session)
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source)
        - locked <0x00000007faa05b40> (a org.hsqldb.jdbc.JDBCPreparedStatement)
        at org.parosproxy.paros.db.paros.ParosTableHistory.getHistoryIdsByParams(ParosTableHistory.java:649)
        at org.parosproxy.paros.db.paros.ParosTableHistory.getHistoryIdsOfHistType(ParosTableHistory.java:597)
        at org.parosproxy.paros.extension.history.ExtensionHistory.getHistoryIds(ExtensionHistory.java:486)
        at org.parosproxy.paros.extension.history.ExtensionHistory.searchHistory(ExtensionHistory.java:501)
        - locked <0x0000000702bb9228> (a org.parosproxy.paros.extension.history.HistoryTableModel)
        at org.parosproxy.paros.extension.history.ExtensionHistory.sessionChanged(ExtensionHistory.java:855)
        at org.parosproxy.paros.extension.history.ExtensionHistory.sessionChanged(ExtensionHistory.java:282)
        at org.parosproxy.paros.extension.ExtensionLoader.sessionChangedAllPlugin(ExtensionLoader.java:566)
        at org.parosproxy.paros.control.Control.discardSession(Control.java:599)
        at org.parosproxy.paros.control.MenuFileControl.newSession(MenuFileControl.java:130)
        at org.parosproxy.paros.view.MainMenuBar$4.actionPerformed(MainMenuBar.java:293)
```

**Comment by JuraLys** [comment]
[ZAP-gui-hang-new-session.txt](https://github.com/zaproxy/zaproxy/files/14188738/ZAP-gui-hang-new-session.txt)
one more hang

**Comment by JuraLys** [comment]
see one more hang logs
[ZAP-gui-hang-when-creating-new-session.txt](https://github.com/zaproxy/zaproxy/files/14352548/ZAP-gui-hang-when-creating-new-session.txt)
[ZAP-logs.zip](https://github.com/zaproxy/zaproxy/files/14352549/ZAP-logs.zip)
