### ISSUE TITLE
OpenAPI import from URL timeout verbose/stacktrace

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zaproxy#8310]
### Describe the bug

When importing an OpenAPI definition from a URL, if the server is slow a read timeout may occur which is caught/handled by the add-on. But, the full stack trace is sent to stdout and the log.

Further when importing under certain conditions the job completes but the progress bar shows incomplete.

### Steps to reproduce the behavior

I was able to produce these situations while importing: https://api.domainsdb.info/v1/swagger.json

Of course there's no guarantee about it's performance (or lack thereof).

### Expected behavior

Catch the exception but maybe only spew the whole stack trace when logging is set to DEBUG.

> Further when importing under certain conditions the job completes but the progress bar shows incomplete.

In this scenario: Repeats should probably be counted as complete, while timeouts probably shouldn't.

### Software versions

Current dev.
OpenAPI Support v38.

### Screenshots

![image](https://github.com/zaproxy/zaproxy/assets/7570458/16c589c0-e87c-43a4-81be-5d2a8fe0e281)

### Errors from the zap.log file

```
68662 [ZAP-OpenAPI-UI-Import] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Read timed out
org.zaproxy.addon.network.common.ZapSocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1454) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1065) ~[?:?]
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149) ~[?:?]
	at org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280) ~[?:?]
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:247) ~[?:?]
	at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:54) ~[?:?]
	at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:299) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.ZapHttpRequestExecutor.execute(ZapHttpRequestExecutor.java:78) ~[?:?]
	at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218) ~[?:?]
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:712) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:178) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245) ~[?:?]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362) ~[?:?]
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendRateLimited(BaseHttpSender.java:413) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:382) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:350) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:306) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:277) ~[?:?]
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:233) ~[?:?]
	at org.parosproxy.paros.network.HttpSender.sendImpl(HttpSender.java:529) ~[main/:?]
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:361) ~[main/:?]
	at org.zaproxy.zap.extension.openapi.network.Requestor.getResponseBody(Requestor.java:88) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinitionV2(ExtensionOpenApi.java:249) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ExtensionOpenApi.importOpenApiDefinition(ExtensionOpenApi.java:234) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ImportDialog.importDefinition(ImportDialog.java:304) ~[?:?]
	at org.zaproxy.zap.extension.openapi.ImportDialog.lambda$getImportButton$4(ImportDialog.java:249) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Output tab output:
```
Failed to access URL: https://api.domainsdb.info/v1/domains/updates/deleted?api_key=api_key&date=date&page=page&limit=50 : org.zaproxy.addon.network.common.ZapSocketTimeoutException : Read timed out
Failed to access URL: https://api.domainsdb.info/v1/domains/updates/deleted/download?api_key=api_key&date=date : org.zaproxy.addon.network.common.ZapSocketTimeoutException : Read timed out
Failed to access URL: https://api.domainsdb.info/v1/info/tld/ : org.zaproxy.addon.network.common.ZapSocketTimeoutException : Read timed out
attribute paths.'/domains/tld/{zone_id}/download'(get).operationId is repeated
attribute paths.'/domains/tld/{zone_id}/search'(get).operationId is repeated
attribute paths.'/domains/updates/added'(get).operationId is repeated
attribute paths.'/domains/updates/added/download'(get).operationId is repeated
attribute paths.'/domains/updates/deleted'(get).operationId is repeated
attribute paths.'/domains/updates/deleted/download'(get).operationId is repeated
attribute paths.'/domains/updates/list'(get).operationId is repeated
attribute paths.'/info/tld/'(get).operationId is repeated
attribute paths.'/info/tld/{zone}'(get).operationId is repeated
```
```

### Additional context

As can be seen in this code: https://github.com/zaproxy/zap-extensions/blob/dcee0eeeb187712ca321a582c557c4fd5b13dfc0/addOns/openapi/src/main/java/org/zaproxy/zap/extension/openapi/ExtensionOpenApi.java#L237-L268

IOException is caught both the exception message and exception (stack) are logged. Perhaps change this to message at WARN and stack at DEBUG?

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
I know I kinda doubled up on the issues in the end. If you want it split in two lemme know.

**Comment by thc202** [comment]
I don't see the inclusion of the stack trace as an issue, in any case the other `IOException`s should still be handled as is.

**Comment by thc202** [comment]
Fair, but then we should do a pass through the whole codebase, we do the same (almost) everywhere.

Yes (assuming the repeated warnings are actually counted as an incomplete task).

**Comment by kingthorin** [comment]
- https://jsonformatter.org/
- https://editor.swagger.io/

<details>
<summary>Fixed def</summary>

```json
{
  "swagger": "2.0",
  "basePath": "/v1",
  "paths": {
    "/domains/search": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SearchResults"
            }
          },
          "403": {
            "description": "api_key is not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Domains Database Search",
        "operationId": "get_search_domain_item",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          },
          {
            "name": "domain",
            "in": "query",
            "type": "string",
            "description": "Domain includes"
          },
          {
            "name": "zone",
            "in": "query",
            "type": "string",
            "description": "In Zone"
          },
          {
            "name": "country",
            "in": "query",
            "type": "string",
            "description": "Hosting Country"
          },
          {
            "name": "isDead",
            "in": "query",
            "type": "boolean",
            "description": "Dead or Not, default not"
          },
          {
            "name": "A",
            "in": "query",
            "type": "string",
            "description": "A record includes"
          },
          {
            "name": "NS",
            "in": "query",
            "type": "string",
            "description": "NS record includes"
          },
          {
            "name": "CNAME",
            "in": "query",
            "type": "string",
            "description": "CNAME record includes"
          },
          {
            "name": "MX",
            "in": "query",
            "type": "string",
            "description": "MX record includes"
          },
          {
            "name": "TXT",
            "in": "query",
            "type": "string",
            "description": "TXT record includes"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/tld/{zone_id}": {
      "parameters": [
        {
          "name": "zone_id",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SearchResults"
            }
          },
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Get TLD records",
        "operationId": "get_tld_domain_item",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          },
          {
            "name": "domain",
            "in": "query",
            "type": "string",
            "description": "Domain includes"
          },
          {
            "name": "country",
            "in": "query",
            "type": "string",
            "description": "Hosting Country"
          },
          {
            "name": "isDead",
            "in": "query",
            "type": "boolean",
            "description": "Dead or Not, default not"
          },
          {
            "name": "A",
            "in": "query",
            "type": "string",
            "description": "A record includes"
          },
          {
            "name": "NS",
            "in": "query",
            "type": "string",
            "description": "NS record includes"
          },
          {
            "name": "CNAME",
            "in": "query",
            "type": "string",
            "description": "CNAME record includes"
          },
          {
            "name": "MX",
            "in": "query",
            "type": "string",
            "description": "MX record includes"
          },
          {
            "name": "TXT",
            "in": "query",
            "type": "string",
            "description": "TXT record includes"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/tld/{zone_id}/download": {
      "parameters": [
        {
          "name": "zone_id",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Download Whole Dataset for TLD",
        "operationId": "get_tld_domain_item1",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/tld/{zone_id}/search": {
      "parameters": [
        {
          "name": "zone_id",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SearchResults"
            }
          },
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Domains Search for TLD",
        "operationId": "get_search_domain_item1",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          },
          {
            "name": "domain",
            "in": "query",
            "type": "string",
            "description": "Domain includes"
          },
          {
            "name": "country",
            "in": "query",
            "type": "string",
            "description": "Hosting Country"
          },
          {
            "name": "isDead",
            "in": "query",
            "type": "boolean",
            "description": "Dead or Not, default not"
          },
          {
            "name": "A",
            "in": "query",
            "type": "string",
            "description": "A record includes"
          },
          {
            "name": "NS",
            "in": "query",
            "type": "string",
            "description": "NS record includes"
          },
          {
            "name": "CNAME",
            "in": "query",
            "type": "string",
            "description": "CNAME record includes"
          },
          {
            "name": "MX",
            "in": "query",
            "type": "string",
            "description": "MX record includes"
          },
          {
            "name": "TXT",
            "in": "query",
            "type": "string",
            "description": "TXT record includes"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/updates/added": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SearchResults"
            }
          },
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Get added domains, latest if date not specified",
        "operationId": "get_tld_domain_item2",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/updates/added/download": {
      "get": {
        "responses": {
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Download added domains, latest if date not specified",
        "operationId": "get_tld_domain_item3",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/updates/deleted": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/SearchResults"
            }
          },
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Get deleted domains, latest if date not specified",
        "operationId": "get_tld_domain_item4",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          },
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/updates/deleted/download": {
      "get": {
        "responses": {
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "Download deleted domains, latest if date not specified",
        "operationId": "get_tld_domain_item5",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          },
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "description": "Request date"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/domains/updates/list": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Updatemodel"
            }
          },
          "403": {
            "description": "No api_key or it's not valid"
          },
          "404": {
            "description": "Results not found"
          }
        },
        "summary": "List of updates",
        "operationId": "get_tld_domain_item6",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          }
        ],
        "tags": [
          "domains/"
        ]
      }
    },
    "/info/api": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/APIKeyInfo"
            }
          }
        },
        "operationId": "get_api_info_item",
        "parameters": [
          {
            "name": "api_key",
            "in": "query",
            "type": "string",
            "description": "API key"
          }
        ],
        "tags": [
          "info/"
        ]
      }
    },
    "/info/stat/": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Zonestats"
              }
            }
          }
        },
        "summary": "Returns overall stagtistics",
        "operationId": "get_statistics_collection",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          }
        ],
        "tags": [
          "info/"
        ]
      }
    },
    "/info/stat/{zone}": {
      "parameters": [
        {
          "name": "zone",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Zonestats"
            }
          },
          "404": {
            "description": "Zone not found."
          }
        },
        "summary": "Returns statistics for specific zone",
        "operationId": "get_statistics_item",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          }
        ],
        "tags": [
          "info/"
        ]
      }
    },
    "/info/tld/": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Zoneinfo"
              }
            }
          }
        },
        "summary": "Returns overall Tld info",
        "operationId": "get_statistics_collection1",
        "tags": [
          "info/"
        ]
      }
    },
    "/info/tld/{zone}": {
      "parameters": [
        {
          "name": "zone",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Zoneinfo"
            }
          },
          "404": {
            "description": "Zone not found."
          }
        },
        "summary": "Returns statistics for specific zone",
        "operationId": "get_statistics_item3",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "type": "string",
            "description": "Search page to request"
          },
          {
            "name": "limit",
            "in": "query",
            "type": "integer",
            "description": "Results per page",
            "default": 50
          }
        ],
        "tags": [
          "info/"
        ]
      }
    }
  },
  "info": {
    "title": "Domains-Index API",
    "version": "1.0",
    "description": "Domains-Index database powered API"
  },
  "produces": [
    "application/json"
  ],
  "consumes": [
    "application/json"
  ],
  "tags": [
    {
      "name": "default",
      "description": "Default namespace"
    },
    {
      "name": "info/",
      "description": "TLD Statistics"
    },
    {
      "name": "domains/",
      "description": "Domains Database"
    }
  ],
  "definitions": {
    "Zonestats": {
      "allOf": [
        {
          "$ref": "#/definitions/ResponseParameters"
        },
        {
          "properties": {
            "statistics": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Zonestats"
              }
            }
          },
          "type": "object"
        }
      ]
    },
    "ResponseParameters": {
      "required": [
        "time"
      ],
      "properties": {
        "total": {
          "type": "integer",
          "description": "Total days reported"
        },
        "time": {
          "type": "string",
          "description": "Time took"
        },
        "next_page": {
          "type": "string",
          "description": "Next page id"
        }
      },
      "type": "object"
    },
    "Zonestatistics": {
      "required": [
        "date",
        "dec",
        "inc",
        "total",
        "zone"
      ],
      "properties": {
        "zone": {
          "type": "string",
          "description": "TLD name"
        },
        "date": {
          "type": "string",
          "format": "date-time",
          "description": "Report Date"
        },
        "dec": {
          "type": "integer",
          "description": "Increase"
        },
        "inc": {
          "type": "integer",
          "description": "Decrease"
        },
        "total": {
          "type": "integer",
          "description": "Total number of records"
        }
      },
      "type": "object"
    },
    "Zoneinfo": {
      "required": [
        "type",
        "zone"
      ],
      "properties": {
        "zone": {
          "type": "string",
          "description": "TLD name"
        },
        "type": {
          "type": "string",
          "description": "TLD type"
        },
        "includes": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "Sub TLDs included"
          }
        },
        "in_bundles": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "Sub TLDs included"
          }
        },
        "description": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "Sub TLDs included"
          }
        }
      },
      "type": "object"
    },
    "APIKeyInfo": {
      "properties": {
        "success": {
          "type": "string",
          "description": "State"
        },
        "license": {
          "type": "string",
          "description": "State"
        },
        "item_id": {
          "type": "string",
          "description": "State"
        },
        "item_name": {
          "type": "string",
          "description": "State"
        },
        "expires": {
          "type": "string",
          "description": "State"
        },
        "customer_name": {
          "type": "string",
          "description": "State"
        },
        "customer_email": {
          "type": "string",
          "description": "State"
        },
        "license_limit": {
          "type": "string",
          "description": "State"
        },
        "price_id": {
          "type": "string",
          "description": "State"
        }
      },
      "type": "object"
    },
    "SearchResults": {
      "allOf": [
        {
          "$ref": "#/definitions/ResponseParameters"
        },
        {
          "properties": {
            "domains": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Domains"
              }
            }
          },
          "type": "object"
        }
      ]
    },
    "Domains": {
      "properties": {
        "domain": {
          "type": "string",
          "description": "Domain name"
        },
        "create_date": {
          "type": "string",
          "format": "date-time",
          "description": "Domain creation date"
        },
        "update_date": {
          "type": "string",
          "format": "date-time",
          "description": "Domain last update date"
        },
        "country": {
          "type": "string",
          "description": "Hosting Country"
        },
        "isDead": {
          "type": "string",
          "description": "If Domain is Dead"
        },
        "A": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "A record"
          }
        },
        "NS": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "NS record"
          }
        },
        "CNAME": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "CNAME record"
          }
        },
        "MX": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/MXrecords"
          }
        },
        "TXT": {
          "type": "array",
          "items": {
            "type": "string",
            "description": "TXT record"
          }
        }
      },
      "type": "object"
    },
    "MXrecords": {
      "properties": {
        "exchange": {
          "type": "string",
          "description": "MX domain"
        },
        "priority": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "Updatemodel": {
      "properties": {
        "date": {
          "type": "string",
          "description": "Update date"
        },
        "added": {
          "type": "string",
          "description": "Updates added list"
        },
        "added_download": {
          "type": "string",
          "description": "Download link for added"
        },
        "deleted": {
          "type": "string",
          "description": "Updates deleted list"
        },
        "deleted_download": {
          "type": "string",
          "description": "Download link for deleted"
        }
      },
      "type": "object"
    }
  },
  "responses": {
    "ParseError": {
      "description": "When a mask can't be parsed"
    },
    "MaskError": {
      "description": "When any error occurs on mask"
    }
  }
}
```

</details>

**Comment by kingthorin** [comment]
The original definition is no longer available.
The site now requires logging in with Google to get an API key.
IIRC in the "fixed" definition I simply appended numbers to the repeated operationIDs.
