### ISSUE TITLE
Zap SSE extension crashes if "id" field of SSE-message is empty

### ISSUE THREAD

**Issue by micvm** [zaproxy/zaproxy#8320]
### Describe the bug

When using the SSE ZAP extension and processing an SSE EventStream that does have an empty "id" (or any other) field, the Extension crashed with:

```
3025050 [ZAP-SSE-Listener] WARN  org.zaproxy.zap.extension.sse.EventStreamListener - An exception occurred while reading Server-Sent Events: String index out of range: 3
java.lang.StringIndexOutOfBoundsException: String index out of range: 3
	at java.lang.StringLatin1.charAt(StringLatin1.java:47) ~[?:?]
	at java.lang.String.charAt(String.java:693) ~[?:?]
	at org.zaproxy.zap.extension.sse.EventStreamProxy.processEvent(EventStreamProxy.java:153) ~[sse-alpha-12.zap:?]
	at org.zaproxy.zap.extension.sse.EventStreamListener.run(EventStreamListener.java:57) [sse-alpha-12.zap:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Steps to reproduce the behavior

- Install and enable SSE ZAP extension
- Visit a web application using a SSE connection
- Make sure this application sends an SSE message with the following fields:
```
data:something
id:
event:somethingelse
```
Since `dataIndex` does not check the length, the Exception is fired.

### Expected behavior

No exception and crash, perhaps a more graceful warning about the empty field if necessary.

### Software versions

ZAP
Version: Dev Build

Installed Add-ons: [[id=alertFilters, version=19.0.0],
[id=ascanrules, version=61.0.0], [id=callhome,
version=0.11.0], [id=commonlib, version=1.21.0],
[id=coreLang, version=15.0.0], [id=database, version=0.3.0],
[id=domxss, version=18.0.0], [id=encoder, version=1.4.0],
[id=gettingStarted, version=16.0.0], [id=help,
version=17.0.0], [id=network, version=0.14.0], [id=oast,
version=0.17.0], [id=pscanrules, version=54.0.0],
[id=quickstart, version=43.0.0], [id=replacer,
version=16.0.0], [id=reports, version=0.28.0], [id=retire,
version=0.29.0], [id=reveal, version=7.0.0], [id=scripts,
version=44.0.0], [id=selenium, version=15.17.0], [id=spider,
version=0.8.0], [id=spiderAjax, version=23.18.0], [id=sse,
version=12.0.0], [id=webdriverlinux, version=70.0.0],
[id=websocket, version=30.0.0]]

Operating System: Linux
Architecture: amd64
CPU Cores: 8
Max Memory: 9 GB
Java Version: Ubuntu 11.0.21
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Home Directory: /home/user/.ZAP_D/
ZAP Installation Directory: /home/user/git/zaproxy/zap/src/main/dist/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [X] Yes

**Comment by kingthorin** [comment]
So ZAP actually exited? Hence "crash"?

**Comment by thc202** [comment]
No.

**Comment by kingthorin** [comment]
😏

**Comment by micvm** [comment]
Sorry for not specifying: I did not mean the entire ZAP. Only the extension.

**Comment by thc202** [comment]
The extension is not crashing either, the exception is being handled.

**Comment by micvm** [comment]
> The extension is not crashing either, the exception is being handled.

Ok. But the current message is not being processed anymore and the processing of the packet stops without any notification on the frontend. Is this the expected behavior?

**Comment by thc202** [comment]
Yes, it's the expected behaviour when an exception occurs. Is it the best behaviour? Not really, and something that can be improved along the better id handling.

**Comment by thc202** [comment]
Sounds good.

**Comment by micvm** [comment]
This works for me in `EventStreamProxy.java`:
```java
if (dataIndex > line.length() && line.charAt(dataIndex) == ' ') {
      // do not include first whitespace
      dataIndex++;
}
```

**Comment by kingthorin** [comment]
I think I must be missing something here but if the index is beyond the length of the line how can the character be a space?

**Comment by micvm** [comment]
Thanks for pointing that out! The other way around:

```java
if (dataIndex < line.length() && line.charAt(dataIndex) == ' ') {
      // do not include first whitespace
      dataIndex++;
}
```
If `dataIndex` is the same or bigger than line-length, `charAt` goes out of bounds (which we want to prevent).

Regarding the equals, I believe the current code should be fine because of being a primitive type comparison.

**Comment by thc202** [comment]
@micvm do you plan to raise a PR?

**Comment by micvm** [comment]
Actually no, but I can make one, no problem.

**Comment by kingthorin** [comment]
Is this fixed as of the PR being merged and add-on released?

**Comment by thc202** [comment]
This is still pending https://github.com/zaproxy/zaproxy/issues/8320#issuecomment-1908276825
