### ISSUE TITLE
cannot close message box "failed to start Chrome browser" (Chrome is installed)

### ISSUE THREAD

**Issue by Adi-18** [zaproxy/zaproxy#8328]
### Describe the bug

After scan I cannot close message box "failed to start Chrome browser"
Chrome is installed and startet successfully.

![image](https://github.com/zaproxy/zaproxy/assets/29123730/fab1ed8c-4a1e-4792-a396-26c7d533e95d)

### Steps to reproduce the behavior

1. Use Automated scan
2.  Use ajaxspider with Chrome
3. start scan and wait
4. Try to close message box

### Expected behavior

Close the box

### Software versions

Version: 2.14.0

### Errors from the zap.log file

2024-02-06 09:10:49,262 [pool-6-thread-20] WARN  WebDriverBackedEmbeddedBrowser - Could not get the dom
org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=121.0.6167.140)
Build info: version: '4.17.0', revision: 'e52b1be057*'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [4dffb6ea0cb483fc8cdb7dea16e65791, getPageSource {}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 121.0.6167.140, chrome: {chromedriverVersion: 121.0.6167.85 (3f98d690ad7e..., userDataDir: C:\Users\ame\AppData\Local\...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:62673}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(manual, http=127.0.0...., se:cdp: ws://localhost:62673/devtoo..., se:cdpVersion: 121.0.6167.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 4dffb6ea0cb483fc8cdb7dea16e65791
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:185) ~[?:?]
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:134) ~[?:?]
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:51) ~[?:?]
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216) ~[?:?]
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:592) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:596) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.getPageSource(RemoteWebDriver.java:382) ~[?:?]
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getDomTreeWithFrames(WebDriverBackedEmbeddedBrowser.java:618) ~[?:?]
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getStrippedDom(WebDriverBackedEmbeddedBrowser.java:394) ~[?:?]
	at com.crawljax.util.ElementResolver.resolve(ElementResolver.java:55) ~[?:?]
	at com.crawljax.util.ElementResolver.resolve(ElementResolver.java:43) ~[?:?]
	at com.crawljax.core.Crawler.resolveByXpath(Crawler.java:273) ~[?:?]
	at com.crawljax.core.Crawler.fireEvent(Crawler.java:228) ~[?:?]
	at com.crawljax.core.Crawler.tryToFireEvent(Crawler.java:184) ~[?:?]
	at com.crawljax.core.Crawler.follow(Crawler.java:155) ~[?:?]
	at com.crawljax.core.Crawler.execute(Crawler.java:128) ~[?:?]
	at com.crawljax.core.CrawlTaskConsumer.handleTask(CrawlTaskConsumer.java:79) ~[?:?]
	at com.crawljax.core.CrawlTaskConsumer.pollAndHandleCrawlTasks(CrawlTaskConsumer.java:71) ~[?:?]
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:47) ~[?:?]
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]

### Would you like to help fix this issue?

- [ ] Yes

**Comment by thc202** [comment]
It's not clear why you can't close it, not focusable?

**Comment by Adi-18** [comment]
Yes its focusable and I also can move the message box around the screen.
When I klickend to X its flashed, but no action.
No reaction when clicking on OK
