### ISSUE TITLE
Fail to generate pdf report dues to SAXParseException

### ISSUE THREAD

**Issue by psiinon** [zaproxy/zaproxy#8330]
### Describe the bug

Several users have raised this problem.
The pdf report is not generated and a stack trace is shown in the logs starting with
```
org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TrAX transformer). org.xml.sax.SAXParseException; lineNumber: 129; columnNumber: 32; An invalid XML character (Unicode: 0x0) was found in the element content of the document.
```

### Steps to reproduce the behavior

This has been reproduced in a unit test by adding a "\0000" character to the following fields:

- Report description
- Report sites URL

All of the other fields tested so far have coped with this, but there may be other instances.

### Expected behavior

The pdf report should be generated no matter which "illegal" characters are present in any of the fields.

### Software versions

Latest

### Would you like to help fix this issue?

- [X] Yes

**Comment by psiinon** [comment]
Other instances reported:

https://groups.google.com/g/zaproxy-users/c/zDxr-gXZIJU/m/bZ7BKYBgAgAJ?utm_medium=email&utm_source=footer

2024-02-07 10:09:26,749 [AWT-EventQueue-0] ERROR ReportDialog - Failed to generate a report using template org.zaproxy.addon.reports.Template@9724a73
org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TrAX transformer). org.xml.sax.SAXParseException; lineNumber: 2039; columnNumber: 27; An invalid XML character (Unicode: 0x13) was found in the element content of the document.

https://groups.google.com/g/zaproxy-users/c/IFaAzCdhb8g/m/y_QHthqpDQAJ?utm_medium=email&utm_source=footer

**Comment by kingthorin** [comment]
In cases where XML is used should we be wrapping content in CDATA blocks?

**Comment by asangeethada** [comment]
Hello, 

I am still seeing this error on report-generator v0.30.  is there anything I can do? 

Thanks

**Comment by thc202** [comment]
Can you share the exception message?

**Comment by asangeethada** [comment]
"Failed to generate report: Can't load the XML resource (using TrAX transformer) org.xml.sax.SAXParseException; lineNumber 4880; columnNumber:37. An invalid XML character (Unicode: 0x11) was found in the element content of the document."

The lineNumbers and character value changes depending on scan, but the report does not get generated 

I am on a Mac, on ZAP 2.14.0, I tried reinstalling the add-on, but issue is still persistent. 

Thanks,

**Comment by asangeethada** [comment]
Stack trace from log file for recent report generation attempt : 

`2024-03-21 10:55:36,670 [AWT-EventQueue-0] ERROR ReportDialog - Failed to generate a report using template Traditional PDF Report
org.xhtmlrenderer.util.XRRuntimeException: Can't load the XML resource (using TrAX transformer). org.xml.sax.SAXParseException; lineNumber: 4880; columnNumber: 37; An invalid XML character (Unicode: 0x11) was found in the element content of the document.
	at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.transform(XMLResource.java:220) ~[reports-release-0.30.0.zap:?]
	at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.createXMLResource(XMLResource.java:179) ~[reports-release-0.30.0.zap:?]
	at org.xhtmlrenderer.resource.XMLResource.load(XMLResource.java:80) ~[reports-release-0.30.0.zap:?]
	at org.xhtmlrenderer.swing.NaiveUserAgent.getXMLResource(NaiveUserAgent.java:295) ~[reports-release-0.30.0.zap:?]
	at org.xhtmlrenderer.pdf.ITextRenderer.loadDocument(ITextRenderer.java:160) ~[reports-release-0.30.0.zap:?]
	at org.xhtmlrenderer.pdf.ITextRenderer.setDocument(ITextRenderer.java:174) ~[reports-release-0.30.0.zap:?]
	at org.zaproxy.addon.reports.ExtensionReports.generateReport(ExtensionReports.java:449) ~[reports-release-0.30.0.zap:?]
	at org.zaproxy.addon.reports.ReportDialog.save(ReportDialog.java:502) [reports-release-0.30.0.zap:?]
	at org.zaproxy.zap.view.StandardFieldsDialog.savePressed(StandardFieldsDialog.java:428) [zap-2.14.0.jar:2.14.0]
	at org.zaproxy.zap.view.StandardFieldsDialog$3.actionPerformed(StandardFieldsDialog.java:411) [zap-2.14.0.jar:2.14.0]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:?]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:?]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:?]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:?]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [?:?]
	at java.awt.Component.processMouseEvent(Unknown Source) [?:?]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:?]
	at java.awt.Component.processEvent(Unknown Source) [?:?]
	at java.awt.Container.processEvent(Unknown Source) [?:?]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:?]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:?]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:?]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:?]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:?]
	at java.awt.EventQueue$4.run(Unknown Source) [?:?]
	at java.awt.EventQueue$4.run(Unknown Source) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue$5.run(Unknown Source) [?:?]
	at java.awt.EventQueue$5.run(Unknown Source) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
Caused by: javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 4880; columnNumber: 37; An invalid XML character (Unicode: 0x11) was found in the element content of the document.
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source) ~[?:?]
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source) ~[?:?]
	at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.transform(XMLResource.java:218) ~[reports-release-0.30.0.zap:?]
	... 44 more
Caused by: org.xml.sax.SAXParseException: An invalid XML character (Unicode: 0x11) was found in the element content of the document.
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(Unknown Source) ~[?:?]
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source) ~[?:?]
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(Unknown Source) ~[?:?]
	at org.xhtmlrenderer.resource.XMLResource$XMLResourceBuilder.transform(XMLResource.java:218) ~[reports-release-0.30.0.zap:?]
	... 44 more`

**Comment by thc202** [comment]
Thank you.
