### ISSUE TITLE
ZAP 2.14 is not working with Oracle JDK 17 or 21, or with microsoft-openJDK11 but it is working fine with Oracle JDK 11

### ISSUE THREAD

**Issue by shravyakusuma09** [zaproxy/zaproxy#8334]
### Describe the bug

ZAP 2.14 is not working with Oracle JDK 17 or 21, or with microsoft-openJDK11 but it is working fine with Oracle JDK 11

### Steps to reproduce the behavior

1. Install ZAP 2.14.
2. Start ZAP.
3. Run functional tests using nightwatch config with ZAP
4. Failing to run with error: 
502 Bad Gateway
ZAP Error [org.apache.hc.client5.http.HttpHostConnectException]: Connect to https://spnapi2.ingr.com:443 [spnapi2.ingr.com/10.145.130.24, spnapi2.ingr.com/0:0:0:0:0:0:0:1] failed: Connection refused: no further information

Stack Trace:
org.apache.hc.client5.http.HttpHostConnectException: Connect to https://spnapi2.ingr.com:443 [spnapi2.ingr.com/10.145.130.24, spnapi2.ingr.com/0:0:0:0:0:0:0:1] failed: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.lambda$connectSocket$0(SSLConnectionSocketFactory.java:232)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.hc.client5.http.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:231)
	at org.zaproxy.addon.network.internal.client.apachev5.SslConnectionSocketFactory.connectSocket(SslConnectionSocketFactory.java:195)
	at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:181)
	at org.apache.hc.client5.http.impl.io.ZapHttpClientConnectionOperator.connect(ZapHttpClientConnectionOperator.java:95)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:447)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:162)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:172)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:142)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapProtocolExec.execute(ZapProtocolExec.java:178)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:81)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:481)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendRateLimited(BaseHttpSender.java:413)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:382)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:350)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:306)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:277)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:233)
	at org.parosproxy.paros.network.HttpSender.sendImpl(HttpSender.java:529)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:349)
	at org.zaproxy.addon.network.internal.server.http.handlers.HttpSenderHandler.handleMessage(HttpSenderHandler.java:78)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131)
	at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94)
	at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:842)

### Expected behavior

Should run successfully 

### Software versions

ZAP 2.14 with Oracle JDK 17

### Would you like to help fix this issue?

- [X] Yes

**Comment by thc202** [comment]
What OS?

**Comment by shravyakusuma09** [comment]
Windows 10

**Comment by thc202** [comment]
Did you give permissions for the other Java versions/JREs to access the network? That's the most likely problem.

**Comment by shravyakusuma09** [comment]
How do I ensure that the Java versions have the access to the network. Could you please help me with that.
I have added this line to the java.policy file but still seeing the same issue 
"permission java.net.SocketPermission "*", "connect, resolve";"

**Comment by thc202** [comment]
I was referring to the Windows settings, e.g.: https://support.microsoft.com/en-us/windows/risks-of-allowing-apps-through-windows-defender-firewall-654559af-3f54-3dcf-349f-71ccd90bcc5c

**Comment by shravyakusuma09** [comment]
The problem is that the API is configured for http but ZAP is using the https URL of the API. We have recently moved to ZAP 2.14 from 2.9 and in 2.9 it was using http. How do we force ZAP to use the http url? I've tried this hud.enabledForDaemon=false but it is not working.

**Comment by thc202** [comment]
Why does it only happen with other JREs? How are you running ZAP?

**Comment by shravyakusuma09** [comment]
I'm starting the ZAP through the below PowerShell script StartZap. 
[StartZap.txt](https://github.com/zaproxy/zaproxy/files/14258713/StartZap.txt)

And running the functional tests with the nightwatch config attached,
 Using the command: "nightwatch -c nightwatch.conf.js -e chrome_zap"

[nightwatch.conf.txt](https://github.com/zaproxy/zaproxy/files/14258784/nightwatch.conf.txt)

**Comment by thc202** [comment]
Are you able to reproduce this when running ZAP without proxying the tests? (i.e. launch ZAP, the browser, and access manually)

**Comment by thc202** [comment]
Great, can you use a new home (e.g. `-dir home`)? Does it still happen?

**Comment by shravyakusuma09** [comment]
Yes, I'm seeing the error even after setting a new home i.e.  
$psi.Arguments="-Xmx512m -jar `"$zapJarFile`" -dir D:\zapdir -daemon -config api.disablekey=true -newsession " +  $zapTemptemp

**Comment by guoqi1234512** [comment]
Why did I not have a quick start when installing zap2.14 for Win10
