### ISSUE TITLE
AJAX Spider - 'Namespace for prefix 'xlink' has not been declared' error when crawling

### ISSUE THREAD

**Issue by acardnell-intruder** [zaproxy/zaproxy#8410]
### Describe the bug

I'm seeing this error a lot in the logs when crawling `testphp.vulnweb.com` with the AJAX spider and Chrome.

```
ERROR:  'Namespace for prefix 'xlink' has not been declared.'
871172 [pool-2-thread-4] WARN  com.crawljax.browser.WebDriverBackedEmbeddedBrowser - Could not get the dom
com.crawljax.core.CrawljaxException: Could not tranform the DOM
        at com.crawljax.util.DomUtils.getDocumentToString(DomUtils.java:253) ~[spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getStrippedDom(WebDriverBackedEmbeddedBrowser.java:394) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.forms.FormHandler.getFormInputs(FormHandler.java:164) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.Crawler.handleInputElements(Crawler.java:209) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.Crawler.follow(Crawler.java:154) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.Crawler.execute(Crawler.java:128) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.CrawlTaskConsumer.handleTask(CrawlTaskConsumer.java:79) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.CrawlTaskConsumer.pollAndHandleCrawlTasks(CrawlTaskConsumer.java:71) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:47) [spiderAjax-release-23.18.0.zap:?]
        at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16) [spiderAjax-release-23.18.0.zap:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: javax.xml.transform.TransformerException: java.lang.RuntimeException: Namespace for prefix 'xlink' has not been declared.
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:784) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:371) ~[?:?]
        at com.crawljax.util.DomUtils.getDocumentToString(DomUtils.java:250) ~[spiderAjax-release-23.18.0.zap:?]
        ... 13 more
Caused by: java.lang.RuntimeException: Namespace for prefix 'xlink' has not been declared.
        at com.sun.org.apache.xml.internal.serializer.SerializerBase.getNamespaceURI(SerializerBase.java:784) ~[?:?]
        at com.sun.org.apache.xml.internal.serializer.SerializerBase.addAttribute(SerializerBase.java:379) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:200) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:134) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:96) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:713) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:775) ~[?:?]
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:371) ~[?:?]
        at com.crawljax.util.DomUtils.getDocumentToString(DomUtils.java:250) ~[spiderAjax-release-23.18.0.zap:?]
        ... 13 more
```

The crawler itself seems to continue though and find URLs, despite the error.

### Steps to reproduce the behavior

I'm using the [ZAP Python API](https://github.com/zaproxy/zap-api-python) and a custom Dockerfile to use Chrome that looks like this:

```
ARG ZAP_VERSION=20240304

FROM --platform=linux/amd64 softwaresecurityproject/zap-stable:${ZAP_VERSION}

ARG CHROME_VERSION=122.0.6261.94-1

USER root

RUN apt-get update && \
    wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb && \
    apt-get install -y ./google-chrome-stable_${CHROME_VERSION}_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

USER zap
```

However, I've confirmed this is happening with Firefox as well.

### Expected behavior

I'm unsure whether this is an issue or just a normal part of scanning but I don't remember seeing this error before - I tested and can confirm I'm seeing this with Firefox as well. The fact it flags it as an `ERROR` suggested it isn't expected behaviour.

### Software versions

ZAP Docker version: 20240304
ZAP Python API version: 0.1.0

### Would you like to help fix this issue?

- [ ] Yes

**Comment by CaliforniaMountainSnake** [comment]
Same problem here...

```
2025-09-04 10:31:09,478 [ZAP-AjaxSpiderApi] WARN  WebDriverBackedEmbeddedBrowser - Could not get the dom
com.crawljax.core.CrawljaxException: Could not tranform the DOM
	at com.crawljax.util.DomUtils.getDocumentToString(DomUtils.java:253) ~[spiderAjax-release-23.26.0.zap:?]
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.getStrippedDom(WebDriverBackedEmbeddedBrowser.java:394) [spiderAjax-release-23.26.0.zap:?]
	at com.crawljax.core.Crawler.crawlIndex(Crawler.java:452) [spiderAjax-release-23.26.0.zap:?]
	at com.crawljax.core.CrawlTaskConsumer.crawlIndex(CrawlTaskConsumer.java:89) [spiderAjax-release-23.26.0.zap:?]
	at com.crawljax.core.CrawlController.call(CrawlController.java:67) [spiderAjax-release-23.26.0.zap:?]
	at com.crawljax.core.CrawljaxRunner.call(CrawljaxRunner.java:37) [spiderAjax-release-23.26.0.zap:?]
	at org.zaproxy.zap.extension.spiderAjax.SpiderThread.run(SpiderThread.java:362) [spiderAjax-release-23.26.0.zap:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: javax.xml.transform.TransformerException: java.lang.RuntimeException: Namespace for prefix 'xlink' has not been declared.
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:789) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:395) ~[?:?]
	at com.crawljax.util.DomUtils.getDocumentToString(DomUtils.java:250) ~[spiderAjax-release-23.26.0.zap:?]
	... 7 more
Caused by: java.lang.RuntimeException: Namespace for prefix 'xlink' has not been declared.
	at java.xml/com.sun.org.apache.xml.internal.serializer.SerializerBase.getNamespaceURI(SerializerBase.java:786) ~[?:?]
	at java.xml/com.sun.org.apache.xml.internal.serializer.SerializerBase.addAttribute(SerializerBase.java:381) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:200) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:229) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:134) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:96) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:718) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:780) ~[?:?]
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:395) ~[?:?]
	at com.crawljax.util.DomUtils.getDocumentToString(DomUtils.java:250) ~[spiderAjax-release-23.26.0.zap:?]
	... 7 more
```

Zap init log:
```
2025-09-04 10:28:39,397 [main ] INFO  DaemonBootstrap - ZAP 2.16.1 started 04/09/2025, 10:28:39 with home: /home/zap/.ZAP/ cores: 12 maxMemory: 3 GB
2025-09-04 10:28:39,416 [main ] INFO  AbstractParam - Setting config database.recoverylog = false was null
2025-09-04 10:28:39,417 [main ] INFO  AbstractParam - Setting config api.disablekey = true was null
2025-09-04 10:28:39,417 [main ] INFO  AbstractParam - Setting config api.addrs.addr.name = .* was null
2025-09-04 10:28:39,417 [main ] INFO  AbstractParam - Setting config api.addrs.addr.regex = true was null
2025-09-04 10:28:39,417 [main ] INFO  AbstractParam - Setting config spider.maxDuration = 0 was null
2025-09-04 10:28:39,417 [main ] INFO  AbstractParam - Setting config scanner.maxScanDurationInMins = 10 was null
2025-09-04 10:28:39,417 [main ] INFO  AbstractParam - Setting config scanner.threadPerHost = 24 was null
2025-09-04 10:28:40,583 [ZAP-daemon] INFO  ExtensionFactory - Installed add-ons: [[id=alertFilters, version=24.0.0], [id=ascanrules, version=73.0.0], [id=authhelper, version=0.28.0], [id=automation, version=0.52.0], [id=bruteforce, version=18.0.0], [id=callhome, version=0.15.0], [id=client, version=0.17.0], [id=commonlib, version=1.35.0], [id=database, version=0.8.0], [id=diff, version=17.0.0], [id=directorylistv1, version=9.0.0], [id=domxss, version=22.0.0], [id=encoder, version=1.7.0], [id=exim, version=0.15.0], [id=formhandler, version=6.7.0], [id=fuzz, version=13.16.0], [id=gettingStarted, version=19.0.0], [id=graaljs, version=0.9.0], [id=graphql, version=0.28.0], [id=help, version=21.0.0], [id=hud, version=0.19.0], [id=invoke, version=16.0.0], [id=network, version=0.23.0], [id=oast, version=0.22.0], [id=onlineMenu, version=14.0.0], [id=openapi, version=45.0.0], [id=postman, version=0.7.0], [id=pscan, version=0.4.0], [id=pscanrules, version=66.0.0], [id=pscanrulesBeta, version=44.0.0], [id=quickstart, version=52.0.0], [id=replacer, version=20.0.0], [id=reports, version=0.40.0], [id=requester, version=7.8.0], [id=retest, version=0.11.0], [id=retire, version=0.48.0], [id=reveal, version=10.0.0], [id=scanpolicies, version=0.4.0], [id=scripts, version=45.13.0], [id=selenium, version=15.40.0], [id=sequence, version=8.0.0], [id=soap, version=26.0.0], [id=spider, version=0.16.0], [id=spiderAjax, version=23.26.0], [id=tips, version=14.0.0], [id=webdriverlinux, version=155.0.0], [id=websocket, version=33.0.0], [id=zest, version=48.9.0]]
2025-09-04 10:28:40,584 [ZAP-daemon] INFO  ExtensionFactory - Loading extensions
2025-09-04 10:28:40,986 [ZAP-daemon] INFO  TlsUtils - Using supported SSL/TLS protocols: [TLSv1.2, TLSv1.3]
2025-09-04 10:28:41,171 [ZAP-daemon] INFO  ExtensionFactory - Extensions loaded
```

**Comment by psiinon** [comment]
Closing as we are now focussing on the Client Spider.
If this issue still occurs with the Client Spider then please raise a new issue.
