### ISSUE TITLE
429 and 503 responses with long "retry-after" causes scans to hang

### ISSUE THREAD

**Issue by FiveOFive** [zaproxy/zaproxy#8627]
### Describe the bug

When a website returns a 429 or 503 response with the "retry-after" header set, the DefaultHttpRequestRetry class tries to honor the returned time interval - https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/impl/DefaultHttpRequestRetryStrategy.java#L206

However, this can cause ZAP threads to wait a really long time, for example if the "retry-after" time is an hour. Even small retry times can add up to long delays over a full scan. From the user perspective the scan is stuck and it's not clear why. I couldn't find a way to check this problem via the UI or APIs. It seems that because the http request is still being retried it isn't added to the history logs or result apis yet. The only way I saw to tell what is going on was to enable debug logging on the http client in log4j2.properties and check the ZAP logs.

I've reproduced this in several different places within ZAP: spider, the active scan analyser, active scan rules, the quick start attack thread.

### Steps to reproduce the behavior

1. Set up a test endpoint locally that always returns a 503 with the "retry-after" header set to a large value. Here's the code for an example node and express js app that does this:

```
import express from 'express';

const app = express();
const PORT = 3050;

app.get('/', (_req, res) => {
  res.setHeader('retry-after', 3600);
  res.status(503).send(`<html><body>This website always returns a 503 with the "retry-after" header set.</body></html>`);
});

app.listen(PORT, () => {
  console.log(`Listening on port ${PORT}`);
});
```

2. Go to the ZAP UI and run an quick start "Automated Scan" of your endpoint. You can also set up a context and start the passive or active scanner to trigger the issue in different places of the ZAP code.
3. The attack button will be disabled and the stop button enabled and progress is stuck at "Accessing URL"

Stuck after starting a quick start:
![Stuck after starting a quick start](https://github.com/user-attachments/assets/e15822fb-aaa8-440f-9858-e90e3cdc0b3a)

Stuck after setting up a context and starting the spider:
![Stuck after starting a spider](https://github.com/user-attachments/assets/9eb19051-4220-4fb4-a900-c131624ce3b3)

Thread dump showing the quick start attack thread WAITING:

```
"ZAP-QuickStart-AttackThread" #251 prio=6 os_prio=31 cpu=7.54ms elapsed=132.65s tid=0x0000000137826000 nid=0x19d9f waiting on condition  [0x0000000378339000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.23/Native Method)
	at java.lang.Thread.sleep(java.base@11.0.23/Unknown Source)
	at java.util.concurrent.TimeUnit.sleep(java.base@11.0.23/Unknown Source)
	at org.apache.hc.core5.util.TimeValue.sleep(TimeValue.java:382)
	at org.apache.hc.client5.http.impl.classic.ZapHttpRequestRetryExec.execute(ZapHttpRequestRetryExec.java:150)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ZapInternalHttpClient.doExecute(ZapInternalHttpClient.java:173)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:245)
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl0(HttpSenderApache.java:483)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:362)
	at org.zaproxy.addon.network.internal.client.apachev5.HttpSenderApache.sendImpl(HttpSenderApache.java:116)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendRateLimited(BaseHttpSender.java:413)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAuthenticated(BaseHttpSender.java:382)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendNoRedirections(BaseHttpSender.java:350)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.send(BaseHttpSender.java:306)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:277)
	at org.zaproxy.addon.network.internal.client.BaseHttpSender.sendAndReceive(BaseHttpSender.java:233)
	at org.parosproxy.paros.network.HttpSender.sendImpl(HttpSender.java:529)
	at org.parosproxy.paros.network.HttpSender.sendAndReceive(HttpSender.java:522)
	at org.zaproxy.zap.extension.quickstart.ExtensionQuickStart.accessNode(ExtensionQuickStart.java:330)
	at org.zaproxy.zap.extension.quickstart.AttackThread.run(AttackThread.java:84)
```

### Expected behavior

For me there are two issues here:
1. There should be a way via both the UI and APIs to tell that ZAP is stuck waiting from a "retry-after" response so that the user can know why the scan appears stuck and take appropriate action.
2. Configurable options for the retry strategy that could be changed to not retry these requests. These 429 and 503 responses generally happen because of a firewall or other automated detection blocking the scan. Can also happen if the site is overwhelmed and goes down. So in my opinion stopping the scan is often the "right" behavior but I could definitely see cases where maybe just one route within a site tree is returning these responses and you want to move on and keep scanning the rest of your context. That flexibility would be nice.

### Software versions

ZAP
Version: 2.15.0

Installed Add-ons: [[id=alertFilters, version=21.0.0],
[id=ascanrules, version=66.0.0], [id=authhelper,
version=0.13.0], [id=automation, version=0.40.0],
[id=bruteforce, version=16.0.0], [id=callhome,
version=0.12.0], [id=commonlib, version=1.25.0],
[id=custompayloads, version=0.13.0], [id=database,
version=0.4.0], [id=diff, version=15.0.0],
[id=directorylistv1, version=8.0.0], [id=domxss,
version=19.0.0], [id=encoder, version=1.5.0], [id=exim,
version=0.9.0], [id=formhandler, version=6.6.0], [id=fuzz,
version=13.13.0], [id=gettingStarted, version=17.0.0],
[id=graaljs, version=0.7.0], [id=graphql, version=0.24.0],
[id=help, version=18.0.0], [id=hud, version=0.19.0],
[id=importurls, version=9.0.0], [id=invoke, version=15.0.0],
[id=network, version=0.16.0], [id=oast, version=0.18.0],
[id=onlineMenu, version=13.0.0], [id=openapi,
version=40.0.0], [id=postman, version=0.4.0],
[id=pscanrules, version=58.0.0], [id=quickstart,
version=47.0.0], [id=replacer, version=17.0.0], [id=reports,
version=0.32.0], [id=requester, version=7.6.0], [id=retest,
version=0.9.0], [id=retire, version=0.35.0], [id=reveal,
version=8.0.0], [id=saverawmessage, version=7.0.0],
[id=savexmlmessage, version=0.3.0], [id=scripts,
version=45.3.0], [id=selenium, version=15.23.0], [id=soap,
version=23.0.0], [id=spider, version=0.11.0],
[id=spiderAjax, version=23.19.0], [id=tips, version=13.0.0],
[id=webdrivermacos, version=82.0.0], [id=websocket,
version=31.0.0], [id=zest, version=45.0.0]]

Operating System: Mac OS X
Architecture: aarch64
CPU Cores: 8
Max Memory: 4 GB
Java Version: Eclipse Adoptium 11.0.23
System's Locale: en_US
Display Locale: en_GB
Format Locale: en_US
Default Charset: UTF-8
ZAP Installation Directory: /Applications/ZAP.app/Contents/Java/./
Look and Feel: FlatLaf Light (com.formdev.flatlaf.FlatLightLaf)

### Would you like to help fix this issue?

- [X] Yes

**Comment by FiveOFive** [comment]
I've tested a potential fix that removes 429 and 503 from the list of status codes to retry - https://github.com/zaproxy/zap-extensions/pull/5727

This worked well in testing and in my opinion makes sense as the default behavior. Now that the requests are not stuck retrying, the ZAP UI shows good information for the 429 and 503 cases.

Here is what happens if the first request from a quick scan is a 429:

![Screenshot 2024-09-15 at 10 54 02 AM](https://github.com/user-attachments/assets/0a129f4a-13ae-42c4-b082-d78b255cc48c)

And if only some paths return a 429 or 503 it can be seen in the request/response data:

![Screenshot 2024-09-15 at 10 53 04 AM](https://github.com/user-attachments/assets/f59f93f7-479f-4d19-b473-ac52d173f18c)

Technically this would be a breaking change, but in my opinion it is much better default behavior than being stuck with no messaging. An alternative would be to keep the current default but make these network settings configurable.

**Comment by FiveOFive** [comment]
Found an older related issue reporting this same behavior for the Active scan rules - https://github.com/zaproxy/zaproxy/issues/8223 As noted in this issue, the behavior is more widespread can happen in other places besides the active scan rules
