### ISSUE TITLE
ZAP start error after reinstalling 2.15.0

### ISSUE THREAD

**Issue by fjmanalang** [zaproxy/zaproxy#8656]
Error from zap.log file

2024-09-30 13:52:10,397 [ZAP-BootstrapGUI] ERROR ExtensionLoader - Failed to initialise extension org.zaproxy.addon.oast.ExtensionOast (from add-on [id=oast, version=0.20.0]), cause: ClassNotFoundException: 
java.lang.NoClassDefFoundError: javax/jdo/JDOObjectNotFoundException
	at org.zaproxy.addon.oast.ExtensionOast.getPermanentDatabase(ExtensionOast.java:243) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast.trimDatabase(ExtensionOast.java:167) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast.postInit(ExtensionOast.java:158) ~[?:?]
	at org.parosproxy.paros.extension.ExtensionLoader.hookAllExtension(ExtensionLoader.java:1001) [zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.extension.ExtensionLoader.startLifeCycle(ExtensionLoader.java:836) [zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.AbstractControl.loadExtension(AbstractControl.java:58) [zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.Control.init(Control.java:156) [zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.Control.initSingletonWithView(Control.java:389) [zap-2.15.0.jar:2.15.0]
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:229) [zap-2.15.0.jar:2.15.0]
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:174) [zap-2.15.0.jar:2.15.0]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:330) ~[zap-2.15.0.jar:2.15.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:594) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:527) ~[?:?]
	... 11 more
2024-09-30 13:52:12,305 [AWT-EventQueue-0] INFO  Control - New Session
2024-09-30 13:52:12,317 [AWT-EventQueue-0] INFO  Control - Create and Open Untitled Db
2024-09-30 14:24:59,819 [ZAP-BootstrapGUI] FATAL GuiBootstrap - Failed to initialise GUI: 
java.lang.reflect.InvocationTargetException: null
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1367) ~[?:?]
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1342) ~[?:?]
	at org.zaproxy.zap.GuiBootstrap.initControlAndPostViewInit(GuiBootstrap.java:234) ~[zap-2.15.0.jar:2.15.0]
	at org.zaproxy.zap.GuiBootstrap$2.run(GuiBootstrap.java:174) [zap-2.15.0.jar:2.15.0]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: javax/jdo/JDOObjectNotFoundException
	at org.zaproxy.addon.oast.ExtensionOast.getPermanentDatabase(ExtensionOast.java:243) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast$OastSessionChangedListener.addRegisteredServersFromPermanentDatabase(ExtensionOast.java:454) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast$OastSessionChangedListener.sessionChanged(ExtensionOast.java:430) ~[?:?]
	at org.parosproxy.paros.extension.ExtensionLoader.sessionChangedAllPlugin(ExtensionLoader.java:567) ~[zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.Control.newSession(Control.java:509) ~[zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.MenuFileControl.newSession(MenuFileControl.java:184) ~[zap-2.15.0.jar:2.15.0]
	at org.zaproxy.zap.GuiBootstrap$3.run(GuiBootstrap.java:310) ~[zap-2.15.0.jar:2.15.0]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: java.lang.ClassNotFoundException
	at org.zaproxy.zap.control.AddOnClassLoader.findClass(AddOnClassLoader.java:330) ~[zap-2.15.0.jar:2.15.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:594) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:527) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast.getPermanentDatabase(ExtensionOast.java:243) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast$OastSessionChangedListener.addRegisteredServersFromPermanentDatabase(ExtensionOast.java:454) ~[?:?]
	at org.zaproxy.addon.oast.ExtensionOast$OastSessionChangedListener.sessionChanged(ExtensionOast.java:430) ~[?:?]
	at org.parosproxy.paros.extension.ExtensionLoader.sessionChangedAllPlugin(ExtensionLoader.java:567) ~[zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.Control.newSession(Control.java:509) ~[zap-2.15.0.jar:2.15.0]
	at org.parosproxy.paros.control.MenuFileControl.newSession(MenuFileControl.java:184) ~[zap-2.15.0.jar:2.15.0]
	at org.zaproxy.zap.GuiBootstrap$3.run(GuiBootstrap.java:310) ~[zap-2.15.0.jar:2.15.0]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]

**Comment by thc202** [comment]
Is the database add-on installed too?

**Comment by fjmanalang** [comment]
> Is the database add-on installed too?

Hmm is it a separate installation aside from the ZAP installer? 

There is a "database-alpha-0.4.0.zap" and "oast-beta-0.18.0.zap" in the plugin folder under the Zap directory.

**Comment by thc202** [comment]
No referring to that one. Did you check the add-ons in the ZAP home? (You can also check in the Manage Add-ons dialogue.)
Those are outdated.
